sampctl package ensure --update

sampctl package --bare --forceBuild --build test_0_0_0_0 y_testing
sampctl package --bare --forceBuild --build test_0_0_0_1 y_testing
sampctl package --bare --forceBuild --build test_0_0_0_2 y_testing
sampctl package --bare --forceBuild --build test_0_0_0_3 y_testing
sampctl package --bare --forceBuild --build test_0_0_1_0 y_testing
sampctl package --bare --forceBuild --build test_0_0_1_1 y_testing
sampctl package --bare --forceBuild --build test_0_0_1_2 y_testing
sampctl package --bare --forceBuild --build test_0_0_1_3 y_testing
sampctl package --bare --forceBuild --build test_0_0_2_0 y_testing
sampctl package --bare --forceBuild --build test_0_0_2_1 y_testing
sampctl package --bare --forceBuild --build test_0_0_2_2 y_testing
sampctl package --bare --forceBuild --build test_0_0_2_3 y_testing
sampctl package --bare --forceBuild --build test_0_0_3_0 y_testing
sampctl package --bare --forceBuild --build test_0_0_3_1 y_testing
sampctl package --bare --forceBuild --build test_0_0_3_2 y_testing
sampctl package --bare --forceBuild --build test_0_0_3_3 y_testing
sampctl package --bare --forceBuild --build test_0_1_0_0 y_testing
sampctl package --bare --forceBuild --build test_0_1_0_1 y_testing
sampctl package --bare --forceBuild --build test_0_1_0_2 y_testing
sampctl package --bare --forceBuild --build test_0_1_0_3 y_testing
sampctl package --bare --forceBuild --build test_0_1_1_0 y_testing
sampctl package --bare --forceBuild --build test_0_1_1_1 y_testing
sampctl package --bare --forceBuild --build test_0_1_1_2 y_testing
sampctl package --bare --forceBuild --build test_0_1_1_3 y_testing
sampctl package --bare --forceBuild --build test_0_1_2_0 y_testing
sampctl package --bare --forceBuild --build test_0_1_2_1 y_testing
sampctl package --bare --forceBuild --build test_0_1_2_2 y_testing
sampctl package --bare --forceBuild --build test_0_1_2_3 y_testing
sampctl package --bare --forceBuild --build test_0_1_3_0 y_testing
sampctl package --bare --forceBuild --build test_0_1_3_1 y_testing
sampctl package --bare --forceBuild --build test_0_1_3_2 y_testing
sampctl package --bare --forceBuild --build test_0_1_3_3 y_testing
sampctl package --bare --forceBuild --build test_0_2_0_0 y_testing
sampctl package --bare --forceBuild --build test_0_2_0_1 y_testing
sampctl package --bare --forceBuild --build test_0_2_0_2 y_testing
sampctl package --bare --forceBuild --build test_0_2_0_3 y_testing
sampctl package --bare --forceBuild --build test_0_2_1_0 y_testing
sampctl package --bare --forceBuild --build test_0_2_1_1 y_testing
sampctl package --bare --forceBuild --build test_0_2_1_2 y_testing
sampctl package --bare --forceBuild --build test_0_2_1_3 y_testing
sampctl package --bare --forceBuild --build test_0_2_2_0 y_testing
sampctl package --bare --forceBuild --build test_0_2_2_1 y_testing
sampctl package --bare --forceBuild --build test_0_2_2_2 y_testing
sampctl package --bare --forceBuild --build test_0_2_2_3 y_testing
sampctl package --bare --forceBuild --build test_0_2_3_0 y_testing
sampctl package --bare --forceBuild --build test_0_2_3_1 y_testing
sampctl package --bare --forceBuild --build test_0_2_3_2 y_testing
sampctl package --bare --forceBuild --build test_0_2_3_3 y_testing
sampctl package --bare --forceBuild --build test_1_0_0_0 y_testing
sampctl package --bare --forceBuild --build test_1_0_0_1 y_testing
sampctl package --bare --forceBuild --build test_1_0_0_2 y_testing
sampctl package --bare --forceBuild --build test_1_0_0_3 y_testing
sampctl package --bare --forceBuild --build test_1_0_1_0 y_testing
sampctl package --bare --forceBuild --build test_1_0_1_1 y_testing
sampctl package --bare --forceBuild --build test_1_0_1_2 y_testing
sampctl package --bare --forceBuild --build test_1_0_1_3 y_testing
sampctl package --bare --forceBuild --build test_1_0_2_0 y_testing
sampctl package --bare --forceBuild --build test_1_0_2_1 y_testing
sampctl package --bare --forceBuild --build test_1_0_2_2 y_testing
sampctl package --bare --forceBuild --build test_1_0_2_3 y_testing
sampctl package --bare --forceBuild --build test_1_0_3_0 y_testing
sampctl package --bare --forceBuild --build test_1_0_3_1 y_testing
sampctl package --bare --forceBuild --build test_1_0_3_2 y_testing
sampctl package --bare --forceBuild --build test_1_0_3_3 y_testing
sampctl package --bare --forceBuild --build test_1_1_0_0 y_testing
sampctl package --bare --forceBuild --build test_1_1_0_1 y_testing
sampctl package --bare --forceBuild --build test_1_1_0_2 y_testing
sampctl package --bare --forceBuild --build test_1_1_0_3 y_testing
sampctl package --bare --forceBuild --build test_1_1_1_0 y_testing
sampctl package --bare --forceBuild --build test_1_1_1_1 y_testing
sampctl package --bare --forceBuild --build test_1_1_1_2 y_testing
sampctl package --bare --forceBuild --build test_1_1_1_3 y_testing
sampctl package --bare --forceBuild --build test_1_1_2_0 y_testing
sampctl package --bare --forceBuild --build test_1_1_2_1 y_testing
sampctl package --bare --forceBuild --build test_1_1_2_2 y_testing
sampctl package --bare --forceBuild --build test_1_1_2_3 y_testing
sampctl package --bare --forceBuild --build test_1_1_3_0 y_testing
sampctl package --bare --forceBuild --build test_1_1_3_1 y_testing
sampctl package --bare --forceBuild --build test_1_1_3_2 y_testing
sampctl package --bare --forceBuild --build test_1_1_3_3 y_testing
sampctl package --bare --forceBuild --build test_1_2_0_0 y_testing
sampctl package --bare --forceBuild --build test_1_2_0_1 y_testing
sampctl package --bare --forceBuild --build test_1_2_0_2 y_testing
sampctl package --bare --forceBuild --build test_1_2_0_3 y_testing
sampctl package --bare --forceBuild --build test_1_2_1_0 y_testing
sampctl package --bare --forceBuild --build test_1_2_1_1 y_testing
sampctl package --bare --forceBuild --build test_1_2_1_2 y_testing
sampctl package --bare --forceBuild --build test_1_2_1_3 y_testing
sampctl package --bare --forceBuild --build test_1_2_2_0 y_testing
sampctl package --bare --forceBuild --build test_1_2_2_1 y_testing
sampctl package --bare --forceBuild --build test_1_2_2_2 y_testing
sampctl package --bare --forceBuild --build test_1_2_2_3 y_testing
sampctl package --bare --forceBuild --build test_1_2_3_0 y_testing
sampctl package --bare --forceBuild --build test_1_2_3_1 y_testing
sampctl package --bare --forceBuild --build test_1_2_3_2 y_testing
sampctl package --bare --forceBuild --build test_1_2_3_3 y_testing

