static stock const Y_UNIQUE_0640_0703_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_0640_0703
	#undef _inc_y_unique_0640_0703
#endif

#if UNIQUE_SYMBOL < (647)
	#if UNIQUE_SYMBOL == (639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (640)
		#define UNIQUE_FUNCTION<%0...%1> %0@0%1
		#endinput
	#elseif UNIQUE_SYMBOL == (640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (641)
		#define UNIQUE_FUNCTION<%0...%1> %0@1%1
		#endinput
	#elseif UNIQUE_SYMBOL == (641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (642)
		#define UNIQUE_FUNCTION<%0...%1> %0@2%1
		#endinput
	#elseif UNIQUE_SYMBOL == (642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (643)
		#define UNIQUE_FUNCTION<%0...%1> %0@3%1
		#endinput
	#elseif UNIQUE_SYMBOL == (643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (644)
		#define UNIQUE_FUNCTION<%0...%1> %0@4%1
		#endinput
	#elseif UNIQUE_SYMBOL == (644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (645)
		#define UNIQUE_FUNCTION<%0...%1> %0@5%1
		#endinput
	#elseif UNIQUE_SYMBOL == (645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (646)
		#define UNIQUE_FUNCTION<%0...%1> %0@6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (647)
		#define UNIQUE_FUNCTION<%0...%1> %0@7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (655)
	#if UNIQUE_SYMBOL == (647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (648)
		#define UNIQUE_FUNCTION<%0...%1> %0@8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (649)
		#define UNIQUE_FUNCTION<%0...%1> %0@9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (650)
		#define UNIQUE_FUNCTION<%0...%1> %0@@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (651)
		#define UNIQUE_FUNCTION<%0...%1> %0@A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (652)
		#define UNIQUE_FUNCTION<%0...%1> %0@B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (653)
		#define UNIQUE_FUNCTION<%0...%1> %0@C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (654)
		#define UNIQUE_FUNCTION<%0...%1> %0@D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (655)
		#define UNIQUE_FUNCTION<%0...%1> %0@E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (663)
	#if UNIQUE_SYMBOL == (655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (656)
		#define UNIQUE_FUNCTION<%0...%1> %0@F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (657)
		#define UNIQUE_FUNCTION<%0...%1> %0@G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (658)
		#define UNIQUE_FUNCTION<%0...%1> %0@H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (659)
		#define UNIQUE_FUNCTION<%0...%1> %0@I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (660)
		#define UNIQUE_FUNCTION<%0...%1> %0@J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (661)
		#define UNIQUE_FUNCTION<%0...%1> %0@K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (662)
		#define UNIQUE_FUNCTION<%0...%1> %0@L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (663)
		#define UNIQUE_FUNCTION<%0...%1> %0@M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (671)
	#if UNIQUE_SYMBOL == (663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (664)
		#define UNIQUE_FUNCTION<%0...%1> %0@N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (665)
		#define UNIQUE_FUNCTION<%0...%1> %0@O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (666)
		#define UNIQUE_FUNCTION<%0...%1> %0@P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (667)
		#define UNIQUE_FUNCTION<%0...%1> %0@Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (668)
		#define UNIQUE_FUNCTION<%0...%1> %0@R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (669)
		#define UNIQUE_FUNCTION<%0...%1> %0@S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (670)
		#define UNIQUE_FUNCTION<%0...%1> %0@T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (671)
		#define UNIQUE_FUNCTION<%0...%1> %0@U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (679)
	#if UNIQUE_SYMBOL == (671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (672)
		#define UNIQUE_FUNCTION<%0...%1> %0@V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (673)
		#define UNIQUE_FUNCTION<%0...%1> %0@W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (674)
		#define UNIQUE_FUNCTION<%0...%1> %0@X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (675)
		#define UNIQUE_FUNCTION<%0...%1> %0@Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (676)
		#define UNIQUE_FUNCTION<%0...%1> %0@Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (677)
		#define UNIQUE_FUNCTION<%0...%1> %0@_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (678)
		#define UNIQUE_FUNCTION<%0...%1> %0@a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (679)
		#define UNIQUE_FUNCTION<%0...%1> %0@b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (687)
	#if UNIQUE_SYMBOL == (679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (680)
		#define UNIQUE_FUNCTION<%0...%1> %0@c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (681)
		#define UNIQUE_FUNCTION<%0...%1> %0@d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (682)
		#define UNIQUE_FUNCTION<%0...%1> %0@e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (683)
		#define UNIQUE_FUNCTION<%0...%1> %0@f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (684)
		#define UNIQUE_FUNCTION<%0...%1> %0@g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (685)
		#define UNIQUE_FUNCTION<%0...%1> %0@h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (686)
		#define UNIQUE_FUNCTION<%0...%1> %0@i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (687)
		#define UNIQUE_FUNCTION<%0...%1> %0@j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (695)
	#if UNIQUE_SYMBOL == (687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (688)
		#define UNIQUE_FUNCTION<%0...%1> %0@k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (689)
		#define UNIQUE_FUNCTION<%0...%1> %0@l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (690)
		#define UNIQUE_FUNCTION<%0...%1> %0@m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (691)
		#define UNIQUE_FUNCTION<%0...%1> %0@n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (692)
		#define UNIQUE_FUNCTION<%0...%1> %0@o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (693)
		#define UNIQUE_FUNCTION<%0...%1> %0@p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (694)
		#define UNIQUE_FUNCTION<%0...%1> %0@q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (695)
		#define UNIQUE_FUNCTION<%0...%1> %0@r%1
		#endinput
	#endif
#else
	#if UNIQUE_SYMBOL == (695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (696)
		#define UNIQUE_FUNCTION<%0...%1> %0@s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (697)
		#define UNIQUE_FUNCTION<%0...%1> %0@t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (698)
		#define UNIQUE_FUNCTION<%0...%1> %0@u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (699)
		#define UNIQUE_FUNCTION<%0...%1> %0@v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (700)
		#define UNIQUE_FUNCTION<%0...%1> %0@w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (701)
		#define UNIQUE_FUNCTION<%0...%1> %0@x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (702)
		#define UNIQUE_FUNCTION<%0...%1> %0@y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (703)
		#define UNIQUE_FUNCTION<%0...%1> %0@z%1
		#endinput
	#endif
#endif

