
// Like `char`, so `4 char == 1`, `4 __cell == 16`.
#define __cell *cellbytes

const __frame_address = 0 __cell;
const __return_address = 1 __cell;
const __parameter_count = 2 __cell;
const __first_parameter = 3 __cell;
const __def_size = 2 __cell;

const __1_cell = 1 __cell;
const __2_cells = 2 __cell;
const __3_cells = 3 __cell;
const __4_cells = 4 __cell;
const __5_cells = 5 __cell;
const __6_cells = 6 __cell;
const __7_cells = 7 __cell;
const __8_cells = 8 __cell;
const __9_cells = 9 __cell;
const __10_cells = 10 __cell;
const __11_cells = 11 __cell;
const __12_cells = 12 __cell;
const __13_cells = 13 __cell;
const __14_cells = 14 __cell;
const __15_cells = 15 __cell;
const __16_cells = 16 __cell;
const __17_cells = 17 __cell;
const __18_cells = 18 __cell;
const __19_cells = 19 __cell;
const __20_cells = 20 __cell;

