static stock const Y_UNIQUE_216704_216767_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_216704_216767
	#undef _inc_y_unique_216704_216767
#endif

#if UNIQUE_SYMBOL < (216711)
	#if UNIQUE_SYMBOL == (216703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216704)
		#define UNIQUE_FUNCTION<%0...%1> %0ou0%1
		#endinput
	#if UNIQUE_SYMBOL == (216704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216705)
		#define UNIQUE_FUNCTION<%0...%1> %0ou1%1
		#endinput
	#if UNIQUE_SYMBOL == (216705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216706)
		#define UNIQUE_FUNCTION<%0...%1> %0ou2%1
		#endinput
	#if UNIQUE_SYMBOL == (216706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216707)
		#define UNIQUE_FUNCTION<%0...%1> %0ou3%1
		#endinput
	#if UNIQUE_SYMBOL == (216707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216708)
		#define UNIQUE_FUNCTION<%0...%1> %0ou4%1
		#endinput
	#if UNIQUE_SYMBOL == (216708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216709)
		#define UNIQUE_FUNCTION<%0...%1> %0ou5%1
		#endinput
	#if UNIQUE_SYMBOL == (216709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216710)
		#define UNIQUE_FUNCTION<%0...%1> %0ou6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216711)
		#define UNIQUE_FUNCTION<%0...%1> %0ou7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (216719)
	#elseif UNIQUE_SYMBOL == (216711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216712)
		#define UNIQUE_FUNCTION<%0...%1> %0ou8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216713)
		#define UNIQUE_FUNCTION<%0...%1> %0ou9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216714)
		#define UNIQUE_FUNCTION<%0...%1> %0ou@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216715)
		#define UNIQUE_FUNCTION<%0...%1> %0ouA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216716)
		#define UNIQUE_FUNCTION<%0...%1> %0ouB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216717)
		#define UNIQUE_FUNCTION<%0...%1> %0ouC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216718)
		#define UNIQUE_FUNCTION<%0...%1> %0ouD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216719)
		#define UNIQUE_FUNCTION<%0...%1> %0ouE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (216727)
	#elseif UNIQUE_SYMBOL == (216719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216720)
		#define UNIQUE_FUNCTION<%0...%1> %0ouF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216721)
		#define UNIQUE_FUNCTION<%0...%1> %0ouG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216722)
		#define UNIQUE_FUNCTION<%0...%1> %0ouH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216723)
		#define UNIQUE_FUNCTION<%0...%1> %0ouI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216724)
		#define UNIQUE_FUNCTION<%0...%1> %0ouJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216725)
		#define UNIQUE_FUNCTION<%0...%1> %0ouK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216726)
		#define UNIQUE_FUNCTION<%0...%1> %0ouL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216727)
		#define UNIQUE_FUNCTION<%0...%1> %0ouM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (216735)
	#elseif UNIQUE_SYMBOL == (216727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216728)
		#define UNIQUE_FUNCTION<%0...%1> %0ouN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216729)
		#define UNIQUE_FUNCTION<%0...%1> %0ouO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216730)
		#define UNIQUE_FUNCTION<%0...%1> %0ouP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216731)
		#define UNIQUE_FUNCTION<%0...%1> %0ouQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216732)
		#define UNIQUE_FUNCTION<%0...%1> %0ouR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216733)
		#define UNIQUE_FUNCTION<%0...%1> %0ouS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216734)
		#define UNIQUE_FUNCTION<%0...%1> %0ouT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216735)
		#define UNIQUE_FUNCTION<%0...%1> %0ouU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (216743)
	#elseif UNIQUE_SYMBOL == (216735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216736)
		#define UNIQUE_FUNCTION<%0...%1> %0ouV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216737)
		#define UNIQUE_FUNCTION<%0...%1> %0ouW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216738)
		#define UNIQUE_FUNCTION<%0...%1> %0ouX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216739)
		#define UNIQUE_FUNCTION<%0...%1> %0ouY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216740)
		#define UNIQUE_FUNCTION<%0...%1> %0ouZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216741)
		#define UNIQUE_FUNCTION<%0...%1> %0ou_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216742)
		#define UNIQUE_FUNCTION<%0...%1> %0oua%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216743)
		#define UNIQUE_FUNCTION<%0...%1> %0oub%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (216751)
	#elseif UNIQUE_SYMBOL == (216743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216744)
		#define UNIQUE_FUNCTION<%0...%1> %0ouc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216745)
		#define UNIQUE_FUNCTION<%0...%1> %0oud%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216746)
		#define UNIQUE_FUNCTION<%0...%1> %0oue%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216747)
		#define UNIQUE_FUNCTION<%0...%1> %0ouf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216748)
		#define UNIQUE_FUNCTION<%0...%1> %0oug%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216749)
		#define UNIQUE_FUNCTION<%0...%1> %0ouh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216750)
		#define UNIQUE_FUNCTION<%0...%1> %0oui%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216751)
		#define UNIQUE_FUNCTION<%0...%1> %0ouj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (216759)
	#elseif UNIQUE_SYMBOL == (216751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216752)
		#define UNIQUE_FUNCTION<%0...%1> %0ouk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216753)
		#define UNIQUE_FUNCTION<%0...%1> %0oul%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216754)
		#define UNIQUE_FUNCTION<%0...%1> %0oum%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216755)
		#define UNIQUE_FUNCTION<%0...%1> %0oun%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216756)
		#define UNIQUE_FUNCTION<%0...%1> %0ouo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216757)
		#define UNIQUE_FUNCTION<%0...%1> %0oup%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216758)
		#define UNIQUE_FUNCTION<%0...%1> %0ouq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216759)
		#define UNIQUE_FUNCTION<%0...%1> %0our%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (216759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216760)
		#define UNIQUE_FUNCTION<%0...%1> %0ous%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216761)
		#define UNIQUE_FUNCTION<%0...%1> %0out%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216762)
		#define UNIQUE_FUNCTION<%0...%1> %0ouu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216763)
		#define UNIQUE_FUNCTION<%0...%1> %0ouv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216764)
		#define UNIQUE_FUNCTION<%0...%1> %0ouw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216765)
		#define UNIQUE_FUNCTION<%0...%1> %0oux%1
		#endinput
	#elseif UNIQUE_SYMBOL == (216765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216766)
		#define UNIQUE_FUNCTION<%0...%1> %0ouy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (216767)
		#define UNIQUE_FUNCTION<%0...%1> %0ouz%1
		#endinput
	#endif
#endif
