static stock const Y_UNIQUE_090880_090943_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_090880_090943
	#undef _inc_y_unique_090880_090943
#endif

#if UNIQUE_SYMBOL < (90887)
	#if UNIQUE_SYMBOL == (90879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90880)
		#define UNIQUE_FUNCTION<%0...%1> %0LB0%1
		#endinput
	#if UNIQUE_SYMBOL == (90880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90881)
		#define UNIQUE_FUNCTION<%0...%1> %0LB1%1
		#endinput
	#if UNIQUE_SYMBOL == (90881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90882)
		#define UNIQUE_FUNCTION<%0...%1> %0LB2%1
		#endinput
	#if UNIQUE_SYMBOL == (90882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90883)
		#define UNIQUE_FUNCTION<%0...%1> %0LB3%1
		#endinput
	#if UNIQUE_SYMBOL == (90883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90884)
		#define UNIQUE_FUNCTION<%0...%1> %0LB4%1
		#endinput
	#if UNIQUE_SYMBOL == (90884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90885)
		#define UNIQUE_FUNCTION<%0...%1> %0LB5%1
		#endinput
	#if UNIQUE_SYMBOL == (90885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90886)
		#define UNIQUE_FUNCTION<%0...%1> %0LB6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90887)
		#define UNIQUE_FUNCTION<%0...%1> %0LB7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90895)
	#elseif UNIQUE_SYMBOL == (90887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90888)
		#define UNIQUE_FUNCTION<%0...%1> %0LB8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90889)
		#define UNIQUE_FUNCTION<%0...%1> %0LB9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90890)
		#define UNIQUE_FUNCTION<%0...%1> %0LB@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90891)
		#define UNIQUE_FUNCTION<%0...%1> %0LBA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90892)
		#define UNIQUE_FUNCTION<%0...%1> %0LBB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90893)
		#define UNIQUE_FUNCTION<%0...%1> %0LBC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90894)
		#define UNIQUE_FUNCTION<%0...%1> %0LBD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90895)
		#define UNIQUE_FUNCTION<%0...%1> %0LBE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90903)
	#elseif UNIQUE_SYMBOL == (90895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90896)
		#define UNIQUE_FUNCTION<%0...%1> %0LBF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90897)
		#define UNIQUE_FUNCTION<%0...%1> %0LBG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90898)
		#define UNIQUE_FUNCTION<%0...%1> %0LBH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90899)
		#define UNIQUE_FUNCTION<%0...%1> %0LBI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90900)
		#define UNIQUE_FUNCTION<%0...%1> %0LBJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90901)
		#define UNIQUE_FUNCTION<%0...%1> %0LBK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90902)
		#define UNIQUE_FUNCTION<%0...%1> %0LBL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90903)
		#define UNIQUE_FUNCTION<%0...%1> %0LBM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90911)
	#elseif UNIQUE_SYMBOL == (90903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90904)
		#define UNIQUE_FUNCTION<%0...%1> %0LBN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90905)
		#define UNIQUE_FUNCTION<%0...%1> %0LBO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90906)
		#define UNIQUE_FUNCTION<%0...%1> %0LBP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90907)
		#define UNIQUE_FUNCTION<%0...%1> %0LBQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90908)
		#define UNIQUE_FUNCTION<%0...%1> %0LBR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90909)
		#define UNIQUE_FUNCTION<%0...%1> %0LBS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90910)
		#define UNIQUE_FUNCTION<%0...%1> %0LBT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90911)
		#define UNIQUE_FUNCTION<%0...%1> %0LBU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90919)
	#elseif UNIQUE_SYMBOL == (90911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90912)
		#define UNIQUE_FUNCTION<%0...%1> %0LBV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90913)
		#define UNIQUE_FUNCTION<%0...%1> %0LBW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90914)
		#define UNIQUE_FUNCTION<%0...%1> %0LBX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90915)
		#define UNIQUE_FUNCTION<%0...%1> %0LBY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90916)
		#define UNIQUE_FUNCTION<%0...%1> %0LBZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90917)
		#define UNIQUE_FUNCTION<%0...%1> %0LB_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90918)
		#define UNIQUE_FUNCTION<%0...%1> %0LBa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90919)
		#define UNIQUE_FUNCTION<%0...%1> %0LBb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90927)
	#elseif UNIQUE_SYMBOL == (90919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90920)
		#define UNIQUE_FUNCTION<%0...%1> %0LBc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90921)
		#define UNIQUE_FUNCTION<%0...%1> %0LBd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90922)
		#define UNIQUE_FUNCTION<%0...%1> %0LBe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90923)
		#define UNIQUE_FUNCTION<%0...%1> %0LBf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90924)
		#define UNIQUE_FUNCTION<%0...%1> %0LBg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90925)
		#define UNIQUE_FUNCTION<%0...%1> %0LBh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90926)
		#define UNIQUE_FUNCTION<%0...%1> %0LBi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90927)
		#define UNIQUE_FUNCTION<%0...%1> %0LBj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90935)
	#elseif UNIQUE_SYMBOL == (90927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90928)
		#define UNIQUE_FUNCTION<%0...%1> %0LBk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90929)
		#define UNIQUE_FUNCTION<%0...%1> %0LBl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90930)
		#define UNIQUE_FUNCTION<%0...%1> %0LBm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90931)
		#define UNIQUE_FUNCTION<%0...%1> %0LBn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90932)
		#define UNIQUE_FUNCTION<%0...%1> %0LBo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90933)
		#define UNIQUE_FUNCTION<%0...%1> %0LBp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90934)
		#define UNIQUE_FUNCTION<%0...%1> %0LBq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90935)
		#define UNIQUE_FUNCTION<%0...%1> %0LBr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (90935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90936)
		#define UNIQUE_FUNCTION<%0...%1> %0LBs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90937)
		#define UNIQUE_FUNCTION<%0...%1> %0LBt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90938)
		#define UNIQUE_FUNCTION<%0...%1> %0LBu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90939)
		#define UNIQUE_FUNCTION<%0...%1> %0LBv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90940)
		#define UNIQUE_FUNCTION<%0...%1> %0LBw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90941)
		#define UNIQUE_FUNCTION<%0...%1> %0LBx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90942)
		#define UNIQUE_FUNCTION<%0...%1> %0LBy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90943)
		#define UNIQUE_FUNCTION<%0...%1> %0LBz%1
		#endinput
	#endif
#endif
