static stock const Y_UNIQUE_180608_180671_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_180608_180671
	#undef _inc_y_unique_180608_180671
#endif

#if UNIQUE_SYMBOL < (180615)
	#if UNIQUE_SYMBOL == (180607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180608)
		#define UNIQUE_FUNCTION<%0...%1> %0g60%1
		#endinput
	#if UNIQUE_SYMBOL == (180608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180609)
		#define UNIQUE_FUNCTION<%0...%1> %0g61%1
		#endinput
	#if UNIQUE_SYMBOL == (180609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180610)
		#define UNIQUE_FUNCTION<%0...%1> %0g62%1
		#endinput
	#if UNIQUE_SYMBOL == (180610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180611)
		#define UNIQUE_FUNCTION<%0...%1> %0g63%1
		#endinput
	#if UNIQUE_SYMBOL == (180611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180612)
		#define UNIQUE_FUNCTION<%0...%1> %0g64%1
		#endinput
	#if UNIQUE_SYMBOL == (180612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180613)
		#define UNIQUE_FUNCTION<%0...%1> %0g65%1
		#endinput
	#if UNIQUE_SYMBOL == (180613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180614)
		#define UNIQUE_FUNCTION<%0...%1> %0g66%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180615)
		#define UNIQUE_FUNCTION<%0...%1> %0g67%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (180623)
	#elseif UNIQUE_SYMBOL == (180615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180616)
		#define UNIQUE_FUNCTION<%0...%1> %0g68%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180617)
		#define UNIQUE_FUNCTION<%0...%1> %0g69%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180618)
		#define UNIQUE_FUNCTION<%0...%1> %0g6@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180619)
		#define UNIQUE_FUNCTION<%0...%1> %0g6A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180620)
		#define UNIQUE_FUNCTION<%0...%1> %0g6B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180621)
		#define UNIQUE_FUNCTION<%0...%1> %0g6C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180622)
		#define UNIQUE_FUNCTION<%0...%1> %0g6D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180623)
		#define UNIQUE_FUNCTION<%0...%1> %0g6E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (180631)
	#elseif UNIQUE_SYMBOL == (180623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180624)
		#define UNIQUE_FUNCTION<%0...%1> %0g6F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180625)
		#define UNIQUE_FUNCTION<%0...%1> %0g6G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180626)
		#define UNIQUE_FUNCTION<%0...%1> %0g6H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180627)
		#define UNIQUE_FUNCTION<%0...%1> %0g6I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180628)
		#define UNIQUE_FUNCTION<%0...%1> %0g6J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180629)
		#define UNIQUE_FUNCTION<%0...%1> %0g6K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180630)
		#define UNIQUE_FUNCTION<%0...%1> %0g6L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180631)
		#define UNIQUE_FUNCTION<%0...%1> %0g6M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (180639)
	#elseif UNIQUE_SYMBOL == (180631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180632)
		#define UNIQUE_FUNCTION<%0...%1> %0g6N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180633)
		#define UNIQUE_FUNCTION<%0...%1> %0g6O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180634)
		#define UNIQUE_FUNCTION<%0...%1> %0g6P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180635)
		#define UNIQUE_FUNCTION<%0...%1> %0g6Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180636)
		#define UNIQUE_FUNCTION<%0...%1> %0g6R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180637)
		#define UNIQUE_FUNCTION<%0...%1> %0g6S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180638)
		#define UNIQUE_FUNCTION<%0...%1> %0g6T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180639)
		#define UNIQUE_FUNCTION<%0...%1> %0g6U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (180647)
	#elseif UNIQUE_SYMBOL == (180639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180640)
		#define UNIQUE_FUNCTION<%0...%1> %0g6V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180641)
		#define UNIQUE_FUNCTION<%0...%1> %0g6W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180642)
		#define UNIQUE_FUNCTION<%0...%1> %0g6X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180643)
		#define UNIQUE_FUNCTION<%0...%1> %0g6Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180644)
		#define UNIQUE_FUNCTION<%0...%1> %0g6Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180645)
		#define UNIQUE_FUNCTION<%0...%1> %0g6_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180646)
		#define UNIQUE_FUNCTION<%0...%1> %0g6a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180647)
		#define UNIQUE_FUNCTION<%0...%1> %0g6b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (180655)
	#elseif UNIQUE_SYMBOL == (180647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180648)
		#define UNIQUE_FUNCTION<%0...%1> %0g6c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180649)
		#define UNIQUE_FUNCTION<%0...%1> %0g6d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180650)
		#define UNIQUE_FUNCTION<%0...%1> %0g6e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180651)
		#define UNIQUE_FUNCTION<%0...%1> %0g6f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180652)
		#define UNIQUE_FUNCTION<%0...%1> %0g6g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180653)
		#define UNIQUE_FUNCTION<%0...%1> %0g6h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180654)
		#define UNIQUE_FUNCTION<%0...%1> %0g6i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180655)
		#define UNIQUE_FUNCTION<%0...%1> %0g6j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (180663)
	#elseif UNIQUE_SYMBOL == (180655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180656)
		#define UNIQUE_FUNCTION<%0...%1> %0g6k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180657)
		#define UNIQUE_FUNCTION<%0...%1> %0g6l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180658)
		#define UNIQUE_FUNCTION<%0...%1> %0g6m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180659)
		#define UNIQUE_FUNCTION<%0...%1> %0g6n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180660)
		#define UNIQUE_FUNCTION<%0...%1> %0g6o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180661)
		#define UNIQUE_FUNCTION<%0...%1> %0g6p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180662)
		#define UNIQUE_FUNCTION<%0...%1> %0g6q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180663)
		#define UNIQUE_FUNCTION<%0...%1> %0g6r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (180663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180664)
		#define UNIQUE_FUNCTION<%0...%1> %0g6s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180665)
		#define UNIQUE_FUNCTION<%0...%1> %0g6t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180666)
		#define UNIQUE_FUNCTION<%0...%1> %0g6u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180667)
		#define UNIQUE_FUNCTION<%0...%1> %0g6v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180668)
		#define UNIQUE_FUNCTION<%0...%1> %0g6w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180669)
		#define UNIQUE_FUNCTION<%0...%1> %0g6x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (180669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180670)
		#define UNIQUE_FUNCTION<%0...%1> %0g6y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (180671)
		#define UNIQUE_FUNCTION<%0...%1> %0g6z%1
		#endinput
	#endif
#endif
