static stock const Y_UNIQUE_128512_128575_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_128512_128575
	#undef _inc_y_unique_128512_128575
#endif

#if UNIQUE_SYMBOL < (128519)
	#if UNIQUE_SYMBOL == (128511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128512)
		#define UNIQUE_FUNCTION<%0...%1> %0UN0%1
		#endinput
	#if UNIQUE_SYMBOL == (128512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128513)
		#define UNIQUE_FUNCTION<%0...%1> %0UN1%1
		#endinput
	#if UNIQUE_SYMBOL == (128513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128514)
		#define UNIQUE_FUNCTION<%0...%1> %0UN2%1
		#endinput
	#if UNIQUE_SYMBOL == (128514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128515)
		#define UNIQUE_FUNCTION<%0...%1> %0UN3%1
		#endinput
	#if UNIQUE_SYMBOL == (128515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128516)
		#define UNIQUE_FUNCTION<%0...%1> %0UN4%1
		#endinput
	#if UNIQUE_SYMBOL == (128516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128517)
		#define UNIQUE_FUNCTION<%0...%1> %0UN5%1
		#endinput
	#if UNIQUE_SYMBOL == (128517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128518)
		#define UNIQUE_FUNCTION<%0...%1> %0UN6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128519)
		#define UNIQUE_FUNCTION<%0...%1> %0UN7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128527)
	#elseif UNIQUE_SYMBOL == (128519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128520)
		#define UNIQUE_FUNCTION<%0...%1> %0UN8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128521)
		#define UNIQUE_FUNCTION<%0...%1> %0UN9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128522)
		#define UNIQUE_FUNCTION<%0...%1> %0UN@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128523)
		#define UNIQUE_FUNCTION<%0...%1> %0UNA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128524)
		#define UNIQUE_FUNCTION<%0...%1> %0UNB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128525)
		#define UNIQUE_FUNCTION<%0...%1> %0UNC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128526)
		#define UNIQUE_FUNCTION<%0...%1> %0UND%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128527)
		#define UNIQUE_FUNCTION<%0...%1> %0UNE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128535)
	#elseif UNIQUE_SYMBOL == (128527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128528)
		#define UNIQUE_FUNCTION<%0...%1> %0UNF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128529)
		#define UNIQUE_FUNCTION<%0...%1> %0UNG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128530)
		#define UNIQUE_FUNCTION<%0...%1> %0UNH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128531)
		#define UNIQUE_FUNCTION<%0...%1> %0UNI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128532)
		#define UNIQUE_FUNCTION<%0...%1> %0UNJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128533)
		#define UNIQUE_FUNCTION<%0...%1> %0UNK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128534)
		#define UNIQUE_FUNCTION<%0...%1> %0UNL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128535)
		#define UNIQUE_FUNCTION<%0...%1> %0UNM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128543)
	#elseif UNIQUE_SYMBOL == (128535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128536)
		#define UNIQUE_FUNCTION<%0...%1> %0UNN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128537)
		#define UNIQUE_FUNCTION<%0...%1> %0UNO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128538)
		#define UNIQUE_FUNCTION<%0...%1> %0UNP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128539)
		#define UNIQUE_FUNCTION<%0...%1> %0UNQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128540)
		#define UNIQUE_FUNCTION<%0...%1> %0UNR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128541)
		#define UNIQUE_FUNCTION<%0...%1> %0UNS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128542)
		#define UNIQUE_FUNCTION<%0...%1> %0UNT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128543)
		#define UNIQUE_FUNCTION<%0...%1> %0UNU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128551)
	#elseif UNIQUE_SYMBOL == (128543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128544)
		#define UNIQUE_FUNCTION<%0...%1> %0UNV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128545)
		#define UNIQUE_FUNCTION<%0...%1> %0UNW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128546)
		#define UNIQUE_FUNCTION<%0...%1> %0UNX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128547)
		#define UNIQUE_FUNCTION<%0...%1> %0UNY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128548)
		#define UNIQUE_FUNCTION<%0...%1> %0UNZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128549)
		#define UNIQUE_FUNCTION<%0...%1> %0UN_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128550)
		#define UNIQUE_FUNCTION<%0...%1> %0UNa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128551)
		#define UNIQUE_FUNCTION<%0...%1> %0UNb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128559)
	#elseif UNIQUE_SYMBOL == (128551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128552)
		#define UNIQUE_FUNCTION<%0...%1> %0UNc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128553)
		#define UNIQUE_FUNCTION<%0...%1> %0UNd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128554)
		#define UNIQUE_FUNCTION<%0...%1> %0UNe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128555)
		#define UNIQUE_FUNCTION<%0...%1> %0UNf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128556)
		#define UNIQUE_FUNCTION<%0...%1> %0UNg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128557)
		#define UNIQUE_FUNCTION<%0...%1> %0UNh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128558)
		#define UNIQUE_FUNCTION<%0...%1> %0UNi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128559)
		#define UNIQUE_FUNCTION<%0...%1> %0UNj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128567)
	#elseif UNIQUE_SYMBOL == (128559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128560)
		#define UNIQUE_FUNCTION<%0...%1> %0UNk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128561)
		#define UNIQUE_FUNCTION<%0...%1> %0UNl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128562)
		#define UNIQUE_FUNCTION<%0...%1> %0UNm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128563)
		#define UNIQUE_FUNCTION<%0...%1> %0UNn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128564)
		#define UNIQUE_FUNCTION<%0...%1> %0UNo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128565)
		#define UNIQUE_FUNCTION<%0...%1> %0UNp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128566)
		#define UNIQUE_FUNCTION<%0...%1> %0UNq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128567)
		#define UNIQUE_FUNCTION<%0...%1> %0UNr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (128567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128568)
		#define UNIQUE_FUNCTION<%0...%1> %0UNs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128569)
		#define UNIQUE_FUNCTION<%0...%1> %0UNt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128570)
		#define UNIQUE_FUNCTION<%0...%1> %0UNu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128571)
		#define UNIQUE_FUNCTION<%0...%1> %0UNv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128572)
		#define UNIQUE_FUNCTION<%0...%1> %0UNw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128573)
		#define UNIQUE_FUNCTION<%0...%1> %0UNx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128574)
		#define UNIQUE_FUNCTION<%0...%1> %0UNy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128575)
		#define UNIQUE_FUNCTION<%0...%1> %0UNz%1
		#endinput
	#endif
#endif
