static stock const Y_UNIQUE_070144_070207_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_070144_070207
	#undef _inc_y_unique_070144_070207
#endif

#if UNIQUE_SYMBOL < (70151)
	#if UNIQUE_SYMBOL == (70143)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70144)
		#define UNIQUE_FUNCTION<%0...%1> %0G80%1
		#endinput
	#if UNIQUE_SYMBOL == (70144)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70145)
		#define UNIQUE_FUNCTION<%0...%1> %0G81%1
		#endinput
	#if UNIQUE_SYMBOL == (70145)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70146)
		#define UNIQUE_FUNCTION<%0...%1> %0G82%1
		#endinput
	#if UNIQUE_SYMBOL == (70146)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70147)
		#define UNIQUE_FUNCTION<%0...%1> %0G83%1
		#endinput
	#if UNIQUE_SYMBOL == (70147)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70148)
		#define UNIQUE_FUNCTION<%0...%1> %0G84%1
		#endinput
	#if UNIQUE_SYMBOL == (70148)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70149)
		#define UNIQUE_FUNCTION<%0...%1> %0G85%1
		#endinput
	#if UNIQUE_SYMBOL == (70149)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70150)
		#define UNIQUE_FUNCTION<%0...%1> %0G86%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70151)
		#define UNIQUE_FUNCTION<%0...%1> %0G87%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (70159)
	#elseif UNIQUE_SYMBOL == (70151)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70152)
		#define UNIQUE_FUNCTION<%0...%1> %0G88%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70152)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70153)
		#define UNIQUE_FUNCTION<%0...%1> %0G89%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70153)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70154)
		#define UNIQUE_FUNCTION<%0...%1> %0G8@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70154)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70155)
		#define UNIQUE_FUNCTION<%0...%1> %0G8A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70155)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70156)
		#define UNIQUE_FUNCTION<%0...%1> %0G8B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70156)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70157)
		#define UNIQUE_FUNCTION<%0...%1> %0G8C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70157)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70158)
		#define UNIQUE_FUNCTION<%0...%1> %0G8D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70159)
		#define UNIQUE_FUNCTION<%0...%1> %0G8E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (70167)
	#elseif UNIQUE_SYMBOL == (70159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70160)
		#define UNIQUE_FUNCTION<%0...%1> %0G8F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70161)
		#define UNIQUE_FUNCTION<%0...%1> %0G8G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70162)
		#define UNIQUE_FUNCTION<%0...%1> %0G8H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70163)
		#define UNIQUE_FUNCTION<%0...%1> %0G8I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70164)
		#define UNIQUE_FUNCTION<%0...%1> %0G8J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70165)
		#define UNIQUE_FUNCTION<%0...%1> %0G8K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70166)
		#define UNIQUE_FUNCTION<%0...%1> %0G8L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70167)
		#define UNIQUE_FUNCTION<%0...%1> %0G8M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (70175)
	#elseif UNIQUE_SYMBOL == (70167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70168)
		#define UNIQUE_FUNCTION<%0...%1> %0G8N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70169)
		#define UNIQUE_FUNCTION<%0...%1> %0G8O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70170)
		#define UNIQUE_FUNCTION<%0...%1> %0G8P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70171)
		#define UNIQUE_FUNCTION<%0...%1> %0G8Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70172)
		#define UNIQUE_FUNCTION<%0...%1> %0G8R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70173)
		#define UNIQUE_FUNCTION<%0...%1> %0G8S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70174)
		#define UNIQUE_FUNCTION<%0...%1> %0G8T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70175)
		#define UNIQUE_FUNCTION<%0...%1> %0G8U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (70183)
	#elseif UNIQUE_SYMBOL == (70175)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70176)
		#define UNIQUE_FUNCTION<%0...%1> %0G8V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70176)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70177)
		#define UNIQUE_FUNCTION<%0...%1> %0G8W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70177)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70178)
		#define UNIQUE_FUNCTION<%0...%1> %0G8X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70178)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70179)
		#define UNIQUE_FUNCTION<%0...%1> %0G8Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70179)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70180)
		#define UNIQUE_FUNCTION<%0...%1> %0G8Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70180)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70181)
		#define UNIQUE_FUNCTION<%0...%1> %0G8_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70181)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70182)
		#define UNIQUE_FUNCTION<%0...%1> %0G8a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70183)
		#define UNIQUE_FUNCTION<%0...%1> %0G8b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (70191)
	#elseif UNIQUE_SYMBOL == (70183)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70184)
		#define UNIQUE_FUNCTION<%0...%1> %0G8c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70184)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70185)
		#define UNIQUE_FUNCTION<%0...%1> %0G8d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70185)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70186)
		#define UNIQUE_FUNCTION<%0...%1> %0G8e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70186)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70187)
		#define UNIQUE_FUNCTION<%0...%1> %0G8f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70187)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70188)
		#define UNIQUE_FUNCTION<%0...%1> %0G8g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70188)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70189)
		#define UNIQUE_FUNCTION<%0...%1> %0G8h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70189)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70190)
		#define UNIQUE_FUNCTION<%0...%1> %0G8i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70191)
		#define UNIQUE_FUNCTION<%0...%1> %0G8j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (70199)
	#elseif UNIQUE_SYMBOL == (70191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70192)
		#define UNIQUE_FUNCTION<%0...%1> %0G8k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70193)
		#define UNIQUE_FUNCTION<%0...%1> %0G8l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70194)
		#define UNIQUE_FUNCTION<%0...%1> %0G8m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70195)
		#define UNIQUE_FUNCTION<%0...%1> %0G8n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70196)
		#define UNIQUE_FUNCTION<%0...%1> %0G8o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70197)
		#define UNIQUE_FUNCTION<%0...%1> %0G8p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70198)
		#define UNIQUE_FUNCTION<%0...%1> %0G8q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70199)
		#define UNIQUE_FUNCTION<%0...%1> %0G8r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (70199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70200)
		#define UNIQUE_FUNCTION<%0...%1> %0G8s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70201)
		#define UNIQUE_FUNCTION<%0...%1> %0G8t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70202)
		#define UNIQUE_FUNCTION<%0...%1> %0G8u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70203)
		#define UNIQUE_FUNCTION<%0...%1> %0G8v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70204)
		#define UNIQUE_FUNCTION<%0...%1> %0G8w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70205)
		#define UNIQUE_FUNCTION<%0...%1> %0G8x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (70205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70206)
		#define UNIQUE_FUNCTION<%0...%1> %0G8y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70207)
		#define UNIQUE_FUNCTION<%0...%1> %0G8z%1
		#endinput
	#endif
#endif
