static stock const Y_UNIQUE_250752_250815_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_250752_250815
	#undef _inc_y_unique_250752_250815
#endif

#if UNIQUE_SYMBOL < (250759)
	#if UNIQUE_SYMBOL == (250751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250752)
		#define UNIQUE_FUNCTION<%0...%1> %0xD0%1
		#endinput
	#if UNIQUE_SYMBOL == (250752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250753)
		#define UNIQUE_FUNCTION<%0...%1> %0xD1%1
		#endinput
	#if UNIQUE_SYMBOL == (250753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250754)
		#define UNIQUE_FUNCTION<%0...%1> %0xD2%1
		#endinput
	#if UNIQUE_SYMBOL == (250754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250755)
		#define UNIQUE_FUNCTION<%0...%1> %0xD3%1
		#endinput
	#if UNIQUE_SYMBOL == (250755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250756)
		#define UNIQUE_FUNCTION<%0...%1> %0xD4%1
		#endinput
	#if UNIQUE_SYMBOL == (250756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250757)
		#define UNIQUE_FUNCTION<%0...%1> %0xD5%1
		#endinput
	#if UNIQUE_SYMBOL == (250757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250758)
		#define UNIQUE_FUNCTION<%0...%1> %0xD6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250759)
		#define UNIQUE_FUNCTION<%0...%1> %0xD7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250767)
	#elseif UNIQUE_SYMBOL == (250759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250760)
		#define UNIQUE_FUNCTION<%0...%1> %0xD8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250761)
		#define UNIQUE_FUNCTION<%0...%1> %0xD9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250762)
		#define UNIQUE_FUNCTION<%0...%1> %0xD@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250763)
		#define UNIQUE_FUNCTION<%0...%1> %0xDA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250764)
		#define UNIQUE_FUNCTION<%0...%1> %0xDB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250765)
		#define UNIQUE_FUNCTION<%0...%1> %0xDC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250766)
		#define UNIQUE_FUNCTION<%0...%1> %0xDD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250767)
		#define UNIQUE_FUNCTION<%0...%1> %0xDE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250775)
	#elseif UNIQUE_SYMBOL == (250767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250768)
		#define UNIQUE_FUNCTION<%0...%1> %0xDF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250769)
		#define UNIQUE_FUNCTION<%0...%1> %0xDG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250770)
		#define UNIQUE_FUNCTION<%0...%1> %0xDH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250771)
		#define UNIQUE_FUNCTION<%0...%1> %0xDI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250772)
		#define UNIQUE_FUNCTION<%0...%1> %0xDJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250773)
		#define UNIQUE_FUNCTION<%0...%1> %0xDK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250774)
		#define UNIQUE_FUNCTION<%0...%1> %0xDL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250775)
		#define UNIQUE_FUNCTION<%0...%1> %0xDM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250783)
	#elseif UNIQUE_SYMBOL == (250775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250776)
		#define UNIQUE_FUNCTION<%0...%1> %0xDN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250777)
		#define UNIQUE_FUNCTION<%0...%1> %0xDO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250778)
		#define UNIQUE_FUNCTION<%0...%1> %0xDP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250779)
		#define UNIQUE_FUNCTION<%0...%1> %0xDQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250780)
		#define UNIQUE_FUNCTION<%0...%1> %0xDR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250781)
		#define UNIQUE_FUNCTION<%0...%1> %0xDS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250782)
		#define UNIQUE_FUNCTION<%0...%1> %0xDT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250783)
		#define UNIQUE_FUNCTION<%0...%1> %0xDU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250791)
	#elseif UNIQUE_SYMBOL == (250783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250784)
		#define UNIQUE_FUNCTION<%0...%1> %0xDV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250785)
		#define UNIQUE_FUNCTION<%0...%1> %0xDW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250786)
		#define UNIQUE_FUNCTION<%0...%1> %0xDX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250787)
		#define UNIQUE_FUNCTION<%0...%1> %0xDY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250788)
		#define UNIQUE_FUNCTION<%0...%1> %0xDZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250789)
		#define UNIQUE_FUNCTION<%0...%1> %0xD_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250790)
		#define UNIQUE_FUNCTION<%0...%1> %0xDa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250791)
		#define UNIQUE_FUNCTION<%0...%1> %0xDb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250799)
	#elseif UNIQUE_SYMBOL == (250791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250792)
		#define UNIQUE_FUNCTION<%0...%1> %0xDc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250793)
		#define UNIQUE_FUNCTION<%0...%1> %0xDd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250794)
		#define UNIQUE_FUNCTION<%0...%1> %0xDe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250795)
		#define UNIQUE_FUNCTION<%0...%1> %0xDf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250796)
		#define UNIQUE_FUNCTION<%0...%1> %0xDg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250797)
		#define UNIQUE_FUNCTION<%0...%1> %0xDh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250798)
		#define UNIQUE_FUNCTION<%0...%1> %0xDi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250799)
		#define UNIQUE_FUNCTION<%0...%1> %0xDj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250807)
	#elseif UNIQUE_SYMBOL == (250799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250800)
		#define UNIQUE_FUNCTION<%0...%1> %0xDk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250801)
		#define UNIQUE_FUNCTION<%0...%1> %0xDl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250802)
		#define UNIQUE_FUNCTION<%0...%1> %0xDm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250803)
		#define UNIQUE_FUNCTION<%0...%1> %0xDn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250804)
		#define UNIQUE_FUNCTION<%0...%1> %0xDo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250805)
		#define UNIQUE_FUNCTION<%0...%1> %0xDp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250806)
		#define UNIQUE_FUNCTION<%0...%1> %0xDq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250807)
		#define UNIQUE_FUNCTION<%0...%1> %0xDr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (250807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250808)
		#define UNIQUE_FUNCTION<%0...%1> %0xDs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250809)
		#define UNIQUE_FUNCTION<%0...%1> %0xDt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250810)
		#define UNIQUE_FUNCTION<%0...%1> %0xDu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250811)
		#define UNIQUE_FUNCTION<%0...%1> %0xDv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250812)
		#define UNIQUE_FUNCTION<%0...%1> %0xDw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250813)
		#define UNIQUE_FUNCTION<%0...%1> %0xDx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250814)
		#define UNIQUE_FUNCTION<%0...%1> %0xDy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250815)
		#define UNIQUE_FUNCTION<%0...%1> %0xDz%1
		#endinput
	#endif
#endif
