static stock const Y_UNIQUE_081216_081279_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_081216_081279
	#undef _inc_y_unique_081216_081279
#endif

#if UNIQUE_SYMBOL < (81223)
	#if UNIQUE_SYMBOL == (81215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81216)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip0%1
		#endinput
	#if UNIQUE_SYMBOL == (81216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81217)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip1%1
		#endinput
	#if UNIQUE_SYMBOL == (81217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81218)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip2%1
		#endinput
	#if UNIQUE_SYMBOL == (81218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81219)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip3%1
		#endinput
	#if UNIQUE_SYMBOL == (81219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81220)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip4%1
		#endinput
	#if UNIQUE_SYMBOL == (81220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81221)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip5%1
		#endinput
	#if UNIQUE_SYMBOL == (81221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81222)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81223)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81231)
	#elseif UNIQUE_SYMBOL == (81223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81224)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81225)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81226)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81227)
		#define UNIQUE_FUNCTION<%0...%1> %0IpA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81228)
		#define UNIQUE_FUNCTION<%0...%1> %0IpB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81229)
		#define UNIQUE_FUNCTION<%0...%1> %0IpC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81230)
		#define UNIQUE_FUNCTION<%0...%1> %0IpD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81231)
		#define UNIQUE_FUNCTION<%0...%1> %0IpE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81239)
	#elseif UNIQUE_SYMBOL == (81231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81232)
		#define UNIQUE_FUNCTION<%0...%1> %0IpF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81233)
		#define UNIQUE_FUNCTION<%0...%1> %0IpG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81234)
		#define UNIQUE_FUNCTION<%0...%1> %0IpH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81235)
		#define UNIQUE_FUNCTION<%0...%1> %0IpI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81236)
		#define UNIQUE_FUNCTION<%0...%1> %0IpJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81237)
		#define UNIQUE_FUNCTION<%0...%1> %0IpK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81238)
		#define UNIQUE_FUNCTION<%0...%1> %0IpL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81239)
		#define UNIQUE_FUNCTION<%0...%1> %0IpM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81247)
	#elseif UNIQUE_SYMBOL == (81239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81240)
		#define UNIQUE_FUNCTION<%0...%1> %0IpN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81241)
		#define UNIQUE_FUNCTION<%0...%1> %0IpO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81242)
		#define UNIQUE_FUNCTION<%0...%1> %0IpP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81243)
		#define UNIQUE_FUNCTION<%0...%1> %0IpQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81244)
		#define UNIQUE_FUNCTION<%0...%1> %0IpR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81245)
		#define UNIQUE_FUNCTION<%0...%1> %0IpS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81246)
		#define UNIQUE_FUNCTION<%0...%1> %0IpT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81247)
		#define UNIQUE_FUNCTION<%0...%1> %0IpU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81255)
	#elseif UNIQUE_SYMBOL == (81247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81248)
		#define UNIQUE_FUNCTION<%0...%1> %0IpV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81249)
		#define UNIQUE_FUNCTION<%0...%1> %0IpW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81250)
		#define UNIQUE_FUNCTION<%0...%1> %0IpX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81251)
		#define UNIQUE_FUNCTION<%0...%1> %0IpY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81252)
		#define UNIQUE_FUNCTION<%0...%1> %0IpZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81253)
		#define UNIQUE_FUNCTION<%0...%1> %0Ip_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81254)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81255)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81263)
	#elseif UNIQUE_SYMBOL == (81255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81256)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81257)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81258)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81259)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81260)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81261)
		#define UNIQUE_FUNCTION<%0...%1> %0Iph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81262)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81263)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81271)
	#elseif UNIQUE_SYMBOL == (81263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81264)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81265)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81266)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81267)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81268)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81269)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81270)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81271)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (81271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81272)
		#define UNIQUE_FUNCTION<%0...%1> %0Ips%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81273)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81274)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81275)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81276)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81277)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81278)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81279)
		#define UNIQUE_FUNCTION<%0...%1> %0Ipz%1
		#endinput
	#endif
#endif
