static stock const Y_UNIQUE_3008_3071_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_3008_3071
	#undef _inc_y_unique_3008_3071
#endif

#if UNIQUE_SYMBOL < (3015)
	#if UNIQUE_SYMBOL == (3007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3008)
		#define UNIQUE_FUNCTION<%0...%1> %0j0%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3009)
		#define UNIQUE_FUNCTION<%0...%1> %0j1%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3010)
		#define UNIQUE_FUNCTION<%0...%1> %0j2%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3011)
		#define UNIQUE_FUNCTION<%0...%1> %0j3%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3012)
		#define UNIQUE_FUNCTION<%0...%1> %0j4%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3013)
		#define UNIQUE_FUNCTION<%0...%1> %0j5%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3014)
		#define UNIQUE_FUNCTION<%0...%1> %0j6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3015)
		#define UNIQUE_FUNCTION<%0...%1> %0j7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3023)
	#if UNIQUE_SYMBOL == (3015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3016)
		#define UNIQUE_FUNCTION<%0...%1> %0j8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3017)
		#define UNIQUE_FUNCTION<%0...%1> %0j9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3018)
		#define UNIQUE_FUNCTION<%0...%1> %0j@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3019)
		#define UNIQUE_FUNCTION<%0...%1> %0jA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3020)
		#define UNIQUE_FUNCTION<%0...%1> %0jB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3021)
		#define UNIQUE_FUNCTION<%0...%1> %0jC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3022)
		#define UNIQUE_FUNCTION<%0...%1> %0jD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3023)
		#define UNIQUE_FUNCTION<%0...%1> %0jE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3031)
	#if UNIQUE_SYMBOL == (3023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3024)
		#define UNIQUE_FUNCTION<%0...%1> %0jF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3025)
		#define UNIQUE_FUNCTION<%0...%1> %0jG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3026)
		#define UNIQUE_FUNCTION<%0...%1> %0jH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3027)
		#define UNIQUE_FUNCTION<%0...%1> %0jI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3028)
		#define UNIQUE_FUNCTION<%0...%1> %0jJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3029)
		#define UNIQUE_FUNCTION<%0...%1> %0jK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3030)
		#define UNIQUE_FUNCTION<%0...%1> %0jL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3031)
		#define UNIQUE_FUNCTION<%0...%1> %0jM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3039)
	#if UNIQUE_SYMBOL == (3031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3032)
		#define UNIQUE_FUNCTION<%0...%1> %0jN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3033)
		#define UNIQUE_FUNCTION<%0...%1> %0jO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3034)
		#define UNIQUE_FUNCTION<%0...%1> %0jP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3035)
		#define UNIQUE_FUNCTION<%0...%1> %0jQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3036)
		#define UNIQUE_FUNCTION<%0...%1> %0jR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3037)
		#define UNIQUE_FUNCTION<%0...%1> %0jS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3038)
		#define UNIQUE_FUNCTION<%0...%1> %0jT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3039)
		#define UNIQUE_FUNCTION<%0...%1> %0jU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3047)
	#if UNIQUE_SYMBOL == (3039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3040)
		#define UNIQUE_FUNCTION<%0...%1> %0jV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3041)
		#define UNIQUE_FUNCTION<%0...%1> %0jW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3042)
		#define UNIQUE_FUNCTION<%0...%1> %0jX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3043)
		#define UNIQUE_FUNCTION<%0...%1> %0jY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3044)
		#define UNIQUE_FUNCTION<%0...%1> %0jZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3045)
		#define UNIQUE_FUNCTION<%0...%1> %0j_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3046)
		#define UNIQUE_FUNCTION<%0...%1> %0ja%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3047)
		#define UNIQUE_FUNCTION<%0...%1> %0jb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3055)
	#if UNIQUE_SYMBOL == (3047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3048)
		#define UNIQUE_FUNCTION<%0...%1> %0jc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3049)
		#define UNIQUE_FUNCTION<%0...%1> %0jd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3050)
		#define UNIQUE_FUNCTION<%0...%1> %0je%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3051)
		#define UNIQUE_FUNCTION<%0...%1> %0jf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3052)
		#define UNIQUE_FUNCTION<%0...%1> %0jg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3053)
		#define UNIQUE_FUNCTION<%0...%1> %0jh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3054)
		#define UNIQUE_FUNCTION<%0...%1> %0ji%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3055)
		#define UNIQUE_FUNCTION<%0...%1> %0jj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3063)
	#if UNIQUE_SYMBOL == (3055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3056)
		#define UNIQUE_FUNCTION<%0...%1> %0jk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3057)
		#define UNIQUE_FUNCTION<%0...%1> %0jl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3058)
		#define UNIQUE_FUNCTION<%0...%1> %0jm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3059)
		#define UNIQUE_FUNCTION<%0...%1> %0jn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3060)
		#define UNIQUE_FUNCTION<%0...%1> %0jo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3061)
		#define UNIQUE_FUNCTION<%0...%1> %0jp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3062)
		#define UNIQUE_FUNCTION<%0...%1> %0jq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3063)
		#define UNIQUE_FUNCTION<%0...%1> %0jr%1
		#endinput
	#endif
#else
	#if UNIQUE_SYMBOL == (3063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3064)
		#define UNIQUE_FUNCTION<%0...%1> %0js%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3065)
		#define UNIQUE_FUNCTION<%0...%1> %0jt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3066)
		#define UNIQUE_FUNCTION<%0...%1> %0ju%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3067)
		#define UNIQUE_FUNCTION<%0...%1> %0jv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3068)
		#define UNIQUE_FUNCTION<%0...%1> %0jw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3069)
		#define UNIQUE_FUNCTION<%0...%1> %0jx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3070)
		#define UNIQUE_FUNCTION<%0...%1> %0jy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3071)
		#define UNIQUE_FUNCTION<%0...%1> %0jz%1
		#endinput
	#endif
#endif

