static stock const Y_UNIQUE_079488_079551_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_079488_079551
	#undef _inc_y_unique_079488_079551
#endif

#if UNIQUE_SYMBOL < (79495)
	#if UNIQUE_SYMBOL == (79487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79488)
		#define UNIQUE_FUNCTION<%0...%1> %0IP0%1
		#endinput
	#if UNIQUE_SYMBOL == (79488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79489)
		#define UNIQUE_FUNCTION<%0...%1> %0IP1%1
		#endinput
	#if UNIQUE_SYMBOL == (79489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79490)
		#define UNIQUE_FUNCTION<%0...%1> %0IP2%1
		#endinput
	#if UNIQUE_SYMBOL == (79490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79491)
		#define UNIQUE_FUNCTION<%0...%1> %0IP3%1
		#endinput
	#if UNIQUE_SYMBOL == (79491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79492)
		#define UNIQUE_FUNCTION<%0...%1> %0IP4%1
		#endinput
	#if UNIQUE_SYMBOL == (79492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79493)
		#define UNIQUE_FUNCTION<%0...%1> %0IP5%1
		#endinput
	#if UNIQUE_SYMBOL == (79493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79494)
		#define UNIQUE_FUNCTION<%0...%1> %0IP6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79495)
		#define UNIQUE_FUNCTION<%0...%1> %0IP7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79503)
	#elseif UNIQUE_SYMBOL == (79495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79496)
		#define UNIQUE_FUNCTION<%0...%1> %0IP8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79497)
		#define UNIQUE_FUNCTION<%0...%1> %0IP9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79498)
		#define UNIQUE_FUNCTION<%0...%1> %0IP@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79499)
		#define UNIQUE_FUNCTION<%0...%1> %0IPA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79500)
		#define UNIQUE_FUNCTION<%0...%1> %0IPB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79501)
		#define UNIQUE_FUNCTION<%0...%1> %0IPC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79502)
		#define UNIQUE_FUNCTION<%0...%1> %0IPD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79503)
		#define UNIQUE_FUNCTION<%0...%1> %0IPE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79511)
	#elseif UNIQUE_SYMBOL == (79503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79504)
		#define UNIQUE_FUNCTION<%0...%1> %0IPF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79505)
		#define UNIQUE_FUNCTION<%0...%1> %0IPG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79506)
		#define UNIQUE_FUNCTION<%0...%1> %0IPH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79507)
		#define UNIQUE_FUNCTION<%0...%1> %0IPI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79508)
		#define UNIQUE_FUNCTION<%0...%1> %0IPJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79509)
		#define UNIQUE_FUNCTION<%0...%1> %0IPK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79510)
		#define UNIQUE_FUNCTION<%0...%1> %0IPL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79511)
		#define UNIQUE_FUNCTION<%0...%1> %0IPM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79519)
	#elseif UNIQUE_SYMBOL == (79511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79512)
		#define UNIQUE_FUNCTION<%0...%1> %0IPN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79513)
		#define UNIQUE_FUNCTION<%0...%1> %0IPO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79514)
		#define UNIQUE_FUNCTION<%0...%1> %0IPP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79515)
		#define UNIQUE_FUNCTION<%0...%1> %0IPQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79516)
		#define UNIQUE_FUNCTION<%0...%1> %0IPR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79517)
		#define UNIQUE_FUNCTION<%0...%1> %0IPS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79518)
		#define UNIQUE_FUNCTION<%0...%1> %0IPT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79519)
		#define UNIQUE_FUNCTION<%0...%1> %0IPU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79527)
	#elseif UNIQUE_SYMBOL == (79519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79520)
		#define UNIQUE_FUNCTION<%0...%1> %0IPV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79521)
		#define UNIQUE_FUNCTION<%0...%1> %0IPW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79522)
		#define UNIQUE_FUNCTION<%0...%1> %0IPX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79523)
		#define UNIQUE_FUNCTION<%0...%1> %0IPY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79524)
		#define UNIQUE_FUNCTION<%0...%1> %0IPZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79525)
		#define UNIQUE_FUNCTION<%0...%1> %0IP_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79526)
		#define UNIQUE_FUNCTION<%0...%1> %0IPa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79527)
		#define UNIQUE_FUNCTION<%0...%1> %0IPb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79535)
	#elseif UNIQUE_SYMBOL == (79527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79528)
		#define UNIQUE_FUNCTION<%0...%1> %0IPc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79529)
		#define UNIQUE_FUNCTION<%0...%1> %0IPd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79530)
		#define UNIQUE_FUNCTION<%0...%1> %0IPe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79531)
		#define UNIQUE_FUNCTION<%0...%1> %0IPf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79532)
		#define UNIQUE_FUNCTION<%0...%1> %0IPg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79533)
		#define UNIQUE_FUNCTION<%0...%1> %0IPh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79534)
		#define UNIQUE_FUNCTION<%0...%1> %0IPi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79535)
		#define UNIQUE_FUNCTION<%0...%1> %0IPj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79543)
	#elseif UNIQUE_SYMBOL == (79535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79536)
		#define UNIQUE_FUNCTION<%0...%1> %0IPk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79537)
		#define UNIQUE_FUNCTION<%0...%1> %0IPl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79538)
		#define UNIQUE_FUNCTION<%0...%1> %0IPm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79539)
		#define UNIQUE_FUNCTION<%0...%1> %0IPn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79540)
		#define UNIQUE_FUNCTION<%0...%1> %0IPo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79541)
		#define UNIQUE_FUNCTION<%0...%1> %0IPp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79542)
		#define UNIQUE_FUNCTION<%0...%1> %0IPq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79543)
		#define UNIQUE_FUNCTION<%0...%1> %0IPr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (79543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79544)
		#define UNIQUE_FUNCTION<%0...%1> %0IPs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79545)
		#define UNIQUE_FUNCTION<%0...%1> %0IPt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79546)
		#define UNIQUE_FUNCTION<%0...%1> %0IPu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79547)
		#define UNIQUE_FUNCTION<%0...%1> %0IPv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79548)
		#define UNIQUE_FUNCTION<%0...%1> %0IPw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79549)
		#define UNIQUE_FUNCTION<%0...%1> %0IPx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79550)
		#define UNIQUE_FUNCTION<%0...%1> %0IPy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79551)
		#define UNIQUE_FUNCTION<%0...%1> %0IPz%1
		#endinput
	#endif
#endif
