static stock const Y_UNIQUE_240000_240063_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_240000_240063
	#undef _inc_y_unique_240000_240063
#endif

#if UNIQUE_SYMBOL < (240007)
	#if UNIQUE_SYMBOL == (239999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240000)
		#define UNIQUE_FUNCTION<%0...%1> %0ua0%1
		#endinput
	#if UNIQUE_SYMBOL == (240000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240001)
		#define UNIQUE_FUNCTION<%0...%1> %0ua1%1
		#endinput
	#if UNIQUE_SYMBOL == (240001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240002)
		#define UNIQUE_FUNCTION<%0...%1> %0ua2%1
		#endinput
	#if UNIQUE_SYMBOL == (240002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240003)
		#define UNIQUE_FUNCTION<%0...%1> %0ua3%1
		#endinput
	#if UNIQUE_SYMBOL == (240003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240004)
		#define UNIQUE_FUNCTION<%0...%1> %0ua4%1
		#endinput
	#if UNIQUE_SYMBOL == (240004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240005)
		#define UNIQUE_FUNCTION<%0...%1> %0ua5%1
		#endinput
	#if UNIQUE_SYMBOL == (240005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240006)
		#define UNIQUE_FUNCTION<%0...%1> %0ua6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240007)
		#define UNIQUE_FUNCTION<%0...%1> %0ua7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (240015)
	#elseif UNIQUE_SYMBOL == (240007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240008)
		#define UNIQUE_FUNCTION<%0...%1> %0ua8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240009)
		#define UNIQUE_FUNCTION<%0...%1> %0ua9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240010)
		#define UNIQUE_FUNCTION<%0...%1> %0ua@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240011)
		#define UNIQUE_FUNCTION<%0...%1> %0uaA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240012)
		#define UNIQUE_FUNCTION<%0...%1> %0uaB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240013)
		#define UNIQUE_FUNCTION<%0...%1> %0uaC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240014)
		#define UNIQUE_FUNCTION<%0...%1> %0uaD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240015)
		#define UNIQUE_FUNCTION<%0...%1> %0uaE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (240023)
	#elseif UNIQUE_SYMBOL == (240015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240016)
		#define UNIQUE_FUNCTION<%0...%1> %0uaF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240017)
		#define UNIQUE_FUNCTION<%0...%1> %0uaG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240018)
		#define UNIQUE_FUNCTION<%0...%1> %0uaH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240019)
		#define UNIQUE_FUNCTION<%0...%1> %0uaI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240020)
		#define UNIQUE_FUNCTION<%0...%1> %0uaJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240021)
		#define UNIQUE_FUNCTION<%0...%1> %0uaK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240022)
		#define UNIQUE_FUNCTION<%0...%1> %0uaL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240023)
		#define UNIQUE_FUNCTION<%0...%1> %0uaM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (240031)
	#elseif UNIQUE_SYMBOL == (240023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240024)
		#define UNIQUE_FUNCTION<%0...%1> %0uaN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240025)
		#define UNIQUE_FUNCTION<%0...%1> %0uaO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240026)
		#define UNIQUE_FUNCTION<%0...%1> %0uaP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240027)
		#define UNIQUE_FUNCTION<%0...%1> %0uaQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240028)
		#define UNIQUE_FUNCTION<%0...%1> %0uaR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240029)
		#define UNIQUE_FUNCTION<%0...%1> %0uaS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240030)
		#define UNIQUE_FUNCTION<%0...%1> %0uaT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240031)
		#define UNIQUE_FUNCTION<%0...%1> %0uaU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (240039)
	#elseif UNIQUE_SYMBOL == (240031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240032)
		#define UNIQUE_FUNCTION<%0...%1> %0uaV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240033)
		#define UNIQUE_FUNCTION<%0...%1> %0uaW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240034)
		#define UNIQUE_FUNCTION<%0...%1> %0uaX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240035)
		#define UNIQUE_FUNCTION<%0...%1> %0uaY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240036)
		#define UNIQUE_FUNCTION<%0...%1> %0uaZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240037)
		#define UNIQUE_FUNCTION<%0...%1> %0ua_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240038)
		#define UNIQUE_FUNCTION<%0...%1> %0uaa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240039)
		#define UNIQUE_FUNCTION<%0...%1> %0uab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (240047)
	#elseif UNIQUE_SYMBOL == (240039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240040)
		#define UNIQUE_FUNCTION<%0...%1> %0uac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240041)
		#define UNIQUE_FUNCTION<%0...%1> %0uad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240042)
		#define UNIQUE_FUNCTION<%0...%1> %0uae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240043)
		#define UNIQUE_FUNCTION<%0...%1> %0uaf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240044)
		#define UNIQUE_FUNCTION<%0...%1> %0uag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240045)
		#define UNIQUE_FUNCTION<%0...%1> %0uah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240046)
		#define UNIQUE_FUNCTION<%0...%1> %0uai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240047)
		#define UNIQUE_FUNCTION<%0...%1> %0uaj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (240055)
	#elseif UNIQUE_SYMBOL == (240047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240048)
		#define UNIQUE_FUNCTION<%0...%1> %0uak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240049)
		#define UNIQUE_FUNCTION<%0...%1> %0ual%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240050)
		#define UNIQUE_FUNCTION<%0...%1> %0uam%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240051)
		#define UNIQUE_FUNCTION<%0...%1> %0uan%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240052)
		#define UNIQUE_FUNCTION<%0...%1> %0uao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240053)
		#define UNIQUE_FUNCTION<%0...%1> %0uap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240054)
		#define UNIQUE_FUNCTION<%0...%1> %0uaq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240055)
		#define UNIQUE_FUNCTION<%0...%1> %0uar%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (240055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240056)
		#define UNIQUE_FUNCTION<%0...%1> %0uas%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240057)
		#define UNIQUE_FUNCTION<%0...%1> %0uat%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240058)
		#define UNIQUE_FUNCTION<%0...%1> %0uau%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240059)
		#define UNIQUE_FUNCTION<%0...%1> %0uav%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240060)
		#define UNIQUE_FUNCTION<%0...%1> %0uaw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240061)
		#define UNIQUE_FUNCTION<%0...%1> %0uax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (240061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240062)
		#define UNIQUE_FUNCTION<%0...%1> %0uay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (240063)
		#define UNIQUE_FUNCTION<%0...%1> %0uaz%1
		#endinput
	#endif
#endif
