static stock const Y_UNIQUE_241984_242047_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_241984_242047
	#undef _inc_y_unique_241984_242047
#endif

#if UNIQUE_SYMBOL < (241991)
	#if UNIQUE_SYMBOL == (241983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241984)
		#define UNIQUE_FUNCTION<%0...%1> %0v50%1
		#endinput
	#if UNIQUE_SYMBOL == (241984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241985)
		#define UNIQUE_FUNCTION<%0...%1> %0v51%1
		#endinput
	#if UNIQUE_SYMBOL == (241985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241986)
		#define UNIQUE_FUNCTION<%0...%1> %0v52%1
		#endinput
	#if UNIQUE_SYMBOL == (241986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241987)
		#define UNIQUE_FUNCTION<%0...%1> %0v53%1
		#endinput
	#if UNIQUE_SYMBOL == (241987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241988)
		#define UNIQUE_FUNCTION<%0...%1> %0v54%1
		#endinput
	#if UNIQUE_SYMBOL == (241988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241989)
		#define UNIQUE_FUNCTION<%0...%1> %0v55%1
		#endinput
	#if UNIQUE_SYMBOL == (241989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241990)
		#define UNIQUE_FUNCTION<%0...%1> %0v56%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241991)
		#define UNIQUE_FUNCTION<%0...%1> %0v57%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241999)
	#elseif UNIQUE_SYMBOL == (241991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241992)
		#define UNIQUE_FUNCTION<%0...%1> %0v58%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241993)
		#define UNIQUE_FUNCTION<%0...%1> %0v59%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241994)
		#define UNIQUE_FUNCTION<%0...%1> %0v5@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241995)
		#define UNIQUE_FUNCTION<%0...%1> %0v5A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241996)
		#define UNIQUE_FUNCTION<%0...%1> %0v5B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241997)
		#define UNIQUE_FUNCTION<%0...%1> %0v5C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241998)
		#define UNIQUE_FUNCTION<%0...%1> %0v5D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241999)
		#define UNIQUE_FUNCTION<%0...%1> %0v5E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242007)
	#elseif UNIQUE_SYMBOL == (241999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242000)
		#define UNIQUE_FUNCTION<%0...%1> %0v5F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242001)
		#define UNIQUE_FUNCTION<%0...%1> %0v5G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242002)
		#define UNIQUE_FUNCTION<%0...%1> %0v5H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242003)
		#define UNIQUE_FUNCTION<%0...%1> %0v5I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242004)
		#define UNIQUE_FUNCTION<%0...%1> %0v5J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242005)
		#define UNIQUE_FUNCTION<%0...%1> %0v5K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242006)
		#define UNIQUE_FUNCTION<%0...%1> %0v5L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242007)
		#define UNIQUE_FUNCTION<%0...%1> %0v5M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242015)
	#elseif UNIQUE_SYMBOL == (242007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242008)
		#define UNIQUE_FUNCTION<%0...%1> %0v5N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242009)
		#define UNIQUE_FUNCTION<%0...%1> %0v5O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242010)
		#define UNIQUE_FUNCTION<%0...%1> %0v5P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242011)
		#define UNIQUE_FUNCTION<%0...%1> %0v5Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242012)
		#define UNIQUE_FUNCTION<%0...%1> %0v5R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242013)
		#define UNIQUE_FUNCTION<%0...%1> %0v5S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242014)
		#define UNIQUE_FUNCTION<%0...%1> %0v5T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242015)
		#define UNIQUE_FUNCTION<%0...%1> %0v5U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242023)
	#elseif UNIQUE_SYMBOL == (242015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242016)
		#define UNIQUE_FUNCTION<%0...%1> %0v5V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242017)
		#define UNIQUE_FUNCTION<%0...%1> %0v5W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242018)
		#define UNIQUE_FUNCTION<%0...%1> %0v5X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242019)
		#define UNIQUE_FUNCTION<%0...%1> %0v5Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242020)
		#define UNIQUE_FUNCTION<%0...%1> %0v5Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242021)
		#define UNIQUE_FUNCTION<%0...%1> %0v5_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242022)
		#define UNIQUE_FUNCTION<%0...%1> %0v5a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242023)
		#define UNIQUE_FUNCTION<%0...%1> %0v5b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242031)
	#elseif UNIQUE_SYMBOL == (242023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242024)
		#define UNIQUE_FUNCTION<%0...%1> %0v5c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242025)
		#define UNIQUE_FUNCTION<%0...%1> %0v5d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242026)
		#define UNIQUE_FUNCTION<%0...%1> %0v5e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242027)
		#define UNIQUE_FUNCTION<%0...%1> %0v5f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242028)
		#define UNIQUE_FUNCTION<%0...%1> %0v5g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242029)
		#define UNIQUE_FUNCTION<%0...%1> %0v5h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242030)
		#define UNIQUE_FUNCTION<%0...%1> %0v5i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242031)
		#define UNIQUE_FUNCTION<%0...%1> %0v5j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242039)
	#elseif UNIQUE_SYMBOL == (242031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242032)
		#define UNIQUE_FUNCTION<%0...%1> %0v5k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242033)
		#define UNIQUE_FUNCTION<%0...%1> %0v5l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242034)
		#define UNIQUE_FUNCTION<%0...%1> %0v5m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242035)
		#define UNIQUE_FUNCTION<%0...%1> %0v5n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242036)
		#define UNIQUE_FUNCTION<%0...%1> %0v5o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242037)
		#define UNIQUE_FUNCTION<%0...%1> %0v5p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242038)
		#define UNIQUE_FUNCTION<%0...%1> %0v5q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242039)
		#define UNIQUE_FUNCTION<%0...%1> %0v5r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (242039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242040)
		#define UNIQUE_FUNCTION<%0...%1> %0v5s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242041)
		#define UNIQUE_FUNCTION<%0...%1> %0v5t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242042)
		#define UNIQUE_FUNCTION<%0...%1> %0v5u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242043)
		#define UNIQUE_FUNCTION<%0...%1> %0v5v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242044)
		#define UNIQUE_FUNCTION<%0...%1> %0v5w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242045)
		#define UNIQUE_FUNCTION<%0...%1> %0v5x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242046)
		#define UNIQUE_FUNCTION<%0...%1> %0v5y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242047)
		#define UNIQUE_FUNCTION<%0...%1> %0v5z%1
		#endinput
	#endif
#endif
