static stock const Y_UNIQUE_087296_087359_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_087296_087359
	#undef _inc_y_unique_087296_087359
#endif

#if UNIQUE_SYMBOL < (87303)
	#if UNIQUE_SYMBOL == (87295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87296)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ0%1
		#endinput
	#if UNIQUE_SYMBOL == (87296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87297)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ1%1
		#endinput
	#if UNIQUE_SYMBOL == (87297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87298)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ2%1
		#endinput
	#if UNIQUE_SYMBOL == (87298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87299)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ3%1
		#endinput
	#if UNIQUE_SYMBOL == (87299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87300)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ4%1
		#endinput
	#if UNIQUE_SYMBOL == (87300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87301)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ5%1
		#endinput
	#if UNIQUE_SYMBOL == (87301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87302)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87303)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87311)
	#elseif UNIQUE_SYMBOL == (87303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87304)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87305)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87306)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87307)
		#define UNIQUE_FUNCTION<%0...%1> %0KJA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87308)
		#define UNIQUE_FUNCTION<%0...%1> %0KJB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87309)
		#define UNIQUE_FUNCTION<%0...%1> %0KJC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87310)
		#define UNIQUE_FUNCTION<%0...%1> %0KJD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87311)
		#define UNIQUE_FUNCTION<%0...%1> %0KJE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87319)
	#elseif UNIQUE_SYMBOL == (87311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87312)
		#define UNIQUE_FUNCTION<%0...%1> %0KJF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87313)
		#define UNIQUE_FUNCTION<%0...%1> %0KJG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87314)
		#define UNIQUE_FUNCTION<%0...%1> %0KJH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87315)
		#define UNIQUE_FUNCTION<%0...%1> %0KJI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87316)
		#define UNIQUE_FUNCTION<%0...%1> %0KJJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87317)
		#define UNIQUE_FUNCTION<%0...%1> %0KJK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87318)
		#define UNIQUE_FUNCTION<%0...%1> %0KJL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87319)
		#define UNIQUE_FUNCTION<%0...%1> %0KJM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87327)
	#elseif UNIQUE_SYMBOL == (87319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87320)
		#define UNIQUE_FUNCTION<%0...%1> %0KJN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87321)
		#define UNIQUE_FUNCTION<%0...%1> %0KJO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87322)
		#define UNIQUE_FUNCTION<%0...%1> %0KJP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87323)
		#define UNIQUE_FUNCTION<%0...%1> %0KJQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87324)
		#define UNIQUE_FUNCTION<%0...%1> %0KJR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87325)
		#define UNIQUE_FUNCTION<%0...%1> %0KJS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87326)
		#define UNIQUE_FUNCTION<%0...%1> %0KJT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87327)
		#define UNIQUE_FUNCTION<%0...%1> %0KJU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87335)
	#elseif UNIQUE_SYMBOL == (87327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87328)
		#define UNIQUE_FUNCTION<%0...%1> %0KJV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87329)
		#define UNIQUE_FUNCTION<%0...%1> %0KJW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87330)
		#define UNIQUE_FUNCTION<%0...%1> %0KJX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87331)
		#define UNIQUE_FUNCTION<%0...%1> %0KJY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87332)
		#define UNIQUE_FUNCTION<%0...%1> %0KJZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87333)
		#define UNIQUE_FUNCTION<%0...%1> %0KJ_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87334)
		#define UNIQUE_FUNCTION<%0...%1> %0KJa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87335)
		#define UNIQUE_FUNCTION<%0...%1> %0KJb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87343)
	#elseif UNIQUE_SYMBOL == (87335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87336)
		#define UNIQUE_FUNCTION<%0...%1> %0KJc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87337)
		#define UNIQUE_FUNCTION<%0...%1> %0KJd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87338)
		#define UNIQUE_FUNCTION<%0...%1> %0KJe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87339)
		#define UNIQUE_FUNCTION<%0...%1> %0KJf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87340)
		#define UNIQUE_FUNCTION<%0...%1> %0KJg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87341)
		#define UNIQUE_FUNCTION<%0...%1> %0KJh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87342)
		#define UNIQUE_FUNCTION<%0...%1> %0KJi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87343)
		#define UNIQUE_FUNCTION<%0...%1> %0KJj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87351)
	#elseif UNIQUE_SYMBOL == (87343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87344)
		#define UNIQUE_FUNCTION<%0...%1> %0KJk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87345)
		#define UNIQUE_FUNCTION<%0...%1> %0KJl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87346)
		#define UNIQUE_FUNCTION<%0...%1> %0KJm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87347)
		#define UNIQUE_FUNCTION<%0...%1> %0KJn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87348)
		#define UNIQUE_FUNCTION<%0...%1> %0KJo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87349)
		#define UNIQUE_FUNCTION<%0...%1> %0KJp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87350)
		#define UNIQUE_FUNCTION<%0...%1> %0KJq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87351)
		#define UNIQUE_FUNCTION<%0...%1> %0KJr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (87351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87352)
		#define UNIQUE_FUNCTION<%0...%1> %0KJs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87353)
		#define UNIQUE_FUNCTION<%0...%1> %0KJt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87354)
		#define UNIQUE_FUNCTION<%0...%1> %0KJu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87355)
		#define UNIQUE_FUNCTION<%0...%1> %0KJv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87356)
		#define UNIQUE_FUNCTION<%0...%1> %0KJw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87357)
		#define UNIQUE_FUNCTION<%0...%1> %0KJx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87358)
		#define UNIQUE_FUNCTION<%0...%1> %0KJy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87359)
		#define UNIQUE_FUNCTION<%0...%1> %0KJz%1
		#endinput
	#endif
#endif
