static stock const Y_UNIQUE_140032_140095_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_140032_140095
	#undef _inc_y_unique_140032_140095
#endif

#if UNIQUE_SYMBOL < (140039)
	#if UNIQUE_SYMBOL == (140031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140032)
		#define UNIQUE_FUNCTION<%0...%1> %0XB0%1
		#endinput
	#if UNIQUE_SYMBOL == (140032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140033)
		#define UNIQUE_FUNCTION<%0...%1> %0XB1%1
		#endinput
	#if UNIQUE_SYMBOL == (140033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140034)
		#define UNIQUE_FUNCTION<%0...%1> %0XB2%1
		#endinput
	#if UNIQUE_SYMBOL == (140034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140035)
		#define UNIQUE_FUNCTION<%0...%1> %0XB3%1
		#endinput
	#if UNIQUE_SYMBOL == (140035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140036)
		#define UNIQUE_FUNCTION<%0...%1> %0XB4%1
		#endinput
	#if UNIQUE_SYMBOL == (140036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140037)
		#define UNIQUE_FUNCTION<%0...%1> %0XB5%1
		#endinput
	#if UNIQUE_SYMBOL == (140037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140038)
		#define UNIQUE_FUNCTION<%0...%1> %0XB6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140039)
		#define UNIQUE_FUNCTION<%0...%1> %0XB7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (140047)
	#elseif UNIQUE_SYMBOL == (140039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140040)
		#define UNIQUE_FUNCTION<%0...%1> %0XB8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140041)
		#define UNIQUE_FUNCTION<%0...%1> %0XB9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140042)
		#define UNIQUE_FUNCTION<%0...%1> %0XB@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140043)
		#define UNIQUE_FUNCTION<%0...%1> %0XBA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140044)
		#define UNIQUE_FUNCTION<%0...%1> %0XBB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140045)
		#define UNIQUE_FUNCTION<%0...%1> %0XBC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140046)
		#define UNIQUE_FUNCTION<%0...%1> %0XBD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140047)
		#define UNIQUE_FUNCTION<%0...%1> %0XBE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (140055)
	#elseif UNIQUE_SYMBOL == (140047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140048)
		#define UNIQUE_FUNCTION<%0...%1> %0XBF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140049)
		#define UNIQUE_FUNCTION<%0...%1> %0XBG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140050)
		#define UNIQUE_FUNCTION<%0...%1> %0XBH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140051)
		#define UNIQUE_FUNCTION<%0...%1> %0XBI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140052)
		#define UNIQUE_FUNCTION<%0...%1> %0XBJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140053)
		#define UNIQUE_FUNCTION<%0...%1> %0XBK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140054)
		#define UNIQUE_FUNCTION<%0...%1> %0XBL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140055)
		#define UNIQUE_FUNCTION<%0...%1> %0XBM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (140063)
	#elseif UNIQUE_SYMBOL == (140055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140056)
		#define UNIQUE_FUNCTION<%0...%1> %0XBN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140057)
		#define UNIQUE_FUNCTION<%0...%1> %0XBO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140058)
		#define UNIQUE_FUNCTION<%0...%1> %0XBP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140059)
		#define UNIQUE_FUNCTION<%0...%1> %0XBQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140060)
		#define UNIQUE_FUNCTION<%0...%1> %0XBR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140061)
		#define UNIQUE_FUNCTION<%0...%1> %0XBS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140062)
		#define UNIQUE_FUNCTION<%0...%1> %0XBT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140063)
		#define UNIQUE_FUNCTION<%0...%1> %0XBU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (140071)
	#elseif UNIQUE_SYMBOL == (140063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140064)
		#define UNIQUE_FUNCTION<%0...%1> %0XBV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140065)
		#define UNIQUE_FUNCTION<%0...%1> %0XBW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140066)
		#define UNIQUE_FUNCTION<%0...%1> %0XBX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140067)
		#define UNIQUE_FUNCTION<%0...%1> %0XBY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140068)
		#define UNIQUE_FUNCTION<%0...%1> %0XBZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140069)
		#define UNIQUE_FUNCTION<%0...%1> %0XB_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140070)
		#define UNIQUE_FUNCTION<%0...%1> %0XBa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140071)
		#define UNIQUE_FUNCTION<%0...%1> %0XBb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (140079)
	#elseif UNIQUE_SYMBOL == (140071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140072)
		#define UNIQUE_FUNCTION<%0...%1> %0XBc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140073)
		#define UNIQUE_FUNCTION<%0...%1> %0XBd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140074)
		#define UNIQUE_FUNCTION<%0...%1> %0XBe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140075)
		#define UNIQUE_FUNCTION<%0...%1> %0XBf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140076)
		#define UNIQUE_FUNCTION<%0...%1> %0XBg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140077)
		#define UNIQUE_FUNCTION<%0...%1> %0XBh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140078)
		#define UNIQUE_FUNCTION<%0...%1> %0XBi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140079)
		#define UNIQUE_FUNCTION<%0...%1> %0XBj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (140087)
	#elseif UNIQUE_SYMBOL == (140079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140080)
		#define UNIQUE_FUNCTION<%0...%1> %0XBk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140081)
		#define UNIQUE_FUNCTION<%0...%1> %0XBl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140082)
		#define UNIQUE_FUNCTION<%0...%1> %0XBm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140083)
		#define UNIQUE_FUNCTION<%0...%1> %0XBn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140084)
		#define UNIQUE_FUNCTION<%0...%1> %0XBo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140085)
		#define UNIQUE_FUNCTION<%0...%1> %0XBp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140086)
		#define UNIQUE_FUNCTION<%0...%1> %0XBq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140087)
		#define UNIQUE_FUNCTION<%0...%1> %0XBr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (140087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140088)
		#define UNIQUE_FUNCTION<%0...%1> %0XBs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140089)
		#define UNIQUE_FUNCTION<%0...%1> %0XBt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140090)
		#define UNIQUE_FUNCTION<%0...%1> %0XBu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140091)
		#define UNIQUE_FUNCTION<%0...%1> %0XBv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140092)
		#define UNIQUE_FUNCTION<%0...%1> %0XBw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140093)
		#define UNIQUE_FUNCTION<%0...%1> %0XBx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (140093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140094)
		#define UNIQUE_FUNCTION<%0...%1> %0XBy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (140095)
		#define UNIQUE_FUNCTION<%0...%1> %0XBz%1
		#endinput
	#endif
#endif
