static stock const Y_UNIQUE_058496_058559_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_058496_058559
	#undef _inc_y_unique_058496_058559
#endif

#if UNIQUE_SYMBOL < (58503)
	#if UNIQUE_SYMBOL == (58495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58496)
		#define UNIQUE_FUNCTION<%0...%1> %0DH0%1
		#endinput
	#if UNIQUE_SYMBOL == (58496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58497)
		#define UNIQUE_FUNCTION<%0...%1> %0DH1%1
		#endinput
	#if UNIQUE_SYMBOL == (58497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58498)
		#define UNIQUE_FUNCTION<%0...%1> %0DH2%1
		#endinput
	#if UNIQUE_SYMBOL == (58498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58499)
		#define UNIQUE_FUNCTION<%0...%1> %0DH3%1
		#endinput
	#if UNIQUE_SYMBOL == (58499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58500)
		#define UNIQUE_FUNCTION<%0...%1> %0DH4%1
		#endinput
	#if UNIQUE_SYMBOL == (58500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58501)
		#define UNIQUE_FUNCTION<%0...%1> %0DH5%1
		#endinput
	#if UNIQUE_SYMBOL == (58501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58502)
		#define UNIQUE_FUNCTION<%0...%1> %0DH6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58503)
		#define UNIQUE_FUNCTION<%0...%1> %0DH7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58511)
	#elseif UNIQUE_SYMBOL == (58503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58504)
		#define UNIQUE_FUNCTION<%0...%1> %0DH8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58505)
		#define UNIQUE_FUNCTION<%0...%1> %0DH9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58506)
		#define UNIQUE_FUNCTION<%0...%1> %0DH@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58507)
		#define UNIQUE_FUNCTION<%0...%1> %0DHA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58508)
		#define UNIQUE_FUNCTION<%0...%1> %0DHB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58509)
		#define UNIQUE_FUNCTION<%0...%1> %0DHC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58510)
		#define UNIQUE_FUNCTION<%0...%1> %0DHD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58511)
		#define UNIQUE_FUNCTION<%0...%1> %0DHE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58519)
	#elseif UNIQUE_SYMBOL == (58511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58512)
		#define UNIQUE_FUNCTION<%0...%1> %0DHF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58513)
		#define UNIQUE_FUNCTION<%0...%1> %0DHG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58514)
		#define UNIQUE_FUNCTION<%0...%1> %0DHH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58515)
		#define UNIQUE_FUNCTION<%0...%1> %0DHI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58516)
		#define UNIQUE_FUNCTION<%0...%1> %0DHJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58517)
		#define UNIQUE_FUNCTION<%0...%1> %0DHK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58518)
		#define UNIQUE_FUNCTION<%0...%1> %0DHL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58519)
		#define UNIQUE_FUNCTION<%0...%1> %0DHM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58527)
	#elseif UNIQUE_SYMBOL == (58519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58520)
		#define UNIQUE_FUNCTION<%0...%1> %0DHN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58521)
		#define UNIQUE_FUNCTION<%0...%1> %0DHO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58522)
		#define UNIQUE_FUNCTION<%0...%1> %0DHP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58523)
		#define UNIQUE_FUNCTION<%0...%1> %0DHQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58524)
		#define UNIQUE_FUNCTION<%0...%1> %0DHR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58525)
		#define UNIQUE_FUNCTION<%0...%1> %0DHS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58526)
		#define UNIQUE_FUNCTION<%0...%1> %0DHT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58527)
		#define UNIQUE_FUNCTION<%0...%1> %0DHU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58535)
	#elseif UNIQUE_SYMBOL == (58527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58528)
		#define UNIQUE_FUNCTION<%0...%1> %0DHV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58529)
		#define UNIQUE_FUNCTION<%0...%1> %0DHW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58530)
		#define UNIQUE_FUNCTION<%0...%1> %0DHX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58531)
		#define UNIQUE_FUNCTION<%0...%1> %0DHY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58532)
		#define UNIQUE_FUNCTION<%0...%1> %0DHZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58533)
		#define UNIQUE_FUNCTION<%0...%1> %0DH_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58534)
		#define UNIQUE_FUNCTION<%0...%1> %0DHa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58535)
		#define UNIQUE_FUNCTION<%0...%1> %0DHb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58543)
	#elseif UNIQUE_SYMBOL == (58535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58536)
		#define UNIQUE_FUNCTION<%0...%1> %0DHc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58537)
		#define UNIQUE_FUNCTION<%0...%1> %0DHd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58538)
		#define UNIQUE_FUNCTION<%0...%1> %0DHe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58539)
		#define UNIQUE_FUNCTION<%0...%1> %0DHf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58540)
		#define UNIQUE_FUNCTION<%0...%1> %0DHg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58541)
		#define UNIQUE_FUNCTION<%0...%1> %0DHh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58542)
		#define UNIQUE_FUNCTION<%0...%1> %0DHi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58543)
		#define UNIQUE_FUNCTION<%0...%1> %0DHj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58551)
	#elseif UNIQUE_SYMBOL == (58543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58544)
		#define UNIQUE_FUNCTION<%0...%1> %0DHk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58545)
		#define UNIQUE_FUNCTION<%0...%1> %0DHl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58546)
		#define UNIQUE_FUNCTION<%0...%1> %0DHm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58547)
		#define UNIQUE_FUNCTION<%0...%1> %0DHn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58548)
		#define UNIQUE_FUNCTION<%0...%1> %0DHo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58549)
		#define UNIQUE_FUNCTION<%0...%1> %0DHp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58550)
		#define UNIQUE_FUNCTION<%0...%1> %0DHq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58551)
		#define UNIQUE_FUNCTION<%0...%1> %0DHr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (58551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58552)
		#define UNIQUE_FUNCTION<%0...%1> %0DHs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58553)
		#define UNIQUE_FUNCTION<%0...%1> %0DHt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58554)
		#define UNIQUE_FUNCTION<%0...%1> %0DHu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58555)
		#define UNIQUE_FUNCTION<%0...%1> %0DHv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58556)
		#define UNIQUE_FUNCTION<%0...%1> %0DHw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58557)
		#define UNIQUE_FUNCTION<%0...%1> %0DHx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58558)
		#define UNIQUE_FUNCTION<%0...%1> %0DHy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58559)
		#define UNIQUE_FUNCTION<%0...%1> %0DHz%1
		#endinput
	#endif
#endif
