static stock const Y_UNIQUE_000000_000063_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_000000_000063
	#undef _inc_y_unique_000000_000063
#endif

#if UNIQUE_SYMBOL < (7)
	#if UNIQUE_SYMBOL == (-1)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (0)
		#define UNIQUE_FUNCTION<%0...%1> %0000%1
		#endinput
	#if UNIQUE_SYMBOL == (0)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1)
		#define UNIQUE_FUNCTION<%0...%1> %0001%1
		#endinput
	#if UNIQUE_SYMBOL == (1)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (2)
		#define UNIQUE_FUNCTION<%0...%1> %0002%1
		#endinput
	#if UNIQUE_SYMBOL == (2)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3)
		#define UNIQUE_FUNCTION<%0...%1> %0003%1
		#endinput
	#if UNIQUE_SYMBOL == (3)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (4)
		#define UNIQUE_FUNCTION<%0...%1> %0004%1
		#endinput
	#if UNIQUE_SYMBOL == (4)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (5)
		#define UNIQUE_FUNCTION<%0...%1> %0005%1
		#endinput
	#if UNIQUE_SYMBOL == (5)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6)
		#define UNIQUE_FUNCTION<%0...%1> %0006%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7)
		#define UNIQUE_FUNCTION<%0...%1> %0007%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15)
	#elseif UNIQUE_SYMBOL == (7)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (8)
		#define UNIQUE_FUNCTION<%0...%1> %0008%1
		#endinput
	#elseif UNIQUE_SYMBOL == (8)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9)
		#define UNIQUE_FUNCTION<%0...%1> %0009%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10)
		#define UNIQUE_FUNCTION<%0...%1> %000@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11)
		#define UNIQUE_FUNCTION<%0...%1> %000A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12)
		#define UNIQUE_FUNCTION<%0...%1> %000B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (13)
		#define UNIQUE_FUNCTION<%0...%1> %000C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (13)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (14)
		#define UNIQUE_FUNCTION<%0...%1> %000D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15)
		#define UNIQUE_FUNCTION<%0...%1> %000E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (23)
	#elseif UNIQUE_SYMBOL == (15)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16)
		#define UNIQUE_FUNCTION<%0...%1> %000F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17)
		#define UNIQUE_FUNCTION<%0...%1> %000G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (18)
		#define UNIQUE_FUNCTION<%0...%1> %000H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (18)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19)
		#define UNIQUE_FUNCTION<%0...%1> %000I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20)
		#define UNIQUE_FUNCTION<%0...%1> %000J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (21)
		#define UNIQUE_FUNCTION<%0...%1> %000K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (21)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22)
		#define UNIQUE_FUNCTION<%0...%1> %000L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (23)
		#define UNIQUE_FUNCTION<%0...%1> %000M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31)
	#elseif UNIQUE_SYMBOL == (23)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24)
		#define UNIQUE_FUNCTION<%0...%1> %000N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25)
		#define UNIQUE_FUNCTION<%0...%1> %000O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26)
		#define UNIQUE_FUNCTION<%0...%1> %000P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (27)
		#define UNIQUE_FUNCTION<%0...%1> %000Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (27)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28)
		#define UNIQUE_FUNCTION<%0...%1> %000R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29)
		#define UNIQUE_FUNCTION<%0...%1> %000S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30)
		#define UNIQUE_FUNCTION<%0...%1> %000T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31)
		#define UNIQUE_FUNCTION<%0...%1> %000U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (39)
	#elseif UNIQUE_SYMBOL == (31)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32)
		#define UNIQUE_FUNCTION<%0...%1> %000V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33)
		#define UNIQUE_FUNCTION<%0...%1> %000W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34)
		#define UNIQUE_FUNCTION<%0...%1> %000X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (35)
		#define UNIQUE_FUNCTION<%0...%1> %000Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (35)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36)
		#define UNIQUE_FUNCTION<%0...%1> %000Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (37)
		#define UNIQUE_FUNCTION<%0...%1> %000_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (37)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (38)
		#define UNIQUE_FUNCTION<%0...%1> %000a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (39)
		#define UNIQUE_FUNCTION<%0...%1> %000b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47)
	#elseif UNIQUE_SYMBOL == (39)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40)
		#define UNIQUE_FUNCTION<%0...%1> %000c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (41)
		#define UNIQUE_FUNCTION<%0...%1> %000d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (41)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42)
		#define UNIQUE_FUNCTION<%0...%1> %000e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43)
		#define UNIQUE_FUNCTION<%0...%1> %000f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (44)
		#define UNIQUE_FUNCTION<%0...%1> %000g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (44)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45)
		#define UNIQUE_FUNCTION<%0...%1> %000h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (46)
		#define UNIQUE_FUNCTION<%0...%1> %000i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47)
		#define UNIQUE_FUNCTION<%0...%1> %000j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55)
	#elseif UNIQUE_SYMBOL == (47)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48)
		#define UNIQUE_FUNCTION<%0...%1> %000k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (49)
		#define UNIQUE_FUNCTION<%0...%1> %000l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (49)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50)
		#define UNIQUE_FUNCTION<%0...%1> %000m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51)
		#define UNIQUE_FUNCTION<%0...%1> %000n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52)
		#define UNIQUE_FUNCTION<%0...%1> %000o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (53)
		#define UNIQUE_FUNCTION<%0...%1> %000p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (53)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54)
		#define UNIQUE_FUNCTION<%0...%1> %000q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55)
		#define UNIQUE_FUNCTION<%0...%1> %000r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (55)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (56)
		#define UNIQUE_FUNCTION<%0...%1> %000s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (56)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (57)
		#define UNIQUE_FUNCTION<%0...%1> %000t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (57)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58)
		#define UNIQUE_FUNCTION<%0...%1> %000u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (59)
		#define UNIQUE_FUNCTION<%0...%1> %000v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (59)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60)
		#define UNIQUE_FUNCTION<%0...%1> %000w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61)
		#define UNIQUE_FUNCTION<%0...%1> %000x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62)
		#define UNIQUE_FUNCTION<%0...%1> %000y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63)
		#define UNIQUE_FUNCTION<%0...%1> %000z%1
		#endinput
	#endif
#endif
