static stock const Y_UNIQUE_107136_107199_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_107136_107199
	#undef _inc_y_unique_107136_107199
#endif

#if UNIQUE_SYMBOL < (107143)
	#if UNIQUE_SYMBOL == (107135)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107136)
		#define UNIQUE_FUNCTION<%0...%1> %0P@0%1
		#endinput
	#if UNIQUE_SYMBOL == (107136)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107137)
		#define UNIQUE_FUNCTION<%0...%1> %0P@1%1
		#endinput
	#if UNIQUE_SYMBOL == (107137)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107138)
		#define UNIQUE_FUNCTION<%0...%1> %0P@2%1
		#endinput
	#if UNIQUE_SYMBOL == (107138)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107139)
		#define UNIQUE_FUNCTION<%0...%1> %0P@3%1
		#endinput
	#if UNIQUE_SYMBOL == (107139)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107140)
		#define UNIQUE_FUNCTION<%0...%1> %0P@4%1
		#endinput
	#if UNIQUE_SYMBOL == (107140)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107141)
		#define UNIQUE_FUNCTION<%0...%1> %0P@5%1
		#endinput
	#if UNIQUE_SYMBOL == (107141)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107142)
		#define UNIQUE_FUNCTION<%0...%1> %0P@6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107143)
		#define UNIQUE_FUNCTION<%0...%1> %0P@7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107151)
	#elseif UNIQUE_SYMBOL == (107143)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107144)
		#define UNIQUE_FUNCTION<%0...%1> %0P@8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107144)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107145)
		#define UNIQUE_FUNCTION<%0...%1> %0P@9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107145)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107146)
		#define UNIQUE_FUNCTION<%0...%1> %0P@@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107146)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107147)
		#define UNIQUE_FUNCTION<%0...%1> %0P@A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107147)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107148)
		#define UNIQUE_FUNCTION<%0...%1> %0P@B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107148)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107149)
		#define UNIQUE_FUNCTION<%0...%1> %0P@C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107149)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107150)
		#define UNIQUE_FUNCTION<%0...%1> %0P@D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107151)
		#define UNIQUE_FUNCTION<%0...%1> %0P@E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107159)
	#elseif UNIQUE_SYMBOL == (107151)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107152)
		#define UNIQUE_FUNCTION<%0...%1> %0P@F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107152)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107153)
		#define UNIQUE_FUNCTION<%0...%1> %0P@G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107153)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107154)
		#define UNIQUE_FUNCTION<%0...%1> %0P@H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107154)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107155)
		#define UNIQUE_FUNCTION<%0...%1> %0P@I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107155)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107156)
		#define UNIQUE_FUNCTION<%0...%1> %0P@J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107156)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107157)
		#define UNIQUE_FUNCTION<%0...%1> %0P@K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107157)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107158)
		#define UNIQUE_FUNCTION<%0...%1> %0P@L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107159)
		#define UNIQUE_FUNCTION<%0...%1> %0P@M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107167)
	#elseif UNIQUE_SYMBOL == (107159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107160)
		#define UNIQUE_FUNCTION<%0...%1> %0P@N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107161)
		#define UNIQUE_FUNCTION<%0...%1> %0P@O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107162)
		#define UNIQUE_FUNCTION<%0...%1> %0P@P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107163)
		#define UNIQUE_FUNCTION<%0...%1> %0P@Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107164)
		#define UNIQUE_FUNCTION<%0...%1> %0P@R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107165)
		#define UNIQUE_FUNCTION<%0...%1> %0P@S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107166)
		#define UNIQUE_FUNCTION<%0...%1> %0P@T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107167)
		#define UNIQUE_FUNCTION<%0...%1> %0P@U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107175)
	#elseif UNIQUE_SYMBOL == (107167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107168)
		#define UNIQUE_FUNCTION<%0...%1> %0P@V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107169)
		#define UNIQUE_FUNCTION<%0...%1> %0P@W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107170)
		#define UNIQUE_FUNCTION<%0...%1> %0P@X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107171)
		#define UNIQUE_FUNCTION<%0...%1> %0P@Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107172)
		#define UNIQUE_FUNCTION<%0...%1> %0P@Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107173)
		#define UNIQUE_FUNCTION<%0...%1> %0P@_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107174)
		#define UNIQUE_FUNCTION<%0...%1> %0P@a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107175)
		#define UNIQUE_FUNCTION<%0...%1> %0P@b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107183)
	#elseif UNIQUE_SYMBOL == (107175)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107176)
		#define UNIQUE_FUNCTION<%0...%1> %0P@c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107176)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107177)
		#define UNIQUE_FUNCTION<%0...%1> %0P@d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107177)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107178)
		#define UNIQUE_FUNCTION<%0...%1> %0P@e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107178)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107179)
		#define UNIQUE_FUNCTION<%0...%1> %0P@f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107179)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107180)
		#define UNIQUE_FUNCTION<%0...%1> %0P@g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107180)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107181)
		#define UNIQUE_FUNCTION<%0...%1> %0P@h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107181)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107182)
		#define UNIQUE_FUNCTION<%0...%1> %0P@i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107183)
		#define UNIQUE_FUNCTION<%0...%1> %0P@j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107191)
	#elseif UNIQUE_SYMBOL == (107183)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107184)
		#define UNIQUE_FUNCTION<%0...%1> %0P@k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107184)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107185)
		#define UNIQUE_FUNCTION<%0...%1> %0P@l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107185)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107186)
		#define UNIQUE_FUNCTION<%0...%1> %0P@m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107186)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107187)
		#define UNIQUE_FUNCTION<%0...%1> %0P@n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107187)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107188)
		#define UNIQUE_FUNCTION<%0...%1> %0P@o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107188)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107189)
		#define UNIQUE_FUNCTION<%0...%1> %0P@p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107189)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107190)
		#define UNIQUE_FUNCTION<%0...%1> %0P@q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107191)
		#define UNIQUE_FUNCTION<%0...%1> %0P@r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (107191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107192)
		#define UNIQUE_FUNCTION<%0...%1> %0P@s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107193)
		#define UNIQUE_FUNCTION<%0...%1> %0P@t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107194)
		#define UNIQUE_FUNCTION<%0...%1> %0P@u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107195)
		#define UNIQUE_FUNCTION<%0...%1> %0P@v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107196)
		#define UNIQUE_FUNCTION<%0...%1> %0P@w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107197)
		#define UNIQUE_FUNCTION<%0...%1> %0P@x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107198)
		#define UNIQUE_FUNCTION<%0...%1> %0P@y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107199)
		#define UNIQUE_FUNCTION<%0...%1> %0P@z%1
		#endinput
	#endif
#endif
