static stock const Y_UNIQUE_187840_187903_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_187840_187903
	#undef _inc_y_unique_187840_187903
#endif

#if UNIQUE_SYMBOL < (187847)
	#if UNIQUE_SYMBOL == (187839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187840)
		#define UNIQUE_FUNCTION<%0...%1> %0hr0%1
		#endinput
	#if UNIQUE_SYMBOL == (187840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187841)
		#define UNIQUE_FUNCTION<%0...%1> %0hr1%1
		#endinput
	#if UNIQUE_SYMBOL == (187841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187842)
		#define UNIQUE_FUNCTION<%0...%1> %0hr2%1
		#endinput
	#if UNIQUE_SYMBOL == (187842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187843)
		#define UNIQUE_FUNCTION<%0...%1> %0hr3%1
		#endinput
	#if UNIQUE_SYMBOL == (187843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187844)
		#define UNIQUE_FUNCTION<%0...%1> %0hr4%1
		#endinput
	#if UNIQUE_SYMBOL == (187844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187845)
		#define UNIQUE_FUNCTION<%0...%1> %0hr5%1
		#endinput
	#if UNIQUE_SYMBOL == (187845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187846)
		#define UNIQUE_FUNCTION<%0...%1> %0hr6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187847)
		#define UNIQUE_FUNCTION<%0...%1> %0hr7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (187855)
	#elseif UNIQUE_SYMBOL == (187847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187848)
		#define UNIQUE_FUNCTION<%0...%1> %0hr8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187849)
		#define UNIQUE_FUNCTION<%0...%1> %0hr9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187850)
		#define UNIQUE_FUNCTION<%0...%1> %0hr@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187851)
		#define UNIQUE_FUNCTION<%0...%1> %0hrA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187852)
		#define UNIQUE_FUNCTION<%0...%1> %0hrB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187853)
		#define UNIQUE_FUNCTION<%0...%1> %0hrC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187854)
		#define UNIQUE_FUNCTION<%0...%1> %0hrD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187855)
		#define UNIQUE_FUNCTION<%0...%1> %0hrE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (187863)
	#elseif UNIQUE_SYMBOL == (187855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187856)
		#define UNIQUE_FUNCTION<%0...%1> %0hrF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187857)
		#define UNIQUE_FUNCTION<%0...%1> %0hrG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187858)
		#define UNIQUE_FUNCTION<%0...%1> %0hrH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187859)
		#define UNIQUE_FUNCTION<%0...%1> %0hrI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187860)
		#define UNIQUE_FUNCTION<%0...%1> %0hrJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187861)
		#define UNIQUE_FUNCTION<%0...%1> %0hrK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187862)
		#define UNIQUE_FUNCTION<%0...%1> %0hrL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187863)
		#define UNIQUE_FUNCTION<%0...%1> %0hrM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (187871)
	#elseif UNIQUE_SYMBOL == (187863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187864)
		#define UNIQUE_FUNCTION<%0...%1> %0hrN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187865)
		#define UNIQUE_FUNCTION<%0...%1> %0hrO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187866)
		#define UNIQUE_FUNCTION<%0...%1> %0hrP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187867)
		#define UNIQUE_FUNCTION<%0...%1> %0hrQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187868)
		#define UNIQUE_FUNCTION<%0...%1> %0hrR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187869)
		#define UNIQUE_FUNCTION<%0...%1> %0hrS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187870)
		#define UNIQUE_FUNCTION<%0...%1> %0hrT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187871)
		#define UNIQUE_FUNCTION<%0...%1> %0hrU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (187879)
	#elseif UNIQUE_SYMBOL == (187871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187872)
		#define UNIQUE_FUNCTION<%0...%1> %0hrV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187873)
		#define UNIQUE_FUNCTION<%0...%1> %0hrW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187874)
		#define UNIQUE_FUNCTION<%0...%1> %0hrX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187875)
		#define UNIQUE_FUNCTION<%0...%1> %0hrY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187876)
		#define UNIQUE_FUNCTION<%0...%1> %0hrZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187877)
		#define UNIQUE_FUNCTION<%0...%1> %0hr_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187878)
		#define UNIQUE_FUNCTION<%0...%1> %0hra%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187879)
		#define UNIQUE_FUNCTION<%0...%1> %0hrb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (187887)
	#elseif UNIQUE_SYMBOL == (187879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187880)
		#define UNIQUE_FUNCTION<%0...%1> %0hrc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187881)
		#define UNIQUE_FUNCTION<%0...%1> %0hrd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187882)
		#define UNIQUE_FUNCTION<%0...%1> %0hre%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187883)
		#define UNIQUE_FUNCTION<%0...%1> %0hrf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187884)
		#define UNIQUE_FUNCTION<%0...%1> %0hrg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187885)
		#define UNIQUE_FUNCTION<%0...%1> %0hrh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187886)
		#define UNIQUE_FUNCTION<%0...%1> %0hri%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187887)
		#define UNIQUE_FUNCTION<%0...%1> %0hrj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (187895)
	#elseif UNIQUE_SYMBOL == (187887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187888)
		#define UNIQUE_FUNCTION<%0...%1> %0hrk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187889)
		#define UNIQUE_FUNCTION<%0...%1> %0hrl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187890)
		#define UNIQUE_FUNCTION<%0...%1> %0hrm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187891)
		#define UNIQUE_FUNCTION<%0...%1> %0hrn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187892)
		#define UNIQUE_FUNCTION<%0...%1> %0hro%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187893)
		#define UNIQUE_FUNCTION<%0...%1> %0hrp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187894)
		#define UNIQUE_FUNCTION<%0...%1> %0hrq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187895)
		#define UNIQUE_FUNCTION<%0...%1> %0hrr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (187895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187896)
		#define UNIQUE_FUNCTION<%0...%1> %0hrs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187897)
		#define UNIQUE_FUNCTION<%0...%1> %0hrt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187898)
		#define UNIQUE_FUNCTION<%0...%1> %0hru%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187899)
		#define UNIQUE_FUNCTION<%0...%1> %0hrv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187900)
		#define UNIQUE_FUNCTION<%0...%1> %0hrw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187901)
		#define UNIQUE_FUNCTION<%0...%1> %0hrx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (187901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187902)
		#define UNIQUE_FUNCTION<%0...%1> %0hry%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (187903)
		#define UNIQUE_FUNCTION<%0...%1> %0hrz%1
		#endinput
	#endif
#endif
