static stock const Y_UNIQUE_098432_098495_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_098432_098495
	#undef _inc_y_unique_098432_098495
#endif

#if UNIQUE_SYMBOL < (98439)
	#if UNIQUE_SYMBOL == (98431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98432)
		#define UNIQUE_FUNCTION<%0...%1> %0N20%1
		#endinput
	#if UNIQUE_SYMBOL == (98432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98433)
		#define UNIQUE_FUNCTION<%0...%1> %0N21%1
		#endinput
	#if UNIQUE_SYMBOL == (98433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98434)
		#define UNIQUE_FUNCTION<%0...%1> %0N22%1
		#endinput
	#if UNIQUE_SYMBOL == (98434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98435)
		#define UNIQUE_FUNCTION<%0...%1> %0N23%1
		#endinput
	#if UNIQUE_SYMBOL == (98435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98436)
		#define UNIQUE_FUNCTION<%0...%1> %0N24%1
		#endinput
	#if UNIQUE_SYMBOL == (98436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98437)
		#define UNIQUE_FUNCTION<%0...%1> %0N25%1
		#endinput
	#if UNIQUE_SYMBOL == (98437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98438)
		#define UNIQUE_FUNCTION<%0...%1> %0N26%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98439)
		#define UNIQUE_FUNCTION<%0...%1> %0N27%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98447)
	#elseif UNIQUE_SYMBOL == (98439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98440)
		#define UNIQUE_FUNCTION<%0...%1> %0N28%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98441)
		#define UNIQUE_FUNCTION<%0...%1> %0N29%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98442)
		#define UNIQUE_FUNCTION<%0...%1> %0N2@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98443)
		#define UNIQUE_FUNCTION<%0...%1> %0N2A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98444)
		#define UNIQUE_FUNCTION<%0...%1> %0N2B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98445)
		#define UNIQUE_FUNCTION<%0...%1> %0N2C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98446)
		#define UNIQUE_FUNCTION<%0...%1> %0N2D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98447)
		#define UNIQUE_FUNCTION<%0...%1> %0N2E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98455)
	#elseif UNIQUE_SYMBOL == (98447)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98448)
		#define UNIQUE_FUNCTION<%0...%1> %0N2F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98448)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98449)
		#define UNIQUE_FUNCTION<%0...%1> %0N2G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98449)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98450)
		#define UNIQUE_FUNCTION<%0...%1> %0N2H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98450)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98451)
		#define UNIQUE_FUNCTION<%0...%1> %0N2I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98451)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98452)
		#define UNIQUE_FUNCTION<%0...%1> %0N2J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98452)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98453)
		#define UNIQUE_FUNCTION<%0...%1> %0N2K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98453)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98454)
		#define UNIQUE_FUNCTION<%0...%1> %0N2L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98455)
		#define UNIQUE_FUNCTION<%0...%1> %0N2M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98463)
	#elseif UNIQUE_SYMBOL == (98455)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98456)
		#define UNIQUE_FUNCTION<%0...%1> %0N2N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98456)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98457)
		#define UNIQUE_FUNCTION<%0...%1> %0N2O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98457)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98458)
		#define UNIQUE_FUNCTION<%0...%1> %0N2P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98458)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98459)
		#define UNIQUE_FUNCTION<%0...%1> %0N2Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98459)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98460)
		#define UNIQUE_FUNCTION<%0...%1> %0N2R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98460)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98461)
		#define UNIQUE_FUNCTION<%0...%1> %0N2S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98461)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98462)
		#define UNIQUE_FUNCTION<%0...%1> %0N2T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98463)
		#define UNIQUE_FUNCTION<%0...%1> %0N2U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98471)
	#elseif UNIQUE_SYMBOL == (98463)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98464)
		#define UNIQUE_FUNCTION<%0...%1> %0N2V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98464)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98465)
		#define UNIQUE_FUNCTION<%0...%1> %0N2W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98465)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98466)
		#define UNIQUE_FUNCTION<%0...%1> %0N2X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98466)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98467)
		#define UNIQUE_FUNCTION<%0...%1> %0N2Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98467)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98468)
		#define UNIQUE_FUNCTION<%0...%1> %0N2Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98468)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98469)
		#define UNIQUE_FUNCTION<%0...%1> %0N2_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98469)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98470)
		#define UNIQUE_FUNCTION<%0...%1> %0N2a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98471)
		#define UNIQUE_FUNCTION<%0...%1> %0N2b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98479)
	#elseif UNIQUE_SYMBOL == (98471)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98472)
		#define UNIQUE_FUNCTION<%0...%1> %0N2c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98472)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98473)
		#define UNIQUE_FUNCTION<%0...%1> %0N2d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98473)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98474)
		#define UNIQUE_FUNCTION<%0...%1> %0N2e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98474)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98475)
		#define UNIQUE_FUNCTION<%0...%1> %0N2f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98475)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98476)
		#define UNIQUE_FUNCTION<%0...%1> %0N2g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98476)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98477)
		#define UNIQUE_FUNCTION<%0...%1> %0N2h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98477)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98478)
		#define UNIQUE_FUNCTION<%0...%1> %0N2i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98479)
		#define UNIQUE_FUNCTION<%0...%1> %0N2j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98487)
	#elseif UNIQUE_SYMBOL == (98479)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98480)
		#define UNIQUE_FUNCTION<%0...%1> %0N2k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98480)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98481)
		#define UNIQUE_FUNCTION<%0...%1> %0N2l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98481)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98482)
		#define UNIQUE_FUNCTION<%0...%1> %0N2m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98482)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98483)
		#define UNIQUE_FUNCTION<%0...%1> %0N2n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98483)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98484)
		#define UNIQUE_FUNCTION<%0...%1> %0N2o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98484)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98485)
		#define UNIQUE_FUNCTION<%0...%1> %0N2p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98485)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98486)
		#define UNIQUE_FUNCTION<%0...%1> %0N2q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98487)
		#define UNIQUE_FUNCTION<%0...%1> %0N2r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (98487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98488)
		#define UNIQUE_FUNCTION<%0...%1> %0N2s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98489)
		#define UNIQUE_FUNCTION<%0...%1> %0N2t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98490)
		#define UNIQUE_FUNCTION<%0...%1> %0N2u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98491)
		#define UNIQUE_FUNCTION<%0...%1> %0N2v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98492)
		#define UNIQUE_FUNCTION<%0...%1> %0N2w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98493)
		#define UNIQUE_FUNCTION<%0...%1> %0N2x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98494)
		#define UNIQUE_FUNCTION<%0...%1> %0N2y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98495)
		#define UNIQUE_FUNCTION<%0...%1> %0N2z%1
		#endinput
	#endif
#endif
