static stock const Y_UNIQUE_015168_015231_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_015168_015231
	#undef _inc_y_unique_015168_015231
#endif

#if UNIQUE_SYMBOL < (15175)
	#if UNIQUE_SYMBOL == (15167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15168)
		#define UNIQUE_FUNCTION<%0...%1> %03h0%1
		#endinput
	#if UNIQUE_SYMBOL == (15168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15169)
		#define UNIQUE_FUNCTION<%0...%1> %03h1%1
		#endinput
	#if UNIQUE_SYMBOL == (15169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15170)
		#define UNIQUE_FUNCTION<%0...%1> %03h2%1
		#endinput
	#if UNIQUE_SYMBOL == (15170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15171)
		#define UNIQUE_FUNCTION<%0...%1> %03h3%1
		#endinput
	#if UNIQUE_SYMBOL == (15171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15172)
		#define UNIQUE_FUNCTION<%0...%1> %03h4%1
		#endinput
	#if UNIQUE_SYMBOL == (15172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15173)
		#define UNIQUE_FUNCTION<%0...%1> %03h5%1
		#endinput
	#if UNIQUE_SYMBOL == (15173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15174)
		#define UNIQUE_FUNCTION<%0...%1> %03h6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15175)
		#define UNIQUE_FUNCTION<%0...%1> %03h7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15183)
	#elseif UNIQUE_SYMBOL == (15175)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15176)
		#define UNIQUE_FUNCTION<%0...%1> %03h8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15176)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15177)
		#define UNIQUE_FUNCTION<%0...%1> %03h9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15177)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15178)
		#define UNIQUE_FUNCTION<%0...%1> %03h@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15178)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15179)
		#define UNIQUE_FUNCTION<%0...%1> %03hA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15179)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15180)
		#define UNIQUE_FUNCTION<%0...%1> %03hB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15180)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15181)
		#define UNIQUE_FUNCTION<%0...%1> %03hC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15181)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15182)
		#define UNIQUE_FUNCTION<%0...%1> %03hD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15183)
		#define UNIQUE_FUNCTION<%0...%1> %03hE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15191)
	#elseif UNIQUE_SYMBOL == (15183)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15184)
		#define UNIQUE_FUNCTION<%0...%1> %03hF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15184)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15185)
		#define UNIQUE_FUNCTION<%0...%1> %03hG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15185)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15186)
		#define UNIQUE_FUNCTION<%0...%1> %03hH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15186)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15187)
		#define UNIQUE_FUNCTION<%0...%1> %03hI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15187)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15188)
		#define UNIQUE_FUNCTION<%0...%1> %03hJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15188)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15189)
		#define UNIQUE_FUNCTION<%0...%1> %03hK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15189)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15190)
		#define UNIQUE_FUNCTION<%0...%1> %03hL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15191)
		#define UNIQUE_FUNCTION<%0...%1> %03hM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15199)
	#elseif UNIQUE_SYMBOL == (15191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15192)
		#define UNIQUE_FUNCTION<%0...%1> %03hN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15193)
		#define UNIQUE_FUNCTION<%0...%1> %03hO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15194)
		#define UNIQUE_FUNCTION<%0...%1> %03hP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15195)
		#define UNIQUE_FUNCTION<%0...%1> %03hQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15196)
		#define UNIQUE_FUNCTION<%0...%1> %03hR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15197)
		#define UNIQUE_FUNCTION<%0...%1> %03hS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15198)
		#define UNIQUE_FUNCTION<%0...%1> %03hT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15199)
		#define UNIQUE_FUNCTION<%0...%1> %03hU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15207)
	#elseif UNIQUE_SYMBOL == (15199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15200)
		#define UNIQUE_FUNCTION<%0...%1> %03hV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15201)
		#define UNIQUE_FUNCTION<%0...%1> %03hW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15202)
		#define UNIQUE_FUNCTION<%0...%1> %03hX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15203)
		#define UNIQUE_FUNCTION<%0...%1> %03hY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15204)
		#define UNIQUE_FUNCTION<%0...%1> %03hZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15205)
		#define UNIQUE_FUNCTION<%0...%1> %03h_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15206)
		#define UNIQUE_FUNCTION<%0...%1> %03ha%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15207)
		#define UNIQUE_FUNCTION<%0...%1> %03hb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15215)
	#elseif UNIQUE_SYMBOL == (15207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15208)
		#define UNIQUE_FUNCTION<%0...%1> %03hc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15209)
		#define UNIQUE_FUNCTION<%0...%1> %03hd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15210)
		#define UNIQUE_FUNCTION<%0...%1> %03he%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15211)
		#define UNIQUE_FUNCTION<%0...%1> %03hf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15212)
		#define UNIQUE_FUNCTION<%0...%1> %03hg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15213)
		#define UNIQUE_FUNCTION<%0...%1> %03hh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15214)
		#define UNIQUE_FUNCTION<%0...%1> %03hi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15215)
		#define UNIQUE_FUNCTION<%0...%1> %03hj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15223)
	#elseif UNIQUE_SYMBOL == (15215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15216)
		#define UNIQUE_FUNCTION<%0...%1> %03hk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15217)
		#define UNIQUE_FUNCTION<%0...%1> %03hl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15218)
		#define UNIQUE_FUNCTION<%0...%1> %03hm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15219)
		#define UNIQUE_FUNCTION<%0...%1> %03hn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15220)
		#define UNIQUE_FUNCTION<%0...%1> %03ho%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15221)
		#define UNIQUE_FUNCTION<%0...%1> %03hp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15222)
		#define UNIQUE_FUNCTION<%0...%1> %03hq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15223)
		#define UNIQUE_FUNCTION<%0...%1> %03hr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (15223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15224)
		#define UNIQUE_FUNCTION<%0...%1> %03hs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15225)
		#define UNIQUE_FUNCTION<%0...%1> %03ht%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15226)
		#define UNIQUE_FUNCTION<%0...%1> %03hu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15227)
		#define UNIQUE_FUNCTION<%0...%1> %03hv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15228)
		#define UNIQUE_FUNCTION<%0...%1> %03hw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15229)
		#define UNIQUE_FUNCTION<%0...%1> %03hx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15230)
		#define UNIQUE_FUNCTION<%0...%1> %03hy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15231)
		#define UNIQUE_FUNCTION<%0...%1> %03hz%1
		#endinput
	#endif
#endif
