static stock const Y_UNIQUE_250880_250943_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_250880_250943
	#undef _inc_y_unique_250880_250943
#endif

#if UNIQUE_SYMBOL < (250887)
	#if UNIQUE_SYMBOL == (250879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250880)
		#define UNIQUE_FUNCTION<%0...%1> %0xF0%1
		#endinput
	#if UNIQUE_SYMBOL == (250880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250881)
		#define UNIQUE_FUNCTION<%0...%1> %0xF1%1
		#endinput
	#if UNIQUE_SYMBOL == (250881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250882)
		#define UNIQUE_FUNCTION<%0...%1> %0xF2%1
		#endinput
	#if UNIQUE_SYMBOL == (250882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250883)
		#define UNIQUE_FUNCTION<%0...%1> %0xF3%1
		#endinput
	#if UNIQUE_SYMBOL == (250883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250884)
		#define UNIQUE_FUNCTION<%0...%1> %0xF4%1
		#endinput
	#if UNIQUE_SYMBOL == (250884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250885)
		#define UNIQUE_FUNCTION<%0...%1> %0xF5%1
		#endinput
	#if UNIQUE_SYMBOL == (250885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250886)
		#define UNIQUE_FUNCTION<%0...%1> %0xF6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250887)
		#define UNIQUE_FUNCTION<%0...%1> %0xF7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250895)
	#elseif UNIQUE_SYMBOL == (250887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250888)
		#define UNIQUE_FUNCTION<%0...%1> %0xF8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250889)
		#define UNIQUE_FUNCTION<%0...%1> %0xF9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250890)
		#define UNIQUE_FUNCTION<%0...%1> %0xF@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250891)
		#define UNIQUE_FUNCTION<%0...%1> %0xFA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250892)
		#define UNIQUE_FUNCTION<%0...%1> %0xFB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250893)
		#define UNIQUE_FUNCTION<%0...%1> %0xFC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250894)
		#define UNIQUE_FUNCTION<%0...%1> %0xFD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250895)
		#define UNIQUE_FUNCTION<%0...%1> %0xFE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250903)
	#elseif UNIQUE_SYMBOL == (250895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250896)
		#define UNIQUE_FUNCTION<%0...%1> %0xFF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250897)
		#define UNIQUE_FUNCTION<%0...%1> %0xFG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250898)
		#define UNIQUE_FUNCTION<%0...%1> %0xFH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250899)
		#define UNIQUE_FUNCTION<%0...%1> %0xFI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250900)
		#define UNIQUE_FUNCTION<%0...%1> %0xFJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250901)
		#define UNIQUE_FUNCTION<%0...%1> %0xFK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250902)
		#define UNIQUE_FUNCTION<%0...%1> %0xFL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250903)
		#define UNIQUE_FUNCTION<%0...%1> %0xFM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250911)
	#elseif UNIQUE_SYMBOL == (250903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250904)
		#define UNIQUE_FUNCTION<%0...%1> %0xFN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250905)
		#define UNIQUE_FUNCTION<%0...%1> %0xFO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250906)
		#define UNIQUE_FUNCTION<%0...%1> %0xFP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250907)
		#define UNIQUE_FUNCTION<%0...%1> %0xFQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250908)
		#define UNIQUE_FUNCTION<%0...%1> %0xFR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250909)
		#define UNIQUE_FUNCTION<%0...%1> %0xFS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250910)
		#define UNIQUE_FUNCTION<%0...%1> %0xFT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250911)
		#define UNIQUE_FUNCTION<%0...%1> %0xFU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250919)
	#elseif UNIQUE_SYMBOL == (250911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250912)
		#define UNIQUE_FUNCTION<%0...%1> %0xFV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250913)
		#define UNIQUE_FUNCTION<%0...%1> %0xFW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250914)
		#define UNIQUE_FUNCTION<%0...%1> %0xFX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250915)
		#define UNIQUE_FUNCTION<%0...%1> %0xFY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250916)
		#define UNIQUE_FUNCTION<%0...%1> %0xFZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250917)
		#define UNIQUE_FUNCTION<%0...%1> %0xF_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250918)
		#define UNIQUE_FUNCTION<%0...%1> %0xFa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250919)
		#define UNIQUE_FUNCTION<%0...%1> %0xFb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250927)
	#elseif UNIQUE_SYMBOL == (250919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250920)
		#define UNIQUE_FUNCTION<%0...%1> %0xFc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250921)
		#define UNIQUE_FUNCTION<%0...%1> %0xFd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250922)
		#define UNIQUE_FUNCTION<%0...%1> %0xFe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250923)
		#define UNIQUE_FUNCTION<%0...%1> %0xFf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250924)
		#define UNIQUE_FUNCTION<%0...%1> %0xFg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250925)
		#define UNIQUE_FUNCTION<%0...%1> %0xFh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250926)
		#define UNIQUE_FUNCTION<%0...%1> %0xFi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250927)
		#define UNIQUE_FUNCTION<%0...%1> %0xFj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250935)
	#elseif UNIQUE_SYMBOL == (250927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250928)
		#define UNIQUE_FUNCTION<%0...%1> %0xFk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250929)
		#define UNIQUE_FUNCTION<%0...%1> %0xFl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250930)
		#define UNIQUE_FUNCTION<%0...%1> %0xFm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250931)
		#define UNIQUE_FUNCTION<%0...%1> %0xFn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250932)
		#define UNIQUE_FUNCTION<%0...%1> %0xFo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250933)
		#define UNIQUE_FUNCTION<%0...%1> %0xFp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250934)
		#define UNIQUE_FUNCTION<%0...%1> %0xFq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250935)
		#define UNIQUE_FUNCTION<%0...%1> %0xFr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (250935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250936)
		#define UNIQUE_FUNCTION<%0...%1> %0xFs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250937)
		#define UNIQUE_FUNCTION<%0...%1> %0xFt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250938)
		#define UNIQUE_FUNCTION<%0...%1> %0xFu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250939)
		#define UNIQUE_FUNCTION<%0...%1> %0xFv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250940)
		#define UNIQUE_FUNCTION<%0...%1> %0xFw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250941)
		#define UNIQUE_FUNCTION<%0...%1> %0xFx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250942)
		#define UNIQUE_FUNCTION<%0...%1> %0xFy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250943)
		#define UNIQUE_FUNCTION<%0...%1> %0xFz%1
		#endinput
	#endif
#endif
