static stock const Y_UNIQUE_156736_156799_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_156736_156799
	#undef _inc_y_unique_156736_156799
#endif

#if UNIQUE_SYMBOL < (156743)
	#if UNIQUE_SYMBOL == (156735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156736)
		#define UNIQUE_FUNCTION<%0...%1> %0aG0%1
		#endinput
	#if UNIQUE_SYMBOL == (156736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156737)
		#define UNIQUE_FUNCTION<%0...%1> %0aG1%1
		#endinput
	#if UNIQUE_SYMBOL == (156737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156738)
		#define UNIQUE_FUNCTION<%0...%1> %0aG2%1
		#endinput
	#if UNIQUE_SYMBOL == (156738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156739)
		#define UNIQUE_FUNCTION<%0...%1> %0aG3%1
		#endinput
	#if UNIQUE_SYMBOL == (156739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156740)
		#define UNIQUE_FUNCTION<%0...%1> %0aG4%1
		#endinput
	#if UNIQUE_SYMBOL == (156740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156741)
		#define UNIQUE_FUNCTION<%0...%1> %0aG5%1
		#endinput
	#if UNIQUE_SYMBOL == (156741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156742)
		#define UNIQUE_FUNCTION<%0...%1> %0aG6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156743)
		#define UNIQUE_FUNCTION<%0...%1> %0aG7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (156751)
	#elseif UNIQUE_SYMBOL == (156743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156744)
		#define UNIQUE_FUNCTION<%0...%1> %0aG8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156745)
		#define UNIQUE_FUNCTION<%0...%1> %0aG9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156746)
		#define UNIQUE_FUNCTION<%0...%1> %0aG@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156747)
		#define UNIQUE_FUNCTION<%0...%1> %0aGA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156748)
		#define UNIQUE_FUNCTION<%0...%1> %0aGB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156749)
		#define UNIQUE_FUNCTION<%0...%1> %0aGC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156750)
		#define UNIQUE_FUNCTION<%0...%1> %0aGD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156751)
		#define UNIQUE_FUNCTION<%0...%1> %0aGE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (156759)
	#elseif UNIQUE_SYMBOL == (156751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156752)
		#define UNIQUE_FUNCTION<%0...%1> %0aGF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156753)
		#define UNIQUE_FUNCTION<%0...%1> %0aGG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156754)
		#define UNIQUE_FUNCTION<%0...%1> %0aGH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156755)
		#define UNIQUE_FUNCTION<%0...%1> %0aGI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156756)
		#define UNIQUE_FUNCTION<%0...%1> %0aGJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156757)
		#define UNIQUE_FUNCTION<%0...%1> %0aGK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156758)
		#define UNIQUE_FUNCTION<%0...%1> %0aGL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156759)
		#define UNIQUE_FUNCTION<%0...%1> %0aGM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (156767)
	#elseif UNIQUE_SYMBOL == (156759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156760)
		#define UNIQUE_FUNCTION<%0...%1> %0aGN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156761)
		#define UNIQUE_FUNCTION<%0...%1> %0aGO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156762)
		#define UNIQUE_FUNCTION<%0...%1> %0aGP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156763)
		#define UNIQUE_FUNCTION<%0...%1> %0aGQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156764)
		#define UNIQUE_FUNCTION<%0...%1> %0aGR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156765)
		#define UNIQUE_FUNCTION<%0...%1> %0aGS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156766)
		#define UNIQUE_FUNCTION<%0...%1> %0aGT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156767)
		#define UNIQUE_FUNCTION<%0...%1> %0aGU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (156775)
	#elseif UNIQUE_SYMBOL == (156767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156768)
		#define UNIQUE_FUNCTION<%0...%1> %0aGV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156769)
		#define UNIQUE_FUNCTION<%0...%1> %0aGW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156770)
		#define UNIQUE_FUNCTION<%0...%1> %0aGX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156771)
		#define UNIQUE_FUNCTION<%0...%1> %0aGY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156772)
		#define UNIQUE_FUNCTION<%0...%1> %0aGZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156773)
		#define UNIQUE_FUNCTION<%0...%1> %0aG_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156774)
		#define UNIQUE_FUNCTION<%0...%1> %0aGa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156775)
		#define UNIQUE_FUNCTION<%0...%1> %0aGb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (156783)
	#elseif UNIQUE_SYMBOL == (156775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156776)
		#define UNIQUE_FUNCTION<%0...%1> %0aGc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156777)
		#define UNIQUE_FUNCTION<%0...%1> %0aGd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156778)
		#define UNIQUE_FUNCTION<%0...%1> %0aGe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156779)
		#define UNIQUE_FUNCTION<%0...%1> %0aGf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156780)
		#define UNIQUE_FUNCTION<%0...%1> %0aGg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156781)
		#define UNIQUE_FUNCTION<%0...%1> %0aGh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156782)
		#define UNIQUE_FUNCTION<%0...%1> %0aGi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156783)
		#define UNIQUE_FUNCTION<%0...%1> %0aGj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (156791)
	#elseif UNIQUE_SYMBOL == (156783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156784)
		#define UNIQUE_FUNCTION<%0...%1> %0aGk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156785)
		#define UNIQUE_FUNCTION<%0...%1> %0aGl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156786)
		#define UNIQUE_FUNCTION<%0...%1> %0aGm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156787)
		#define UNIQUE_FUNCTION<%0...%1> %0aGn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156788)
		#define UNIQUE_FUNCTION<%0...%1> %0aGo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156789)
		#define UNIQUE_FUNCTION<%0...%1> %0aGp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156790)
		#define UNIQUE_FUNCTION<%0...%1> %0aGq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156791)
		#define UNIQUE_FUNCTION<%0...%1> %0aGr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (156791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156792)
		#define UNIQUE_FUNCTION<%0...%1> %0aGs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156793)
		#define UNIQUE_FUNCTION<%0...%1> %0aGt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156794)
		#define UNIQUE_FUNCTION<%0...%1> %0aGu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156795)
		#define UNIQUE_FUNCTION<%0...%1> %0aGv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156796)
		#define UNIQUE_FUNCTION<%0...%1> %0aGw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156797)
		#define UNIQUE_FUNCTION<%0...%1> %0aGx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (156797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156798)
		#define UNIQUE_FUNCTION<%0...%1> %0aGy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (156799)
		#define UNIQUE_FUNCTION<%0...%1> %0aGz%1
		#endinput
	#endif
#endif
