static stock const Y_UNIQUE_075520_075583_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_075520_075583
	#undef _inc_y_unique_075520_075583
#endif

#if UNIQUE_SYMBOL < (75527)
	#if UNIQUE_SYMBOL == (75519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75520)
		#define UNIQUE_FUNCTION<%0...%1> %0HR0%1
		#endinput
	#if UNIQUE_SYMBOL == (75520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75521)
		#define UNIQUE_FUNCTION<%0...%1> %0HR1%1
		#endinput
	#if UNIQUE_SYMBOL == (75521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75522)
		#define UNIQUE_FUNCTION<%0...%1> %0HR2%1
		#endinput
	#if UNIQUE_SYMBOL == (75522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75523)
		#define UNIQUE_FUNCTION<%0...%1> %0HR3%1
		#endinput
	#if UNIQUE_SYMBOL == (75523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75524)
		#define UNIQUE_FUNCTION<%0...%1> %0HR4%1
		#endinput
	#if UNIQUE_SYMBOL == (75524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75525)
		#define UNIQUE_FUNCTION<%0...%1> %0HR5%1
		#endinput
	#if UNIQUE_SYMBOL == (75525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75526)
		#define UNIQUE_FUNCTION<%0...%1> %0HR6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75527)
		#define UNIQUE_FUNCTION<%0...%1> %0HR7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (75535)
	#elseif UNIQUE_SYMBOL == (75527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75528)
		#define UNIQUE_FUNCTION<%0...%1> %0HR8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75529)
		#define UNIQUE_FUNCTION<%0...%1> %0HR9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75530)
		#define UNIQUE_FUNCTION<%0...%1> %0HR@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75531)
		#define UNIQUE_FUNCTION<%0...%1> %0HRA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75532)
		#define UNIQUE_FUNCTION<%0...%1> %0HRB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75533)
		#define UNIQUE_FUNCTION<%0...%1> %0HRC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75534)
		#define UNIQUE_FUNCTION<%0...%1> %0HRD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75535)
		#define UNIQUE_FUNCTION<%0...%1> %0HRE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (75543)
	#elseif UNIQUE_SYMBOL == (75535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75536)
		#define UNIQUE_FUNCTION<%0...%1> %0HRF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75537)
		#define UNIQUE_FUNCTION<%0...%1> %0HRG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75538)
		#define UNIQUE_FUNCTION<%0...%1> %0HRH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75539)
		#define UNIQUE_FUNCTION<%0...%1> %0HRI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75540)
		#define UNIQUE_FUNCTION<%0...%1> %0HRJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75541)
		#define UNIQUE_FUNCTION<%0...%1> %0HRK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75542)
		#define UNIQUE_FUNCTION<%0...%1> %0HRL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75543)
		#define UNIQUE_FUNCTION<%0...%1> %0HRM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (75551)
	#elseif UNIQUE_SYMBOL == (75543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75544)
		#define UNIQUE_FUNCTION<%0...%1> %0HRN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75545)
		#define UNIQUE_FUNCTION<%0...%1> %0HRO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75546)
		#define UNIQUE_FUNCTION<%0...%1> %0HRP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75547)
		#define UNIQUE_FUNCTION<%0...%1> %0HRQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75548)
		#define UNIQUE_FUNCTION<%0...%1> %0HRR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75549)
		#define UNIQUE_FUNCTION<%0...%1> %0HRS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75550)
		#define UNIQUE_FUNCTION<%0...%1> %0HRT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75551)
		#define UNIQUE_FUNCTION<%0...%1> %0HRU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (75559)
	#elseif UNIQUE_SYMBOL == (75551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75552)
		#define UNIQUE_FUNCTION<%0...%1> %0HRV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75553)
		#define UNIQUE_FUNCTION<%0...%1> %0HRW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75554)
		#define UNIQUE_FUNCTION<%0...%1> %0HRX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75555)
		#define UNIQUE_FUNCTION<%0...%1> %0HRY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75556)
		#define UNIQUE_FUNCTION<%0...%1> %0HRZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75557)
		#define UNIQUE_FUNCTION<%0...%1> %0HR_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75558)
		#define UNIQUE_FUNCTION<%0...%1> %0HRa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75559)
		#define UNIQUE_FUNCTION<%0...%1> %0HRb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (75567)
	#elseif UNIQUE_SYMBOL == (75559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75560)
		#define UNIQUE_FUNCTION<%0...%1> %0HRc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75561)
		#define UNIQUE_FUNCTION<%0...%1> %0HRd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75562)
		#define UNIQUE_FUNCTION<%0...%1> %0HRe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75563)
		#define UNIQUE_FUNCTION<%0...%1> %0HRf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75564)
		#define UNIQUE_FUNCTION<%0...%1> %0HRg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75565)
		#define UNIQUE_FUNCTION<%0...%1> %0HRh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75566)
		#define UNIQUE_FUNCTION<%0...%1> %0HRi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75567)
		#define UNIQUE_FUNCTION<%0...%1> %0HRj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (75575)
	#elseif UNIQUE_SYMBOL == (75567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75568)
		#define UNIQUE_FUNCTION<%0...%1> %0HRk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75569)
		#define UNIQUE_FUNCTION<%0...%1> %0HRl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75570)
		#define UNIQUE_FUNCTION<%0...%1> %0HRm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75571)
		#define UNIQUE_FUNCTION<%0...%1> %0HRn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75572)
		#define UNIQUE_FUNCTION<%0...%1> %0HRo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75573)
		#define UNIQUE_FUNCTION<%0...%1> %0HRp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75574)
		#define UNIQUE_FUNCTION<%0...%1> %0HRq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75575)
		#define UNIQUE_FUNCTION<%0...%1> %0HRr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (75575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75576)
		#define UNIQUE_FUNCTION<%0...%1> %0HRs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75577)
		#define UNIQUE_FUNCTION<%0...%1> %0HRt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75578)
		#define UNIQUE_FUNCTION<%0...%1> %0HRu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75579)
		#define UNIQUE_FUNCTION<%0...%1> %0HRv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75580)
		#define UNIQUE_FUNCTION<%0...%1> %0HRw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75581)
		#define UNIQUE_FUNCTION<%0...%1> %0HRx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75582)
		#define UNIQUE_FUNCTION<%0...%1> %0HRy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75583)
		#define UNIQUE_FUNCTION<%0...%1> %0HRz%1
		#endinput
	#endif
#endif
