static stock const Y_UNIQUE_141952_142015_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_141952_142015
	#undef _inc_y_unique_141952_142015
#endif

#if UNIQUE_SYMBOL < (141959)
	#if UNIQUE_SYMBOL == (141951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141952)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe0%1
		#endinput
	#if UNIQUE_SYMBOL == (141952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141953)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe1%1
		#endinput
	#if UNIQUE_SYMBOL == (141953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141954)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe2%1
		#endinput
	#if UNIQUE_SYMBOL == (141954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141955)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe3%1
		#endinput
	#if UNIQUE_SYMBOL == (141955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141956)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe4%1
		#endinput
	#if UNIQUE_SYMBOL == (141956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141957)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe5%1
		#endinput
	#if UNIQUE_SYMBOL == (141957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141958)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141959)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141967)
	#elseif UNIQUE_SYMBOL == (141959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141960)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141961)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141962)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141963)
		#define UNIQUE_FUNCTION<%0...%1> %0XeA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141964)
		#define UNIQUE_FUNCTION<%0...%1> %0XeB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141965)
		#define UNIQUE_FUNCTION<%0...%1> %0XeC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141966)
		#define UNIQUE_FUNCTION<%0...%1> %0XeD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141967)
		#define UNIQUE_FUNCTION<%0...%1> %0XeE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141975)
	#elseif UNIQUE_SYMBOL == (141967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141968)
		#define UNIQUE_FUNCTION<%0...%1> %0XeF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141969)
		#define UNIQUE_FUNCTION<%0...%1> %0XeG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141970)
		#define UNIQUE_FUNCTION<%0...%1> %0XeH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141971)
		#define UNIQUE_FUNCTION<%0...%1> %0XeI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141972)
		#define UNIQUE_FUNCTION<%0...%1> %0XeJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141973)
		#define UNIQUE_FUNCTION<%0...%1> %0XeK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141974)
		#define UNIQUE_FUNCTION<%0...%1> %0XeL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141975)
		#define UNIQUE_FUNCTION<%0...%1> %0XeM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141983)
	#elseif UNIQUE_SYMBOL == (141975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141976)
		#define UNIQUE_FUNCTION<%0...%1> %0XeN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141977)
		#define UNIQUE_FUNCTION<%0...%1> %0XeO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141978)
		#define UNIQUE_FUNCTION<%0...%1> %0XeP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141979)
		#define UNIQUE_FUNCTION<%0...%1> %0XeQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141980)
		#define UNIQUE_FUNCTION<%0...%1> %0XeR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141981)
		#define UNIQUE_FUNCTION<%0...%1> %0XeS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141982)
		#define UNIQUE_FUNCTION<%0...%1> %0XeT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141983)
		#define UNIQUE_FUNCTION<%0...%1> %0XeU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141991)
	#elseif UNIQUE_SYMBOL == (141983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141984)
		#define UNIQUE_FUNCTION<%0...%1> %0XeV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141985)
		#define UNIQUE_FUNCTION<%0...%1> %0XeW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141986)
		#define UNIQUE_FUNCTION<%0...%1> %0XeX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141987)
		#define UNIQUE_FUNCTION<%0...%1> %0XeY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141988)
		#define UNIQUE_FUNCTION<%0...%1> %0XeZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141989)
		#define UNIQUE_FUNCTION<%0...%1> %0Xe_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141990)
		#define UNIQUE_FUNCTION<%0...%1> %0Xea%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141991)
		#define UNIQUE_FUNCTION<%0...%1> %0Xeb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141999)
	#elseif UNIQUE_SYMBOL == (141991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141992)
		#define UNIQUE_FUNCTION<%0...%1> %0Xec%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141993)
		#define UNIQUE_FUNCTION<%0...%1> %0Xed%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141994)
		#define UNIQUE_FUNCTION<%0...%1> %0Xee%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141995)
		#define UNIQUE_FUNCTION<%0...%1> %0Xef%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141996)
		#define UNIQUE_FUNCTION<%0...%1> %0Xeg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141997)
		#define UNIQUE_FUNCTION<%0...%1> %0Xeh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141998)
		#define UNIQUE_FUNCTION<%0...%1> %0Xei%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141999)
		#define UNIQUE_FUNCTION<%0...%1> %0Xej%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (142007)
	#elseif UNIQUE_SYMBOL == (141999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142000)
		#define UNIQUE_FUNCTION<%0...%1> %0Xek%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142001)
		#define UNIQUE_FUNCTION<%0...%1> %0Xel%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142002)
		#define UNIQUE_FUNCTION<%0...%1> %0Xem%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142003)
		#define UNIQUE_FUNCTION<%0...%1> %0Xen%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142004)
		#define UNIQUE_FUNCTION<%0...%1> %0Xeo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142005)
		#define UNIQUE_FUNCTION<%0...%1> %0Xep%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142006)
		#define UNIQUE_FUNCTION<%0...%1> %0Xeq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142007)
		#define UNIQUE_FUNCTION<%0...%1> %0Xer%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (142007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142008)
		#define UNIQUE_FUNCTION<%0...%1> %0Xes%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142009)
		#define UNIQUE_FUNCTION<%0...%1> %0Xet%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142010)
		#define UNIQUE_FUNCTION<%0...%1> %0Xeu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142011)
		#define UNIQUE_FUNCTION<%0...%1> %0Xev%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142012)
		#define UNIQUE_FUNCTION<%0...%1> %0Xew%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142013)
		#define UNIQUE_FUNCTION<%0...%1> %0Xex%1
		#endinput
	#elseif UNIQUE_SYMBOL == (142013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142014)
		#define UNIQUE_FUNCTION<%0...%1> %0Xey%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (142015)
		#define UNIQUE_FUNCTION<%0...%1> %0Xez%1
		#endinput
	#endif
#endif
