static stock const Y_UNIQUE_073536_073599_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_073536_073599
	#undef _inc_y_unique_073536_073599
#endif

#if UNIQUE_SYMBOL < (73543)
	#if UNIQUE_SYMBOL == (73535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73536)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx0%1
		#endinput
	#if UNIQUE_SYMBOL == (73536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73537)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx1%1
		#endinput
	#if UNIQUE_SYMBOL == (73537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73538)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx2%1
		#endinput
	#if UNIQUE_SYMBOL == (73538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73539)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx3%1
		#endinput
	#if UNIQUE_SYMBOL == (73539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73540)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx4%1
		#endinput
	#if UNIQUE_SYMBOL == (73540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73541)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx5%1
		#endinput
	#if UNIQUE_SYMBOL == (73541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73542)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73543)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73551)
	#elseif UNIQUE_SYMBOL == (73543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73544)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73545)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73546)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73547)
		#define UNIQUE_FUNCTION<%0...%1> %0GxA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73548)
		#define UNIQUE_FUNCTION<%0...%1> %0GxB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73549)
		#define UNIQUE_FUNCTION<%0...%1> %0GxC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73550)
		#define UNIQUE_FUNCTION<%0...%1> %0GxD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73551)
		#define UNIQUE_FUNCTION<%0...%1> %0GxE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73559)
	#elseif UNIQUE_SYMBOL == (73551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73552)
		#define UNIQUE_FUNCTION<%0...%1> %0GxF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73553)
		#define UNIQUE_FUNCTION<%0...%1> %0GxG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73554)
		#define UNIQUE_FUNCTION<%0...%1> %0GxH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73555)
		#define UNIQUE_FUNCTION<%0...%1> %0GxI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73556)
		#define UNIQUE_FUNCTION<%0...%1> %0GxJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73557)
		#define UNIQUE_FUNCTION<%0...%1> %0GxK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73558)
		#define UNIQUE_FUNCTION<%0...%1> %0GxL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73559)
		#define UNIQUE_FUNCTION<%0...%1> %0GxM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73567)
	#elseif UNIQUE_SYMBOL == (73559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73560)
		#define UNIQUE_FUNCTION<%0...%1> %0GxN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73561)
		#define UNIQUE_FUNCTION<%0...%1> %0GxO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73562)
		#define UNIQUE_FUNCTION<%0...%1> %0GxP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73563)
		#define UNIQUE_FUNCTION<%0...%1> %0GxQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73564)
		#define UNIQUE_FUNCTION<%0...%1> %0GxR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73565)
		#define UNIQUE_FUNCTION<%0...%1> %0GxS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73566)
		#define UNIQUE_FUNCTION<%0...%1> %0GxT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73567)
		#define UNIQUE_FUNCTION<%0...%1> %0GxU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73575)
	#elseif UNIQUE_SYMBOL == (73567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73568)
		#define UNIQUE_FUNCTION<%0...%1> %0GxV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73569)
		#define UNIQUE_FUNCTION<%0...%1> %0GxW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73570)
		#define UNIQUE_FUNCTION<%0...%1> %0GxX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73571)
		#define UNIQUE_FUNCTION<%0...%1> %0GxY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73572)
		#define UNIQUE_FUNCTION<%0...%1> %0GxZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73573)
		#define UNIQUE_FUNCTION<%0...%1> %0Gx_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73574)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73575)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73583)
	#elseif UNIQUE_SYMBOL == (73575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73576)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73577)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73578)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73579)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73580)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73581)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73582)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73583)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73591)
	#elseif UNIQUE_SYMBOL == (73583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73584)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73585)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73586)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73587)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73588)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73589)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73590)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73591)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (73591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73592)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73593)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73594)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73595)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73596)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73597)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73598)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73599)
		#define UNIQUE_FUNCTION<%0...%1> %0Gxz%1
		#endinput
	#endif
#endif
