static stock const Y_UNIQUE_024256_024319_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_024256_024319
	#undef _inc_y_unique_024256_024319
#endif

#if UNIQUE_SYMBOL < (24263)
	#if UNIQUE_SYMBOL == (24255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24256)
		#define UNIQUE_FUNCTION<%0...%1> %05v0%1
		#endinput
	#if UNIQUE_SYMBOL == (24256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24257)
		#define UNIQUE_FUNCTION<%0...%1> %05v1%1
		#endinput
	#if UNIQUE_SYMBOL == (24257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24258)
		#define UNIQUE_FUNCTION<%0...%1> %05v2%1
		#endinput
	#if UNIQUE_SYMBOL == (24258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24259)
		#define UNIQUE_FUNCTION<%0...%1> %05v3%1
		#endinput
	#if UNIQUE_SYMBOL == (24259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24260)
		#define UNIQUE_FUNCTION<%0...%1> %05v4%1
		#endinput
	#if UNIQUE_SYMBOL == (24260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24261)
		#define UNIQUE_FUNCTION<%0...%1> %05v5%1
		#endinput
	#if UNIQUE_SYMBOL == (24261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24262)
		#define UNIQUE_FUNCTION<%0...%1> %05v6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24263)
		#define UNIQUE_FUNCTION<%0...%1> %05v7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24271)
	#elseif UNIQUE_SYMBOL == (24263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24264)
		#define UNIQUE_FUNCTION<%0...%1> %05v8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24265)
		#define UNIQUE_FUNCTION<%0...%1> %05v9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24266)
		#define UNIQUE_FUNCTION<%0...%1> %05v@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24267)
		#define UNIQUE_FUNCTION<%0...%1> %05vA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24268)
		#define UNIQUE_FUNCTION<%0...%1> %05vB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24269)
		#define UNIQUE_FUNCTION<%0...%1> %05vC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24270)
		#define UNIQUE_FUNCTION<%0...%1> %05vD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24271)
		#define UNIQUE_FUNCTION<%0...%1> %05vE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24279)
	#elseif UNIQUE_SYMBOL == (24271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24272)
		#define UNIQUE_FUNCTION<%0...%1> %05vF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24273)
		#define UNIQUE_FUNCTION<%0...%1> %05vG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24274)
		#define UNIQUE_FUNCTION<%0...%1> %05vH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24275)
		#define UNIQUE_FUNCTION<%0...%1> %05vI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24276)
		#define UNIQUE_FUNCTION<%0...%1> %05vJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24277)
		#define UNIQUE_FUNCTION<%0...%1> %05vK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24278)
		#define UNIQUE_FUNCTION<%0...%1> %05vL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24279)
		#define UNIQUE_FUNCTION<%0...%1> %05vM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24287)
	#elseif UNIQUE_SYMBOL == (24279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24280)
		#define UNIQUE_FUNCTION<%0...%1> %05vN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24281)
		#define UNIQUE_FUNCTION<%0...%1> %05vO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24282)
		#define UNIQUE_FUNCTION<%0...%1> %05vP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24283)
		#define UNIQUE_FUNCTION<%0...%1> %05vQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24284)
		#define UNIQUE_FUNCTION<%0...%1> %05vR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24285)
		#define UNIQUE_FUNCTION<%0...%1> %05vS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24286)
		#define UNIQUE_FUNCTION<%0...%1> %05vT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24287)
		#define UNIQUE_FUNCTION<%0...%1> %05vU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24295)
	#elseif UNIQUE_SYMBOL == (24287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24288)
		#define UNIQUE_FUNCTION<%0...%1> %05vV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24289)
		#define UNIQUE_FUNCTION<%0...%1> %05vW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24290)
		#define UNIQUE_FUNCTION<%0...%1> %05vX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24291)
		#define UNIQUE_FUNCTION<%0...%1> %05vY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24292)
		#define UNIQUE_FUNCTION<%0...%1> %05vZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24293)
		#define UNIQUE_FUNCTION<%0...%1> %05v_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24294)
		#define UNIQUE_FUNCTION<%0...%1> %05va%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24295)
		#define UNIQUE_FUNCTION<%0...%1> %05vb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24303)
	#elseif UNIQUE_SYMBOL == (24295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24296)
		#define UNIQUE_FUNCTION<%0...%1> %05vc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24297)
		#define UNIQUE_FUNCTION<%0...%1> %05vd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24298)
		#define UNIQUE_FUNCTION<%0...%1> %05ve%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24299)
		#define UNIQUE_FUNCTION<%0...%1> %05vf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24300)
		#define UNIQUE_FUNCTION<%0...%1> %05vg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24301)
		#define UNIQUE_FUNCTION<%0...%1> %05vh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24302)
		#define UNIQUE_FUNCTION<%0...%1> %05vi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24303)
		#define UNIQUE_FUNCTION<%0...%1> %05vj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24311)
	#elseif UNIQUE_SYMBOL == (24303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24304)
		#define UNIQUE_FUNCTION<%0...%1> %05vk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24305)
		#define UNIQUE_FUNCTION<%0...%1> %05vl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24306)
		#define UNIQUE_FUNCTION<%0...%1> %05vm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24307)
		#define UNIQUE_FUNCTION<%0...%1> %05vn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24308)
		#define UNIQUE_FUNCTION<%0...%1> %05vo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24309)
		#define UNIQUE_FUNCTION<%0...%1> %05vp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24310)
		#define UNIQUE_FUNCTION<%0...%1> %05vq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24311)
		#define UNIQUE_FUNCTION<%0...%1> %05vr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (24311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24312)
		#define UNIQUE_FUNCTION<%0...%1> %05vs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24313)
		#define UNIQUE_FUNCTION<%0...%1> %05vt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24314)
		#define UNIQUE_FUNCTION<%0...%1> %05vu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24315)
		#define UNIQUE_FUNCTION<%0...%1> %05vv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24316)
		#define UNIQUE_FUNCTION<%0...%1> %05vw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24317)
		#define UNIQUE_FUNCTION<%0...%1> %05vx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24318)
		#define UNIQUE_FUNCTION<%0...%1> %05vy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24319)
		#define UNIQUE_FUNCTION<%0...%1> %05vz%1
		#endinput
	#endif
#endif
