static stock const Y_UNIQUE_122944_123007_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_122944_123007
	#undef _inc_y_unique_122944_123007
#endif

#if UNIQUE_SYMBOL < (122951)
	#if UNIQUE_SYMBOL == (122943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122944)
		#define UNIQUE_FUNCTION<%0...%1> %0T10%1
		#endinput
	#if UNIQUE_SYMBOL == (122944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122945)
		#define UNIQUE_FUNCTION<%0...%1> %0T11%1
		#endinput
	#if UNIQUE_SYMBOL == (122945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122946)
		#define UNIQUE_FUNCTION<%0...%1> %0T12%1
		#endinput
	#if UNIQUE_SYMBOL == (122946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122947)
		#define UNIQUE_FUNCTION<%0...%1> %0T13%1
		#endinput
	#if UNIQUE_SYMBOL == (122947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122948)
		#define UNIQUE_FUNCTION<%0...%1> %0T14%1
		#endinput
	#if UNIQUE_SYMBOL == (122948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122949)
		#define UNIQUE_FUNCTION<%0...%1> %0T15%1
		#endinput
	#if UNIQUE_SYMBOL == (122949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122950)
		#define UNIQUE_FUNCTION<%0...%1> %0T16%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122951)
		#define UNIQUE_FUNCTION<%0...%1> %0T17%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122959)
	#elseif UNIQUE_SYMBOL == (122951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122952)
		#define UNIQUE_FUNCTION<%0...%1> %0T18%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122953)
		#define UNIQUE_FUNCTION<%0...%1> %0T19%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122954)
		#define UNIQUE_FUNCTION<%0...%1> %0T1@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122955)
		#define UNIQUE_FUNCTION<%0...%1> %0T1A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122956)
		#define UNIQUE_FUNCTION<%0...%1> %0T1B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122957)
		#define UNIQUE_FUNCTION<%0...%1> %0T1C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122958)
		#define UNIQUE_FUNCTION<%0...%1> %0T1D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122959)
		#define UNIQUE_FUNCTION<%0...%1> %0T1E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122967)
	#elseif UNIQUE_SYMBOL == (122959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122960)
		#define UNIQUE_FUNCTION<%0...%1> %0T1F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122961)
		#define UNIQUE_FUNCTION<%0...%1> %0T1G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122962)
		#define UNIQUE_FUNCTION<%0...%1> %0T1H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122963)
		#define UNIQUE_FUNCTION<%0...%1> %0T1I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122964)
		#define UNIQUE_FUNCTION<%0...%1> %0T1J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122965)
		#define UNIQUE_FUNCTION<%0...%1> %0T1K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122966)
		#define UNIQUE_FUNCTION<%0...%1> %0T1L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122967)
		#define UNIQUE_FUNCTION<%0...%1> %0T1M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122975)
	#elseif UNIQUE_SYMBOL == (122967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122968)
		#define UNIQUE_FUNCTION<%0...%1> %0T1N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122969)
		#define UNIQUE_FUNCTION<%0...%1> %0T1O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122970)
		#define UNIQUE_FUNCTION<%0...%1> %0T1P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122971)
		#define UNIQUE_FUNCTION<%0...%1> %0T1Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122972)
		#define UNIQUE_FUNCTION<%0...%1> %0T1R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122973)
		#define UNIQUE_FUNCTION<%0...%1> %0T1S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122974)
		#define UNIQUE_FUNCTION<%0...%1> %0T1T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122975)
		#define UNIQUE_FUNCTION<%0...%1> %0T1U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122983)
	#elseif UNIQUE_SYMBOL == (122975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122976)
		#define UNIQUE_FUNCTION<%0...%1> %0T1V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122977)
		#define UNIQUE_FUNCTION<%0...%1> %0T1W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122978)
		#define UNIQUE_FUNCTION<%0...%1> %0T1X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122979)
		#define UNIQUE_FUNCTION<%0...%1> %0T1Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122980)
		#define UNIQUE_FUNCTION<%0...%1> %0T1Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122981)
		#define UNIQUE_FUNCTION<%0...%1> %0T1_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122982)
		#define UNIQUE_FUNCTION<%0...%1> %0T1a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122983)
		#define UNIQUE_FUNCTION<%0...%1> %0T1b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122991)
	#elseif UNIQUE_SYMBOL == (122983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122984)
		#define UNIQUE_FUNCTION<%0...%1> %0T1c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122985)
		#define UNIQUE_FUNCTION<%0...%1> %0T1d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122986)
		#define UNIQUE_FUNCTION<%0...%1> %0T1e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122987)
		#define UNIQUE_FUNCTION<%0...%1> %0T1f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122988)
		#define UNIQUE_FUNCTION<%0...%1> %0T1g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122989)
		#define UNIQUE_FUNCTION<%0...%1> %0T1h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122990)
		#define UNIQUE_FUNCTION<%0...%1> %0T1i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122991)
		#define UNIQUE_FUNCTION<%0...%1> %0T1j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122999)
	#elseif UNIQUE_SYMBOL == (122991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122992)
		#define UNIQUE_FUNCTION<%0...%1> %0T1k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122993)
		#define UNIQUE_FUNCTION<%0...%1> %0T1l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122994)
		#define UNIQUE_FUNCTION<%0...%1> %0T1m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122995)
		#define UNIQUE_FUNCTION<%0...%1> %0T1n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122996)
		#define UNIQUE_FUNCTION<%0...%1> %0T1o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122997)
		#define UNIQUE_FUNCTION<%0...%1> %0T1p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122998)
		#define UNIQUE_FUNCTION<%0...%1> %0T1q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122999)
		#define UNIQUE_FUNCTION<%0...%1> %0T1r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (122999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123000)
		#define UNIQUE_FUNCTION<%0...%1> %0T1s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123001)
		#define UNIQUE_FUNCTION<%0...%1> %0T1t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123002)
		#define UNIQUE_FUNCTION<%0...%1> %0T1u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123003)
		#define UNIQUE_FUNCTION<%0...%1> %0T1v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123004)
		#define UNIQUE_FUNCTION<%0...%1> %0T1w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123005)
		#define UNIQUE_FUNCTION<%0...%1> %0T1x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123006)
		#define UNIQUE_FUNCTION<%0...%1> %0T1y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123007)
		#define UNIQUE_FUNCTION<%0...%1> %0T1z%1
		#endinput
	#endif
#endif
