static stock const Y_UNIQUE_043904_043967_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_043904_043967
	#undef _inc_y_unique_043904_043967
#endif

#if UNIQUE_SYMBOL < (43911)
	#if UNIQUE_SYMBOL == (43903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43904)
		#define UNIQUE_FUNCTION<%0...%1> %0@i0%1
		#endinput
	#if UNIQUE_SYMBOL == (43904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43905)
		#define UNIQUE_FUNCTION<%0...%1> %0@i1%1
		#endinput
	#if UNIQUE_SYMBOL == (43905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43906)
		#define UNIQUE_FUNCTION<%0...%1> %0@i2%1
		#endinput
	#if UNIQUE_SYMBOL == (43906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43907)
		#define UNIQUE_FUNCTION<%0...%1> %0@i3%1
		#endinput
	#if UNIQUE_SYMBOL == (43907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43908)
		#define UNIQUE_FUNCTION<%0...%1> %0@i4%1
		#endinput
	#if UNIQUE_SYMBOL == (43908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43909)
		#define UNIQUE_FUNCTION<%0...%1> %0@i5%1
		#endinput
	#if UNIQUE_SYMBOL == (43909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43910)
		#define UNIQUE_FUNCTION<%0...%1> %0@i6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43911)
		#define UNIQUE_FUNCTION<%0...%1> %0@i7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (43919)
	#elseif UNIQUE_SYMBOL == (43911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43912)
		#define UNIQUE_FUNCTION<%0...%1> %0@i8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43913)
		#define UNIQUE_FUNCTION<%0...%1> %0@i9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43914)
		#define UNIQUE_FUNCTION<%0...%1> %0@i@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43915)
		#define UNIQUE_FUNCTION<%0...%1> %0@iA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43916)
		#define UNIQUE_FUNCTION<%0...%1> %0@iB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43917)
		#define UNIQUE_FUNCTION<%0...%1> %0@iC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43918)
		#define UNIQUE_FUNCTION<%0...%1> %0@iD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43919)
		#define UNIQUE_FUNCTION<%0...%1> %0@iE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (43927)
	#elseif UNIQUE_SYMBOL == (43919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43920)
		#define UNIQUE_FUNCTION<%0...%1> %0@iF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43921)
		#define UNIQUE_FUNCTION<%0...%1> %0@iG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43922)
		#define UNIQUE_FUNCTION<%0...%1> %0@iH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43923)
		#define UNIQUE_FUNCTION<%0...%1> %0@iI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43924)
		#define UNIQUE_FUNCTION<%0...%1> %0@iJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43925)
		#define UNIQUE_FUNCTION<%0...%1> %0@iK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43926)
		#define UNIQUE_FUNCTION<%0...%1> %0@iL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43927)
		#define UNIQUE_FUNCTION<%0...%1> %0@iM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (43935)
	#elseif UNIQUE_SYMBOL == (43927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43928)
		#define UNIQUE_FUNCTION<%0...%1> %0@iN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43929)
		#define UNIQUE_FUNCTION<%0...%1> %0@iO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43930)
		#define UNIQUE_FUNCTION<%0...%1> %0@iP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43931)
		#define UNIQUE_FUNCTION<%0...%1> %0@iQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43932)
		#define UNIQUE_FUNCTION<%0...%1> %0@iR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43933)
		#define UNIQUE_FUNCTION<%0...%1> %0@iS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43934)
		#define UNIQUE_FUNCTION<%0...%1> %0@iT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43935)
		#define UNIQUE_FUNCTION<%0...%1> %0@iU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (43943)
	#elseif UNIQUE_SYMBOL == (43935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43936)
		#define UNIQUE_FUNCTION<%0...%1> %0@iV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43937)
		#define UNIQUE_FUNCTION<%0...%1> %0@iW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43938)
		#define UNIQUE_FUNCTION<%0...%1> %0@iX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43939)
		#define UNIQUE_FUNCTION<%0...%1> %0@iY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43940)
		#define UNIQUE_FUNCTION<%0...%1> %0@iZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43941)
		#define UNIQUE_FUNCTION<%0...%1> %0@i_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43942)
		#define UNIQUE_FUNCTION<%0...%1> %0@ia%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43943)
		#define UNIQUE_FUNCTION<%0...%1> %0@ib%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (43951)
	#elseif UNIQUE_SYMBOL == (43943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43944)
		#define UNIQUE_FUNCTION<%0...%1> %0@ic%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43945)
		#define UNIQUE_FUNCTION<%0...%1> %0@id%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43946)
		#define UNIQUE_FUNCTION<%0...%1> %0@ie%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43947)
		#define UNIQUE_FUNCTION<%0...%1> %0@if%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43948)
		#define UNIQUE_FUNCTION<%0...%1> %0@ig%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43949)
		#define UNIQUE_FUNCTION<%0...%1> %0@ih%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43950)
		#define UNIQUE_FUNCTION<%0...%1> %0@ii%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43951)
		#define UNIQUE_FUNCTION<%0...%1> %0@ij%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (43959)
	#elseif UNIQUE_SYMBOL == (43951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43952)
		#define UNIQUE_FUNCTION<%0...%1> %0@ik%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43953)
		#define UNIQUE_FUNCTION<%0...%1> %0@il%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43954)
		#define UNIQUE_FUNCTION<%0...%1> %0@im%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43955)
		#define UNIQUE_FUNCTION<%0...%1> %0@in%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43956)
		#define UNIQUE_FUNCTION<%0...%1> %0@io%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43957)
		#define UNIQUE_FUNCTION<%0...%1> %0@ip%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43958)
		#define UNIQUE_FUNCTION<%0...%1> %0@iq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43959)
		#define UNIQUE_FUNCTION<%0...%1> %0@ir%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (43959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43960)
		#define UNIQUE_FUNCTION<%0...%1> %0@is%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43961)
		#define UNIQUE_FUNCTION<%0...%1> %0@it%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43962)
		#define UNIQUE_FUNCTION<%0...%1> %0@iu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43963)
		#define UNIQUE_FUNCTION<%0...%1> %0@iv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43964)
		#define UNIQUE_FUNCTION<%0...%1> %0@iw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43965)
		#define UNIQUE_FUNCTION<%0...%1> %0@ix%1
		#endinput
	#elseif UNIQUE_SYMBOL == (43965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43966)
		#define UNIQUE_FUNCTION<%0...%1> %0@iy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (43967)
		#define UNIQUE_FUNCTION<%0...%1> %0@iz%1
		#endinput
	#endif
#endif
