static stock const Y_UNIQUE_120768_120831_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_120768_120831
	#undef _inc_y_unique_120768_120831
#endif

#if UNIQUE_SYMBOL < (120775)
	#if UNIQUE_SYMBOL == (120767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120768)
		#define UNIQUE_FUNCTION<%0...%1> %0SU0%1
		#endinput
	#if UNIQUE_SYMBOL == (120768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120769)
		#define UNIQUE_FUNCTION<%0...%1> %0SU1%1
		#endinput
	#if UNIQUE_SYMBOL == (120769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120770)
		#define UNIQUE_FUNCTION<%0...%1> %0SU2%1
		#endinput
	#if UNIQUE_SYMBOL == (120770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120771)
		#define UNIQUE_FUNCTION<%0...%1> %0SU3%1
		#endinput
	#if UNIQUE_SYMBOL == (120771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120772)
		#define UNIQUE_FUNCTION<%0...%1> %0SU4%1
		#endinput
	#if UNIQUE_SYMBOL == (120772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120773)
		#define UNIQUE_FUNCTION<%0...%1> %0SU5%1
		#endinput
	#if UNIQUE_SYMBOL == (120773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120774)
		#define UNIQUE_FUNCTION<%0...%1> %0SU6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120775)
		#define UNIQUE_FUNCTION<%0...%1> %0SU7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120783)
	#elseif UNIQUE_SYMBOL == (120775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120776)
		#define UNIQUE_FUNCTION<%0...%1> %0SU8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120777)
		#define UNIQUE_FUNCTION<%0...%1> %0SU9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120778)
		#define UNIQUE_FUNCTION<%0...%1> %0SU@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120779)
		#define UNIQUE_FUNCTION<%0...%1> %0SUA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120780)
		#define UNIQUE_FUNCTION<%0...%1> %0SUB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120781)
		#define UNIQUE_FUNCTION<%0...%1> %0SUC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120782)
		#define UNIQUE_FUNCTION<%0...%1> %0SUD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120783)
		#define UNIQUE_FUNCTION<%0...%1> %0SUE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120791)
	#elseif UNIQUE_SYMBOL == (120783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120784)
		#define UNIQUE_FUNCTION<%0...%1> %0SUF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120785)
		#define UNIQUE_FUNCTION<%0...%1> %0SUG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120786)
		#define UNIQUE_FUNCTION<%0...%1> %0SUH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120787)
		#define UNIQUE_FUNCTION<%0...%1> %0SUI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120788)
		#define UNIQUE_FUNCTION<%0...%1> %0SUJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120789)
		#define UNIQUE_FUNCTION<%0...%1> %0SUK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120790)
		#define UNIQUE_FUNCTION<%0...%1> %0SUL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120791)
		#define UNIQUE_FUNCTION<%0...%1> %0SUM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120799)
	#elseif UNIQUE_SYMBOL == (120791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120792)
		#define UNIQUE_FUNCTION<%0...%1> %0SUN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120793)
		#define UNIQUE_FUNCTION<%0...%1> %0SUO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120794)
		#define UNIQUE_FUNCTION<%0...%1> %0SUP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120795)
		#define UNIQUE_FUNCTION<%0...%1> %0SUQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120796)
		#define UNIQUE_FUNCTION<%0...%1> %0SUR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120797)
		#define UNIQUE_FUNCTION<%0...%1> %0SUS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120798)
		#define UNIQUE_FUNCTION<%0...%1> %0SUT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120799)
		#define UNIQUE_FUNCTION<%0...%1> %0SUU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120807)
	#elseif UNIQUE_SYMBOL == (120799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120800)
		#define UNIQUE_FUNCTION<%0...%1> %0SUV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120801)
		#define UNIQUE_FUNCTION<%0...%1> %0SUW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120802)
		#define UNIQUE_FUNCTION<%0...%1> %0SUX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120803)
		#define UNIQUE_FUNCTION<%0...%1> %0SUY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120804)
		#define UNIQUE_FUNCTION<%0...%1> %0SUZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120805)
		#define UNIQUE_FUNCTION<%0...%1> %0SU_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120806)
		#define UNIQUE_FUNCTION<%0...%1> %0SUa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120807)
		#define UNIQUE_FUNCTION<%0...%1> %0SUb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120815)
	#elseif UNIQUE_SYMBOL == (120807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120808)
		#define UNIQUE_FUNCTION<%0...%1> %0SUc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120809)
		#define UNIQUE_FUNCTION<%0...%1> %0SUd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120810)
		#define UNIQUE_FUNCTION<%0...%1> %0SUe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120811)
		#define UNIQUE_FUNCTION<%0...%1> %0SUf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120812)
		#define UNIQUE_FUNCTION<%0...%1> %0SUg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120813)
		#define UNIQUE_FUNCTION<%0...%1> %0SUh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120814)
		#define UNIQUE_FUNCTION<%0...%1> %0SUi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120815)
		#define UNIQUE_FUNCTION<%0...%1> %0SUj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120823)
	#elseif UNIQUE_SYMBOL == (120815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120816)
		#define UNIQUE_FUNCTION<%0...%1> %0SUk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120817)
		#define UNIQUE_FUNCTION<%0...%1> %0SUl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120818)
		#define UNIQUE_FUNCTION<%0...%1> %0SUm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120819)
		#define UNIQUE_FUNCTION<%0...%1> %0SUn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120820)
		#define UNIQUE_FUNCTION<%0...%1> %0SUo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120821)
		#define UNIQUE_FUNCTION<%0...%1> %0SUp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120822)
		#define UNIQUE_FUNCTION<%0...%1> %0SUq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120823)
		#define UNIQUE_FUNCTION<%0...%1> %0SUr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (120823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120824)
		#define UNIQUE_FUNCTION<%0...%1> %0SUs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120825)
		#define UNIQUE_FUNCTION<%0...%1> %0SUt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120826)
		#define UNIQUE_FUNCTION<%0...%1> %0SUu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120827)
		#define UNIQUE_FUNCTION<%0...%1> %0SUv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120828)
		#define UNIQUE_FUNCTION<%0...%1> %0SUw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120829)
		#define UNIQUE_FUNCTION<%0...%1> %0SUx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120830)
		#define UNIQUE_FUNCTION<%0...%1> %0SUy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120831)
		#define UNIQUE_FUNCTION<%0...%1> %0SUz%1
		#endinput
	#endif
#endif
