static stock const Y_UNIQUE_261632_261695_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_261632_261695
	#undef _inc_y_unique_261632_261695
#endif

#if UNIQUE_SYMBOL < (261639)
	#if UNIQUE_SYMBOL == (261631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261632)
		#define UNIQUE_FUNCTION<%0...%1> %0zs0%1
		#endinput
	#if UNIQUE_SYMBOL == (261632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261633)
		#define UNIQUE_FUNCTION<%0...%1> %0zs1%1
		#endinput
	#if UNIQUE_SYMBOL == (261633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261634)
		#define UNIQUE_FUNCTION<%0...%1> %0zs2%1
		#endinput
	#if UNIQUE_SYMBOL == (261634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261635)
		#define UNIQUE_FUNCTION<%0...%1> %0zs3%1
		#endinput
	#if UNIQUE_SYMBOL == (261635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261636)
		#define UNIQUE_FUNCTION<%0...%1> %0zs4%1
		#endinput
	#if UNIQUE_SYMBOL == (261636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261637)
		#define UNIQUE_FUNCTION<%0...%1> %0zs5%1
		#endinput
	#if UNIQUE_SYMBOL == (261637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261638)
		#define UNIQUE_FUNCTION<%0...%1> %0zs6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261639)
		#define UNIQUE_FUNCTION<%0...%1> %0zs7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261647)
	#elseif UNIQUE_SYMBOL == (261639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261640)
		#define UNIQUE_FUNCTION<%0...%1> %0zs8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261641)
		#define UNIQUE_FUNCTION<%0...%1> %0zs9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261642)
		#define UNIQUE_FUNCTION<%0...%1> %0zs@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261643)
		#define UNIQUE_FUNCTION<%0...%1> %0zsA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261644)
		#define UNIQUE_FUNCTION<%0...%1> %0zsB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261645)
		#define UNIQUE_FUNCTION<%0...%1> %0zsC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261646)
		#define UNIQUE_FUNCTION<%0...%1> %0zsD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261647)
		#define UNIQUE_FUNCTION<%0...%1> %0zsE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261655)
	#elseif UNIQUE_SYMBOL == (261647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261648)
		#define UNIQUE_FUNCTION<%0...%1> %0zsF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261649)
		#define UNIQUE_FUNCTION<%0...%1> %0zsG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261650)
		#define UNIQUE_FUNCTION<%0...%1> %0zsH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261651)
		#define UNIQUE_FUNCTION<%0...%1> %0zsI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261652)
		#define UNIQUE_FUNCTION<%0...%1> %0zsJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261653)
		#define UNIQUE_FUNCTION<%0...%1> %0zsK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261654)
		#define UNIQUE_FUNCTION<%0...%1> %0zsL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261655)
		#define UNIQUE_FUNCTION<%0...%1> %0zsM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261663)
	#elseif UNIQUE_SYMBOL == (261655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261656)
		#define UNIQUE_FUNCTION<%0...%1> %0zsN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261657)
		#define UNIQUE_FUNCTION<%0...%1> %0zsO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261658)
		#define UNIQUE_FUNCTION<%0...%1> %0zsP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261659)
		#define UNIQUE_FUNCTION<%0...%1> %0zsQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261660)
		#define UNIQUE_FUNCTION<%0...%1> %0zsR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261661)
		#define UNIQUE_FUNCTION<%0...%1> %0zsS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261662)
		#define UNIQUE_FUNCTION<%0...%1> %0zsT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261663)
		#define UNIQUE_FUNCTION<%0...%1> %0zsU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261671)
	#elseif UNIQUE_SYMBOL == (261663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261664)
		#define UNIQUE_FUNCTION<%0...%1> %0zsV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261665)
		#define UNIQUE_FUNCTION<%0...%1> %0zsW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261666)
		#define UNIQUE_FUNCTION<%0...%1> %0zsX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261667)
		#define UNIQUE_FUNCTION<%0...%1> %0zsY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261668)
		#define UNIQUE_FUNCTION<%0...%1> %0zsZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261669)
		#define UNIQUE_FUNCTION<%0...%1> %0zs_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261670)
		#define UNIQUE_FUNCTION<%0...%1> %0zsa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261671)
		#define UNIQUE_FUNCTION<%0...%1> %0zsb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261679)
	#elseif UNIQUE_SYMBOL == (261671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261672)
		#define UNIQUE_FUNCTION<%0...%1> %0zsc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261673)
		#define UNIQUE_FUNCTION<%0...%1> %0zsd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261674)
		#define UNIQUE_FUNCTION<%0...%1> %0zse%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261675)
		#define UNIQUE_FUNCTION<%0...%1> %0zsf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261676)
		#define UNIQUE_FUNCTION<%0...%1> %0zsg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261677)
		#define UNIQUE_FUNCTION<%0...%1> %0zsh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261678)
		#define UNIQUE_FUNCTION<%0...%1> %0zsi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261679)
		#define UNIQUE_FUNCTION<%0...%1> %0zsj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261687)
	#elseif UNIQUE_SYMBOL == (261679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261680)
		#define UNIQUE_FUNCTION<%0...%1> %0zsk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261681)
		#define UNIQUE_FUNCTION<%0...%1> %0zsl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261682)
		#define UNIQUE_FUNCTION<%0...%1> %0zsm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261683)
		#define UNIQUE_FUNCTION<%0...%1> %0zsn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261684)
		#define UNIQUE_FUNCTION<%0...%1> %0zso%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261685)
		#define UNIQUE_FUNCTION<%0...%1> %0zsp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261686)
		#define UNIQUE_FUNCTION<%0...%1> %0zsq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261687)
		#define UNIQUE_FUNCTION<%0...%1> %0zsr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (261687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261688)
		#define UNIQUE_FUNCTION<%0...%1> %0zss%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261689)
		#define UNIQUE_FUNCTION<%0...%1> %0zst%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261690)
		#define UNIQUE_FUNCTION<%0...%1> %0zsu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261691)
		#define UNIQUE_FUNCTION<%0...%1> %0zsv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261692)
		#define UNIQUE_FUNCTION<%0...%1> %0zsw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261693)
		#define UNIQUE_FUNCTION<%0...%1> %0zsx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261694)
		#define UNIQUE_FUNCTION<%0...%1> %0zsy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261695)
		#define UNIQUE_FUNCTION<%0...%1> %0zsz%1
		#endinput
	#endif
#endif
