static stock const Y_UNIQUE_034240_034303_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_034240_034303
	#undef _inc_y_unique_034240_034303
#endif

#if UNIQUE_SYMBOL < (34247)
	#if UNIQUE_SYMBOL == (34239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34240)
		#define UNIQUE_FUNCTION<%0...%1> %08M0%1
		#endinput
	#if UNIQUE_SYMBOL == (34240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34241)
		#define UNIQUE_FUNCTION<%0...%1> %08M1%1
		#endinput
	#if UNIQUE_SYMBOL == (34241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34242)
		#define UNIQUE_FUNCTION<%0...%1> %08M2%1
		#endinput
	#if UNIQUE_SYMBOL == (34242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34243)
		#define UNIQUE_FUNCTION<%0...%1> %08M3%1
		#endinput
	#if UNIQUE_SYMBOL == (34243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34244)
		#define UNIQUE_FUNCTION<%0...%1> %08M4%1
		#endinput
	#if UNIQUE_SYMBOL == (34244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34245)
		#define UNIQUE_FUNCTION<%0...%1> %08M5%1
		#endinput
	#if UNIQUE_SYMBOL == (34245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34246)
		#define UNIQUE_FUNCTION<%0...%1> %08M6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34247)
		#define UNIQUE_FUNCTION<%0...%1> %08M7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34255)
	#elseif UNIQUE_SYMBOL == (34247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34248)
		#define UNIQUE_FUNCTION<%0...%1> %08M8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34249)
		#define UNIQUE_FUNCTION<%0...%1> %08M9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34250)
		#define UNIQUE_FUNCTION<%0...%1> %08M@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34251)
		#define UNIQUE_FUNCTION<%0...%1> %08MA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34252)
		#define UNIQUE_FUNCTION<%0...%1> %08MB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34253)
		#define UNIQUE_FUNCTION<%0...%1> %08MC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34254)
		#define UNIQUE_FUNCTION<%0...%1> %08MD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34255)
		#define UNIQUE_FUNCTION<%0...%1> %08ME%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34263)
	#elseif UNIQUE_SYMBOL == (34255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34256)
		#define UNIQUE_FUNCTION<%0...%1> %08MF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34257)
		#define UNIQUE_FUNCTION<%0...%1> %08MG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34258)
		#define UNIQUE_FUNCTION<%0...%1> %08MH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34259)
		#define UNIQUE_FUNCTION<%0...%1> %08MI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34260)
		#define UNIQUE_FUNCTION<%0...%1> %08MJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34261)
		#define UNIQUE_FUNCTION<%0...%1> %08MK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34262)
		#define UNIQUE_FUNCTION<%0...%1> %08ML%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34263)
		#define UNIQUE_FUNCTION<%0...%1> %08MM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34271)
	#elseif UNIQUE_SYMBOL == (34263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34264)
		#define UNIQUE_FUNCTION<%0...%1> %08MN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34265)
		#define UNIQUE_FUNCTION<%0...%1> %08MO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34266)
		#define UNIQUE_FUNCTION<%0...%1> %08MP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34267)
		#define UNIQUE_FUNCTION<%0...%1> %08MQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34268)
		#define UNIQUE_FUNCTION<%0...%1> %08MR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34269)
		#define UNIQUE_FUNCTION<%0...%1> %08MS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34270)
		#define UNIQUE_FUNCTION<%0...%1> %08MT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34271)
		#define UNIQUE_FUNCTION<%0...%1> %08MU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34279)
	#elseif UNIQUE_SYMBOL == (34271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34272)
		#define UNIQUE_FUNCTION<%0...%1> %08MV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34273)
		#define UNIQUE_FUNCTION<%0...%1> %08MW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34274)
		#define UNIQUE_FUNCTION<%0...%1> %08MX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34275)
		#define UNIQUE_FUNCTION<%0...%1> %08MY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34276)
		#define UNIQUE_FUNCTION<%0...%1> %08MZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34277)
		#define UNIQUE_FUNCTION<%0...%1> %08M_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34278)
		#define UNIQUE_FUNCTION<%0...%1> %08Ma%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34279)
		#define UNIQUE_FUNCTION<%0...%1> %08Mb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34287)
	#elseif UNIQUE_SYMBOL == (34279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34280)
		#define UNIQUE_FUNCTION<%0...%1> %08Mc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34281)
		#define UNIQUE_FUNCTION<%0...%1> %08Md%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34282)
		#define UNIQUE_FUNCTION<%0...%1> %08Me%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34283)
		#define UNIQUE_FUNCTION<%0...%1> %08Mf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34284)
		#define UNIQUE_FUNCTION<%0...%1> %08Mg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34285)
		#define UNIQUE_FUNCTION<%0...%1> %08Mh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34286)
		#define UNIQUE_FUNCTION<%0...%1> %08Mi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34287)
		#define UNIQUE_FUNCTION<%0...%1> %08Mj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34295)
	#elseif UNIQUE_SYMBOL == (34287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34288)
		#define UNIQUE_FUNCTION<%0...%1> %08Mk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34289)
		#define UNIQUE_FUNCTION<%0...%1> %08Ml%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34290)
		#define UNIQUE_FUNCTION<%0...%1> %08Mm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34291)
		#define UNIQUE_FUNCTION<%0...%1> %08Mn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34292)
		#define UNIQUE_FUNCTION<%0...%1> %08Mo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34293)
		#define UNIQUE_FUNCTION<%0...%1> %08Mp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34294)
		#define UNIQUE_FUNCTION<%0...%1> %08Mq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34295)
		#define UNIQUE_FUNCTION<%0...%1> %08Mr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (34295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34296)
		#define UNIQUE_FUNCTION<%0...%1> %08Ms%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34297)
		#define UNIQUE_FUNCTION<%0...%1> %08Mt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34298)
		#define UNIQUE_FUNCTION<%0...%1> %08Mu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34299)
		#define UNIQUE_FUNCTION<%0...%1> %08Mv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34300)
		#define UNIQUE_FUNCTION<%0...%1> %08Mw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34301)
		#define UNIQUE_FUNCTION<%0...%1> %08Mx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34302)
		#define UNIQUE_FUNCTION<%0...%1> %08My%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34303)
		#define UNIQUE_FUNCTION<%0...%1> %08Mz%1
		#endinput
	#endif
#endif
