static stock const Y_UNIQUE_055296_055359_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_055296_055359
	#undef _inc_y_unique_055296_055359
#endif

#if UNIQUE_SYMBOL < (55303)
	#if UNIQUE_SYMBOL == (55295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55296)
		#define UNIQUE_FUNCTION<%0...%1> %0CV0%1
		#endinput
	#if UNIQUE_SYMBOL == (55296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55297)
		#define UNIQUE_FUNCTION<%0...%1> %0CV1%1
		#endinput
	#if UNIQUE_SYMBOL == (55297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55298)
		#define UNIQUE_FUNCTION<%0...%1> %0CV2%1
		#endinput
	#if UNIQUE_SYMBOL == (55298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55299)
		#define UNIQUE_FUNCTION<%0...%1> %0CV3%1
		#endinput
	#if UNIQUE_SYMBOL == (55299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55300)
		#define UNIQUE_FUNCTION<%0...%1> %0CV4%1
		#endinput
	#if UNIQUE_SYMBOL == (55300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55301)
		#define UNIQUE_FUNCTION<%0...%1> %0CV5%1
		#endinput
	#if UNIQUE_SYMBOL == (55301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55302)
		#define UNIQUE_FUNCTION<%0...%1> %0CV6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55303)
		#define UNIQUE_FUNCTION<%0...%1> %0CV7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55311)
	#elseif UNIQUE_SYMBOL == (55303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55304)
		#define UNIQUE_FUNCTION<%0...%1> %0CV8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55305)
		#define UNIQUE_FUNCTION<%0...%1> %0CV9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55306)
		#define UNIQUE_FUNCTION<%0...%1> %0CV@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55307)
		#define UNIQUE_FUNCTION<%0...%1> %0CVA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55308)
		#define UNIQUE_FUNCTION<%0...%1> %0CVB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55309)
		#define UNIQUE_FUNCTION<%0...%1> %0CVC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55310)
		#define UNIQUE_FUNCTION<%0...%1> %0CVD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55311)
		#define UNIQUE_FUNCTION<%0...%1> %0CVE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55319)
	#elseif UNIQUE_SYMBOL == (55311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55312)
		#define UNIQUE_FUNCTION<%0...%1> %0CVF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55313)
		#define UNIQUE_FUNCTION<%0...%1> %0CVG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55314)
		#define UNIQUE_FUNCTION<%0...%1> %0CVH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55315)
		#define UNIQUE_FUNCTION<%0...%1> %0CVI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55316)
		#define UNIQUE_FUNCTION<%0...%1> %0CVJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55317)
		#define UNIQUE_FUNCTION<%0...%1> %0CVK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55318)
		#define UNIQUE_FUNCTION<%0...%1> %0CVL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55319)
		#define UNIQUE_FUNCTION<%0...%1> %0CVM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55327)
	#elseif UNIQUE_SYMBOL == (55319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55320)
		#define UNIQUE_FUNCTION<%0...%1> %0CVN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55321)
		#define UNIQUE_FUNCTION<%0...%1> %0CVO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55322)
		#define UNIQUE_FUNCTION<%0...%1> %0CVP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55323)
		#define UNIQUE_FUNCTION<%0...%1> %0CVQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55324)
		#define UNIQUE_FUNCTION<%0...%1> %0CVR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55325)
		#define UNIQUE_FUNCTION<%0...%1> %0CVS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55326)
		#define UNIQUE_FUNCTION<%0...%1> %0CVT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55327)
		#define UNIQUE_FUNCTION<%0...%1> %0CVU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55335)
	#elseif UNIQUE_SYMBOL == (55327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55328)
		#define UNIQUE_FUNCTION<%0...%1> %0CVV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55329)
		#define UNIQUE_FUNCTION<%0...%1> %0CVW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55330)
		#define UNIQUE_FUNCTION<%0...%1> %0CVX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55331)
		#define UNIQUE_FUNCTION<%0...%1> %0CVY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55332)
		#define UNIQUE_FUNCTION<%0...%1> %0CVZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55333)
		#define UNIQUE_FUNCTION<%0...%1> %0CV_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55334)
		#define UNIQUE_FUNCTION<%0...%1> %0CVa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55335)
		#define UNIQUE_FUNCTION<%0...%1> %0CVb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55343)
	#elseif UNIQUE_SYMBOL == (55335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55336)
		#define UNIQUE_FUNCTION<%0...%1> %0CVc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55337)
		#define UNIQUE_FUNCTION<%0...%1> %0CVd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55338)
		#define UNIQUE_FUNCTION<%0...%1> %0CVe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55339)
		#define UNIQUE_FUNCTION<%0...%1> %0CVf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55340)
		#define UNIQUE_FUNCTION<%0...%1> %0CVg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55341)
		#define UNIQUE_FUNCTION<%0...%1> %0CVh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55342)
		#define UNIQUE_FUNCTION<%0...%1> %0CVi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55343)
		#define UNIQUE_FUNCTION<%0...%1> %0CVj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (55351)
	#elseif UNIQUE_SYMBOL == (55343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55344)
		#define UNIQUE_FUNCTION<%0...%1> %0CVk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55345)
		#define UNIQUE_FUNCTION<%0...%1> %0CVl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55346)
		#define UNIQUE_FUNCTION<%0...%1> %0CVm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55347)
		#define UNIQUE_FUNCTION<%0...%1> %0CVn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55348)
		#define UNIQUE_FUNCTION<%0...%1> %0CVo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55349)
		#define UNIQUE_FUNCTION<%0...%1> %0CVp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55350)
		#define UNIQUE_FUNCTION<%0...%1> %0CVq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55351)
		#define UNIQUE_FUNCTION<%0...%1> %0CVr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (55351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55352)
		#define UNIQUE_FUNCTION<%0...%1> %0CVs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55353)
		#define UNIQUE_FUNCTION<%0...%1> %0CVt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55354)
		#define UNIQUE_FUNCTION<%0...%1> %0CVu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55355)
		#define UNIQUE_FUNCTION<%0...%1> %0CVv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55356)
		#define UNIQUE_FUNCTION<%0...%1> %0CVw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55357)
		#define UNIQUE_FUNCTION<%0...%1> %0CVx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (55357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55358)
		#define UNIQUE_FUNCTION<%0...%1> %0CVy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (55359)
		#define UNIQUE_FUNCTION<%0...%1> %0CVz%1
		#endinput
	#endif
#endif
