static stock const Y_UNIQUE_010880_010943_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_010880_010943
	#undef _inc_y_unique_010880_010943
#endif

#if UNIQUE_SYMBOL < (10887)
	#if UNIQUE_SYMBOL == (10879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10880)
		#define UNIQUE_FUNCTION<%0...%1> %02e0%1
		#endinput
	#if UNIQUE_SYMBOL == (10880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10881)
		#define UNIQUE_FUNCTION<%0...%1> %02e1%1
		#endinput
	#if UNIQUE_SYMBOL == (10881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10882)
		#define UNIQUE_FUNCTION<%0...%1> %02e2%1
		#endinput
	#if UNIQUE_SYMBOL == (10882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10883)
		#define UNIQUE_FUNCTION<%0...%1> %02e3%1
		#endinput
	#if UNIQUE_SYMBOL == (10883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10884)
		#define UNIQUE_FUNCTION<%0...%1> %02e4%1
		#endinput
	#if UNIQUE_SYMBOL == (10884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10885)
		#define UNIQUE_FUNCTION<%0...%1> %02e5%1
		#endinput
	#if UNIQUE_SYMBOL == (10885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10886)
		#define UNIQUE_FUNCTION<%0...%1> %02e6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10887)
		#define UNIQUE_FUNCTION<%0...%1> %02e7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10895)
	#elseif UNIQUE_SYMBOL == (10887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10888)
		#define UNIQUE_FUNCTION<%0...%1> %02e8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10889)
		#define UNIQUE_FUNCTION<%0...%1> %02e9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10890)
		#define UNIQUE_FUNCTION<%0...%1> %02e@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10891)
		#define UNIQUE_FUNCTION<%0...%1> %02eA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10892)
		#define UNIQUE_FUNCTION<%0...%1> %02eB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10893)
		#define UNIQUE_FUNCTION<%0...%1> %02eC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10894)
		#define UNIQUE_FUNCTION<%0...%1> %02eD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10895)
		#define UNIQUE_FUNCTION<%0...%1> %02eE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10903)
	#elseif UNIQUE_SYMBOL == (10895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10896)
		#define UNIQUE_FUNCTION<%0...%1> %02eF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10897)
		#define UNIQUE_FUNCTION<%0...%1> %02eG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10898)
		#define UNIQUE_FUNCTION<%0...%1> %02eH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10899)
		#define UNIQUE_FUNCTION<%0...%1> %02eI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10900)
		#define UNIQUE_FUNCTION<%0...%1> %02eJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10901)
		#define UNIQUE_FUNCTION<%0...%1> %02eK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10902)
		#define UNIQUE_FUNCTION<%0...%1> %02eL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10903)
		#define UNIQUE_FUNCTION<%0...%1> %02eM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10911)
	#elseif UNIQUE_SYMBOL == (10903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10904)
		#define UNIQUE_FUNCTION<%0...%1> %02eN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10905)
		#define UNIQUE_FUNCTION<%0...%1> %02eO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10906)
		#define UNIQUE_FUNCTION<%0...%1> %02eP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10907)
		#define UNIQUE_FUNCTION<%0...%1> %02eQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10908)
		#define UNIQUE_FUNCTION<%0...%1> %02eR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10909)
		#define UNIQUE_FUNCTION<%0...%1> %02eS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10910)
		#define UNIQUE_FUNCTION<%0...%1> %02eT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10911)
		#define UNIQUE_FUNCTION<%0...%1> %02eU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10919)
	#elseif UNIQUE_SYMBOL == (10911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10912)
		#define UNIQUE_FUNCTION<%0...%1> %02eV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10913)
		#define UNIQUE_FUNCTION<%0...%1> %02eW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10914)
		#define UNIQUE_FUNCTION<%0...%1> %02eX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10915)
		#define UNIQUE_FUNCTION<%0...%1> %02eY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10916)
		#define UNIQUE_FUNCTION<%0...%1> %02eZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10917)
		#define UNIQUE_FUNCTION<%0...%1> %02e_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10918)
		#define UNIQUE_FUNCTION<%0...%1> %02ea%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10919)
		#define UNIQUE_FUNCTION<%0...%1> %02eb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10927)
	#elseif UNIQUE_SYMBOL == (10919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10920)
		#define UNIQUE_FUNCTION<%0...%1> %02ec%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10921)
		#define UNIQUE_FUNCTION<%0...%1> %02ed%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10922)
		#define UNIQUE_FUNCTION<%0...%1> %02ee%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10923)
		#define UNIQUE_FUNCTION<%0...%1> %02ef%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10924)
		#define UNIQUE_FUNCTION<%0...%1> %02eg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10925)
		#define UNIQUE_FUNCTION<%0...%1> %02eh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10926)
		#define UNIQUE_FUNCTION<%0...%1> %02ei%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10927)
		#define UNIQUE_FUNCTION<%0...%1> %02ej%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10935)
	#elseif UNIQUE_SYMBOL == (10927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10928)
		#define UNIQUE_FUNCTION<%0...%1> %02ek%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10929)
		#define UNIQUE_FUNCTION<%0...%1> %02el%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10930)
		#define UNIQUE_FUNCTION<%0...%1> %02em%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10931)
		#define UNIQUE_FUNCTION<%0...%1> %02en%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10932)
		#define UNIQUE_FUNCTION<%0...%1> %02eo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10933)
		#define UNIQUE_FUNCTION<%0...%1> %02ep%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10934)
		#define UNIQUE_FUNCTION<%0...%1> %02eq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10935)
		#define UNIQUE_FUNCTION<%0...%1> %02er%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (10935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10936)
		#define UNIQUE_FUNCTION<%0...%1> %02es%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10937)
		#define UNIQUE_FUNCTION<%0...%1> %02et%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10938)
		#define UNIQUE_FUNCTION<%0...%1> %02eu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10939)
		#define UNIQUE_FUNCTION<%0...%1> %02ev%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10940)
		#define UNIQUE_FUNCTION<%0...%1> %02ew%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10941)
		#define UNIQUE_FUNCTION<%0...%1> %02ex%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10942)
		#define UNIQUE_FUNCTION<%0...%1> %02ey%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10943)
		#define UNIQUE_FUNCTION<%0...%1> %02ez%1
		#endinput
	#endif
#endif
