static stock const Y_UNIQUE_136064_136127_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_136064_136127
	#undef _inc_y_unique_136064_136127
#endif

#if UNIQUE_SYMBOL < (136071)
	#if UNIQUE_SYMBOL == (136063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136064)
		#define UNIQUE_FUNCTION<%0...%1> %0WD0%1
		#endinput
	#if UNIQUE_SYMBOL == (136064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136065)
		#define UNIQUE_FUNCTION<%0...%1> %0WD1%1
		#endinput
	#if UNIQUE_SYMBOL == (136065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136066)
		#define UNIQUE_FUNCTION<%0...%1> %0WD2%1
		#endinput
	#if UNIQUE_SYMBOL == (136066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136067)
		#define UNIQUE_FUNCTION<%0...%1> %0WD3%1
		#endinput
	#if UNIQUE_SYMBOL == (136067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136068)
		#define UNIQUE_FUNCTION<%0...%1> %0WD4%1
		#endinput
	#if UNIQUE_SYMBOL == (136068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136069)
		#define UNIQUE_FUNCTION<%0...%1> %0WD5%1
		#endinput
	#if UNIQUE_SYMBOL == (136069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136070)
		#define UNIQUE_FUNCTION<%0...%1> %0WD6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136071)
		#define UNIQUE_FUNCTION<%0...%1> %0WD7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136079)
	#elseif UNIQUE_SYMBOL == (136071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136072)
		#define UNIQUE_FUNCTION<%0...%1> %0WD8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136073)
		#define UNIQUE_FUNCTION<%0...%1> %0WD9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136074)
		#define UNIQUE_FUNCTION<%0...%1> %0WD@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136075)
		#define UNIQUE_FUNCTION<%0...%1> %0WDA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136076)
		#define UNIQUE_FUNCTION<%0...%1> %0WDB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136077)
		#define UNIQUE_FUNCTION<%0...%1> %0WDC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136078)
		#define UNIQUE_FUNCTION<%0...%1> %0WDD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136079)
		#define UNIQUE_FUNCTION<%0...%1> %0WDE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136087)
	#elseif UNIQUE_SYMBOL == (136079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136080)
		#define UNIQUE_FUNCTION<%0...%1> %0WDF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136081)
		#define UNIQUE_FUNCTION<%0...%1> %0WDG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136082)
		#define UNIQUE_FUNCTION<%0...%1> %0WDH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136083)
		#define UNIQUE_FUNCTION<%0...%1> %0WDI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136084)
		#define UNIQUE_FUNCTION<%0...%1> %0WDJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136085)
		#define UNIQUE_FUNCTION<%0...%1> %0WDK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136086)
		#define UNIQUE_FUNCTION<%0...%1> %0WDL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136087)
		#define UNIQUE_FUNCTION<%0...%1> %0WDM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136095)
	#elseif UNIQUE_SYMBOL == (136087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136088)
		#define UNIQUE_FUNCTION<%0...%1> %0WDN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136089)
		#define UNIQUE_FUNCTION<%0...%1> %0WDO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136090)
		#define UNIQUE_FUNCTION<%0...%1> %0WDP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136091)
		#define UNIQUE_FUNCTION<%0...%1> %0WDQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136092)
		#define UNIQUE_FUNCTION<%0...%1> %0WDR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136093)
		#define UNIQUE_FUNCTION<%0...%1> %0WDS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136094)
		#define UNIQUE_FUNCTION<%0...%1> %0WDT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136095)
		#define UNIQUE_FUNCTION<%0...%1> %0WDU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136103)
	#elseif UNIQUE_SYMBOL == (136095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136096)
		#define UNIQUE_FUNCTION<%0...%1> %0WDV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136097)
		#define UNIQUE_FUNCTION<%0...%1> %0WDW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136098)
		#define UNIQUE_FUNCTION<%0...%1> %0WDX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136099)
		#define UNIQUE_FUNCTION<%0...%1> %0WDY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136100)
		#define UNIQUE_FUNCTION<%0...%1> %0WDZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136101)
		#define UNIQUE_FUNCTION<%0...%1> %0WD_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136102)
		#define UNIQUE_FUNCTION<%0...%1> %0WDa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136103)
		#define UNIQUE_FUNCTION<%0...%1> %0WDb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136111)
	#elseif UNIQUE_SYMBOL == (136103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136104)
		#define UNIQUE_FUNCTION<%0...%1> %0WDc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136105)
		#define UNIQUE_FUNCTION<%0...%1> %0WDd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136106)
		#define UNIQUE_FUNCTION<%0...%1> %0WDe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136107)
		#define UNIQUE_FUNCTION<%0...%1> %0WDf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136108)
		#define UNIQUE_FUNCTION<%0...%1> %0WDg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136109)
		#define UNIQUE_FUNCTION<%0...%1> %0WDh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136110)
		#define UNIQUE_FUNCTION<%0...%1> %0WDi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136111)
		#define UNIQUE_FUNCTION<%0...%1> %0WDj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136119)
	#elseif UNIQUE_SYMBOL == (136111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136112)
		#define UNIQUE_FUNCTION<%0...%1> %0WDk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136113)
		#define UNIQUE_FUNCTION<%0...%1> %0WDl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136114)
		#define UNIQUE_FUNCTION<%0...%1> %0WDm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136115)
		#define UNIQUE_FUNCTION<%0...%1> %0WDn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136116)
		#define UNIQUE_FUNCTION<%0...%1> %0WDo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136117)
		#define UNIQUE_FUNCTION<%0...%1> %0WDp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136118)
		#define UNIQUE_FUNCTION<%0...%1> %0WDq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136119)
		#define UNIQUE_FUNCTION<%0...%1> %0WDr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (136119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136120)
		#define UNIQUE_FUNCTION<%0...%1> %0WDs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136121)
		#define UNIQUE_FUNCTION<%0...%1> %0WDt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136122)
		#define UNIQUE_FUNCTION<%0...%1> %0WDu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136123)
		#define UNIQUE_FUNCTION<%0...%1> %0WDv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136124)
		#define UNIQUE_FUNCTION<%0...%1> %0WDw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136125)
		#define UNIQUE_FUNCTION<%0...%1> %0WDx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136126)
		#define UNIQUE_FUNCTION<%0...%1> %0WDy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136127)
		#define UNIQUE_FUNCTION<%0...%1> %0WDz%1
		#endinput
	#endif
#endif
