static stock const Y_UNIQUE_003776_003839_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_003776_003839
	#undef _inc_y_unique_003776_003839
#endif

#if UNIQUE_SYMBOL < (3783)
	#if UNIQUE_SYMBOL == (3775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3776)
		#define UNIQUE_FUNCTION<%0...%1> %00v0%1
		#endinput
	#if UNIQUE_SYMBOL == (3776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3777)
		#define UNIQUE_FUNCTION<%0...%1> %00v1%1
		#endinput
	#if UNIQUE_SYMBOL == (3777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3778)
		#define UNIQUE_FUNCTION<%0...%1> %00v2%1
		#endinput
	#if UNIQUE_SYMBOL == (3778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3779)
		#define UNIQUE_FUNCTION<%0...%1> %00v3%1
		#endinput
	#if UNIQUE_SYMBOL == (3779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3780)
		#define UNIQUE_FUNCTION<%0...%1> %00v4%1
		#endinput
	#if UNIQUE_SYMBOL == (3780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3781)
		#define UNIQUE_FUNCTION<%0...%1> %00v5%1
		#endinput
	#if UNIQUE_SYMBOL == (3781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3782)
		#define UNIQUE_FUNCTION<%0...%1> %00v6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3783)
		#define UNIQUE_FUNCTION<%0...%1> %00v7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3791)
	#elseif UNIQUE_SYMBOL == (3783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3784)
		#define UNIQUE_FUNCTION<%0...%1> %00v8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3785)
		#define UNIQUE_FUNCTION<%0...%1> %00v9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3786)
		#define UNIQUE_FUNCTION<%0...%1> %00v@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3787)
		#define UNIQUE_FUNCTION<%0...%1> %00vA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3788)
		#define UNIQUE_FUNCTION<%0...%1> %00vB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3789)
		#define UNIQUE_FUNCTION<%0...%1> %00vC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3790)
		#define UNIQUE_FUNCTION<%0...%1> %00vD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3791)
		#define UNIQUE_FUNCTION<%0...%1> %00vE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3799)
	#elseif UNIQUE_SYMBOL == (3791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3792)
		#define UNIQUE_FUNCTION<%0...%1> %00vF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3793)
		#define UNIQUE_FUNCTION<%0...%1> %00vG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3794)
		#define UNIQUE_FUNCTION<%0...%1> %00vH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3795)
		#define UNIQUE_FUNCTION<%0...%1> %00vI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3796)
		#define UNIQUE_FUNCTION<%0...%1> %00vJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3797)
		#define UNIQUE_FUNCTION<%0...%1> %00vK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3798)
		#define UNIQUE_FUNCTION<%0...%1> %00vL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3799)
		#define UNIQUE_FUNCTION<%0...%1> %00vM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3807)
	#elseif UNIQUE_SYMBOL == (3799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3800)
		#define UNIQUE_FUNCTION<%0...%1> %00vN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3801)
		#define UNIQUE_FUNCTION<%0...%1> %00vO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3802)
		#define UNIQUE_FUNCTION<%0...%1> %00vP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3803)
		#define UNIQUE_FUNCTION<%0...%1> %00vQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3804)
		#define UNIQUE_FUNCTION<%0...%1> %00vR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3805)
		#define UNIQUE_FUNCTION<%0...%1> %00vS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3806)
		#define UNIQUE_FUNCTION<%0...%1> %00vT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3807)
		#define UNIQUE_FUNCTION<%0...%1> %00vU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3815)
	#elseif UNIQUE_SYMBOL == (3807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3808)
		#define UNIQUE_FUNCTION<%0...%1> %00vV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3809)
		#define UNIQUE_FUNCTION<%0...%1> %00vW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3810)
		#define UNIQUE_FUNCTION<%0...%1> %00vX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3811)
		#define UNIQUE_FUNCTION<%0...%1> %00vY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3812)
		#define UNIQUE_FUNCTION<%0...%1> %00vZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3813)
		#define UNIQUE_FUNCTION<%0...%1> %00v_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3814)
		#define UNIQUE_FUNCTION<%0...%1> %00va%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3815)
		#define UNIQUE_FUNCTION<%0...%1> %00vb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3823)
	#elseif UNIQUE_SYMBOL == (3815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3816)
		#define UNIQUE_FUNCTION<%0...%1> %00vc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3817)
		#define UNIQUE_FUNCTION<%0...%1> %00vd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3818)
		#define UNIQUE_FUNCTION<%0...%1> %00ve%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3819)
		#define UNIQUE_FUNCTION<%0...%1> %00vf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3820)
		#define UNIQUE_FUNCTION<%0...%1> %00vg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3821)
		#define UNIQUE_FUNCTION<%0...%1> %00vh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3822)
		#define UNIQUE_FUNCTION<%0...%1> %00vi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3823)
		#define UNIQUE_FUNCTION<%0...%1> %00vj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3831)
	#elseif UNIQUE_SYMBOL == (3823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3824)
		#define UNIQUE_FUNCTION<%0...%1> %00vk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3825)
		#define UNIQUE_FUNCTION<%0...%1> %00vl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3826)
		#define UNIQUE_FUNCTION<%0...%1> %00vm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3827)
		#define UNIQUE_FUNCTION<%0...%1> %00vn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3828)
		#define UNIQUE_FUNCTION<%0...%1> %00vo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3829)
		#define UNIQUE_FUNCTION<%0...%1> %00vp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3830)
		#define UNIQUE_FUNCTION<%0...%1> %00vq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3831)
		#define UNIQUE_FUNCTION<%0...%1> %00vr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (3831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3832)
		#define UNIQUE_FUNCTION<%0...%1> %00vs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3833)
		#define UNIQUE_FUNCTION<%0...%1> %00vt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3834)
		#define UNIQUE_FUNCTION<%0...%1> %00vu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3835)
		#define UNIQUE_FUNCTION<%0...%1> %00vv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3836)
		#define UNIQUE_FUNCTION<%0...%1> %00vw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3837)
		#define UNIQUE_FUNCTION<%0...%1> %00vx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3838)
		#define UNIQUE_FUNCTION<%0...%1> %00vy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3839)
		#define UNIQUE_FUNCTION<%0...%1> %00vz%1
		#endinput
	#endif
#endif
