static stock const Y_UNIQUE_050624_050687_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_050624_050687
	#undef _inc_y_unique_050624_050687
#endif

#if UNIQUE_SYMBOL < (50631)
	#if UNIQUE_SYMBOL == (50623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50624)
		#define UNIQUE_FUNCTION<%0...%1> %0BM0%1
		#endinput
	#if UNIQUE_SYMBOL == (50624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50625)
		#define UNIQUE_FUNCTION<%0...%1> %0BM1%1
		#endinput
	#if UNIQUE_SYMBOL == (50625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50626)
		#define UNIQUE_FUNCTION<%0...%1> %0BM2%1
		#endinput
	#if UNIQUE_SYMBOL == (50626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50627)
		#define UNIQUE_FUNCTION<%0...%1> %0BM3%1
		#endinput
	#if UNIQUE_SYMBOL == (50627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50628)
		#define UNIQUE_FUNCTION<%0...%1> %0BM4%1
		#endinput
	#if UNIQUE_SYMBOL == (50628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50629)
		#define UNIQUE_FUNCTION<%0...%1> %0BM5%1
		#endinput
	#if UNIQUE_SYMBOL == (50629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50630)
		#define UNIQUE_FUNCTION<%0...%1> %0BM6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50631)
		#define UNIQUE_FUNCTION<%0...%1> %0BM7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50639)
	#elseif UNIQUE_SYMBOL == (50631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50632)
		#define UNIQUE_FUNCTION<%0...%1> %0BM8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50633)
		#define UNIQUE_FUNCTION<%0...%1> %0BM9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50634)
		#define UNIQUE_FUNCTION<%0...%1> %0BM@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50635)
		#define UNIQUE_FUNCTION<%0...%1> %0BMA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50636)
		#define UNIQUE_FUNCTION<%0...%1> %0BMB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50637)
		#define UNIQUE_FUNCTION<%0...%1> %0BMC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50638)
		#define UNIQUE_FUNCTION<%0...%1> %0BMD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50639)
		#define UNIQUE_FUNCTION<%0...%1> %0BME%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50647)
	#elseif UNIQUE_SYMBOL == (50639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50640)
		#define UNIQUE_FUNCTION<%0...%1> %0BMF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50641)
		#define UNIQUE_FUNCTION<%0...%1> %0BMG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50642)
		#define UNIQUE_FUNCTION<%0...%1> %0BMH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50643)
		#define UNIQUE_FUNCTION<%0...%1> %0BMI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50644)
		#define UNIQUE_FUNCTION<%0...%1> %0BMJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50645)
		#define UNIQUE_FUNCTION<%0...%1> %0BMK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50646)
		#define UNIQUE_FUNCTION<%0...%1> %0BML%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50647)
		#define UNIQUE_FUNCTION<%0...%1> %0BMM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50655)
	#elseif UNIQUE_SYMBOL == (50647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50648)
		#define UNIQUE_FUNCTION<%0...%1> %0BMN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50649)
		#define UNIQUE_FUNCTION<%0...%1> %0BMO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50650)
		#define UNIQUE_FUNCTION<%0...%1> %0BMP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50651)
		#define UNIQUE_FUNCTION<%0...%1> %0BMQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50652)
		#define UNIQUE_FUNCTION<%0...%1> %0BMR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50653)
		#define UNIQUE_FUNCTION<%0...%1> %0BMS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50654)
		#define UNIQUE_FUNCTION<%0...%1> %0BMT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50655)
		#define UNIQUE_FUNCTION<%0...%1> %0BMU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50663)
	#elseif UNIQUE_SYMBOL == (50655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50656)
		#define UNIQUE_FUNCTION<%0...%1> %0BMV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50657)
		#define UNIQUE_FUNCTION<%0...%1> %0BMW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50658)
		#define UNIQUE_FUNCTION<%0...%1> %0BMX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50659)
		#define UNIQUE_FUNCTION<%0...%1> %0BMY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50660)
		#define UNIQUE_FUNCTION<%0...%1> %0BMZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50661)
		#define UNIQUE_FUNCTION<%0...%1> %0BM_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50662)
		#define UNIQUE_FUNCTION<%0...%1> %0BMa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50663)
		#define UNIQUE_FUNCTION<%0...%1> %0BMb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50671)
	#elseif UNIQUE_SYMBOL == (50663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50664)
		#define UNIQUE_FUNCTION<%0...%1> %0BMc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50665)
		#define UNIQUE_FUNCTION<%0...%1> %0BMd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50666)
		#define UNIQUE_FUNCTION<%0...%1> %0BMe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50667)
		#define UNIQUE_FUNCTION<%0...%1> %0BMf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50668)
		#define UNIQUE_FUNCTION<%0...%1> %0BMg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50669)
		#define UNIQUE_FUNCTION<%0...%1> %0BMh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50670)
		#define UNIQUE_FUNCTION<%0...%1> %0BMi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50671)
		#define UNIQUE_FUNCTION<%0...%1> %0BMj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50679)
	#elseif UNIQUE_SYMBOL == (50671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50672)
		#define UNIQUE_FUNCTION<%0...%1> %0BMk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50673)
		#define UNIQUE_FUNCTION<%0...%1> %0BMl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50674)
		#define UNIQUE_FUNCTION<%0...%1> %0BMm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50675)
		#define UNIQUE_FUNCTION<%0...%1> %0BMn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50676)
		#define UNIQUE_FUNCTION<%0...%1> %0BMo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50677)
		#define UNIQUE_FUNCTION<%0...%1> %0BMp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50678)
		#define UNIQUE_FUNCTION<%0...%1> %0BMq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50679)
		#define UNIQUE_FUNCTION<%0...%1> %0BMr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (50679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50680)
		#define UNIQUE_FUNCTION<%0...%1> %0BMs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50681)
		#define UNIQUE_FUNCTION<%0...%1> %0BMt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50682)
		#define UNIQUE_FUNCTION<%0...%1> %0BMu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50683)
		#define UNIQUE_FUNCTION<%0...%1> %0BMv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50684)
		#define UNIQUE_FUNCTION<%0...%1> %0BMw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50685)
		#define UNIQUE_FUNCTION<%0...%1> %0BMx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50686)
		#define UNIQUE_FUNCTION<%0...%1> %0BMy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50687)
		#define UNIQUE_FUNCTION<%0...%1> %0BMz%1
		#endinput
	#endif
#endif
