static stock const Y_UNIQUE_1664_1727_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_1664_1727
	#undef _inc_y_unique_1664_1727
#endif

#if UNIQUE_SYMBOL < (1671)
	#if UNIQUE_SYMBOL == (1663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1664)
		#define UNIQUE_FUNCTION<%0...%1> %0P0%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1665)
		#define UNIQUE_FUNCTION<%0...%1> %0P1%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1666)
		#define UNIQUE_FUNCTION<%0...%1> %0P2%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1667)
		#define UNIQUE_FUNCTION<%0...%1> %0P3%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1668)
		#define UNIQUE_FUNCTION<%0...%1> %0P4%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1669)
		#define UNIQUE_FUNCTION<%0...%1> %0P5%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1670)
		#define UNIQUE_FUNCTION<%0...%1> %0P6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1671)
		#define UNIQUE_FUNCTION<%0...%1> %0P7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (1679)
	#if UNIQUE_SYMBOL == (1671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1672)
		#define UNIQUE_FUNCTION<%0...%1> %0P8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1673)
		#define UNIQUE_FUNCTION<%0...%1> %0P9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1674)
		#define UNIQUE_FUNCTION<%0...%1> %0P@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1675)
		#define UNIQUE_FUNCTION<%0...%1> %0PA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1676)
		#define UNIQUE_FUNCTION<%0...%1> %0PB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1677)
		#define UNIQUE_FUNCTION<%0...%1> %0PC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1678)
		#define UNIQUE_FUNCTION<%0...%1> %0PD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1679)
		#define UNIQUE_FUNCTION<%0...%1> %0PE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (1687)
	#if UNIQUE_SYMBOL == (1679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1680)
		#define UNIQUE_FUNCTION<%0...%1> %0PF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1681)
		#define UNIQUE_FUNCTION<%0...%1> %0PG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1682)
		#define UNIQUE_FUNCTION<%0...%1> %0PH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1683)
		#define UNIQUE_FUNCTION<%0...%1> %0PI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1684)
		#define UNIQUE_FUNCTION<%0...%1> %0PJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1685)
		#define UNIQUE_FUNCTION<%0...%1> %0PK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1686)
		#define UNIQUE_FUNCTION<%0...%1> %0PL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1687)
		#define UNIQUE_FUNCTION<%0...%1> %0PM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (1695)
	#if UNIQUE_SYMBOL == (1687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1688)
		#define UNIQUE_FUNCTION<%0...%1> %0PN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1689)
		#define UNIQUE_FUNCTION<%0...%1> %0PO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1690)
		#define UNIQUE_FUNCTION<%0...%1> %0PP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1691)
		#define UNIQUE_FUNCTION<%0...%1> %0PQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1692)
		#define UNIQUE_FUNCTION<%0...%1> %0PR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1693)
		#define UNIQUE_FUNCTION<%0...%1> %0PS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1694)
		#define UNIQUE_FUNCTION<%0...%1> %0PT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1695)
		#define UNIQUE_FUNCTION<%0...%1> %0PU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (1703)
	#if UNIQUE_SYMBOL == (1695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1696)
		#define UNIQUE_FUNCTION<%0...%1> %0PV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1697)
		#define UNIQUE_FUNCTION<%0...%1> %0PW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1698)
		#define UNIQUE_FUNCTION<%0...%1> %0PX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1699)
		#define UNIQUE_FUNCTION<%0...%1> %0PY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1700)
		#define UNIQUE_FUNCTION<%0...%1> %0PZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1701)
		#define UNIQUE_FUNCTION<%0...%1> %0P_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1702)
		#define UNIQUE_FUNCTION<%0...%1> %0Pa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1703)
		#define UNIQUE_FUNCTION<%0...%1> %0Pb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (1711)
	#if UNIQUE_SYMBOL == (1703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1704)
		#define UNIQUE_FUNCTION<%0...%1> %0Pc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1705)
		#define UNIQUE_FUNCTION<%0...%1> %0Pd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1706)
		#define UNIQUE_FUNCTION<%0...%1> %0Pe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1707)
		#define UNIQUE_FUNCTION<%0...%1> %0Pf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1708)
		#define UNIQUE_FUNCTION<%0...%1> %0Pg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1709)
		#define UNIQUE_FUNCTION<%0...%1> %0Ph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1710)
		#define UNIQUE_FUNCTION<%0...%1> %0Pi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1711)
		#define UNIQUE_FUNCTION<%0...%1> %0Pj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (1719)
	#if UNIQUE_SYMBOL == (1711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1712)
		#define UNIQUE_FUNCTION<%0...%1> %0Pk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1713)
		#define UNIQUE_FUNCTION<%0...%1> %0Pl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1714)
		#define UNIQUE_FUNCTION<%0...%1> %0Pm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1715)
		#define UNIQUE_FUNCTION<%0...%1> %0Pn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1716)
		#define UNIQUE_FUNCTION<%0...%1> %0Po%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1717)
		#define UNIQUE_FUNCTION<%0...%1> %0Pp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1718)
		#define UNIQUE_FUNCTION<%0...%1> %0Pq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1719)
		#define UNIQUE_FUNCTION<%0...%1> %0Pr%1
		#endinput
	#endif
#else
	#if UNIQUE_SYMBOL == (1719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1720)
		#define UNIQUE_FUNCTION<%0...%1> %0Ps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1721)
		#define UNIQUE_FUNCTION<%0...%1> %0Pt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1722)
		#define UNIQUE_FUNCTION<%0...%1> %0Pu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1723)
		#define UNIQUE_FUNCTION<%0...%1> %0Pv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1724)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1725)
		#define UNIQUE_FUNCTION<%0...%1> %0Px%1
		#endinput
	#elseif UNIQUE_SYMBOL == (1725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1726)
		#define UNIQUE_FUNCTION<%0...%1> %0Py%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (1727)
		#define UNIQUE_FUNCTION<%0...%1> %0Pz%1
		#endinput
	#endif
#endif

