static stock const Y_UNIQUE_120960_121023_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_120960_121023
	#undef _inc_y_unique_120960_121023
#endif

#if UNIQUE_SYMBOL < (120967)
	#if UNIQUE_SYMBOL == (120959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120960)
		#define UNIQUE_FUNCTION<%0...%1> %0SX0%1
		#endinput
	#if UNIQUE_SYMBOL == (120960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120961)
		#define UNIQUE_FUNCTION<%0...%1> %0SX1%1
		#endinput
	#if UNIQUE_SYMBOL == (120961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120962)
		#define UNIQUE_FUNCTION<%0...%1> %0SX2%1
		#endinput
	#if UNIQUE_SYMBOL == (120962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120963)
		#define UNIQUE_FUNCTION<%0...%1> %0SX3%1
		#endinput
	#if UNIQUE_SYMBOL == (120963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120964)
		#define UNIQUE_FUNCTION<%0...%1> %0SX4%1
		#endinput
	#if UNIQUE_SYMBOL == (120964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120965)
		#define UNIQUE_FUNCTION<%0...%1> %0SX5%1
		#endinput
	#if UNIQUE_SYMBOL == (120965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120966)
		#define UNIQUE_FUNCTION<%0...%1> %0SX6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120967)
		#define UNIQUE_FUNCTION<%0...%1> %0SX7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120975)
	#elseif UNIQUE_SYMBOL == (120967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120968)
		#define UNIQUE_FUNCTION<%0...%1> %0SX8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120969)
		#define UNIQUE_FUNCTION<%0...%1> %0SX9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120970)
		#define UNIQUE_FUNCTION<%0...%1> %0SX@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120971)
		#define UNIQUE_FUNCTION<%0...%1> %0SXA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120972)
		#define UNIQUE_FUNCTION<%0...%1> %0SXB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120973)
		#define UNIQUE_FUNCTION<%0...%1> %0SXC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120974)
		#define UNIQUE_FUNCTION<%0...%1> %0SXD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120975)
		#define UNIQUE_FUNCTION<%0...%1> %0SXE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120983)
	#elseif UNIQUE_SYMBOL == (120975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120976)
		#define UNIQUE_FUNCTION<%0...%1> %0SXF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120977)
		#define UNIQUE_FUNCTION<%0...%1> %0SXG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120978)
		#define UNIQUE_FUNCTION<%0...%1> %0SXH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120979)
		#define UNIQUE_FUNCTION<%0...%1> %0SXI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120980)
		#define UNIQUE_FUNCTION<%0...%1> %0SXJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120981)
		#define UNIQUE_FUNCTION<%0...%1> %0SXK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120982)
		#define UNIQUE_FUNCTION<%0...%1> %0SXL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120983)
		#define UNIQUE_FUNCTION<%0...%1> %0SXM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120991)
	#elseif UNIQUE_SYMBOL == (120983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120984)
		#define UNIQUE_FUNCTION<%0...%1> %0SXN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120985)
		#define UNIQUE_FUNCTION<%0...%1> %0SXO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120986)
		#define UNIQUE_FUNCTION<%0...%1> %0SXP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120987)
		#define UNIQUE_FUNCTION<%0...%1> %0SXQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120988)
		#define UNIQUE_FUNCTION<%0...%1> %0SXR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120989)
		#define UNIQUE_FUNCTION<%0...%1> %0SXS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120990)
		#define UNIQUE_FUNCTION<%0...%1> %0SXT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120991)
		#define UNIQUE_FUNCTION<%0...%1> %0SXU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120999)
	#elseif UNIQUE_SYMBOL == (120991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120992)
		#define UNIQUE_FUNCTION<%0...%1> %0SXV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120993)
		#define UNIQUE_FUNCTION<%0...%1> %0SXW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120994)
		#define UNIQUE_FUNCTION<%0...%1> %0SXX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120995)
		#define UNIQUE_FUNCTION<%0...%1> %0SXY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120996)
		#define UNIQUE_FUNCTION<%0...%1> %0SXZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120997)
		#define UNIQUE_FUNCTION<%0...%1> %0SX_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120998)
		#define UNIQUE_FUNCTION<%0...%1> %0SXa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120999)
		#define UNIQUE_FUNCTION<%0...%1> %0SXb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (121007)
	#elseif UNIQUE_SYMBOL == (120999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121000)
		#define UNIQUE_FUNCTION<%0...%1> %0SXc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121001)
		#define UNIQUE_FUNCTION<%0...%1> %0SXd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121002)
		#define UNIQUE_FUNCTION<%0...%1> %0SXe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121003)
		#define UNIQUE_FUNCTION<%0...%1> %0SXf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121004)
		#define UNIQUE_FUNCTION<%0...%1> %0SXg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121005)
		#define UNIQUE_FUNCTION<%0...%1> %0SXh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121006)
		#define UNIQUE_FUNCTION<%0...%1> %0SXi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121007)
		#define UNIQUE_FUNCTION<%0...%1> %0SXj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (121015)
	#elseif UNIQUE_SYMBOL == (121007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121008)
		#define UNIQUE_FUNCTION<%0...%1> %0SXk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121009)
		#define UNIQUE_FUNCTION<%0...%1> %0SXl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121010)
		#define UNIQUE_FUNCTION<%0...%1> %0SXm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121011)
		#define UNIQUE_FUNCTION<%0...%1> %0SXn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121012)
		#define UNIQUE_FUNCTION<%0...%1> %0SXo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121013)
		#define UNIQUE_FUNCTION<%0...%1> %0SXp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121014)
		#define UNIQUE_FUNCTION<%0...%1> %0SXq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121015)
		#define UNIQUE_FUNCTION<%0...%1> %0SXr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (121015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121016)
		#define UNIQUE_FUNCTION<%0...%1> %0SXs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121017)
		#define UNIQUE_FUNCTION<%0...%1> %0SXt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121018)
		#define UNIQUE_FUNCTION<%0...%1> %0SXu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121019)
		#define UNIQUE_FUNCTION<%0...%1> %0SXv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121020)
		#define UNIQUE_FUNCTION<%0...%1> %0SXw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121021)
		#define UNIQUE_FUNCTION<%0...%1> %0SXx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121022)
		#define UNIQUE_FUNCTION<%0...%1> %0SXy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121023)
		#define UNIQUE_FUNCTION<%0...%1> %0SXz%1
		#endinput
	#endif
#endif
