static stock const Y_UNIQUE_006656_006719_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_006656_006719
	#undef _inc_y_unique_006656_006719
#endif

#if UNIQUE_SYMBOL < (6663)
	#if UNIQUE_SYMBOL == (6655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6656)
		#define UNIQUE_FUNCTION<%0...%1> %01c0%1
		#endinput
	#if UNIQUE_SYMBOL == (6656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6657)
		#define UNIQUE_FUNCTION<%0...%1> %01c1%1
		#endinput
	#if UNIQUE_SYMBOL == (6657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6658)
		#define UNIQUE_FUNCTION<%0...%1> %01c2%1
		#endinput
	#if UNIQUE_SYMBOL == (6658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6659)
		#define UNIQUE_FUNCTION<%0...%1> %01c3%1
		#endinput
	#if UNIQUE_SYMBOL == (6659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6660)
		#define UNIQUE_FUNCTION<%0...%1> %01c4%1
		#endinput
	#if UNIQUE_SYMBOL == (6660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6661)
		#define UNIQUE_FUNCTION<%0...%1> %01c5%1
		#endinput
	#if UNIQUE_SYMBOL == (6661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6662)
		#define UNIQUE_FUNCTION<%0...%1> %01c6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6663)
		#define UNIQUE_FUNCTION<%0...%1> %01c7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (6671)
	#elseif UNIQUE_SYMBOL == (6663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6664)
		#define UNIQUE_FUNCTION<%0...%1> %01c8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6665)
		#define UNIQUE_FUNCTION<%0...%1> %01c9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6666)
		#define UNIQUE_FUNCTION<%0...%1> %01c@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6667)
		#define UNIQUE_FUNCTION<%0...%1> %01cA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6668)
		#define UNIQUE_FUNCTION<%0...%1> %01cB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6669)
		#define UNIQUE_FUNCTION<%0...%1> %01cC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6670)
		#define UNIQUE_FUNCTION<%0...%1> %01cD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6671)
		#define UNIQUE_FUNCTION<%0...%1> %01cE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (6679)
	#elseif UNIQUE_SYMBOL == (6671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6672)
		#define UNIQUE_FUNCTION<%0...%1> %01cF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6673)
		#define UNIQUE_FUNCTION<%0...%1> %01cG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6674)
		#define UNIQUE_FUNCTION<%0...%1> %01cH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6675)
		#define UNIQUE_FUNCTION<%0...%1> %01cI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6676)
		#define UNIQUE_FUNCTION<%0...%1> %01cJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6677)
		#define UNIQUE_FUNCTION<%0...%1> %01cK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6678)
		#define UNIQUE_FUNCTION<%0...%1> %01cL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6679)
		#define UNIQUE_FUNCTION<%0...%1> %01cM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (6687)
	#elseif UNIQUE_SYMBOL == (6679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6680)
		#define UNIQUE_FUNCTION<%0...%1> %01cN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6681)
		#define UNIQUE_FUNCTION<%0...%1> %01cO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6682)
		#define UNIQUE_FUNCTION<%0...%1> %01cP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6683)
		#define UNIQUE_FUNCTION<%0...%1> %01cQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6684)
		#define UNIQUE_FUNCTION<%0...%1> %01cR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6685)
		#define UNIQUE_FUNCTION<%0...%1> %01cS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6686)
		#define UNIQUE_FUNCTION<%0...%1> %01cT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6687)
		#define UNIQUE_FUNCTION<%0...%1> %01cU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (6695)
	#elseif UNIQUE_SYMBOL == (6687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6688)
		#define UNIQUE_FUNCTION<%0...%1> %01cV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6689)
		#define UNIQUE_FUNCTION<%0...%1> %01cW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6690)
		#define UNIQUE_FUNCTION<%0...%1> %01cX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6691)
		#define UNIQUE_FUNCTION<%0...%1> %01cY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6692)
		#define UNIQUE_FUNCTION<%0...%1> %01cZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6693)
		#define UNIQUE_FUNCTION<%0...%1> %01c_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6694)
		#define UNIQUE_FUNCTION<%0...%1> %01ca%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6695)
		#define UNIQUE_FUNCTION<%0...%1> %01cb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (6703)
	#elseif UNIQUE_SYMBOL == (6695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6696)
		#define UNIQUE_FUNCTION<%0...%1> %01cc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6697)
		#define UNIQUE_FUNCTION<%0...%1> %01cd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6698)
		#define UNIQUE_FUNCTION<%0...%1> %01ce%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6699)
		#define UNIQUE_FUNCTION<%0...%1> %01cf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6700)
		#define UNIQUE_FUNCTION<%0...%1> %01cg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6701)
		#define UNIQUE_FUNCTION<%0...%1> %01ch%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6702)
		#define UNIQUE_FUNCTION<%0...%1> %01ci%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6703)
		#define UNIQUE_FUNCTION<%0...%1> %01cj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (6711)
	#elseif UNIQUE_SYMBOL == (6703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6704)
		#define UNIQUE_FUNCTION<%0...%1> %01ck%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6705)
		#define UNIQUE_FUNCTION<%0...%1> %01cl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6706)
		#define UNIQUE_FUNCTION<%0...%1> %01cm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6707)
		#define UNIQUE_FUNCTION<%0...%1> %01cn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6708)
		#define UNIQUE_FUNCTION<%0...%1> %01co%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6709)
		#define UNIQUE_FUNCTION<%0...%1> %01cp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6710)
		#define UNIQUE_FUNCTION<%0...%1> %01cq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6711)
		#define UNIQUE_FUNCTION<%0...%1> %01cr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (6711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6712)
		#define UNIQUE_FUNCTION<%0...%1> %01cs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6713)
		#define UNIQUE_FUNCTION<%0...%1> %01ct%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6714)
		#define UNIQUE_FUNCTION<%0...%1> %01cu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6715)
		#define UNIQUE_FUNCTION<%0...%1> %01cv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6716)
		#define UNIQUE_FUNCTION<%0...%1> %01cw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6717)
		#define UNIQUE_FUNCTION<%0...%1> %01cx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (6717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6718)
		#define UNIQUE_FUNCTION<%0...%1> %01cy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (6719)
		#define UNIQUE_FUNCTION<%0...%1> %01cz%1
		#endinput
	#endif
#endif
