static stock const Y_UNIQUE_098560_098623_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_098560_098623
	#undef _inc_y_unique_098560_098623
#endif

#if UNIQUE_SYMBOL < (98567)
	#if UNIQUE_SYMBOL == (98559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98560)
		#define UNIQUE_FUNCTION<%0...%1> %0N40%1
		#endinput
	#if UNIQUE_SYMBOL == (98560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98561)
		#define UNIQUE_FUNCTION<%0...%1> %0N41%1
		#endinput
	#if UNIQUE_SYMBOL == (98561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98562)
		#define UNIQUE_FUNCTION<%0...%1> %0N42%1
		#endinput
	#if UNIQUE_SYMBOL == (98562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98563)
		#define UNIQUE_FUNCTION<%0...%1> %0N43%1
		#endinput
	#if UNIQUE_SYMBOL == (98563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98564)
		#define UNIQUE_FUNCTION<%0...%1> %0N44%1
		#endinput
	#if UNIQUE_SYMBOL == (98564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98565)
		#define UNIQUE_FUNCTION<%0...%1> %0N45%1
		#endinput
	#if UNIQUE_SYMBOL == (98565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98566)
		#define UNIQUE_FUNCTION<%0...%1> %0N46%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98567)
		#define UNIQUE_FUNCTION<%0...%1> %0N47%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98575)
	#elseif UNIQUE_SYMBOL == (98567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98568)
		#define UNIQUE_FUNCTION<%0...%1> %0N48%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98569)
		#define UNIQUE_FUNCTION<%0...%1> %0N49%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98570)
		#define UNIQUE_FUNCTION<%0...%1> %0N4@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98571)
		#define UNIQUE_FUNCTION<%0...%1> %0N4A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98572)
		#define UNIQUE_FUNCTION<%0...%1> %0N4B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98573)
		#define UNIQUE_FUNCTION<%0...%1> %0N4C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98574)
		#define UNIQUE_FUNCTION<%0...%1> %0N4D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98575)
		#define UNIQUE_FUNCTION<%0...%1> %0N4E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98583)
	#elseif UNIQUE_SYMBOL == (98575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98576)
		#define UNIQUE_FUNCTION<%0...%1> %0N4F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98577)
		#define UNIQUE_FUNCTION<%0...%1> %0N4G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98578)
		#define UNIQUE_FUNCTION<%0...%1> %0N4H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98579)
		#define UNIQUE_FUNCTION<%0...%1> %0N4I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98580)
		#define UNIQUE_FUNCTION<%0...%1> %0N4J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98581)
		#define UNIQUE_FUNCTION<%0...%1> %0N4K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98582)
		#define UNIQUE_FUNCTION<%0...%1> %0N4L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98583)
		#define UNIQUE_FUNCTION<%0...%1> %0N4M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98591)
	#elseif UNIQUE_SYMBOL == (98583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98584)
		#define UNIQUE_FUNCTION<%0...%1> %0N4N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98585)
		#define UNIQUE_FUNCTION<%0...%1> %0N4O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98586)
		#define UNIQUE_FUNCTION<%0...%1> %0N4P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98587)
		#define UNIQUE_FUNCTION<%0...%1> %0N4Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98588)
		#define UNIQUE_FUNCTION<%0...%1> %0N4R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98589)
		#define UNIQUE_FUNCTION<%0...%1> %0N4S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98590)
		#define UNIQUE_FUNCTION<%0...%1> %0N4T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98591)
		#define UNIQUE_FUNCTION<%0...%1> %0N4U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98599)
	#elseif UNIQUE_SYMBOL == (98591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98592)
		#define UNIQUE_FUNCTION<%0...%1> %0N4V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98593)
		#define UNIQUE_FUNCTION<%0...%1> %0N4W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98594)
		#define UNIQUE_FUNCTION<%0...%1> %0N4X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98595)
		#define UNIQUE_FUNCTION<%0...%1> %0N4Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98596)
		#define UNIQUE_FUNCTION<%0...%1> %0N4Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98597)
		#define UNIQUE_FUNCTION<%0...%1> %0N4_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98598)
		#define UNIQUE_FUNCTION<%0...%1> %0N4a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98599)
		#define UNIQUE_FUNCTION<%0...%1> %0N4b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98607)
	#elseif UNIQUE_SYMBOL == (98599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98600)
		#define UNIQUE_FUNCTION<%0...%1> %0N4c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98601)
		#define UNIQUE_FUNCTION<%0...%1> %0N4d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98602)
		#define UNIQUE_FUNCTION<%0...%1> %0N4e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98603)
		#define UNIQUE_FUNCTION<%0...%1> %0N4f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98604)
		#define UNIQUE_FUNCTION<%0...%1> %0N4g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98605)
		#define UNIQUE_FUNCTION<%0...%1> %0N4h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98606)
		#define UNIQUE_FUNCTION<%0...%1> %0N4i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98607)
		#define UNIQUE_FUNCTION<%0...%1> %0N4j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98615)
	#elseif UNIQUE_SYMBOL == (98607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98608)
		#define UNIQUE_FUNCTION<%0...%1> %0N4k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98609)
		#define UNIQUE_FUNCTION<%0...%1> %0N4l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98610)
		#define UNIQUE_FUNCTION<%0...%1> %0N4m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98611)
		#define UNIQUE_FUNCTION<%0...%1> %0N4n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98612)
		#define UNIQUE_FUNCTION<%0...%1> %0N4o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98613)
		#define UNIQUE_FUNCTION<%0...%1> %0N4p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98614)
		#define UNIQUE_FUNCTION<%0...%1> %0N4q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98615)
		#define UNIQUE_FUNCTION<%0...%1> %0N4r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (98615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98616)
		#define UNIQUE_FUNCTION<%0...%1> %0N4s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98617)
		#define UNIQUE_FUNCTION<%0...%1> %0N4t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98618)
		#define UNIQUE_FUNCTION<%0...%1> %0N4u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98619)
		#define UNIQUE_FUNCTION<%0...%1> %0N4v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98620)
		#define UNIQUE_FUNCTION<%0...%1> %0N4w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98621)
		#define UNIQUE_FUNCTION<%0...%1> %0N4x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98622)
		#define UNIQUE_FUNCTION<%0...%1> %0N4y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98623)
		#define UNIQUE_FUNCTION<%0...%1> %0N4z%1
		#endinput
	#endif
#endif
