static stock const Y_UNIQUE_066688_066751_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_066688_066751
	#undef _inc_y_unique_066688_066751
#endif

#if UNIQUE_SYMBOL < (66695)
	#if UNIQUE_SYMBOL == (66687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66688)
		#define UNIQUE_FUNCTION<%0...%1> %0FH0%1
		#endinput
	#if UNIQUE_SYMBOL == (66688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66689)
		#define UNIQUE_FUNCTION<%0...%1> %0FH1%1
		#endinput
	#if UNIQUE_SYMBOL == (66689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66690)
		#define UNIQUE_FUNCTION<%0...%1> %0FH2%1
		#endinput
	#if UNIQUE_SYMBOL == (66690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66691)
		#define UNIQUE_FUNCTION<%0...%1> %0FH3%1
		#endinput
	#if UNIQUE_SYMBOL == (66691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66692)
		#define UNIQUE_FUNCTION<%0...%1> %0FH4%1
		#endinput
	#if UNIQUE_SYMBOL == (66692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66693)
		#define UNIQUE_FUNCTION<%0...%1> %0FH5%1
		#endinput
	#if UNIQUE_SYMBOL == (66693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66694)
		#define UNIQUE_FUNCTION<%0...%1> %0FH6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66695)
		#define UNIQUE_FUNCTION<%0...%1> %0FH7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66703)
	#elseif UNIQUE_SYMBOL == (66695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66696)
		#define UNIQUE_FUNCTION<%0...%1> %0FH8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66697)
		#define UNIQUE_FUNCTION<%0...%1> %0FH9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66698)
		#define UNIQUE_FUNCTION<%0...%1> %0FH@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66699)
		#define UNIQUE_FUNCTION<%0...%1> %0FHA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66700)
		#define UNIQUE_FUNCTION<%0...%1> %0FHB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66701)
		#define UNIQUE_FUNCTION<%0...%1> %0FHC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66702)
		#define UNIQUE_FUNCTION<%0...%1> %0FHD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66703)
		#define UNIQUE_FUNCTION<%0...%1> %0FHE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66711)
	#elseif UNIQUE_SYMBOL == (66703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66704)
		#define UNIQUE_FUNCTION<%0...%1> %0FHF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66705)
		#define UNIQUE_FUNCTION<%0...%1> %0FHG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66706)
		#define UNIQUE_FUNCTION<%0...%1> %0FHH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66707)
		#define UNIQUE_FUNCTION<%0...%1> %0FHI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66708)
		#define UNIQUE_FUNCTION<%0...%1> %0FHJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66709)
		#define UNIQUE_FUNCTION<%0...%1> %0FHK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66710)
		#define UNIQUE_FUNCTION<%0...%1> %0FHL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66711)
		#define UNIQUE_FUNCTION<%0...%1> %0FHM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66719)
	#elseif UNIQUE_SYMBOL == (66711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66712)
		#define UNIQUE_FUNCTION<%0...%1> %0FHN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66713)
		#define UNIQUE_FUNCTION<%0...%1> %0FHO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66714)
		#define UNIQUE_FUNCTION<%0...%1> %0FHP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66715)
		#define UNIQUE_FUNCTION<%0...%1> %0FHQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66716)
		#define UNIQUE_FUNCTION<%0...%1> %0FHR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66717)
		#define UNIQUE_FUNCTION<%0...%1> %0FHS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66718)
		#define UNIQUE_FUNCTION<%0...%1> %0FHT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66719)
		#define UNIQUE_FUNCTION<%0...%1> %0FHU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66727)
	#elseif UNIQUE_SYMBOL == (66719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66720)
		#define UNIQUE_FUNCTION<%0...%1> %0FHV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66721)
		#define UNIQUE_FUNCTION<%0...%1> %0FHW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66722)
		#define UNIQUE_FUNCTION<%0...%1> %0FHX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66723)
		#define UNIQUE_FUNCTION<%0...%1> %0FHY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66724)
		#define UNIQUE_FUNCTION<%0...%1> %0FHZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66725)
		#define UNIQUE_FUNCTION<%0...%1> %0FH_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66726)
		#define UNIQUE_FUNCTION<%0...%1> %0FHa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66727)
		#define UNIQUE_FUNCTION<%0...%1> %0FHb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66735)
	#elseif UNIQUE_SYMBOL == (66727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66728)
		#define UNIQUE_FUNCTION<%0...%1> %0FHc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66729)
		#define UNIQUE_FUNCTION<%0...%1> %0FHd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66730)
		#define UNIQUE_FUNCTION<%0...%1> %0FHe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66731)
		#define UNIQUE_FUNCTION<%0...%1> %0FHf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66732)
		#define UNIQUE_FUNCTION<%0...%1> %0FHg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66733)
		#define UNIQUE_FUNCTION<%0...%1> %0FHh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66734)
		#define UNIQUE_FUNCTION<%0...%1> %0FHi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66735)
		#define UNIQUE_FUNCTION<%0...%1> %0FHj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66743)
	#elseif UNIQUE_SYMBOL == (66735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66736)
		#define UNIQUE_FUNCTION<%0...%1> %0FHk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66737)
		#define UNIQUE_FUNCTION<%0...%1> %0FHl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66738)
		#define UNIQUE_FUNCTION<%0...%1> %0FHm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66739)
		#define UNIQUE_FUNCTION<%0...%1> %0FHn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66740)
		#define UNIQUE_FUNCTION<%0...%1> %0FHo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66741)
		#define UNIQUE_FUNCTION<%0...%1> %0FHp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66742)
		#define UNIQUE_FUNCTION<%0...%1> %0FHq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66743)
		#define UNIQUE_FUNCTION<%0...%1> %0FHr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (66743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66744)
		#define UNIQUE_FUNCTION<%0...%1> %0FHs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66745)
		#define UNIQUE_FUNCTION<%0...%1> %0FHt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66746)
		#define UNIQUE_FUNCTION<%0...%1> %0FHu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66747)
		#define UNIQUE_FUNCTION<%0...%1> %0FHv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66748)
		#define UNIQUE_FUNCTION<%0...%1> %0FHw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66749)
		#define UNIQUE_FUNCTION<%0...%1> %0FHx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66750)
		#define UNIQUE_FUNCTION<%0...%1> %0FHy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66751)
		#define UNIQUE_FUNCTION<%0...%1> %0FHz%1
		#endinput
	#endif
#endif
