static stock const Y_UNIQUE_0064_0127_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_0064_0127
	#undef _inc_y_unique_0064_0127
#endif

#if UNIQUE_SYMBOL < (71)
	#if UNIQUE_SYMBOL == (63)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64)
		#define UNIQUE_FUNCTION<%0...%1> %010%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65)
		#define UNIQUE_FUNCTION<%0...%1> %011%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66)
		#define UNIQUE_FUNCTION<%0...%1> %012%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67)
		#define UNIQUE_FUNCTION<%0...%1> %013%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68)
		#define UNIQUE_FUNCTION<%0...%1> %014%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69)
		#define UNIQUE_FUNCTION<%0...%1> %015%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (70)
		#define UNIQUE_FUNCTION<%0...%1> %016%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71)
		#define UNIQUE_FUNCTION<%0...%1> %017%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79)
	#if UNIQUE_SYMBOL == (71)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72)
		#define UNIQUE_FUNCTION<%0...%1> %018%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73)
		#define UNIQUE_FUNCTION<%0...%1> %019%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74)
		#define UNIQUE_FUNCTION<%0...%1> %01@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (75)
		#define UNIQUE_FUNCTION<%0...%1> %01A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (75)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (76)
		#define UNIQUE_FUNCTION<%0...%1> %01B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (76)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (77)
		#define UNIQUE_FUNCTION<%0...%1> %01C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (77)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78)
		#define UNIQUE_FUNCTION<%0...%1> %01D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79)
		#define UNIQUE_FUNCTION<%0...%1> %01E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87)
	#if UNIQUE_SYMBOL == (79)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80)
		#define UNIQUE_FUNCTION<%0...%1> %01F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81)
		#define UNIQUE_FUNCTION<%0...%1> %01G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82)
		#define UNIQUE_FUNCTION<%0...%1> %01H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (83)
		#define UNIQUE_FUNCTION<%0...%1> %01I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (83)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (84)
		#define UNIQUE_FUNCTION<%0...%1> %01J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (84)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (85)
		#define UNIQUE_FUNCTION<%0...%1> %01K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (85)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (86)
		#define UNIQUE_FUNCTION<%0...%1> %01L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87)
		#define UNIQUE_FUNCTION<%0...%1> %01M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95)
	#if UNIQUE_SYMBOL == (87)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88)
		#define UNIQUE_FUNCTION<%0...%1> %01N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89)
		#define UNIQUE_FUNCTION<%0...%1> %01O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90)
		#define UNIQUE_FUNCTION<%0...%1> %01P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91)
		#define UNIQUE_FUNCTION<%0...%1> %01Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (92)
		#define UNIQUE_FUNCTION<%0...%1> %01R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (92)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (93)
		#define UNIQUE_FUNCTION<%0...%1> %01S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (93)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94)
		#define UNIQUE_FUNCTION<%0...%1> %01T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95)
		#define UNIQUE_FUNCTION<%0...%1> %01U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (103)
	#if UNIQUE_SYMBOL == (95)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (96)
		#define UNIQUE_FUNCTION<%0...%1> %01V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (96)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97)
		#define UNIQUE_FUNCTION<%0...%1> %01W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98)
		#define UNIQUE_FUNCTION<%0...%1> %01X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99)
		#define UNIQUE_FUNCTION<%0...%1> %01Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (100)
		#define UNIQUE_FUNCTION<%0...%1> %01Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101)
		#define UNIQUE_FUNCTION<%0...%1> %01_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (102)
		#define UNIQUE_FUNCTION<%0...%1> %01a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (103)
		#define UNIQUE_FUNCTION<%0...%1> %01b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (111)
	#if UNIQUE_SYMBOL == (103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104)
		#define UNIQUE_FUNCTION<%0...%1> %01c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105)
		#define UNIQUE_FUNCTION<%0...%1> %01d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106)
		#define UNIQUE_FUNCTION<%0...%1> %01e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107)
		#define UNIQUE_FUNCTION<%0...%1> %01f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (108)
		#define UNIQUE_FUNCTION<%0...%1> %01g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (109)
		#define UNIQUE_FUNCTION<%0...%1> %01h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110)
		#define UNIQUE_FUNCTION<%0...%1> %01i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (111)
		#define UNIQUE_FUNCTION<%0...%1> %01j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (119)
	#if UNIQUE_SYMBOL == (111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (112)
		#define UNIQUE_FUNCTION<%0...%1> %01k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (113)
		#define UNIQUE_FUNCTION<%0...%1> %01l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (114)
		#define UNIQUE_FUNCTION<%0...%1> %01m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (115)
		#define UNIQUE_FUNCTION<%0...%1> %01n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116)
		#define UNIQUE_FUNCTION<%0...%1> %01o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (117)
		#define UNIQUE_FUNCTION<%0...%1> %01p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118)
		#define UNIQUE_FUNCTION<%0...%1> %01q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (119)
		#define UNIQUE_FUNCTION<%0...%1> %01r%1
		#endinput
	#endif
#else
	#if UNIQUE_SYMBOL == (119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120)
		#define UNIQUE_FUNCTION<%0...%1> %01s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (121)
		#define UNIQUE_FUNCTION<%0...%1> %01t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122)
		#define UNIQUE_FUNCTION<%0...%1> %01u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123)
		#define UNIQUE_FUNCTION<%0...%1> %01v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (124)
		#define UNIQUE_FUNCTION<%0...%1> %01w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (125)
		#define UNIQUE_FUNCTION<%0...%1> %01x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126)
		#define UNIQUE_FUNCTION<%0...%1> %01y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (127)
		#define UNIQUE_FUNCTION<%0...%1> %01z%1
		#endinput
	#endif
#endif

