static stock const Y_UNIQUE_116032_116095_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_116032_116095
	#undef _inc_y_unique_116032_116095
#endif

#if UNIQUE_SYMBOL < (116039)
	#if UNIQUE_SYMBOL == (116031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116032)
		#define UNIQUE_FUNCTION<%0...%1> %0RK0%1
		#endinput
	#if UNIQUE_SYMBOL == (116032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116033)
		#define UNIQUE_FUNCTION<%0...%1> %0RK1%1
		#endinput
	#if UNIQUE_SYMBOL == (116033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116034)
		#define UNIQUE_FUNCTION<%0...%1> %0RK2%1
		#endinput
	#if UNIQUE_SYMBOL == (116034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116035)
		#define UNIQUE_FUNCTION<%0...%1> %0RK3%1
		#endinput
	#if UNIQUE_SYMBOL == (116035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116036)
		#define UNIQUE_FUNCTION<%0...%1> %0RK4%1
		#endinput
	#if UNIQUE_SYMBOL == (116036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116037)
		#define UNIQUE_FUNCTION<%0...%1> %0RK5%1
		#endinput
	#if UNIQUE_SYMBOL == (116037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116038)
		#define UNIQUE_FUNCTION<%0...%1> %0RK6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116039)
		#define UNIQUE_FUNCTION<%0...%1> %0RK7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (116047)
	#elseif UNIQUE_SYMBOL == (116039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116040)
		#define UNIQUE_FUNCTION<%0...%1> %0RK8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116041)
		#define UNIQUE_FUNCTION<%0...%1> %0RK9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116042)
		#define UNIQUE_FUNCTION<%0...%1> %0RK@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116043)
		#define UNIQUE_FUNCTION<%0...%1> %0RKA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116044)
		#define UNIQUE_FUNCTION<%0...%1> %0RKB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116045)
		#define UNIQUE_FUNCTION<%0...%1> %0RKC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116046)
		#define UNIQUE_FUNCTION<%0...%1> %0RKD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116047)
		#define UNIQUE_FUNCTION<%0...%1> %0RKE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (116055)
	#elseif UNIQUE_SYMBOL == (116047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116048)
		#define UNIQUE_FUNCTION<%0...%1> %0RKF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116049)
		#define UNIQUE_FUNCTION<%0...%1> %0RKG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116050)
		#define UNIQUE_FUNCTION<%0...%1> %0RKH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116051)
		#define UNIQUE_FUNCTION<%0...%1> %0RKI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116052)
		#define UNIQUE_FUNCTION<%0...%1> %0RKJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116053)
		#define UNIQUE_FUNCTION<%0...%1> %0RKK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116054)
		#define UNIQUE_FUNCTION<%0...%1> %0RKL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116055)
		#define UNIQUE_FUNCTION<%0...%1> %0RKM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (116063)
	#elseif UNIQUE_SYMBOL == (116055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116056)
		#define UNIQUE_FUNCTION<%0...%1> %0RKN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116057)
		#define UNIQUE_FUNCTION<%0...%1> %0RKO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116058)
		#define UNIQUE_FUNCTION<%0...%1> %0RKP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116059)
		#define UNIQUE_FUNCTION<%0...%1> %0RKQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116060)
		#define UNIQUE_FUNCTION<%0...%1> %0RKR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116061)
		#define UNIQUE_FUNCTION<%0...%1> %0RKS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116062)
		#define UNIQUE_FUNCTION<%0...%1> %0RKT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116063)
		#define UNIQUE_FUNCTION<%0...%1> %0RKU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (116071)
	#elseif UNIQUE_SYMBOL == (116063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116064)
		#define UNIQUE_FUNCTION<%0...%1> %0RKV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116065)
		#define UNIQUE_FUNCTION<%0...%1> %0RKW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116066)
		#define UNIQUE_FUNCTION<%0...%1> %0RKX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116067)
		#define UNIQUE_FUNCTION<%0...%1> %0RKY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116068)
		#define UNIQUE_FUNCTION<%0...%1> %0RKZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116069)
		#define UNIQUE_FUNCTION<%0...%1> %0RK_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116070)
		#define UNIQUE_FUNCTION<%0...%1> %0RKa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116071)
		#define UNIQUE_FUNCTION<%0...%1> %0RKb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (116079)
	#elseif UNIQUE_SYMBOL == (116071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116072)
		#define UNIQUE_FUNCTION<%0...%1> %0RKc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116073)
		#define UNIQUE_FUNCTION<%0...%1> %0RKd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116074)
		#define UNIQUE_FUNCTION<%0...%1> %0RKe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116075)
		#define UNIQUE_FUNCTION<%0...%1> %0RKf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116076)
		#define UNIQUE_FUNCTION<%0...%1> %0RKg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116077)
		#define UNIQUE_FUNCTION<%0...%1> %0RKh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116078)
		#define UNIQUE_FUNCTION<%0...%1> %0RKi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116079)
		#define UNIQUE_FUNCTION<%0...%1> %0RKj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (116087)
	#elseif UNIQUE_SYMBOL == (116079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116080)
		#define UNIQUE_FUNCTION<%0...%1> %0RKk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116081)
		#define UNIQUE_FUNCTION<%0...%1> %0RKl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116082)
		#define UNIQUE_FUNCTION<%0...%1> %0RKm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116083)
		#define UNIQUE_FUNCTION<%0...%1> %0RKn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116084)
		#define UNIQUE_FUNCTION<%0...%1> %0RKo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116085)
		#define UNIQUE_FUNCTION<%0...%1> %0RKp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116086)
		#define UNIQUE_FUNCTION<%0...%1> %0RKq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116087)
		#define UNIQUE_FUNCTION<%0...%1> %0RKr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (116087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116088)
		#define UNIQUE_FUNCTION<%0...%1> %0RKs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116089)
		#define UNIQUE_FUNCTION<%0...%1> %0RKt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116090)
		#define UNIQUE_FUNCTION<%0...%1> %0RKu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116091)
		#define UNIQUE_FUNCTION<%0...%1> %0RKv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116092)
		#define UNIQUE_FUNCTION<%0...%1> %0RKw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116093)
		#define UNIQUE_FUNCTION<%0...%1> %0RKx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (116093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116094)
		#define UNIQUE_FUNCTION<%0...%1> %0RKy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (116095)
		#define UNIQUE_FUNCTION<%0...%1> %0RKz%1
		#endinput
	#endif
#endif
