static stock const Y_UNIQUE_040384_040447_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_040384_040447
	#undef _inc_y_unique_040384_040447
#endif

#if UNIQUE_SYMBOL < (40391)
	#if UNIQUE_SYMBOL == (40383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40384)
		#define UNIQUE_FUNCTION<%0...%1> %09r0%1
		#endinput
	#if UNIQUE_SYMBOL == (40384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40385)
		#define UNIQUE_FUNCTION<%0...%1> %09r1%1
		#endinput
	#if UNIQUE_SYMBOL == (40385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40386)
		#define UNIQUE_FUNCTION<%0...%1> %09r2%1
		#endinput
	#if UNIQUE_SYMBOL == (40386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40387)
		#define UNIQUE_FUNCTION<%0...%1> %09r3%1
		#endinput
	#if UNIQUE_SYMBOL == (40387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40388)
		#define UNIQUE_FUNCTION<%0...%1> %09r4%1
		#endinput
	#if UNIQUE_SYMBOL == (40388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40389)
		#define UNIQUE_FUNCTION<%0...%1> %09r5%1
		#endinput
	#if UNIQUE_SYMBOL == (40389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40390)
		#define UNIQUE_FUNCTION<%0...%1> %09r6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40391)
		#define UNIQUE_FUNCTION<%0...%1> %09r7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (40399)
	#elseif UNIQUE_SYMBOL == (40391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40392)
		#define UNIQUE_FUNCTION<%0...%1> %09r8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40393)
		#define UNIQUE_FUNCTION<%0...%1> %09r9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40394)
		#define UNIQUE_FUNCTION<%0...%1> %09r@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40395)
		#define UNIQUE_FUNCTION<%0...%1> %09rA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40396)
		#define UNIQUE_FUNCTION<%0...%1> %09rB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40397)
		#define UNIQUE_FUNCTION<%0...%1> %09rC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40398)
		#define UNIQUE_FUNCTION<%0...%1> %09rD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40399)
		#define UNIQUE_FUNCTION<%0...%1> %09rE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (40407)
	#elseif UNIQUE_SYMBOL == (40399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40400)
		#define UNIQUE_FUNCTION<%0...%1> %09rF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40401)
		#define UNIQUE_FUNCTION<%0...%1> %09rG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40402)
		#define UNIQUE_FUNCTION<%0...%1> %09rH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40403)
		#define UNIQUE_FUNCTION<%0...%1> %09rI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40404)
		#define UNIQUE_FUNCTION<%0...%1> %09rJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40405)
		#define UNIQUE_FUNCTION<%0...%1> %09rK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40406)
		#define UNIQUE_FUNCTION<%0...%1> %09rL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40407)
		#define UNIQUE_FUNCTION<%0...%1> %09rM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (40415)
	#elseif UNIQUE_SYMBOL == (40407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40408)
		#define UNIQUE_FUNCTION<%0...%1> %09rN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40409)
		#define UNIQUE_FUNCTION<%0...%1> %09rO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40410)
		#define UNIQUE_FUNCTION<%0...%1> %09rP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40411)
		#define UNIQUE_FUNCTION<%0...%1> %09rQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40412)
		#define UNIQUE_FUNCTION<%0...%1> %09rR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40413)
		#define UNIQUE_FUNCTION<%0...%1> %09rS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40414)
		#define UNIQUE_FUNCTION<%0...%1> %09rT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40415)
		#define UNIQUE_FUNCTION<%0...%1> %09rU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (40423)
	#elseif UNIQUE_SYMBOL == (40415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40416)
		#define UNIQUE_FUNCTION<%0...%1> %09rV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40417)
		#define UNIQUE_FUNCTION<%0...%1> %09rW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40418)
		#define UNIQUE_FUNCTION<%0...%1> %09rX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40419)
		#define UNIQUE_FUNCTION<%0...%1> %09rY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40420)
		#define UNIQUE_FUNCTION<%0...%1> %09rZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40421)
		#define UNIQUE_FUNCTION<%0...%1> %09r_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40422)
		#define UNIQUE_FUNCTION<%0...%1> %09ra%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40423)
		#define UNIQUE_FUNCTION<%0...%1> %09rb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (40431)
	#elseif UNIQUE_SYMBOL == (40423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40424)
		#define UNIQUE_FUNCTION<%0...%1> %09rc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40425)
		#define UNIQUE_FUNCTION<%0...%1> %09rd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40426)
		#define UNIQUE_FUNCTION<%0...%1> %09re%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40427)
		#define UNIQUE_FUNCTION<%0...%1> %09rf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40428)
		#define UNIQUE_FUNCTION<%0...%1> %09rg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40429)
		#define UNIQUE_FUNCTION<%0...%1> %09rh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40430)
		#define UNIQUE_FUNCTION<%0...%1> %09ri%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40431)
		#define UNIQUE_FUNCTION<%0...%1> %09rj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (40439)
	#elseif UNIQUE_SYMBOL == (40431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40432)
		#define UNIQUE_FUNCTION<%0...%1> %09rk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40433)
		#define UNIQUE_FUNCTION<%0...%1> %09rl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40434)
		#define UNIQUE_FUNCTION<%0...%1> %09rm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40435)
		#define UNIQUE_FUNCTION<%0...%1> %09rn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40436)
		#define UNIQUE_FUNCTION<%0...%1> %09ro%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40437)
		#define UNIQUE_FUNCTION<%0...%1> %09rp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40438)
		#define UNIQUE_FUNCTION<%0...%1> %09rq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40439)
		#define UNIQUE_FUNCTION<%0...%1> %09rr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (40439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40440)
		#define UNIQUE_FUNCTION<%0...%1> %09rs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40441)
		#define UNIQUE_FUNCTION<%0...%1> %09rt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40442)
		#define UNIQUE_FUNCTION<%0...%1> %09ru%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40443)
		#define UNIQUE_FUNCTION<%0...%1> %09rv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40444)
		#define UNIQUE_FUNCTION<%0...%1> %09rw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40445)
		#define UNIQUE_FUNCTION<%0...%1> %09rx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (40445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40446)
		#define UNIQUE_FUNCTION<%0...%1> %09ry%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (40447)
		#define UNIQUE_FUNCTION<%0...%1> %09rz%1
		#endinput
	#endif
#endif
