static stock const Y_UNIQUE_242496_242559_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_242496_242559
	#undef _inc_y_unique_242496_242559
#endif

#if UNIQUE_SYMBOL < (242503)
	#if UNIQUE_SYMBOL == (242495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242496)
		#define UNIQUE_FUNCTION<%0...%1> %0vC0%1
		#endinput
	#if UNIQUE_SYMBOL == (242496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242497)
		#define UNIQUE_FUNCTION<%0...%1> %0vC1%1
		#endinput
	#if UNIQUE_SYMBOL == (242497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242498)
		#define UNIQUE_FUNCTION<%0...%1> %0vC2%1
		#endinput
	#if UNIQUE_SYMBOL == (242498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242499)
		#define UNIQUE_FUNCTION<%0...%1> %0vC3%1
		#endinput
	#if UNIQUE_SYMBOL == (242499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242500)
		#define UNIQUE_FUNCTION<%0...%1> %0vC4%1
		#endinput
	#if UNIQUE_SYMBOL == (242500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242501)
		#define UNIQUE_FUNCTION<%0...%1> %0vC5%1
		#endinput
	#if UNIQUE_SYMBOL == (242501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242502)
		#define UNIQUE_FUNCTION<%0...%1> %0vC6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242503)
		#define UNIQUE_FUNCTION<%0...%1> %0vC7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242511)
	#elseif UNIQUE_SYMBOL == (242503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242504)
		#define UNIQUE_FUNCTION<%0...%1> %0vC8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242505)
		#define UNIQUE_FUNCTION<%0...%1> %0vC9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242506)
		#define UNIQUE_FUNCTION<%0...%1> %0vC@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242507)
		#define UNIQUE_FUNCTION<%0...%1> %0vCA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242508)
		#define UNIQUE_FUNCTION<%0...%1> %0vCB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242509)
		#define UNIQUE_FUNCTION<%0...%1> %0vCC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242510)
		#define UNIQUE_FUNCTION<%0...%1> %0vCD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242511)
		#define UNIQUE_FUNCTION<%0...%1> %0vCE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242519)
	#elseif UNIQUE_SYMBOL == (242511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242512)
		#define UNIQUE_FUNCTION<%0...%1> %0vCF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242513)
		#define UNIQUE_FUNCTION<%0...%1> %0vCG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242514)
		#define UNIQUE_FUNCTION<%0...%1> %0vCH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242515)
		#define UNIQUE_FUNCTION<%0...%1> %0vCI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242516)
		#define UNIQUE_FUNCTION<%0...%1> %0vCJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242517)
		#define UNIQUE_FUNCTION<%0...%1> %0vCK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242518)
		#define UNIQUE_FUNCTION<%0...%1> %0vCL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242519)
		#define UNIQUE_FUNCTION<%0...%1> %0vCM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242527)
	#elseif UNIQUE_SYMBOL == (242519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242520)
		#define UNIQUE_FUNCTION<%0...%1> %0vCN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242521)
		#define UNIQUE_FUNCTION<%0...%1> %0vCO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242522)
		#define UNIQUE_FUNCTION<%0...%1> %0vCP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242523)
		#define UNIQUE_FUNCTION<%0...%1> %0vCQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242524)
		#define UNIQUE_FUNCTION<%0...%1> %0vCR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242525)
		#define UNIQUE_FUNCTION<%0...%1> %0vCS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242526)
		#define UNIQUE_FUNCTION<%0...%1> %0vCT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242527)
		#define UNIQUE_FUNCTION<%0...%1> %0vCU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242535)
	#elseif UNIQUE_SYMBOL == (242527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242528)
		#define UNIQUE_FUNCTION<%0...%1> %0vCV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242529)
		#define UNIQUE_FUNCTION<%0...%1> %0vCW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242530)
		#define UNIQUE_FUNCTION<%0...%1> %0vCX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242531)
		#define UNIQUE_FUNCTION<%0...%1> %0vCY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242532)
		#define UNIQUE_FUNCTION<%0...%1> %0vCZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242533)
		#define UNIQUE_FUNCTION<%0...%1> %0vC_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242534)
		#define UNIQUE_FUNCTION<%0...%1> %0vCa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242535)
		#define UNIQUE_FUNCTION<%0...%1> %0vCb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242543)
	#elseif UNIQUE_SYMBOL == (242535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242536)
		#define UNIQUE_FUNCTION<%0...%1> %0vCc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242537)
		#define UNIQUE_FUNCTION<%0...%1> %0vCd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242538)
		#define UNIQUE_FUNCTION<%0...%1> %0vCe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242539)
		#define UNIQUE_FUNCTION<%0...%1> %0vCf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242540)
		#define UNIQUE_FUNCTION<%0...%1> %0vCg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242541)
		#define UNIQUE_FUNCTION<%0...%1> %0vCh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242542)
		#define UNIQUE_FUNCTION<%0...%1> %0vCi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242543)
		#define UNIQUE_FUNCTION<%0...%1> %0vCj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242551)
	#elseif UNIQUE_SYMBOL == (242543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242544)
		#define UNIQUE_FUNCTION<%0...%1> %0vCk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242545)
		#define UNIQUE_FUNCTION<%0...%1> %0vCl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242546)
		#define UNIQUE_FUNCTION<%0...%1> %0vCm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242547)
		#define UNIQUE_FUNCTION<%0...%1> %0vCn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242548)
		#define UNIQUE_FUNCTION<%0...%1> %0vCo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242549)
		#define UNIQUE_FUNCTION<%0...%1> %0vCp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242550)
		#define UNIQUE_FUNCTION<%0...%1> %0vCq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242551)
		#define UNIQUE_FUNCTION<%0...%1> %0vCr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (242551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242552)
		#define UNIQUE_FUNCTION<%0...%1> %0vCs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242553)
		#define UNIQUE_FUNCTION<%0...%1> %0vCt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242554)
		#define UNIQUE_FUNCTION<%0...%1> %0vCu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242555)
		#define UNIQUE_FUNCTION<%0...%1> %0vCv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242556)
		#define UNIQUE_FUNCTION<%0...%1> %0vCw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242557)
		#define UNIQUE_FUNCTION<%0...%1> %0vCx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242558)
		#define UNIQUE_FUNCTION<%0...%1> %0vCy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242559)
		#define UNIQUE_FUNCTION<%0...%1> %0vCz%1
		#endinput
	#endif
#endif
