static stock const Y_UNIQUE_052352_052415_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_052352_052415
	#undef _inc_y_unique_052352_052415
#endif

#if UNIQUE_SYMBOL < (52359)
	#if UNIQUE_SYMBOL == (52351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52352)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm0%1
		#endinput
	#if UNIQUE_SYMBOL == (52352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52353)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm1%1
		#endinput
	#if UNIQUE_SYMBOL == (52353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52354)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm2%1
		#endinput
	#if UNIQUE_SYMBOL == (52354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52355)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm3%1
		#endinput
	#if UNIQUE_SYMBOL == (52355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52356)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm4%1
		#endinput
	#if UNIQUE_SYMBOL == (52356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52357)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm5%1
		#endinput
	#if UNIQUE_SYMBOL == (52357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52358)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52359)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52367)
	#elseif UNIQUE_SYMBOL == (52359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52360)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52361)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52362)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52363)
		#define UNIQUE_FUNCTION<%0...%1> %0BmA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52364)
		#define UNIQUE_FUNCTION<%0...%1> %0BmB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52365)
		#define UNIQUE_FUNCTION<%0...%1> %0BmC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52366)
		#define UNIQUE_FUNCTION<%0...%1> %0BmD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52367)
		#define UNIQUE_FUNCTION<%0...%1> %0BmE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52375)
	#elseif UNIQUE_SYMBOL == (52367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52368)
		#define UNIQUE_FUNCTION<%0...%1> %0BmF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52369)
		#define UNIQUE_FUNCTION<%0...%1> %0BmG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52370)
		#define UNIQUE_FUNCTION<%0...%1> %0BmH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52371)
		#define UNIQUE_FUNCTION<%0...%1> %0BmI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52372)
		#define UNIQUE_FUNCTION<%0...%1> %0BmJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52373)
		#define UNIQUE_FUNCTION<%0...%1> %0BmK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52374)
		#define UNIQUE_FUNCTION<%0...%1> %0BmL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52375)
		#define UNIQUE_FUNCTION<%0...%1> %0BmM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52383)
	#elseif UNIQUE_SYMBOL == (52375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52376)
		#define UNIQUE_FUNCTION<%0...%1> %0BmN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52377)
		#define UNIQUE_FUNCTION<%0...%1> %0BmO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52378)
		#define UNIQUE_FUNCTION<%0...%1> %0BmP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52379)
		#define UNIQUE_FUNCTION<%0...%1> %0BmQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52380)
		#define UNIQUE_FUNCTION<%0...%1> %0BmR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52381)
		#define UNIQUE_FUNCTION<%0...%1> %0BmS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52382)
		#define UNIQUE_FUNCTION<%0...%1> %0BmT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52383)
		#define UNIQUE_FUNCTION<%0...%1> %0BmU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52391)
	#elseif UNIQUE_SYMBOL == (52383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52384)
		#define UNIQUE_FUNCTION<%0...%1> %0BmV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52385)
		#define UNIQUE_FUNCTION<%0...%1> %0BmW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52386)
		#define UNIQUE_FUNCTION<%0...%1> %0BmX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52387)
		#define UNIQUE_FUNCTION<%0...%1> %0BmY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52388)
		#define UNIQUE_FUNCTION<%0...%1> %0BmZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52389)
		#define UNIQUE_FUNCTION<%0...%1> %0Bm_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52390)
		#define UNIQUE_FUNCTION<%0...%1> %0Bma%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52391)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52399)
	#elseif UNIQUE_SYMBOL == (52391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52392)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52393)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52394)
		#define UNIQUE_FUNCTION<%0...%1> %0Bme%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52395)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52396)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52397)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52398)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52399)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52407)
	#elseif UNIQUE_SYMBOL == (52399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52400)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52401)
		#define UNIQUE_FUNCTION<%0...%1> %0Bml%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52402)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52403)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52404)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52405)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52406)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52407)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (52407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52408)
		#define UNIQUE_FUNCTION<%0...%1> %0Bms%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52409)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52410)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52411)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52412)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52413)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52414)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52415)
		#define UNIQUE_FUNCTION<%0...%1> %0Bmz%1
		#endinput
	#endif
#endif
