static stock const Y_UNIQUE_235072_235135_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_235072_235135
	#undef _inc_y_unique_235072_235135
#endif

#if UNIQUE_SYMBOL < (235079)
	#if UNIQUE_SYMBOL == (235071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235072)
		#define UNIQUE_FUNCTION<%0...%1> %0tO0%1
		#endinput
	#if UNIQUE_SYMBOL == (235072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235073)
		#define UNIQUE_FUNCTION<%0...%1> %0tO1%1
		#endinput
	#if UNIQUE_SYMBOL == (235073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235074)
		#define UNIQUE_FUNCTION<%0...%1> %0tO2%1
		#endinput
	#if UNIQUE_SYMBOL == (235074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235075)
		#define UNIQUE_FUNCTION<%0...%1> %0tO3%1
		#endinput
	#if UNIQUE_SYMBOL == (235075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235076)
		#define UNIQUE_FUNCTION<%0...%1> %0tO4%1
		#endinput
	#if UNIQUE_SYMBOL == (235076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235077)
		#define UNIQUE_FUNCTION<%0...%1> %0tO5%1
		#endinput
	#if UNIQUE_SYMBOL == (235077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235078)
		#define UNIQUE_FUNCTION<%0...%1> %0tO6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235079)
		#define UNIQUE_FUNCTION<%0...%1> %0tO7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (235087)
	#elseif UNIQUE_SYMBOL == (235079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235080)
		#define UNIQUE_FUNCTION<%0...%1> %0tO8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235081)
		#define UNIQUE_FUNCTION<%0...%1> %0tO9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235082)
		#define UNIQUE_FUNCTION<%0...%1> %0tO@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235083)
		#define UNIQUE_FUNCTION<%0...%1> %0tOA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235084)
		#define UNIQUE_FUNCTION<%0...%1> %0tOB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235085)
		#define UNIQUE_FUNCTION<%0...%1> %0tOC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235086)
		#define UNIQUE_FUNCTION<%0...%1> %0tOD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235087)
		#define UNIQUE_FUNCTION<%0...%1> %0tOE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (235095)
	#elseif UNIQUE_SYMBOL == (235087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235088)
		#define UNIQUE_FUNCTION<%0...%1> %0tOF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235089)
		#define UNIQUE_FUNCTION<%0...%1> %0tOG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235090)
		#define UNIQUE_FUNCTION<%0...%1> %0tOH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235091)
		#define UNIQUE_FUNCTION<%0...%1> %0tOI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235092)
		#define UNIQUE_FUNCTION<%0...%1> %0tOJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235093)
		#define UNIQUE_FUNCTION<%0...%1> %0tOK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235094)
		#define UNIQUE_FUNCTION<%0...%1> %0tOL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235095)
		#define UNIQUE_FUNCTION<%0...%1> %0tOM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (235103)
	#elseif UNIQUE_SYMBOL == (235095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235096)
		#define UNIQUE_FUNCTION<%0...%1> %0tON%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235097)
		#define UNIQUE_FUNCTION<%0...%1> %0tOO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235098)
		#define UNIQUE_FUNCTION<%0...%1> %0tOP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235099)
		#define UNIQUE_FUNCTION<%0...%1> %0tOQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235100)
		#define UNIQUE_FUNCTION<%0...%1> %0tOR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235101)
		#define UNIQUE_FUNCTION<%0...%1> %0tOS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235102)
		#define UNIQUE_FUNCTION<%0...%1> %0tOT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235103)
		#define UNIQUE_FUNCTION<%0...%1> %0tOU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (235111)
	#elseif UNIQUE_SYMBOL == (235103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235104)
		#define UNIQUE_FUNCTION<%0...%1> %0tOV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235105)
		#define UNIQUE_FUNCTION<%0...%1> %0tOW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235106)
		#define UNIQUE_FUNCTION<%0...%1> %0tOX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235107)
		#define UNIQUE_FUNCTION<%0...%1> %0tOY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235108)
		#define UNIQUE_FUNCTION<%0...%1> %0tOZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235109)
		#define UNIQUE_FUNCTION<%0...%1> %0tO_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235110)
		#define UNIQUE_FUNCTION<%0...%1> %0tOa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235111)
		#define UNIQUE_FUNCTION<%0...%1> %0tOb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (235119)
	#elseif UNIQUE_SYMBOL == (235111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235112)
		#define UNIQUE_FUNCTION<%0...%1> %0tOc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235113)
		#define UNIQUE_FUNCTION<%0...%1> %0tOd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235114)
		#define UNIQUE_FUNCTION<%0...%1> %0tOe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235115)
		#define UNIQUE_FUNCTION<%0...%1> %0tOf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235116)
		#define UNIQUE_FUNCTION<%0...%1> %0tOg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235117)
		#define UNIQUE_FUNCTION<%0...%1> %0tOh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235118)
		#define UNIQUE_FUNCTION<%0...%1> %0tOi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235119)
		#define UNIQUE_FUNCTION<%0...%1> %0tOj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (235127)
	#elseif UNIQUE_SYMBOL == (235119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235120)
		#define UNIQUE_FUNCTION<%0...%1> %0tOk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235121)
		#define UNIQUE_FUNCTION<%0...%1> %0tOl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235122)
		#define UNIQUE_FUNCTION<%0...%1> %0tOm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235123)
		#define UNIQUE_FUNCTION<%0...%1> %0tOn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235124)
		#define UNIQUE_FUNCTION<%0...%1> %0tOo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235125)
		#define UNIQUE_FUNCTION<%0...%1> %0tOp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235126)
		#define UNIQUE_FUNCTION<%0...%1> %0tOq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235127)
		#define UNIQUE_FUNCTION<%0...%1> %0tOr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (235127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235128)
		#define UNIQUE_FUNCTION<%0...%1> %0tOs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235129)
		#define UNIQUE_FUNCTION<%0...%1> %0tOt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235130)
		#define UNIQUE_FUNCTION<%0...%1> %0tOu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235131)
		#define UNIQUE_FUNCTION<%0...%1> %0tOv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235132)
		#define UNIQUE_FUNCTION<%0...%1> %0tOw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235133)
		#define UNIQUE_FUNCTION<%0...%1> %0tOx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (235133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235134)
		#define UNIQUE_FUNCTION<%0...%1> %0tOy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (235135)
		#define UNIQUE_FUNCTION<%0...%1> %0tOz%1
		#endinput
	#endif
#endif
