static stock const Y_UNIQUE_201472_201535_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_201472_201535
	#undef _inc_y_unique_201472_201535
#endif

#if UNIQUE_SYMBOL < (201479)
	#if UNIQUE_SYMBOL == (201471)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201472)
		#define UNIQUE_FUNCTION<%0...%1> %0lB0%1
		#endinput
	#if UNIQUE_SYMBOL == (201472)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201473)
		#define UNIQUE_FUNCTION<%0...%1> %0lB1%1
		#endinput
	#if UNIQUE_SYMBOL == (201473)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201474)
		#define UNIQUE_FUNCTION<%0...%1> %0lB2%1
		#endinput
	#if UNIQUE_SYMBOL == (201474)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201475)
		#define UNIQUE_FUNCTION<%0...%1> %0lB3%1
		#endinput
	#if UNIQUE_SYMBOL == (201475)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201476)
		#define UNIQUE_FUNCTION<%0...%1> %0lB4%1
		#endinput
	#if UNIQUE_SYMBOL == (201476)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201477)
		#define UNIQUE_FUNCTION<%0...%1> %0lB5%1
		#endinput
	#if UNIQUE_SYMBOL == (201477)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201478)
		#define UNIQUE_FUNCTION<%0...%1> %0lB6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201479)
		#define UNIQUE_FUNCTION<%0...%1> %0lB7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201487)
	#elseif UNIQUE_SYMBOL == (201479)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201480)
		#define UNIQUE_FUNCTION<%0...%1> %0lB8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201480)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201481)
		#define UNIQUE_FUNCTION<%0...%1> %0lB9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201481)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201482)
		#define UNIQUE_FUNCTION<%0...%1> %0lB@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201482)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201483)
		#define UNIQUE_FUNCTION<%0...%1> %0lBA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201483)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201484)
		#define UNIQUE_FUNCTION<%0...%1> %0lBB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201484)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201485)
		#define UNIQUE_FUNCTION<%0...%1> %0lBC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201485)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201486)
		#define UNIQUE_FUNCTION<%0...%1> %0lBD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201487)
		#define UNIQUE_FUNCTION<%0...%1> %0lBE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201495)
	#elseif UNIQUE_SYMBOL == (201487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201488)
		#define UNIQUE_FUNCTION<%0...%1> %0lBF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201489)
		#define UNIQUE_FUNCTION<%0...%1> %0lBG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201490)
		#define UNIQUE_FUNCTION<%0...%1> %0lBH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201491)
		#define UNIQUE_FUNCTION<%0...%1> %0lBI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201492)
		#define UNIQUE_FUNCTION<%0...%1> %0lBJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201493)
		#define UNIQUE_FUNCTION<%0...%1> %0lBK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201494)
		#define UNIQUE_FUNCTION<%0...%1> %0lBL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201495)
		#define UNIQUE_FUNCTION<%0...%1> %0lBM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201503)
	#elseif UNIQUE_SYMBOL == (201495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201496)
		#define UNIQUE_FUNCTION<%0...%1> %0lBN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201497)
		#define UNIQUE_FUNCTION<%0...%1> %0lBO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201498)
		#define UNIQUE_FUNCTION<%0...%1> %0lBP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201499)
		#define UNIQUE_FUNCTION<%0...%1> %0lBQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201500)
		#define UNIQUE_FUNCTION<%0...%1> %0lBR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201501)
		#define UNIQUE_FUNCTION<%0...%1> %0lBS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201502)
		#define UNIQUE_FUNCTION<%0...%1> %0lBT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201503)
		#define UNIQUE_FUNCTION<%0...%1> %0lBU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201511)
	#elseif UNIQUE_SYMBOL == (201503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201504)
		#define UNIQUE_FUNCTION<%0...%1> %0lBV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201505)
		#define UNIQUE_FUNCTION<%0...%1> %0lBW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201506)
		#define UNIQUE_FUNCTION<%0...%1> %0lBX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201507)
		#define UNIQUE_FUNCTION<%0...%1> %0lBY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201508)
		#define UNIQUE_FUNCTION<%0...%1> %0lBZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201509)
		#define UNIQUE_FUNCTION<%0...%1> %0lB_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201510)
		#define UNIQUE_FUNCTION<%0...%1> %0lBa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201511)
		#define UNIQUE_FUNCTION<%0...%1> %0lBb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201519)
	#elseif UNIQUE_SYMBOL == (201511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201512)
		#define UNIQUE_FUNCTION<%0...%1> %0lBc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201513)
		#define UNIQUE_FUNCTION<%0...%1> %0lBd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201514)
		#define UNIQUE_FUNCTION<%0...%1> %0lBe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201515)
		#define UNIQUE_FUNCTION<%0...%1> %0lBf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201516)
		#define UNIQUE_FUNCTION<%0...%1> %0lBg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201517)
		#define UNIQUE_FUNCTION<%0...%1> %0lBh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201518)
		#define UNIQUE_FUNCTION<%0...%1> %0lBi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201519)
		#define UNIQUE_FUNCTION<%0...%1> %0lBj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201527)
	#elseif UNIQUE_SYMBOL == (201519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201520)
		#define UNIQUE_FUNCTION<%0...%1> %0lBk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201521)
		#define UNIQUE_FUNCTION<%0...%1> %0lBl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201522)
		#define UNIQUE_FUNCTION<%0...%1> %0lBm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201523)
		#define UNIQUE_FUNCTION<%0...%1> %0lBn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201524)
		#define UNIQUE_FUNCTION<%0...%1> %0lBo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201525)
		#define UNIQUE_FUNCTION<%0...%1> %0lBp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201526)
		#define UNIQUE_FUNCTION<%0...%1> %0lBq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201527)
		#define UNIQUE_FUNCTION<%0...%1> %0lBr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (201527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201528)
		#define UNIQUE_FUNCTION<%0...%1> %0lBs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201529)
		#define UNIQUE_FUNCTION<%0...%1> %0lBt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201530)
		#define UNIQUE_FUNCTION<%0...%1> %0lBu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201531)
		#define UNIQUE_FUNCTION<%0...%1> %0lBv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201532)
		#define UNIQUE_FUNCTION<%0...%1> %0lBw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201533)
		#define UNIQUE_FUNCTION<%0...%1> %0lBx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201534)
		#define UNIQUE_FUNCTION<%0...%1> %0lBy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201535)
		#define UNIQUE_FUNCTION<%0...%1> %0lBz%1
		#endinput
	#endif
#endif
