static stock const Y_UNIQUE_064192_064255_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_064192_064255
	#undef _inc_y_unique_064192_064255
#endif

#if UNIQUE_SYMBOL < (64199)
	#if UNIQUE_SYMBOL == (64191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64192)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef0%1
		#endinput
	#if UNIQUE_SYMBOL == (64192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64193)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef1%1
		#endinput
	#if UNIQUE_SYMBOL == (64193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64194)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef2%1
		#endinput
	#if UNIQUE_SYMBOL == (64194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64195)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef3%1
		#endinput
	#if UNIQUE_SYMBOL == (64195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64196)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef4%1
		#endinput
	#if UNIQUE_SYMBOL == (64196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64197)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef5%1
		#endinput
	#if UNIQUE_SYMBOL == (64197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64198)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64199)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (64207)
	#elseif UNIQUE_SYMBOL == (64199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64200)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64201)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64202)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64203)
		#define UNIQUE_FUNCTION<%0...%1> %0EfA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64204)
		#define UNIQUE_FUNCTION<%0...%1> %0EfB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64205)
		#define UNIQUE_FUNCTION<%0...%1> %0EfC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64206)
		#define UNIQUE_FUNCTION<%0...%1> %0EfD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64207)
		#define UNIQUE_FUNCTION<%0...%1> %0EfE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (64215)
	#elseif UNIQUE_SYMBOL == (64207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64208)
		#define UNIQUE_FUNCTION<%0...%1> %0EfF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64209)
		#define UNIQUE_FUNCTION<%0...%1> %0EfG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64210)
		#define UNIQUE_FUNCTION<%0...%1> %0EfH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64211)
		#define UNIQUE_FUNCTION<%0...%1> %0EfI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64212)
		#define UNIQUE_FUNCTION<%0...%1> %0EfJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64213)
		#define UNIQUE_FUNCTION<%0...%1> %0EfK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64214)
		#define UNIQUE_FUNCTION<%0...%1> %0EfL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64215)
		#define UNIQUE_FUNCTION<%0...%1> %0EfM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (64223)
	#elseif UNIQUE_SYMBOL == (64215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64216)
		#define UNIQUE_FUNCTION<%0...%1> %0EfN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64217)
		#define UNIQUE_FUNCTION<%0...%1> %0EfO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64218)
		#define UNIQUE_FUNCTION<%0...%1> %0EfP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64219)
		#define UNIQUE_FUNCTION<%0...%1> %0EfQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64220)
		#define UNIQUE_FUNCTION<%0...%1> %0EfR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64221)
		#define UNIQUE_FUNCTION<%0...%1> %0EfS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64222)
		#define UNIQUE_FUNCTION<%0...%1> %0EfT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64223)
		#define UNIQUE_FUNCTION<%0...%1> %0EfU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (64231)
	#elseif UNIQUE_SYMBOL == (64223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64224)
		#define UNIQUE_FUNCTION<%0...%1> %0EfV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64225)
		#define UNIQUE_FUNCTION<%0...%1> %0EfW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64226)
		#define UNIQUE_FUNCTION<%0...%1> %0EfX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64227)
		#define UNIQUE_FUNCTION<%0...%1> %0EfY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64228)
		#define UNIQUE_FUNCTION<%0...%1> %0EfZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64229)
		#define UNIQUE_FUNCTION<%0...%1> %0Ef_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64230)
		#define UNIQUE_FUNCTION<%0...%1> %0Efa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64231)
		#define UNIQUE_FUNCTION<%0...%1> %0Efb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (64239)
	#elseif UNIQUE_SYMBOL == (64231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64232)
		#define UNIQUE_FUNCTION<%0...%1> %0Efc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64233)
		#define UNIQUE_FUNCTION<%0...%1> %0Efd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64234)
		#define UNIQUE_FUNCTION<%0...%1> %0Efe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64235)
		#define UNIQUE_FUNCTION<%0...%1> %0Eff%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64236)
		#define UNIQUE_FUNCTION<%0...%1> %0Efg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64237)
		#define UNIQUE_FUNCTION<%0...%1> %0Efh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64238)
		#define UNIQUE_FUNCTION<%0...%1> %0Efi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64239)
		#define UNIQUE_FUNCTION<%0...%1> %0Efj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (64247)
	#elseif UNIQUE_SYMBOL == (64239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64240)
		#define UNIQUE_FUNCTION<%0...%1> %0Efk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64241)
		#define UNIQUE_FUNCTION<%0...%1> %0Efl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64242)
		#define UNIQUE_FUNCTION<%0...%1> %0Efm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64243)
		#define UNIQUE_FUNCTION<%0...%1> %0Efn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64244)
		#define UNIQUE_FUNCTION<%0...%1> %0Efo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64245)
		#define UNIQUE_FUNCTION<%0...%1> %0Efp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64246)
		#define UNIQUE_FUNCTION<%0...%1> %0Efq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64247)
		#define UNIQUE_FUNCTION<%0...%1> %0Efr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (64247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64248)
		#define UNIQUE_FUNCTION<%0...%1> %0Efs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64249)
		#define UNIQUE_FUNCTION<%0...%1> %0Eft%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64250)
		#define UNIQUE_FUNCTION<%0...%1> %0Efu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64251)
		#define UNIQUE_FUNCTION<%0...%1> %0Efv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64252)
		#define UNIQUE_FUNCTION<%0...%1> %0Efw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64253)
		#define UNIQUE_FUNCTION<%0...%1> %0Efx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (64253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64254)
		#define UNIQUE_FUNCTION<%0...%1> %0Efy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (64255)
		#define UNIQUE_FUNCTION<%0...%1> %0Efz%1
		#endinput
	#endif
#endif
