static stock const Y_UNIQUE_007488_007551_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_007488_007551
	#undef _inc_y_unique_007488_007551
#endif

#if UNIQUE_SYMBOL < (7495)
	#if UNIQUE_SYMBOL == (7487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7488)
		#define UNIQUE_FUNCTION<%0...%1> %01p0%1
		#endinput
	#if UNIQUE_SYMBOL == (7488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7489)
		#define UNIQUE_FUNCTION<%0...%1> %01p1%1
		#endinput
	#if UNIQUE_SYMBOL == (7489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7490)
		#define UNIQUE_FUNCTION<%0...%1> %01p2%1
		#endinput
	#if UNIQUE_SYMBOL == (7490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7491)
		#define UNIQUE_FUNCTION<%0...%1> %01p3%1
		#endinput
	#if UNIQUE_SYMBOL == (7491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7492)
		#define UNIQUE_FUNCTION<%0...%1> %01p4%1
		#endinput
	#if UNIQUE_SYMBOL == (7492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7493)
		#define UNIQUE_FUNCTION<%0...%1> %01p5%1
		#endinput
	#if UNIQUE_SYMBOL == (7493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7494)
		#define UNIQUE_FUNCTION<%0...%1> %01p6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7495)
		#define UNIQUE_FUNCTION<%0...%1> %01p7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7503)
	#elseif UNIQUE_SYMBOL == (7495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7496)
		#define UNIQUE_FUNCTION<%0...%1> %01p8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7497)
		#define UNIQUE_FUNCTION<%0...%1> %01p9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7498)
		#define UNIQUE_FUNCTION<%0...%1> %01p@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7499)
		#define UNIQUE_FUNCTION<%0...%1> %01pA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7500)
		#define UNIQUE_FUNCTION<%0...%1> %01pB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7501)
		#define UNIQUE_FUNCTION<%0...%1> %01pC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7502)
		#define UNIQUE_FUNCTION<%0...%1> %01pD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7503)
		#define UNIQUE_FUNCTION<%0...%1> %01pE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7511)
	#elseif UNIQUE_SYMBOL == (7503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7504)
		#define UNIQUE_FUNCTION<%0...%1> %01pF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7505)
		#define UNIQUE_FUNCTION<%0...%1> %01pG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7506)
		#define UNIQUE_FUNCTION<%0...%1> %01pH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7507)
		#define UNIQUE_FUNCTION<%0...%1> %01pI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7508)
		#define UNIQUE_FUNCTION<%0...%1> %01pJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7509)
		#define UNIQUE_FUNCTION<%0...%1> %01pK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7510)
		#define UNIQUE_FUNCTION<%0...%1> %01pL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7511)
		#define UNIQUE_FUNCTION<%0...%1> %01pM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7519)
	#elseif UNIQUE_SYMBOL == (7511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7512)
		#define UNIQUE_FUNCTION<%0...%1> %01pN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7513)
		#define UNIQUE_FUNCTION<%0...%1> %01pO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7514)
		#define UNIQUE_FUNCTION<%0...%1> %01pP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7515)
		#define UNIQUE_FUNCTION<%0...%1> %01pQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7516)
		#define UNIQUE_FUNCTION<%0...%1> %01pR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7517)
		#define UNIQUE_FUNCTION<%0...%1> %01pS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7518)
		#define UNIQUE_FUNCTION<%0...%1> %01pT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7519)
		#define UNIQUE_FUNCTION<%0...%1> %01pU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7527)
	#elseif UNIQUE_SYMBOL == (7519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7520)
		#define UNIQUE_FUNCTION<%0...%1> %01pV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7521)
		#define UNIQUE_FUNCTION<%0...%1> %01pW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7522)
		#define UNIQUE_FUNCTION<%0...%1> %01pX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7523)
		#define UNIQUE_FUNCTION<%0...%1> %01pY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7524)
		#define UNIQUE_FUNCTION<%0...%1> %01pZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7525)
		#define UNIQUE_FUNCTION<%0...%1> %01p_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7526)
		#define UNIQUE_FUNCTION<%0...%1> %01pa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7527)
		#define UNIQUE_FUNCTION<%0...%1> %01pb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7535)
	#elseif UNIQUE_SYMBOL == (7527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7528)
		#define UNIQUE_FUNCTION<%0...%1> %01pc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7529)
		#define UNIQUE_FUNCTION<%0...%1> %01pd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7530)
		#define UNIQUE_FUNCTION<%0...%1> %01pe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7531)
		#define UNIQUE_FUNCTION<%0...%1> %01pf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7532)
		#define UNIQUE_FUNCTION<%0...%1> %01pg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7533)
		#define UNIQUE_FUNCTION<%0...%1> %01ph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7534)
		#define UNIQUE_FUNCTION<%0...%1> %01pi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7535)
		#define UNIQUE_FUNCTION<%0...%1> %01pj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7543)
	#elseif UNIQUE_SYMBOL == (7535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7536)
		#define UNIQUE_FUNCTION<%0...%1> %01pk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7537)
		#define UNIQUE_FUNCTION<%0...%1> %01pl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7538)
		#define UNIQUE_FUNCTION<%0...%1> %01pm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7539)
		#define UNIQUE_FUNCTION<%0...%1> %01pn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7540)
		#define UNIQUE_FUNCTION<%0...%1> %01po%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7541)
		#define UNIQUE_FUNCTION<%0...%1> %01pp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7542)
		#define UNIQUE_FUNCTION<%0...%1> %01pq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7543)
		#define UNIQUE_FUNCTION<%0...%1> %01pr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (7543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7544)
		#define UNIQUE_FUNCTION<%0...%1> %01ps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7545)
		#define UNIQUE_FUNCTION<%0...%1> %01pt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7546)
		#define UNIQUE_FUNCTION<%0...%1> %01pu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7547)
		#define UNIQUE_FUNCTION<%0...%1> %01pv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7548)
		#define UNIQUE_FUNCTION<%0...%1> %01pw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7549)
		#define UNIQUE_FUNCTION<%0...%1> %01px%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7550)
		#define UNIQUE_FUNCTION<%0...%1> %01py%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7551)
		#define UNIQUE_FUNCTION<%0...%1> %01pz%1
		#endinput
	#endif
#endif
