static stock const Y_UNIQUE_257600_257663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_257600_257663
	#undef _inc_y_unique_257600_257663
#endif

#if UNIQUE_SYMBOL < (257607)
	#if UNIQUE_SYMBOL == (257599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257600)
		#define UNIQUE_FUNCTION<%0...%1> %0yt0%1
		#endinput
	#if UNIQUE_SYMBOL == (257600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257601)
		#define UNIQUE_FUNCTION<%0...%1> %0yt1%1
		#endinput
	#if UNIQUE_SYMBOL == (257601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257602)
		#define UNIQUE_FUNCTION<%0...%1> %0yt2%1
		#endinput
	#if UNIQUE_SYMBOL == (257602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257603)
		#define UNIQUE_FUNCTION<%0...%1> %0yt3%1
		#endinput
	#if UNIQUE_SYMBOL == (257603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257604)
		#define UNIQUE_FUNCTION<%0...%1> %0yt4%1
		#endinput
	#if UNIQUE_SYMBOL == (257604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257605)
		#define UNIQUE_FUNCTION<%0...%1> %0yt5%1
		#endinput
	#if UNIQUE_SYMBOL == (257605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257606)
		#define UNIQUE_FUNCTION<%0...%1> %0yt6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257607)
		#define UNIQUE_FUNCTION<%0...%1> %0yt7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (257615)
	#elseif UNIQUE_SYMBOL == (257607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257608)
		#define UNIQUE_FUNCTION<%0...%1> %0yt8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257609)
		#define UNIQUE_FUNCTION<%0...%1> %0yt9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257610)
		#define UNIQUE_FUNCTION<%0...%1> %0yt@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257611)
		#define UNIQUE_FUNCTION<%0...%1> %0ytA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257612)
		#define UNIQUE_FUNCTION<%0...%1> %0ytB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257613)
		#define UNIQUE_FUNCTION<%0...%1> %0ytC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257614)
		#define UNIQUE_FUNCTION<%0...%1> %0ytD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257615)
		#define UNIQUE_FUNCTION<%0...%1> %0ytE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (257623)
	#elseif UNIQUE_SYMBOL == (257615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257616)
		#define UNIQUE_FUNCTION<%0...%1> %0ytF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257617)
		#define UNIQUE_FUNCTION<%0...%1> %0ytG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257618)
		#define UNIQUE_FUNCTION<%0...%1> %0ytH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257619)
		#define UNIQUE_FUNCTION<%0...%1> %0ytI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257620)
		#define UNIQUE_FUNCTION<%0...%1> %0ytJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257621)
		#define UNIQUE_FUNCTION<%0...%1> %0ytK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257622)
		#define UNIQUE_FUNCTION<%0...%1> %0ytL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257623)
		#define UNIQUE_FUNCTION<%0...%1> %0ytM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (257631)
	#elseif UNIQUE_SYMBOL == (257623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257624)
		#define UNIQUE_FUNCTION<%0...%1> %0ytN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257625)
		#define UNIQUE_FUNCTION<%0...%1> %0ytO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257626)
		#define UNIQUE_FUNCTION<%0...%1> %0ytP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257627)
		#define UNIQUE_FUNCTION<%0...%1> %0ytQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257628)
		#define UNIQUE_FUNCTION<%0...%1> %0ytR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257629)
		#define UNIQUE_FUNCTION<%0...%1> %0ytS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257630)
		#define UNIQUE_FUNCTION<%0...%1> %0ytT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257631)
		#define UNIQUE_FUNCTION<%0...%1> %0ytU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (257639)
	#elseif UNIQUE_SYMBOL == (257631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257632)
		#define UNIQUE_FUNCTION<%0...%1> %0ytV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257633)
		#define UNIQUE_FUNCTION<%0...%1> %0ytW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257634)
		#define UNIQUE_FUNCTION<%0...%1> %0ytX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257635)
		#define UNIQUE_FUNCTION<%0...%1> %0ytY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257636)
		#define UNIQUE_FUNCTION<%0...%1> %0ytZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257637)
		#define UNIQUE_FUNCTION<%0...%1> %0yt_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257638)
		#define UNIQUE_FUNCTION<%0...%1> %0yta%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257639)
		#define UNIQUE_FUNCTION<%0...%1> %0ytb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (257647)
	#elseif UNIQUE_SYMBOL == (257639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257640)
		#define UNIQUE_FUNCTION<%0...%1> %0ytc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257641)
		#define UNIQUE_FUNCTION<%0...%1> %0ytd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257642)
		#define UNIQUE_FUNCTION<%0...%1> %0yte%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257643)
		#define UNIQUE_FUNCTION<%0...%1> %0ytf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257644)
		#define UNIQUE_FUNCTION<%0...%1> %0ytg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257645)
		#define UNIQUE_FUNCTION<%0...%1> %0yth%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257646)
		#define UNIQUE_FUNCTION<%0...%1> %0yti%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257647)
		#define UNIQUE_FUNCTION<%0...%1> %0ytj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (257655)
	#elseif UNIQUE_SYMBOL == (257647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257648)
		#define UNIQUE_FUNCTION<%0...%1> %0ytk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257649)
		#define UNIQUE_FUNCTION<%0...%1> %0ytl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257650)
		#define UNIQUE_FUNCTION<%0...%1> %0ytm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257651)
		#define UNIQUE_FUNCTION<%0...%1> %0ytn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257652)
		#define UNIQUE_FUNCTION<%0...%1> %0yto%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257653)
		#define UNIQUE_FUNCTION<%0...%1> %0ytp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257654)
		#define UNIQUE_FUNCTION<%0...%1> %0ytq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257655)
		#define UNIQUE_FUNCTION<%0...%1> %0ytr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (257655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257656)
		#define UNIQUE_FUNCTION<%0...%1> %0yts%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257657)
		#define UNIQUE_FUNCTION<%0...%1> %0ytt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257658)
		#define UNIQUE_FUNCTION<%0...%1> %0ytu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257659)
		#define UNIQUE_FUNCTION<%0...%1> %0ytv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257660)
		#define UNIQUE_FUNCTION<%0...%1> %0ytw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257661)
		#define UNIQUE_FUNCTION<%0...%1> %0ytx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (257661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257662)
		#define UNIQUE_FUNCTION<%0...%1> %0yty%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (257663)
		#define UNIQUE_FUNCTION<%0...%1> %0ytz%1
		#endinput
	#endif
#endif
