static stock const Y_UNIQUE_033600_033663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_033600_033663
	#undef _inc_y_unique_033600_033663
#endif

#if UNIQUE_SYMBOL < (33607)
	#if UNIQUE_SYMBOL == (33599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33600)
		#define UNIQUE_FUNCTION<%0...%1> %08C0%1
		#endinput
	#if UNIQUE_SYMBOL == (33600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33601)
		#define UNIQUE_FUNCTION<%0...%1> %08C1%1
		#endinput
	#if UNIQUE_SYMBOL == (33601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33602)
		#define UNIQUE_FUNCTION<%0...%1> %08C2%1
		#endinput
	#if UNIQUE_SYMBOL == (33602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33603)
		#define UNIQUE_FUNCTION<%0...%1> %08C3%1
		#endinput
	#if UNIQUE_SYMBOL == (33603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33604)
		#define UNIQUE_FUNCTION<%0...%1> %08C4%1
		#endinput
	#if UNIQUE_SYMBOL == (33604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33605)
		#define UNIQUE_FUNCTION<%0...%1> %08C5%1
		#endinput
	#if UNIQUE_SYMBOL == (33605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33606)
		#define UNIQUE_FUNCTION<%0...%1> %08C6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33607)
		#define UNIQUE_FUNCTION<%0...%1> %08C7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33615)
	#elseif UNIQUE_SYMBOL == (33607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33608)
		#define UNIQUE_FUNCTION<%0...%1> %08C8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33609)
		#define UNIQUE_FUNCTION<%0...%1> %08C9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33610)
		#define UNIQUE_FUNCTION<%0...%1> %08C@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33611)
		#define UNIQUE_FUNCTION<%0...%1> %08CA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33612)
		#define UNIQUE_FUNCTION<%0...%1> %08CB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33613)
		#define UNIQUE_FUNCTION<%0...%1> %08CC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33614)
		#define UNIQUE_FUNCTION<%0...%1> %08CD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33615)
		#define UNIQUE_FUNCTION<%0...%1> %08CE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33623)
	#elseif UNIQUE_SYMBOL == (33615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33616)
		#define UNIQUE_FUNCTION<%0...%1> %08CF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33617)
		#define UNIQUE_FUNCTION<%0...%1> %08CG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33618)
		#define UNIQUE_FUNCTION<%0...%1> %08CH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33619)
		#define UNIQUE_FUNCTION<%0...%1> %08CI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33620)
		#define UNIQUE_FUNCTION<%0...%1> %08CJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33621)
		#define UNIQUE_FUNCTION<%0...%1> %08CK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33622)
		#define UNIQUE_FUNCTION<%0...%1> %08CL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33623)
		#define UNIQUE_FUNCTION<%0...%1> %08CM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33631)
	#elseif UNIQUE_SYMBOL == (33623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33624)
		#define UNIQUE_FUNCTION<%0...%1> %08CN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33625)
		#define UNIQUE_FUNCTION<%0...%1> %08CO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33626)
		#define UNIQUE_FUNCTION<%0...%1> %08CP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33627)
		#define UNIQUE_FUNCTION<%0...%1> %08CQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33628)
		#define UNIQUE_FUNCTION<%0...%1> %08CR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33629)
		#define UNIQUE_FUNCTION<%0...%1> %08CS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33630)
		#define UNIQUE_FUNCTION<%0...%1> %08CT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33631)
		#define UNIQUE_FUNCTION<%0...%1> %08CU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33639)
	#elseif UNIQUE_SYMBOL == (33631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33632)
		#define UNIQUE_FUNCTION<%0...%1> %08CV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33633)
		#define UNIQUE_FUNCTION<%0...%1> %08CW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33634)
		#define UNIQUE_FUNCTION<%0...%1> %08CX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33635)
		#define UNIQUE_FUNCTION<%0...%1> %08CY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33636)
		#define UNIQUE_FUNCTION<%0...%1> %08CZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33637)
		#define UNIQUE_FUNCTION<%0...%1> %08C_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33638)
		#define UNIQUE_FUNCTION<%0...%1> %08Ca%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33639)
		#define UNIQUE_FUNCTION<%0...%1> %08Cb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33647)
	#elseif UNIQUE_SYMBOL == (33639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33640)
		#define UNIQUE_FUNCTION<%0...%1> %08Cc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33641)
		#define UNIQUE_FUNCTION<%0...%1> %08Cd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33642)
		#define UNIQUE_FUNCTION<%0...%1> %08Ce%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33643)
		#define UNIQUE_FUNCTION<%0...%1> %08Cf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33644)
		#define UNIQUE_FUNCTION<%0...%1> %08Cg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33645)
		#define UNIQUE_FUNCTION<%0...%1> %08Ch%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33646)
		#define UNIQUE_FUNCTION<%0...%1> %08Ci%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33647)
		#define UNIQUE_FUNCTION<%0...%1> %08Cj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33655)
	#elseif UNIQUE_SYMBOL == (33647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33648)
		#define UNIQUE_FUNCTION<%0...%1> %08Ck%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33649)
		#define UNIQUE_FUNCTION<%0...%1> %08Cl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33650)
		#define UNIQUE_FUNCTION<%0...%1> %08Cm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33651)
		#define UNIQUE_FUNCTION<%0...%1> %08Cn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33652)
		#define UNIQUE_FUNCTION<%0...%1> %08Co%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33653)
		#define UNIQUE_FUNCTION<%0...%1> %08Cp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33654)
		#define UNIQUE_FUNCTION<%0...%1> %08Cq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33655)
		#define UNIQUE_FUNCTION<%0...%1> %08Cr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (33655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33656)
		#define UNIQUE_FUNCTION<%0...%1> %08Cs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33657)
		#define UNIQUE_FUNCTION<%0...%1> %08Ct%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33658)
		#define UNIQUE_FUNCTION<%0...%1> %08Cu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33659)
		#define UNIQUE_FUNCTION<%0...%1> %08Cv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33660)
		#define UNIQUE_FUNCTION<%0...%1> %08Cw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33661)
		#define UNIQUE_FUNCTION<%0...%1> %08Cx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33662)
		#define UNIQUE_FUNCTION<%0...%1> %08Cy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33663)
		#define UNIQUE_FUNCTION<%0...%1> %08Cz%1
		#endinput
	#endif
#endif
