static stock const Y_UNIQUE_034304_034367_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_034304_034367
	#undef _inc_y_unique_034304_034367
#endif

#if UNIQUE_SYMBOL < (34311)
	#if UNIQUE_SYMBOL == (34303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34304)
		#define UNIQUE_FUNCTION<%0...%1> %08N0%1
		#endinput
	#if UNIQUE_SYMBOL == (34304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34305)
		#define UNIQUE_FUNCTION<%0...%1> %08N1%1
		#endinput
	#if UNIQUE_SYMBOL == (34305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34306)
		#define UNIQUE_FUNCTION<%0...%1> %08N2%1
		#endinput
	#if UNIQUE_SYMBOL == (34306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34307)
		#define UNIQUE_FUNCTION<%0...%1> %08N3%1
		#endinput
	#if UNIQUE_SYMBOL == (34307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34308)
		#define UNIQUE_FUNCTION<%0...%1> %08N4%1
		#endinput
	#if UNIQUE_SYMBOL == (34308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34309)
		#define UNIQUE_FUNCTION<%0...%1> %08N5%1
		#endinput
	#if UNIQUE_SYMBOL == (34309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34310)
		#define UNIQUE_FUNCTION<%0...%1> %08N6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34311)
		#define UNIQUE_FUNCTION<%0...%1> %08N7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34319)
	#elseif UNIQUE_SYMBOL == (34311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34312)
		#define UNIQUE_FUNCTION<%0...%1> %08N8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34313)
		#define UNIQUE_FUNCTION<%0...%1> %08N9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34314)
		#define UNIQUE_FUNCTION<%0...%1> %08N@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34315)
		#define UNIQUE_FUNCTION<%0...%1> %08NA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34316)
		#define UNIQUE_FUNCTION<%0...%1> %08NB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34317)
		#define UNIQUE_FUNCTION<%0...%1> %08NC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34318)
		#define UNIQUE_FUNCTION<%0...%1> %08ND%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34319)
		#define UNIQUE_FUNCTION<%0...%1> %08NE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34327)
	#elseif UNIQUE_SYMBOL == (34319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34320)
		#define UNIQUE_FUNCTION<%0...%1> %08NF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34321)
		#define UNIQUE_FUNCTION<%0...%1> %08NG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34322)
		#define UNIQUE_FUNCTION<%0...%1> %08NH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34323)
		#define UNIQUE_FUNCTION<%0...%1> %08NI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34324)
		#define UNIQUE_FUNCTION<%0...%1> %08NJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34325)
		#define UNIQUE_FUNCTION<%0...%1> %08NK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34326)
		#define UNIQUE_FUNCTION<%0...%1> %08NL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34327)
		#define UNIQUE_FUNCTION<%0...%1> %08NM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34335)
	#elseif UNIQUE_SYMBOL == (34327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34328)
		#define UNIQUE_FUNCTION<%0...%1> %08NN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34329)
		#define UNIQUE_FUNCTION<%0...%1> %08NO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34330)
		#define UNIQUE_FUNCTION<%0...%1> %08NP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34331)
		#define UNIQUE_FUNCTION<%0...%1> %08NQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34332)
		#define UNIQUE_FUNCTION<%0...%1> %08NR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34333)
		#define UNIQUE_FUNCTION<%0...%1> %08NS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34334)
		#define UNIQUE_FUNCTION<%0...%1> %08NT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34335)
		#define UNIQUE_FUNCTION<%0...%1> %08NU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34343)
	#elseif UNIQUE_SYMBOL == (34335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34336)
		#define UNIQUE_FUNCTION<%0...%1> %08NV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34337)
		#define UNIQUE_FUNCTION<%0...%1> %08NW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34338)
		#define UNIQUE_FUNCTION<%0...%1> %08NX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34339)
		#define UNIQUE_FUNCTION<%0...%1> %08NY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34340)
		#define UNIQUE_FUNCTION<%0...%1> %08NZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34341)
		#define UNIQUE_FUNCTION<%0...%1> %08N_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34342)
		#define UNIQUE_FUNCTION<%0...%1> %08Na%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34343)
		#define UNIQUE_FUNCTION<%0...%1> %08Nb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34351)
	#elseif UNIQUE_SYMBOL == (34343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34344)
		#define UNIQUE_FUNCTION<%0...%1> %08Nc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34345)
		#define UNIQUE_FUNCTION<%0...%1> %08Nd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34346)
		#define UNIQUE_FUNCTION<%0...%1> %08Ne%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34347)
		#define UNIQUE_FUNCTION<%0...%1> %08Nf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34348)
		#define UNIQUE_FUNCTION<%0...%1> %08Ng%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34349)
		#define UNIQUE_FUNCTION<%0...%1> %08Nh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34350)
		#define UNIQUE_FUNCTION<%0...%1> %08Ni%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34351)
		#define UNIQUE_FUNCTION<%0...%1> %08Nj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34359)
	#elseif UNIQUE_SYMBOL == (34351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34352)
		#define UNIQUE_FUNCTION<%0...%1> %08Nk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34353)
		#define UNIQUE_FUNCTION<%0...%1> %08Nl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34354)
		#define UNIQUE_FUNCTION<%0...%1> %08Nm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34355)
		#define UNIQUE_FUNCTION<%0...%1> %08Nn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34356)
		#define UNIQUE_FUNCTION<%0...%1> %08No%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34357)
		#define UNIQUE_FUNCTION<%0...%1> %08Np%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34358)
		#define UNIQUE_FUNCTION<%0...%1> %08Nq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34359)
		#define UNIQUE_FUNCTION<%0...%1> %08Nr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (34359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34360)
		#define UNIQUE_FUNCTION<%0...%1> %08Ns%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34361)
		#define UNIQUE_FUNCTION<%0...%1> %08Nt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34362)
		#define UNIQUE_FUNCTION<%0...%1> %08Nu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34363)
		#define UNIQUE_FUNCTION<%0...%1> %08Nv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34364)
		#define UNIQUE_FUNCTION<%0...%1> %08Nw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34365)
		#define UNIQUE_FUNCTION<%0...%1> %08Nx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34366)
		#define UNIQUE_FUNCTION<%0...%1> %08Ny%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34367)
		#define UNIQUE_FUNCTION<%0...%1> %08Nz%1
		#endinput
	#endif
#endif
