static stock const Y_UNIQUE_141824_141887_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_141824_141887
	#undef _inc_y_unique_141824_141887
#endif

#if UNIQUE_SYMBOL < (141831)
	#if UNIQUE_SYMBOL == (141823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141824)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc0%1
		#endinput
	#if UNIQUE_SYMBOL == (141824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141825)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc1%1
		#endinput
	#if UNIQUE_SYMBOL == (141825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141826)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc2%1
		#endinput
	#if UNIQUE_SYMBOL == (141826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141827)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc3%1
		#endinput
	#if UNIQUE_SYMBOL == (141827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141828)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc4%1
		#endinput
	#if UNIQUE_SYMBOL == (141828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141829)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc5%1
		#endinput
	#if UNIQUE_SYMBOL == (141829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141830)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141831)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141839)
	#elseif UNIQUE_SYMBOL == (141831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141832)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141833)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141834)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141835)
		#define UNIQUE_FUNCTION<%0...%1> %0XcA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141836)
		#define UNIQUE_FUNCTION<%0...%1> %0XcB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141837)
		#define UNIQUE_FUNCTION<%0...%1> %0XcC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141838)
		#define UNIQUE_FUNCTION<%0...%1> %0XcD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141839)
		#define UNIQUE_FUNCTION<%0...%1> %0XcE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141847)
	#elseif UNIQUE_SYMBOL == (141839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141840)
		#define UNIQUE_FUNCTION<%0...%1> %0XcF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141841)
		#define UNIQUE_FUNCTION<%0...%1> %0XcG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141842)
		#define UNIQUE_FUNCTION<%0...%1> %0XcH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141843)
		#define UNIQUE_FUNCTION<%0...%1> %0XcI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141844)
		#define UNIQUE_FUNCTION<%0...%1> %0XcJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141845)
		#define UNIQUE_FUNCTION<%0...%1> %0XcK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141846)
		#define UNIQUE_FUNCTION<%0...%1> %0XcL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141847)
		#define UNIQUE_FUNCTION<%0...%1> %0XcM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141855)
	#elseif UNIQUE_SYMBOL == (141847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141848)
		#define UNIQUE_FUNCTION<%0...%1> %0XcN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141849)
		#define UNIQUE_FUNCTION<%0...%1> %0XcO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141850)
		#define UNIQUE_FUNCTION<%0...%1> %0XcP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141851)
		#define UNIQUE_FUNCTION<%0...%1> %0XcQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141852)
		#define UNIQUE_FUNCTION<%0...%1> %0XcR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141853)
		#define UNIQUE_FUNCTION<%0...%1> %0XcS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141854)
		#define UNIQUE_FUNCTION<%0...%1> %0XcT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141855)
		#define UNIQUE_FUNCTION<%0...%1> %0XcU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141863)
	#elseif UNIQUE_SYMBOL == (141855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141856)
		#define UNIQUE_FUNCTION<%0...%1> %0XcV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141857)
		#define UNIQUE_FUNCTION<%0...%1> %0XcW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141858)
		#define UNIQUE_FUNCTION<%0...%1> %0XcX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141859)
		#define UNIQUE_FUNCTION<%0...%1> %0XcY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141860)
		#define UNIQUE_FUNCTION<%0...%1> %0XcZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141861)
		#define UNIQUE_FUNCTION<%0...%1> %0Xc_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141862)
		#define UNIQUE_FUNCTION<%0...%1> %0Xca%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141863)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141871)
	#elseif UNIQUE_SYMBOL == (141863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141864)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141865)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141866)
		#define UNIQUE_FUNCTION<%0...%1> %0Xce%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141867)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141868)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141869)
		#define UNIQUE_FUNCTION<%0...%1> %0Xch%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141870)
		#define UNIQUE_FUNCTION<%0...%1> %0Xci%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141871)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141879)
	#elseif UNIQUE_SYMBOL == (141871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141872)
		#define UNIQUE_FUNCTION<%0...%1> %0Xck%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141873)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141874)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141875)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141876)
		#define UNIQUE_FUNCTION<%0...%1> %0Xco%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141877)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141878)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141879)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (141879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141880)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141881)
		#define UNIQUE_FUNCTION<%0...%1> %0Xct%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141882)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141883)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141884)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141885)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141886)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141887)
		#define UNIQUE_FUNCTION<%0...%1> %0Xcz%1
		#endinput
	#endif
#endif
