static stock const Y_UNIQUE_016384_016447_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_016384_016447
	#undef _inc_y_unique_016384_016447
#endif

#if UNIQUE_SYMBOL < (16391)
	#if UNIQUE_SYMBOL == (16383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16384)
		#define UNIQUE_FUNCTION<%0...%1> %0400%1
		#endinput
	#if UNIQUE_SYMBOL == (16384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16385)
		#define UNIQUE_FUNCTION<%0...%1> %0401%1
		#endinput
	#if UNIQUE_SYMBOL == (16385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16386)
		#define UNIQUE_FUNCTION<%0...%1> %0402%1
		#endinput
	#if UNIQUE_SYMBOL == (16386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16387)
		#define UNIQUE_FUNCTION<%0...%1> %0403%1
		#endinput
	#if UNIQUE_SYMBOL == (16387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16388)
		#define UNIQUE_FUNCTION<%0...%1> %0404%1
		#endinput
	#if UNIQUE_SYMBOL == (16388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16389)
		#define UNIQUE_FUNCTION<%0...%1> %0405%1
		#endinput
	#if UNIQUE_SYMBOL == (16389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16390)
		#define UNIQUE_FUNCTION<%0...%1> %0406%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16391)
		#define UNIQUE_FUNCTION<%0...%1> %0407%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (16399)
	#elseif UNIQUE_SYMBOL == (16391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16392)
		#define UNIQUE_FUNCTION<%0...%1> %0408%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16393)
		#define UNIQUE_FUNCTION<%0...%1> %0409%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16394)
		#define UNIQUE_FUNCTION<%0...%1> %040@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16395)
		#define UNIQUE_FUNCTION<%0...%1> %040A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16396)
		#define UNIQUE_FUNCTION<%0...%1> %040B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16397)
		#define UNIQUE_FUNCTION<%0...%1> %040C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16398)
		#define UNIQUE_FUNCTION<%0...%1> %040D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16399)
		#define UNIQUE_FUNCTION<%0...%1> %040E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (16407)
	#elseif UNIQUE_SYMBOL == (16399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16400)
		#define UNIQUE_FUNCTION<%0...%1> %040F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16401)
		#define UNIQUE_FUNCTION<%0...%1> %040G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16402)
		#define UNIQUE_FUNCTION<%0...%1> %040H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16403)
		#define UNIQUE_FUNCTION<%0...%1> %040I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16404)
		#define UNIQUE_FUNCTION<%0...%1> %040J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16405)
		#define UNIQUE_FUNCTION<%0...%1> %040K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16406)
		#define UNIQUE_FUNCTION<%0...%1> %040L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16407)
		#define UNIQUE_FUNCTION<%0...%1> %040M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (16415)
	#elseif UNIQUE_SYMBOL == (16407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16408)
		#define UNIQUE_FUNCTION<%0...%1> %040N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16409)
		#define UNIQUE_FUNCTION<%0...%1> %040O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16410)
		#define UNIQUE_FUNCTION<%0...%1> %040P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16411)
		#define UNIQUE_FUNCTION<%0...%1> %040Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16412)
		#define UNIQUE_FUNCTION<%0...%1> %040R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16413)
		#define UNIQUE_FUNCTION<%0...%1> %040S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16414)
		#define UNIQUE_FUNCTION<%0...%1> %040T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16415)
		#define UNIQUE_FUNCTION<%0...%1> %040U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (16423)
	#elseif UNIQUE_SYMBOL == (16415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16416)
		#define UNIQUE_FUNCTION<%0...%1> %040V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16417)
		#define UNIQUE_FUNCTION<%0...%1> %040W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16418)
		#define UNIQUE_FUNCTION<%0...%1> %040X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16419)
		#define UNIQUE_FUNCTION<%0...%1> %040Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16420)
		#define UNIQUE_FUNCTION<%0...%1> %040Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16421)
		#define UNIQUE_FUNCTION<%0...%1> %040_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16422)
		#define UNIQUE_FUNCTION<%0...%1> %040a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16423)
		#define UNIQUE_FUNCTION<%0...%1> %040b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (16431)
	#elseif UNIQUE_SYMBOL == (16423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16424)
		#define UNIQUE_FUNCTION<%0...%1> %040c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16425)
		#define UNIQUE_FUNCTION<%0...%1> %040d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16426)
		#define UNIQUE_FUNCTION<%0...%1> %040e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16427)
		#define UNIQUE_FUNCTION<%0...%1> %040f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16428)
		#define UNIQUE_FUNCTION<%0...%1> %040g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16429)
		#define UNIQUE_FUNCTION<%0...%1> %040h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16430)
		#define UNIQUE_FUNCTION<%0...%1> %040i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16431)
		#define UNIQUE_FUNCTION<%0...%1> %040j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (16439)
	#elseif UNIQUE_SYMBOL == (16431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16432)
		#define UNIQUE_FUNCTION<%0...%1> %040k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16433)
		#define UNIQUE_FUNCTION<%0...%1> %040l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16434)
		#define UNIQUE_FUNCTION<%0...%1> %040m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16435)
		#define UNIQUE_FUNCTION<%0...%1> %040n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16436)
		#define UNIQUE_FUNCTION<%0...%1> %040o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16437)
		#define UNIQUE_FUNCTION<%0...%1> %040p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16438)
		#define UNIQUE_FUNCTION<%0...%1> %040q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16439)
		#define UNIQUE_FUNCTION<%0...%1> %040r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (16439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16440)
		#define UNIQUE_FUNCTION<%0...%1> %040s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16441)
		#define UNIQUE_FUNCTION<%0...%1> %040t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16442)
		#define UNIQUE_FUNCTION<%0...%1> %040u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16443)
		#define UNIQUE_FUNCTION<%0...%1> %040v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16444)
		#define UNIQUE_FUNCTION<%0...%1> %040w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16445)
		#define UNIQUE_FUNCTION<%0...%1> %040x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (16445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16446)
		#define UNIQUE_FUNCTION<%0...%1> %040y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (16447)
		#define UNIQUE_FUNCTION<%0...%1> %040z%1
		#endinput
	#endif
#endif
