static stock const Y_UNIQUE_107072_107135_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_107072_107135
	#undef _inc_y_unique_107072_107135
#endif

#if UNIQUE_SYMBOL < (107079)
	#if UNIQUE_SYMBOL == (107071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107072)
		#define UNIQUE_FUNCTION<%0...%1> %0P90%1
		#endinput
	#if UNIQUE_SYMBOL == (107072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107073)
		#define UNIQUE_FUNCTION<%0...%1> %0P91%1
		#endinput
	#if UNIQUE_SYMBOL == (107073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107074)
		#define UNIQUE_FUNCTION<%0...%1> %0P92%1
		#endinput
	#if UNIQUE_SYMBOL == (107074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107075)
		#define UNIQUE_FUNCTION<%0...%1> %0P93%1
		#endinput
	#if UNIQUE_SYMBOL == (107075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107076)
		#define UNIQUE_FUNCTION<%0...%1> %0P94%1
		#endinput
	#if UNIQUE_SYMBOL == (107076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107077)
		#define UNIQUE_FUNCTION<%0...%1> %0P95%1
		#endinput
	#if UNIQUE_SYMBOL == (107077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107078)
		#define UNIQUE_FUNCTION<%0...%1> %0P96%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107079)
		#define UNIQUE_FUNCTION<%0...%1> %0P97%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107087)
	#elseif UNIQUE_SYMBOL == (107079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107080)
		#define UNIQUE_FUNCTION<%0...%1> %0P98%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107081)
		#define UNIQUE_FUNCTION<%0...%1> %0P99%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107082)
		#define UNIQUE_FUNCTION<%0...%1> %0P9@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107083)
		#define UNIQUE_FUNCTION<%0...%1> %0P9A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107084)
		#define UNIQUE_FUNCTION<%0...%1> %0P9B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107085)
		#define UNIQUE_FUNCTION<%0...%1> %0P9C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107086)
		#define UNIQUE_FUNCTION<%0...%1> %0P9D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107087)
		#define UNIQUE_FUNCTION<%0...%1> %0P9E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107095)
	#elseif UNIQUE_SYMBOL == (107087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107088)
		#define UNIQUE_FUNCTION<%0...%1> %0P9F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107089)
		#define UNIQUE_FUNCTION<%0...%1> %0P9G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107090)
		#define UNIQUE_FUNCTION<%0...%1> %0P9H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107091)
		#define UNIQUE_FUNCTION<%0...%1> %0P9I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107092)
		#define UNIQUE_FUNCTION<%0...%1> %0P9J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107093)
		#define UNIQUE_FUNCTION<%0...%1> %0P9K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107094)
		#define UNIQUE_FUNCTION<%0...%1> %0P9L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107095)
		#define UNIQUE_FUNCTION<%0...%1> %0P9M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107103)
	#elseif UNIQUE_SYMBOL == (107095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107096)
		#define UNIQUE_FUNCTION<%0...%1> %0P9N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107097)
		#define UNIQUE_FUNCTION<%0...%1> %0P9O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107098)
		#define UNIQUE_FUNCTION<%0...%1> %0P9P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107099)
		#define UNIQUE_FUNCTION<%0...%1> %0P9Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107100)
		#define UNIQUE_FUNCTION<%0...%1> %0P9R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107101)
		#define UNIQUE_FUNCTION<%0...%1> %0P9S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107102)
		#define UNIQUE_FUNCTION<%0...%1> %0P9T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107103)
		#define UNIQUE_FUNCTION<%0...%1> %0P9U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107111)
	#elseif UNIQUE_SYMBOL == (107103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107104)
		#define UNIQUE_FUNCTION<%0...%1> %0P9V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107105)
		#define UNIQUE_FUNCTION<%0...%1> %0P9W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107106)
		#define UNIQUE_FUNCTION<%0...%1> %0P9X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107107)
		#define UNIQUE_FUNCTION<%0...%1> %0P9Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107108)
		#define UNIQUE_FUNCTION<%0...%1> %0P9Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107109)
		#define UNIQUE_FUNCTION<%0...%1> %0P9_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107110)
		#define UNIQUE_FUNCTION<%0...%1> %0P9a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107111)
		#define UNIQUE_FUNCTION<%0...%1> %0P9b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107119)
	#elseif UNIQUE_SYMBOL == (107111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107112)
		#define UNIQUE_FUNCTION<%0...%1> %0P9c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107113)
		#define UNIQUE_FUNCTION<%0...%1> %0P9d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107114)
		#define UNIQUE_FUNCTION<%0...%1> %0P9e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107115)
		#define UNIQUE_FUNCTION<%0...%1> %0P9f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107116)
		#define UNIQUE_FUNCTION<%0...%1> %0P9g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107117)
		#define UNIQUE_FUNCTION<%0...%1> %0P9h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107118)
		#define UNIQUE_FUNCTION<%0...%1> %0P9i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107119)
		#define UNIQUE_FUNCTION<%0...%1> %0P9j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (107127)
	#elseif UNIQUE_SYMBOL == (107119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107120)
		#define UNIQUE_FUNCTION<%0...%1> %0P9k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107121)
		#define UNIQUE_FUNCTION<%0...%1> %0P9l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107122)
		#define UNIQUE_FUNCTION<%0...%1> %0P9m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107123)
		#define UNIQUE_FUNCTION<%0...%1> %0P9n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107124)
		#define UNIQUE_FUNCTION<%0...%1> %0P9o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107125)
		#define UNIQUE_FUNCTION<%0...%1> %0P9p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107126)
		#define UNIQUE_FUNCTION<%0...%1> %0P9q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107127)
		#define UNIQUE_FUNCTION<%0...%1> %0P9r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (107127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107128)
		#define UNIQUE_FUNCTION<%0...%1> %0P9s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107129)
		#define UNIQUE_FUNCTION<%0...%1> %0P9t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107130)
		#define UNIQUE_FUNCTION<%0...%1> %0P9u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107131)
		#define UNIQUE_FUNCTION<%0...%1> %0P9v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107132)
		#define UNIQUE_FUNCTION<%0...%1> %0P9w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107133)
		#define UNIQUE_FUNCTION<%0...%1> %0P9x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (107133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107134)
		#define UNIQUE_FUNCTION<%0...%1> %0P9y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (107135)
		#define UNIQUE_FUNCTION<%0...%1> %0P9z%1
		#endinput
	#endif
#endif
