static stock const Y_UNIQUE_145216_145279_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_145216_145279
	#undef _inc_y_unique_145216_145279
#endif

#if UNIQUE_SYMBOL < (145223)
	#if UNIQUE_SYMBOL == (145215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145216)
		#define UNIQUE_FUNCTION<%0...%1> %0YS0%1
		#endinput
	#if UNIQUE_SYMBOL == (145216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145217)
		#define UNIQUE_FUNCTION<%0...%1> %0YS1%1
		#endinput
	#if UNIQUE_SYMBOL == (145217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145218)
		#define UNIQUE_FUNCTION<%0...%1> %0YS2%1
		#endinput
	#if UNIQUE_SYMBOL == (145218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145219)
		#define UNIQUE_FUNCTION<%0...%1> %0YS3%1
		#endinput
	#if UNIQUE_SYMBOL == (145219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145220)
		#define UNIQUE_FUNCTION<%0...%1> %0YS4%1
		#endinput
	#if UNIQUE_SYMBOL == (145220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145221)
		#define UNIQUE_FUNCTION<%0...%1> %0YS5%1
		#endinput
	#if UNIQUE_SYMBOL == (145221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145222)
		#define UNIQUE_FUNCTION<%0...%1> %0YS6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145223)
		#define UNIQUE_FUNCTION<%0...%1> %0YS7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145231)
	#elseif UNIQUE_SYMBOL == (145223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145224)
		#define UNIQUE_FUNCTION<%0...%1> %0YS8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145225)
		#define UNIQUE_FUNCTION<%0...%1> %0YS9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145226)
		#define UNIQUE_FUNCTION<%0...%1> %0YS@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145227)
		#define UNIQUE_FUNCTION<%0...%1> %0YSA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145228)
		#define UNIQUE_FUNCTION<%0...%1> %0YSB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145229)
		#define UNIQUE_FUNCTION<%0...%1> %0YSC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145230)
		#define UNIQUE_FUNCTION<%0...%1> %0YSD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145231)
		#define UNIQUE_FUNCTION<%0...%1> %0YSE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145239)
	#elseif UNIQUE_SYMBOL == (145231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145232)
		#define UNIQUE_FUNCTION<%0...%1> %0YSF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145233)
		#define UNIQUE_FUNCTION<%0...%1> %0YSG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145234)
		#define UNIQUE_FUNCTION<%0...%1> %0YSH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145235)
		#define UNIQUE_FUNCTION<%0...%1> %0YSI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145236)
		#define UNIQUE_FUNCTION<%0...%1> %0YSJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145237)
		#define UNIQUE_FUNCTION<%0...%1> %0YSK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145238)
		#define UNIQUE_FUNCTION<%0...%1> %0YSL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145239)
		#define UNIQUE_FUNCTION<%0...%1> %0YSM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145247)
	#elseif UNIQUE_SYMBOL == (145239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145240)
		#define UNIQUE_FUNCTION<%0...%1> %0YSN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145241)
		#define UNIQUE_FUNCTION<%0...%1> %0YSO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145242)
		#define UNIQUE_FUNCTION<%0...%1> %0YSP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145243)
		#define UNIQUE_FUNCTION<%0...%1> %0YSQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145244)
		#define UNIQUE_FUNCTION<%0...%1> %0YSR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145245)
		#define UNIQUE_FUNCTION<%0...%1> %0YSS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145246)
		#define UNIQUE_FUNCTION<%0...%1> %0YST%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145247)
		#define UNIQUE_FUNCTION<%0...%1> %0YSU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145255)
	#elseif UNIQUE_SYMBOL == (145247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145248)
		#define UNIQUE_FUNCTION<%0...%1> %0YSV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145249)
		#define UNIQUE_FUNCTION<%0...%1> %0YSW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145250)
		#define UNIQUE_FUNCTION<%0...%1> %0YSX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145251)
		#define UNIQUE_FUNCTION<%0...%1> %0YSY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145252)
		#define UNIQUE_FUNCTION<%0...%1> %0YSZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145253)
		#define UNIQUE_FUNCTION<%0...%1> %0YS_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145254)
		#define UNIQUE_FUNCTION<%0...%1> %0YSa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145255)
		#define UNIQUE_FUNCTION<%0...%1> %0YSb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145263)
	#elseif UNIQUE_SYMBOL == (145255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145256)
		#define UNIQUE_FUNCTION<%0...%1> %0YSc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145257)
		#define UNIQUE_FUNCTION<%0...%1> %0YSd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145258)
		#define UNIQUE_FUNCTION<%0...%1> %0YSe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145259)
		#define UNIQUE_FUNCTION<%0...%1> %0YSf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145260)
		#define UNIQUE_FUNCTION<%0...%1> %0YSg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145261)
		#define UNIQUE_FUNCTION<%0...%1> %0YSh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145262)
		#define UNIQUE_FUNCTION<%0...%1> %0YSi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145263)
		#define UNIQUE_FUNCTION<%0...%1> %0YSj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145271)
	#elseif UNIQUE_SYMBOL == (145263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145264)
		#define UNIQUE_FUNCTION<%0...%1> %0YSk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145265)
		#define UNIQUE_FUNCTION<%0...%1> %0YSl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145266)
		#define UNIQUE_FUNCTION<%0...%1> %0YSm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145267)
		#define UNIQUE_FUNCTION<%0...%1> %0YSn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145268)
		#define UNIQUE_FUNCTION<%0...%1> %0YSo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145269)
		#define UNIQUE_FUNCTION<%0...%1> %0YSp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145270)
		#define UNIQUE_FUNCTION<%0...%1> %0YSq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145271)
		#define UNIQUE_FUNCTION<%0...%1> %0YSr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (145271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145272)
		#define UNIQUE_FUNCTION<%0...%1> %0YSs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145273)
		#define UNIQUE_FUNCTION<%0...%1> %0YSt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145274)
		#define UNIQUE_FUNCTION<%0...%1> %0YSu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145275)
		#define UNIQUE_FUNCTION<%0...%1> %0YSv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145276)
		#define UNIQUE_FUNCTION<%0...%1> %0YSw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145277)
		#define UNIQUE_FUNCTION<%0...%1> %0YSx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145278)
		#define UNIQUE_FUNCTION<%0...%1> %0YSy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145279)
		#define UNIQUE_FUNCTION<%0...%1> %0YSz%1
		#endinput
	#endif
#endif
