static stock const Y_UNIQUE_019520_019583_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_019520_019583
	#undef _inc_y_unique_019520_019583
#endif

#if UNIQUE_SYMBOL < (19527)
	#if UNIQUE_SYMBOL == (19519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19520)
		#define UNIQUE_FUNCTION<%0...%1> %04l0%1
		#endinput
	#if UNIQUE_SYMBOL == (19520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19521)
		#define UNIQUE_FUNCTION<%0...%1> %04l1%1
		#endinput
	#if UNIQUE_SYMBOL == (19521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19522)
		#define UNIQUE_FUNCTION<%0...%1> %04l2%1
		#endinput
	#if UNIQUE_SYMBOL == (19522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19523)
		#define UNIQUE_FUNCTION<%0...%1> %04l3%1
		#endinput
	#if UNIQUE_SYMBOL == (19523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19524)
		#define UNIQUE_FUNCTION<%0...%1> %04l4%1
		#endinput
	#if UNIQUE_SYMBOL == (19524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19525)
		#define UNIQUE_FUNCTION<%0...%1> %04l5%1
		#endinput
	#if UNIQUE_SYMBOL == (19525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19526)
		#define UNIQUE_FUNCTION<%0...%1> %04l6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19527)
		#define UNIQUE_FUNCTION<%0...%1> %04l7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19535)
	#elseif UNIQUE_SYMBOL == (19527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19528)
		#define UNIQUE_FUNCTION<%0...%1> %04l8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19529)
		#define UNIQUE_FUNCTION<%0...%1> %04l9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19530)
		#define UNIQUE_FUNCTION<%0...%1> %04l@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19531)
		#define UNIQUE_FUNCTION<%0...%1> %04lA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19532)
		#define UNIQUE_FUNCTION<%0...%1> %04lB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19533)
		#define UNIQUE_FUNCTION<%0...%1> %04lC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19534)
		#define UNIQUE_FUNCTION<%0...%1> %04lD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19535)
		#define UNIQUE_FUNCTION<%0...%1> %04lE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19543)
	#elseif UNIQUE_SYMBOL == (19535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19536)
		#define UNIQUE_FUNCTION<%0...%1> %04lF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19537)
		#define UNIQUE_FUNCTION<%0...%1> %04lG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19538)
		#define UNIQUE_FUNCTION<%0...%1> %04lH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19539)
		#define UNIQUE_FUNCTION<%0...%1> %04lI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19540)
		#define UNIQUE_FUNCTION<%0...%1> %04lJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19541)
		#define UNIQUE_FUNCTION<%0...%1> %04lK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19542)
		#define UNIQUE_FUNCTION<%0...%1> %04lL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19543)
		#define UNIQUE_FUNCTION<%0...%1> %04lM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19551)
	#elseif UNIQUE_SYMBOL == (19543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19544)
		#define UNIQUE_FUNCTION<%0...%1> %04lN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19545)
		#define UNIQUE_FUNCTION<%0...%1> %04lO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19546)
		#define UNIQUE_FUNCTION<%0...%1> %04lP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19547)
		#define UNIQUE_FUNCTION<%0...%1> %04lQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19548)
		#define UNIQUE_FUNCTION<%0...%1> %04lR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19549)
		#define UNIQUE_FUNCTION<%0...%1> %04lS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19550)
		#define UNIQUE_FUNCTION<%0...%1> %04lT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19551)
		#define UNIQUE_FUNCTION<%0...%1> %04lU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19559)
	#elseif UNIQUE_SYMBOL == (19551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19552)
		#define UNIQUE_FUNCTION<%0...%1> %04lV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19553)
		#define UNIQUE_FUNCTION<%0...%1> %04lW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19554)
		#define UNIQUE_FUNCTION<%0...%1> %04lX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19555)
		#define UNIQUE_FUNCTION<%0...%1> %04lY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19556)
		#define UNIQUE_FUNCTION<%0...%1> %04lZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19557)
		#define UNIQUE_FUNCTION<%0...%1> %04l_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19558)
		#define UNIQUE_FUNCTION<%0...%1> %04la%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19559)
		#define UNIQUE_FUNCTION<%0...%1> %04lb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19567)
	#elseif UNIQUE_SYMBOL == (19559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19560)
		#define UNIQUE_FUNCTION<%0...%1> %04lc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19561)
		#define UNIQUE_FUNCTION<%0...%1> %04ld%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19562)
		#define UNIQUE_FUNCTION<%0...%1> %04le%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19563)
		#define UNIQUE_FUNCTION<%0...%1> %04lf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19564)
		#define UNIQUE_FUNCTION<%0...%1> %04lg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19565)
		#define UNIQUE_FUNCTION<%0...%1> %04lh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19566)
		#define UNIQUE_FUNCTION<%0...%1> %04li%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19567)
		#define UNIQUE_FUNCTION<%0...%1> %04lj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19575)
	#elseif UNIQUE_SYMBOL == (19567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19568)
		#define UNIQUE_FUNCTION<%0...%1> %04lk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19569)
		#define UNIQUE_FUNCTION<%0...%1> %04ll%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19570)
		#define UNIQUE_FUNCTION<%0...%1> %04lm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19571)
		#define UNIQUE_FUNCTION<%0...%1> %04ln%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19572)
		#define UNIQUE_FUNCTION<%0...%1> %04lo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19573)
		#define UNIQUE_FUNCTION<%0...%1> %04lp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19574)
		#define UNIQUE_FUNCTION<%0...%1> %04lq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19575)
		#define UNIQUE_FUNCTION<%0...%1> %04lr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (19575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19576)
		#define UNIQUE_FUNCTION<%0...%1> %04ls%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19577)
		#define UNIQUE_FUNCTION<%0...%1> %04lt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19578)
		#define UNIQUE_FUNCTION<%0...%1> %04lu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19579)
		#define UNIQUE_FUNCTION<%0...%1> %04lv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19580)
		#define UNIQUE_FUNCTION<%0...%1> %04lw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19581)
		#define UNIQUE_FUNCTION<%0...%1> %04lx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19582)
		#define UNIQUE_FUNCTION<%0...%1> %04ly%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19583)
		#define UNIQUE_FUNCTION<%0...%1> %04lz%1
		#endinput
	#endif
#endif
