static stock const Y_UNIQUE_028736_028799_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_028736_028799
	#undef _inc_y_unique_028736_028799
#endif

#if UNIQUE_SYMBOL < (28743)
	#if UNIQUE_SYMBOL == (28735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28736)
		#define UNIQUE_FUNCTION<%0...%1> %0710%1
		#endinput
	#if UNIQUE_SYMBOL == (28736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28737)
		#define UNIQUE_FUNCTION<%0...%1> %0711%1
		#endinput
	#if UNIQUE_SYMBOL == (28737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28738)
		#define UNIQUE_FUNCTION<%0...%1> %0712%1
		#endinput
	#if UNIQUE_SYMBOL == (28738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28739)
		#define UNIQUE_FUNCTION<%0...%1> %0713%1
		#endinput
	#if UNIQUE_SYMBOL == (28739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28740)
		#define UNIQUE_FUNCTION<%0...%1> %0714%1
		#endinput
	#if UNIQUE_SYMBOL == (28740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28741)
		#define UNIQUE_FUNCTION<%0...%1> %0715%1
		#endinput
	#if UNIQUE_SYMBOL == (28741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28742)
		#define UNIQUE_FUNCTION<%0...%1> %0716%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28743)
		#define UNIQUE_FUNCTION<%0...%1> %0717%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28751)
	#elseif UNIQUE_SYMBOL == (28743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28744)
		#define UNIQUE_FUNCTION<%0...%1> %0718%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28745)
		#define UNIQUE_FUNCTION<%0...%1> %0719%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28746)
		#define UNIQUE_FUNCTION<%0...%1> %071@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28747)
		#define UNIQUE_FUNCTION<%0...%1> %071A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28748)
		#define UNIQUE_FUNCTION<%0...%1> %071B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28749)
		#define UNIQUE_FUNCTION<%0...%1> %071C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28750)
		#define UNIQUE_FUNCTION<%0...%1> %071D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28751)
		#define UNIQUE_FUNCTION<%0...%1> %071E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28759)
	#elseif UNIQUE_SYMBOL == (28751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28752)
		#define UNIQUE_FUNCTION<%0...%1> %071F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28753)
		#define UNIQUE_FUNCTION<%0...%1> %071G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28754)
		#define UNIQUE_FUNCTION<%0...%1> %071H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28755)
		#define UNIQUE_FUNCTION<%0...%1> %071I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28756)
		#define UNIQUE_FUNCTION<%0...%1> %071J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28757)
		#define UNIQUE_FUNCTION<%0...%1> %071K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28758)
		#define UNIQUE_FUNCTION<%0...%1> %071L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28759)
		#define UNIQUE_FUNCTION<%0...%1> %071M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28767)
	#elseif UNIQUE_SYMBOL == (28759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28760)
		#define UNIQUE_FUNCTION<%0...%1> %071N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28761)
		#define UNIQUE_FUNCTION<%0...%1> %071O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28762)
		#define UNIQUE_FUNCTION<%0...%1> %071P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28763)
		#define UNIQUE_FUNCTION<%0...%1> %071Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28764)
		#define UNIQUE_FUNCTION<%0...%1> %071R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28765)
		#define UNIQUE_FUNCTION<%0...%1> %071S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28766)
		#define UNIQUE_FUNCTION<%0...%1> %071T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28767)
		#define UNIQUE_FUNCTION<%0...%1> %071U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28775)
	#elseif UNIQUE_SYMBOL == (28767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28768)
		#define UNIQUE_FUNCTION<%0...%1> %071V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28769)
		#define UNIQUE_FUNCTION<%0...%1> %071W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28770)
		#define UNIQUE_FUNCTION<%0...%1> %071X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28771)
		#define UNIQUE_FUNCTION<%0...%1> %071Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28772)
		#define UNIQUE_FUNCTION<%0...%1> %071Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28773)
		#define UNIQUE_FUNCTION<%0...%1> %071_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28774)
		#define UNIQUE_FUNCTION<%0...%1> %071a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28775)
		#define UNIQUE_FUNCTION<%0...%1> %071b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28783)
	#elseif UNIQUE_SYMBOL == (28775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28776)
		#define UNIQUE_FUNCTION<%0...%1> %071c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28777)
		#define UNIQUE_FUNCTION<%0...%1> %071d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28778)
		#define UNIQUE_FUNCTION<%0...%1> %071e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28779)
		#define UNIQUE_FUNCTION<%0...%1> %071f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28780)
		#define UNIQUE_FUNCTION<%0...%1> %071g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28781)
		#define UNIQUE_FUNCTION<%0...%1> %071h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28782)
		#define UNIQUE_FUNCTION<%0...%1> %071i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28783)
		#define UNIQUE_FUNCTION<%0...%1> %071j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28791)
	#elseif UNIQUE_SYMBOL == (28783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28784)
		#define UNIQUE_FUNCTION<%0...%1> %071k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28785)
		#define UNIQUE_FUNCTION<%0...%1> %071l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28786)
		#define UNIQUE_FUNCTION<%0...%1> %071m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28787)
		#define UNIQUE_FUNCTION<%0...%1> %071n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28788)
		#define UNIQUE_FUNCTION<%0...%1> %071o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28789)
		#define UNIQUE_FUNCTION<%0...%1> %071p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28790)
		#define UNIQUE_FUNCTION<%0...%1> %071q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28791)
		#define UNIQUE_FUNCTION<%0...%1> %071r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (28791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28792)
		#define UNIQUE_FUNCTION<%0...%1> %071s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28793)
		#define UNIQUE_FUNCTION<%0...%1> %071t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28794)
		#define UNIQUE_FUNCTION<%0...%1> %071u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28795)
		#define UNIQUE_FUNCTION<%0...%1> %071v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28796)
		#define UNIQUE_FUNCTION<%0...%1> %071w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28797)
		#define UNIQUE_FUNCTION<%0...%1> %071x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28798)
		#define UNIQUE_FUNCTION<%0...%1> %071y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28799)
		#define UNIQUE_FUNCTION<%0...%1> %071z%1
		#endinput
	#endif
#endif
