static stock const Y_UNIQUE_095104_095167_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_095104_095167
	#undef _inc_y_unique_095104_095167
#endif

#if UNIQUE_SYMBOL < (95111)
	#if UNIQUE_SYMBOL == (95103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95104)
		#define UNIQUE_FUNCTION<%0...%1> %0MD0%1
		#endinput
	#if UNIQUE_SYMBOL == (95104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95105)
		#define UNIQUE_FUNCTION<%0...%1> %0MD1%1
		#endinput
	#if UNIQUE_SYMBOL == (95105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95106)
		#define UNIQUE_FUNCTION<%0...%1> %0MD2%1
		#endinput
	#if UNIQUE_SYMBOL == (95106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95107)
		#define UNIQUE_FUNCTION<%0...%1> %0MD3%1
		#endinput
	#if UNIQUE_SYMBOL == (95107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95108)
		#define UNIQUE_FUNCTION<%0...%1> %0MD4%1
		#endinput
	#if UNIQUE_SYMBOL == (95108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95109)
		#define UNIQUE_FUNCTION<%0...%1> %0MD5%1
		#endinput
	#if UNIQUE_SYMBOL == (95109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95110)
		#define UNIQUE_FUNCTION<%0...%1> %0MD6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95111)
		#define UNIQUE_FUNCTION<%0...%1> %0MD7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95119)
	#elseif UNIQUE_SYMBOL == (95111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95112)
		#define UNIQUE_FUNCTION<%0...%1> %0MD8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95113)
		#define UNIQUE_FUNCTION<%0...%1> %0MD9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95114)
		#define UNIQUE_FUNCTION<%0...%1> %0MD@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95115)
		#define UNIQUE_FUNCTION<%0...%1> %0MDA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95116)
		#define UNIQUE_FUNCTION<%0...%1> %0MDB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95117)
		#define UNIQUE_FUNCTION<%0...%1> %0MDC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95118)
		#define UNIQUE_FUNCTION<%0...%1> %0MDD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95119)
		#define UNIQUE_FUNCTION<%0...%1> %0MDE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95127)
	#elseif UNIQUE_SYMBOL == (95119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95120)
		#define UNIQUE_FUNCTION<%0...%1> %0MDF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95121)
		#define UNIQUE_FUNCTION<%0...%1> %0MDG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95122)
		#define UNIQUE_FUNCTION<%0...%1> %0MDH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95123)
		#define UNIQUE_FUNCTION<%0...%1> %0MDI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95124)
		#define UNIQUE_FUNCTION<%0...%1> %0MDJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95125)
		#define UNIQUE_FUNCTION<%0...%1> %0MDK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95126)
		#define UNIQUE_FUNCTION<%0...%1> %0MDL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95127)
		#define UNIQUE_FUNCTION<%0...%1> %0MDM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95135)
	#elseif UNIQUE_SYMBOL == (95127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95128)
		#define UNIQUE_FUNCTION<%0...%1> %0MDN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95129)
		#define UNIQUE_FUNCTION<%0...%1> %0MDO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95130)
		#define UNIQUE_FUNCTION<%0...%1> %0MDP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95131)
		#define UNIQUE_FUNCTION<%0...%1> %0MDQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95132)
		#define UNIQUE_FUNCTION<%0...%1> %0MDR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95133)
		#define UNIQUE_FUNCTION<%0...%1> %0MDS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95134)
		#define UNIQUE_FUNCTION<%0...%1> %0MDT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95135)
		#define UNIQUE_FUNCTION<%0...%1> %0MDU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95143)
	#elseif UNIQUE_SYMBOL == (95135)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95136)
		#define UNIQUE_FUNCTION<%0...%1> %0MDV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95136)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95137)
		#define UNIQUE_FUNCTION<%0...%1> %0MDW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95137)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95138)
		#define UNIQUE_FUNCTION<%0...%1> %0MDX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95138)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95139)
		#define UNIQUE_FUNCTION<%0...%1> %0MDY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95139)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95140)
		#define UNIQUE_FUNCTION<%0...%1> %0MDZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95140)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95141)
		#define UNIQUE_FUNCTION<%0...%1> %0MD_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95141)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95142)
		#define UNIQUE_FUNCTION<%0...%1> %0MDa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95143)
		#define UNIQUE_FUNCTION<%0...%1> %0MDb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95151)
	#elseif UNIQUE_SYMBOL == (95143)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95144)
		#define UNIQUE_FUNCTION<%0...%1> %0MDc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95144)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95145)
		#define UNIQUE_FUNCTION<%0...%1> %0MDd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95145)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95146)
		#define UNIQUE_FUNCTION<%0...%1> %0MDe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95146)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95147)
		#define UNIQUE_FUNCTION<%0...%1> %0MDf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95147)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95148)
		#define UNIQUE_FUNCTION<%0...%1> %0MDg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95148)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95149)
		#define UNIQUE_FUNCTION<%0...%1> %0MDh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95149)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95150)
		#define UNIQUE_FUNCTION<%0...%1> %0MDi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95151)
		#define UNIQUE_FUNCTION<%0...%1> %0MDj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (95159)
	#elseif UNIQUE_SYMBOL == (95151)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95152)
		#define UNIQUE_FUNCTION<%0...%1> %0MDk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95152)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95153)
		#define UNIQUE_FUNCTION<%0...%1> %0MDl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95153)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95154)
		#define UNIQUE_FUNCTION<%0...%1> %0MDm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95154)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95155)
		#define UNIQUE_FUNCTION<%0...%1> %0MDn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95155)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95156)
		#define UNIQUE_FUNCTION<%0...%1> %0MDo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95156)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95157)
		#define UNIQUE_FUNCTION<%0...%1> %0MDp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95157)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95158)
		#define UNIQUE_FUNCTION<%0...%1> %0MDq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95159)
		#define UNIQUE_FUNCTION<%0...%1> %0MDr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (95159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95160)
		#define UNIQUE_FUNCTION<%0...%1> %0MDs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95161)
		#define UNIQUE_FUNCTION<%0...%1> %0MDt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95162)
		#define UNIQUE_FUNCTION<%0...%1> %0MDu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95163)
		#define UNIQUE_FUNCTION<%0...%1> %0MDv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95164)
		#define UNIQUE_FUNCTION<%0...%1> %0MDw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95165)
		#define UNIQUE_FUNCTION<%0...%1> %0MDx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (95165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95166)
		#define UNIQUE_FUNCTION<%0...%1> %0MDy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (95167)
		#define UNIQUE_FUNCTION<%0...%1> %0MDz%1
		#endinput
	#endif
#endif
