static stock const Y_UNIQUE_104000_104063_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_104000_104063
	#undef _inc_y_unique_104000_104063
#endif

#if UNIQUE_SYMBOL < (104007)
	#if UNIQUE_SYMBOL == (103999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104000)
		#define UNIQUE_FUNCTION<%0...%1> %0OO0%1
		#endinput
	#if UNIQUE_SYMBOL == (104000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104001)
		#define UNIQUE_FUNCTION<%0...%1> %0OO1%1
		#endinput
	#if UNIQUE_SYMBOL == (104001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104002)
		#define UNIQUE_FUNCTION<%0...%1> %0OO2%1
		#endinput
	#if UNIQUE_SYMBOL == (104002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104003)
		#define UNIQUE_FUNCTION<%0...%1> %0OO3%1
		#endinput
	#if UNIQUE_SYMBOL == (104003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104004)
		#define UNIQUE_FUNCTION<%0...%1> %0OO4%1
		#endinput
	#if UNIQUE_SYMBOL == (104004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104005)
		#define UNIQUE_FUNCTION<%0...%1> %0OO5%1
		#endinput
	#if UNIQUE_SYMBOL == (104005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104006)
		#define UNIQUE_FUNCTION<%0...%1> %0OO6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104007)
		#define UNIQUE_FUNCTION<%0...%1> %0OO7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104015)
	#elseif UNIQUE_SYMBOL == (104007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104008)
		#define UNIQUE_FUNCTION<%0...%1> %0OO8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104009)
		#define UNIQUE_FUNCTION<%0...%1> %0OO9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104010)
		#define UNIQUE_FUNCTION<%0...%1> %0OO@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104011)
		#define UNIQUE_FUNCTION<%0...%1> %0OOA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104012)
		#define UNIQUE_FUNCTION<%0...%1> %0OOB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104013)
		#define UNIQUE_FUNCTION<%0...%1> %0OOC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104014)
		#define UNIQUE_FUNCTION<%0...%1> %0OOD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104015)
		#define UNIQUE_FUNCTION<%0...%1> %0OOE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104023)
	#elseif UNIQUE_SYMBOL == (104015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104016)
		#define UNIQUE_FUNCTION<%0...%1> %0OOF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104017)
		#define UNIQUE_FUNCTION<%0...%1> %0OOG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104018)
		#define UNIQUE_FUNCTION<%0...%1> %0OOH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104019)
		#define UNIQUE_FUNCTION<%0...%1> %0OOI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104020)
		#define UNIQUE_FUNCTION<%0...%1> %0OOJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104021)
		#define UNIQUE_FUNCTION<%0...%1> %0OOK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104022)
		#define UNIQUE_FUNCTION<%0...%1> %0OOL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104023)
		#define UNIQUE_FUNCTION<%0...%1> %0OOM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104031)
	#elseif UNIQUE_SYMBOL == (104023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104024)
		#define UNIQUE_FUNCTION<%0...%1> %0OON%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104025)
		#define UNIQUE_FUNCTION<%0...%1> %0OOO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104026)
		#define UNIQUE_FUNCTION<%0...%1> %0OOP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104027)
		#define UNIQUE_FUNCTION<%0...%1> %0OOQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104028)
		#define UNIQUE_FUNCTION<%0...%1> %0OOR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104029)
		#define UNIQUE_FUNCTION<%0...%1> %0OOS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104030)
		#define UNIQUE_FUNCTION<%0...%1> %0OOT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104031)
		#define UNIQUE_FUNCTION<%0...%1> %0OOU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104039)
	#elseif UNIQUE_SYMBOL == (104031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104032)
		#define UNIQUE_FUNCTION<%0...%1> %0OOV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104033)
		#define UNIQUE_FUNCTION<%0...%1> %0OOW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104034)
		#define UNIQUE_FUNCTION<%0...%1> %0OOX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104035)
		#define UNIQUE_FUNCTION<%0...%1> %0OOY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104036)
		#define UNIQUE_FUNCTION<%0...%1> %0OOZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104037)
		#define UNIQUE_FUNCTION<%0...%1> %0OO_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104038)
		#define UNIQUE_FUNCTION<%0...%1> %0OOa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104039)
		#define UNIQUE_FUNCTION<%0...%1> %0OOb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104047)
	#elseif UNIQUE_SYMBOL == (104039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104040)
		#define UNIQUE_FUNCTION<%0...%1> %0OOc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104041)
		#define UNIQUE_FUNCTION<%0...%1> %0OOd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104042)
		#define UNIQUE_FUNCTION<%0...%1> %0OOe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104043)
		#define UNIQUE_FUNCTION<%0...%1> %0OOf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104044)
		#define UNIQUE_FUNCTION<%0...%1> %0OOg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104045)
		#define UNIQUE_FUNCTION<%0...%1> %0OOh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104046)
		#define UNIQUE_FUNCTION<%0...%1> %0OOi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104047)
		#define UNIQUE_FUNCTION<%0...%1> %0OOj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104055)
	#elseif UNIQUE_SYMBOL == (104047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104048)
		#define UNIQUE_FUNCTION<%0...%1> %0OOk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104049)
		#define UNIQUE_FUNCTION<%0...%1> %0OOl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104050)
		#define UNIQUE_FUNCTION<%0...%1> %0OOm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104051)
		#define UNIQUE_FUNCTION<%0...%1> %0OOn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104052)
		#define UNIQUE_FUNCTION<%0...%1> %0OOo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104053)
		#define UNIQUE_FUNCTION<%0...%1> %0OOp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104054)
		#define UNIQUE_FUNCTION<%0...%1> %0OOq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104055)
		#define UNIQUE_FUNCTION<%0...%1> %0OOr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (104055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104056)
		#define UNIQUE_FUNCTION<%0...%1> %0OOs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104057)
		#define UNIQUE_FUNCTION<%0...%1> %0OOt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104058)
		#define UNIQUE_FUNCTION<%0...%1> %0OOu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104059)
		#define UNIQUE_FUNCTION<%0...%1> %0OOv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104060)
		#define UNIQUE_FUNCTION<%0...%1> %0OOw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104061)
		#define UNIQUE_FUNCTION<%0...%1> %0OOx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104062)
		#define UNIQUE_FUNCTION<%0...%1> %0OOy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104063)
		#define UNIQUE_FUNCTION<%0...%1> %0OOz%1
		#endinput
	#endif
#endif
