static stock const Y_UNIQUE_081920_081983_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_081920_081983
	#undef _inc_y_unique_081920_081983
#endif

#if UNIQUE_SYMBOL < (81927)
	#if UNIQUE_SYMBOL == (81919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81920)
		#define UNIQUE_FUNCTION<%0...%1> %0J00%1
		#endinput
	#if UNIQUE_SYMBOL == (81920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81921)
		#define UNIQUE_FUNCTION<%0...%1> %0J01%1
		#endinput
	#if UNIQUE_SYMBOL == (81921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81922)
		#define UNIQUE_FUNCTION<%0...%1> %0J02%1
		#endinput
	#if UNIQUE_SYMBOL == (81922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81923)
		#define UNIQUE_FUNCTION<%0...%1> %0J03%1
		#endinput
	#if UNIQUE_SYMBOL == (81923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81924)
		#define UNIQUE_FUNCTION<%0...%1> %0J04%1
		#endinput
	#if UNIQUE_SYMBOL == (81924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81925)
		#define UNIQUE_FUNCTION<%0...%1> %0J05%1
		#endinput
	#if UNIQUE_SYMBOL == (81925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81926)
		#define UNIQUE_FUNCTION<%0...%1> %0J06%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81927)
		#define UNIQUE_FUNCTION<%0...%1> %0J07%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81935)
	#elseif UNIQUE_SYMBOL == (81927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81928)
		#define UNIQUE_FUNCTION<%0...%1> %0J08%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81929)
		#define UNIQUE_FUNCTION<%0...%1> %0J09%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81930)
		#define UNIQUE_FUNCTION<%0...%1> %0J0@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81931)
		#define UNIQUE_FUNCTION<%0...%1> %0J0A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81932)
		#define UNIQUE_FUNCTION<%0...%1> %0J0B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81933)
		#define UNIQUE_FUNCTION<%0...%1> %0J0C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81934)
		#define UNIQUE_FUNCTION<%0...%1> %0J0D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81935)
		#define UNIQUE_FUNCTION<%0...%1> %0J0E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81943)
	#elseif UNIQUE_SYMBOL == (81935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81936)
		#define UNIQUE_FUNCTION<%0...%1> %0J0F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81937)
		#define UNIQUE_FUNCTION<%0...%1> %0J0G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81938)
		#define UNIQUE_FUNCTION<%0...%1> %0J0H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81939)
		#define UNIQUE_FUNCTION<%0...%1> %0J0I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81940)
		#define UNIQUE_FUNCTION<%0...%1> %0J0J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81941)
		#define UNIQUE_FUNCTION<%0...%1> %0J0K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81942)
		#define UNIQUE_FUNCTION<%0...%1> %0J0L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81943)
		#define UNIQUE_FUNCTION<%0...%1> %0J0M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81951)
	#elseif UNIQUE_SYMBOL == (81943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81944)
		#define UNIQUE_FUNCTION<%0...%1> %0J0N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81945)
		#define UNIQUE_FUNCTION<%0...%1> %0J0O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81946)
		#define UNIQUE_FUNCTION<%0...%1> %0J0P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81947)
		#define UNIQUE_FUNCTION<%0...%1> %0J0Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81948)
		#define UNIQUE_FUNCTION<%0...%1> %0J0R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81949)
		#define UNIQUE_FUNCTION<%0...%1> %0J0S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81950)
		#define UNIQUE_FUNCTION<%0...%1> %0J0T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81951)
		#define UNIQUE_FUNCTION<%0...%1> %0J0U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81959)
	#elseif UNIQUE_SYMBOL == (81951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81952)
		#define UNIQUE_FUNCTION<%0...%1> %0J0V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81953)
		#define UNIQUE_FUNCTION<%0...%1> %0J0W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81954)
		#define UNIQUE_FUNCTION<%0...%1> %0J0X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81955)
		#define UNIQUE_FUNCTION<%0...%1> %0J0Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81956)
		#define UNIQUE_FUNCTION<%0...%1> %0J0Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81957)
		#define UNIQUE_FUNCTION<%0...%1> %0J0_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81958)
		#define UNIQUE_FUNCTION<%0...%1> %0J0a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81959)
		#define UNIQUE_FUNCTION<%0...%1> %0J0b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81967)
	#elseif UNIQUE_SYMBOL == (81959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81960)
		#define UNIQUE_FUNCTION<%0...%1> %0J0c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81961)
		#define UNIQUE_FUNCTION<%0...%1> %0J0d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81962)
		#define UNIQUE_FUNCTION<%0...%1> %0J0e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81963)
		#define UNIQUE_FUNCTION<%0...%1> %0J0f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81964)
		#define UNIQUE_FUNCTION<%0...%1> %0J0g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81965)
		#define UNIQUE_FUNCTION<%0...%1> %0J0h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81966)
		#define UNIQUE_FUNCTION<%0...%1> %0J0i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81967)
		#define UNIQUE_FUNCTION<%0...%1> %0J0j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81975)
	#elseif UNIQUE_SYMBOL == (81967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81968)
		#define UNIQUE_FUNCTION<%0...%1> %0J0k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81969)
		#define UNIQUE_FUNCTION<%0...%1> %0J0l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81970)
		#define UNIQUE_FUNCTION<%0...%1> %0J0m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81971)
		#define UNIQUE_FUNCTION<%0...%1> %0J0n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81972)
		#define UNIQUE_FUNCTION<%0...%1> %0J0o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81973)
		#define UNIQUE_FUNCTION<%0...%1> %0J0p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81974)
		#define UNIQUE_FUNCTION<%0...%1> %0J0q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81975)
		#define UNIQUE_FUNCTION<%0...%1> %0J0r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (81975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81976)
		#define UNIQUE_FUNCTION<%0...%1> %0J0s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81977)
		#define UNIQUE_FUNCTION<%0...%1> %0J0t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81978)
		#define UNIQUE_FUNCTION<%0...%1> %0J0u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81979)
		#define UNIQUE_FUNCTION<%0...%1> %0J0v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81980)
		#define UNIQUE_FUNCTION<%0...%1> %0J0w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81981)
		#define UNIQUE_FUNCTION<%0...%1> %0J0x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81982)
		#define UNIQUE_FUNCTION<%0...%1> %0J0y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81983)
		#define UNIQUE_FUNCTION<%0...%1> %0J0z%1
		#endinput
	#endif
#endif
