static stock const Y_UNIQUE_0704_0767_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_0704_0767
	#undef _inc_y_unique_0704_0767
#endif

#if UNIQUE_SYMBOL < (711)
	#if UNIQUE_SYMBOL == (703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (704)
		#define UNIQUE_FUNCTION<%0...%1> %0A0%1
		#endinput
	#elseif UNIQUE_SYMBOL == (704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (705)
		#define UNIQUE_FUNCTION<%0...%1> %0A1%1
		#endinput
	#elseif UNIQUE_SYMBOL == (705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (706)
		#define UNIQUE_FUNCTION<%0...%1> %0A2%1
		#endinput
	#elseif UNIQUE_SYMBOL == (706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (707)
		#define UNIQUE_FUNCTION<%0...%1> %0A3%1
		#endinput
	#elseif UNIQUE_SYMBOL == (707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (708)
		#define UNIQUE_FUNCTION<%0...%1> %0A4%1
		#endinput
	#elseif UNIQUE_SYMBOL == (708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (709)
		#define UNIQUE_FUNCTION<%0...%1> %0A5%1
		#endinput
	#elseif UNIQUE_SYMBOL == (709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (710)
		#define UNIQUE_FUNCTION<%0...%1> %0A6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (711)
		#define UNIQUE_FUNCTION<%0...%1> %0A7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (719)
	#if UNIQUE_SYMBOL == (711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (712)
		#define UNIQUE_FUNCTION<%0...%1> %0A8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (713)
		#define UNIQUE_FUNCTION<%0...%1> %0A9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (714)
		#define UNIQUE_FUNCTION<%0...%1> %0A@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (715)
		#define UNIQUE_FUNCTION<%0...%1> %0AA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (716)
		#define UNIQUE_FUNCTION<%0...%1> %0AB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (717)
		#define UNIQUE_FUNCTION<%0...%1> %0AC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (718)
		#define UNIQUE_FUNCTION<%0...%1> %0AD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (719)
		#define UNIQUE_FUNCTION<%0...%1> %0AE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (727)
	#if UNIQUE_SYMBOL == (719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (720)
		#define UNIQUE_FUNCTION<%0...%1> %0AF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (721)
		#define UNIQUE_FUNCTION<%0...%1> %0AG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (722)
		#define UNIQUE_FUNCTION<%0...%1> %0AH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (723)
		#define UNIQUE_FUNCTION<%0...%1> %0AI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (724)
		#define UNIQUE_FUNCTION<%0...%1> %0AJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (725)
		#define UNIQUE_FUNCTION<%0...%1> %0AK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (726)
		#define UNIQUE_FUNCTION<%0...%1> %0AL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (727)
		#define UNIQUE_FUNCTION<%0...%1> %0AM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (735)
	#if UNIQUE_SYMBOL == (727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (728)
		#define UNIQUE_FUNCTION<%0...%1> %0AN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (729)
		#define UNIQUE_FUNCTION<%0...%1> %0AO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (730)
		#define UNIQUE_FUNCTION<%0...%1> %0AP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (731)
		#define UNIQUE_FUNCTION<%0...%1> %0AQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (732)
		#define UNIQUE_FUNCTION<%0...%1> %0AR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (733)
		#define UNIQUE_FUNCTION<%0...%1> %0AS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (734)
		#define UNIQUE_FUNCTION<%0...%1> %0AT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (735)
		#define UNIQUE_FUNCTION<%0...%1> %0AU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (743)
	#if UNIQUE_SYMBOL == (735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (736)
		#define UNIQUE_FUNCTION<%0...%1> %0AV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (737)
		#define UNIQUE_FUNCTION<%0...%1> %0AW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (738)
		#define UNIQUE_FUNCTION<%0...%1> %0AX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (739)
		#define UNIQUE_FUNCTION<%0...%1> %0AY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (740)
		#define UNIQUE_FUNCTION<%0...%1> %0AZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (741)
		#define UNIQUE_FUNCTION<%0...%1> %0A_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (742)
		#define UNIQUE_FUNCTION<%0...%1> %0Aa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (743)
		#define UNIQUE_FUNCTION<%0...%1> %0Ab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (751)
	#if UNIQUE_SYMBOL == (743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (744)
		#define UNIQUE_FUNCTION<%0...%1> %0Ac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (745)
		#define UNIQUE_FUNCTION<%0...%1> %0Ad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (746)
		#define UNIQUE_FUNCTION<%0...%1> %0Ae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (747)
		#define UNIQUE_FUNCTION<%0...%1> %0Af%1
		#endinput
	#elseif UNIQUE_SYMBOL == (747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (748)
		#define UNIQUE_FUNCTION<%0...%1> %0Ag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (749)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (750)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (751)
		#define UNIQUE_FUNCTION<%0...%1> %0Aj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (759)
	#if UNIQUE_SYMBOL == (751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (752)
		#define UNIQUE_FUNCTION<%0...%1> %0Ak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (753)
		#define UNIQUE_FUNCTION<%0...%1> %0Al%1
		#endinput
	#elseif UNIQUE_SYMBOL == (753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (754)
		#define UNIQUE_FUNCTION<%0...%1> %0Am%1
		#endinput
	#elseif UNIQUE_SYMBOL == (754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (755)
		#define UNIQUE_FUNCTION<%0...%1> %0An%1
		#endinput
	#elseif UNIQUE_SYMBOL == (755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (756)
		#define UNIQUE_FUNCTION<%0...%1> %0Ao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (757)
		#define UNIQUE_FUNCTION<%0...%1> %0Ap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (758)
		#define UNIQUE_FUNCTION<%0...%1> %0Aq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (759)
		#define UNIQUE_FUNCTION<%0...%1> %0Ar%1
		#endinput
	#endif
#else
	#if UNIQUE_SYMBOL == (759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (760)
		#define UNIQUE_FUNCTION<%0...%1> %0As%1
		#endinput
	#elseif UNIQUE_SYMBOL == (760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (761)
		#define UNIQUE_FUNCTION<%0...%1> %0At%1
		#endinput
	#elseif UNIQUE_SYMBOL == (761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (762)
		#define UNIQUE_FUNCTION<%0...%1> %0Au%1
		#endinput
	#elseif UNIQUE_SYMBOL == (762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (763)
		#define UNIQUE_FUNCTION<%0...%1> %0Av%1
		#endinput
	#elseif UNIQUE_SYMBOL == (763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (764)
		#define UNIQUE_FUNCTION<%0...%1> %0Aw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (765)
		#define UNIQUE_FUNCTION<%0...%1> %0Ax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (766)
		#define UNIQUE_FUNCTION<%0...%1> %0Ay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (767)
		#define UNIQUE_FUNCTION<%0...%1> %0Az%1
		#endinput
	#endif
#endif

