static stock const Y_UNIQUE_034688_034751_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_034688_034751
	#undef _inc_y_unique_034688_034751
#endif

#if UNIQUE_SYMBOL < (34695)
	#if UNIQUE_SYMBOL == (34687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34688)
		#define UNIQUE_FUNCTION<%0...%1> %08T0%1
		#endinput
	#if UNIQUE_SYMBOL == (34688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34689)
		#define UNIQUE_FUNCTION<%0...%1> %08T1%1
		#endinput
	#if UNIQUE_SYMBOL == (34689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34690)
		#define UNIQUE_FUNCTION<%0...%1> %08T2%1
		#endinput
	#if UNIQUE_SYMBOL == (34690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34691)
		#define UNIQUE_FUNCTION<%0...%1> %08T3%1
		#endinput
	#if UNIQUE_SYMBOL == (34691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34692)
		#define UNIQUE_FUNCTION<%0...%1> %08T4%1
		#endinput
	#if UNIQUE_SYMBOL == (34692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34693)
		#define UNIQUE_FUNCTION<%0...%1> %08T5%1
		#endinput
	#if UNIQUE_SYMBOL == (34693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34694)
		#define UNIQUE_FUNCTION<%0...%1> %08T6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34695)
		#define UNIQUE_FUNCTION<%0...%1> %08T7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34703)
	#elseif UNIQUE_SYMBOL == (34695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34696)
		#define UNIQUE_FUNCTION<%0...%1> %08T8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34697)
		#define UNIQUE_FUNCTION<%0...%1> %08T9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34698)
		#define UNIQUE_FUNCTION<%0...%1> %08T@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34699)
		#define UNIQUE_FUNCTION<%0...%1> %08TA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34700)
		#define UNIQUE_FUNCTION<%0...%1> %08TB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34701)
		#define UNIQUE_FUNCTION<%0...%1> %08TC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34702)
		#define UNIQUE_FUNCTION<%0...%1> %08TD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34703)
		#define UNIQUE_FUNCTION<%0...%1> %08TE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34711)
	#elseif UNIQUE_SYMBOL == (34703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34704)
		#define UNIQUE_FUNCTION<%0...%1> %08TF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34705)
		#define UNIQUE_FUNCTION<%0...%1> %08TG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34706)
		#define UNIQUE_FUNCTION<%0...%1> %08TH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34707)
		#define UNIQUE_FUNCTION<%0...%1> %08TI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34708)
		#define UNIQUE_FUNCTION<%0...%1> %08TJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34709)
		#define UNIQUE_FUNCTION<%0...%1> %08TK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34710)
		#define UNIQUE_FUNCTION<%0...%1> %08TL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34711)
		#define UNIQUE_FUNCTION<%0...%1> %08TM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34719)
	#elseif UNIQUE_SYMBOL == (34711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34712)
		#define UNIQUE_FUNCTION<%0...%1> %08TN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34713)
		#define UNIQUE_FUNCTION<%0...%1> %08TO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34714)
		#define UNIQUE_FUNCTION<%0...%1> %08TP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34715)
		#define UNIQUE_FUNCTION<%0...%1> %08TQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34716)
		#define UNIQUE_FUNCTION<%0...%1> %08TR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34717)
		#define UNIQUE_FUNCTION<%0...%1> %08TS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34718)
		#define UNIQUE_FUNCTION<%0...%1> %08TT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34719)
		#define UNIQUE_FUNCTION<%0...%1> %08TU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34727)
	#elseif UNIQUE_SYMBOL == (34719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34720)
		#define UNIQUE_FUNCTION<%0...%1> %08TV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34721)
		#define UNIQUE_FUNCTION<%0...%1> %08TW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34722)
		#define UNIQUE_FUNCTION<%0...%1> %08TX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34723)
		#define UNIQUE_FUNCTION<%0...%1> %08TY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34724)
		#define UNIQUE_FUNCTION<%0...%1> %08TZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34725)
		#define UNIQUE_FUNCTION<%0...%1> %08T_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34726)
		#define UNIQUE_FUNCTION<%0...%1> %08Ta%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34727)
		#define UNIQUE_FUNCTION<%0...%1> %08Tb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34735)
	#elseif UNIQUE_SYMBOL == (34727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34728)
		#define UNIQUE_FUNCTION<%0...%1> %08Tc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34729)
		#define UNIQUE_FUNCTION<%0...%1> %08Td%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34730)
		#define UNIQUE_FUNCTION<%0...%1> %08Te%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34731)
		#define UNIQUE_FUNCTION<%0...%1> %08Tf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34732)
		#define UNIQUE_FUNCTION<%0...%1> %08Tg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34733)
		#define UNIQUE_FUNCTION<%0...%1> %08Th%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34734)
		#define UNIQUE_FUNCTION<%0...%1> %08Ti%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34735)
		#define UNIQUE_FUNCTION<%0...%1> %08Tj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (34743)
	#elseif UNIQUE_SYMBOL == (34735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34736)
		#define UNIQUE_FUNCTION<%0...%1> %08Tk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34737)
		#define UNIQUE_FUNCTION<%0...%1> %08Tl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34738)
		#define UNIQUE_FUNCTION<%0...%1> %08Tm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34739)
		#define UNIQUE_FUNCTION<%0...%1> %08Tn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34740)
		#define UNIQUE_FUNCTION<%0...%1> %08To%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34741)
		#define UNIQUE_FUNCTION<%0...%1> %08Tp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34742)
		#define UNIQUE_FUNCTION<%0...%1> %08Tq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34743)
		#define UNIQUE_FUNCTION<%0...%1> %08Tr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (34743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34744)
		#define UNIQUE_FUNCTION<%0...%1> %08Ts%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34745)
		#define UNIQUE_FUNCTION<%0...%1> %08Tt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34746)
		#define UNIQUE_FUNCTION<%0...%1> %08Tu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34747)
		#define UNIQUE_FUNCTION<%0...%1> %08Tv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34748)
		#define UNIQUE_FUNCTION<%0...%1> %08Tw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34749)
		#define UNIQUE_FUNCTION<%0...%1> %08Tx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (34749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34750)
		#define UNIQUE_FUNCTION<%0...%1> %08Ty%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (34751)
		#define UNIQUE_FUNCTION<%0...%1> %08Tz%1
		#endinput
	#endif
#endif
