static stock const Y_UNIQUE_047104_047167_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_047104_047167
	#undef _inc_y_unique_047104_047167
#endif

#if UNIQUE_SYMBOL < (47111)
	#if UNIQUE_SYMBOL == (47103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47104)
		#define UNIQUE_FUNCTION<%0...%1> %0AV0%1
		#endinput
	#if UNIQUE_SYMBOL == (47104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47105)
		#define UNIQUE_FUNCTION<%0...%1> %0AV1%1
		#endinput
	#if UNIQUE_SYMBOL == (47105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47106)
		#define UNIQUE_FUNCTION<%0...%1> %0AV2%1
		#endinput
	#if UNIQUE_SYMBOL == (47106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47107)
		#define UNIQUE_FUNCTION<%0...%1> %0AV3%1
		#endinput
	#if UNIQUE_SYMBOL == (47107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47108)
		#define UNIQUE_FUNCTION<%0...%1> %0AV4%1
		#endinput
	#if UNIQUE_SYMBOL == (47108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47109)
		#define UNIQUE_FUNCTION<%0...%1> %0AV5%1
		#endinput
	#if UNIQUE_SYMBOL == (47109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47110)
		#define UNIQUE_FUNCTION<%0...%1> %0AV6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47111)
		#define UNIQUE_FUNCTION<%0...%1> %0AV7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47119)
	#elseif UNIQUE_SYMBOL == (47111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47112)
		#define UNIQUE_FUNCTION<%0...%1> %0AV8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47113)
		#define UNIQUE_FUNCTION<%0...%1> %0AV9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47114)
		#define UNIQUE_FUNCTION<%0...%1> %0AV@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47115)
		#define UNIQUE_FUNCTION<%0...%1> %0AVA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47116)
		#define UNIQUE_FUNCTION<%0...%1> %0AVB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47117)
		#define UNIQUE_FUNCTION<%0...%1> %0AVC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47118)
		#define UNIQUE_FUNCTION<%0...%1> %0AVD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47119)
		#define UNIQUE_FUNCTION<%0...%1> %0AVE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47127)
	#elseif UNIQUE_SYMBOL == (47119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47120)
		#define UNIQUE_FUNCTION<%0...%1> %0AVF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47121)
		#define UNIQUE_FUNCTION<%0...%1> %0AVG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47122)
		#define UNIQUE_FUNCTION<%0...%1> %0AVH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47123)
		#define UNIQUE_FUNCTION<%0...%1> %0AVI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47124)
		#define UNIQUE_FUNCTION<%0...%1> %0AVJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47125)
		#define UNIQUE_FUNCTION<%0...%1> %0AVK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47126)
		#define UNIQUE_FUNCTION<%0...%1> %0AVL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47127)
		#define UNIQUE_FUNCTION<%0...%1> %0AVM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47135)
	#elseif UNIQUE_SYMBOL == (47127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47128)
		#define UNIQUE_FUNCTION<%0...%1> %0AVN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47129)
		#define UNIQUE_FUNCTION<%0...%1> %0AVO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47130)
		#define UNIQUE_FUNCTION<%0...%1> %0AVP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47131)
		#define UNIQUE_FUNCTION<%0...%1> %0AVQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47132)
		#define UNIQUE_FUNCTION<%0...%1> %0AVR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47133)
		#define UNIQUE_FUNCTION<%0...%1> %0AVS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47134)
		#define UNIQUE_FUNCTION<%0...%1> %0AVT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47135)
		#define UNIQUE_FUNCTION<%0...%1> %0AVU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47143)
	#elseif UNIQUE_SYMBOL == (47135)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47136)
		#define UNIQUE_FUNCTION<%0...%1> %0AVV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47136)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47137)
		#define UNIQUE_FUNCTION<%0...%1> %0AVW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47137)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47138)
		#define UNIQUE_FUNCTION<%0...%1> %0AVX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47138)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47139)
		#define UNIQUE_FUNCTION<%0...%1> %0AVY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47139)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47140)
		#define UNIQUE_FUNCTION<%0...%1> %0AVZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47140)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47141)
		#define UNIQUE_FUNCTION<%0...%1> %0AV_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47141)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47142)
		#define UNIQUE_FUNCTION<%0...%1> %0AVa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47143)
		#define UNIQUE_FUNCTION<%0...%1> %0AVb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47151)
	#elseif UNIQUE_SYMBOL == (47143)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47144)
		#define UNIQUE_FUNCTION<%0...%1> %0AVc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47144)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47145)
		#define UNIQUE_FUNCTION<%0...%1> %0AVd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47145)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47146)
		#define UNIQUE_FUNCTION<%0...%1> %0AVe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47146)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47147)
		#define UNIQUE_FUNCTION<%0...%1> %0AVf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47147)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47148)
		#define UNIQUE_FUNCTION<%0...%1> %0AVg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47148)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47149)
		#define UNIQUE_FUNCTION<%0...%1> %0AVh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47149)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47150)
		#define UNIQUE_FUNCTION<%0...%1> %0AVi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47151)
		#define UNIQUE_FUNCTION<%0...%1> %0AVj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47159)
	#elseif UNIQUE_SYMBOL == (47151)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47152)
		#define UNIQUE_FUNCTION<%0...%1> %0AVk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47152)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47153)
		#define UNIQUE_FUNCTION<%0...%1> %0AVl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47153)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47154)
		#define UNIQUE_FUNCTION<%0...%1> %0AVm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47154)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47155)
		#define UNIQUE_FUNCTION<%0...%1> %0AVn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47155)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47156)
		#define UNIQUE_FUNCTION<%0...%1> %0AVo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47156)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47157)
		#define UNIQUE_FUNCTION<%0...%1> %0AVp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47157)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47158)
		#define UNIQUE_FUNCTION<%0...%1> %0AVq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47159)
		#define UNIQUE_FUNCTION<%0...%1> %0AVr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (47159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47160)
		#define UNIQUE_FUNCTION<%0...%1> %0AVs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47161)
		#define UNIQUE_FUNCTION<%0...%1> %0AVt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47162)
		#define UNIQUE_FUNCTION<%0...%1> %0AVu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47163)
		#define UNIQUE_FUNCTION<%0...%1> %0AVv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47164)
		#define UNIQUE_FUNCTION<%0...%1> %0AVw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47165)
		#define UNIQUE_FUNCTION<%0...%1> %0AVx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47166)
		#define UNIQUE_FUNCTION<%0...%1> %0AVy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47167)
		#define UNIQUE_FUNCTION<%0...%1> %0AVz%1
		#endinput
	#endif
#endif
