static stock const Y_UNIQUE_222016_222079_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_222016_222079
	#undef _inc_y_unique_222016_222079
#endif

#if UNIQUE_SYMBOL < (222023)
	#if UNIQUE_SYMBOL == (222015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222016)
		#define UNIQUE_FUNCTION<%0...%1> %0qC0%1
		#endinput
	#if UNIQUE_SYMBOL == (222016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222017)
		#define UNIQUE_FUNCTION<%0...%1> %0qC1%1
		#endinput
	#if UNIQUE_SYMBOL == (222017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222018)
		#define UNIQUE_FUNCTION<%0...%1> %0qC2%1
		#endinput
	#if UNIQUE_SYMBOL == (222018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222019)
		#define UNIQUE_FUNCTION<%0...%1> %0qC3%1
		#endinput
	#if UNIQUE_SYMBOL == (222019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222020)
		#define UNIQUE_FUNCTION<%0...%1> %0qC4%1
		#endinput
	#if UNIQUE_SYMBOL == (222020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222021)
		#define UNIQUE_FUNCTION<%0...%1> %0qC5%1
		#endinput
	#if UNIQUE_SYMBOL == (222021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222022)
		#define UNIQUE_FUNCTION<%0...%1> %0qC6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222023)
		#define UNIQUE_FUNCTION<%0...%1> %0qC7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (222031)
	#elseif UNIQUE_SYMBOL == (222023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222024)
		#define UNIQUE_FUNCTION<%0...%1> %0qC8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222025)
		#define UNIQUE_FUNCTION<%0...%1> %0qC9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222026)
		#define UNIQUE_FUNCTION<%0...%1> %0qC@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222027)
		#define UNIQUE_FUNCTION<%0...%1> %0qCA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222028)
		#define UNIQUE_FUNCTION<%0...%1> %0qCB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222029)
		#define UNIQUE_FUNCTION<%0...%1> %0qCC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222030)
		#define UNIQUE_FUNCTION<%0...%1> %0qCD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222031)
		#define UNIQUE_FUNCTION<%0...%1> %0qCE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (222039)
	#elseif UNIQUE_SYMBOL == (222031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222032)
		#define UNIQUE_FUNCTION<%0...%1> %0qCF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222033)
		#define UNIQUE_FUNCTION<%0...%1> %0qCG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222034)
		#define UNIQUE_FUNCTION<%0...%1> %0qCH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222035)
		#define UNIQUE_FUNCTION<%0...%1> %0qCI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222036)
		#define UNIQUE_FUNCTION<%0...%1> %0qCJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222037)
		#define UNIQUE_FUNCTION<%0...%1> %0qCK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222038)
		#define UNIQUE_FUNCTION<%0...%1> %0qCL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222039)
		#define UNIQUE_FUNCTION<%0...%1> %0qCM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (222047)
	#elseif UNIQUE_SYMBOL == (222039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222040)
		#define UNIQUE_FUNCTION<%0...%1> %0qCN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222041)
		#define UNIQUE_FUNCTION<%0...%1> %0qCO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222042)
		#define UNIQUE_FUNCTION<%0...%1> %0qCP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222043)
		#define UNIQUE_FUNCTION<%0...%1> %0qCQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222044)
		#define UNIQUE_FUNCTION<%0...%1> %0qCR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222045)
		#define UNIQUE_FUNCTION<%0...%1> %0qCS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222046)
		#define UNIQUE_FUNCTION<%0...%1> %0qCT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222047)
		#define UNIQUE_FUNCTION<%0...%1> %0qCU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (222055)
	#elseif UNIQUE_SYMBOL == (222047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222048)
		#define UNIQUE_FUNCTION<%0...%1> %0qCV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222049)
		#define UNIQUE_FUNCTION<%0...%1> %0qCW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222050)
		#define UNIQUE_FUNCTION<%0...%1> %0qCX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222051)
		#define UNIQUE_FUNCTION<%0...%1> %0qCY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222052)
		#define UNIQUE_FUNCTION<%0...%1> %0qCZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222053)
		#define UNIQUE_FUNCTION<%0...%1> %0qC_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222054)
		#define UNIQUE_FUNCTION<%0...%1> %0qCa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222055)
		#define UNIQUE_FUNCTION<%0...%1> %0qCb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (222063)
	#elseif UNIQUE_SYMBOL == (222055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222056)
		#define UNIQUE_FUNCTION<%0...%1> %0qCc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222057)
		#define UNIQUE_FUNCTION<%0...%1> %0qCd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222058)
		#define UNIQUE_FUNCTION<%0...%1> %0qCe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222059)
		#define UNIQUE_FUNCTION<%0...%1> %0qCf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222060)
		#define UNIQUE_FUNCTION<%0...%1> %0qCg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222061)
		#define UNIQUE_FUNCTION<%0...%1> %0qCh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222062)
		#define UNIQUE_FUNCTION<%0...%1> %0qCi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222063)
		#define UNIQUE_FUNCTION<%0...%1> %0qCj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (222071)
	#elseif UNIQUE_SYMBOL == (222063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222064)
		#define UNIQUE_FUNCTION<%0...%1> %0qCk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222065)
		#define UNIQUE_FUNCTION<%0...%1> %0qCl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222066)
		#define UNIQUE_FUNCTION<%0...%1> %0qCm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222067)
		#define UNIQUE_FUNCTION<%0...%1> %0qCn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222068)
		#define UNIQUE_FUNCTION<%0...%1> %0qCo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222069)
		#define UNIQUE_FUNCTION<%0...%1> %0qCp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222070)
		#define UNIQUE_FUNCTION<%0...%1> %0qCq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222071)
		#define UNIQUE_FUNCTION<%0...%1> %0qCr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (222071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222072)
		#define UNIQUE_FUNCTION<%0...%1> %0qCs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222073)
		#define UNIQUE_FUNCTION<%0...%1> %0qCt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222074)
		#define UNIQUE_FUNCTION<%0...%1> %0qCu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222075)
		#define UNIQUE_FUNCTION<%0...%1> %0qCv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222076)
		#define UNIQUE_FUNCTION<%0...%1> %0qCw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222077)
		#define UNIQUE_FUNCTION<%0...%1> %0qCx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (222077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222078)
		#define UNIQUE_FUNCTION<%0...%1> %0qCy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (222079)
		#define UNIQUE_FUNCTION<%0...%1> %0qCz%1
		#endinput
	#endif
#endif
