static stock const Y_UNIQUE_015680_015743_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_015680_015743
	#undef _inc_y_unique_015680_015743
#endif

#if UNIQUE_SYMBOL < (15687)
	#if UNIQUE_SYMBOL == (15679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15680)
		#define UNIQUE_FUNCTION<%0...%1> %03p0%1
		#endinput
	#if UNIQUE_SYMBOL == (15680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15681)
		#define UNIQUE_FUNCTION<%0...%1> %03p1%1
		#endinput
	#if UNIQUE_SYMBOL == (15681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15682)
		#define UNIQUE_FUNCTION<%0...%1> %03p2%1
		#endinput
	#if UNIQUE_SYMBOL == (15682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15683)
		#define UNIQUE_FUNCTION<%0...%1> %03p3%1
		#endinput
	#if UNIQUE_SYMBOL == (15683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15684)
		#define UNIQUE_FUNCTION<%0...%1> %03p4%1
		#endinput
	#if UNIQUE_SYMBOL == (15684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15685)
		#define UNIQUE_FUNCTION<%0...%1> %03p5%1
		#endinput
	#if UNIQUE_SYMBOL == (15685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15686)
		#define UNIQUE_FUNCTION<%0...%1> %03p6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15687)
		#define UNIQUE_FUNCTION<%0...%1> %03p7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15695)
	#elseif UNIQUE_SYMBOL == (15687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15688)
		#define UNIQUE_FUNCTION<%0...%1> %03p8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15689)
		#define UNIQUE_FUNCTION<%0...%1> %03p9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15690)
		#define UNIQUE_FUNCTION<%0...%1> %03p@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15691)
		#define UNIQUE_FUNCTION<%0...%1> %03pA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15692)
		#define UNIQUE_FUNCTION<%0...%1> %03pB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15693)
		#define UNIQUE_FUNCTION<%0...%1> %03pC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15694)
		#define UNIQUE_FUNCTION<%0...%1> %03pD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15695)
		#define UNIQUE_FUNCTION<%0...%1> %03pE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15703)
	#elseif UNIQUE_SYMBOL == (15695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15696)
		#define UNIQUE_FUNCTION<%0...%1> %03pF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15697)
		#define UNIQUE_FUNCTION<%0...%1> %03pG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15698)
		#define UNIQUE_FUNCTION<%0...%1> %03pH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15699)
		#define UNIQUE_FUNCTION<%0...%1> %03pI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15700)
		#define UNIQUE_FUNCTION<%0...%1> %03pJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15701)
		#define UNIQUE_FUNCTION<%0...%1> %03pK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15702)
		#define UNIQUE_FUNCTION<%0...%1> %03pL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15703)
		#define UNIQUE_FUNCTION<%0...%1> %03pM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15711)
	#elseif UNIQUE_SYMBOL == (15703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15704)
		#define UNIQUE_FUNCTION<%0...%1> %03pN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15705)
		#define UNIQUE_FUNCTION<%0...%1> %03pO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15706)
		#define UNIQUE_FUNCTION<%0...%1> %03pP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15707)
		#define UNIQUE_FUNCTION<%0...%1> %03pQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15708)
		#define UNIQUE_FUNCTION<%0...%1> %03pR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15709)
		#define UNIQUE_FUNCTION<%0...%1> %03pS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15710)
		#define UNIQUE_FUNCTION<%0...%1> %03pT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15711)
		#define UNIQUE_FUNCTION<%0...%1> %03pU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15719)
	#elseif UNIQUE_SYMBOL == (15711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15712)
		#define UNIQUE_FUNCTION<%0...%1> %03pV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15713)
		#define UNIQUE_FUNCTION<%0...%1> %03pW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15714)
		#define UNIQUE_FUNCTION<%0...%1> %03pX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15715)
		#define UNIQUE_FUNCTION<%0...%1> %03pY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15716)
		#define UNIQUE_FUNCTION<%0...%1> %03pZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15717)
		#define UNIQUE_FUNCTION<%0...%1> %03p_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15718)
		#define UNIQUE_FUNCTION<%0...%1> %03pa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15719)
		#define UNIQUE_FUNCTION<%0...%1> %03pb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15727)
	#elseif UNIQUE_SYMBOL == (15719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15720)
		#define UNIQUE_FUNCTION<%0...%1> %03pc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15721)
		#define UNIQUE_FUNCTION<%0...%1> %03pd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15722)
		#define UNIQUE_FUNCTION<%0...%1> %03pe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15723)
		#define UNIQUE_FUNCTION<%0...%1> %03pf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15724)
		#define UNIQUE_FUNCTION<%0...%1> %03pg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15725)
		#define UNIQUE_FUNCTION<%0...%1> %03ph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15726)
		#define UNIQUE_FUNCTION<%0...%1> %03pi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15727)
		#define UNIQUE_FUNCTION<%0...%1> %03pj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15735)
	#elseif UNIQUE_SYMBOL == (15727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15728)
		#define UNIQUE_FUNCTION<%0...%1> %03pk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15729)
		#define UNIQUE_FUNCTION<%0...%1> %03pl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15730)
		#define UNIQUE_FUNCTION<%0...%1> %03pm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15731)
		#define UNIQUE_FUNCTION<%0...%1> %03pn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15732)
		#define UNIQUE_FUNCTION<%0...%1> %03po%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15733)
		#define UNIQUE_FUNCTION<%0...%1> %03pp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15734)
		#define UNIQUE_FUNCTION<%0...%1> %03pq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15735)
		#define UNIQUE_FUNCTION<%0...%1> %03pr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (15735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15736)
		#define UNIQUE_FUNCTION<%0...%1> %03ps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15737)
		#define UNIQUE_FUNCTION<%0...%1> %03pt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15738)
		#define UNIQUE_FUNCTION<%0...%1> %03pu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15739)
		#define UNIQUE_FUNCTION<%0...%1> %03pv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15740)
		#define UNIQUE_FUNCTION<%0...%1> %03pw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15741)
		#define UNIQUE_FUNCTION<%0...%1> %03px%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15742)
		#define UNIQUE_FUNCTION<%0...%1> %03py%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15743)
		#define UNIQUE_FUNCTION<%0...%1> %03pz%1
		#endinput
	#endif
#endif
