static stock const Y_UNIQUE_036928_036991_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_036928_036991
	#undef _inc_y_unique_036928_036991
#endif

#if UNIQUE_SYMBOL < (36935)
	#if UNIQUE_SYMBOL == (36927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36928)
		#define UNIQUE_FUNCTION<%0...%1> %0910%1
		#endinput
	#if UNIQUE_SYMBOL == (36928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36929)
		#define UNIQUE_FUNCTION<%0...%1> %0911%1
		#endinput
	#if UNIQUE_SYMBOL == (36929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36930)
		#define UNIQUE_FUNCTION<%0...%1> %0912%1
		#endinput
	#if UNIQUE_SYMBOL == (36930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36931)
		#define UNIQUE_FUNCTION<%0...%1> %0913%1
		#endinput
	#if UNIQUE_SYMBOL == (36931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36932)
		#define UNIQUE_FUNCTION<%0...%1> %0914%1
		#endinput
	#if UNIQUE_SYMBOL == (36932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36933)
		#define UNIQUE_FUNCTION<%0...%1> %0915%1
		#endinput
	#if UNIQUE_SYMBOL == (36933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36934)
		#define UNIQUE_FUNCTION<%0...%1> %0916%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36935)
		#define UNIQUE_FUNCTION<%0...%1> %0917%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36943)
	#elseif UNIQUE_SYMBOL == (36935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36936)
		#define UNIQUE_FUNCTION<%0...%1> %0918%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36937)
		#define UNIQUE_FUNCTION<%0...%1> %0919%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36938)
		#define UNIQUE_FUNCTION<%0...%1> %091@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36939)
		#define UNIQUE_FUNCTION<%0...%1> %091A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36940)
		#define UNIQUE_FUNCTION<%0...%1> %091B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36941)
		#define UNIQUE_FUNCTION<%0...%1> %091C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36942)
		#define UNIQUE_FUNCTION<%0...%1> %091D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36943)
		#define UNIQUE_FUNCTION<%0...%1> %091E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36951)
	#elseif UNIQUE_SYMBOL == (36943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36944)
		#define UNIQUE_FUNCTION<%0...%1> %091F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36945)
		#define UNIQUE_FUNCTION<%0...%1> %091G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36946)
		#define UNIQUE_FUNCTION<%0...%1> %091H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36947)
		#define UNIQUE_FUNCTION<%0...%1> %091I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36948)
		#define UNIQUE_FUNCTION<%0...%1> %091J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36949)
		#define UNIQUE_FUNCTION<%0...%1> %091K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36950)
		#define UNIQUE_FUNCTION<%0...%1> %091L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36951)
		#define UNIQUE_FUNCTION<%0...%1> %091M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36959)
	#elseif UNIQUE_SYMBOL == (36951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36952)
		#define UNIQUE_FUNCTION<%0...%1> %091N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36953)
		#define UNIQUE_FUNCTION<%0...%1> %091O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36954)
		#define UNIQUE_FUNCTION<%0...%1> %091P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36955)
		#define UNIQUE_FUNCTION<%0...%1> %091Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36956)
		#define UNIQUE_FUNCTION<%0...%1> %091R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36957)
		#define UNIQUE_FUNCTION<%0...%1> %091S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36958)
		#define UNIQUE_FUNCTION<%0...%1> %091T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36959)
		#define UNIQUE_FUNCTION<%0...%1> %091U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36967)
	#elseif UNIQUE_SYMBOL == (36959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36960)
		#define UNIQUE_FUNCTION<%0...%1> %091V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36961)
		#define UNIQUE_FUNCTION<%0...%1> %091W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36962)
		#define UNIQUE_FUNCTION<%0...%1> %091X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36963)
		#define UNIQUE_FUNCTION<%0...%1> %091Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36964)
		#define UNIQUE_FUNCTION<%0...%1> %091Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36965)
		#define UNIQUE_FUNCTION<%0...%1> %091_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36966)
		#define UNIQUE_FUNCTION<%0...%1> %091a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36967)
		#define UNIQUE_FUNCTION<%0...%1> %091b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36975)
	#elseif UNIQUE_SYMBOL == (36967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36968)
		#define UNIQUE_FUNCTION<%0...%1> %091c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36969)
		#define UNIQUE_FUNCTION<%0...%1> %091d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36970)
		#define UNIQUE_FUNCTION<%0...%1> %091e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36971)
		#define UNIQUE_FUNCTION<%0...%1> %091f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36972)
		#define UNIQUE_FUNCTION<%0...%1> %091g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36973)
		#define UNIQUE_FUNCTION<%0...%1> %091h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36974)
		#define UNIQUE_FUNCTION<%0...%1> %091i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36975)
		#define UNIQUE_FUNCTION<%0...%1> %091j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36983)
	#elseif UNIQUE_SYMBOL == (36975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36976)
		#define UNIQUE_FUNCTION<%0...%1> %091k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36977)
		#define UNIQUE_FUNCTION<%0...%1> %091l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36978)
		#define UNIQUE_FUNCTION<%0...%1> %091m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36979)
		#define UNIQUE_FUNCTION<%0...%1> %091n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36980)
		#define UNIQUE_FUNCTION<%0...%1> %091o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36981)
		#define UNIQUE_FUNCTION<%0...%1> %091p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36982)
		#define UNIQUE_FUNCTION<%0...%1> %091q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36983)
		#define UNIQUE_FUNCTION<%0...%1> %091r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (36983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36984)
		#define UNIQUE_FUNCTION<%0...%1> %091s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36985)
		#define UNIQUE_FUNCTION<%0...%1> %091t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36986)
		#define UNIQUE_FUNCTION<%0...%1> %091u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36987)
		#define UNIQUE_FUNCTION<%0...%1> %091v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36988)
		#define UNIQUE_FUNCTION<%0...%1> %091w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36989)
		#define UNIQUE_FUNCTION<%0...%1> %091x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36990)
		#define UNIQUE_FUNCTION<%0...%1> %091y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36991)
		#define UNIQUE_FUNCTION<%0...%1> %091z%1
		#endinput
	#endif
#endif
