static stock const Y_UNIQUE_208896_208959_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_208896_208959
	#undef _inc_y_unique_208896_208959
#endif

#if UNIQUE_SYMBOL < (208903)
	#if UNIQUE_SYMBOL == (208895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208896)
		#define UNIQUE_FUNCTION<%0...%1> %0n00%1
		#endinput
	#if UNIQUE_SYMBOL == (208896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208897)
		#define UNIQUE_FUNCTION<%0...%1> %0n01%1
		#endinput
	#if UNIQUE_SYMBOL == (208897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208898)
		#define UNIQUE_FUNCTION<%0...%1> %0n02%1
		#endinput
	#if UNIQUE_SYMBOL == (208898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208899)
		#define UNIQUE_FUNCTION<%0...%1> %0n03%1
		#endinput
	#if UNIQUE_SYMBOL == (208899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208900)
		#define UNIQUE_FUNCTION<%0...%1> %0n04%1
		#endinput
	#if UNIQUE_SYMBOL == (208900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208901)
		#define UNIQUE_FUNCTION<%0...%1> %0n05%1
		#endinput
	#if UNIQUE_SYMBOL == (208901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208902)
		#define UNIQUE_FUNCTION<%0...%1> %0n06%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208903)
		#define UNIQUE_FUNCTION<%0...%1> %0n07%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (208911)
	#elseif UNIQUE_SYMBOL == (208903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208904)
		#define UNIQUE_FUNCTION<%0...%1> %0n08%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208905)
		#define UNIQUE_FUNCTION<%0...%1> %0n09%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208906)
		#define UNIQUE_FUNCTION<%0...%1> %0n0@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208907)
		#define UNIQUE_FUNCTION<%0...%1> %0n0A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208908)
		#define UNIQUE_FUNCTION<%0...%1> %0n0B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208909)
		#define UNIQUE_FUNCTION<%0...%1> %0n0C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208910)
		#define UNIQUE_FUNCTION<%0...%1> %0n0D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208911)
		#define UNIQUE_FUNCTION<%0...%1> %0n0E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (208919)
	#elseif UNIQUE_SYMBOL == (208911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208912)
		#define UNIQUE_FUNCTION<%0...%1> %0n0F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208913)
		#define UNIQUE_FUNCTION<%0...%1> %0n0G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208914)
		#define UNIQUE_FUNCTION<%0...%1> %0n0H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208915)
		#define UNIQUE_FUNCTION<%0...%1> %0n0I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208916)
		#define UNIQUE_FUNCTION<%0...%1> %0n0J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208917)
		#define UNIQUE_FUNCTION<%0...%1> %0n0K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208918)
		#define UNIQUE_FUNCTION<%0...%1> %0n0L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208919)
		#define UNIQUE_FUNCTION<%0...%1> %0n0M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (208927)
	#elseif UNIQUE_SYMBOL == (208919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208920)
		#define UNIQUE_FUNCTION<%0...%1> %0n0N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208921)
		#define UNIQUE_FUNCTION<%0...%1> %0n0O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208922)
		#define UNIQUE_FUNCTION<%0...%1> %0n0P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208923)
		#define UNIQUE_FUNCTION<%0...%1> %0n0Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208924)
		#define UNIQUE_FUNCTION<%0...%1> %0n0R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208925)
		#define UNIQUE_FUNCTION<%0...%1> %0n0S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208926)
		#define UNIQUE_FUNCTION<%0...%1> %0n0T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208927)
		#define UNIQUE_FUNCTION<%0...%1> %0n0U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (208935)
	#elseif UNIQUE_SYMBOL == (208927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208928)
		#define UNIQUE_FUNCTION<%0...%1> %0n0V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208929)
		#define UNIQUE_FUNCTION<%0...%1> %0n0W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208930)
		#define UNIQUE_FUNCTION<%0...%1> %0n0X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208931)
		#define UNIQUE_FUNCTION<%0...%1> %0n0Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208932)
		#define UNIQUE_FUNCTION<%0...%1> %0n0Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208933)
		#define UNIQUE_FUNCTION<%0...%1> %0n0_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208934)
		#define UNIQUE_FUNCTION<%0...%1> %0n0a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208935)
		#define UNIQUE_FUNCTION<%0...%1> %0n0b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (208943)
	#elseif UNIQUE_SYMBOL == (208935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208936)
		#define UNIQUE_FUNCTION<%0...%1> %0n0c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208937)
		#define UNIQUE_FUNCTION<%0...%1> %0n0d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208938)
		#define UNIQUE_FUNCTION<%0...%1> %0n0e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208939)
		#define UNIQUE_FUNCTION<%0...%1> %0n0f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208940)
		#define UNIQUE_FUNCTION<%0...%1> %0n0g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208941)
		#define UNIQUE_FUNCTION<%0...%1> %0n0h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208942)
		#define UNIQUE_FUNCTION<%0...%1> %0n0i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208943)
		#define UNIQUE_FUNCTION<%0...%1> %0n0j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (208951)
	#elseif UNIQUE_SYMBOL == (208943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208944)
		#define UNIQUE_FUNCTION<%0...%1> %0n0k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208945)
		#define UNIQUE_FUNCTION<%0...%1> %0n0l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208946)
		#define UNIQUE_FUNCTION<%0...%1> %0n0m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208947)
		#define UNIQUE_FUNCTION<%0...%1> %0n0n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208948)
		#define UNIQUE_FUNCTION<%0...%1> %0n0o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208949)
		#define UNIQUE_FUNCTION<%0...%1> %0n0p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208950)
		#define UNIQUE_FUNCTION<%0...%1> %0n0q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208951)
		#define UNIQUE_FUNCTION<%0...%1> %0n0r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (208951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208952)
		#define UNIQUE_FUNCTION<%0...%1> %0n0s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208953)
		#define UNIQUE_FUNCTION<%0...%1> %0n0t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208954)
		#define UNIQUE_FUNCTION<%0...%1> %0n0u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208955)
		#define UNIQUE_FUNCTION<%0...%1> %0n0v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208956)
		#define UNIQUE_FUNCTION<%0...%1> %0n0w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208957)
		#define UNIQUE_FUNCTION<%0...%1> %0n0x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (208957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208958)
		#define UNIQUE_FUNCTION<%0...%1> %0n0y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (208959)
		#define UNIQUE_FUNCTION<%0...%1> %0n0z%1
		#endinput
	#endif
#endif
