static stock const Y_UNIQUE_202624_202687_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_202624_202687
	#undef _inc_y_unique_202624_202687
#endif

#if UNIQUE_SYMBOL < (202631)
	#if UNIQUE_SYMBOL == (202623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202624)
		#define UNIQUE_FUNCTION<%0...%1> %0lT0%1
		#endinput
	#if UNIQUE_SYMBOL == (202624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202625)
		#define UNIQUE_FUNCTION<%0...%1> %0lT1%1
		#endinput
	#if UNIQUE_SYMBOL == (202625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202626)
		#define UNIQUE_FUNCTION<%0...%1> %0lT2%1
		#endinput
	#if UNIQUE_SYMBOL == (202626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202627)
		#define UNIQUE_FUNCTION<%0...%1> %0lT3%1
		#endinput
	#if UNIQUE_SYMBOL == (202627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202628)
		#define UNIQUE_FUNCTION<%0...%1> %0lT4%1
		#endinput
	#if UNIQUE_SYMBOL == (202628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202629)
		#define UNIQUE_FUNCTION<%0...%1> %0lT5%1
		#endinput
	#if UNIQUE_SYMBOL == (202629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202630)
		#define UNIQUE_FUNCTION<%0...%1> %0lT6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202631)
		#define UNIQUE_FUNCTION<%0...%1> %0lT7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (202639)
	#elseif UNIQUE_SYMBOL == (202631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202632)
		#define UNIQUE_FUNCTION<%0...%1> %0lT8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202633)
		#define UNIQUE_FUNCTION<%0...%1> %0lT9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202634)
		#define UNIQUE_FUNCTION<%0...%1> %0lT@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202635)
		#define UNIQUE_FUNCTION<%0...%1> %0lTA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202636)
		#define UNIQUE_FUNCTION<%0...%1> %0lTB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202637)
		#define UNIQUE_FUNCTION<%0...%1> %0lTC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202638)
		#define UNIQUE_FUNCTION<%0...%1> %0lTD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202639)
		#define UNIQUE_FUNCTION<%0...%1> %0lTE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (202647)
	#elseif UNIQUE_SYMBOL == (202639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202640)
		#define UNIQUE_FUNCTION<%0...%1> %0lTF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202641)
		#define UNIQUE_FUNCTION<%0...%1> %0lTG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202642)
		#define UNIQUE_FUNCTION<%0...%1> %0lTH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202643)
		#define UNIQUE_FUNCTION<%0...%1> %0lTI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202644)
		#define UNIQUE_FUNCTION<%0...%1> %0lTJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202645)
		#define UNIQUE_FUNCTION<%0...%1> %0lTK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202646)
		#define UNIQUE_FUNCTION<%0...%1> %0lTL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202647)
		#define UNIQUE_FUNCTION<%0...%1> %0lTM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (202655)
	#elseif UNIQUE_SYMBOL == (202647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202648)
		#define UNIQUE_FUNCTION<%0...%1> %0lTN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202649)
		#define UNIQUE_FUNCTION<%0...%1> %0lTO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202650)
		#define UNIQUE_FUNCTION<%0...%1> %0lTP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202651)
		#define UNIQUE_FUNCTION<%0...%1> %0lTQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202652)
		#define UNIQUE_FUNCTION<%0...%1> %0lTR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202653)
		#define UNIQUE_FUNCTION<%0...%1> %0lTS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202654)
		#define UNIQUE_FUNCTION<%0...%1> %0lTT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202655)
		#define UNIQUE_FUNCTION<%0...%1> %0lTU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (202663)
	#elseif UNIQUE_SYMBOL == (202655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202656)
		#define UNIQUE_FUNCTION<%0...%1> %0lTV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202657)
		#define UNIQUE_FUNCTION<%0...%1> %0lTW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202658)
		#define UNIQUE_FUNCTION<%0...%1> %0lTX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202659)
		#define UNIQUE_FUNCTION<%0...%1> %0lTY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202660)
		#define UNIQUE_FUNCTION<%0...%1> %0lTZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202661)
		#define UNIQUE_FUNCTION<%0...%1> %0lT_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202662)
		#define UNIQUE_FUNCTION<%0...%1> %0lTa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202663)
		#define UNIQUE_FUNCTION<%0...%1> %0lTb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (202671)
	#elseif UNIQUE_SYMBOL == (202663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202664)
		#define UNIQUE_FUNCTION<%0...%1> %0lTc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202665)
		#define UNIQUE_FUNCTION<%0...%1> %0lTd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202666)
		#define UNIQUE_FUNCTION<%0...%1> %0lTe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202667)
		#define UNIQUE_FUNCTION<%0...%1> %0lTf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202668)
		#define UNIQUE_FUNCTION<%0...%1> %0lTg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202669)
		#define UNIQUE_FUNCTION<%0...%1> %0lTh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202670)
		#define UNIQUE_FUNCTION<%0...%1> %0lTi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202671)
		#define UNIQUE_FUNCTION<%0...%1> %0lTj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (202679)
	#elseif UNIQUE_SYMBOL == (202671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202672)
		#define UNIQUE_FUNCTION<%0...%1> %0lTk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202673)
		#define UNIQUE_FUNCTION<%0...%1> %0lTl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202674)
		#define UNIQUE_FUNCTION<%0...%1> %0lTm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202675)
		#define UNIQUE_FUNCTION<%0...%1> %0lTn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202676)
		#define UNIQUE_FUNCTION<%0...%1> %0lTo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202677)
		#define UNIQUE_FUNCTION<%0...%1> %0lTp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202678)
		#define UNIQUE_FUNCTION<%0...%1> %0lTq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202679)
		#define UNIQUE_FUNCTION<%0...%1> %0lTr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (202679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202680)
		#define UNIQUE_FUNCTION<%0...%1> %0lTs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202681)
		#define UNIQUE_FUNCTION<%0...%1> %0lTt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202682)
		#define UNIQUE_FUNCTION<%0...%1> %0lTu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202683)
		#define UNIQUE_FUNCTION<%0...%1> %0lTv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202684)
		#define UNIQUE_FUNCTION<%0...%1> %0lTw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202685)
		#define UNIQUE_FUNCTION<%0...%1> %0lTx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (202685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202686)
		#define UNIQUE_FUNCTION<%0...%1> %0lTy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (202687)
		#define UNIQUE_FUNCTION<%0...%1> %0lTz%1
		#endinput
	#endif
#endif
