static stock const Y_UNIQUE_058880_058943_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_058880_058943
	#undef _inc_y_unique_058880_058943
#endif

#if UNIQUE_SYMBOL < (58887)
	#if UNIQUE_SYMBOL == (58879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58880)
		#define UNIQUE_FUNCTION<%0...%1> %0DN0%1
		#endinput
	#if UNIQUE_SYMBOL == (58880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58881)
		#define UNIQUE_FUNCTION<%0...%1> %0DN1%1
		#endinput
	#if UNIQUE_SYMBOL == (58881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58882)
		#define UNIQUE_FUNCTION<%0...%1> %0DN2%1
		#endinput
	#if UNIQUE_SYMBOL == (58882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58883)
		#define UNIQUE_FUNCTION<%0...%1> %0DN3%1
		#endinput
	#if UNIQUE_SYMBOL == (58883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58884)
		#define UNIQUE_FUNCTION<%0...%1> %0DN4%1
		#endinput
	#if UNIQUE_SYMBOL == (58884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58885)
		#define UNIQUE_FUNCTION<%0...%1> %0DN5%1
		#endinput
	#if UNIQUE_SYMBOL == (58885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58886)
		#define UNIQUE_FUNCTION<%0...%1> %0DN6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58887)
		#define UNIQUE_FUNCTION<%0...%1> %0DN7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58895)
	#elseif UNIQUE_SYMBOL == (58887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58888)
		#define UNIQUE_FUNCTION<%0...%1> %0DN8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58889)
		#define UNIQUE_FUNCTION<%0...%1> %0DN9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58890)
		#define UNIQUE_FUNCTION<%0...%1> %0DN@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58891)
		#define UNIQUE_FUNCTION<%0...%1> %0DNA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58892)
		#define UNIQUE_FUNCTION<%0...%1> %0DNB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58893)
		#define UNIQUE_FUNCTION<%0...%1> %0DNC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58894)
		#define UNIQUE_FUNCTION<%0...%1> %0DND%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58895)
		#define UNIQUE_FUNCTION<%0...%1> %0DNE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58903)
	#elseif UNIQUE_SYMBOL == (58895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58896)
		#define UNIQUE_FUNCTION<%0...%1> %0DNF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58897)
		#define UNIQUE_FUNCTION<%0...%1> %0DNG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58898)
		#define UNIQUE_FUNCTION<%0...%1> %0DNH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58899)
		#define UNIQUE_FUNCTION<%0...%1> %0DNI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58900)
		#define UNIQUE_FUNCTION<%0...%1> %0DNJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58901)
		#define UNIQUE_FUNCTION<%0...%1> %0DNK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58902)
		#define UNIQUE_FUNCTION<%0...%1> %0DNL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58903)
		#define UNIQUE_FUNCTION<%0...%1> %0DNM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58911)
	#elseif UNIQUE_SYMBOL == (58903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58904)
		#define UNIQUE_FUNCTION<%0...%1> %0DNN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58905)
		#define UNIQUE_FUNCTION<%0...%1> %0DNO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58906)
		#define UNIQUE_FUNCTION<%0...%1> %0DNP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58907)
		#define UNIQUE_FUNCTION<%0...%1> %0DNQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58908)
		#define UNIQUE_FUNCTION<%0...%1> %0DNR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58909)
		#define UNIQUE_FUNCTION<%0...%1> %0DNS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58910)
		#define UNIQUE_FUNCTION<%0...%1> %0DNT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58911)
		#define UNIQUE_FUNCTION<%0...%1> %0DNU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58919)
	#elseif UNIQUE_SYMBOL == (58911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58912)
		#define UNIQUE_FUNCTION<%0...%1> %0DNV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58913)
		#define UNIQUE_FUNCTION<%0...%1> %0DNW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58914)
		#define UNIQUE_FUNCTION<%0...%1> %0DNX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58915)
		#define UNIQUE_FUNCTION<%0...%1> %0DNY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58916)
		#define UNIQUE_FUNCTION<%0...%1> %0DNZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58917)
		#define UNIQUE_FUNCTION<%0...%1> %0DN_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58918)
		#define UNIQUE_FUNCTION<%0...%1> %0DNa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58919)
		#define UNIQUE_FUNCTION<%0...%1> %0DNb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58927)
	#elseif UNIQUE_SYMBOL == (58919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58920)
		#define UNIQUE_FUNCTION<%0...%1> %0DNc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58921)
		#define UNIQUE_FUNCTION<%0...%1> %0DNd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58922)
		#define UNIQUE_FUNCTION<%0...%1> %0DNe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58923)
		#define UNIQUE_FUNCTION<%0...%1> %0DNf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58924)
		#define UNIQUE_FUNCTION<%0...%1> %0DNg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58925)
		#define UNIQUE_FUNCTION<%0...%1> %0DNh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58926)
		#define UNIQUE_FUNCTION<%0...%1> %0DNi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58927)
		#define UNIQUE_FUNCTION<%0...%1> %0DNj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (58935)
	#elseif UNIQUE_SYMBOL == (58927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58928)
		#define UNIQUE_FUNCTION<%0...%1> %0DNk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58929)
		#define UNIQUE_FUNCTION<%0...%1> %0DNl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58930)
		#define UNIQUE_FUNCTION<%0...%1> %0DNm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58931)
		#define UNIQUE_FUNCTION<%0...%1> %0DNn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58932)
		#define UNIQUE_FUNCTION<%0...%1> %0DNo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58933)
		#define UNIQUE_FUNCTION<%0...%1> %0DNp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58934)
		#define UNIQUE_FUNCTION<%0...%1> %0DNq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58935)
		#define UNIQUE_FUNCTION<%0...%1> %0DNr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (58935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58936)
		#define UNIQUE_FUNCTION<%0...%1> %0DNs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58937)
		#define UNIQUE_FUNCTION<%0...%1> %0DNt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58938)
		#define UNIQUE_FUNCTION<%0...%1> %0DNu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58939)
		#define UNIQUE_FUNCTION<%0...%1> %0DNv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58940)
		#define UNIQUE_FUNCTION<%0...%1> %0DNw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58941)
		#define UNIQUE_FUNCTION<%0...%1> %0DNx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (58941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58942)
		#define UNIQUE_FUNCTION<%0...%1> %0DNy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (58943)
		#define UNIQUE_FUNCTION<%0...%1> %0DNz%1
		#endinput
	#endif
#endif
