static stock const Y_UNIQUE_099904_099967_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_099904_099967
	#undef _inc_y_unique_099904_099967
#endif

#if UNIQUE_SYMBOL < (99911)
	#if UNIQUE_SYMBOL == (99903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99904)
		#define UNIQUE_FUNCTION<%0...%1> %0NO0%1
		#endinput
	#if UNIQUE_SYMBOL == (99904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99905)
		#define UNIQUE_FUNCTION<%0...%1> %0NO1%1
		#endinput
	#if UNIQUE_SYMBOL == (99905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99906)
		#define UNIQUE_FUNCTION<%0...%1> %0NO2%1
		#endinput
	#if UNIQUE_SYMBOL == (99906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99907)
		#define UNIQUE_FUNCTION<%0...%1> %0NO3%1
		#endinput
	#if UNIQUE_SYMBOL == (99907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99908)
		#define UNIQUE_FUNCTION<%0...%1> %0NO4%1
		#endinput
	#if UNIQUE_SYMBOL == (99908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99909)
		#define UNIQUE_FUNCTION<%0...%1> %0NO5%1
		#endinput
	#if UNIQUE_SYMBOL == (99909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99910)
		#define UNIQUE_FUNCTION<%0...%1> %0NO6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99911)
		#define UNIQUE_FUNCTION<%0...%1> %0NO7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (99919)
	#elseif UNIQUE_SYMBOL == (99911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99912)
		#define UNIQUE_FUNCTION<%0...%1> %0NO8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99913)
		#define UNIQUE_FUNCTION<%0...%1> %0NO9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99914)
		#define UNIQUE_FUNCTION<%0...%1> %0NO@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99915)
		#define UNIQUE_FUNCTION<%0...%1> %0NOA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99916)
		#define UNIQUE_FUNCTION<%0...%1> %0NOB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99917)
		#define UNIQUE_FUNCTION<%0...%1> %0NOC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99918)
		#define UNIQUE_FUNCTION<%0...%1> %0NOD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99919)
		#define UNIQUE_FUNCTION<%0...%1> %0NOE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (99927)
	#elseif UNIQUE_SYMBOL == (99919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99920)
		#define UNIQUE_FUNCTION<%0...%1> %0NOF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99921)
		#define UNIQUE_FUNCTION<%0...%1> %0NOG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99922)
		#define UNIQUE_FUNCTION<%0...%1> %0NOH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99923)
		#define UNIQUE_FUNCTION<%0...%1> %0NOI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99924)
		#define UNIQUE_FUNCTION<%0...%1> %0NOJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99925)
		#define UNIQUE_FUNCTION<%0...%1> %0NOK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99926)
		#define UNIQUE_FUNCTION<%0...%1> %0NOL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99927)
		#define UNIQUE_FUNCTION<%0...%1> %0NOM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (99935)
	#elseif UNIQUE_SYMBOL == (99927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99928)
		#define UNIQUE_FUNCTION<%0...%1> %0NON%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99929)
		#define UNIQUE_FUNCTION<%0...%1> %0NOO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99930)
		#define UNIQUE_FUNCTION<%0...%1> %0NOP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99931)
		#define UNIQUE_FUNCTION<%0...%1> %0NOQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99932)
		#define UNIQUE_FUNCTION<%0...%1> %0NOR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99933)
		#define UNIQUE_FUNCTION<%0...%1> %0NOS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99934)
		#define UNIQUE_FUNCTION<%0...%1> %0NOT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99935)
		#define UNIQUE_FUNCTION<%0...%1> %0NOU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (99943)
	#elseif UNIQUE_SYMBOL == (99935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99936)
		#define UNIQUE_FUNCTION<%0...%1> %0NOV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99937)
		#define UNIQUE_FUNCTION<%0...%1> %0NOW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99938)
		#define UNIQUE_FUNCTION<%0...%1> %0NOX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99939)
		#define UNIQUE_FUNCTION<%0...%1> %0NOY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99940)
		#define UNIQUE_FUNCTION<%0...%1> %0NOZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99941)
		#define UNIQUE_FUNCTION<%0...%1> %0NO_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99942)
		#define UNIQUE_FUNCTION<%0...%1> %0NOa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99943)
		#define UNIQUE_FUNCTION<%0...%1> %0NOb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (99951)
	#elseif UNIQUE_SYMBOL == (99943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99944)
		#define UNIQUE_FUNCTION<%0...%1> %0NOc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99945)
		#define UNIQUE_FUNCTION<%0...%1> %0NOd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99946)
		#define UNIQUE_FUNCTION<%0...%1> %0NOe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99947)
		#define UNIQUE_FUNCTION<%0...%1> %0NOf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99948)
		#define UNIQUE_FUNCTION<%0...%1> %0NOg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99949)
		#define UNIQUE_FUNCTION<%0...%1> %0NOh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99950)
		#define UNIQUE_FUNCTION<%0...%1> %0NOi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99951)
		#define UNIQUE_FUNCTION<%0...%1> %0NOj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (99959)
	#elseif UNIQUE_SYMBOL == (99951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99952)
		#define UNIQUE_FUNCTION<%0...%1> %0NOk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99953)
		#define UNIQUE_FUNCTION<%0...%1> %0NOl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99954)
		#define UNIQUE_FUNCTION<%0...%1> %0NOm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99955)
		#define UNIQUE_FUNCTION<%0...%1> %0NOn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99956)
		#define UNIQUE_FUNCTION<%0...%1> %0NOo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99957)
		#define UNIQUE_FUNCTION<%0...%1> %0NOp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99958)
		#define UNIQUE_FUNCTION<%0...%1> %0NOq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99959)
		#define UNIQUE_FUNCTION<%0...%1> %0NOr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (99959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99960)
		#define UNIQUE_FUNCTION<%0...%1> %0NOs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99961)
		#define UNIQUE_FUNCTION<%0...%1> %0NOt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99962)
		#define UNIQUE_FUNCTION<%0...%1> %0NOu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99963)
		#define UNIQUE_FUNCTION<%0...%1> %0NOv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99964)
		#define UNIQUE_FUNCTION<%0...%1> %0NOw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99965)
		#define UNIQUE_FUNCTION<%0...%1> %0NOx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (99965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99966)
		#define UNIQUE_FUNCTION<%0...%1> %0NOy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (99967)
		#define UNIQUE_FUNCTION<%0...%1> %0NOz%1
		#endinput
	#endif
#endif
