static stock const Y_UNIQUE_024960_025023_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_024960_025023
	#undef _inc_y_unique_024960_025023
#endif

#if UNIQUE_SYMBOL < (24967)
	#if UNIQUE_SYMBOL == (24959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24960)
		#define UNIQUE_FUNCTION<%0...%1> %0660%1
		#endinput
	#if UNIQUE_SYMBOL == (24960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24961)
		#define UNIQUE_FUNCTION<%0...%1> %0661%1
		#endinput
	#if UNIQUE_SYMBOL == (24961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24962)
		#define UNIQUE_FUNCTION<%0...%1> %0662%1
		#endinput
	#if UNIQUE_SYMBOL == (24962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24963)
		#define UNIQUE_FUNCTION<%0...%1> %0663%1
		#endinput
	#if UNIQUE_SYMBOL == (24963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24964)
		#define UNIQUE_FUNCTION<%0...%1> %0664%1
		#endinput
	#if UNIQUE_SYMBOL == (24964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24965)
		#define UNIQUE_FUNCTION<%0...%1> %0665%1
		#endinput
	#if UNIQUE_SYMBOL == (24965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24966)
		#define UNIQUE_FUNCTION<%0...%1> %0666%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24967)
		#define UNIQUE_FUNCTION<%0...%1> %0667%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24975)
	#elseif UNIQUE_SYMBOL == (24967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24968)
		#define UNIQUE_FUNCTION<%0...%1> %0668%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24969)
		#define UNIQUE_FUNCTION<%0...%1> %0669%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24970)
		#define UNIQUE_FUNCTION<%0...%1> %066@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24971)
		#define UNIQUE_FUNCTION<%0...%1> %066A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24972)
		#define UNIQUE_FUNCTION<%0...%1> %066B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24973)
		#define UNIQUE_FUNCTION<%0...%1> %066C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24974)
		#define UNIQUE_FUNCTION<%0...%1> %066D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24975)
		#define UNIQUE_FUNCTION<%0...%1> %066E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24983)
	#elseif UNIQUE_SYMBOL == (24975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24976)
		#define UNIQUE_FUNCTION<%0...%1> %066F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24977)
		#define UNIQUE_FUNCTION<%0...%1> %066G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24978)
		#define UNIQUE_FUNCTION<%0...%1> %066H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24979)
		#define UNIQUE_FUNCTION<%0...%1> %066I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24980)
		#define UNIQUE_FUNCTION<%0...%1> %066J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24981)
		#define UNIQUE_FUNCTION<%0...%1> %066K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24982)
		#define UNIQUE_FUNCTION<%0...%1> %066L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24983)
		#define UNIQUE_FUNCTION<%0...%1> %066M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24991)
	#elseif UNIQUE_SYMBOL == (24983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24984)
		#define UNIQUE_FUNCTION<%0...%1> %066N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24985)
		#define UNIQUE_FUNCTION<%0...%1> %066O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24986)
		#define UNIQUE_FUNCTION<%0...%1> %066P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24987)
		#define UNIQUE_FUNCTION<%0...%1> %066Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24988)
		#define UNIQUE_FUNCTION<%0...%1> %066R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24989)
		#define UNIQUE_FUNCTION<%0...%1> %066S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24990)
		#define UNIQUE_FUNCTION<%0...%1> %066T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24991)
		#define UNIQUE_FUNCTION<%0...%1> %066U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24999)
	#elseif UNIQUE_SYMBOL == (24991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24992)
		#define UNIQUE_FUNCTION<%0...%1> %066V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24993)
		#define UNIQUE_FUNCTION<%0...%1> %066W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24994)
		#define UNIQUE_FUNCTION<%0...%1> %066X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24995)
		#define UNIQUE_FUNCTION<%0...%1> %066Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24996)
		#define UNIQUE_FUNCTION<%0...%1> %066Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24997)
		#define UNIQUE_FUNCTION<%0...%1> %066_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24998)
		#define UNIQUE_FUNCTION<%0...%1> %066a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24999)
		#define UNIQUE_FUNCTION<%0...%1> %066b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25007)
	#elseif UNIQUE_SYMBOL == (24999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25000)
		#define UNIQUE_FUNCTION<%0...%1> %066c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25001)
		#define UNIQUE_FUNCTION<%0...%1> %066d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25002)
		#define UNIQUE_FUNCTION<%0...%1> %066e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25003)
		#define UNIQUE_FUNCTION<%0...%1> %066f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25004)
		#define UNIQUE_FUNCTION<%0...%1> %066g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25005)
		#define UNIQUE_FUNCTION<%0...%1> %066h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25006)
		#define UNIQUE_FUNCTION<%0...%1> %066i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25007)
		#define UNIQUE_FUNCTION<%0...%1> %066j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25015)
	#elseif UNIQUE_SYMBOL == (25007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25008)
		#define UNIQUE_FUNCTION<%0...%1> %066k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25009)
		#define UNIQUE_FUNCTION<%0...%1> %066l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25010)
		#define UNIQUE_FUNCTION<%0...%1> %066m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25011)
		#define UNIQUE_FUNCTION<%0...%1> %066n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25012)
		#define UNIQUE_FUNCTION<%0...%1> %066o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25013)
		#define UNIQUE_FUNCTION<%0...%1> %066p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25014)
		#define UNIQUE_FUNCTION<%0...%1> %066q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25015)
		#define UNIQUE_FUNCTION<%0...%1> %066r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (25015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25016)
		#define UNIQUE_FUNCTION<%0...%1> %066s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25017)
		#define UNIQUE_FUNCTION<%0...%1> %066t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25018)
		#define UNIQUE_FUNCTION<%0...%1> %066u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25019)
		#define UNIQUE_FUNCTION<%0...%1> %066v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25020)
		#define UNIQUE_FUNCTION<%0...%1> %066w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25021)
		#define UNIQUE_FUNCTION<%0...%1> %066x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25022)
		#define UNIQUE_FUNCTION<%0...%1> %066y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25023)
		#define UNIQUE_FUNCTION<%0...%1> %066z%1
		#endinput
	#endif
#endif
