static stock const Y_UNIQUE_081600_081663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_081600_081663
	#undef _inc_y_unique_081600_081663
#endif

#if UNIQUE_SYMBOL < (81607)
	#if UNIQUE_SYMBOL == (81599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81600)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv0%1
		#endinput
	#if UNIQUE_SYMBOL == (81600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81601)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv1%1
		#endinput
	#if UNIQUE_SYMBOL == (81601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81602)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv2%1
		#endinput
	#if UNIQUE_SYMBOL == (81602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81603)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv3%1
		#endinput
	#if UNIQUE_SYMBOL == (81603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81604)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv4%1
		#endinput
	#if UNIQUE_SYMBOL == (81604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81605)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv5%1
		#endinput
	#if UNIQUE_SYMBOL == (81605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81606)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81607)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81615)
	#elseif UNIQUE_SYMBOL == (81607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81608)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81609)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81610)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81611)
		#define UNIQUE_FUNCTION<%0...%1> %0IvA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81612)
		#define UNIQUE_FUNCTION<%0...%1> %0IvB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81613)
		#define UNIQUE_FUNCTION<%0...%1> %0IvC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81614)
		#define UNIQUE_FUNCTION<%0...%1> %0IvD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81615)
		#define UNIQUE_FUNCTION<%0...%1> %0IvE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81623)
	#elseif UNIQUE_SYMBOL == (81615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81616)
		#define UNIQUE_FUNCTION<%0...%1> %0IvF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81617)
		#define UNIQUE_FUNCTION<%0...%1> %0IvG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81618)
		#define UNIQUE_FUNCTION<%0...%1> %0IvH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81619)
		#define UNIQUE_FUNCTION<%0...%1> %0IvI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81620)
		#define UNIQUE_FUNCTION<%0...%1> %0IvJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81621)
		#define UNIQUE_FUNCTION<%0...%1> %0IvK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81622)
		#define UNIQUE_FUNCTION<%0...%1> %0IvL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81623)
		#define UNIQUE_FUNCTION<%0...%1> %0IvM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81631)
	#elseif UNIQUE_SYMBOL == (81623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81624)
		#define UNIQUE_FUNCTION<%0...%1> %0IvN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81625)
		#define UNIQUE_FUNCTION<%0...%1> %0IvO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81626)
		#define UNIQUE_FUNCTION<%0...%1> %0IvP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81627)
		#define UNIQUE_FUNCTION<%0...%1> %0IvQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81628)
		#define UNIQUE_FUNCTION<%0...%1> %0IvR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81629)
		#define UNIQUE_FUNCTION<%0...%1> %0IvS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81630)
		#define UNIQUE_FUNCTION<%0...%1> %0IvT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81631)
		#define UNIQUE_FUNCTION<%0...%1> %0IvU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81639)
	#elseif UNIQUE_SYMBOL == (81631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81632)
		#define UNIQUE_FUNCTION<%0...%1> %0IvV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81633)
		#define UNIQUE_FUNCTION<%0...%1> %0IvW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81634)
		#define UNIQUE_FUNCTION<%0...%1> %0IvX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81635)
		#define UNIQUE_FUNCTION<%0...%1> %0IvY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81636)
		#define UNIQUE_FUNCTION<%0...%1> %0IvZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81637)
		#define UNIQUE_FUNCTION<%0...%1> %0Iv_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81638)
		#define UNIQUE_FUNCTION<%0...%1> %0Iva%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81639)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81647)
	#elseif UNIQUE_SYMBOL == (81639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81640)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81641)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81642)
		#define UNIQUE_FUNCTION<%0...%1> %0Ive%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81643)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81644)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81645)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81646)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81647)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (81655)
	#elseif UNIQUE_SYMBOL == (81647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81648)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81649)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81650)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81651)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81652)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81653)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81654)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81655)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (81655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81656)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81657)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81658)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81659)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81660)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81661)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (81661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81662)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (81663)
		#define UNIQUE_FUNCTION<%0...%1> %0Ivz%1
		#endinput
	#endif
#endif
