static stock const Y_UNIQUE_198016_198079_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_198016_198079
	#undef _inc_y_unique_198016_198079
#endif

#if UNIQUE_SYMBOL < (198023)
	#if UNIQUE_SYMBOL == (198015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198016)
		#define UNIQUE_FUNCTION<%0...%1> %0kL0%1
		#endinput
	#if UNIQUE_SYMBOL == (198016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198017)
		#define UNIQUE_FUNCTION<%0...%1> %0kL1%1
		#endinput
	#if UNIQUE_SYMBOL == (198017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198018)
		#define UNIQUE_FUNCTION<%0...%1> %0kL2%1
		#endinput
	#if UNIQUE_SYMBOL == (198018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198019)
		#define UNIQUE_FUNCTION<%0...%1> %0kL3%1
		#endinput
	#if UNIQUE_SYMBOL == (198019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198020)
		#define UNIQUE_FUNCTION<%0...%1> %0kL4%1
		#endinput
	#if UNIQUE_SYMBOL == (198020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198021)
		#define UNIQUE_FUNCTION<%0...%1> %0kL5%1
		#endinput
	#if UNIQUE_SYMBOL == (198021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198022)
		#define UNIQUE_FUNCTION<%0...%1> %0kL6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198023)
		#define UNIQUE_FUNCTION<%0...%1> %0kL7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (198031)
	#elseif UNIQUE_SYMBOL == (198023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198024)
		#define UNIQUE_FUNCTION<%0...%1> %0kL8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198025)
		#define UNIQUE_FUNCTION<%0...%1> %0kL9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198026)
		#define UNIQUE_FUNCTION<%0...%1> %0kL@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198027)
		#define UNIQUE_FUNCTION<%0...%1> %0kLA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198028)
		#define UNIQUE_FUNCTION<%0...%1> %0kLB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198029)
		#define UNIQUE_FUNCTION<%0...%1> %0kLC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198030)
		#define UNIQUE_FUNCTION<%0...%1> %0kLD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198031)
		#define UNIQUE_FUNCTION<%0...%1> %0kLE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (198039)
	#elseif UNIQUE_SYMBOL == (198031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198032)
		#define UNIQUE_FUNCTION<%0...%1> %0kLF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198033)
		#define UNIQUE_FUNCTION<%0...%1> %0kLG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198034)
		#define UNIQUE_FUNCTION<%0...%1> %0kLH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198035)
		#define UNIQUE_FUNCTION<%0...%1> %0kLI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198036)
		#define UNIQUE_FUNCTION<%0...%1> %0kLJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198037)
		#define UNIQUE_FUNCTION<%0...%1> %0kLK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198038)
		#define UNIQUE_FUNCTION<%0...%1> %0kLL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198039)
		#define UNIQUE_FUNCTION<%0...%1> %0kLM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (198047)
	#elseif UNIQUE_SYMBOL == (198039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198040)
		#define UNIQUE_FUNCTION<%0...%1> %0kLN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198041)
		#define UNIQUE_FUNCTION<%0...%1> %0kLO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198042)
		#define UNIQUE_FUNCTION<%0...%1> %0kLP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198043)
		#define UNIQUE_FUNCTION<%0...%1> %0kLQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198044)
		#define UNIQUE_FUNCTION<%0...%1> %0kLR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198045)
		#define UNIQUE_FUNCTION<%0...%1> %0kLS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198046)
		#define UNIQUE_FUNCTION<%0...%1> %0kLT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198047)
		#define UNIQUE_FUNCTION<%0...%1> %0kLU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (198055)
	#elseif UNIQUE_SYMBOL == (198047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198048)
		#define UNIQUE_FUNCTION<%0...%1> %0kLV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198049)
		#define UNIQUE_FUNCTION<%0...%1> %0kLW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198050)
		#define UNIQUE_FUNCTION<%0...%1> %0kLX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198051)
		#define UNIQUE_FUNCTION<%0...%1> %0kLY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198052)
		#define UNIQUE_FUNCTION<%0...%1> %0kLZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198053)
		#define UNIQUE_FUNCTION<%0...%1> %0kL_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198054)
		#define UNIQUE_FUNCTION<%0...%1> %0kLa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198055)
		#define UNIQUE_FUNCTION<%0...%1> %0kLb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (198063)
	#elseif UNIQUE_SYMBOL == (198055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198056)
		#define UNIQUE_FUNCTION<%0...%1> %0kLc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198057)
		#define UNIQUE_FUNCTION<%0...%1> %0kLd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198058)
		#define UNIQUE_FUNCTION<%0...%1> %0kLe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198059)
		#define UNIQUE_FUNCTION<%0...%1> %0kLf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198060)
		#define UNIQUE_FUNCTION<%0...%1> %0kLg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198061)
		#define UNIQUE_FUNCTION<%0...%1> %0kLh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198062)
		#define UNIQUE_FUNCTION<%0...%1> %0kLi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198063)
		#define UNIQUE_FUNCTION<%0...%1> %0kLj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (198071)
	#elseif UNIQUE_SYMBOL == (198063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198064)
		#define UNIQUE_FUNCTION<%0...%1> %0kLk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198065)
		#define UNIQUE_FUNCTION<%0...%1> %0kLl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198066)
		#define UNIQUE_FUNCTION<%0...%1> %0kLm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198067)
		#define UNIQUE_FUNCTION<%0...%1> %0kLn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198068)
		#define UNIQUE_FUNCTION<%0...%1> %0kLo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198069)
		#define UNIQUE_FUNCTION<%0...%1> %0kLp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198070)
		#define UNIQUE_FUNCTION<%0...%1> %0kLq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198071)
		#define UNIQUE_FUNCTION<%0...%1> %0kLr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (198071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198072)
		#define UNIQUE_FUNCTION<%0...%1> %0kLs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198073)
		#define UNIQUE_FUNCTION<%0...%1> %0kLt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198074)
		#define UNIQUE_FUNCTION<%0...%1> %0kLu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198075)
		#define UNIQUE_FUNCTION<%0...%1> %0kLv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198076)
		#define UNIQUE_FUNCTION<%0...%1> %0kLw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198077)
		#define UNIQUE_FUNCTION<%0...%1> %0kLx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (198077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198078)
		#define UNIQUE_FUNCTION<%0...%1> %0kLy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (198079)
		#define UNIQUE_FUNCTION<%0...%1> %0kLz%1
		#endinput
	#endif
#endif
