static stock const Y_UNIQUE_163840_163903_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_163840_163903
	#undef _inc_y_unique_163840_163903
#endif

#if UNIQUE_SYMBOL < (163847)
	#if UNIQUE_SYMBOL == (163839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163840)
		#define UNIQUE_FUNCTION<%0...%1> %0c00%1
		#endinput
	#if UNIQUE_SYMBOL == (163840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163841)
		#define UNIQUE_FUNCTION<%0...%1> %0c01%1
		#endinput
	#if UNIQUE_SYMBOL == (163841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163842)
		#define UNIQUE_FUNCTION<%0...%1> %0c02%1
		#endinput
	#if UNIQUE_SYMBOL == (163842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163843)
		#define UNIQUE_FUNCTION<%0...%1> %0c03%1
		#endinput
	#if UNIQUE_SYMBOL == (163843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163844)
		#define UNIQUE_FUNCTION<%0...%1> %0c04%1
		#endinput
	#if UNIQUE_SYMBOL == (163844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163845)
		#define UNIQUE_FUNCTION<%0...%1> %0c05%1
		#endinput
	#if UNIQUE_SYMBOL == (163845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163846)
		#define UNIQUE_FUNCTION<%0...%1> %0c06%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163847)
		#define UNIQUE_FUNCTION<%0...%1> %0c07%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (163855)
	#elseif UNIQUE_SYMBOL == (163847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163848)
		#define UNIQUE_FUNCTION<%0...%1> %0c08%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163849)
		#define UNIQUE_FUNCTION<%0...%1> %0c09%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163850)
		#define UNIQUE_FUNCTION<%0...%1> %0c0@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163851)
		#define UNIQUE_FUNCTION<%0...%1> %0c0A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163852)
		#define UNIQUE_FUNCTION<%0...%1> %0c0B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163853)
		#define UNIQUE_FUNCTION<%0...%1> %0c0C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163854)
		#define UNIQUE_FUNCTION<%0...%1> %0c0D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163855)
		#define UNIQUE_FUNCTION<%0...%1> %0c0E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (163863)
	#elseif UNIQUE_SYMBOL == (163855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163856)
		#define UNIQUE_FUNCTION<%0...%1> %0c0F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163857)
		#define UNIQUE_FUNCTION<%0...%1> %0c0G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163858)
		#define UNIQUE_FUNCTION<%0...%1> %0c0H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163859)
		#define UNIQUE_FUNCTION<%0...%1> %0c0I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163860)
		#define UNIQUE_FUNCTION<%0...%1> %0c0J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163861)
		#define UNIQUE_FUNCTION<%0...%1> %0c0K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163862)
		#define UNIQUE_FUNCTION<%0...%1> %0c0L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163863)
		#define UNIQUE_FUNCTION<%0...%1> %0c0M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (163871)
	#elseif UNIQUE_SYMBOL == (163863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163864)
		#define UNIQUE_FUNCTION<%0...%1> %0c0N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163865)
		#define UNIQUE_FUNCTION<%0...%1> %0c0O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163866)
		#define UNIQUE_FUNCTION<%0...%1> %0c0P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163867)
		#define UNIQUE_FUNCTION<%0...%1> %0c0Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163868)
		#define UNIQUE_FUNCTION<%0...%1> %0c0R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163869)
		#define UNIQUE_FUNCTION<%0...%1> %0c0S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163870)
		#define UNIQUE_FUNCTION<%0...%1> %0c0T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163871)
		#define UNIQUE_FUNCTION<%0...%1> %0c0U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (163879)
	#elseif UNIQUE_SYMBOL == (163871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163872)
		#define UNIQUE_FUNCTION<%0...%1> %0c0V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163873)
		#define UNIQUE_FUNCTION<%0...%1> %0c0W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163874)
		#define UNIQUE_FUNCTION<%0...%1> %0c0X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163875)
		#define UNIQUE_FUNCTION<%0...%1> %0c0Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163876)
		#define UNIQUE_FUNCTION<%0...%1> %0c0Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163877)
		#define UNIQUE_FUNCTION<%0...%1> %0c0_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163878)
		#define UNIQUE_FUNCTION<%0...%1> %0c0a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163879)
		#define UNIQUE_FUNCTION<%0...%1> %0c0b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (163887)
	#elseif UNIQUE_SYMBOL == (163879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163880)
		#define UNIQUE_FUNCTION<%0...%1> %0c0c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163881)
		#define UNIQUE_FUNCTION<%0...%1> %0c0d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163882)
		#define UNIQUE_FUNCTION<%0...%1> %0c0e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163883)
		#define UNIQUE_FUNCTION<%0...%1> %0c0f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163884)
		#define UNIQUE_FUNCTION<%0...%1> %0c0g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163885)
		#define UNIQUE_FUNCTION<%0...%1> %0c0h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163886)
		#define UNIQUE_FUNCTION<%0...%1> %0c0i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163887)
		#define UNIQUE_FUNCTION<%0...%1> %0c0j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (163895)
	#elseif UNIQUE_SYMBOL == (163887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163888)
		#define UNIQUE_FUNCTION<%0...%1> %0c0k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163889)
		#define UNIQUE_FUNCTION<%0...%1> %0c0l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163890)
		#define UNIQUE_FUNCTION<%0...%1> %0c0m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163891)
		#define UNIQUE_FUNCTION<%0...%1> %0c0n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163892)
		#define UNIQUE_FUNCTION<%0...%1> %0c0o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163893)
		#define UNIQUE_FUNCTION<%0...%1> %0c0p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163894)
		#define UNIQUE_FUNCTION<%0...%1> %0c0q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163895)
		#define UNIQUE_FUNCTION<%0...%1> %0c0r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (163895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163896)
		#define UNIQUE_FUNCTION<%0...%1> %0c0s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163897)
		#define UNIQUE_FUNCTION<%0...%1> %0c0t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163898)
		#define UNIQUE_FUNCTION<%0...%1> %0c0u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163899)
		#define UNIQUE_FUNCTION<%0...%1> %0c0v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163900)
		#define UNIQUE_FUNCTION<%0...%1> %0c0w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163901)
		#define UNIQUE_FUNCTION<%0...%1> %0c0x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (163901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163902)
		#define UNIQUE_FUNCTION<%0...%1> %0c0y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (163903)
		#define UNIQUE_FUNCTION<%0...%1> %0c0z%1
		#endinput
	#endif
#endif
