static stock const Y_UNIQUE_094592_094655_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_094592_094655
	#undef _inc_y_unique_094592_094655
#endif

#if UNIQUE_SYMBOL < (94599)
	#if UNIQUE_SYMBOL == (94591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94592)
		#define UNIQUE_FUNCTION<%0...%1> %0M60%1
		#endinput
	#if UNIQUE_SYMBOL == (94592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94593)
		#define UNIQUE_FUNCTION<%0...%1> %0M61%1
		#endinput
	#if UNIQUE_SYMBOL == (94593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94594)
		#define UNIQUE_FUNCTION<%0...%1> %0M62%1
		#endinput
	#if UNIQUE_SYMBOL == (94594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94595)
		#define UNIQUE_FUNCTION<%0...%1> %0M63%1
		#endinput
	#if UNIQUE_SYMBOL == (94595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94596)
		#define UNIQUE_FUNCTION<%0...%1> %0M64%1
		#endinput
	#if UNIQUE_SYMBOL == (94596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94597)
		#define UNIQUE_FUNCTION<%0...%1> %0M65%1
		#endinput
	#if UNIQUE_SYMBOL == (94597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94598)
		#define UNIQUE_FUNCTION<%0...%1> %0M66%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94599)
		#define UNIQUE_FUNCTION<%0...%1> %0M67%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (94607)
	#elseif UNIQUE_SYMBOL == (94599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94600)
		#define UNIQUE_FUNCTION<%0...%1> %0M68%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94601)
		#define UNIQUE_FUNCTION<%0...%1> %0M69%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94602)
		#define UNIQUE_FUNCTION<%0...%1> %0M6@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94603)
		#define UNIQUE_FUNCTION<%0...%1> %0M6A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94604)
		#define UNIQUE_FUNCTION<%0...%1> %0M6B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94605)
		#define UNIQUE_FUNCTION<%0...%1> %0M6C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94606)
		#define UNIQUE_FUNCTION<%0...%1> %0M6D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94607)
		#define UNIQUE_FUNCTION<%0...%1> %0M6E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (94615)
	#elseif UNIQUE_SYMBOL == (94607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94608)
		#define UNIQUE_FUNCTION<%0...%1> %0M6F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94609)
		#define UNIQUE_FUNCTION<%0...%1> %0M6G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94610)
		#define UNIQUE_FUNCTION<%0...%1> %0M6H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94611)
		#define UNIQUE_FUNCTION<%0...%1> %0M6I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94612)
		#define UNIQUE_FUNCTION<%0...%1> %0M6J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94613)
		#define UNIQUE_FUNCTION<%0...%1> %0M6K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94614)
		#define UNIQUE_FUNCTION<%0...%1> %0M6L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94615)
		#define UNIQUE_FUNCTION<%0...%1> %0M6M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (94623)
	#elseif UNIQUE_SYMBOL == (94615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94616)
		#define UNIQUE_FUNCTION<%0...%1> %0M6N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94617)
		#define UNIQUE_FUNCTION<%0...%1> %0M6O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94618)
		#define UNIQUE_FUNCTION<%0...%1> %0M6P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94619)
		#define UNIQUE_FUNCTION<%0...%1> %0M6Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94620)
		#define UNIQUE_FUNCTION<%0...%1> %0M6R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94621)
		#define UNIQUE_FUNCTION<%0...%1> %0M6S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94622)
		#define UNIQUE_FUNCTION<%0...%1> %0M6T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94623)
		#define UNIQUE_FUNCTION<%0...%1> %0M6U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (94631)
	#elseif UNIQUE_SYMBOL == (94623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94624)
		#define UNIQUE_FUNCTION<%0...%1> %0M6V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94625)
		#define UNIQUE_FUNCTION<%0...%1> %0M6W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94626)
		#define UNIQUE_FUNCTION<%0...%1> %0M6X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94627)
		#define UNIQUE_FUNCTION<%0...%1> %0M6Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94628)
		#define UNIQUE_FUNCTION<%0...%1> %0M6Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94629)
		#define UNIQUE_FUNCTION<%0...%1> %0M6_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94630)
		#define UNIQUE_FUNCTION<%0...%1> %0M6a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94631)
		#define UNIQUE_FUNCTION<%0...%1> %0M6b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (94639)
	#elseif UNIQUE_SYMBOL == (94631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94632)
		#define UNIQUE_FUNCTION<%0...%1> %0M6c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94633)
		#define UNIQUE_FUNCTION<%0...%1> %0M6d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94634)
		#define UNIQUE_FUNCTION<%0...%1> %0M6e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94635)
		#define UNIQUE_FUNCTION<%0...%1> %0M6f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94636)
		#define UNIQUE_FUNCTION<%0...%1> %0M6g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94637)
		#define UNIQUE_FUNCTION<%0...%1> %0M6h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94638)
		#define UNIQUE_FUNCTION<%0...%1> %0M6i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94639)
		#define UNIQUE_FUNCTION<%0...%1> %0M6j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (94647)
	#elseif UNIQUE_SYMBOL == (94639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94640)
		#define UNIQUE_FUNCTION<%0...%1> %0M6k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94641)
		#define UNIQUE_FUNCTION<%0...%1> %0M6l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94642)
		#define UNIQUE_FUNCTION<%0...%1> %0M6m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94643)
		#define UNIQUE_FUNCTION<%0...%1> %0M6n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94644)
		#define UNIQUE_FUNCTION<%0...%1> %0M6o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94645)
		#define UNIQUE_FUNCTION<%0...%1> %0M6p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94646)
		#define UNIQUE_FUNCTION<%0...%1> %0M6q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94647)
		#define UNIQUE_FUNCTION<%0...%1> %0M6r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (94647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94648)
		#define UNIQUE_FUNCTION<%0...%1> %0M6s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94649)
		#define UNIQUE_FUNCTION<%0...%1> %0M6t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94650)
		#define UNIQUE_FUNCTION<%0...%1> %0M6u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94651)
		#define UNIQUE_FUNCTION<%0...%1> %0M6v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94652)
		#define UNIQUE_FUNCTION<%0...%1> %0M6w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94653)
		#define UNIQUE_FUNCTION<%0...%1> %0M6x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (94653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94654)
		#define UNIQUE_FUNCTION<%0...%1> %0M6y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (94655)
		#define UNIQUE_FUNCTION<%0...%1> %0M6z%1
		#endinput
	#endif
#endif
