static stock const Y_UNIQUE_048000_048063_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_048000_048063
	#undef _inc_y_unique_048000_048063
#endif

#if UNIQUE_SYMBOL < (48007)
	#if UNIQUE_SYMBOL == (47999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48000)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai0%1
		#endinput
	#if UNIQUE_SYMBOL == (48000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48001)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai1%1
		#endinput
	#if UNIQUE_SYMBOL == (48001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48002)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai2%1
		#endinput
	#if UNIQUE_SYMBOL == (48002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48003)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai3%1
		#endinput
	#if UNIQUE_SYMBOL == (48003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48004)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai4%1
		#endinput
	#if UNIQUE_SYMBOL == (48004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48005)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai5%1
		#endinput
	#if UNIQUE_SYMBOL == (48005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48006)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48007)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48015)
	#elseif UNIQUE_SYMBOL == (48007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48008)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48009)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48010)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48011)
		#define UNIQUE_FUNCTION<%0...%1> %0AiA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48012)
		#define UNIQUE_FUNCTION<%0...%1> %0AiB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48013)
		#define UNIQUE_FUNCTION<%0...%1> %0AiC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48014)
		#define UNIQUE_FUNCTION<%0...%1> %0AiD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48015)
		#define UNIQUE_FUNCTION<%0...%1> %0AiE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48023)
	#elseif UNIQUE_SYMBOL == (48015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48016)
		#define UNIQUE_FUNCTION<%0...%1> %0AiF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48017)
		#define UNIQUE_FUNCTION<%0...%1> %0AiG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48018)
		#define UNIQUE_FUNCTION<%0...%1> %0AiH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48019)
		#define UNIQUE_FUNCTION<%0...%1> %0AiI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48020)
		#define UNIQUE_FUNCTION<%0...%1> %0AiJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48021)
		#define UNIQUE_FUNCTION<%0...%1> %0AiK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48022)
		#define UNIQUE_FUNCTION<%0...%1> %0AiL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48023)
		#define UNIQUE_FUNCTION<%0...%1> %0AiM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48031)
	#elseif UNIQUE_SYMBOL == (48023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48024)
		#define UNIQUE_FUNCTION<%0...%1> %0AiN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48025)
		#define UNIQUE_FUNCTION<%0...%1> %0AiO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48026)
		#define UNIQUE_FUNCTION<%0...%1> %0AiP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48027)
		#define UNIQUE_FUNCTION<%0...%1> %0AiQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48028)
		#define UNIQUE_FUNCTION<%0...%1> %0AiR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48029)
		#define UNIQUE_FUNCTION<%0...%1> %0AiS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48030)
		#define UNIQUE_FUNCTION<%0...%1> %0AiT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48031)
		#define UNIQUE_FUNCTION<%0...%1> %0AiU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48039)
	#elseif UNIQUE_SYMBOL == (48031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48032)
		#define UNIQUE_FUNCTION<%0...%1> %0AiV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48033)
		#define UNIQUE_FUNCTION<%0...%1> %0AiW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48034)
		#define UNIQUE_FUNCTION<%0...%1> %0AiX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48035)
		#define UNIQUE_FUNCTION<%0...%1> %0AiY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48036)
		#define UNIQUE_FUNCTION<%0...%1> %0AiZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48037)
		#define UNIQUE_FUNCTION<%0...%1> %0Ai_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48038)
		#define UNIQUE_FUNCTION<%0...%1> %0Aia%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48039)
		#define UNIQUE_FUNCTION<%0...%1> %0Aib%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48047)
	#elseif UNIQUE_SYMBOL == (48039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48040)
		#define UNIQUE_FUNCTION<%0...%1> %0Aic%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48041)
		#define UNIQUE_FUNCTION<%0...%1> %0Aid%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48042)
		#define UNIQUE_FUNCTION<%0...%1> %0Aie%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48043)
		#define UNIQUE_FUNCTION<%0...%1> %0Aif%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48044)
		#define UNIQUE_FUNCTION<%0...%1> %0Aig%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48045)
		#define UNIQUE_FUNCTION<%0...%1> %0Aih%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48046)
		#define UNIQUE_FUNCTION<%0...%1> %0Aii%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48047)
		#define UNIQUE_FUNCTION<%0...%1> %0Aij%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48055)
	#elseif UNIQUE_SYMBOL == (48047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48048)
		#define UNIQUE_FUNCTION<%0...%1> %0Aik%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48049)
		#define UNIQUE_FUNCTION<%0...%1> %0Ail%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48050)
		#define UNIQUE_FUNCTION<%0...%1> %0Aim%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48051)
		#define UNIQUE_FUNCTION<%0...%1> %0Ain%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48052)
		#define UNIQUE_FUNCTION<%0...%1> %0Aio%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48053)
		#define UNIQUE_FUNCTION<%0...%1> %0Aip%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48054)
		#define UNIQUE_FUNCTION<%0...%1> %0Aiq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48055)
		#define UNIQUE_FUNCTION<%0...%1> %0Air%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (48055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48056)
		#define UNIQUE_FUNCTION<%0...%1> %0Ais%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48057)
		#define UNIQUE_FUNCTION<%0...%1> %0Ait%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48058)
		#define UNIQUE_FUNCTION<%0...%1> %0Aiu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48059)
		#define UNIQUE_FUNCTION<%0...%1> %0Aiv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48060)
		#define UNIQUE_FUNCTION<%0...%1> %0Aiw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48061)
		#define UNIQUE_FUNCTION<%0...%1> %0Aix%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48062)
		#define UNIQUE_FUNCTION<%0...%1> %0Aiy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48063)
		#define UNIQUE_FUNCTION<%0...%1> %0Aiz%1
		#endinput
	#endif
#endif
