static stock const Y_UNIQUE_122560_122623_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_122560_122623
	#undef _inc_y_unique_122560_122623
#endif

#if UNIQUE_SYMBOL < (122567)
	#if UNIQUE_SYMBOL == (122559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122560)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv0%1
		#endinput
	#if UNIQUE_SYMBOL == (122560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122561)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv1%1
		#endinput
	#if UNIQUE_SYMBOL == (122561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122562)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv2%1
		#endinput
	#if UNIQUE_SYMBOL == (122562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122563)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv3%1
		#endinput
	#if UNIQUE_SYMBOL == (122563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122564)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv4%1
		#endinput
	#if UNIQUE_SYMBOL == (122564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122565)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv5%1
		#endinput
	#if UNIQUE_SYMBOL == (122565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122566)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122567)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122575)
	#elseif UNIQUE_SYMBOL == (122567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122568)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122569)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122570)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122571)
		#define UNIQUE_FUNCTION<%0...%1> %0SvA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122572)
		#define UNIQUE_FUNCTION<%0...%1> %0SvB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122573)
		#define UNIQUE_FUNCTION<%0...%1> %0SvC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122574)
		#define UNIQUE_FUNCTION<%0...%1> %0SvD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122575)
		#define UNIQUE_FUNCTION<%0...%1> %0SvE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122583)
	#elseif UNIQUE_SYMBOL == (122575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122576)
		#define UNIQUE_FUNCTION<%0...%1> %0SvF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122577)
		#define UNIQUE_FUNCTION<%0...%1> %0SvG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122578)
		#define UNIQUE_FUNCTION<%0...%1> %0SvH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122579)
		#define UNIQUE_FUNCTION<%0...%1> %0SvI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122580)
		#define UNIQUE_FUNCTION<%0...%1> %0SvJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122581)
		#define UNIQUE_FUNCTION<%0...%1> %0SvK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122582)
		#define UNIQUE_FUNCTION<%0...%1> %0SvL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122583)
		#define UNIQUE_FUNCTION<%0...%1> %0SvM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122591)
	#elseif UNIQUE_SYMBOL == (122583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122584)
		#define UNIQUE_FUNCTION<%0...%1> %0SvN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122585)
		#define UNIQUE_FUNCTION<%0...%1> %0SvO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122586)
		#define UNIQUE_FUNCTION<%0...%1> %0SvP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122587)
		#define UNIQUE_FUNCTION<%0...%1> %0SvQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122588)
		#define UNIQUE_FUNCTION<%0...%1> %0SvR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122589)
		#define UNIQUE_FUNCTION<%0...%1> %0SvS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122590)
		#define UNIQUE_FUNCTION<%0...%1> %0SvT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122591)
		#define UNIQUE_FUNCTION<%0...%1> %0SvU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122599)
	#elseif UNIQUE_SYMBOL == (122591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122592)
		#define UNIQUE_FUNCTION<%0...%1> %0SvV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122593)
		#define UNIQUE_FUNCTION<%0...%1> %0SvW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122594)
		#define UNIQUE_FUNCTION<%0...%1> %0SvX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122595)
		#define UNIQUE_FUNCTION<%0...%1> %0SvY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122596)
		#define UNIQUE_FUNCTION<%0...%1> %0SvZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122597)
		#define UNIQUE_FUNCTION<%0...%1> %0Sv_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122598)
		#define UNIQUE_FUNCTION<%0...%1> %0Sva%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122599)
		#define UNIQUE_FUNCTION<%0...%1> %0Svb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122607)
	#elseif UNIQUE_SYMBOL == (122599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122600)
		#define UNIQUE_FUNCTION<%0...%1> %0Svc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122601)
		#define UNIQUE_FUNCTION<%0...%1> %0Svd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122602)
		#define UNIQUE_FUNCTION<%0...%1> %0Sve%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122603)
		#define UNIQUE_FUNCTION<%0...%1> %0Svf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122604)
		#define UNIQUE_FUNCTION<%0...%1> %0Svg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122605)
		#define UNIQUE_FUNCTION<%0...%1> %0Svh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122606)
		#define UNIQUE_FUNCTION<%0...%1> %0Svi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122607)
		#define UNIQUE_FUNCTION<%0...%1> %0Svj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (122615)
	#elseif UNIQUE_SYMBOL == (122607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122608)
		#define UNIQUE_FUNCTION<%0...%1> %0Svk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122609)
		#define UNIQUE_FUNCTION<%0...%1> %0Svl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122610)
		#define UNIQUE_FUNCTION<%0...%1> %0Svm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122611)
		#define UNIQUE_FUNCTION<%0...%1> %0Svn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122612)
		#define UNIQUE_FUNCTION<%0...%1> %0Svo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122613)
		#define UNIQUE_FUNCTION<%0...%1> %0Svp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122614)
		#define UNIQUE_FUNCTION<%0...%1> %0Svq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122615)
		#define UNIQUE_FUNCTION<%0...%1> %0Svr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (122615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122616)
		#define UNIQUE_FUNCTION<%0...%1> %0Svs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122617)
		#define UNIQUE_FUNCTION<%0...%1> %0Svt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122618)
		#define UNIQUE_FUNCTION<%0...%1> %0Svu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122619)
		#define UNIQUE_FUNCTION<%0...%1> %0Svv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122620)
		#define UNIQUE_FUNCTION<%0...%1> %0Svw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122621)
		#define UNIQUE_FUNCTION<%0...%1> %0Svx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (122621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122622)
		#define UNIQUE_FUNCTION<%0...%1> %0Svy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (122623)
		#define UNIQUE_FUNCTION<%0...%1> %0Svz%1
		#endinput
	#endif
#endif
