static stock const Y_UNIQUE_251648_251711_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_251648_251711
	#undef _inc_y_unique_251648_251711
#endif

#if UNIQUE_SYMBOL < (251655)
	#if UNIQUE_SYMBOL == (251647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251648)
		#define UNIQUE_FUNCTION<%0...%1> %0xR0%1
		#endinput
	#if UNIQUE_SYMBOL == (251648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251649)
		#define UNIQUE_FUNCTION<%0...%1> %0xR1%1
		#endinput
	#if UNIQUE_SYMBOL == (251649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251650)
		#define UNIQUE_FUNCTION<%0...%1> %0xR2%1
		#endinput
	#if UNIQUE_SYMBOL == (251650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251651)
		#define UNIQUE_FUNCTION<%0...%1> %0xR3%1
		#endinput
	#if UNIQUE_SYMBOL == (251651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251652)
		#define UNIQUE_FUNCTION<%0...%1> %0xR4%1
		#endinput
	#if UNIQUE_SYMBOL == (251652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251653)
		#define UNIQUE_FUNCTION<%0...%1> %0xR5%1
		#endinput
	#if UNIQUE_SYMBOL == (251653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251654)
		#define UNIQUE_FUNCTION<%0...%1> %0xR6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251655)
		#define UNIQUE_FUNCTION<%0...%1> %0xR7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (251663)
	#elseif UNIQUE_SYMBOL == (251655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251656)
		#define UNIQUE_FUNCTION<%0...%1> %0xR8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251657)
		#define UNIQUE_FUNCTION<%0...%1> %0xR9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251658)
		#define UNIQUE_FUNCTION<%0...%1> %0xR@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251659)
		#define UNIQUE_FUNCTION<%0...%1> %0xRA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251660)
		#define UNIQUE_FUNCTION<%0...%1> %0xRB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251661)
		#define UNIQUE_FUNCTION<%0...%1> %0xRC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251662)
		#define UNIQUE_FUNCTION<%0...%1> %0xRD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251663)
		#define UNIQUE_FUNCTION<%0...%1> %0xRE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (251671)
	#elseif UNIQUE_SYMBOL == (251663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251664)
		#define UNIQUE_FUNCTION<%0...%1> %0xRF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251665)
		#define UNIQUE_FUNCTION<%0...%1> %0xRG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251666)
		#define UNIQUE_FUNCTION<%0...%1> %0xRH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251667)
		#define UNIQUE_FUNCTION<%0...%1> %0xRI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251668)
		#define UNIQUE_FUNCTION<%0...%1> %0xRJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251669)
		#define UNIQUE_FUNCTION<%0...%1> %0xRK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251670)
		#define UNIQUE_FUNCTION<%0...%1> %0xRL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251671)
		#define UNIQUE_FUNCTION<%0...%1> %0xRM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (251679)
	#elseif UNIQUE_SYMBOL == (251671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251672)
		#define UNIQUE_FUNCTION<%0...%1> %0xRN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251673)
		#define UNIQUE_FUNCTION<%0...%1> %0xRO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251674)
		#define UNIQUE_FUNCTION<%0...%1> %0xRP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251675)
		#define UNIQUE_FUNCTION<%0...%1> %0xRQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251676)
		#define UNIQUE_FUNCTION<%0...%1> %0xRR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251677)
		#define UNIQUE_FUNCTION<%0...%1> %0xRS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251678)
		#define UNIQUE_FUNCTION<%0...%1> %0xRT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251679)
		#define UNIQUE_FUNCTION<%0...%1> %0xRU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (251687)
	#elseif UNIQUE_SYMBOL == (251679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251680)
		#define UNIQUE_FUNCTION<%0...%1> %0xRV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251681)
		#define UNIQUE_FUNCTION<%0...%1> %0xRW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251682)
		#define UNIQUE_FUNCTION<%0...%1> %0xRX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251683)
		#define UNIQUE_FUNCTION<%0...%1> %0xRY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251684)
		#define UNIQUE_FUNCTION<%0...%1> %0xRZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251685)
		#define UNIQUE_FUNCTION<%0...%1> %0xR_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251686)
		#define UNIQUE_FUNCTION<%0...%1> %0xRa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251687)
		#define UNIQUE_FUNCTION<%0...%1> %0xRb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (251695)
	#elseif UNIQUE_SYMBOL == (251687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251688)
		#define UNIQUE_FUNCTION<%0...%1> %0xRc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251689)
		#define UNIQUE_FUNCTION<%0...%1> %0xRd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251690)
		#define UNIQUE_FUNCTION<%0...%1> %0xRe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251691)
		#define UNIQUE_FUNCTION<%0...%1> %0xRf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251692)
		#define UNIQUE_FUNCTION<%0...%1> %0xRg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251693)
		#define UNIQUE_FUNCTION<%0...%1> %0xRh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251694)
		#define UNIQUE_FUNCTION<%0...%1> %0xRi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251695)
		#define UNIQUE_FUNCTION<%0...%1> %0xRj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (251703)
	#elseif UNIQUE_SYMBOL == (251695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251696)
		#define UNIQUE_FUNCTION<%0...%1> %0xRk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251697)
		#define UNIQUE_FUNCTION<%0...%1> %0xRl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251698)
		#define UNIQUE_FUNCTION<%0...%1> %0xRm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251699)
		#define UNIQUE_FUNCTION<%0...%1> %0xRn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251700)
		#define UNIQUE_FUNCTION<%0...%1> %0xRo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251701)
		#define UNIQUE_FUNCTION<%0...%1> %0xRp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251702)
		#define UNIQUE_FUNCTION<%0...%1> %0xRq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251703)
		#define UNIQUE_FUNCTION<%0...%1> %0xRr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (251703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251704)
		#define UNIQUE_FUNCTION<%0...%1> %0xRs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251705)
		#define UNIQUE_FUNCTION<%0...%1> %0xRt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251706)
		#define UNIQUE_FUNCTION<%0...%1> %0xRu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251707)
		#define UNIQUE_FUNCTION<%0...%1> %0xRv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251708)
		#define UNIQUE_FUNCTION<%0...%1> %0xRw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251709)
		#define UNIQUE_FUNCTION<%0...%1> %0xRx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (251709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251710)
		#define UNIQUE_FUNCTION<%0...%1> %0xRy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (251711)
		#define UNIQUE_FUNCTION<%0...%1> %0xRz%1
		#endinput
	#endif
#endif
