static stock const Y_UNIQUE_105792_105855_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_105792_105855
	#undef _inc_y_unique_105792_105855
#endif

#if UNIQUE_SYMBOL < (105799)
	#if UNIQUE_SYMBOL == (105791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105792)
		#define UNIQUE_FUNCTION<%0...%1> %0Op0%1
		#endinput
	#if UNIQUE_SYMBOL == (105792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105793)
		#define UNIQUE_FUNCTION<%0...%1> %0Op1%1
		#endinput
	#if UNIQUE_SYMBOL == (105793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105794)
		#define UNIQUE_FUNCTION<%0...%1> %0Op2%1
		#endinput
	#if UNIQUE_SYMBOL == (105794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105795)
		#define UNIQUE_FUNCTION<%0...%1> %0Op3%1
		#endinput
	#if UNIQUE_SYMBOL == (105795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105796)
		#define UNIQUE_FUNCTION<%0...%1> %0Op4%1
		#endinput
	#if UNIQUE_SYMBOL == (105796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105797)
		#define UNIQUE_FUNCTION<%0...%1> %0Op5%1
		#endinput
	#if UNIQUE_SYMBOL == (105797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105798)
		#define UNIQUE_FUNCTION<%0...%1> %0Op6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105799)
		#define UNIQUE_FUNCTION<%0...%1> %0Op7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (105807)
	#elseif UNIQUE_SYMBOL == (105799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105800)
		#define UNIQUE_FUNCTION<%0...%1> %0Op8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105801)
		#define UNIQUE_FUNCTION<%0...%1> %0Op9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105802)
		#define UNIQUE_FUNCTION<%0...%1> %0Op@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105803)
		#define UNIQUE_FUNCTION<%0...%1> %0OpA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105804)
		#define UNIQUE_FUNCTION<%0...%1> %0OpB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105805)
		#define UNIQUE_FUNCTION<%0...%1> %0OpC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105806)
		#define UNIQUE_FUNCTION<%0...%1> %0OpD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105807)
		#define UNIQUE_FUNCTION<%0...%1> %0OpE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (105815)
	#elseif UNIQUE_SYMBOL == (105807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105808)
		#define UNIQUE_FUNCTION<%0...%1> %0OpF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105809)
		#define UNIQUE_FUNCTION<%0...%1> %0OpG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105810)
		#define UNIQUE_FUNCTION<%0...%1> %0OpH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105811)
		#define UNIQUE_FUNCTION<%0...%1> %0OpI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105812)
		#define UNIQUE_FUNCTION<%0...%1> %0OpJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105813)
		#define UNIQUE_FUNCTION<%0...%1> %0OpK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105814)
		#define UNIQUE_FUNCTION<%0...%1> %0OpL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105815)
		#define UNIQUE_FUNCTION<%0...%1> %0OpM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (105823)
	#elseif UNIQUE_SYMBOL == (105815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105816)
		#define UNIQUE_FUNCTION<%0...%1> %0OpN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105817)
		#define UNIQUE_FUNCTION<%0...%1> %0OpO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105818)
		#define UNIQUE_FUNCTION<%0...%1> %0OpP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105819)
		#define UNIQUE_FUNCTION<%0...%1> %0OpQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105820)
		#define UNIQUE_FUNCTION<%0...%1> %0OpR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105821)
		#define UNIQUE_FUNCTION<%0...%1> %0OpS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105822)
		#define UNIQUE_FUNCTION<%0...%1> %0OpT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105823)
		#define UNIQUE_FUNCTION<%0...%1> %0OpU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (105831)
	#elseif UNIQUE_SYMBOL == (105823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105824)
		#define UNIQUE_FUNCTION<%0...%1> %0OpV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105825)
		#define UNIQUE_FUNCTION<%0...%1> %0OpW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105826)
		#define UNIQUE_FUNCTION<%0...%1> %0OpX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105827)
		#define UNIQUE_FUNCTION<%0...%1> %0OpY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105828)
		#define UNIQUE_FUNCTION<%0...%1> %0OpZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105829)
		#define UNIQUE_FUNCTION<%0...%1> %0Op_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105830)
		#define UNIQUE_FUNCTION<%0...%1> %0Opa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105831)
		#define UNIQUE_FUNCTION<%0...%1> %0Opb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (105839)
	#elseif UNIQUE_SYMBOL == (105831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105832)
		#define UNIQUE_FUNCTION<%0...%1> %0Opc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105833)
		#define UNIQUE_FUNCTION<%0...%1> %0Opd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105834)
		#define UNIQUE_FUNCTION<%0...%1> %0Ope%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105835)
		#define UNIQUE_FUNCTION<%0...%1> %0Opf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105836)
		#define UNIQUE_FUNCTION<%0...%1> %0Opg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105837)
		#define UNIQUE_FUNCTION<%0...%1> %0Oph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105838)
		#define UNIQUE_FUNCTION<%0...%1> %0Opi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105839)
		#define UNIQUE_FUNCTION<%0...%1> %0Opj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (105847)
	#elseif UNIQUE_SYMBOL == (105839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105840)
		#define UNIQUE_FUNCTION<%0...%1> %0Opk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105841)
		#define UNIQUE_FUNCTION<%0...%1> %0Opl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105842)
		#define UNIQUE_FUNCTION<%0...%1> %0Opm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105843)
		#define UNIQUE_FUNCTION<%0...%1> %0Opn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105844)
		#define UNIQUE_FUNCTION<%0...%1> %0Opo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105845)
		#define UNIQUE_FUNCTION<%0...%1> %0Opp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105846)
		#define UNIQUE_FUNCTION<%0...%1> %0Opq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105847)
		#define UNIQUE_FUNCTION<%0...%1> %0Opr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (105847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105848)
		#define UNIQUE_FUNCTION<%0...%1> %0Ops%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105849)
		#define UNIQUE_FUNCTION<%0...%1> %0Opt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105850)
		#define UNIQUE_FUNCTION<%0...%1> %0Opu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105851)
		#define UNIQUE_FUNCTION<%0...%1> %0Opv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105852)
		#define UNIQUE_FUNCTION<%0...%1> %0Opw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105853)
		#define UNIQUE_FUNCTION<%0...%1> %0Opx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (105853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105854)
		#define UNIQUE_FUNCTION<%0...%1> %0Opy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (105855)
		#define UNIQUE_FUNCTION<%0...%1> %0Opz%1
		#endinput
	#endif
#endif
