static stock const Y_UNIQUE_067776_067839_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_067776_067839
	#undef _inc_y_unique_067776_067839
#endif

#if UNIQUE_SYMBOL < (67783)
	#if UNIQUE_SYMBOL == (67775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67776)
		#define UNIQUE_FUNCTION<%0...%1> %0FY0%1
		#endinput
	#if UNIQUE_SYMBOL == (67776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67777)
		#define UNIQUE_FUNCTION<%0...%1> %0FY1%1
		#endinput
	#if UNIQUE_SYMBOL == (67777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67778)
		#define UNIQUE_FUNCTION<%0...%1> %0FY2%1
		#endinput
	#if UNIQUE_SYMBOL == (67778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67779)
		#define UNIQUE_FUNCTION<%0...%1> %0FY3%1
		#endinput
	#if UNIQUE_SYMBOL == (67779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67780)
		#define UNIQUE_FUNCTION<%0...%1> %0FY4%1
		#endinput
	#if UNIQUE_SYMBOL == (67780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67781)
		#define UNIQUE_FUNCTION<%0...%1> %0FY5%1
		#endinput
	#if UNIQUE_SYMBOL == (67781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67782)
		#define UNIQUE_FUNCTION<%0...%1> %0FY6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67783)
		#define UNIQUE_FUNCTION<%0...%1> %0FY7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67791)
	#elseif UNIQUE_SYMBOL == (67783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67784)
		#define UNIQUE_FUNCTION<%0...%1> %0FY8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67785)
		#define UNIQUE_FUNCTION<%0...%1> %0FY9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67786)
		#define UNIQUE_FUNCTION<%0...%1> %0FY@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67787)
		#define UNIQUE_FUNCTION<%0...%1> %0FYA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67788)
		#define UNIQUE_FUNCTION<%0...%1> %0FYB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67789)
		#define UNIQUE_FUNCTION<%0...%1> %0FYC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67790)
		#define UNIQUE_FUNCTION<%0...%1> %0FYD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67791)
		#define UNIQUE_FUNCTION<%0...%1> %0FYE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67799)
	#elseif UNIQUE_SYMBOL == (67791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67792)
		#define UNIQUE_FUNCTION<%0...%1> %0FYF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67793)
		#define UNIQUE_FUNCTION<%0...%1> %0FYG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67794)
		#define UNIQUE_FUNCTION<%0...%1> %0FYH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67795)
		#define UNIQUE_FUNCTION<%0...%1> %0FYI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67796)
		#define UNIQUE_FUNCTION<%0...%1> %0FYJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67797)
		#define UNIQUE_FUNCTION<%0...%1> %0FYK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67798)
		#define UNIQUE_FUNCTION<%0...%1> %0FYL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67799)
		#define UNIQUE_FUNCTION<%0...%1> %0FYM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67807)
	#elseif UNIQUE_SYMBOL == (67799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67800)
		#define UNIQUE_FUNCTION<%0...%1> %0FYN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67801)
		#define UNIQUE_FUNCTION<%0...%1> %0FYO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67802)
		#define UNIQUE_FUNCTION<%0...%1> %0FYP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67803)
		#define UNIQUE_FUNCTION<%0...%1> %0FYQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67804)
		#define UNIQUE_FUNCTION<%0...%1> %0FYR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67805)
		#define UNIQUE_FUNCTION<%0...%1> %0FYS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67806)
		#define UNIQUE_FUNCTION<%0...%1> %0FYT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67807)
		#define UNIQUE_FUNCTION<%0...%1> %0FYU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67815)
	#elseif UNIQUE_SYMBOL == (67807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67808)
		#define UNIQUE_FUNCTION<%0...%1> %0FYV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67809)
		#define UNIQUE_FUNCTION<%0...%1> %0FYW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67810)
		#define UNIQUE_FUNCTION<%0...%1> %0FYX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67811)
		#define UNIQUE_FUNCTION<%0...%1> %0FYY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67812)
		#define UNIQUE_FUNCTION<%0...%1> %0FYZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67813)
		#define UNIQUE_FUNCTION<%0...%1> %0FY_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67814)
		#define UNIQUE_FUNCTION<%0...%1> %0FYa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67815)
		#define UNIQUE_FUNCTION<%0...%1> %0FYb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67823)
	#elseif UNIQUE_SYMBOL == (67815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67816)
		#define UNIQUE_FUNCTION<%0...%1> %0FYc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67817)
		#define UNIQUE_FUNCTION<%0...%1> %0FYd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67818)
		#define UNIQUE_FUNCTION<%0...%1> %0FYe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67819)
		#define UNIQUE_FUNCTION<%0...%1> %0FYf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67820)
		#define UNIQUE_FUNCTION<%0...%1> %0FYg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67821)
		#define UNIQUE_FUNCTION<%0...%1> %0FYh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67822)
		#define UNIQUE_FUNCTION<%0...%1> %0FYi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67823)
		#define UNIQUE_FUNCTION<%0...%1> %0FYj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67831)
	#elseif UNIQUE_SYMBOL == (67823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67824)
		#define UNIQUE_FUNCTION<%0...%1> %0FYk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67825)
		#define UNIQUE_FUNCTION<%0...%1> %0FYl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67826)
		#define UNIQUE_FUNCTION<%0...%1> %0FYm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67827)
		#define UNIQUE_FUNCTION<%0...%1> %0FYn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67828)
		#define UNIQUE_FUNCTION<%0...%1> %0FYo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67829)
		#define UNIQUE_FUNCTION<%0...%1> %0FYp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67830)
		#define UNIQUE_FUNCTION<%0...%1> %0FYq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67831)
		#define UNIQUE_FUNCTION<%0...%1> %0FYr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (67831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67832)
		#define UNIQUE_FUNCTION<%0...%1> %0FYs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67833)
		#define UNIQUE_FUNCTION<%0...%1> %0FYt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67834)
		#define UNIQUE_FUNCTION<%0...%1> %0FYu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67835)
		#define UNIQUE_FUNCTION<%0...%1> %0FYv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67836)
		#define UNIQUE_FUNCTION<%0...%1> %0FYw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67837)
		#define UNIQUE_FUNCTION<%0...%1> %0FYx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67838)
		#define UNIQUE_FUNCTION<%0...%1> %0FYy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67839)
		#define UNIQUE_FUNCTION<%0...%1> %0FYz%1
		#endinput
	#endif
#endif
