static stock const Y_UNIQUE_045824_045887_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_045824_045887
	#undef _inc_y_unique_045824_045887
#endif

#if UNIQUE_SYMBOL < (45831)
	#if UNIQUE_SYMBOL == (45823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45824)
		#define UNIQUE_FUNCTION<%0...%1> %0AB0%1
		#endinput
	#if UNIQUE_SYMBOL == (45824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45825)
		#define UNIQUE_FUNCTION<%0...%1> %0AB1%1
		#endinput
	#if UNIQUE_SYMBOL == (45825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45826)
		#define UNIQUE_FUNCTION<%0...%1> %0AB2%1
		#endinput
	#if UNIQUE_SYMBOL == (45826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45827)
		#define UNIQUE_FUNCTION<%0...%1> %0AB3%1
		#endinput
	#if UNIQUE_SYMBOL == (45827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45828)
		#define UNIQUE_FUNCTION<%0...%1> %0AB4%1
		#endinput
	#if UNIQUE_SYMBOL == (45828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45829)
		#define UNIQUE_FUNCTION<%0...%1> %0AB5%1
		#endinput
	#if UNIQUE_SYMBOL == (45829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45830)
		#define UNIQUE_FUNCTION<%0...%1> %0AB6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45831)
		#define UNIQUE_FUNCTION<%0...%1> %0AB7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45839)
	#elseif UNIQUE_SYMBOL == (45831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45832)
		#define UNIQUE_FUNCTION<%0...%1> %0AB8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45833)
		#define UNIQUE_FUNCTION<%0...%1> %0AB9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45834)
		#define UNIQUE_FUNCTION<%0...%1> %0AB@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45835)
		#define UNIQUE_FUNCTION<%0...%1> %0ABA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45836)
		#define UNIQUE_FUNCTION<%0...%1> %0ABB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45837)
		#define UNIQUE_FUNCTION<%0...%1> %0ABC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45838)
		#define UNIQUE_FUNCTION<%0...%1> %0ABD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45839)
		#define UNIQUE_FUNCTION<%0...%1> %0ABE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45847)
	#elseif UNIQUE_SYMBOL == (45839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45840)
		#define UNIQUE_FUNCTION<%0...%1> %0ABF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45841)
		#define UNIQUE_FUNCTION<%0...%1> %0ABG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45842)
		#define UNIQUE_FUNCTION<%0...%1> %0ABH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45843)
		#define UNIQUE_FUNCTION<%0...%1> %0ABI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45844)
		#define UNIQUE_FUNCTION<%0...%1> %0ABJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45845)
		#define UNIQUE_FUNCTION<%0...%1> %0ABK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45846)
		#define UNIQUE_FUNCTION<%0...%1> %0ABL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45847)
		#define UNIQUE_FUNCTION<%0...%1> %0ABM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45855)
	#elseif UNIQUE_SYMBOL == (45847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45848)
		#define UNIQUE_FUNCTION<%0...%1> %0ABN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45849)
		#define UNIQUE_FUNCTION<%0...%1> %0ABO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45850)
		#define UNIQUE_FUNCTION<%0...%1> %0ABP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45851)
		#define UNIQUE_FUNCTION<%0...%1> %0ABQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45852)
		#define UNIQUE_FUNCTION<%0...%1> %0ABR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45853)
		#define UNIQUE_FUNCTION<%0...%1> %0ABS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45854)
		#define UNIQUE_FUNCTION<%0...%1> %0ABT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45855)
		#define UNIQUE_FUNCTION<%0...%1> %0ABU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45863)
	#elseif UNIQUE_SYMBOL == (45855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45856)
		#define UNIQUE_FUNCTION<%0...%1> %0ABV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45857)
		#define UNIQUE_FUNCTION<%0...%1> %0ABW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45858)
		#define UNIQUE_FUNCTION<%0...%1> %0ABX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45859)
		#define UNIQUE_FUNCTION<%0...%1> %0ABY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45860)
		#define UNIQUE_FUNCTION<%0...%1> %0ABZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45861)
		#define UNIQUE_FUNCTION<%0...%1> %0AB_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45862)
		#define UNIQUE_FUNCTION<%0...%1> %0ABa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45863)
		#define UNIQUE_FUNCTION<%0...%1> %0ABb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45871)
	#elseif UNIQUE_SYMBOL == (45863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45864)
		#define UNIQUE_FUNCTION<%0...%1> %0ABc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45865)
		#define UNIQUE_FUNCTION<%0...%1> %0ABd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45866)
		#define UNIQUE_FUNCTION<%0...%1> %0ABe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45867)
		#define UNIQUE_FUNCTION<%0...%1> %0ABf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45868)
		#define UNIQUE_FUNCTION<%0...%1> %0ABg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45869)
		#define UNIQUE_FUNCTION<%0...%1> %0ABh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45870)
		#define UNIQUE_FUNCTION<%0...%1> %0ABi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45871)
		#define UNIQUE_FUNCTION<%0...%1> %0ABj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45879)
	#elseif UNIQUE_SYMBOL == (45871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45872)
		#define UNIQUE_FUNCTION<%0...%1> %0ABk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45873)
		#define UNIQUE_FUNCTION<%0...%1> %0ABl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45874)
		#define UNIQUE_FUNCTION<%0...%1> %0ABm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45875)
		#define UNIQUE_FUNCTION<%0...%1> %0ABn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45876)
		#define UNIQUE_FUNCTION<%0...%1> %0ABo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45877)
		#define UNIQUE_FUNCTION<%0...%1> %0ABp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45878)
		#define UNIQUE_FUNCTION<%0...%1> %0ABq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45879)
		#define UNIQUE_FUNCTION<%0...%1> %0ABr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (45879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45880)
		#define UNIQUE_FUNCTION<%0...%1> %0ABs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45881)
		#define UNIQUE_FUNCTION<%0...%1> %0ABt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45882)
		#define UNIQUE_FUNCTION<%0...%1> %0ABu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45883)
		#define UNIQUE_FUNCTION<%0...%1> %0ABv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45884)
		#define UNIQUE_FUNCTION<%0...%1> %0ABw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45885)
		#define UNIQUE_FUNCTION<%0...%1> %0ABx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45886)
		#define UNIQUE_FUNCTION<%0...%1> %0ABy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45887)
		#define UNIQUE_FUNCTION<%0...%1> %0ABz%1
		#endinput
	#endif
#endif
