static stock const Y_UNIQUE_073984_074047_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_073984_074047
	#undef _inc_y_unique_073984_074047
#endif

#if UNIQUE_SYMBOL < (73991)
	#if UNIQUE_SYMBOL == (73983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73984)
		#define UNIQUE_FUNCTION<%0...%1> %0H40%1
		#endinput
	#if UNIQUE_SYMBOL == (73984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73985)
		#define UNIQUE_FUNCTION<%0...%1> %0H41%1
		#endinput
	#if UNIQUE_SYMBOL == (73985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73986)
		#define UNIQUE_FUNCTION<%0...%1> %0H42%1
		#endinput
	#if UNIQUE_SYMBOL == (73986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73987)
		#define UNIQUE_FUNCTION<%0...%1> %0H43%1
		#endinput
	#if UNIQUE_SYMBOL == (73987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73988)
		#define UNIQUE_FUNCTION<%0...%1> %0H44%1
		#endinput
	#if UNIQUE_SYMBOL == (73988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73989)
		#define UNIQUE_FUNCTION<%0...%1> %0H45%1
		#endinput
	#if UNIQUE_SYMBOL == (73989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73990)
		#define UNIQUE_FUNCTION<%0...%1> %0H46%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73991)
		#define UNIQUE_FUNCTION<%0...%1> %0H47%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (73999)
	#elseif UNIQUE_SYMBOL == (73991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73992)
		#define UNIQUE_FUNCTION<%0...%1> %0H48%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73993)
		#define UNIQUE_FUNCTION<%0...%1> %0H49%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73994)
		#define UNIQUE_FUNCTION<%0...%1> %0H4@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73995)
		#define UNIQUE_FUNCTION<%0...%1> %0H4A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73996)
		#define UNIQUE_FUNCTION<%0...%1> %0H4B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73997)
		#define UNIQUE_FUNCTION<%0...%1> %0H4C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (73997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73998)
		#define UNIQUE_FUNCTION<%0...%1> %0H4D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (73999)
		#define UNIQUE_FUNCTION<%0...%1> %0H4E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (74007)
	#elseif UNIQUE_SYMBOL == (73999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74000)
		#define UNIQUE_FUNCTION<%0...%1> %0H4F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74001)
		#define UNIQUE_FUNCTION<%0...%1> %0H4G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74002)
		#define UNIQUE_FUNCTION<%0...%1> %0H4H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74003)
		#define UNIQUE_FUNCTION<%0...%1> %0H4I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74004)
		#define UNIQUE_FUNCTION<%0...%1> %0H4J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74005)
		#define UNIQUE_FUNCTION<%0...%1> %0H4K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74006)
		#define UNIQUE_FUNCTION<%0...%1> %0H4L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74007)
		#define UNIQUE_FUNCTION<%0...%1> %0H4M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (74015)
	#elseif UNIQUE_SYMBOL == (74007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74008)
		#define UNIQUE_FUNCTION<%0...%1> %0H4N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74009)
		#define UNIQUE_FUNCTION<%0...%1> %0H4O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74010)
		#define UNIQUE_FUNCTION<%0...%1> %0H4P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74011)
		#define UNIQUE_FUNCTION<%0...%1> %0H4Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74012)
		#define UNIQUE_FUNCTION<%0...%1> %0H4R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74013)
		#define UNIQUE_FUNCTION<%0...%1> %0H4S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74014)
		#define UNIQUE_FUNCTION<%0...%1> %0H4T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74015)
		#define UNIQUE_FUNCTION<%0...%1> %0H4U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (74023)
	#elseif UNIQUE_SYMBOL == (74015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74016)
		#define UNIQUE_FUNCTION<%0...%1> %0H4V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74017)
		#define UNIQUE_FUNCTION<%0...%1> %0H4W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74018)
		#define UNIQUE_FUNCTION<%0...%1> %0H4X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74019)
		#define UNIQUE_FUNCTION<%0...%1> %0H4Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74020)
		#define UNIQUE_FUNCTION<%0...%1> %0H4Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74021)
		#define UNIQUE_FUNCTION<%0...%1> %0H4_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74022)
		#define UNIQUE_FUNCTION<%0...%1> %0H4a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74023)
		#define UNIQUE_FUNCTION<%0...%1> %0H4b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (74031)
	#elseif UNIQUE_SYMBOL == (74023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74024)
		#define UNIQUE_FUNCTION<%0...%1> %0H4c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74025)
		#define UNIQUE_FUNCTION<%0...%1> %0H4d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74026)
		#define UNIQUE_FUNCTION<%0...%1> %0H4e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74027)
		#define UNIQUE_FUNCTION<%0...%1> %0H4f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74028)
		#define UNIQUE_FUNCTION<%0...%1> %0H4g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74029)
		#define UNIQUE_FUNCTION<%0...%1> %0H4h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74030)
		#define UNIQUE_FUNCTION<%0...%1> %0H4i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74031)
		#define UNIQUE_FUNCTION<%0...%1> %0H4j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (74039)
	#elseif UNIQUE_SYMBOL == (74031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74032)
		#define UNIQUE_FUNCTION<%0...%1> %0H4k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74033)
		#define UNIQUE_FUNCTION<%0...%1> %0H4l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74034)
		#define UNIQUE_FUNCTION<%0...%1> %0H4m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74035)
		#define UNIQUE_FUNCTION<%0...%1> %0H4n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74036)
		#define UNIQUE_FUNCTION<%0...%1> %0H4o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74037)
		#define UNIQUE_FUNCTION<%0...%1> %0H4p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74038)
		#define UNIQUE_FUNCTION<%0...%1> %0H4q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74039)
		#define UNIQUE_FUNCTION<%0...%1> %0H4r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (74039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74040)
		#define UNIQUE_FUNCTION<%0...%1> %0H4s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74041)
		#define UNIQUE_FUNCTION<%0...%1> %0H4t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74042)
		#define UNIQUE_FUNCTION<%0...%1> %0H4u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74043)
		#define UNIQUE_FUNCTION<%0...%1> %0H4v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74044)
		#define UNIQUE_FUNCTION<%0...%1> %0H4w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74045)
		#define UNIQUE_FUNCTION<%0...%1> %0H4x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (74045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74046)
		#define UNIQUE_FUNCTION<%0...%1> %0H4y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (74047)
		#define UNIQUE_FUNCTION<%0...%1> %0H4z%1
		#endinput
	#endif
#endif
