static stock const Y_UNIQUE_078976_079039_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_078976_079039
	#undef _inc_y_unique_078976_079039
#endif

#if UNIQUE_SYMBOL < (78983)
	#if UNIQUE_SYMBOL == (78975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78976)
		#define UNIQUE_FUNCTION<%0...%1> %0IH0%1
		#endinput
	#if UNIQUE_SYMBOL == (78976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78977)
		#define UNIQUE_FUNCTION<%0...%1> %0IH1%1
		#endinput
	#if UNIQUE_SYMBOL == (78977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78978)
		#define UNIQUE_FUNCTION<%0...%1> %0IH2%1
		#endinput
	#if UNIQUE_SYMBOL == (78978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78979)
		#define UNIQUE_FUNCTION<%0...%1> %0IH3%1
		#endinput
	#if UNIQUE_SYMBOL == (78979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78980)
		#define UNIQUE_FUNCTION<%0...%1> %0IH4%1
		#endinput
	#if UNIQUE_SYMBOL == (78980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78981)
		#define UNIQUE_FUNCTION<%0...%1> %0IH5%1
		#endinput
	#if UNIQUE_SYMBOL == (78981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78982)
		#define UNIQUE_FUNCTION<%0...%1> %0IH6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78983)
		#define UNIQUE_FUNCTION<%0...%1> %0IH7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (78991)
	#elseif UNIQUE_SYMBOL == (78983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78984)
		#define UNIQUE_FUNCTION<%0...%1> %0IH8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78985)
		#define UNIQUE_FUNCTION<%0...%1> %0IH9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78986)
		#define UNIQUE_FUNCTION<%0...%1> %0IH@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78987)
		#define UNIQUE_FUNCTION<%0...%1> %0IHA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78988)
		#define UNIQUE_FUNCTION<%0...%1> %0IHB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78989)
		#define UNIQUE_FUNCTION<%0...%1> %0IHC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78990)
		#define UNIQUE_FUNCTION<%0...%1> %0IHD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78991)
		#define UNIQUE_FUNCTION<%0...%1> %0IHE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (78999)
	#elseif UNIQUE_SYMBOL == (78991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78992)
		#define UNIQUE_FUNCTION<%0...%1> %0IHF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78993)
		#define UNIQUE_FUNCTION<%0...%1> %0IHG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78994)
		#define UNIQUE_FUNCTION<%0...%1> %0IHH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78995)
		#define UNIQUE_FUNCTION<%0...%1> %0IHI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78996)
		#define UNIQUE_FUNCTION<%0...%1> %0IHJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78997)
		#define UNIQUE_FUNCTION<%0...%1> %0IHK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (78997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78998)
		#define UNIQUE_FUNCTION<%0...%1> %0IHL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (78999)
		#define UNIQUE_FUNCTION<%0...%1> %0IHM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79007)
	#elseif UNIQUE_SYMBOL == (78999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79000)
		#define UNIQUE_FUNCTION<%0...%1> %0IHN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79001)
		#define UNIQUE_FUNCTION<%0...%1> %0IHO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79002)
		#define UNIQUE_FUNCTION<%0...%1> %0IHP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79003)
		#define UNIQUE_FUNCTION<%0...%1> %0IHQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79004)
		#define UNIQUE_FUNCTION<%0...%1> %0IHR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79005)
		#define UNIQUE_FUNCTION<%0...%1> %0IHS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79006)
		#define UNIQUE_FUNCTION<%0...%1> %0IHT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79007)
		#define UNIQUE_FUNCTION<%0...%1> %0IHU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79015)
	#elseif UNIQUE_SYMBOL == (79007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79008)
		#define UNIQUE_FUNCTION<%0...%1> %0IHV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79009)
		#define UNIQUE_FUNCTION<%0...%1> %0IHW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79010)
		#define UNIQUE_FUNCTION<%0...%1> %0IHX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79011)
		#define UNIQUE_FUNCTION<%0...%1> %0IHY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79012)
		#define UNIQUE_FUNCTION<%0...%1> %0IHZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79013)
		#define UNIQUE_FUNCTION<%0...%1> %0IH_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79014)
		#define UNIQUE_FUNCTION<%0...%1> %0IHa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79015)
		#define UNIQUE_FUNCTION<%0...%1> %0IHb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79023)
	#elseif UNIQUE_SYMBOL == (79015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79016)
		#define UNIQUE_FUNCTION<%0...%1> %0IHc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79017)
		#define UNIQUE_FUNCTION<%0...%1> %0IHd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79018)
		#define UNIQUE_FUNCTION<%0...%1> %0IHe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79019)
		#define UNIQUE_FUNCTION<%0...%1> %0IHf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79020)
		#define UNIQUE_FUNCTION<%0...%1> %0IHg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79021)
		#define UNIQUE_FUNCTION<%0...%1> %0IHh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79022)
		#define UNIQUE_FUNCTION<%0...%1> %0IHi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79023)
		#define UNIQUE_FUNCTION<%0...%1> %0IHj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79031)
	#elseif UNIQUE_SYMBOL == (79023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79024)
		#define UNIQUE_FUNCTION<%0...%1> %0IHk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79025)
		#define UNIQUE_FUNCTION<%0...%1> %0IHl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79026)
		#define UNIQUE_FUNCTION<%0...%1> %0IHm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79027)
		#define UNIQUE_FUNCTION<%0...%1> %0IHn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79028)
		#define UNIQUE_FUNCTION<%0...%1> %0IHo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79029)
		#define UNIQUE_FUNCTION<%0...%1> %0IHp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79030)
		#define UNIQUE_FUNCTION<%0...%1> %0IHq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79031)
		#define UNIQUE_FUNCTION<%0...%1> %0IHr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (79031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79032)
		#define UNIQUE_FUNCTION<%0...%1> %0IHs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79033)
		#define UNIQUE_FUNCTION<%0...%1> %0IHt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79034)
		#define UNIQUE_FUNCTION<%0...%1> %0IHu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79035)
		#define UNIQUE_FUNCTION<%0...%1> %0IHv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79036)
		#define UNIQUE_FUNCTION<%0...%1> %0IHw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79037)
		#define UNIQUE_FUNCTION<%0...%1> %0IHx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79038)
		#define UNIQUE_FUNCTION<%0...%1> %0IHy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79039)
		#define UNIQUE_FUNCTION<%0...%1> %0IHz%1
		#endinput
	#endif
#endif
