static stock const Y_UNIQUE_160832_160895_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_160832_160895
	#undef _inc_y_unique_160832_160895
#endif

#if UNIQUE_SYMBOL < (160839)
	#if UNIQUE_SYMBOL == (160831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160832)
		#define UNIQUE_FUNCTION<%0...%1> %0bG0%1
		#endinput
	#if UNIQUE_SYMBOL == (160832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160833)
		#define UNIQUE_FUNCTION<%0...%1> %0bG1%1
		#endinput
	#if UNIQUE_SYMBOL == (160833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160834)
		#define UNIQUE_FUNCTION<%0...%1> %0bG2%1
		#endinput
	#if UNIQUE_SYMBOL == (160834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160835)
		#define UNIQUE_FUNCTION<%0...%1> %0bG3%1
		#endinput
	#if UNIQUE_SYMBOL == (160835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160836)
		#define UNIQUE_FUNCTION<%0...%1> %0bG4%1
		#endinput
	#if UNIQUE_SYMBOL == (160836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160837)
		#define UNIQUE_FUNCTION<%0...%1> %0bG5%1
		#endinput
	#if UNIQUE_SYMBOL == (160837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160838)
		#define UNIQUE_FUNCTION<%0...%1> %0bG6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160839)
		#define UNIQUE_FUNCTION<%0...%1> %0bG7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (160847)
	#elseif UNIQUE_SYMBOL == (160839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160840)
		#define UNIQUE_FUNCTION<%0...%1> %0bG8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160841)
		#define UNIQUE_FUNCTION<%0...%1> %0bG9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160842)
		#define UNIQUE_FUNCTION<%0...%1> %0bG@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160843)
		#define UNIQUE_FUNCTION<%0...%1> %0bGA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160844)
		#define UNIQUE_FUNCTION<%0...%1> %0bGB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160845)
		#define UNIQUE_FUNCTION<%0...%1> %0bGC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160846)
		#define UNIQUE_FUNCTION<%0...%1> %0bGD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160847)
		#define UNIQUE_FUNCTION<%0...%1> %0bGE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (160855)
	#elseif UNIQUE_SYMBOL == (160847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160848)
		#define UNIQUE_FUNCTION<%0...%1> %0bGF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160849)
		#define UNIQUE_FUNCTION<%0...%1> %0bGG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160850)
		#define UNIQUE_FUNCTION<%0...%1> %0bGH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160851)
		#define UNIQUE_FUNCTION<%0...%1> %0bGI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160852)
		#define UNIQUE_FUNCTION<%0...%1> %0bGJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160853)
		#define UNIQUE_FUNCTION<%0...%1> %0bGK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160854)
		#define UNIQUE_FUNCTION<%0...%1> %0bGL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160855)
		#define UNIQUE_FUNCTION<%0...%1> %0bGM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (160863)
	#elseif UNIQUE_SYMBOL == (160855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160856)
		#define UNIQUE_FUNCTION<%0...%1> %0bGN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160857)
		#define UNIQUE_FUNCTION<%0...%1> %0bGO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160858)
		#define UNIQUE_FUNCTION<%0...%1> %0bGP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160859)
		#define UNIQUE_FUNCTION<%0...%1> %0bGQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160860)
		#define UNIQUE_FUNCTION<%0...%1> %0bGR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160861)
		#define UNIQUE_FUNCTION<%0...%1> %0bGS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160862)
		#define UNIQUE_FUNCTION<%0...%1> %0bGT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160863)
		#define UNIQUE_FUNCTION<%0...%1> %0bGU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (160871)
	#elseif UNIQUE_SYMBOL == (160863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160864)
		#define UNIQUE_FUNCTION<%0...%1> %0bGV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160865)
		#define UNIQUE_FUNCTION<%0...%1> %0bGW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160866)
		#define UNIQUE_FUNCTION<%0...%1> %0bGX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160867)
		#define UNIQUE_FUNCTION<%0...%1> %0bGY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160868)
		#define UNIQUE_FUNCTION<%0...%1> %0bGZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160869)
		#define UNIQUE_FUNCTION<%0...%1> %0bG_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160870)
		#define UNIQUE_FUNCTION<%0...%1> %0bGa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160871)
		#define UNIQUE_FUNCTION<%0...%1> %0bGb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (160879)
	#elseif UNIQUE_SYMBOL == (160871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160872)
		#define UNIQUE_FUNCTION<%0...%1> %0bGc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160873)
		#define UNIQUE_FUNCTION<%0...%1> %0bGd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160874)
		#define UNIQUE_FUNCTION<%0...%1> %0bGe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160875)
		#define UNIQUE_FUNCTION<%0...%1> %0bGf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160876)
		#define UNIQUE_FUNCTION<%0...%1> %0bGg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160877)
		#define UNIQUE_FUNCTION<%0...%1> %0bGh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160878)
		#define UNIQUE_FUNCTION<%0...%1> %0bGi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160879)
		#define UNIQUE_FUNCTION<%0...%1> %0bGj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (160887)
	#elseif UNIQUE_SYMBOL == (160879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160880)
		#define UNIQUE_FUNCTION<%0...%1> %0bGk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160881)
		#define UNIQUE_FUNCTION<%0...%1> %0bGl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160882)
		#define UNIQUE_FUNCTION<%0...%1> %0bGm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160883)
		#define UNIQUE_FUNCTION<%0...%1> %0bGn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160884)
		#define UNIQUE_FUNCTION<%0...%1> %0bGo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160885)
		#define UNIQUE_FUNCTION<%0...%1> %0bGp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160886)
		#define UNIQUE_FUNCTION<%0...%1> %0bGq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160887)
		#define UNIQUE_FUNCTION<%0...%1> %0bGr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (160887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160888)
		#define UNIQUE_FUNCTION<%0...%1> %0bGs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160889)
		#define UNIQUE_FUNCTION<%0...%1> %0bGt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160890)
		#define UNIQUE_FUNCTION<%0...%1> %0bGu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160891)
		#define UNIQUE_FUNCTION<%0...%1> %0bGv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160892)
		#define UNIQUE_FUNCTION<%0...%1> %0bGw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160893)
		#define UNIQUE_FUNCTION<%0...%1> %0bGx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (160893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160894)
		#define UNIQUE_FUNCTION<%0...%1> %0bGy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (160895)
		#define UNIQUE_FUNCTION<%0...%1> %0bGz%1
		#endinput
	#endif
#endif
