static stock const Y_UNIQUE_090752_090815_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_090752_090815
	#undef _inc_y_unique_090752_090815
#endif

#if UNIQUE_SYMBOL < (90759)
	#if UNIQUE_SYMBOL == (90751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90752)
		#define UNIQUE_FUNCTION<%0...%1> %0L@0%1
		#endinput
	#if UNIQUE_SYMBOL == (90752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90753)
		#define UNIQUE_FUNCTION<%0...%1> %0L@1%1
		#endinput
	#if UNIQUE_SYMBOL == (90753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90754)
		#define UNIQUE_FUNCTION<%0...%1> %0L@2%1
		#endinput
	#if UNIQUE_SYMBOL == (90754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90755)
		#define UNIQUE_FUNCTION<%0...%1> %0L@3%1
		#endinput
	#if UNIQUE_SYMBOL == (90755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90756)
		#define UNIQUE_FUNCTION<%0...%1> %0L@4%1
		#endinput
	#if UNIQUE_SYMBOL == (90756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90757)
		#define UNIQUE_FUNCTION<%0...%1> %0L@5%1
		#endinput
	#if UNIQUE_SYMBOL == (90757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90758)
		#define UNIQUE_FUNCTION<%0...%1> %0L@6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90759)
		#define UNIQUE_FUNCTION<%0...%1> %0L@7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90767)
	#elseif UNIQUE_SYMBOL == (90759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90760)
		#define UNIQUE_FUNCTION<%0...%1> %0L@8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90761)
		#define UNIQUE_FUNCTION<%0...%1> %0L@9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90762)
		#define UNIQUE_FUNCTION<%0...%1> %0L@@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90763)
		#define UNIQUE_FUNCTION<%0...%1> %0L@A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90764)
		#define UNIQUE_FUNCTION<%0...%1> %0L@B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90765)
		#define UNIQUE_FUNCTION<%0...%1> %0L@C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90766)
		#define UNIQUE_FUNCTION<%0...%1> %0L@D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90767)
		#define UNIQUE_FUNCTION<%0...%1> %0L@E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90775)
	#elseif UNIQUE_SYMBOL == (90767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90768)
		#define UNIQUE_FUNCTION<%0...%1> %0L@F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90769)
		#define UNIQUE_FUNCTION<%0...%1> %0L@G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90770)
		#define UNIQUE_FUNCTION<%0...%1> %0L@H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90771)
		#define UNIQUE_FUNCTION<%0...%1> %0L@I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90772)
		#define UNIQUE_FUNCTION<%0...%1> %0L@J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90773)
		#define UNIQUE_FUNCTION<%0...%1> %0L@K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90774)
		#define UNIQUE_FUNCTION<%0...%1> %0L@L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90775)
		#define UNIQUE_FUNCTION<%0...%1> %0L@M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90783)
	#elseif UNIQUE_SYMBOL == (90775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90776)
		#define UNIQUE_FUNCTION<%0...%1> %0L@N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90777)
		#define UNIQUE_FUNCTION<%0...%1> %0L@O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90778)
		#define UNIQUE_FUNCTION<%0...%1> %0L@P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90779)
		#define UNIQUE_FUNCTION<%0...%1> %0L@Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90780)
		#define UNIQUE_FUNCTION<%0...%1> %0L@R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90781)
		#define UNIQUE_FUNCTION<%0...%1> %0L@S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90782)
		#define UNIQUE_FUNCTION<%0...%1> %0L@T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90783)
		#define UNIQUE_FUNCTION<%0...%1> %0L@U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90791)
	#elseif UNIQUE_SYMBOL == (90783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90784)
		#define UNIQUE_FUNCTION<%0...%1> %0L@V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90785)
		#define UNIQUE_FUNCTION<%0...%1> %0L@W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90786)
		#define UNIQUE_FUNCTION<%0...%1> %0L@X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90787)
		#define UNIQUE_FUNCTION<%0...%1> %0L@Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90788)
		#define UNIQUE_FUNCTION<%0...%1> %0L@Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90789)
		#define UNIQUE_FUNCTION<%0...%1> %0L@_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90790)
		#define UNIQUE_FUNCTION<%0...%1> %0L@a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90791)
		#define UNIQUE_FUNCTION<%0...%1> %0L@b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90799)
	#elseif UNIQUE_SYMBOL == (90791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90792)
		#define UNIQUE_FUNCTION<%0...%1> %0L@c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90793)
		#define UNIQUE_FUNCTION<%0...%1> %0L@d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90794)
		#define UNIQUE_FUNCTION<%0...%1> %0L@e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90795)
		#define UNIQUE_FUNCTION<%0...%1> %0L@f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90796)
		#define UNIQUE_FUNCTION<%0...%1> %0L@g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90797)
		#define UNIQUE_FUNCTION<%0...%1> %0L@h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90798)
		#define UNIQUE_FUNCTION<%0...%1> %0L@i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90799)
		#define UNIQUE_FUNCTION<%0...%1> %0L@j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90807)
	#elseif UNIQUE_SYMBOL == (90799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90800)
		#define UNIQUE_FUNCTION<%0...%1> %0L@k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90801)
		#define UNIQUE_FUNCTION<%0...%1> %0L@l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90802)
		#define UNIQUE_FUNCTION<%0...%1> %0L@m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90803)
		#define UNIQUE_FUNCTION<%0...%1> %0L@n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90804)
		#define UNIQUE_FUNCTION<%0...%1> %0L@o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90805)
		#define UNIQUE_FUNCTION<%0...%1> %0L@p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90806)
		#define UNIQUE_FUNCTION<%0...%1> %0L@q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90807)
		#define UNIQUE_FUNCTION<%0...%1> %0L@r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (90807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90808)
		#define UNIQUE_FUNCTION<%0...%1> %0L@s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90809)
		#define UNIQUE_FUNCTION<%0...%1> %0L@t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90810)
		#define UNIQUE_FUNCTION<%0...%1> %0L@u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90811)
		#define UNIQUE_FUNCTION<%0...%1> %0L@v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90812)
		#define UNIQUE_FUNCTION<%0...%1> %0L@w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90813)
		#define UNIQUE_FUNCTION<%0...%1> %0L@x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90814)
		#define UNIQUE_FUNCTION<%0...%1> %0L@y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90815)
		#define UNIQUE_FUNCTION<%0...%1> %0L@z%1
		#endinput
	#endif
#endif
