static stock const Y_UNIQUE_098240_098303_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_098240_098303
	#undef _inc_y_unique_098240_098303
#endif

#if UNIQUE_SYMBOL < (98247)
	#if UNIQUE_SYMBOL == (98239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98240)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz0%1
		#endinput
	#if UNIQUE_SYMBOL == (98240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98241)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz1%1
		#endinput
	#if UNIQUE_SYMBOL == (98241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98242)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz2%1
		#endinput
	#if UNIQUE_SYMBOL == (98242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98243)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz3%1
		#endinput
	#if UNIQUE_SYMBOL == (98243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98244)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz4%1
		#endinput
	#if UNIQUE_SYMBOL == (98244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98245)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz5%1
		#endinput
	#if UNIQUE_SYMBOL == (98245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98246)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98247)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98255)
	#elseif UNIQUE_SYMBOL == (98247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98248)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98249)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98250)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98251)
		#define UNIQUE_FUNCTION<%0...%1> %0MzA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98252)
		#define UNIQUE_FUNCTION<%0...%1> %0MzB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98253)
		#define UNIQUE_FUNCTION<%0...%1> %0MzC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98254)
		#define UNIQUE_FUNCTION<%0...%1> %0MzD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98255)
		#define UNIQUE_FUNCTION<%0...%1> %0MzE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98263)
	#elseif UNIQUE_SYMBOL == (98255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98256)
		#define UNIQUE_FUNCTION<%0...%1> %0MzF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98257)
		#define UNIQUE_FUNCTION<%0...%1> %0MzG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98258)
		#define UNIQUE_FUNCTION<%0...%1> %0MzH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98259)
		#define UNIQUE_FUNCTION<%0...%1> %0MzI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98260)
		#define UNIQUE_FUNCTION<%0...%1> %0MzJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98261)
		#define UNIQUE_FUNCTION<%0...%1> %0MzK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98262)
		#define UNIQUE_FUNCTION<%0...%1> %0MzL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98263)
		#define UNIQUE_FUNCTION<%0...%1> %0MzM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98271)
	#elseif UNIQUE_SYMBOL == (98263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98264)
		#define UNIQUE_FUNCTION<%0...%1> %0MzN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98265)
		#define UNIQUE_FUNCTION<%0...%1> %0MzO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98266)
		#define UNIQUE_FUNCTION<%0...%1> %0MzP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98267)
		#define UNIQUE_FUNCTION<%0...%1> %0MzQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98268)
		#define UNIQUE_FUNCTION<%0...%1> %0MzR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98269)
		#define UNIQUE_FUNCTION<%0...%1> %0MzS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98270)
		#define UNIQUE_FUNCTION<%0...%1> %0MzT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98271)
		#define UNIQUE_FUNCTION<%0...%1> %0MzU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98279)
	#elseif UNIQUE_SYMBOL == (98271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98272)
		#define UNIQUE_FUNCTION<%0...%1> %0MzV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98273)
		#define UNIQUE_FUNCTION<%0...%1> %0MzW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98274)
		#define UNIQUE_FUNCTION<%0...%1> %0MzX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98275)
		#define UNIQUE_FUNCTION<%0...%1> %0MzY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98276)
		#define UNIQUE_FUNCTION<%0...%1> %0MzZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98277)
		#define UNIQUE_FUNCTION<%0...%1> %0Mz_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98278)
		#define UNIQUE_FUNCTION<%0...%1> %0Mza%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98279)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98287)
	#elseif UNIQUE_SYMBOL == (98279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98280)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98281)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98282)
		#define UNIQUE_FUNCTION<%0...%1> %0Mze%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98283)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98284)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98285)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98286)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98287)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (98295)
	#elseif UNIQUE_SYMBOL == (98287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98288)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98289)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98290)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98291)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98292)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98293)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98294)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98295)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (98295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98296)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98297)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98298)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98299)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98300)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98301)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (98301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98302)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (98303)
		#define UNIQUE_FUNCTION<%0...%1> %0Mzz%1
		#endinput
	#endif
#endif
