static stock const Y_UNIQUE_009920_009983_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_009920_009983
	#undef _inc_y_unique_009920_009983
#endif

#if UNIQUE_SYMBOL < (9927)
	#if UNIQUE_SYMBOL == (9919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9920)
		#define UNIQUE_FUNCTION<%0...%1> %02Q0%1
		#endinput
	#if UNIQUE_SYMBOL == (9920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9921)
		#define UNIQUE_FUNCTION<%0...%1> %02Q1%1
		#endinput
	#if UNIQUE_SYMBOL == (9921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9922)
		#define UNIQUE_FUNCTION<%0...%1> %02Q2%1
		#endinput
	#if UNIQUE_SYMBOL == (9922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9923)
		#define UNIQUE_FUNCTION<%0...%1> %02Q3%1
		#endinput
	#if UNIQUE_SYMBOL == (9923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9924)
		#define UNIQUE_FUNCTION<%0...%1> %02Q4%1
		#endinput
	#if UNIQUE_SYMBOL == (9924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9925)
		#define UNIQUE_FUNCTION<%0...%1> %02Q5%1
		#endinput
	#if UNIQUE_SYMBOL == (9925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9926)
		#define UNIQUE_FUNCTION<%0...%1> %02Q6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9927)
		#define UNIQUE_FUNCTION<%0...%1> %02Q7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (9935)
	#elseif UNIQUE_SYMBOL == (9927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9928)
		#define UNIQUE_FUNCTION<%0...%1> %02Q8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9929)
		#define UNIQUE_FUNCTION<%0...%1> %02Q9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9930)
		#define UNIQUE_FUNCTION<%0...%1> %02Q@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9931)
		#define UNIQUE_FUNCTION<%0...%1> %02QA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9932)
		#define UNIQUE_FUNCTION<%0...%1> %02QB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9933)
		#define UNIQUE_FUNCTION<%0...%1> %02QC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9934)
		#define UNIQUE_FUNCTION<%0...%1> %02QD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9935)
		#define UNIQUE_FUNCTION<%0...%1> %02QE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (9943)
	#elseif UNIQUE_SYMBOL == (9935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9936)
		#define UNIQUE_FUNCTION<%0...%1> %02QF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9937)
		#define UNIQUE_FUNCTION<%0...%1> %02QG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9938)
		#define UNIQUE_FUNCTION<%0...%1> %02QH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9939)
		#define UNIQUE_FUNCTION<%0...%1> %02QI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9940)
		#define UNIQUE_FUNCTION<%0...%1> %02QJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9941)
		#define UNIQUE_FUNCTION<%0...%1> %02QK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9942)
		#define UNIQUE_FUNCTION<%0...%1> %02QL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9943)
		#define UNIQUE_FUNCTION<%0...%1> %02QM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (9951)
	#elseif UNIQUE_SYMBOL == (9943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9944)
		#define UNIQUE_FUNCTION<%0...%1> %02QN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9945)
		#define UNIQUE_FUNCTION<%0...%1> %02QO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9946)
		#define UNIQUE_FUNCTION<%0...%1> %02QP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9947)
		#define UNIQUE_FUNCTION<%0...%1> %02QQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9948)
		#define UNIQUE_FUNCTION<%0...%1> %02QR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9949)
		#define UNIQUE_FUNCTION<%0...%1> %02QS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9950)
		#define UNIQUE_FUNCTION<%0...%1> %02QT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9951)
		#define UNIQUE_FUNCTION<%0...%1> %02QU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (9959)
	#elseif UNIQUE_SYMBOL == (9951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9952)
		#define UNIQUE_FUNCTION<%0...%1> %02QV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9953)
		#define UNIQUE_FUNCTION<%0...%1> %02QW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9954)
		#define UNIQUE_FUNCTION<%0...%1> %02QX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9955)
		#define UNIQUE_FUNCTION<%0...%1> %02QY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9956)
		#define UNIQUE_FUNCTION<%0...%1> %02QZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9957)
		#define UNIQUE_FUNCTION<%0...%1> %02Q_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9958)
		#define UNIQUE_FUNCTION<%0...%1> %02Qa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9959)
		#define UNIQUE_FUNCTION<%0...%1> %02Qb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (9967)
	#elseif UNIQUE_SYMBOL == (9959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9960)
		#define UNIQUE_FUNCTION<%0...%1> %02Qc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9961)
		#define UNIQUE_FUNCTION<%0...%1> %02Qd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9962)
		#define UNIQUE_FUNCTION<%0...%1> %02Qe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9963)
		#define UNIQUE_FUNCTION<%0...%1> %02Qf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9964)
		#define UNIQUE_FUNCTION<%0...%1> %02Qg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9965)
		#define UNIQUE_FUNCTION<%0...%1> %02Qh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9966)
		#define UNIQUE_FUNCTION<%0...%1> %02Qi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9967)
		#define UNIQUE_FUNCTION<%0...%1> %02Qj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (9975)
	#elseif UNIQUE_SYMBOL == (9967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9968)
		#define UNIQUE_FUNCTION<%0...%1> %02Qk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9969)
		#define UNIQUE_FUNCTION<%0...%1> %02Ql%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9970)
		#define UNIQUE_FUNCTION<%0...%1> %02Qm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9971)
		#define UNIQUE_FUNCTION<%0...%1> %02Qn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9972)
		#define UNIQUE_FUNCTION<%0...%1> %02Qo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9973)
		#define UNIQUE_FUNCTION<%0...%1> %02Qp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9974)
		#define UNIQUE_FUNCTION<%0...%1> %02Qq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9975)
		#define UNIQUE_FUNCTION<%0...%1> %02Qr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (9975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9976)
		#define UNIQUE_FUNCTION<%0...%1> %02Qs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9977)
		#define UNIQUE_FUNCTION<%0...%1> %02Qt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9978)
		#define UNIQUE_FUNCTION<%0...%1> %02Qu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9979)
		#define UNIQUE_FUNCTION<%0...%1> %02Qv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9980)
		#define UNIQUE_FUNCTION<%0...%1> %02Qw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9981)
		#define UNIQUE_FUNCTION<%0...%1> %02Qx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (9981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9982)
		#define UNIQUE_FUNCTION<%0...%1> %02Qy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (9983)
		#define UNIQUE_FUNCTION<%0...%1> %02Qz%1
		#endinput
	#endif
#endif
