static stock const Y_UNIQUE_132608_132671_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_132608_132671
	#undef _inc_y_unique_132608_132671
#endif

#if UNIQUE_SYMBOL < (132615)
	#if UNIQUE_SYMBOL == (132607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132608)
		#define UNIQUE_FUNCTION<%0...%1> %0VN0%1
		#endinput
	#if UNIQUE_SYMBOL == (132608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132609)
		#define UNIQUE_FUNCTION<%0...%1> %0VN1%1
		#endinput
	#if UNIQUE_SYMBOL == (132609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132610)
		#define UNIQUE_FUNCTION<%0...%1> %0VN2%1
		#endinput
	#if UNIQUE_SYMBOL == (132610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132611)
		#define UNIQUE_FUNCTION<%0...%1> %0VN3%1
		#endinput
	#if UNIQUE_SYMBOL == (132611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132612)
		#define UNIQUE_FUNCTION<%0...%1> %0VN4%1
		#endinput
	#if UNIQUE_SYMBOL == (132612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132613)
		#define UNIQUE_FUNCTION<%0...%1> %0VN5%1
		#endinput
	#if UNIQUE_SYMBOL == (132613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132614)
		#define UNIQUE_FUNCTION<%0...%1> %0VN6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132615)
		#define UNIQUE_FUNCTION<%0...%1> %0VN7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132623)
	#elseif UNIQUE_SYMBOL == (132615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132616)
		#define UNIQUE_FUNCTION<%0...%1> %0VN8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132617)
		#define UNIQUE_FUNCTION<%0...%1> %0VN9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132618)
		#define UNIQUE_FUNCTION<%0...%1> %0VN@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132619)
		#define UNIQUE_FUNCTION<%0...%1> %0VNA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132620)
		#define UNIQUE_FUNCTION<%0...%1> %0VNB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132621)
		#define UNIQUE_FUNCTION<%0...%1> %0VNC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132622)
		#define UNIQUE_FUNCTION<%0...%1> %0VND%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132623)
		#define UNIQUE_FUNCTION<%0...%1> %0VNE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132631)
	#elseif UNIQUE_SYMBOL == (132623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132624)
		#define UNIQUE_FUNCTION<%0...%1> %0VNF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132625)
		#define UNIQUE_FUNCTION<%0...%1> %0VNG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132626)
		#define UNIQUE_FUNCTION<%0...%1> %0VNH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132627)
		#define UNIQUE_FUNCTION<%0...%1> %0VNI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132628)
		#define UNIQUE_FUNCTION<%0...%1> %0VNJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132629)
		#define UNIQUE_FUNCTION<%0...%1> %0VNK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132630)
		#define UNIQUE_FUNCTION<%0...%1> %0VNL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132631)
		#define UNIQUE_FUNCTION<%0...%1> %0VNM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132639)
	#elseif UNIQUE_SYMBOL == (132631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132632)
		#define UNIQUE_FUNCTION<%0...%1> %0VNN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132633)
		#define UNIQUE_FUNCTION<%0...%1> %0VNO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132634)
		#define UNIQUE_FUNCTION<%0...%1> %0VNP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132635)
		#define UNIQUE_FUNCTION<%0...%1> %0VNQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132636)
		#define UNIQUE_FUNCTION<%0...%1> %0VNR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132637)
		#define UNIQUE_FUNCTION<%0...%1> %0VNS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132638)
		#define UNIQUE_FUNCTION<%0...%1> %0VNT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132639)
		#define UNIQUE_FUNCTION<%0...%1> %0VNU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132647)
	#elseif UNIQUE_SYMBOL == (132639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132640)
		#define UNIQUE_FUNCTION<%0...%1> %0VNV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132641)
		#define UNIQUE_FUNCTION<%0...%1> %0VNW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132642)
		#define UNIQUE_FUNCTION<%0...%1> %0VNX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132643)
		#define UNIQUE_FUNCTION<%0...%1> %0VNY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132644)
		#define UNIQUE_FUNCTION<%0...%1> %0VNZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132645)
		#define UNIQUE_FUNCTION<%0...%1> %0VN_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132646)
		#define UNIQUE_FUNCTION<%0...%1> %0VNa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132647)
		#define UNIQUE_FUNCTION<%0...%1> %0VNb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132655)
	#elseif UNIQUE_SYMBOL == (132647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132648)
		#define UNIQUE_FUNCTION<%0...%1> %0VNc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132649)
		#define UNIQUE_FUNCTION<%0...%1> %0VNd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132650)
		#define UNIQUE_FUNCTION<%0...%1> %0VNe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132651)
		#define UNIQUE_FUNCTION<%0...%1> %0VNf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132652)
		#define UNIQUE_FUNCTION<%0...%1> %0VNg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132653)
		#define UNIQUE_FUNCTION<%0...%1> %0VNh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132654)
		#define UNIQUE_FUNCTION<%0...%1> %0VNi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132655)
		#define UNIQUE_FUNCTION<%0...%1> %0VNj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132663)
	#elseif UNIQUE_SYMBOL == (132655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132656)
		#define UNIQUE_FUNCTION<%0...%1> %0VNk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132657)
		#define UNIQUE_FUNCTION<%0...%1> %0VNl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132658)
		#define UNIQUE_FUNCTION<%0...%1> %0VNm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132659)
		#define UNIQUE_FUNCTION<%0...%1> %0VNn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132660)
		#define UNIQUE_FUNCTION<%0...%1> %0VNo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132661)
		#define UNIQUE_FUNCTION<%0...%1> %0VNp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132662)
		#define UNIQUE_FUNCTION<%0...%1> %0VNq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132663)
		#define UNIQUE_FUNCTION<%0...%1> %0VNr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (132663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132664)
		#define UNIQUE_FUNCTION<%0...%1> %0VNs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132665)
		#define UNIQUE_FUNCTION<%0...%1> %0VNt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132666)
		#define UNIQUE_FUNCTION<%0...%1> %0VNu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132667)
		#define UNIQUE_FUNCTION<%0...%1> %0VNv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132668)
		#define UNIQUE_FUNCTION<%0...%1> %0VNw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132669)
		#define UNIQUE_FUNCTION<%0...%1> %0VNx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132670)
		#define UNIQUE_FUNCTION<%0...%1> %0VNy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132671)
		#define UNIQUE_FUNCTION<%0...%1> %0VNz%1
		#endinput
	#endif
#endif
