static stock const Y_UNIQUE_145920_145983_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_145920_145983
	#undef _inc_y_unique_145920_145983
#endif

#if UNIQUE_SYMBOL < (145927)
	#if UNIQUE_SYMBOL == (145919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145920)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc0%1
		#endinput
	#if UNIQUE_SYMBOL == (145920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145921)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc1%1
		#endinput
	#if UNIQUE_SYMBOL == (145921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145922)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc2%1
		#endinput
	#if UNIQUE_SYMBOL == (145922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145923)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc3%1
		#endinput
	#if UNIQUE_SYMBOL == (145923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145924)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc4%1
		#endinput
	#if UNIQUE_SYMBOL == (145924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145925)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc5%1
		#endinput
	#if UNIQUE_SYMBOL == (145925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145926)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145927)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145935)
	#elseif UNIQUE_SYMBOL == (145927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145928)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145929)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145930)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145931)
		#define UNIQUE_FUNCTION<%0...%1> %0YcA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145932)
		#define UNIQUE_FUNCTION<%0...%1> %0YcB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145933)
		#define UNIQUE_FUNCTION<%0...%1> %0YcC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145934)
		#define UNIQUE_FUNCTION<%0...%1> %0YcD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145935)
		#define UNIQUE_FUNCTION<%0...%1> %0YcE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145943)
	#elseif UNIQUE_SYMBOL == (145935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145936)
		#define UNIQUE_FUNCTION<%0...%1> %0YcF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145937)
		#define UNIQUE_FUNCTION<%0...%1> %0YcG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145938)
		#define UNIQUE_FUNCTION<%0...%1> %0YcH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145939)
		#define UNIQUE_FUNCTION<%0...%1> %0YcI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145940)
		#define UNIQUE_FUNCTION<%0...%1> %0YcJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145941)
		#define UNIQUE_FUNCTION<%0...%1> %0YcK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145942)
		#define UNIQUE_FUNCTION<%0...%1> %0YcL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145943)
		#define UNIQUE_FUNCTION<%0...%1> %0YcM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145951)
	#elseif UNIQUE_SYMBOL == (145943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145944)
		#define UNIQUE_FUNCTION<%0...%1> %0YcN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145945)
		#define UNIQUE_FUNCTION<%0...%1> %0YcO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145946)
		#define UNIQUE_FUNCTION<%0...%1> %0YcP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145947)
		#define UNIQUE_FUNCTION<%0...%1> %0YcQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145948)
		#define UNIQUE_FUNCTION<%0...%1> %0YcR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145949)
		#define UNIQUE_FUNCTION<%0...%1> %0YcS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145950)
		#define UNIQUE_FUNCTION<%0...%1> %0YcT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145951)
		#define UNIQUE_FUNCTION<%0...%1> %0YcU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145959)
	#elseif UNIQUE_SYMBOL == (145951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145952)
		#define UNIQUE_FUNCTION<%0...%1> %0YcV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145953)
		#define UNIQUE_FUNCTION<%0...%1> %0YcW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145954)
		#define UNIQUE_FUNCTION<%0...%1> %0YcX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145955)
		#define UNIQUE_FUNCTION<%0...%1> %0YcY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145956)
		#define UNIQUE_FUNCTION<%0...%1> %0YcZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145957)
		#define UNIQUE_FUNCTION<%0...%1> %0Yc_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145958)
		#define UNIQUE_FUNCTION<%0...%1> %0Yca%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145959)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145967)
	#elseif UNIQUE_SYMBOL == (145959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145960)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145961)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145962)
		#define UNIQUE_FUNCTION<%0...%1> %0Yce%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145963)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145964)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145965)
		#define UNIQUE_FUNCTION<%0...%1> %0Ych%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145966)
		#define UNIQUE_FUNCTION<%0...%1> %0Yci%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145967)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145975)
	#elseif UNIQUE_SYMBOL == (145967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145968)
		#define UNIQUE_FUNCTION<%0...%1> %0Yck%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145969)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145970)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145971)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145972)
		#define UNIQUE_FUNCTION<%0...%1> %0Yco%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145973)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145974)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145975)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (145975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145976)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145977)
		#define UNIQUE_FUNCTION<%0...%1> %0Yct%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145978)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145979)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145980)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145981)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145982)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145983)
		#define UNIQUE_FUNCTION<%0...%1> %0Ycz%1
		#endinput
	#endif
#endif
