static stock const Y_UNIQUE_242752_242815_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_242752_242815
	#undef _inc_y_unique_242752_242815
#endif

#if UNIQUE_SYMBOL < (242759)
	#if UNIQUE_SYMBOL == (242751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242752)
		#define UNIQUE_FUNCTION<%0...%1> %0vG0%1
		#endinput
	#if UNIQUE_SYMBOL == (242752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242753)
		#define UNIQUE_FUNCTION<%0...%1> %0vG1%1
		#endinput
	#if UNIQUE_SYMBOL == (242753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242754)
		#define UNIQUE_FUNCTION<%0...%1> %0vG2%1
		#endinput
	#if UNIQUE_SYMBOL == (242754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242755)
		#define UNIQUE_FUNCTION<%0...%1> %0vG3%1
		#endinput
	#if UNIQUE_SYMBOL == (242755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242756)
		#define UNIQUE_FUNCTION<%0...%1> %0vG4%1
		#endinput
	#if UNIQUE_SYMBOL == (242756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242757)
		#define UNIQUE_FUNCTION<%0...%1> %0vG5%1
		#endinput
	#if UNIQUE_SYMBOL == (242757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242758)
		#define UNIQUE_FUNCTION<%0...%1> %0vG6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242759)
		#define UNIQUE_FUNCTION<%0...%1> %0vG7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242767)
	#elseif UNIQUE_SYMBOL == (242759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242760)
		#define UNIQUE_FUNCTION<%0...%1> %0vG8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242761)
		#define UNIQUE_FUNCTION<%0...%1> %0vG9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242762)
		#define UNIQUE_FUNCTION<%0...%1> %0vG@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242763)
		#define UNIQUE_FUNCTION<%0...%1> %0vGA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242764)
		#define UNIQUE_FUNCTION<%0...%1> %0vGB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242765)
		#define UNIQUE_FUNCTION<%0...%1> %0vGC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242766)
		#define UNIQUE_FUNCTION<%0...%1> %0vGD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242767)
		#define UNIQUE_FUNCTION<%0...%1> %0vGE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242775)
	#elseif UNIQUE_SYMBOL == (242767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242768)
		#define UNIQUE_FUNCTION<%0...%1> %0vGF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242769)
		#define UNIQUE_FUNCTION<%0...%1> %0vGG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242770)
		#define UNIQUE_FUNCTION<%0...%1> %0vGH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242771)
		#define UNIQUE_FUNCTION<%0...%1> %0vGI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242772)
		#define UNIQUE_FUNCTION<%0...%1> %0vGJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242773)
		#define UNIQUE_FUNCTION<%0...%1> %0vGK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242774)
		#define UNIQUE_FUNCTION<%0...%1> %0vGL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242775)
		#define UNIQUE_FUNCTION<%0...%1> %0vGM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242783)
	#elseif UNIQUE_SYMBOL == (242775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242776)
		#define UNIQUE_FUNCTION<%0...%1> %0vGN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242777)
		#define UNIQUE_FUNCTION<%0...%1> %0vGO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242778)
		#define UNIQUE_FUNCTION<%0...%1> %0vGP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242779)
		#define UNIQUE_FUNCTION<%0...%1> %0vGQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242780)
		#define UNIQUE_FUNCTION<%0...%1> %0vGR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242781)
		#define UNIQUE_FUNCTION<%0...%1> %0vGS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242782)
		#define UNIQUE_FUNCTION<%0...%1> %0vGT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242783)
		#define UNIQUE_FUNCTION<%0...%1> %0vGU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242791)
	#elseif UNIQUE_SYMBOL == (242783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242784)
		#define UNIQUE_FUNCTION<%0...%1> %0vGV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242785)
		#define UNIQUE_FUNCTION<%0...%1> %0vGW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242786)
		#define UNIQUE_FUNCTION<%0...%1> %0vGX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242787)
		#define UNIQUE_FUNCTION<%0...%1> %0vGY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242788)
		#define UNIQUE_FUNCTION<%0...%1> %0vGZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242789)
		#define UNIQUE_FUNCTION<%0...%1> %0vG_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242790)
		#define UNIQUE_FUNCTION<%0...%1> %0vGa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242791)
		#define UNIQUE_FUNCTION<%0...%1> %0vGb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242799)
	#elseif UNIQUE_SYMBOL == (242791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242792)
		#define UNIQUE_FUNCTION<%0...%1> %0vGc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242793)
		#define UNIQUE_FUNCTION<%0...%1> %0vGd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242794)
		#define UNIQUE_FUNCTION<%0...%1> %0vGe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242795)
		#define UNIQUE_FUNCTION<%0...%1> %0vGf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242796)
		#define UNIQUE_FUNCTION<%0...%1> %0vGg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242797)
		#define UNIQUE_FUNCTION<%0...%1> %0vGh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242798)
		#define UNIQUE_FUNCTION<%0...%1> %0vGi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242799)
		#define UNIQUE_FUNCTION<%0...%1> %0vGj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242807)
	#elseif UNIQUE_SYMBOL == (242799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242800)
		#define UNIQUE_FUNCTION<%0...%1> %0vGk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242801)
		#define UNIQUE_FUNCTION<%0...%1> %0vGl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242802)
		#define UNIQUE_FUNCTION<%0...%1> %0vGm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242803)
		#define UNIQUE_FUNCTION<%0...%1> %0vGn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242804)
		#define UNIQUE_FUNCTION<%0...%1> %0vGo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242805)
		#define UNIQUE_FUNCTION<%0...%1> %0vGp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242806)
		#define UNIQUE_FUNCTION<%0...%1> %0vGq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242807)
		#define UNIQUE_FUNCTION<%0...%1> %0vGr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (242807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242808)
		#define UNIQUE_FUNCTION<%0...%1> %0vGs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242809)
		#define UNIQUE_FUNCTION<%0...%1> %0vGt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242810)
		#define UNIQUE_FUNCTION<%0...%1> %0vGu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242811)
		#define UNIQUE_FUNCTION<%0...%1> %0vGv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242812)
		#define UNIQUE_FUNCTION<%0...%1> %0vGw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242813)
		#define UNIQUE_FUNCTION<%0...%1> %0vGx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242814)
		#define UNIQUE_FUNCTION<%0...%1> %0vGy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242815)
		#define UNIQUE_FUNCTION<%0...%1> %0vGz%1
		#endinput
	#endif
#endif
