static stock const Y_UNIQUE_104832_104895_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_104832_104895
	#undef _inc_y_unique_104832_104895
#endif

#if UNIQUE_SYMBOL < (104839)
	#if UNIQUE_SYMBOL == (104831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104832)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa0%1
		#endinput
	#if UNIQUE_SYMBOL == (104832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104833)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa1%1
		#endinput
	#if UNIQUE_SYMBOL == (104833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104834)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa2%1
		#endinput
	#if UNIQUE_SYMBOL == (104834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104835)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa3%1
		#endinput
	#if UNIQUE_SYMBOL == (104835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104836)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa4%1
		#endinput
	#if UNIQUE_SYMBOL == (104836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104837)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa5%1
		#endinput
	#if UNIQUE_SYMBOL == (104837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104838)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104839)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104847)
	#elseif UNIQUE_SYMBOL == (104839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104840)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104841)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104842)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104843)
		#define UNIQUE_FUNCTION<%0...%1> %0OaA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104844)
		#define UNIQUE_FUNCTION<%0...%1> %0OaB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104845)
		#define UNIQUE_FUNCTION<%0...%1> %0OaC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104846)
		#define UNIQUE_FUNCTION<%0...%1> %0OaD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104847)
		#define UNIQUE_FUNCTION<%0...%1> %0OaE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104855)
	#elseif UNIQUE_SYMBOL == (104847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104848)
		#define UNIQUE_FUNCTION<%0...%1> %0OaF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104849)
		#define UNIQUE_FUNCTION<%0...%1> %0OaG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104850)
		#define UNIQUE_FUNCTION<%0...%1> %0OaH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104851)
		#define UNIQUE_FUNCTION<%0...%1> %0OaI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104852)
		#define UNIQUE_FUNCTION<%0...%1> %0OaJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104853)
		#define UNIQUE_FUNCTION<%0...%1> %0OaK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104854)
		#define UNIQUE_FUNCTION<%0...%1> %0OaL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104855)
		#define UNIQUE_FUNCTION<%0...%1> %0OaM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104863)
	#elseif UNIQUE_SYMBOL == (104855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104856)
		#define UNIQUE_FUNCTION<%0...%1> %0OaN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104857)
		#define UNIQUE_FUNCTION<%0...%1> %0OaO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104858)
		#define UNIQUE_FUNCTION<%0...%1> %0OaP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104859)
		#define UNIQUE_FUNCTION<%0...%1> %0OaQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104860)
		#define UNIQUE_FUNCTION<%0...%1> %0OaR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104861)
		#define UNIQUE_FUNCTION<%0...%1> %0OaS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104862)
		#define UNIQUE_FUNCTION<%0...%1> %0OaT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104863)
		#define UNIQUE_FUNCTION<%0...%1> %0OaU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104871)
	#elseif UNIQUE_SYMBOL == (104863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104864)
		#define UNIQUE_FUNCTION<%0...%1> %0OaV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104865)
		#define UNIQUE_FUNCTION<%0...%1> %0OaW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104866)
		#define UNIQUE_FUNCTION<%0...%1> %0OaX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104867)
		#define UNIQUE_FUNCTION<%0...%1> %0OaY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104868)
		#define UNIQUE_FUNCTION<%0...%1> %0OaZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104869)
		#define UNIQUE_FUNCTION<%0...%1> %0Oa_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104870)
		#define UNIQUE_FUNCTION<%0...%1> %0Oaa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104871)
		#define UNIQUE_FUNCTION<%0...%1> %0Oab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104879)
	#elseif UNIQUE_SYMBOL == (104871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104872)
		#define UNIQUE_FUNCTION<%0...%1> %0Oac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104873)
		#define UNIQUE_FUNCTION<%0...%1> %0Oad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104874)
		#define UNIQUE_FUNCTION<%0...%1> %0Oae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104875)
		#define UNIQUE_FUNCTION<%0...%1> %0Oaf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104876)
		#define UNIQUE_FUNCTION<%0...%1> %0Oag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104877)
		#define UNIQUE_FUNCTION<%0...%1> %0Oah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104878)
		#define UNIQUE_FUNCTION<%0...%1> %0Oai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104879)
		#define UNIQUE_FUNCTION<%0...%1> %0Oaj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (104887)
	#elseif UNIQUE_SYMBOL == (104879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104880)
		#define UNIQUE_FUNCTION<%0...%1> %0Oak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104881)
		#define UNIQUE_FUNCTION<%0...%1> %0Oal%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104882)
		#define UNIQUE_FUNCTION<%0...%1> %0Oam%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104883)
		#define UNIQUE_FUNCTION<%0...%1> %0Oan%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104884)
		#define UNIQUE_FUNCTION<%0...%1> %0Oao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104885)
		#define UNIQUE_FUNCTION<%0...%1> %0Oap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104886)
		#define UNIQUE_FUNCTION<%0...%1> %0Oaq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104887)
		#define UNIQUE_FUNCTION<%0...%1> %0Oar%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (104887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104888)
		#define UNIQUE_FUNCTION<%0...%1> %0Oas%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104889)
		#define UNIQUE_FUNCTION<%0...%1> %0Oat%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104890)
		#define UNIQUE_FUNCTION<%0...%1> %0Oau%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104891)
		#define UNIQUE_FUNCTION<%0...%1> %0Oav%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104892)
		#define UNIQUE_FUNCTION<%0...%1> %0Oaw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104893)
		#define UNIQUE_FUNCTION<%0...%1> %0Oax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (104893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104894)
		#define UNIQUE_FUNCTION<%0...%1> %0Oay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (104895)
		#define UNIQUE_FUNCTION<%0...%1> %0Oaz%1
		#endinput
	#endif
#endif
