static stock const Y_UNIQUE_007872_007935_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_007872_007935
	#undef _inc_y_unique_007872_007935
#endif

#if UNIQUE_SYMBOL < (7879)
	#if UNIQUE_SYMBOL == (7871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7872)
		#define UNIQUE_FUNCTION<%0...%1> %01v0%1
		#endinput
	#if UNIQUE_SYMBOL == (7872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7873)
		#define UNIQUE_FUNCTION<%0...%1> %01v1%1
		#endinput
	#if UNIQUE_SYMBOL == (7873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7874)
		#define UNIQUE_FUNCTION<%0...%1> %01v2%1
		#endinput
	#if UNIQUE_SYMBOL == (7874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7875)
		#define UNIQUE_FUNCTION<%0...%1> %01v3%1
		#endinput
	#if UNIQUE_SYMBOL == (7875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7876)
		#define UNIQUE_FUNCTION<%0...%1> %01v4%1
		#endinput
	#if UNIQUE_SYMBOL == (7876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7877)
		#define UNIQUE_FUNCTION<%0...%1> %01v5%1
		#endinput
	#if UNIQUE_SYMBOL == (7877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7878)
		#define UNIQUE_FUNCTION<%0...%1> %01v6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7879)
		#define UNIQUE_FUNCTION<%0...%1> %01v7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7887)
	#elseif UNIQUE_SYMBOL == (7879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7880)
		#define UNIQUE_FUNCTION<%0...%1> %01v8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7881)
		#define UNIQUE_FUNCTION<%0...%1> %01v9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7882)
		#define UNIQUE_FUNCTION<%0...%1> %01v@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7883)
		#define UNIQUE_FUNCTION<%0...%1> %01vA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7884)
		#define UNIQUE_FUNCTION<%0...%1> %01vB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7885)
		#define UNIQUE_FUNCTION<%0...%1> %01vC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7886)
		#define UNIQUE_FUNCTION<%0...%1> %01vD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7887)
		#define UNIQUE_FUNCTION<%0...%1> %01vE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7895)
	#elseif UNIQUE_SYMBOL == (7887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7888)
		#define UNIQUE_FUNCTION<%0...%1> %01vF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7889)
		#define UNIQUE_FUNCTION<%0...%1> %01vG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7890)
		#define UNIQUE_FUNCTION<%0...%1> %01vH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7891)
		#define UNIQUE_FUNCTION<%0...%1> %01vI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7892)
		#define UNIQUE_FUNCTION<%0...%1> %01vJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7893)
		#define UNIQUE_FUNCTION<%0...%1> %01vK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7894)
		#define UNIQUE_FUNCTION<%0...%1> %01vL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7895)
		#define UNIQUE_FUNCTION<%0...%1> %01vM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7903)
	#elseif UNIQUE_SYMBOL == (7895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7896)
		#define UNIQUE_FUNCTION<%0...%1> %01vN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7897)
		#define UNIQUE_FUNCTION<%0...%1> %01vO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7898)
		#define UNIQUE_FUNCTION<%0...%1> %01vP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7899)
		#define UNIQUE_FUNCTION<%0...%1> %01vQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7900)
		#define UNIQUE_FUNCTION<%0...%1> %01vR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7901)
		#define UNIQUE_FUNCTION<%0...%1> %01vS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7902)
		#define UNIQUE_FUNCTION<%0...%1> %01vT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7903)
		#define UNIQUE_FUNCTION<%0...%1> %01vU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7911)
	#elseif UNIQUE_SYMBOL == (7903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7904)
		#define UNIQUE_FUNCTION<%0...%1> %01vV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7905)
		#define UNIQUE_FUNCTION<%0...%1> %01vW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7906)
		#define UNIQUE_FUNCTION<%0...%1> %01vX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7907)
		#define UNIQUE_FUNCTION<%0...%1> %01vY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7908)
		#define UNIQUE_FUNCTION<%0...%1> %01vZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7909)
		#define UNIQUE_FUNCTION<%0...%1> %01v_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7910)
		#define UNIQUE_FUNCTION<%0...%1> %01va%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7911)
		#define UNIQUE_FUNCTION<%0...%1> %01vb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7919)
	#elseif UNIQUE_SYMBOL == (7911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7912)
		#define UNIQUE_FUNCTION<%0...%1> %01vc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7913)
		#define UNIQUE_FUNCTION<%0...%1> %01vd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7914)
		#define UNIQUE_FUNCTION<%0...%1> %01ve%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7915)
		#define UNIQUE_FUNCTION<%0...%1> %01vf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7916)
		#define UNIQUE_FUNCTION<%0...%1> %01vg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7917)
		#define UNIQUE_FUNCTION<%0...%1> %01vh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7918)
		#define UNIQUE_FUNCTION<%0...%1> %01vi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7919)
		#define UNIQUE_FUNCTION<%0...%1> %01vj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7927)
	#elseif UNIQUE_SYMBOL == (7919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7920)
		#define UNIQUE_FUNCTION<%0...%1> %01vk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7921)
		#define UNIQUE_FUNCTION<%0...%1> %01vl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7922)
		#define UNIQUE_FUNCTION<%0...%1> %01vm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7923)
		#define UNIQUE_FUNCTION<%0...%1> %01vn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7924)
		#define UNIQUE_FUNCTION<%0...%1> %01vo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7925)
		#define UNIQUE_FUNCTION<%0...%1> %01vp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7926)
		#define UNIQUE_FUNCTION<%0...%1> %01vq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7927)
		#define UNIQUE_FUNCTION<%0...%1> %01vr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (7927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7928)
		#define UNIQUE_FUNCTION<%0...%1> %01vs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7929)
		#define UNIQUE_FUNCTION<%0...%1> %01vt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7930)
		#define UNIQUE_FUNCTION<%0...%1> %01vu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7931)
		#define UNIQUE_FUNCTION<%0...%1> %01vv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7932)
		#define UNIQUE_FUNCTION<%0...%1> %01vw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7933)
		#define UNIQUE_FUNCTION<%0...%1> %01vx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7934)
		#define UNIQUE_FUNCTION<%0...%1> %01vy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7935)
		#define UNIQUE_FUNCTION<%0...%1> %01vz%1
		#endinput
	#endif
#endif
