static stock const Y_UNIQUE_167360_167423_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_167360_167423
	#undef _inc_y_unique_167360_167423
#endif

#if UNIQUE_SYMBOL < (167367)
	#if UNIQUE_SYMBOL == (167359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167360)
		#define UNIQUE_FUNCTION<%0...%1> %0cr0%1
		#endinput
	#if UNIQUE_SYMBOL == (167360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167361)
		#define UNIQUE_FUNCTION<%0...%1> %0cr1%1
		#endinput
	#if UNIQUE_SYMBOL == (167361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167362)
		#define UNIQUE_FUNCTION<%0...%1> %0cr2%1
		#endinput
	#if UNIQUE_SYMBOL == (167362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167363)
		#define UNIQUE_FUNCTION<%0...%1> %0cr3%1
		#endinput
	#if UNIQUE_SYMBOL == (167363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167364)
		#define UNIQUE_FUNCTION<%0...%1> %0cr4%1
		#endinput
	#if UNIQUE_SYMBOL == (167364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167365)
		#define UNIQUE_FUNCTION<%0...%1> %0cr5%1
		#endinput
	#if UNIQUE_SYMBOL == (167365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167366)
		#define UNIQUE_FUNCTION<%0...%1> %0cr6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167367)
		#define UNIQUE_FUNCTION<%0...%1> %0cr7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (167375)
	#elseif UNIQUE_SYMBOL == (167367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167368)
		#define UNIQUE_FUNCTION<%0...%1> %0cr8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167369)
		#define UNIQUE_FUNCTION<%0...%1> %0cr9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167370)
		#define UNIQUE_FUNCTION<%0...%1> %0cr@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167371)
		#define UNIQUE_FUNCTION<%0...%1> %0crA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167372)
		#define UNIQUE_FUNCTION<%0...%1> %0crB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167373)
		#define UNIQUE_FUNCTION<%0...%1> %0crC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167374)
		#define UNIQUE_FUNCTION<%0...%1> %0crD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167375)
		#define UNIQUE_FUNCTION<%0...%1> %0crE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (167383)
	#elseif UNIQUE_SYMBOL == (167375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167376)
		#define UNIQUE_FUNCTION<%0...%1> %0crF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167377)
		#define UNIQUE_FUNCTION<%0...%1> %0crG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167378)
		#define UNIQUE_FUNCTION<%0...%1> %0crH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167379)
		#define UNIQUE_FUNCTION<%0...%1> %0crI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167380)
		#define UNIQUE_FUNCTION<%0...%1> %0crJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167381)
		#define UNIQUE_FUNCTION<%0...%1> %0crK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167382)
		#define UNIQUE_FUNCTION<%0...%1> %0crL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167383)
		#define UNIQUE_FUNCTION<%0...%1> %0crM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (167391)
	#elseif UNIQUE_SYMBOL == (167383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167384)
		#define UNIQUE_FUNCTION<%0...%1> %0crN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167385)
		#define UNIQUE_FUNCTION<%0...%1> %0crO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167386)
		#define UNIQUE_FUNCTION<%0...%1> %0crP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167387)
		#define UNIQUE_FUNCTION<%0...%1> %0crQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167388)
		#define UNIQUE_FUNCTION<%0...%1> %0crR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167389)
		#define UNIQUE_FUNCTION<%0...%1> %0crS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167390)
		#define UNIQUE_FUNCTION<%0...%1> %0crT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167391)
		#define UNIQUE_FUNCTION<%0...%1> %0crU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (167399)
	#elseif UNIQUE_SYMBOL == (167391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167392)
		#define UNIQUE_FUNCTION<%0...%1> %0crV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167393)
		#define UNIQUE_FUNCTION<%0...%1> %0crW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167394)
		#define UNIQUE_FUNCTION<%0...%1> %0crX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167395)
		#define UNIQUE_FUNCTION<%0...%1> %0crY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167396)
		#define UNIQUE_FUNCTION<%0...%1> %0crZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167397)
		#define UNIQUE_FUNCTION<%0...%1> %0cr_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167398)
		#define UNIQUE_FUNCTION<%0...%1> %0cra%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167399)
		#define UNIQUE_FUNCTION<%0...%1> %0crb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (167407)
	#elseif UNIQUE_SYMBOL == (167399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167400)
		#define UNIQUE_FUNCTION<%0...%1> %0crc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167401)
		#define UNIQUE_FUNCTION<%0...%1> %0crd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167402)
		#define UNIQUE_FUNCTION<%0...%1> %0cre%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167403)
		#define UNIQUE_FUNCTION<%0...%1> %0crf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167404)
		#define UNIQUE_FUNCTION<%0...%1> %0crg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167405)
		#define UNIQUE_FUNCTION<%0...%1> %0crh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167406)
		#define UNIQUE_FUNCTION<%0...%1> %0cri%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167407)
		#define UNIQUE_FUNCTION<%0...%1> %0crj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (167415)
	#elseif UNIQUE_SYMBOL == (167407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167408)
		#define UNIQUE_FUNCTION<%0...%1> %0crk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167409)
		#define UNIQUE_FUNCTION<%0...%1> %0crl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167410)
		#define UNIQUE_FUNCTION<%0...%1> %0crm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167411)
		#define UNIQUE_FUNCTION<%0...%1> %0crn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167412)
		#define UNIQUE_FUNCTION<%0...%1> %0cro%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167413)
		#define UNIQUE_FUNCTION<%0...%1> %0crp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167414)
		#define UNIQUE_FUNCTION<%0...%1> %0crq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167415)
		#define UNIQUE_FUNCTION<%0...%1> %0crr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (167415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167416)
		#define UNIQUE_FUNCTION<%0...%1> %0crs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167417)
		#define UNIQUE_FUNCTION<%0...%1> %0crt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167418)
		#define UNIQUE_FUNCTION<%0...%1> %0cru%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167419)
		#define UNIQUE_FUNCTION<%0...%1> %0crv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167420)
		#define UNIQUE_FUNCTION<%0...%1> %0crw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167421)
		#define UNIQUE_FUNCTION<%0...%1> %0crx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (167421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167422)
		#define UNIQUE_FUNCTION<%0...%1> %0cry%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (167423)
		#define UNIQUE_FUNCTION<%0...%1> %0crz%1
		#endinput
	#endif
#endif
