static stock const Y_UNIQUE_060224_060287_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_060224_060287
	#undef _inc_y_unique_060224_060287
#endif

#if UNIQUE_SYMBOL < (60231)
	#if UNIQUE_SYMBOL == (60223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60224)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh0%1
		#endinput
	#if UNIQUE_SYMBOL == (60224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60225)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh1%1
		#endinput
	#if UNIQUE_SYMBOL == (60225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60226)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh2%1
		#endinput
	#if UNIQUE_SYMBOL == (60226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60227)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh3%1
		#endinput
	#if UNIQUE_SYMBOL == (60227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60228)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh4%1
		#endinput
	#if UNIQUE_SYMBOL == (60228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60229)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh5%1
		#endinput
	#if UNIQUE_SYMBOL == (60229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60230)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60231)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (60239)
	#elseif UNIQUE_SYMBOL == (60231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60232)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60233)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60234)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60235)
		#define UNIQUE_FUNCTION<%0...%1> %0DhA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60236)
		#define UNIQUE_FUNCTION<%0...%1> %0DhB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60237)
		#define UNIQUE_FUNCTION<%0...%1> %0DhC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60238)
		#define UNIQUE_FUNCTION<%0...%1> %0DhD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60239)
		#define UNIQUE_FUNCTION<%0...%1> %0DhE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (60247)
	#elseif UNIQUE_SYMBOL == (60239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60240)
		#define UNIQUE_FUNCTION<%0...%1> %0DhF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60241)
		#define UNIQUE_FUNCTION<%0...%1> %0DhG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60242)
		#define UNIQUE_FUNCTION<%0...%1> %0DhH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60243)
		#define UNIQUE_FUNCTION<%0...%1> %0DhI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60244)
		#define UNIQUE_FUNCTION<%0...%1> %0DhJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60245)
		#define UNIQUE_FUNCTION<%0...%1> %0DhK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60246)
		#define UNIQUE_FUNCTION<%0...%1> %0DhL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60247)
		#define UNIQUE_FUNCTION<%0...%1> %0DhM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (60255)
	#elseif UNIQUE_SYMBOL == (60247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60248)
		#define UNIQUE_FUNCTION<%0...%1> %0DhN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60249)
		#define UNIQUE_FUNCTION<%0...%1> %0DhO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60250)
		#define UNIQUE_FUNCTION<%0...%1> %0DhP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60251)
		#define UNIQUE_FUNCTION<%0...%1> %0DhQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60252)
		#define UNIQUE_FUNCTION<%0...%1> %0DhR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60253)
		#define UNIQUE_FUNCTION<%0...%1> %0DhS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60254)
		#define UNIQUE_FUNCTION<%0...%1> %0DhT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60255)
		#define UNIQUE_FUNCTION<%0...%1> %0DhU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (60263)
	#elseif UNIQUE_SYMBOL == (60255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60256)
		#define UNIQUE_FUNCTION<%0...%1> %0DhV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60257)
		#define UNIQUE_FUNCTION<%0...%1> %0DhW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60258)
		#define UNIQUE_FUNCTION<%0...%1> %0DhX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60259)
		#define UNIQUE_FUNCTION<%0...%1> %0DhY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60260)
		#define UNIQUE_FUNCTION<%0...%1> %0DhZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60261)
		#define UNIQUE_FUNCTION<%0...%1> %0Dh_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60262)
		#define UNIQUE_FUNCTION<%0...%1> %0Dha%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60263)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (60271)
	#elseif UNIQUE_SYMBOL == (60263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60264)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60265)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60266)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60267)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60268)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60269)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60270)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60271)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (60279)
	#elseif UNIQUE_SYMBOL == (60271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60272)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60273)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60274)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60275)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60276)
		#define UNIQUE_FUNCTION<%0...%1> %0Dho%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60277)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60278)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60279)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (60279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60280)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60281)
		#define UNIQUE_FUNCTION<%0...%1> %0Dht%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60282)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60283)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60284)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60285)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (60285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60286)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (60287)
		#define UNIQUE_FUNCTION<%0...%1> %0Dhz%1
		#endinput
	#endif
#endif
