static stock const Y_UNIQUE_066560_066623_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_066560_066623
	#undef _inc_y_unique_066560_066623
#endif

#if UNIQUE_SYMBOL < (66567)
	#if UNIQUE_SYMBOL == (66559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66560)
		#define UNIQUE_FUNCTION<%0...%1> %0FF0%1
		#endinput
	#if UNIQUE_SYMBOL == (66560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66561)
		#define UNIQUE_FUNCTION<%0...%1> %0FF1%1
		#endinput
	#if UNIQUE_SYMBOL == (66561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66562)
		#define UNIQUE_FUNCTION<%0...%1> %0FF2%1
		#endinput
	#if UNIQUE_SYMBOL == (66562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66563)
		#define UNIQUE_FUNCTION<%0...%1> %0FF3%1
		#endinput
	#if UNIQUE_SYMBOL == (66563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66564)
		#define UNIQUE_FUNCTION<%0...%1> %0FF4%1
		#endinput
	#if UNIQUE_SYMBOL == (66564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66565)
		#define UNIQUE_FUNCTION<%0...%1> %0FF5%1
		#endinput
	#if UNIQUE_SYMBOL == (66565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66566)
		#define UNIQUE_FUNCTION<%0...%1> %0FF6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66567)
		#define UNIQUE_FUNCTION<%0...%1> %0FF7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66575)
	#elseif UNIQUE_SYMBOL == (66567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66568)
		#define UNIQUE_FUNCTION<%0...%1> %0FF8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66569)
		#define UNIQUE_FUNCTION<%0...%1> %0FF9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66570)
		#define UNIQUE_FUNCTION<%0...%1> %0FF@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66571)
		#define UNIQUE_FUNCTION<%0...%1> %0FFA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66572)
		#define UNIQUE_FUNCTION<%0...%1> %0FFB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66573)
		#define UNIQUE_FUNCTION<%0...%1> %0FFC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66574)
		#define UNIQUE_FUNCTION<%0...%1> %0FFD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66575)
		#define UNIQUE_FUNCTION<%0...%1> %0FFE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66583)
	#elseif UNIQUE_SYMBOL == (66575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66576)
		#define UNIQUE_FUNCTION<%0...%1> %0FFF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66577)
		#define UNIQUE_FUNCTION<%0...%1> %0FFG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66578)
		#define UNIQUE_FUNCTION<%0...%1> %0FFH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66579)
		#define UNIQUE_FUNCTION<%0...%1> %0FFI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66580)
		#define UNIQUE_FUNCTION<%0...%1> %0FFJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66581)
		#define UNIQUE_FUNCTION<%0...%1> %0FFK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66582)
		#define UNIQUE_FUNCTION<%0...%1> %0FFL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66583)
		#define UNIQUE_FUNCTION<%0...%1> %0FFM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66591)
	#elseif UNIQUE_SYMBOL == (66583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66584)
		#define UNIQUE_FUNCTION<%0...%1> %0FFN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66585)
		#define UNIQUE_FUNCTION<%0...%1> %0FFO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66586)
		#define UNIQUE_FUNCTION<%0...%1> %0FFP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66587)
		#define UNIQUE_FUNCTION<%0...%1> %0FFQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66588)
		#define UNIQUE_FUNCTION<%0...%1> %0FFR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66589)
		#define UNIQUE_FUNCTION<%0...%1> %0FFS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66590)
		#define UNIQUE_FUNCTION<%0...%1> %0FFT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66591)
		#define UNIQUE_FUNCTION<%0...%1> %0FFU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66599)
	#elseif UNIQUE_SYMBOL == (66591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66592)
		#define UNIQUE_FUNCTION<%0...%1> %0FFV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66593)
		#define UNIQUE_FUNCTION<%0...%1> %0FFW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66594)
		#define UNIQUE_FUNCTION<%0...%1> %0FFX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66595)
		#define UNIQUE_FUNCTION<%0...%1> %0FFY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66596)
		#define UNIQUE_FUNCTION<%0...%1> %0FFZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66597)
		#define UNIQUE_FUNCTION<%0...%1> %0FF_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66598)
		#define UNIQUE_FUNCTION<%0...%1> %0FFa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66599)
		#define UNIQUE_FUNCTION<%0...%1> %0FFb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66607)
	#elseif UNIQUE_SYMBOL == (66599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66600)
		#define UNIQUE_FUNCTION<%0...%1> %0FFc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66601)
		#define UNIQUE_FUNCTION<%0...%1> %0FFd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66602)
		#define UNIQUE_FUNCTION<%0...%1> %0FFe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66603)
		#define UNIQUE_FUNCTION<%0...%1> %0FFf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66604)
		#define UNIQUE_FUNCTION<%0...%1> %0FFg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66605)
		#define UNIQUE_FUNCTION<%0...%1> %0FFh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66606)
		#define UNIQUE_FUNCTION<%0...%1> %0FFi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66607)
		#define UNIQUE_FUNCTION<%0...%1> %0FFj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66615)
	#elseif UNIQUE_SYMBOL == (66607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66608)
		#define UNIQUE_FUNCTION<%0...%1> %0FFk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66609)
		#define UNIQUE_FUNCTION<%0...%1> %0FFl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66610)
		#define UNIQUE_FUNCTION<%0...%1> %0FFm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66611)
		#define UNIQUE_FUNCTION<%0...%1> %0FFn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66612)
		#define UNIQUE_FUNCTION<%0...%1> %0FFo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66613)
		#define UNIQUE_FUNCTION<%0...%1> %0FFp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66614)
		#define UNIQUE_FUNCTION<%0...%1> %0FFq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66615)
		#define UNIQUE_FUNCTION<%0...%1> %0FFr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (66615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66616)
		#define UNIQUE_FUNCTION<%0...%1> %0FFs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66617)
		#define UNIQUE_FUNCTION<%0...%1> %0FFt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66618)
		#define UNIQUE_FUNCTION<%0...%1> %0FFu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66619)
		#define UNIQUE_FUNCTION<%0...%1> %0FFv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66620)
		#define UNIQUE_FUNCTION<%0...%1> %0FFw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66621)
		#define UNIQUE_FUNCTION<%0...%1> %0FFx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66622)
		#define UNIQUE_FUNCTION<%0...%1> %0FFy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66623)
		#define UNIQUE_FUNCTION<%0...%1> %0FFz%1
		#endinput
	#endif
#endif
