static stock const Y_UNIQUE_015744_015807_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_015744_015807
	#undef _inc_y_unique_015744_015807
#endif

#if UNIQUE_SYMBOL < (15751)
	#if UNIQUE_SYMBOL == (15743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15744)
		#define UNIQUE_FUNCTION<%0...%1> %03q0%1
		#endinput
	#if UNIQUE_SYMBOL == (15744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15745)
		#define UNIQUE_FUNCTION<%0...%1> %03q1%1
		#endinput
	#if UNIQUE_SYMBOL == (15745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15746)
		#define UNIQUE_FUNCTION<%0...%1> %03q2%1
		#endinput
	#if UNIQUE_SYMBOL == (15746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15747)
		#define UNIQUE_FUNCTION<%0...%1> %03q3%1
		#endinput
	#if UNIQUE_SYMBOL == (15747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15748)
		#define UNIQUE_FUNCTION<%0...%1> %03q4%1
		#endinput
	#if UNIQUE_SYMBOL == (15748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15749)
		#define UNIQUE_FUNCTION<%0...%1> %03q5%1
		#endinput
	#if UNIQUE_SYMBOL == (15749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15750)
		#define UNIQUE_FUNCTION<%0...%1> %03q6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15751)
		#define UNIQUE_FUNCTION<%0...%1> %03q7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15759)
	#elseif UNIQUE_SYMBOL == (15751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15752)
		#define UNIQUE_FUNCTION<%0...%1> %03q8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15753)
		#define UNIQUE_FUNCTION<%0...%1> %03q9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15754)
		#define UNIQUE_FUNCTION<%0...%1> %03q@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15755)
		#define UNIQUE_FUNCTION<%0...%1> %03qA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15756)
		#define UNIQUE_FUNCTION<%0...%1> %03qB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15757)
		#define UNIQUE_FUNCTION<%0...%1> %03qC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15758)
		#define UNIQUE_FUNCTION<%0...%1> %03qD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15759)
		#define UNIQUE_FUNCTION<%0...%1> %03qE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15767)
	#elseif UNIQUE_SYMBOL == (15759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15760)
		#define UNIQUE_FUNCTION<%0...%1> %03qF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15761)
		#define UNIQUE_FUNCTION<%0...%1> %03qG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15762)
		#define UNIQUE_FUNCTION<%0...%1> %03qH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15763)
		#define UNIQUE_FUNCTION<%0...%1> %03qI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15764)
		#define UNIQUE_FUNCTION<%0...%1> %03qJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15765)
		#define UNIQUE_FUNCTION<%0...%1> %03qK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15766)
		#define UNIQUE_FUNCTION<%0...%1> %03qL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15767)
		#define UNIQUE_FUNCTION<%0...%1> %03qM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15775)
	#elseif UNIQUE_SYMBOL == (15767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15768)
		#define UNIQUE_FUNCTION<%0...%1> %03qN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15769)
		#define UNIQUE_FUNCTION<%0...%1> %03qO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15770)
		#define UNIQUE_FUNCTION<%0...%1> %03qP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15771)
		#define UNIQUE_FUNCTION<%0...%1> %03qQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15772)
		#define UNIQUE_FUNCTION<%0...%1> %03qR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15773)
		#define UNIQUE_FUNCTION<%0...%1> %03qS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15774)
		#define UNIQUE_FUNCTION<%0...%1> %03qT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15775)
		#define UNIQUE_FUNCTION<%0...%1> %03qU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15783)
	#elseif UNIQUE_SYMBOL == (15775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15776)
		#define UNIQUE_FUNCTION<%0...%1> %03qV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15777)
		#define UNIQUE_FUNCTION<%0...%1> %03qW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15778)
		#define UNIQUE_FUNCTION<%0...%1> %03qX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15779)
		#define UNIQUE_FUNCTION<%0...%1> %03qY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15780)
		#define UNIQUE_FUNCTION<%0...%1> %03qZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15781)
		#define UNIQUE_FUNCTION<%0...%1> %03q_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15782)
		#define UNIQUE_FUNCTION<%0...%1> %03qa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15783)
		#define UNIQUE_FUNCTION<%0...%1> %03qb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15791)
	#elseif UNIQUE_SYMBOL == (15783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15784)
		#define UNIQUE_FUNCTION<%0...%1> %03qc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15785)
		#define UNIQUE_FUNCTION<%0...%1> %03qd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15786)
		#define UNIQUE_FUNCTION<%0...%1> %03qe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15787)
		#define UNIQUE_FUNCTION<%0...%1> %03qf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15788)
		#define UNIQUE_FUNCTION<%0...%1> %03qg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15789)
		#define UNIQUE_FUNCTION<%0...%1> %03qh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15790)
		#define UNIQUE_FUNCTION<%0...%1> %03qi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15791)
		#define UNIQUE_FUNCTION<%0...%1> %03qj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15799)
	#elseif UNIQUE_SYMBOL == (15791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15792)
		#define UNIQUE_FUNCTION<%0...%1> %03qk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15793)
		#define UNIQUE_FUNCTION<%0...%1> %03ql%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15794)
		#define UNIQUE_FUNCTION<%0...%1> %03qm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15795)
		#define UNIQUE_FUNCTION<%0...%1> %03qn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15796)
		#define UNIQUE_FUNCTION<%0...%1> %03qo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15797)
		#define UNIQUE_FUNCTION<%0...%1> %03qp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15798)
		#define UNIQUE_FUNCTION<%0...%1> %03qq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15799)
		#define UNIQUE_FUNCTION<%0...%1> %03qr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (15799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15800)
		#define UNIQUE_FUNCTION<%0...%1> %03qs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15801)
		#define UNIQUE_FUNCTION<%0...%1> %03qt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15802)
		#define UNIQUE_FUNCTION<%0...%1> %03qu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15803)
		#define UNIQUE_FUNCTION<%0...%1> %03qv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15804)
		#define UNIQUE_FUNCTION<%0...%1> %03qw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15805)
		#define UNIQUE_FUNCTION<%0...%1> %03qx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15806)
		#define UNIQUE_FUNCTION<%0...%1> %03qy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15807)
		#define UNIQUE_FUNCTION<%0...%1> %03qz%1
		#endinput
	#endif
#endif
