static stock const Y_UNIQUE_033536_033599_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_033536_033599
	#undef _inc_y_unique_033536_033599
#endif

#if UNIQUE_SYMBOL < (33543)
	#if UNIQUE_SYMBOL == (33535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33536)
		#define UNIQUE_FUNCTION<%0...%1> %08B0%1
		#endinput
	#if UNIQUE_SYMBOL == (33536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33537)
		#define UNIQUE_FUNCTION<%0...%1> %08B1%1
		#endinput
	#if UNIQUE_SYMBOL == (33537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33538)
		#define UNIQUE_FUNCTION<%0...%1> %08B2%1
		#endinput
	#if UNIQUE_SYMBOL == (33538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33539)
		#define UNIQUE_FUNCTION<%0...%1> %08B3%1
		#endinput
	#if UNIQUE_SYMBOL == (33539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33540)
		#define UNIQUE_FUNCTION<%0...%1> %08B4%1
		#endinput
	#if UNIQUE_SYMBOL == (33540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33541)
		#define UNIQUE_FUNCTION<%0...%1> %08B5%1
		#endinput
	#if UNIQUE_SYMBOL == (33541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33542)
		#define UNIQUE_FUNCTION<%0...%1> %08B6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33543)
		#define UNIQUE_FUNCTION<%0...%1> %08B7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33551)
	#elseif UNIQUE_SYMBOL == (33543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33544)
		#define UNIQUE_FUNCTION<%0...%1> %08B8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33545)
		#define UNIQUE_FUNCTION<%0...%1> %08B9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33546)
		#define UNIQUE_FUNCTION<%0...%1> %08B@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33547)
		#define UNIQUE_FUNCTION<%0...%1> %08BA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33548)
		#define UNIQUE_FUNCTION<%0...%1> %08BB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33549)
		#define UNIQUE_FUNCTION<%0...%1> %08BC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33550)
		#define UNIQUE_FUNCTION<%0...%1> %08BD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33551)
		#define UNIQUE_FUNCTION<%0...%1> %08BE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33559)
	#elseif UNIQUE_SYMBOL == (33551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33552)
		#define UNIQUE_FUNCTION<%0...%1> %08BF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33553)
		#define UNIQUE_FUNCTION<%0...%1> %08BG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33554)
		#define UNIQUE_FUNCTION<%0...%1> %08BH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33555)
		#define UNIQUE_FUNCTION<%0...%1> %08BI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33556)
		#define UNIQUE_FUNCTION<%0...%1> %08BJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33557)
		#define UNIQUE_FUNCTION<%0...%1> %08BK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33558)
		#define UNIQUE_FUNCTION<%0...%1> %08BL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33559)
		#define UNIQUE_FUNCTION<%0...%1> %08BM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33567)
	#elseif UNIQUE_SYMBOL == (33559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33560)
		#define UNIQUE_FUNCTION<%0...%1> %08BN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33561)
		#define UNIQUE_FUNCTION<%0...%1> %08BO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33562)
		#define UNIQUE_FUNCTION<%0...%1> %08BP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33563)
		#define UNIQUE_FUNCTION<%0...%1> %08BQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33564)
		#define UNIQUE_FUNCTION<%0...%1> %08BR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33565)
		#define UNIQUE_FUNCTION<%0...%1> %08BS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33566)
		#define UNIQUE_FUNCTION<%0...%1> %08BT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33567)
		#define UNIQUE_FUNCTION<%0...%1> %08BU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33575)
	#elseif UNIQUE_SYMBOL == (33567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33568)
		#define UNIQUE_FUNCTION<%0...%1> %08BV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33569)
		#define UNIQUE_FUNCTION<%0...%1> %08BW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33570)
		#define UNIQUE_FUNCTION<%0...%1> %08BX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33571)
		#define UNIQUE_FUNCTION<%0...%1> %08BY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33572)
		#define UNIQUE_FUNCTION<%0...%1> %08BZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33573)
		#define UNIQUE_FUNCTION<%0...%1> %08B_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33574)
		#define UNIQUE_FUNCTION<%0...%1> %08Ba%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33575)
		#define UNIQUE_FUNCTION<%0...%1> %08Bb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33583)
	#elseif UNIQUE_SYMBOL == (33575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33576)
		#define UNIQUE_FUNCTION<%0...%1> %08Bc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33577)
		#define UNIQUE_FUNCTION<%0...%1> %08Bd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33578)
		#define UNIQUE_FUNCTION<%0...%1> %08Be%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33579)
		#define UNIQUE_FUNCTION<%0...%1> %08Bf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33580)
		#define UNIQUE_FUNCTION<%0...%1> %08Bg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33581)
		#define UNIQUE_FUNCTION<%0...%1> %08Bh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33582)
		#define UNIQUE_FUNCTION<%0...%1> %08Bi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33583)
		#define UNIQUE_FUNCTION<%0...%1> %08Bj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33591)
	#elseif UNIQUE_SYMBOL == (33583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33584)
		#define UNIQUE_FUNCTION<%0...%1> %08Bk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33585)
		#define UNIQUE_FUNCTION<%0...%1> %08Bl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33586)
		#define UNIQUE_FUNCTION<%0...%1> %08Bm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33587)
		#define UNIQUE_FUNCTION<%0...%1> %08Bn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33588)
		#define UNIQUE_FUNCTION<%0...%1> %08Bo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33589)
		#define UNIQUE_FUNCTION<%0...%1> %08Bp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33590)
		#define UNIQUE_FUNCTION<%0...%1> %08Bq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33591)
		#define UNIQUE_FUNCTION<%0...%1> %08Br%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (33591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33592)
		#define UNIQUE_FUNCTION<%0...%1> %08Bs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33593)
		#define UNIQUE_FUNCTION<%0...%1> %08Bt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33594)
		#define UNIQUE_FUNCTION<%0...%1> %08Bu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33595)
		#define UNIQUE_FUNCTION<%0...%1> %08Bv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33596)
		#define UNIQUE_FUNCTION<%0...%1> %08Bw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33597)
		#define UNIQUE_FUNCTION<%0...%1> %08Bx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33598)
		#define UNIQUE_FUNCTION<%0...%1> %08By%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33599)
		#define UNIQUE_FUNCTION<%0...%1> %08Bz%1
		#endinput
	#endif
#endif
