static stock const Y_UNIQUE_007680_007743_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_007680_007743
	#undef _inc_y_unique_007680_007743
#endif

#if UNIQUE_SYMBOL < (7687)
	#if UNIQUE_SYMBOL == (7679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7680)
		#define UNIQUE_FUNCTION<%0...%1> %01s0%1
		#endinput
	#if UNIQUE_SYMBOL == (7680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7681)
		#define UNIQUE_FUNCTION<%0...%1> %01s1%1
		#endinput
	#if UNIQUE_SYMBOL == (7681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7682)
		#define UNIQUE_FUNCTION<%0...%1> %01s2%1
		#endinput
	#if UNIQUE_SYMBOL == (7682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7683)
		#define UNIQUE_FUNCTION<%0...%1> %01s3%1
		#endinput
	#if UNIQUE_SYMBOL == (7683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7684)
		#define UNIQUE_FUNCTION<%0...%1> %01s4%1
		#endinput
	#if UNIQUE_SYMBOL == (7684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7685)
		#define UNIQUE_FUNCTION<%0...%1> %01s5%1
		#endinput
	#if UNIQUE_SYMBOL == (7685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7686)
		#define UNIQUE_FUNCTION<%0...%1> %01s6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7687)
		#define UNIQUE_FUNCTION<%0...%1> %01s7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7695)
	#elseif UNIQUE_SYMBOL == (7687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7688)
		#define UNIQUE_FUNCTION<%0...%1> %01s8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7689)
		#define UNIQUE_FUNCTION<%0...%1> %01s9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7690)
		#define UNIQUE_FUNCTION<%0...%1> %01s@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7691)
		#define UNIQUE_FUNCTION<%0...%1> %01sA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7692)
		#define UNIQUE_FUNCTION<%0...%1> %01sB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7693)
		#define UNIQUE_FUNCTION<%0...%1> %01sC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7694)
		#define UNIQUE_FUNCTION<%0...%1> %01sD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7695)
		#define UNIQUE_FUNCTION<%0...%1> %01sE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7703)
	#elseif UNIQUE_SYMBOL == (7695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7696)
		#define UNIQUE_FUNCTION<%0...%1> %01sF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7697)
		#define UNIQUE_FUNCTION<%0...%1> %01sG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7698)
		#define UNIQUE_FUNCTION<%0...%1> %01sH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7699)
		#define UNIQUE_FUNCTION<%0...%1> %01sI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7700)
		#define UNIQUE_FUNCTION<%0...%1> %01sJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7701)
		#define UNIQUE_FUNCTION<%0...%1> %01sK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7702)
		#define UNIQUE_FUNCTION<%0...%1> %01sL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7703)
		#define UNIQUE_FUNCTION<%0...%1> %01sM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7711)
	#elseif UNIQUE_SYMBOL == (7703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7704)
		#define UNIQUE_FUNCTION<%0...%1> %01sN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7705)
		#define UNIQUE_FUNCTION<%0...%1> %01sO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7706)
		#define UNIQUE_FUNCTION<%0...%1> %01sP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7707)
		#define UNIQUE_FUNCTION<%0...%1> %01sQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7708)
		#define UNIQUE_FUNCTION<%0...%1> %01sR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7709)
		#define UNIQUE_FUNCTION<%0...%1> %01sS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7710)
		#define UNIQUE_FUNCTION<%0...%1> %01sT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7711)
		#define UNIQUE_FUNCTION<%0...%1> %01sU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7719)
	#elseif UNIQUE_SYMBOL == (7711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7712)
		#define UNIQUE_FUNCTION<%0...%1> %01sV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7713)
		#define UNIQUE_FUNCTION<%0...%1> %01sW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7714)
		#define UNIQUE_FUNCTION<%0...%1> %01sX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7715)
		#define UNIQUE_FUNCTION<%0...%1> %01sY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7716)
		#define UNIQUE_FUNCTION<%0...%1> %01sZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7717)
		#define UNIQUE_FUNCTION<%0...%1> %01s_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7718)
		#define UNIQUE_FUNCTION<%0...%1> %01sa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7719)
		#define UNIQUE_FUNCTION<%0...%1> %01sb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7727)
	#elseif UNIQUE_SYMBOL == (7719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7720)
		#define UNIQUE_FUNCTION<%0...%1> %01sc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7721)
		#define UNIQUE_FUNCTION<%0...%1> %01sd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7722)
		#define UNIQUE_FUNCTION<%0...%1> %01se%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7723)
		#define UNIQUE_FUNCTION<%0...%1> %01sf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7724)
		#define UNIQUE_FUNCTION<%0...%1> %01sg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7725)
		#define UNIQUE_FUNCTION<%0...%1> %01sh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7726)
		#define UNIQUE_FUNCTION<%0...%1> %01si%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7727)
		#define UNIQUE_FUNCTION<%0...%1> %01sj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (7735)
	#elseif UNIQUE_SYMBOL == (7727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7728)
		#define UNIQUE_FUNCTION<%0...%1> %01sk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7729)
		#define UNIQUE_FUNCTION<%0...%1> %01sl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7730)
		#define UNIQUE_FUNCTION<%0...%1> %01sm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7731)
		#define UNIQUE_FUNCTION<%0...%1> %01sn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7732)
		#define UNIQUE_FUNCTION<%0...%1> %01so%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7733)
		#define UNIQUE_FUNCTION<%0...%1> %01sp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7734)
		#define UNIQUE_FUNCTION<%0...%1> %01sq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7735)
		#define UNIQUE_FUNCTION<%0...%1> %01sr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (7735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7736)
		#define UNIQUE_FUNCTION<%0...%1> %01ss%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7737)
		#define UNIQUE_FUNCTION<%0...%1> %01st%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7738)
		#define UNIQUE_FUNCTION<%0...%1> %01su%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7739)
		#define UNIQUE_FUNCTION<%0...%1> %01sv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7740)
		#define UNIQUE_FUNCTION<%0...%1> %01sw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7741)
		#define UNIQUE_FUNCTION<%0...%1> %01sx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (7741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7742)
		#define UNIQUE_FUNCTION<%0...%1> %01sy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (7743)
		#define UNIQUE_FUNCTION<%0...%1> %01sz%1
		#endinput
	#endif
#endif
