static stock const Y_UNIQUE_250560_250623_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_250560_250623
	#undef _inc_y_unique_250560_250623
#endif

#if UNIQUE_SYMBOL < (250567)
	#if UNIQUE_SYMBOL == (250559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250560)
		#define UNIQUE_FUNCTION<%0...%1> %0xA0%1
		#endinput
	#if UNIQUE_SYMBOL == (250560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250561)
		#define UNIQUE_FUNCTION<%0...%1> %0xA1%1
		#endinput
	#if UNIQUE_SYMBOL == (250561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250562)
		#define UNIQUE_FUNCTION<%0...%1> %0xA2%1
		#endinput
	#if UNIQUE_SYMBOL == (250562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250563)
		#define UNIQUE_FUNCTION<%0...%1> %0xA3%1
		#endinput
	#if UNIQUE_SYMBOL == (250563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250564)
		#define UNIQUE_FUNCTION<%0...%1> %0xA4%1
		#endinput
	#if UNIQUE_SYMBOL == (250564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250565)
		#define UNIQUE_FUNCTION<%0...%1> %0xA5%1
		#endinput
	#if UNIQUE_SYMBOL == (250565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250566)
		#define UNIQUE_FUNCTION<%0...%1> %0xA6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250567)
		#define UNIQUE_FUNCTION<%0...%1> %0xA7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250575)
	#elseif UNIQUE_SYMBOL == (250567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250568)
		#define UNIQUE_FUNCTION<%0...%1> %0xA8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250569)
		#define UNIQUE_FUNCTION<%0...%1> %0xA9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250570)
		#define UNIQUE_FUNCTION<%0...%1> %0xA@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250571)
		#define UNIQUE_FUNCTION<%0...%1> %0xAA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250572)
		#define UNIQUE_FUNCTION<%0...%1> %0xAB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250573)
		#define UNIQUE_FUNCTION<%0...%1> %0xAC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250574)
		#define UNIQUE_FUNCTION<%0...%1> %0xAD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250575)
		#define UNIQUE_FUNCTION<%0...%1> %0xAE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250583)
	#elseif UNIQUE_SYMBOL == (250575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250576)
		#define UNIQUE_FUNCTION<%0...%1> %0xAF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250577)
		#define UNIQUE_FUNCTION<%0...%1> %0xAG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250578)
		#define UNIQUE_FUNCTION<%0...%1> %0xAH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250579)
		#define UNIQUE_FUNCTION<%0...%1> %0xAI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250580)
		#define UNIQUE_FUNCTION<%0...%1> %0xAJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250581)
		#define UNIQUE_FUNCTION<%0...%1> %0xAK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250582)
		#define UNIQUE_FUNCTION<%0...%1> %0xAL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250583)
		#define UNIQUE_FUNCTION<%0...%1> %0xAM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250591)
	#elseif UNIQUE_SYMBOL == (250583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250584)
		#define UNIQUE_FUNCTION<%0...%1> %0xAN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250585)
		#define UNIQUE_FUNCTION<%0...%1> %0xAO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250586)
		#define UNIQUE_FUNCTION<%0...%1> %0xAP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250587)
		#define UNIQUE_FUNCTION<%0...%1> %0xAQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250588)
		#define UNIQUE_FUNCTION<%0...%1> %0xAR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250589)
		#define UNIQUE_FUNCTION<%0...%1> %0xAS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250590)
		#define UNIQUE_FUNCTION<%0...%1> %0xAT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250591)
		#define UNIQUE_FUNCTION<%0...%1> %0xAU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250599)
	#elseif UNIQUE_SYMBOL == (250591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250592)
		#define UNIQUE_FUNCTION<%0...%1> %0xAV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250593)
		#define UNIQUE_FUNCTION<%0...%1> %0xAW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250594)
		#define UNIQUE_FUNCTION<%0...%1> %0xAX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250595)
		#define UNIQUE_FUNCTION<%0...%1> %0xAY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250596)
		#define UNIQUE_FUNCTION<%0...%1> %0xAZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250597)
		#define UNIQUE_FUNCTION<%0...%1> %0xA_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250598)
		#define UNIQUE_FUNCTION<%0...%1> %0xAa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250599)
		#define UNIQUE_FUNCTION<%0...%1> %0xAb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250607)
	#elseif UNIQUE_SYMBOL == (250599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250600)
		#define UNIQUE_FUNCTION<%0...%1> %0xAc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250601)
		#define UNIQUE_FUNCTION<%0...%1> %0xAd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250602)
		#define UNIQUE_FUNCTION<%0...%1> %0xAe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250603)
		#define UNIQUE_FUNCTION<%0...%1> %0xAf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250604)
		#define UNIQUE_FUNCTION<%0...%1> %0xAg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250605)
		#define UNIQUE_FUNCTION<%0...%1> %0xAh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250606)
		#define UNIQUE_FUNCTION<%0...%1> %0xAi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250607)
		#define UNIQUE_FUNCTION<%0...%1> %0xAj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (250615)
	#elseif UNIQUE_SYMBOL == (250607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250608)
		#define UNIQUE_FUNCTION<%0...%1> %0xAk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250609)
		#define UNIQUE_FUNCTION<%0...%1> %0xAl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250610)
		#define UNIQUE_FUNCTION<%0...%1> %0xAm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250611)
		#define UNIQUE_FUNCTION<%0...%1> %0xAn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250612)
		#define UNIQUE_FUNCTION<%0...%1> %0xAo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250613)
		#define UNIQUE_FUNCTION<%0...%1> %0xAp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250614)
		#define UNIQUE_FUNCTION<%0...%1> %0xAq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250615)
		#define UNIQUE_FUNCTION<%0...%1> %0xAr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (250615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250616)
		#define UNIQUE_FUNCTION<%0...%1> %0xAs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250617)
		#define UNIQUE_FUNCTION<%0...%1> %0xAt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250618)
		#define UNIQUE_FUNCTION<%0...%1> %0xAu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250619)
		#define UNIQUE_FUNCTION<%0...%1> %0xAv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250620)
		#define UNIQUE_FUNCTION<%0...%1> %0xAw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250621)
		#define UNIQUE_FUNCTION<%0...%1> %0xAx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (250621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250622)
		#define UNIQUE_FUNCTION<%0...%1> %0xAy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (250623)
		#define UNIQUE_FUNCTION<%0...%1> %0xAz%1
		#endinput
	#endif
#endif
