static stock const Y_UNIQUE_071744_071807_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_071744_071807
	#undef _inc_y_unique_071744_071807
#endif

#if UNIQUE_SYMBOL < (71751)
	#if UNIQUE_SYMBOL == (71743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71744)
		#define UNIQUE_FUNCTION<%0...%1> %0GW0%1
		#endinput
	#if UNIQUE_SYMBOL == (71744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71745)
		#define UNIQUE_FUNCTION<%0...%1> %0GW1%1
		#endinput
	#if UNIQUE_SYMBOL == (71745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71746)
		#define UNIQUE_FUNCTION<%0...%1> %0GW2%1
		#endinput
	#if UNIQUE_SYMBOL == (71746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71747)
		#define UNIQUE_FUNCTION<%0...%1> %0GW3%1
		#endinput
	#if UNIQUE_SYMBOL == (71747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71748)
		#define UNIQUE_FUNCTION<%0...%1> %0GW4%1
		#endinput
	#if UNIQUE_SYMBOL == (71748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71749)
		#define UNIQUE_FUNCTION<%0...%1> %0GW5%1
		#endinput
	#if UNIQUE_SYMBOL == (71749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71750)
		#define UNIQUE_FUNCTION<%0...%1> %0GW6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71751)
		#define UNIQUE_FUNCTION<%0...%1> %0GW7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (71759)
	#elseif UNIQUE_SYMBOL == (71751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71752)
		#define UNIQUE_FUNCTION<%0...%1> %0GW8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71753)
		#define UNIQUE_FUNCTION<%0...%1> %0GW9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71754)
		#define UNIQUE_FUNCTION<%0...%1> %0GW@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71755)
		#define UNIQUE_FUNCTION<%0...%1> %0GWA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71756)
		#define UNIQUE_FUNCTION<%0...%1> %0GWB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71757)
		#define UNIQUE_FUNCTION<%0...%1> %0GWC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71758)
		#define UNIQUE_FUNCTION<%0...%1> %0GWD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71759)
		#define UNIQUE_FUNCTION<%0...%1> %0GWE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (71767)
	#elseif UNIQUE_SYMBOL == (71759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71760)
		#define UNIQUE_FUNCTION<%0...%1> %0GWF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71761)
		#define UNIQUE_FUNCTION<%0...%1> %0GWG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71762)
		#define UNIQUE_FUNCTION<%0...%1> %0GWH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71763)
		#define UNIQUE_FUNCTION<%0...%1> %0GWI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71764)
		#define UNIQUE_FUNCTION<%0...%1> %0GWJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71765)
		#define UNIQUE_FUNCTION<%0...%1> %0GWK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71766)
		#define UNIQUE_FUNCTION<%0...%1> %0GWL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71767)
		#define UNIQUE_FUNCTION<%0...%1> %0GWM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (71775)
	#elseif UNIQUE_SYMBOL == (71767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71768)
		#define UNIQUE_FUNCTION<%0...%1> %0GWN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71769)
		#define UNIQUE_FUNCTION<%0...%1> %0GWO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71770)
		#define UNIQUE_FUNCTION<%0...%1> %0GWP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71771)
		#define UNIQUE_FUNCTION<%0...%1> %0GWQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71772)
		#define UNIQUE_FUNCTION<%0...%1> %0GWR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71773)
		#define UNIQUE_FUNCTION<%0...%1> %0GWS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71774)
		#define UNIQUE_FUNCTION<%0...%1> %0GWT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71775)
		#define UNIQUE_FUNCTION<%0...%1> %0GWU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (71783)
	#elseif UNIQUE_SYMBOL == (71775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71776)
		#define UNIQUE_FUNCTION<%0...%1> %0GWV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71777)
		#define UNIQUE_FUNCTION<%0...%1> %0GWW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71778)
		#define UNIQUE_FUNCTION<%0...%1> %0GWX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71779)
		#define UNIQUE_FUNCTION<%0...%1> %0GWY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71780)
		#define UNIQUE_FUNCTION<%0...%1> %0GWZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71781)
		#define UNIQUE_FUNCTION<%0...%1> %0GW_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71782)
		#define UNIQUE_FUNCTION<%0...%1> %0GWa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71783)
		#define UNIQUE_FUNCTION<%0...%1> %0GWb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (71791)
	#elseif UNIQUE_SYMBOL == (71783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71784)
		#define UNIQUE_FUNCTION<%0...%1> %0GWc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71785)
		#define UNIQUE_FUNCTION<%0...%1> %0GWd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71786)
		#define UNIQUE_FUNCTION<%0...%1> %0GWe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71787)
		#define UNIQUE_FUNCTION<%0...%1> %0GWf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71788)
		#define UNIQUE_FUNCTION<%0...%1> %0GWg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71789)
		#define UNIQUE_FUNCTION<%0...%1> %0GWh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71790)
		#define UNIQUE_FUNCTION<%0...%1> %0GWi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71791)
		#define UNIQUE_FUNCTION<%0...%1> %0GWj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (71799)
	#elseif UNIQUE_SYMBOL == (71791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71792)
		#define UNIQUE_FUNCTION<%0...%1> %0GWk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71793)
		#define UNIQUE_FUNCTION<%0...%1> %0GWl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71794)
		#define UNIQUE_FUNCTION<%0...%1> %0GWm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71795)
		#define UNIQUE_FUNCTION<%0...%1> %0GWn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71796)
		#define UNIQUE_FUNCTION<%0...%1> %0GWo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71797)
		#define UNIQUE_FUNCTION<%0...%1> %0GWp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71798)
		#define UNIQUE_FUNCTION<%0...%1> %0GWq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71799)
		#define UNIQUE_FUNCTION<%0...%1> %0GWr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (71799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71800)
		#define UNIQUE_FUNCTION<%0...%1> %0GWs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71801)
		#define UNIQUE_FUNCTION<%0...%1> %0GWt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71802)
		#define UNIQUE_FUNCTION<%0...%1> %0GWu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71803)
		#define UNIQUE_FUNCTION<%0...%1> %0GWv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71804)
		#define UNIQUE_FUNCTION<%0...%1> %0GWw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71805)
		#define UNIQUE_FUNCTION<%0...%1> %0GWx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (71805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71806)
		#define UNIQUE_FUNCTION<%0...%1> %0GWy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (71807)
		#define UNIQUE_FUNCTION<%0...%1> %0GWz%1
		#endinput
	#endif
#endif
