static stock const Y_UNIQUE_022720_022783_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_022720_022783
	#undef _inc_y_unique_022720_022783
#endif

#if UNIQUE_SYMBOL < (22727)
	#if UNIQUE_SYMBOL == (22719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22720)
		#define UNIQUE_FUNCTION<%0...%1> %05Y0%1
		#endinput
	#if UNIQUE_SYMBOL == (22720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22721)
		#define UNIQUE_FUNCTION<%0...%1> %05Y1%1
		#endinput
	#if UNIQUE_SYMBOL == (22721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22722)
		#define UNIQUE_FUNCTION<%0...%1> %05Y2%1
		#endinput
	#if UNIQUE_SYMBOL == (22722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22723)
		#define UNIQUE_FUNCTION<%0...%1> %05Y3%1
		#endinput
	#if UNIQUE_SYMBOL == (22723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22724)
		#define UNIQUE_FUNCTION<%0...%1> %05Y4%1
		#endinput
	#if UNIQUE_SYMBOL == (22724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22725)
		#define UNIQUE_FUNCTION<%0...%1> %05Y5%1
		#endinput
	#if UNIQUE_SYMBOL == (22725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22726)
		#define UNIQUE_FUNCTION<%0...%1> %05Y6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22727)
		#define UNIQUE_FUNCTION<%0...%1> %05Y7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (22735)
	#elseif UNIQUE_SYMBOL == (22727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22728)
		#define UNIQUE_FUNCTION<%0...%1> %05Y8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22729)
		#define UNIQUE_FUNCTION<%0...%1> %05Y9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22730)
		#define UNIQUE_FUNCTION<%0...%1> %05Y@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22731)
		#define UNIQUE_FUNCTION<%0...%1> %05YA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22732)
		#define UNIQUE_FUNCTION<%0...%1> %05YB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22733)
		#define UNIQUE_FUNCTION<%0...%1> %05YC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22734)
		#define UNIQUE_FUNCTION<%0...%1> %05YD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22735)
		#define UNIQUE_FUNCTION<%0...%1> %05YE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (22743)
	#elseif UNIQUE_SYMBOL == (22735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22736)
		#define UNIQUE_FUNCTION<%0...%1> %05YF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22737)
		#define UNIQUE_FUNCTION<%0...%1> %05YG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22738)
		#define UNIQUE_FUNCTION<%0...%1> %05YH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22739)
		#define UNIQUE_FUNCTION<%0...%1> %05YI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22740)
		#define UNIQUE_FUNCTION<%0...%1> %05YJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22741)
		#define UNIQUE_FUNCTION<%0...%1> %05YK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22742)
		#define UNIQUE_FUNCTION<%0...%1> %05YL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22743)
		#define UNIQUE_FUNCTION<%0...%1> %05YM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (22751)
	#elseif UNIQUE_SYMBOL == (22743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22744)
		#define UNIQUE_FUNCTION<%0...%1> %05YN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22745)
		#define UNIQUE_FUNCTION<%0...%1> %05YO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22746)
		#define UNIQUE_FUNCTION<%0...%1> %05YP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22747)
		#define UNIQUE_FUNCTION<%0...%1> %05YQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22748)
		#define UNIQUE_FUNCTION<%0...%1> %05YR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22749)
		#define UNIQUE_FUNCTION<%0...%1> %05YS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22750)
		#define UNIQUE_FUNCTION<%0...%1> %05YT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22751)
		#define UNIQUE_FUNCTION<%0...%1> %05YU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (22759)
	#elseif UNIQUE_SYMBOL == (22751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22752)
		#define UNIQUE_FUNCTION<%0...%1> %05YV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22753)
		#define UNIQUE_FUNCTION<%0...%1> %05YW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22754)
		#define UNIQUE_FUNCTION<%0...%1> %05YX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22755)
		#define UNIQUE_FUNCTION<%0...%1> %05YY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22756)
		#define UNIQUE_FUNCTION<%0...%1> %05YZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22757)
		#define UNIQUE_FUNCTION<%0...%1> %05Y_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22758)
		#define UNIQUE_FUNCTION<%0...%1> %05Ya%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22759)
		#define UNIQUE_FUNCTION<%0...%1> %05Yb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (22767)
	#elseif UNIQUE_SYMBOL == (22759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22760)
		#define UNIQUE_FUNCTION<%0...%1> %05Yc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22761)
		#define UNIQUE_FUNCTION<%0...%1> %05Yd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22762)
		#define UNIQUE_FUNCTION<%0...%1> %05Ye%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22763)
		#define UNIQUE_FUNCTION<%0...%1> %05Yf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22764)
		#define UNIQUE_FUNCTION<%0...%1> %05Yg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22765)
		#define UNIQUE_FUNCTION<%0...%1> %05Yh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22766)
		#define UNIQUE_FUNCTION<%0...%1> %05Yi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22767)
		#define UNIQUE_FUNCTION<%0...%1> %05Yj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (22775)
	#elseif UNIQUE_SYMBOL == (22767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22768)
		#define UNIQUE_FUNCTION<%0...%1> %05Yk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22769)
		#define UNIQUE_FUNCTION<%0...%1> %05Yl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22770)
		#define UNIQUE_FUNCTION<%0...%1> %05Ym%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22771)
		#define UNIQUE_FUNCTION<%0...%1> %05Yn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22772)
		#define UNIQUE_FUNCTION<%0...%1> %05Yo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22773)
		#define UNIQUE_FUNCTION<%0...%1> %05Yp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22774)
		#define UNIQUE_FUNCTION<%0...%1> %05Yq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22775)
		#define UNIQUE_FUNCTION<%0...%1> %05Yr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (22775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22776)
		#define UNIQUE_FUNCTION<%0...%1> %05Ys%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22777)
		#define UNIQUE_FUNCTION<%0...%1> %05Yt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22778)
		#define UNIQUE_FUNCTION<%0...%1> %05Yu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22779)
		#define UNIQUE_FUNCTION<%0...%1> %05Yv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22780)
		#define UNIQUE_FUNCTION<%0...%1> %05Yw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22781)
		#define UNIQUE_FUNCTION<%0...%1> %05Yx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (22781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22782)
		#define UNIQUE_FUNCTION<%0...%1> %05Yy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (22783)
		#define UNIQUE_FUNCTION<%0...%1> %05Yz%1
		#endinput
	#endif
#endif
