static stock const Y_UNIQUE_028544_028607_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_028544_028607
	#undef _inc_y_unique_028544_028607
#endif

#if UNIQUE_SYMBOL < (28551)
	#if UNIQUE_SYMBOL == (28543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28544)
		#define UNIQUE_FUNCTION<%0...%1> %06y0%1
		#endinput
	#if UNIQUE_SYMBOL == (28544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28545)
		#define UNIQUE_FUNCTION<%0...%1> %06y1%1
		#endinput
	#if UNIQUE_SYMBOL == (28545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28546)
		#define UNIQUE_FUNCTION<%0...%1> %06y2%1
		#endinput
	#if UNIQUE_SYMBOL == (28546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28547)
		#define UNIQUE_FUNCTION<%0...%1> %06y3%1
		#endinput
	#if UNIQUE_SYMBOL == (28547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28548)
		#define UNIQUE_FUNCTION<%0...%1> %06y4%1
		#endinput
	#if UNIQUE_SYMBOL == (28548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28549)
		#define UNIQUE_FUNCTION<%0...%1> %06y5%1
		#endinput
	#if UNIQUE_SYMBOL == (28549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28550)
		#define UNIQUE_FUNCTION<%0...%1> %06y6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28551)
		#define UNIQUE_FUNCTION<%0...%1> %06y7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28559)
	#elseif UNIQUE_SYMBOL == (28551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28552)
		#define UNIQUE_FUNCTION<%0...%1> %06y8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28553)
		#define UNIQUE_FUNCTION<%0...%1> %06y9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28554)
		#define UNIQUE_FUNCTION<%0...%1> %06y@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28555)
		#define UNIQUE_FUNCTION<%0...%1> %06yA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28556)
		#define UNIQUE_FUNCTION<%0...%1> %06yB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28557)
		#define UNIQUE_FUNCTION<%0...%1> %06yC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28558)
		#define UNIQUE_FUNCTION<%0...%1> %06yD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28559)
		#define UNIQUE_FUNCTION<%0...%1> %06yE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28567)
	#elseif UNIQUE_SYMBOL == (28559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28560)
		#define UNIQUE_FUNCTION<%0...%1> %06yF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28561)
		#define UNIQUE_FUNCTION<%0...%1> %06yG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28562)
		#define UNIQUE_FUNCTION<%0...%1> %06yH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28563)
		#define UNIQUE_FUNCTION<%0...%1> %06yI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28564)
		#define UNIQUE_FUNCTION<%0...%1> %06yJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28565)
		#define UNIQUE_FUNCTION<%0...%1> %06yK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28566)
		#define UNIQUE_FUNCTION<%0...%1> %06yL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28567)
		#define UNIQUE_FUNCTION<%0...%1> %06yM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28575)
	#elseif UNIQUE_SYMBOL == (28567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28568)
		#define UNIQUE_FUNCTION<%0...%1> %06yN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28569)
		#define UNIQUE_FUNCTION<%0...%1> %06yO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28570)
		#define UNIQUE_FUNCTION<%0...%1> %06yP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28571)
		#define UNIQUE_FUNCTION<%0...%1> %06yQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28572)
		#define UNIQUE_FUNCTION<%0...%1> %06yR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28573)
		#define UNIQUE_FUNCTION<%0...%1> %06yS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28574)
		#define UNIQUE_FUNCTION<%0...%1> %06yT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28575)
		#define UNIQUE_FUNCTION<%0...%1> %06yU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28583)
	#elseif UNIQUE_SYMBOL == (28575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28576)
		#define UNIQUE_FUNCTION<%0...%1> %06yV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28577)
		#define UNIQUE_FUNCTION<%0...%1> %06yW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28578)
		#define UNIQUE_FUNCTION<%0...%1> %06yX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28579)
		#define UNIQUE_FUNCTION<%0...%1> %06yY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28580)
		#define UNIQUE_FUNCTION<%0...%1> %06yZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28581)
		#define UNIQUE_FUNCTION<%0...%1> %06y_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28582)
		#define UNIQUE_FUNCTION<%0...%1> %06ya%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28583)
		#define UNIQUE_FUNCTION<%0...%1> %06yb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28591)
	#elseif UNIQUE_SYMBOL == (28583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28584)
		#define UNIQUE_FUNCTION<%0...%1> %06yc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28585)
		#define UNIQUE_FUNCTION<%0...%1> %06yd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28586)
		#define UNIQUE_FUNCTION<%0...%1> %06ye%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28587)
		#define UNIQUE_FUNCTION<%0...%1> %06yf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28588)
		#define UNIQUE_FUNCTION<%0...%1> %06yg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28589)
		#define UNIQUE_FUNCTION<%0...%1> %06yh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28590)
		#define UNIQUE_FUNCTION<%0...%1> %06yi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28591)
		#define UNIQUE_FUNCTION<%0...%1> %06yj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (28599)
	#elseif UNIQUE_SYMBOL == (28591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28592)
		#define UNIQUE_FUNCTION<%0...%1> %06yk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28593)
		#define UNIQUE_FUNCTION<%0...%1> %06yl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28594)
		#define UNIQUE_FUNCTION<%0...%1> %06ym%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28595)
		#define UNIQUE_FUNCTION<%0...%1> %06yn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28596)
		#define UNIQUE_FUNCTION<%0...%1> %06yo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28597)
		#define UNIQUE_FUNCTION<%0...%1> %06yp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28598)
		#define UNIQUE_FUNCTION<%0...%1> %06yq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28599)
		#define UNIQUE_FUNCTION<%0...%1> %06yr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (28599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28600)
		#define UNIQUE_FUNCTION<%0...%1> %06ys%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28601)
		#define UNIQUE_FUNCTION<%0...%1> %06yt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28602)
		#define UNIQUE_FUNCTION<%0...%1> %06yu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28603)
		#define UNIQUE_FUNCTION<%0...%1> %06yv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28604)
		#define UNIQUE_FUNCTION<%0...%1> %06yw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28605)
		#define UNIQUE_FUNCTION<%0...%1> %06yx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (28605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28606)
		#define UNIQUE_FUNCTION<%0...%1> %06yy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28607)
		#define UNIQUE_FUNCTION<%0...%1> %06yz%1
		#endinput
	#endif
#endif
