static stock const Y_UNIQUE_061504_061567_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_061504_061567
	#undef _inc_y_unique_061504_061567
#endif

#if UNIQUE_SYMBOL < (61511)
	#if UNIQUE_SYMBOL == (61503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61504)
		#define UNIQUE_FUNCTION<%0...%1> %0E10%1
		#endinput
	#if UNIQUE_SYMBOL == (61504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61505)
		#define UNIQUE_FUNCTION<%0...%1> %0E11%1
		#endinput
	#if UNIQUE_SYMBOL == (61505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61506)
		#define UNIQUE_FUNCTION<%0...%1> %0E12%1
		#endinput
	#if UNIQUE_SYMBOL == (61506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61507)
		#define UNIQUE_FUNCTION<%0...%1> %0E13%1
		#endinput
	#if UNIQUE_SYMBOL == (61507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61508)
		#define UNIQUE_FUNCTION<%0...%1> %0E14%1
		#endinput
	#if UNIQUE_SYMBOL == (61508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61509)
		#define UNIQUE_FUNCTION<%0...%1> %0E15%1
		#endinput
	#if UNIQUE_SYMBOL == (61509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61510)
		#define UNIQUE_FUNCTION<%0...%1> %0E16%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61511)
		#define UNIQUE_FUNCTION<%0...%1> %0E17%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (61519)
	#elseif UNIQUE_SYMBOL == (61511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61512)
		#define UNIQUE_FUNCTION<%0...%1> %0E18%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61513)
		#define UNIQUE_FUNCTION<%0...%1> %0E19%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61514)
		#define UNIQUE_FUNCTION<%0...%1> %0E1@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61515)
		#define UNIQUE_FUNCTION<%0...%1> %0E1A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61516)
		#define UNIQUE_FUNCTION<%0...%1> %0E1B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61517)
		#define UNIQUE_FUNCTION<%0...%1> %0E1C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61518)
		#define UNIQUE_FUNCTION<%0...%1> %0E1D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61519)
		#define UNIQUE_FUNCTION<%0...%1> %0E1E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (61527)
	#elseif UNIQUE_SYMBOL == (61519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61520)
		#define UNIQUE_FUNCTION<%0...%1> %0E1F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61521)
		#define UNIQUE_FUNCTION<%0...%1> %0E1G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61522)
		#define UNIQUE_FUNCTION<%0...%1> %0E1H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61523)
		#define UNIQUE_FUNCTION<%0...%1> %0E1I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61524)
		#define UNIQUE_FUNCTION<%0...%1> %0E1J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61525)
		#define UNIQUE_FUNCTION<%0...%1> %0E1K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61526)
		#define UNIQUE_FUNCTION<%0...%1> %0E1L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61527)
		#define UNIQUE_FUNCTION<%0...%1> %0E1M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (61535)
	#elseif UNIQUE_SYMBOL == (61527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61528)
		#define UNIQUE_FUNCTION<%0...%1> %0E1N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61529)
		#define UNIQUE_FUNCTION<%0...%1> %0E1O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61530)
		#define UNIQUE_FUNCTION<%0...%1> %0E1P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61531)
		#define UNIQUE_FUNCTION<%0...%1> %0E1Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61532)
		#define UNIQUE_FUNCTION<%0...%1> %0E1R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61533)
		#define UNIQUE_FUNCTION<%0...%1> %0E1S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61534)
		#define UNIQUE_FUNCTION<%0...%1> %0E1T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61535)
		#define UNIQUE_FUNCTION<%0...%1> %0E1U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (61543)
	#elseif UNIQUE_SYMBOL == (61535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61536)
		#define UNIQUE_FUNCTION<%0...%1> %0E1V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61537)
		#define UNIQUE_FUNCTION<%0...%1> %0E1W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61538)
		#define UNIQUE_FUNCTION<%0...%1> %0E1X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61539)
		#define UNIQUE_FUNCTION<%0...%1> %0E1Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61540)
		#define UNIQUE_FUNCTION<%0...%1> %0E1Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61541)
		#define UNIQUE_FUNCTION<%0...%1> %0E1_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61542)
		#define UNIQUE_FUNCTION<%0...%1> %0E1a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61543)
		#define UNIQUE_FUNCTION<%0...%1> %0E1b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (61551)
	#elseif UNIQUE_SYMBOL == (61543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61544)
		#define UNIQUE_FUNCTION<%0...%1> %0E1c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61545)
		#define UNIQUE_FUNCTION<%0...%1> %0E1d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61546)
		#define UNIQUE_FUNCTION<%0...%1> %0E1e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61547)
		#define UNIQUE_FUNCTION<%0...%1> %0E1f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61548)
		#define UNIQUE_FUNCTION<%0...%1> %0E1g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61549)
		#define UNIQUE_FUNCTION<%0...%1> %0E1h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61550)
		#define UNIQUE_FUNCTION<%0...%1> %0E1i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61551)
		#define UNIQUE_FUNCTION<%0...%1> %0E1j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (61559)
	#elseif UNIQUE_SYMBOL == (61551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61552)
		#define UNIQUE_FUNCTION<%0...%1> %0E1k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61553)
		#define UNIQUE_FUNCTION<%0...%1> %0E1l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61554)
		#define UNIQUE_FUNCTION<%0...%1> %0E1m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61555)
		#define UNIQUE_FUNCTION<%0...%1> %0E1n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61556)
		#define UNIQUE_FUNCTION<%0...%1> %0E1o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61557)
		#define UNIQUE_FUNCTION<%0...%1> %0E1p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61558)
		#define UNIQUE_FUNCTION<%0...%1> %0E1q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61559)
		#define UNIQUE_FUNCTION<%0...%1> %0E1r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (61559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61560)
		#define UNIQUE_FUNCTION<%0...%1> %0E1s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61561)
		#define UNIQUE_FUNCTION<%0...%1> %0E1t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61562)
		#define UNIQUE_FUNCTION<%0...%1> %0E1u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61563)
		#define UNIQUE_FUNCTION<%0...%1> %0E1v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61564)
		#define UNIQUE_FUNCTION<%0...%1> %0E1w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61565)
		#define UNIQUE_FUNCTION<%0...%1> %0E1x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (61565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61566)
		#define UNIQUE_FUNCTION<%0...%1> %0E1y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (61567)
		#define UNIQUE_FUNCTION<%0...%1> %0E1z%1
		#endinput
	#endif
#endif
