static stock const Y_UNIQUE_159872_159935_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_159872_159935
	#undef _inc_y_unique_159872_159935
#endif

#if UNIQUE_SYMBOL < (159879)
	#if UNIQUE_SYMBOL == (159871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159872)
		#define UNIQUE_FUNCTION<%0...%1> %0b20%1
		#endinput
	#if UNIQUE_SYMBOL == (159872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159873)
		#define UNIQUE_FUNCTION<%0...%1> %0b21%1
		#endinput
	#if UNIQUE_SYMBOL == (159873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159874)
		#define UNIQUE_FUNCTION<%0...%1> %0b22%1
		#endinput
	#if UNIQUE_SYMBOL == (159874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159875)
		#define UNIQUE_FUNCTION<%0...%1> %0b23%1
		#endinput
	#if UNIQUE_SYMBOL == (159875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159876)
		#define UNIQUE_FUNCTION<%0...%1> %0b24%1
		#endinput
	#if UNIQUE_SYMBOL == (159876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159877)
		#define UNIQUE_FUNCTION<%0...%1> %0b25%1
		#endinput
	#if UNIQUE_SYMBOL == (159877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159878)
		#define UNIQUE_FUNCTION<%0...%1> %0b26%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159879)
		#define UNIQUE_FUNCTION<%0...%1> %0b27%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (159887)
	#elseif UNIQUE_SYMBOL == (159879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159880)
		#define UNIQUE_FUNCTION<%0...%1> %0b28%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159881)
		#define UNIQUE_FUNCTION<%0...%1> %0b29%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159882)
		#define UNIQUE_FUNCTION<%0...%1> %0b2@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159883)
		#define UNIQUE_FUNCTION<%0...%1> %0b2A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159884)
		#define UNIQUE_FUNCTION<%0...%1> %0b2B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159885)
		#define UNIQUE_FUNCTION<%0...%1> %0b2C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159886)
		#define UNIQUE_FUNCTION<%0...%1> %0b2D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159887)
		#define UNIQUE_FUNCTION<%0...%1> %0b2E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (159895)
	#elseif UNIQUE_SYMBOL == (159887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159888)
		#define UNIQUE_FUNCTION<%0...%1> %0b2F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159889)
		#define UNIQUE_FUNCTION<%0...%1> %0b2G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159890)
		#define UNIQUE_FUNCTION<%0...%1> %0b2H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159891)
		#define UNIQUE_FUNCTION<%0...%1> %0b2I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159892)
		#define UNIQUE_FUNCTION<%0...%1> %0b2J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159893)
		#define UNIQUE_FUNCTION<%0...%1> %0b2K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159894)
		#define UNIQUE_FUNCTION<%0...%1> %0b2L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159895)
		#define UNIQUE_FUNCTION<%0...%1> %0b2M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (159903)
	#elseif UNIQUE_SYMBOL == (159895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159896)
		#define UNIQUE_FUNCTION<%0...%1> %0b2N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159897)
		#define UNIQUE_FUNCTION<%0...%1> %0b2O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159898)
		#define UNIQUE_FUNCTION<%0...%1> %0b2P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159899)
		#define UNIQUE_FUNCTION<%0...%1> %0b2Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159900)
		#define UNIQUE_FUNCTION<%0...%1> %0b2R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159901)
		#define UNIQUE_FUNCTION<%0...%1> %0b2S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159902)
		#define UNIQUE_FUNCTION<%0...%1> %0b2T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159903)
		#define UNIQUE_FUNCTION<%0...%1> %0b2U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (159911)
	#elseif UNIQUE_SYMBOL == (159903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159904)
		#define UNIQUE_FUNCTION<%0...%1> %0b2V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159905)
		#define UNIQUE_FUNCTION<%0...%1> %0b2W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159906)
		#define UNIQUE_FUNCTION<%0...%1> %0b2X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159907)
		#define UNIQUE_FUNCTION<%0...%1> %0b2Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159908)
		#define UNIQUE_FUNCTION<%0...%1> %0b2Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159909)
		#define UNIQUE_FUNCTION<%0...%1> %0b2_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159910)
		#define UNIQUE_FUNCTION<%0...%1> %0b2a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159911)
		#define UNIQUE_FUNCTION<%0...%1> %0b2b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (159919)
	#elseif UNIQUE_SYMBOL == (159911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159912)
		#define UNIQUE_FUNCTION<%0...%1> %0b2c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159913)
		#define UNIQUE_FUNCTION<%0...%1> %0b2d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159914)
		#define UNIQUE_FUNCTION<%0...%1> %0b2e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159915)
		#define UNIQUE_FUNCTION<%0...%1> %0b2f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159916)
		#define UNIQUE_FUNCTION<%0...%1> %0b2g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159917)
		#define UNIQUE_FUNCTION<%0...%1> %0b2h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159918)
		#define UNIQUE_FUNCTION<%0...%1> %0b2i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159919)
		#define UNIQUE_FUNCTION<%0...%1> %0b2j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (159927)
	#elseif UNIQUE_SYMBOL == (159919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159920)
		#define UNIQUE_FUNCTION<%0...%1> %0b2k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159921)
		#define UNIQUE_FUNCTION<%0...%1> %0b2l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159922)
		#define UNIQUE_FUNCTION<%0...%1> %0b2m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159923)
		#define UNIQUE_FUNCTION<%0...%1> %0b2n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159924)
		#define UNIQUE_FUNCTION<%0...%1> %0b2o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159925)
		#define UNIQUE_FUNCTION<%0...%1> %0b2p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159926)
		#define UNIQUE_FUNCTION<%0...%1> %0b2q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159927)
		#define UNIQUE_FUNCTION<%0...%1> %0b2r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (159927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159928)
		#define UNIQUE_FUNCTION<%0...%1> %0b2s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159929)
		#define UNIQUE_FUNCTION<%0...%1> %0b2t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159930)
		#define UNIQUE_FUNCTION<%0...%1> %0b2u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159931)
		#define UNIQUE_FUNCTION<%0...%1> %0b2v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159932)
		#define UNIQUE_FUNCTION<%0...%1> %0b2w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159933)
		#define UNIQUE_FUNCTION<%0...%1> %0b2x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (159933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159934)
		#define UNIQUE_FUNCTION<%0...%1> %0b2y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (159935)
		#define UNIQUE_FUNCTION<%0...%1> %0b2z%1
		#endinput
	#endif
#endif
