static stock const Y_UNIQUE_079744_079807_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_079744_079807
	#undef _inc_y_unique_079744_079807
#endif

#if UNIQUE_SYMBOL < (79751)
	#if UNIQUE_SYMBOL == (79743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79744)
		#define UNIQUE_FUNCTION<%0...%1> %0IT0%1
		#endinput
	#if UNIQUE_SYMBOL == (79744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79745)
		#define UNIQUE_FUNCTION<%0...%1> %0IT1%1
		#endinput
	#if UNIQUE_SYMBOL == (79745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79746)
		#define UNIQUE_FUNCTION<%0...%1> %0IT2%1
		#endinput
	#if UNIQUE_SYMBOL == (79746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79747)
		#define UNIQUE_FUNCTION<%0...%1> %0IT3%1
		#endinput
	#if UNIQUE_SYMBOL == (79747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79748)
		#define UNIQUE_FUNCTION<%0...%1> %0IT4%1
		#endinput
	#if UNIQUE_SYMBOL == (79748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79749)
		#define UNIQUE_FUNCTION<%0...%1> %0IT5%1
		#endinput
	#if UNIQUE_SYMBOL == (79749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79750)
		#define UNIQUE_FUNCTION<%0...%1> %0IT6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79751)
		#define UNIQUE_FUNCTION<%0...%1> %0IT7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79759)
	#elseif UNIQUE_SYMBOL == (79751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79752)
		#define UNIQUE_FUNCTION<%0...%1> %0IT8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79753)
		#define UNIQUE_FUNCTION<%0...%1> %0IT9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79754)
		#define UNIQUE_FUNCTION<%0...%1> %0IT@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79755)
		#define UNIQUE_FUNCTION<%0...%1> %0ITA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79756)
		#define UNIQUE_FUNCTION<%0...%1> %0ITB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79757)
		#define UNIQUE_FUNCTION<%0...%1> %0ITC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79758)
		#define UNIQUE_FUNCTION<%0...%1> %0ITD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79759)
		#define UNIQUE_FUNCTION<%0...%1> %0ITE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79767)
	#elseif UNIQUE_SYMBOL == (79759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79760)
		#define UNIQUE_FUNCTION<%0...%1> %0ITF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79761)
		#define UNIQUE_FUNCTION<%0...%1> %0ITG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79762)
		#define UNIQUE_FUNCTION<%0...%1> %0ITH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79763)
		#define UNIQUE_FUNCTION<%0...%1> %0ITI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79764)
		#define UNIQUE_FUNCTION<%0...%1> %0ITJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79765)
		#define UNIQUE_FUNCTION<%0...%1> %0ITK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79766)
		#define UNIQUE_FUNCTION<%0...%1> %0ITL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79767)
		#define UNIQUE_FUNCTION<%0...%1> %0ITM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79775)
	#elseif UNIQUE_SYMBOL == (79767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79768)
		#define UNIQUE_FUNCTION<%0...%1> %0ITN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79769)
		#define UNIQUE_FUNCTION<%0...%1> %0ITO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79770)
		#define UNIQUE_FUNCTION<%0...%1> %0ITP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79771)
		#define UNIQUE_FUNCTION<%0...%1> %0ITQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79772)
		#define UNIQUE_FUNCTION<%0...%1> %0ITR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79773)
		#define UNIQUE_FUNCTION<%0...%1> %0ITS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79774)
		#define UNIQUE_FUNCTION<%0...%1> %0ITT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79775)
		#define UNIQUE_FUNCTION<%0...%1> %0ITU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79783)
	#elseif UNIQUE_SYMBOL == (79775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79776)
		#define UNIQUE_FUNCTION<%0...%1> %0ITV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79777)
		#define UNIQUE_FUNCTION<%0...%1> %0ITW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79778)
		#define UNIQUE_FUNCTION<%0...%1> %0ITX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79779)
		#define UNIQUE_FUNCTION<%0...%1> %0ITY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79780)
		#define UNIQUE_FUNCTION<%0...%1> %0ITZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79781)
		#define UNIQUE_FUNCTION<%0...%1> %0IT_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79782)
		#define UNIQUE_FUNCTION<%0...%1> %0ITa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79783)
		#define UNIQUE_FUNCTION<%0...%1> %0ITb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79791)
	#elseif UNIQUE_SYMBOL == (79783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79784)
		#define UNIQUE_FUNCTION<%0...%1> %0ITc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79785)
		#define UNIQUE_FUNCTION<%0...%1> %0ITd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79786)
		#define UNIQUE_FUNCTION<%0...%1> %0ITe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79787)
		#define UNIQUE_FUNCTION<%0...%1> %0ITf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79788)
		#define UNIQUE_FUNCTION<%0...%1> %0ITg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79789)
		#define UNIQUE_FUNCTION<%0...%1> %0ITh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79790)
		#define UNIQUE_FUNCTION<%0...%1> %0ITi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79791)
		#define UNIQUE_FUNCTION<%0...%1> %0ITj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79799)
	#elseif UNIQUE_SYMBOL == (79791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79792)
		#define UNIQUE_FUNCTION<%0...%1> %0ITk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79793)
		#define UNIQUE_FUNCTION<%0...%1> %0ITl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79794)
		#define UNIQUE_FUNCTION<%0...%1> %0ITm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79795)
		#define UNIQUE_FUNCTION<%0...%1> %0ITn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79796)
		#define UNIQUE_FUNCTION<%0...%1> %0ITo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79797)
		#define UNIQUE_FUNCTION<%0...%1> %0ITp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79798)
		#define UNIQUE_FUNCTION<%0...%1> %0ITq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79799)
		#define UNIQUE_FUNCTION<%0...%1> %0ITr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (79799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79800)
		#define UNIQUE_FUNCTION<%0...%1> %0ITs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79801)
		#define UNIQUE_FUNCTION<%0...%1> %0ITt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79802)
		#define UNIQUE_FUNCTION<%0...%1> %0ITu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79803)
		#define UNIQUE_FUNCTION<%0...%1> %0ITv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79804)
		#define UNIQUE_FUNCTION<%0...%1> %0ITw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79805)
		#define UNIQUE_FUNCTION<%0...%1> %0ITx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79806)
		#define UNIQUE_FUNCTION<%0...%1> %0ITy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79807)
		#define UNIQUE_FUNCTION<%0...%1> %0ITz%1
		#endinput
	#endif
#endif
