static stock const Y_UNIQUE_143488_143551_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_143488_143551
	#undef _inc_y_unique_143488_143551
#endif

#if UNIQUE_SYMBOL < (143495)
	#if UNIQUE_SYMBOL == (143487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143488)
		#define UNIQUE_FUNCTION<%0...%1> %0Y20%1
		#endinput
	#if UNIQUE_SYMBOL == (143488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143489)
		#define UNIQUE_FUNCTION<%0...%1> %0Y21%1
		#endinput
	#if UNIQUE_SYMBOL == (143489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143490)
		#define UNIQUE_FUNCTION<%0...%1> %0Y22%1
		#endinput
	#if UNIQUE_SYMBOL == (143490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143491)
		#define UNIQUE_FUNCTION<%0...%1> %0Y23%1
		#endinput
	#if UNIQUE_SYMBOL == (143491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143492)
		#define UNIQUE_FUNCTION<%0...%1> %0Y24%1
		#endinput
	#if UNIQUE_SYMBOL == (143492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143493)
		#define UNIQUE_FUNCTION<%0...%1> %0Y25%1
		#endinput
	#if UNIQUE_SYMBOL == (143493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143494)
		#define UNIQUE_FUNCTION<%0...%1> %0Y26%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143495)
		#define UNIQUE_FUNCTION<%0...%1> %0Y27%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (143503)
	#elseif UNIQUE_SYMBOL == (143495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143496)
		#define UNIQUE_FUNCTION<%0...%1> %0Y28%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143497)
		#define UNIQUE_FUNCTION<%0...%1> %0Y29%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143498)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143499)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143500)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143501)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143502)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143503)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (143511)
	#elseif UNIQUE_SYMBOL == (143503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143504)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143505)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143506)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143507)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143508)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143509)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143510)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143511)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (143519)
	#elseif UNIQUE_SYMBOL == (143511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143512)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143513)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143514)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143515)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143516)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143517)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143518)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143519)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (143527)
	#elseif UNIQUE_SYMBOL == (143519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143520)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143521)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143522)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143523)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143524)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143525)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143526)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143527)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (143535)
	#elseif UNIQUE_SYMBOL == (143527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143528)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143529)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143530)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143531)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143532)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143533)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143534)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143535)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (143543)
	#elseif UNIQUE_SYMBOL == (143535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143536)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143537)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143538)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143539)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143540)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143541)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143542)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143543)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (143543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143544)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143545)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143546)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143547)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143548)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143549)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (143549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143550)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (143551)
		#define UNIQUE_FUNCTION<%0...%1> %0Y2z%1
		#endinput
	#endif
#endif
