static stock const Y_UNIQUE_110336_110399_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_110336_110399
	#undef _inc_y_unique_110336_110399
#endif

#if UNIQUE_SYMBOL < (110343)
	#if UNIQUE_SYMBOL == (110335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110336)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw0%1
		#endinput
	#if UNIQUE_SYMBOL == (110336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110337)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw1%1
		#endinput
	#if UNIQUE_SYMBOL == (110337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110338)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw2%1
		#endinput
	#if UNIQUE_SYMBOL == (110338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110339)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw3%1
		#endinput
	#if UNIQUE_SYMBOL == (110339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110340)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw4%1
		#endinput
	#if UNIQUE_SYMBOL == (110340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110341)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw5%1
		#endinput
	#if UNIQUE_SYMBOL == (110341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110342)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110343)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (110351)
	#elseif UNIQUE_SYMBOL == (110343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110344)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110345)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110346)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110347)
		#define UNIQUE_FUNCTION<%0...%1> %0PwA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110348)
		#define UNIQUE_FUNCTION<%0...%1> %0PwB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110349)
		#define UNIQUE_FUNCTION<%0...%1> %0PwC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110350)
		#define UNIQUE_FUNCTION<%0...%1> %0PwD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110351)
		#define UNIQUE_FUNCTION<%0...%1> %0PwE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (110359)
	#elseif UNIQUE_SYMBOL == (110351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110352)
		#define UNIQUE_FUNCTION<%0...%1> %0PwF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110353)
		#define UNIQUE_FUNCTION<%0...%1> %0PwG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110354)
		#define UNIQUE_FUNCTION<%0...%1> %0PwH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110355)
		#define UNIQUE_FUNCTION<%0...%1> %0PwI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110356)
		#define UNIQUE_FUNCTION<%0...%1> %0PwJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110357)
		#define UNIQUE_FUNCTION<%0...%1> %0PwK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110358)
		#define UNIQUE_FUNCTION<%0...%1> %0PwL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110359)
		#define UNIQUE_FUNCTION<%0...%1> %0PwM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (110367)
	#elseif UNIQUE_SYMBOL == (110359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110360)
		#define UNIQUE_FUNCTION<%0...%1> %0PwN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110361)
		#define UNIQUE_FUNCTION<%0...%1> %0PwO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110362)
		#define UNIQUE_FUNCTION<%0...%1> %0PwP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110363)
		#define UNIQUE_FUNCTION<%0...%1> %0PwQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110364)
		#define UNIQUE_FUNCTION<%0...%1> %0PwR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110365)
		#define UNIQUE_FUNCTION<%0...%1> %0PwS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110366)
		#define UNIQUE_FUNCTION<%0...%1> %0PwT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110367)
		#define UNIQUE_FUNCTION<%0...%1> %0PwU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (110375)
	#elseif UNIQUE_SYMBOL == (110367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110368)
		#define UNIQUE_FUNCTION<%0...%1> %0PwV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110369)
		#define UNIQUE_FUNCTION<%0...%1> %0PwW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110370)
		#define UNIQUE_FUNCTION<%0...%1> %0PwX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110371)
		#define UNIQUE_FUNCTION<%0...%1> %0PwY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110372)
		#define UNIQUE_FUNCTION<%0...%1> %0PwZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110373)
		#define UNIQUE_FUNCTION<%0...%1> %0Pw_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110374)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110375)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (110383)
	#elseif UNIQUE_SYMBOL == (110375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110376)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110377)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110378)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110379)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110380)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110381)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110382)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110383)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (110391)
	#elseif UNIQUE_SYMBOL == (110383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110384)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110385)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110386)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110387)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110388)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110389)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110390)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110391)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (110391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110392)
		#define UNIQUE_FUNCTION<%0...%1> %0Pws%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110393)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110394)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110395)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110396)
		#define UNIQUE_FUNCTION<%0...%1> %0Pww%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110397)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (110397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110398)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (110399)
		#define UNIQUE_FUNCTION<%0...%1> %0Pwz%1
		#endinput
	#endif
#endif
