static stock const Y_UNIQUE_136000_136063_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_136000_136063
	#undef _inc_y_unique_136000_136063
#endif

#if UNIQUE_SYMBOL < (136007)
	#if UNIQUE_SYMBOL == (135999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136000)
		#define UNIQUE_FUNCTION<%0...%1> %0WC0%1
		#endinput
	#if UNIQUE_SYMBOL == (136000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136001)
		#define UNIQUE_FUNCTION<%0...%1> %0WC1%1
		#endinput
	#if UNIQUE_SYMBOL == (136001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136002)
		#define UNIQUE_FUNCTION<%0...%1> %0WC2%1
		#endinput
	#if UNIQUE_SYMBOL == (136002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136003)
		#define UNIQUE_FUNCTION<%0...%1> %0WC3%1
		#endinput
	#if UNIQUE_SYMBOL == (136003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136004)
		#define UNIQUE_FUNCTION<%0...%1> %0WC4%1
		#endinput
	#if UNIQUE_SYMBOL == (136004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136005)
		#define UNIQUE_FUNCTION<%0...%1> %0WC5%1
		#endinput
	#if UNIQUE_SYMBOL == (136005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136006)
		#define UNIQUE_FUNCTION<%0...%1> %0WC6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136007)
		#define UNIQUE_FUNCTION<%0...%1> %0WC7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136015)
	#elseif UNIQUE_SYMBOL == (136007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136008)
		#define UNIQUE_FUNCTION<%0...%1> %0WC8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136009)
		#define UNIQUE_FUNCTION<%0...%1> %0WC9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136010)
		#define UNIQUE_FUNCTION<%0...%1> %0WC@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136011)
		#define UNIQUE_FUNCTION<%0...%1> %0WCA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136012)
		#define UNIQUE_FUNCTION<%0...%1> %0WCB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136013)
		#define UNIQUE_FUNCTION<%0...%1> %0WCC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136014)
		#define UNIQUE_FUNCTION<%0...%1> %0WCD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136015)
		#define UNIQUE_FUNCTION<%0...%1> %0WCE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136023)
	#elseif UNIQUE_SYMBOL == (136015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136016)
		#define UNIQUE_FUNCTION<%0...%1> %0WCF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136017)
		#define UNIQUE_FUNCTION<%0...%1> %0WCG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136018)
		#define UNIQUE_FUNCTION<%0...%1> %0WCH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136019)
		#define UNIQUE_FUNCTION<%0...%1> %0WCI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136020)
		#define UNIQUE_FUNCTION<%0...%1> %0WCJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136021)
		#define UNIQUE_FUNCTION<%0...%1> %0WCK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136022)
		#define UNIQUE_FUNCTION<%0...%1> %0WCL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136023)
		#define UNIQUE_FUNCTION<%0...%1> %0WCM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136031)
	#elseif UNIQUE_SYMBOL == (136023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136024)
		#define UNIQUE_FUNCTION<%0...%1> %0WCN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136025)
		#define UNIQUE_FUNCTION<%0...%1> %0WCO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136026)
		#define UNIQUE_FUNCTION<%0...%1> %0WCP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136027)
		#define UNIQUE_FUNCTION<%0...%1> %0WCQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136028)
		#define UNIQUE_FUNCTION<%0...%1> %0WCR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136029)
		#define UNIQUE_FUNCTION<%0...%1> %0WCS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136030)
		#define UNIQUE_FUNCTION<%0...%1> %0WCT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136031)
		#define UNIQUE_FUNCTION<%0...%1> %0WCU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136039)
	#elseif UNIQUE_SYMBOL == (136031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136032)
		#define UNIQUE_FUNCTION<%0...%1> %0WCV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136033)
		#define UNIQUE_FUNCTION<%0...%1> %0WCW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136034)
		#define UNIQUE_FUNCTION<%0...%1> %0WCX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136035)
		#define UNIQUE_FUNCTION<%0...%1> %0WCY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136036)
		#define UNIQUE_FUNCTION<%0...%1> %0WCZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136037)
		#define UNIQUE_FUNCTION<%0...%1> %0WC_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136038)
		#define UNIQUE_FUNCTION<%0...%1> %0WCa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136039)
		#define UNIQUE_FUNCTION<%0...%1> %0WCb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136047)
	#elseif UNIQUE_SYMBOL == (136039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136040)
		#define UNIQUE_FUNCTION<%0...%1> %0WCc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136041)
		#define UNIQUE_FUNCTION<%0...%1> %0WCd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136042)
		#define UNIQUE_FUNCTION<%0...%1> %0WCe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136043)
		#define UNIQUE_FUNCTION<%0...%1> %0WCf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136044)
		#define UNIQUE_FUNCTION<%0...%1> %0WCg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136045)
		#define UNIQUE_FUNCTION<%0...%1> %0WCh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136046)
		#define UNIQUE_FUNCTION<%0...%1> %0WCi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136047)
		#define UNIQUE_FUNCTION<%0...%1> %0WCj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136055)
	#elseif UNIQUE_SYMBOL == (136047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136048)
		#define UNIQUE_FUNCTION<%0...%1> %0WCk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136049)
		#define UNIQUE_FUNCTION<%0...%1> %0WCl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136050)
		#define UNIQUE_FUNCTION<%0...%1> %0WCm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136051)
		#define UNIQUE_FUNCTION<%0...%1> %0WCn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136052)
		#define UNIQUE_FUNCTION<%0...%1> %0WCo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136053)
		#define UNIQUE_FUNCTION<%0...%1> %0WCp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136054)
		#define UNIQUE_FUNCTION<%0...%1> %0WCq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136055)
		#define UNIQUE_FUNCTION<%0...%1> %0WCr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (136055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136056)
		#define UNIQUE_FUNCTION<%0...%1> %0WCs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136057)
		#define UNIQUE_FUNCTION<%0...%1> %0WCt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136058)
		#define UNIQUE_FUNCTION<%0...%1> %0WCu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136059)
		#define UNIQUE_FUNCTION<%0...%1> %0WCv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136060)
		#define UNIQUE_FUNCTION<%0...%1> %0WCw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136061)
		#define UNIQUE_FUNCTION<%0...%1> %0WCx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136062)
		#define UNIQUE_FUNCTION<%0...%1> %0WCy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136063)
		#define UNIQUE_FUNCTION<%0...%1> %0WCz%1
		#endinput
	#endif
#endif
