static stock const Y_UNIQUE_042368_042431_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_042368_042431
	#undef _inc_y_unique_042368_042431
#endif

#if UNIQUE_SYMBOL < (42375)
	#if UNIQUE_SYMBOL == (42367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42368)
		#define UNIQUE_FUNCTION<%0...%1> %0@L0%1
		#endinput
	#if UNIQUE_SYMBOL == (42368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42369)
		#define UNIQUE_FUNCTION<%0...%1> %0@L1%1
		#endinput
	#if UNIQUE_SYMBOL == (42369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42370)
		#define UNIQUE_FUNCTION<%0...%1> %0@L2%1
		#endinput
	#if UNIQUE_SYMBOL == (42370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42371)
		#define UNIQUE_FUNCTION<%0...%1> %0@L3%1
		#endinput
	#if UNIQUE_SYMBOL == (42371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42372)
		#define UNIQUE_FUNCTION<%0...%1> %0@L4%1
		#endinput
	#if UNIQUE_SYMBOL == (42372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42373)
		#define UNIQUE_FUNCTION<%0...%1> %0@L5%1
		#endinput
	#if UNIQUE_SYMBOL == (42373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42374)
		#define UNIQUE_FUNCTION<%0...%1> %0@L6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42375)
		#define UNIQUE_FUNCTION<%0...%1> %0@L7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (42383)
	#elseif UNIQUE_SYMBOL == (42375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42376)
		#define UNIQUE_FUNCTION<%0...%1> %0@L8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42377)
		#define UNIQUE_FUNCTION<%0...%1> %0@L9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42378)
		#define UNIQUE_FUNCTION<%0...%1> %0@L@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42379)
		#define UNIQUE_FUNCTION<%0...%1> %0@LA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42380)
		#define UNIQUE_FUNCTION<%0...%1> %0@LB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42381)
		#define UNIQUE_FUNCTION<%0...%1> %0@LC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42382)
		#define UNIQUE_FUNCTION<%0...%1> %0@LD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42383)
		#define UNIQUE_FUNCTION<%0...%1> %0@LE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (42391)
	#elseif UNIQUE_SYMBOL == (42383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42384)
		#define UNIQUE_FUNCTION<%0...%1> %0@LF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42385)
		#define UNIQUE_FUNCTION<%0...%1> %0@LG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42386)
		#define UNIQUE_FUNCTION<%0...%1> %0@LH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42387)
		#define UNIQUE_FUNCTION<%0...%1> %0@LI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42388)
		#define UNIQUE_FUNCTION<%0...%1> %0@LJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42389)
		#define UNIQUE_FUNCTION<%0...%1> %0@LK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42390)
		#define UNIQUE_FUNCTION<%0...%1> %0@LL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42391)
		#define UNIQUE_FUNCTION<%0...%1> %0@LM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (42399)
	#elseif UNIQUE_SYMBOL == (42391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42392)
		#define UNIQUE_FUNCTION<%0...%1> %0@LN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42393)
		#define UNIQUE_FUNCTION<%0...%1> %0@LO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42394)
		#define UNIQUE_FUNCTION<%0...%1> %0@LP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42395)
		#define UNIQUE_FUNCTION<%0...%1> %0@LQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42396)
		#define UNIQUE_FUNCTION<%0...%1> %0@LR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42397)
		#define UNIQUE_FUNCTION<%0...%1> %0@LS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42398)
		#define UNIQUE_FUNCTION<%0...%1> %0@LT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42399)
		#define UNIQUE_FUNCTION<%0...%1> %0@LU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (42407)
	#elseif UNIQUE_SYMBOL == (42399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42400)
		#define UNIQUE_FUNCTION<%0...%1> %0@LV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42401)
		#define UNIQUE_FUNCTION<%0...%1> %0@LW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42402)
		#define UNIQUE_FUNCTION<%0...%1> %0@LX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42403)
		#define UNIQUE_FUNCTION<%0...%1> %0@LY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42404)
		#define UNIQUE_FUNCTION<%0...%1> %0@LZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42405)
		#define UNIQUE_FUNCTION<%0...%1> %0@L_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42406)
		#define UNIQUE_FUNCTION<%0...%1> %0@La%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42407)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (42415)
	#elseif UNIQUE_SYMBOL == (42407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42408)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42409)
		#define UNIQUE_FUNCTION<%0...%1> %0@Ld%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42410)
		#define UNIQUE_FUNCTION<%0...%1> %0@Le%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42411)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42412)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42413)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42414)
		#define UNIQUE_FUNCTION<%0...%1> %0@Li%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42415)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (42423)
	#elseif UNIQUE_SYMBOL == (42415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42416)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42417)
		#define UNIQUE_FUNCTION<%0...%1> %0@Ll%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42418)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42419)
		#define UNIQUE_FUNCTION<%0...%1> %0@Ln%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42420)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42421)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42422)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42423)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (42423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42424)
		#define UNIQUE_FUNCTION<%0...%1> %0@Ls%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42425)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42426)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42427)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42428)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42429)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (42429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42430)
		#define UNIQUE_FUNCTION<%0...%1> %0@Ly%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (42431)
		#define UNIQUE_FUNCTION<%0...%1> %0@Lz%1
		#endinput
	#endif
#endif
