static stock const Y_UNIQUE_241536_241599_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_241536_241599
	#undef _inc_y_unique_241536_241599
#endif

#if UNIQUE_SYMBOL < (241543)
	#if UNIQUE_SYMBOL == (241535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241536)
		#define UNIQUE_FUNCTION<%0...%1> %0uy0%1
		#endinput
	#if UNIQUE_SYMBOL == (241536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241537)
		#define UNIQUE_FUNCTION<%0...%1> %0uy1%1
		#endinput
	#if UNIQUE_SYMBOL == (241537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241538)
		#define UNIQUE_FUNCTION<%0...%1> %0uy2%1
		#endinput
	#if UNIQUE_SYMBOL == (241538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241539)
		#define UNIQUE_FUNCTION<%0...%1> %0uy3%1
		#endinput
	#if UNIQUE_SYMBOL == (241539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241540)
		#define UNIQUE_FUNCTION<%0...%1> %0uy4%1
		#endinput
	#if UNIQUE_SYMBOL == (241540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241541)
		#define UNIQUE_FUNCTION<%0...%1> %0uy5%1
		#endinput
	#if UNIQUE_SYMBOL == (241541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241542)
		#define UNIQUE_FUNCTION<%0...%1> %0uy6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241543)
		#define UNIQUE_FUNCTION<%0...%1> %0uy7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241551)
	#elseif UNIQUE_SYMBOL == (241543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241544)
		#define UNIQUE_FUNCTION<%0...%1> %0uy8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241545)
		#define UNIQUE_FUNCTION<%0...%1> %0uy9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241546)
		#define UNIQUE_FUNCTION<%0...%1> %0uy@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241547)
		#define UNIQUE_FUNCTION<%0...%1> %0uyA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241548)
		#define UNIQUE_FUNCTION<%0...%1> %0uyB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241549)
		#define UNIQUE_FUNCTION<%0...%1> %0uyC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241550)
		#define UNIQUE_FUNCTION<%0...%1> %0uyD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241551)
		#define UNIQUE_FUNCTION<%0...%1> %0uyE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241559)
	#elseif UNIQUE_SYMBOL == (241551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241552)
		#define UNIQUE_FUNCTION<%0...%1> %0uyF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241553)
		#define UNIQUE_FUNCTION<%0...%1> %0uyG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241554)
		#define UNIQUE_FUNCTION<%0...%1> %0uyH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241555)
		#define UNIQUE_FUNCTION<%0...%1> %0uyI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241556)
		#define UNIQUE_FUNCTION<%0...%1> %0uyJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241557)
		#define UNIQUE_FUNCTION<%0...%1> %0uyK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241558)
		#define UNIQUE_FUNCTION<%0...%1> %0uyL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241559)
		#define UNIQUE_FUNCTION<%0...%1> %0uyM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241567)
	#elseif UNIQUE_SYMBOL == (241559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241560)
		#define UNIQUE_FUNCTION<%0...%1> %0uyN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241561)
		#define UNIQUE_FUNCTION<%0...%1> %0uyO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241562)
		#define UNIQUE_FUNCTION<%0...%1> %0uyP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241563)
		#define UNIQUE_FUNCTION<%0...%1> %0uyQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241564)
		#define UNIQUE_FUNCTION<%0...%1> %0uyR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241565)
		#define UNIQUE_FUNCTION<%0...%1> %0uyS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241566)
		#define UNIQUE_FUNCTION<%0...%1> %0uyT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241567)
		#define UNIQUE_FUNCTION<%0...%1> %0uyU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241575)
	#elseif UNIQUE_SYMBOL == (241567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241568)
		#define UNIQUE_FUNCTION<%0...%1> %0uyV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241569)
		#define UNIQUE_FUNCTION<%0...%1> %0uyW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241570)
		#define UNIQUE_FUNCTION<%0...%1> %0uyX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241571)
		#define UNIQUE_FUNCTION<%0...%1> %0uyY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241572)
		#define UNIQUE_FUNCTION<%0...%1> %0uyZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241573)
		#define UNIQUE_FUNCTION<%0...%1> %0uy_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241574)
		#define UNIQUE_FUNCTION<%0...%1> %0uya%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241575)
		#define UNIQUE_FUNCTION<%0...%1> %0uyb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241583)
	#elseif UNIQUE_SYMBOL == (241575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241576)
		#define UNIQUE_FUNCTION<%0...%1> %0uyc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241577)
		#define UNIQUE_FUNCTION<%0...%1> %0uyd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241578)
		#define UNIQUE_FUNCTION<%0...%1> %0uye%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241579)
		#define UNIQUE_FUNCTION<%0...%1> %0uyf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241580)
		#define UNIQUE_FUNCTION<%0...%1> %0uyg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241581)
		#define UNIQUE_FUNCTION<%0...%1> %0uyh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241582)
		#define UNIQUE_FUNCTION<%0...%1> %0uyi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241583)
		#define UNIQUE_FUNCTION<%0...%1> %0uyj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (241591)
	#elseif UNIQUE_SYMBOL == (241583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241584)
		#define UNIQUE_FUNCTION<%0...%1> %0uyk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241585)
		#define UNIQUE_FUNCTION<%0...%1> %0uyl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241586)
		#define UNIQUE_FUNCTION<%0...%1> %0uym%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241587)
		#define UNIQUE_FUNCTION<%0...%1> %0uyn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241588)
		#define UNIQUE_FUNCTION<%0...%1> %0uyo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241589)
		#define UNIQUE_FUNCTION<%0...%1> %0uyp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241590)
		#define UNIQUE_FUNCTION<%0...%1> %0uyq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241591)
		#define UNIQUE_FUNCTION<%0...%1> %0uyr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (241591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241592)
		#define UNIQUE_FUNCTION<%0...%1> %0uys%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241593)
		#define UNIQUE_FUNCTION<%0...%1> %0uyt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241594)
		#define UNIQUE_FUNCTION<%0...%1> %0uyu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241595)
		#define UNIQUE_FUNCTION<%0...%1> %0uyv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241596)
		#define UNIQUE_FUNCTION<%0...%1> %0uyw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241597)
		#define UNIQUE_FUNCTION<%0...%1> %0uyx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (241597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241598)
		#define UNIQUE_FUNCTION<%0...%1> %0uyy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (241599)
		#define UNIQUE_FUNCTION<%0...%1> %0uyz%1
		#endinput
	#endif
#endif
