static stock const Y_UNIQUE_048704_048767_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_048704_048767
	#undef _inc_y_unique_048704_048767
#endif

#if UNIQUE_SYMBOL < (48711)
	#if UNIQUE_SYMBOL == (48703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48704)
		#define UNIQUE_FUNCTION<%0...%1> %0At0%1
		#endinput
	#if UNIQUE_SYMBOL == (48704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48705)
		#define UNIQUE_FUNCTION<%0...%1> %0At1%1
		#endinput
	#if UNIQUE_SYMBOL == (48705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48706)
		#define UNIQUE_FUNCTION<%0...%1> %0At2%1
		#endinput
	#if UNIQUE_SYMBOL == (48706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48707)
		#define UNIQUE_FUNCTION<%0...%1> %0At3%1
		#endinput
	#if UNIQUE_SYMBOL == (48707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48708)
		#define UNIQUE_FUNCTION<%0...%1> %0At4%1
		#endinput
	#if UNIQUE_SYMBOL == (48708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48709)
		#define UNIQUE_FUNCTION<%0...%1> %0At5%1
		#endinput
	#if UNIQUE_SYMBOL == (48709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48710)
		#define UNIQUE_FUNCTION<%0...%1> %0At6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48711)
		#define UNIQUE_FUNCTION<%0...%1> %0At7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48719)
	#elseif UNIQUE_SYMBOL == (48711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48712)
		#define UNIQUE_FUNCTION<%0...%1> %0At8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48713)
		#define UNIQUE_FUNCTION<%0...%1> %0At9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48714)
		#define UNIQUE_FUNCTION<%0...%1> %0At@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48715)
		#define UNIQUE_FUNCTION<%0...%1> %0AtA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48716)
		#define UNIQUE_FUNCTION<%0...%1> %0AtB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48717)
		#define UNIQUE_FUNCTION<%0...%1> %0AtC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48718)
		#define UNIQUE_FUNCTION<%0...%1> %0AtD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48719)
		#define UNIQUE_FUNCTION<%0...%1> %0AtE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48727)
	#elseif UNIQUE_SYMBOL == (48719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48720)
		#define UNIQUE_FUNCTION<%0...%1> %0AtF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48721)
		#define UNIQUE_FUNCTION<%0...%1> %0AtG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48722)
		#define UNIQUE_FUNCTION<%0...%1> %0AtH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48723)
		#define UNIQUE_FUNCTION<%0...%1> %0AtI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48724)
		#define UNIQUE_FUNCTION<%0...%1> %0AtJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48725)
		#define UNIQUE_FUNCTION<%0...%1> %0AtK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48726)
		#define UNIQUE_FUNCTION<%0...%1> %0AtL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48727)
		#define UNIQUE_FUNCTION<%0...%1> %0AtM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48735)
	#elseif UNIQUE_SYMBOL == (48727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48728)
		#define UNIQUE_FUNCTION<%0...%1> %0AtN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48729)
		#define UNIQUE_FUNCTION<%0...%1> %0AtO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48730)
		#define UNIQUE_FUNCTION<%0...%1> %0AtP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48731)
		#define UNIQUE_FUNCTION<%0...%1> %0AtQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48732)
		#define UNIQUE_FUNCTION<%0...%1> %0AtR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48733)
		#define UNIQUE_FUNCTION<%0...%1> %0AtS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48734)
		#define UNIQUE_FUNCTION<%0...%1> %0AtT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48735)
		#define UNIQUE_FUNCTION<%0...%1> %0AtU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48743)
	#elseif UNIQUE_SYMBOL == (48735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48736)
		#define UNIQUE_FUNCTION<%0...%1> %0AtV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48737)
		#define UNIQUE_FUNCTION<%0...%1> %0AtW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48738)
		#define UNIQUE_FUNCTION<%0...%1> %0AtX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48739)
		#define UNIQUE_FUNCTION<%0...%1> %0AtY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48740)
		#define UNIQUE_FUNCTION<%0...%1> %0AtZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48741)
		#define UNIQUE_FUNCTION<%0...%1> %0At_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48742)
		#define UNIQUE_FUNCTION<%0...%1> %0Ata%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48743)
		#define UNIQUE_FUNCTION<%0...%1> %0Atb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48751)
	#elseif UNIQUE_SYMBOL == (48743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48744)
		#define UNIQUE_FUNCTION<%0...%1> %0Atc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48745)
		#define UNIQUE_FUNCTION<%0...%1> %0Atd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48746)
		#define UNIQUE_FUNCTION<%0...%1> %0Ate%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48747)
		#define UNIQUE_FUNCTION<%0...%1> %0Atf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48748)
		#define UNIQUE_FUNCTION<%0...%1> %0Atg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48749)
		#define UNIQUE_FUNCTION<%0...%1> %0Ath%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48750)
		#define UNIQUE_FUNCTION<%0...%1> %0Ati%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48751)
		#define UNIQUE_FUNCTION<%0...%1> %0Atj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (48759)
	#elseif UNIQUE_SYMBOL == (48751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48752)
		#define UNIQUE_FUNCTION<%0...%1> %0Atk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48753)
		#define UNIQUE_FUNCTION<%0...%1> %0Atl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48754)
		#define UNIQUE_FUNCTION<%0...%1> %0Atm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48755)
		#define UNIQUE_FUNCTION<%0...%1> %0Atn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48756)
		#define UNIQUE_FUNCTION<%0...%1> %0Ato%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48757)
		#define UNIQUE_FUNCTION<%0...%1> %0Atp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48758)
		#define UNIQUE_FUNCTION<%0...%1> %0Atq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48759)
		#define UNIQUE_FUNCTION<%0...%1> %0Atr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (48759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48760)
		#define UNIQUE_FUNCTION<%0...%1> %0Ats%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48761)
		#define UNIQUE_FUNCTION<%0...%1> %0Att%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48762)
		#define UNIQUE_FUNCTION<%0...%1> %0Atu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48763)
		#define UNIQUE_FUNCTION<%0...%1> %0Atv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48764)
		#define UNIQUE_FUNCTION<%0...%1> %0Atw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48765)
		#define UNIQUE_FUNCTION<%0...%1> %0Atx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (48765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48766)
		#define UNIQUE_FUNCTION<%0...%1> %0Aty%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (48767)
		#define UNIQUE_FUNCTION<%0...%1> %0Atz%1
		#endinput
	#endif
#endif
