static stock const Y_UNIQUE_054720_054783_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_054720_054783
	#undef _inc_y_unique_054720_054783
#endif

#if UNIQUE_SYMBOL < (54727)
	#if UNIQUE_SYMBOL == (54719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54720)
		#define UNIQUE_FUNCTION<%0...%1> %0CM0%1
		#endinput
	#if UNIQUE_SYMBOL == (54720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54721)
		#define UNIQUE_FUNCTION<%0...%1> %0CM1%1
		#endinput
	#if UNIQUE_SYMBOL == (54721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54722)
		#define UNIQUE_FUNCTION<%0...%1> %0CM2%1
		#endinput
	#if UNIQUE_SYMBOL == (54722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54723)
		#define UNIQUE_FUNCTION<%0...%1> %0CM3%1
		#endinput
	#if UNIQUE_SYMBOL == (54723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54724)
		#define UNIQUE_FUNCTION<%0...%1> %0CM4%1
		#endinput
	#if UNIQUE_SYMBOL == (54724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54725)
		#define UNIQUE_FUNCTION<%0...%1> %0CM5%1
		#endinput
	#if UNIQUE_SYMBOL == (54725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54726)
		#define UNIQUE_FUNCTION<%0...%1> %0CM6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54727)
		#define UNIQUE_FUNCTION<%0...%1> %0CM7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54735)
	#elseif UNIQUE_SYMBOL == (54727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54728)
		#define UNIQUE_FUNCTION<%0...%1> %0CM8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54729)
		#define UNIQUE_FUNCTION<%0...%1> %0CM9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54730)
		#define UNIQUE_FUNCTION<%0...%1> %0CM@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54731)
		#define UNIQUE_FUNCTION<%0...%1> %0CMA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54732)
		#define UNIQUE_FUNCTION<%0...%1> %0CMB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54733)
		#define UNIQUE_FUNCTION<%0...%1> %0CMC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54734)
		#define UNIQUE_FUNCTION<%0...%1> %0CMD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54735)
		#define UNIQUE_FUNCTION<%0...%1> %0CME%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54743)
	#elseif UNIQUE_SYMBOL == (54735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54736)
		#define UNIQUE_FUNCTION<%0...%1> %0CMF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54737)
		#define UNIQUE_FUNCTION<%0...%1> %0CMG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54738)
		#define UNIQUE_FUNCTION<%0...%1> %0CMH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54739)
		#define UNIQUE_FUNCTION<%0...%1> %0CMI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54740)
		#define UNIQUE_FUNCTION<%0...%1> %0CMJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54741)
		#define UNIQUE_FUNCTION<%0...%1> %0CMK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54742)
		#define UNIQUE_FUNCTION<%0...%1> %0CML%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54743)
		#define UNIQUE_FUNCTION<%0...%1> %0CMM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54751)
	#elseif UNIQUE_SYMBOL == (54743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54744)
		#define UNIQUE_FUNCTION<%0...%1> %0CMN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54745)
		#define UNIQUE_FUNCTION<%0...%1> %0CMO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54746)
		#define UNIQUE_FUNCTION<%0...%1> %0CMP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54747)
		#define UNIQUE_FUNCTION<%0...%1> %0CMQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54748)
		#define UNIQUE_FUNCTION<%0...%1> %0CMR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54749)
		#define UNIQUE_FUNCTION<%0...%1> %0CMS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54750)
		#define UNIQUE_FUNCTION<%0...%1> %0CMT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54751)
		#define UNIQUE_FUNCTION<%0...%1> %0CMU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54759)
	#elseif UNIQUE_SYMBOL == (54751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54752)
		#define UNIQUE_FUNCTION<%0...%1> %0CMV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54753)
		#define UNIQUE_FUNCTION<%0...%1> %0CMW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54754)
		#define UNIQUE_FUNCTION<%0...%1> %0CMX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54755)
		#define UNIQUE_FUNCTION<%0...%1> %0CMY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54756)
		#define UNIQUE_FUNCTION<%0...%1> %0CMZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54757)
		#define UNIQUE_FUNCTION<%0...%1> %0CM_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54758)
		#define UNIQUE_FUNCTION<%0...%1> %0CMa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54759)
		#define UNIQUE_FUNCTION<%0...%1> %0CMb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54767)
	#elseif UNIQUE_SYMBOL == (54759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54760)
		#define UNIQUE_FUNCTION<%0...%1> %0CMc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54761)
		#define UNIQUE_FUNCTION<%0...%1> %0CMd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54762)
		#define UNIQUE_FUNCTION<%0...%1> %0CMe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54763)
		#define UNIQUE_FUNCTION<%0...%1> %0CMf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54764)
		#define UNIQUE_FUNCTION<%0...%1> %0CMg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54765)
		#define UNIQUE_FUNCTION<%0...%1> %0CMh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54766)
		#define UNIQUE_FUNCTION<%0...%1> %0CMi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54767)
		#define UNIQUE_FUNCTION<%0...%1> %0CMj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54775)
	#elseif UNIQUE_SYMBOL == (54767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54768)
		#define UNIQUE_FUNCTION<%0...%1> %0CMk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54769)
		#define UNIQUE_FUNCTION<%0...%1> %0CMl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54770)
		#define UNIQUE_FUNCTION<%0...%1> %0CMm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54771)
		#define UNIQUE_FUNCTION<%0...%1> %0CMn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54772)
		#define UNIQUE_FUNCTION<%0...%1> %0CMo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54773)
		#define UNIQUE_FUNCTION<%0...%1> %0CMp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54774)
		#define UNIQUE_FUNCTION<%0...%1> %0CMq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54775)
		#define UNIQUE_FUNCTION<%0...%1> %0CMr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (54775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54776)
		#define UNIQUE_FUNCTION<%0...%1> %0CMs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54777)
		#define UNIQUE_FUNCTION<%0...%1> %0CMt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54778)
		#define UNIQUE_FUNCTION<%0...%1> %0CMu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54779)
		#define UNIQUE_FUNCTION<%0...%1> %0CMv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54780)
		#define UNIQUE_FUNCTION<%0...%1> %0CMw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54781)
		#define UNIQUE_FUNCTION<%0...%1> %0CMx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54782)
		#define UNIQUE_FUNCTION<%0...%1> %0CMy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54783)
		#define UNIQUE_FUNCTION<%0...%1> %0CMz%1
		#endinput
	#endif
#endif
