static stock const Y_UNIQUE_131776_131839_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_131776_131839
	#undef _inc_y_unique_131776_131839
#endif

#if UNIQUE_SYMBOL < (131783)
	#if UNIQUE_SYMBOL == (131775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131776)
		#define UNIQUE_FUNCTION<%0...%1> %0VA0%1
		#endinput
	#if UNIQUE_SYMBOL == (131776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131777)
		#define UNIQUE_FUNCTION<%0...%1> %0VA1%1
		#endinput
	#if UNIQUE_SYMBOL == (131777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131778)
		#define UNIQUE_FUNCTION<%0...%1> %0VA2%1
		#endinput
	#if UNIQUE_SYMBOL == (131778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131779)
		#define UNIQUE_FUNCTION<%0...%1> %0VA3%1
		#endinput
	#if UNIQUE_SYMBOL == (131779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131780)
		#define UNIQUE_FUNCTION<%0...%1> %0VA4%1
		#endinput
	#if UNIQUE_SYMBOL == (131780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131781)
		#define UNIQUE_FUNCTION<%0...%1> %0VA5%1
		#endinput
	#if UNIQUE_SYMBOL == (131781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131782)
		#define UNIQUE_FUNCTION<%0...%1> %0VA6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131783)
		#define UNIQUE_FUNCTION<%0...%1> %0VA7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (131791)
	#elseif UNIQUE_SYMBOL == (131783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131784)
		#define UNIQUE_FUNCTION<%0...%1> %0VA8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131785)
		#define UNIQUE_FUNCTION<%0...%1> %0VA9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131786)
		#define UNIQUE_FUNCTION<%0...%1> %0VA@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131787)
		#define UNIQUE_FUNCTION<%0...%1> %0VAA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131788)
		#define UNIQUE_FUNCTION<%0...%1> %0VAB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131789)
		#define UNIQUE_FUNCTION<%0...%1> %0VAC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131790)
		#define UNIQUE_FUNCTION<%0...%1> %0VAD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131791)
		#define UNIQUE_FUNCTION<%0...%1> %0VAE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (131799)
	#elseif UNIQUE_SYMBOL == (131791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131792)
		#define UNIQUE_FUNCTION<%0...%1> %0VAF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131793)
		#define UNIQUE_FUNCTION<%0...%1> %0VAG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131794)
		#define UNIQUE_FUNCTION<%0...%1> %0VAH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131795)
		#define UNIQUE_FUNCTION<%0...%1> %0VAI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131796)
		#define UNIQUE_FUNCTION<%0...%1> %0VAJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131797)
		#define UNIQUE_FUNCTION<%0...%1> %0VAK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131798)
		#define UNIQUE_FUNCTION<%0...%1> %0VAL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131799)
		#define UNIQUE_FUNCTION<%0...%1> %0VAM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (131807)
	#elseif UNIQUE_SYMBOL == (131799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131800)
		#define UNIQUE_FUNCTION<%0...%1> %0VAN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131801)
		#define UNIQUE_FUNCTION<%0...%1> %0VAO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131802)
		#define UNIQUE_FUNCTION<%0...%1> %0VAP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131803)
		#define UNIQUE_FUNCTION<%0...%1> %0VAQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131804)
		#define UNIQUE_FUNCTION<%0...%1> %0VAR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131805)
		#define UNIQUE_FUNCTION<%0...%1> %0VAS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131806)
		#define UNIQUE_FUNCTION<%0...%1> %0VAT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131807)
		#define UNIQUE_FUNCTION<%0...%1> %0VAU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (131815)
	#elseif UNIQUE_SYMBOL == (131807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131808)
		#define UNIQUE_FUNCTION<%0...%1> %0VAV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131809)
		#define UNIQUE_FUNCTION<%0...%1> %0VAW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131810)
		#define UNIQUE_FUNCTION<%0...%1> %0VAX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131811)
		#define UNIQUE_FUNCTION<%0...%1> %0VAY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131812)
		#define UNIQUE_FUNCTION<%0...%1> %0VAZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131813)
		#define UNIQUE_FUNCTION<%0...%1> %0VA_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131814)
		#define UNIQUE_FUNCTION<%0...%1> %0VAa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131815)
		#define UNIQUE_FUNCTION<%0...%1> %0VAb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (131823)
	#elseif UNIQUE_SYMBOL == (131815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131816)
		#define UNIQUE_FUNCTION<%0...%1> %0VAc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131817)
		#define UNIQUE_FUNCTION<%0...%1> %0VAd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131818)
		#define UNIQUE_FUNCTION<%0...%1> %0VAe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131819)
		#define UNIQUE_FUNCTION<%0...%1> %0VAf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131820)
		#define UNIQUE_FUNCTION<%0...%1> %0VAg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131821)
		#define UNIQUE_FUNCTION<%0...%1> %0VAh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131822)
		#define UNIQUE_FUNCTION<%0...%1> %0VAi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131823)
		#define UNIQUE_FUNCTION<%0...%1> %0VAj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (131831)
	#elseif UNIQUE_SYMBOL == (131823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131824)
		#define UNIQUE_FUNCTION<%0...%1> %0VAk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131825)
		#define UNIQUE_FUNCTION<%0...%1> %0VAl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131826)
		#define UNIQUE_FUNCTION<%0...%1> %0VAm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131827)
		#define UNIQUE_FUNCTION<%0...%1> %0VAn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131828)
		#define UNIQUE_FUNCTION<%0...%1> %0VAo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131829)
		#define UNIQUE_FUNCTION<%0...%1> %0VAp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131830)
		#define UNIQUE_FUNCTION<%0...%1> %0VAq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131831)
		#define UNIQUE_FUNCTION<%0...%1> %0VAr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (131831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131832)
		#define UNIQUE_FUNCTION<%0...%1> %0VAs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131833)
		#define UNIQUE_FUNCTION<%0...%1> %0VAt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131834)
		#define UNIQUE_FUNCTION<%0...%1> %0VAu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131835)
		#define UNIQUE_FUNCTION<%0...%1> %0VAv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131836)
		#define UNIQUE_FUNCTION<%0...%1> %0VAw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131837)
		#define UNIQUE_FUNCTION<%0...%1> %0VAx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (131837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131838)
		#define UNIQUE_FUNCTION<%0...%1> %0VAy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (131839)
		#define UNIQUE_FUNCTION<%0...%1> %0VAz%1
		#endinput
	#endif
#endif
