static stock const Y_UNIQUE_003328_003391_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_003328_003391
	#undef _inc_y_unique_003328_003391
#endif

#if UNIQUE_SYMBOL < (3335)
	#if UNIQUE_SYMBOL == (3327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3328)
		#define UNIQUE_FUNCTION<%0...%1> %00o0%1
		#endinput
	#if UNIQUE_SYMBOL == (3328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3329)
		#define UNIQUE_FUNCTION<%0...%1> %00o1%1
		#endinput
	#if UNIQUE_SYMBOL == (3329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3330)
		#define UNIQUE_FUNCTION<%0...%1> %00o2%1
		#endinput
	#if UNIQUE_SYMBOL == (3330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3331)
		#define UNIQUE_FUNCTION<%0...%1> %00o3%1
		#endinput
	#if UNIQUE_SYMBOL == (3331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3332)
		#define UNIQUE_FUNCTION<%0...%1> %00o4%1
		#endinput
	#if UNIQUE_SYMBOL == (3332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3333)
		#define UNIQUE_FUNCTION<%0...%1> %00o5%1
		#endinput
	#if UNIQUE_SYMBOL == (3333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3334)
		#define UNIQUE_FUNCTION<%0...%1> %00o6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3335)
		#define UNIQUE_FUNCTION<%0...%1> %00o7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3343)
	#elseif UNIQUE_SYMBOL == (3335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3336)
		#define UNIQUE_FUNCTION<%0...%1> %00o8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3337)
		#define UNIQUE_FUNCTION<%0...%1> %00o9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3338)
		#define UNIQUE_FUNCTION<%0...%1> %00o@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3339)
		#define UNIQUE_FUNCTION<%0...%1> %00oA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3340)
		#define UNIQUE_FUNCTION<%0...%1> %00oB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3341)
		#define UNIQUE_FUNCTION<%0...%1> %00oC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3342)
		#define UNIQUE_FUNCTION<%0...%1> %00oD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3343)
		#define UNIQUE_FUNCTION<%0...%1> %00oE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3351)
	#elseif UNIQUE_SYMBOL == (3343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3344)
		#define UNIQUE_FUNCTION<%0...%1> %00oF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3345)
		#define UNIQUE_FUNCTION<%0...%1> %00oG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3346)
		#define UNIQUE_FUNCTION<%0...%1> %00oH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3347)
		#define UNIQUE_FUNCTION<%0...%1> %00oI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3348)
		#define UNIQUE_FUNCTION<%0...%1> %00oJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3349)
		#define UNIQUE_FUNCTION<%0...%1> %00oK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3350)
		#define UNIQUE_FUNCTION<%0...%1> %00oL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3351)
		#define UNIQUE_FUNCTION<%0...%1> %00oM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3359)
	#elseif UNIQUE_SYMBOL == (3351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3352)
		#define UNIQUE_FUNCTION<%0...%1> %00oN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3353)
		#define UNIQUE_FUNCTION<%0...%1> %00oO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3354)
		#define UNIQUE_FUNCTION<%0...%1> %00oP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3355)
		#define UNIQUE_FUNCTION<%0...%1> %00oQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3356)
		#define UNIQUE_FUNCTION<%0...%1> %00oR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3357)
		#define UNIQUE_FUNCTION<%0...%1> %00oS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3358)
		#define UNIQUE_FUNCTION<%0...%1> %00oT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3359)
		#define UNIQUE_FUNCTION<%0...%1> %00oU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3367)
	#elseif UNIQUE_SYMBOL == (3359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3360)
		#define UNIQUE_FUNCTION<%0...%1> %00oV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3361)
		#define UNIQUE_FUNCTION<%0...%1> %00oW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3362)
		#define UNIQUE_FUNCTION<%0...%1> %00oX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3363)
		#define UNIQUE_FUNCTION<%0...%1> %00oY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3364)
		#define UNIQUE_FUNCTION<%0...%1> %00oZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3365)
		#define UNIQUE_FUNCTION<%0...%1> %00o_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3366)
		#define UNIQUE_FUNCTION<%0...%1> %00oa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3367)
		#define UNIQUE_FUNCTION<%0...%1> %00ob%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3375)
	#elseif UNIQUE_SYMBOL == (3367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3368)
		#define UNIQUE_FUNCTION<%0...%1> %00oc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3369)
		#define UNIQUE_FUNCTION<%0...%1> %00od%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3370)
		#define UNIQUE_FUNCTION<%0...%1> %00oe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3371)
		#define UNIQUE_FUNCTION<%0...%1> %00of%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3372)
		#define UNIQUE_FUNCTION<%0...%1> %00og%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3373)
		#define UNIQUE_FUNCTION<%0...%1> %00oh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3374)
		#define UNIQUE_FUNCTION<%0...%1> %00oi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3375)
		#define UNIQUE_FUNCTION<%0...%1> %00oj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3383)
	#elseif UNIQUE_SYMBOL == (3375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3376)
		#define UNIQUE_FUNCTION<%0...%1> %00ok%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3377)
		#define UNIQUE_FUNCTION<%0...%1> %00ol%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3378)
		#define UNIQUE_FUNCTION<%0...%1> %00om%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3379)
		#define UNIQUE_FUNCTION<%0...%1> %00on%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3380)
		#define UNIQUE_FUNCTION<%0...%1> %00oo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3381)
		#define UNIQUE_FUNCTION<%0...%1> %00op%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3382)
		#define UNIQUE_FUNCTION<%0...%1> %00oq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3383)
		#define UNIQUE_FUNCTION<%0...%1> %00or%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (3383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3384)
		#define UNIQUE_FUNCTION<%0...%1> %00os%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3385)
		#define UNIQUE_FUNCTION<%0...%1> %00ot%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3386)
		#define UNIQUE_FUNCTION<%0...%1> %00ou%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3387)
		#define UNIQUE_FUNCTION<%0...%1> %00ov%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3388)
		#define UNIQUE_FUNCTION<%0...%1> %00ow%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3389)
		#define UNIQUE_FUNCTION<%0...%1> %00ox%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3390)
		#define UNIQUE_FUNCTION<%0...%1> %00oy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3391)
		#define UNIQUE_FUNCTION<%0...%1> %00oz%1
		#endinput
	#endif
#endif
