static stock const Y_UNIQUE_088768_088831_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_088768_088831
	#undef _inc_y_unique_088768_088831
#endif

#if UNIQUE_SYMBOL < (88775)
	#if UNIQUE_SYMBOL == (88767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88768)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf0%1
		#endinput
	#if UNIQUE_SYMBOL == (88768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88769)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf1%1
		#endinput
	#if UNIQUE_SYMBOL == (88769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88770)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf2%1
		#endinput
	#if UNIQUE_SYMBOL == (88770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88771)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf3%1
		#endinput
	#if UNIQUE_SYMBOL == (88771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88772)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf4%1
		#endinput
	#if UNIQUE_SYMBOL == (88772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88773)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf5%1
		#endinput
	#if UNIQUE_SYMBOL == (88773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88774)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88775)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (88783)
	#elseif UNIQUE_SYMBOL == (88775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88776)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88777)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88778)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88779)
		#define UNIQUE_FUNCTION<%0...%1> %0KfA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88780)
		#define UNIQUE_FUNCTION<%0...%1> %0KfB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88781)
		#define UNIQUE_FUNCTION<%0...%1> %0KfC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88782)
		#define UNIQUE_FUNCTION<%0...%1> %0KfD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88783)
		#define UNIQUE_FUNCTION<%0...%1> %0KfE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (88791)
	#elseif UNIQUE_SYMBOL == (88783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88784)
		#define UNIQUE_FUNCTION<%0...%1> %0KfF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88785)
		#define UNIQUE_FUNCTION<%0...%1> %0KfG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88786)
		#define UNIQUE_FUNCTION<%0...%1> %0KfH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88787)
		#define UNIQUE_FUNCTION<%0...%1> %0KfI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88788)
		#define UNIQUE_FUNCTION<%0...%1> %0KfJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88789)
		#define UNIQUE_FUNCTION<%0...%1> %0KfK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88790)
		#define UNIQUE_FUNCTION<%0...%1> %0KfL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88791)
		#define UNIQUE_FUNCTION<%0...%1> %0KfM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (88799)
	#elseif UNIQUE_SYMBOL == (88791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88792)
		#define UNIQUE_FUNCTION<%0...%1> %0KfN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88793)
		#define UNIQUE_FUNCTION<%0...%1> %0KfO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88794)
		#define UNIQUE_FUNCTION<%0...%1> %0KfP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88795)
		#define UNIQUE_FUNCTION<%0...%1> %0KfQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88796)
		#define UNIQUE_FUNCTION<%0...%1> %0KfR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88797)
		#define UNIQUE_FUNCTION<%0...%1> %0KfS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88798)
		#define UNIQUE_FUNCTION<%0...%1> %0KfT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88799)
		#define UNIQUE_FUNCTION<%0...%1> %0KfU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (88807)
	#elseif UNIQUE_SYMBOL == (88799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88800)
		#define UNIQUE_FUNCTION<%0...%1> %0KfV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88801)
		#define UNIQUE_FUNCTION<%0...%1> %0KfW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88802)
		#define UNIQUE_FUNCTION<%0...%1> %0KfX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88803)
		#define UNIQUE_FUNCTION<%0...%1> %0KfY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88804)
		#define UNIQUE_FUNCTION<%0...%1> %0KfZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88805)
		#define UNIQUE_FUNCTION<%0...%1> %0Kf_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88806)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88807)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (88815)
	#elseif UNIQUE_SYMBOL == (88807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88808)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88809)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88810)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88811)
		#define UNIQUE_FUNCTION<%0...%1> %0Kff%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88812)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88813)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88814)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88815)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (88823)
	#elseif UNIQUE_SYMBOL == (88815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88816)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88817)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88818)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88819)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88820)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88821)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88822)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88823)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (88823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88824)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88825)
		#define UNIQUE_FUNCTION<%0...%1> %0Kft%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88826)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88827)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88828)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88829)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (88829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88830)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (88831)
		#define UNIQUE_FUNCTION<%0...%1> %0Kfz%1
		#endinput
	#endif
#endif
