static stock const Y_UNIQUE_123328_123391_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_123328_123391
	#undef _inc_y_unique_123328_123391
#endif

#if UNIQUE_SYMBOL < (123335)
	#if UNIQUE_SYMBOL == (123327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123328)
		#define UNIQUE_FUNCTION<%0...%1> %0T70%1
		#endinput
	#if UNIQUE_SYMBOL == (123328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123329)
		#define UNIQUE_FUNCTION<%0...%1> %0T71%1
		#endinput
	#if UNIQUE_SYMBOL == (123329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123330)
		#define UNIQUE_FUNCTION<%0...%1> %0T72%1
		#endinput
	#if UNIQUE_SYMBOL == (123330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123331)
		#define UNIQUE_FUNCTION<%0...%1> %0T73%1
		#endinput
	#if UNIQUE_SYMBOL == (123331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123332)
		#define UNIQUE_FUNCTION<%0...%1> %0T74%1
		#endinput
	#if UNIQUE_SYMBOL == (123332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123333)
		#define UNIQUE_FUNCTION<%0...%1> %0T75%1
		#endinput
	#if UNIQUE_SYMBOL == (123333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123334)
		#define UNIQUE_FUNCTION<%0...%1> %0T76%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123335)
		#define UNIQUE_FUNCTION<%0...%1> %0T77%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123343)
	#elseif UNIQUE_SYMBOL == (123335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123336)
		#define UNIQUE_FUNCTION<%0...%1> %0T78%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123337)
		#define UNIQUE_FUNCTION<%0...%1> %0T79%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123338)
		#define UNIQUE_FUNCTION<%0...%1> %0T7@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123339)
		#define UNIQUE_FUNCTION<%0...%1> %0T7A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123340)
		#define UNIQUE_FUNCTION<%0...%1> %0T7B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123341)
		#define UNIQUE_FUNCTION<%0...%1> %0T7C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123342)
		#define UNIQUE_FUNCTION<%0...%1> %0T7D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123343)
		#define UNIQUE_FUNCTION<%0...%1> %0T7E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123351)
	#elseif UNIQUE_SYMBOL == (123343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123344)
		#define UNIQUE_FUNCTION<%0...%1> %0T7F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123345)
		#define UNIQUE_FUNCTION<%0...%1> %0T7G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123346)
		#define UNIQUE_FUNCTION<%0...%1> %0T7H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123347)
		#define UNIQUE_FUNCTION<%0...%1> %0T7I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123348)
		#define UNIQUE_FUNCTION<%0...%1> %0T7J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123349)
		#define UNIQUE_FUNCTION<%0...%1> %0T7K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123350)
		#define UNIQUE_FUNCTION<%0...%1> %0T7L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123351)
		#define UNIQUE_FUNCTION<%0...%1> %0T7M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123359)
	#elseif UNIQUE_SYMBOL == (123351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123352)
		#define UNIQUE_FUNCTION<%0...%1> %0T7N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123353)
		#define UNIQUE_FUNCTION<%0...%1> %0T7O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123354)
		#define UNIQUE_FUNCTION<%0...%1> %0T7P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123355)
		#define UNIQUE_FUNCTION<%0...%1> %0T7Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123356)
		#define UNIQUE_FUNCTION<%0...%1> %0T7R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123357)
		#define UNIQUE_FUNCTION<%0...%1> %0T7S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123358)
		#define UNIQUE_FUNCTION<%0...%1> %0T7T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123359)
		#define UNIQUE_FUNCTION<%0...%1> %0T7U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123367)
	#elseif UNIQUE_SYMBOL == (123359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123360)
		#define UNIQUE_FUNCTION<%0...%1> %0T7V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123361)
		#define UNIQUE_FUNCTION<%0...%1> %0T7W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123362)
		#define UNIQUE_FUNCTION<%0...%1> %0T7X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123363)
		#define UNIQUE_FUNCTION<%0...%1> %0T7Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123364)
		#define UNIQUE_FUNCTION<%0...%1> %0T7Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123365)
		#define UNIQUE_FUNCTION<%0...%1> %0T7_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123366)
		#define UNIQUE_FUNCTION<%0...%1> %0T7a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123367)
		#define UNIQUE_FUNCTION<%0...%1> %0T7b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123375)
	#elseif UNIQUE_SYMBOL == (123367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123368)
		#define UNIQUE_FUNCTION<%0...%1> %0T7c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123369)
		#define UNIQUE_FUNCTION<%0...%1> %0T7d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123370)
		#define UNIQUE_FUNCTION<%0...%1> %0T7e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123371)
		#define UNIQUE_FUNCTION<%0...%1> %0T7f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123372)
		#define UNIQUE_FUNCTION<%0...%1> %0T7g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123373)
		#define UNIQUE_FUNCTION<%0...%1> %0T7h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123374)
		#define UNIQUE_FUNCTION<%0...%1> %0T7i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123375)
		#define UNIQUE_FUNCTION<%0...%1> %0T7j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123383)
	#elseif UNIQUE_SYMBOL == (123375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123376)
		#define UNIQUE_FUNCTION<%0...%1> %0T7k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123377)
		#define UNIQUE_FUNCTION<%0...%1> %0T7l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123378)
		#define UNIQUE_FUNCTION<%0...%1> %0T7m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123379)
		#define UNIQUE_FUNCTION<%0...%1> %0T7n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123380)
		#define UNIQUE_FUNCTION<%0...%1> %0T7o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123381)
		#define UNIQUE_FUNCTION<%0...%1> %0T7p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123382)
		#define UNIQUE_FUNCTION<%0...%1> %0T7q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123383)
		#define UNIQUE_FUNCTION<%0...%1> %0T7r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (123383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123384)
		#define UNIQUE_FUNCTION<%0...%1> %0T7s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123385)
		#define UNIQUE_FUNCTION<%0...%1> %0T7t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123386)
		#define UNIQUE_FUNCTION<%0...%1> %0T7u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123387)
		#define UNIQUE_FUNCTION<%0...%1> %0T7v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123388)
		#define UNIQUE_FUNCTION<%0...%1> %0T7w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123389)
		#define UNIQUE_FUNCTION<%0...%1> %0T7x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123390)
		#define UNIQUE_FUNCTION<%0...%1> %0T7y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123391)
		#define UNIQUE_FUNCTION<%0...%1> %0T7z%1
		#endinput
	#endif
#endif
