static stock const Y_UNIQUE_191808_191871_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_191808_191871
	#undef _inc_y_unique_191808_191871
#endif

#if UNIQUE_SYMBOL < (191815)
	#if UNIQUE_SYMBOL == (191807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191808)
		#define UNIQUE_FUNCTION<%0...%1> %0ip0%1
		#endinput
	#if UNIQUE_SYMBOL == (191808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191809)
		#define UNIQUE_FUNCTION<%0...%1> %0ip1%1
		#endinput
	#if UNIQUE_SYMBOL == (191809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191810)
		#define UNIQUE_FUNCTION<%0...%1> %0ip2%1
		#endinput
	#if UNIQUE_SYMBOL == (191810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191811)
		#define UNIQUE_FUNCTION<%0...%1> %0ip3%1
		#endinput
	#if UNIQUE_SYMBOL == (191811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191812)
		#define UNIQUE_FUNCTION<%0...%1> %0ip4%1
		#endinput
	#if UNIQUE_SYMBOL == (191812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191813)
		#define UNIQUE_FUNCTION<%0...%1> %0ip5%1
		#endinput
	#if UNIQUE_SYMBOL == (191813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191814)
		#define UNIQUE_FUNCTION<%0...%1> %0ip6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191815)
		#define UNIQUE_FUNCTION<%0...%1> %0ip7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (191823)
	#elseif UNIQUE_SYMBOL == (191815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191816)
		#define UNIQUE_FUNCTION<%0...%1> %0ip8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191817)
		#define UNIQUE_FUNCTION<%0...%1> %0ip9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191818)
		#define UNIQUE_FUNCTION<%0...%1> %0ip@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191819)
		#define UNIQUE_FUNCTION<%0...%1> %0ipA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191820)
		#define UNIQUE_FUNCTION<%0...%1> %0ipB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191821)
		#define UNIQUE_FUNCTION<%0...%1> %0ipC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191822)
		#define UNIQUE_FUNCTION<%0...%1> %0ipD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191823)
		#define UNIQUE_FUNCTION<%0...%1> %0ipE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (191831)
	#elseif UNIQUE_SYMBOL == (191823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191824)
		#define UNIQUE_FUNCTION<%0...%1> %0ipF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191825)
		#define UNIQUE_FUNCTION<%0...%1> %0ipG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191826)
		#define UNIQUE_FUNCTION<%0...%1> %0ipH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191827)
		#define UNIQUE_FUNCTION<%0...%1> %0ipI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191828)
		#define UNIQUE_FUNCTION<%0...%1> %0ipJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191829)
		#define UNIQUE_FUNCTION<%0...%1> %0ipK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191830)
		#define UNIQUE_FUNCTION<%0...%1> %0ipL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191831)
		#define UNIQUE_FUNCTION<%0...%1> %0ipM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (191839)
	#elseif UNIQUE_SYMBOL == (191831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191832)
		#define UNIQUE_FUNCTION<%0...%1> %0ipN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191833)
		#define UNIQUE_FUNCTION<%0...%1> %0ipO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191834)
		#define UNIQUE_FUNCTION<%0...%1> %0ipP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191835)
		#define UNIQUE_FUNCTION<%0...%1> %0ipQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191836)
		#define UNIQUE_FUNCTION<%0...%1> %0ipR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191837)
		#define UNIQUE_FUNCTION<%0...%1> %0ipS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191838)
		#define UNIQUE_FUNCTION<%0...%1> %0ipT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191839)
		#define UNIQUE_FUNCTION<%0...%1> %0ipU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (191847)
	#elseif UNIQUE_SYMBOL == (191839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191840)
		#define UNIQUE_FUNCTION<%0...%1> %0ipV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191841)
		#define UNIQUE_FUNCTION<%0...%1> %0ipW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191842)
		#define UNIQUE_FUNCTION<%0...%1> %0ipX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191843)
		#define UNIQUE_FUNCTION<%0...%1> %0ipY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191844)
		#define UNIQUE_FUNCTION<%0...%1> %0ipZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191845)
		#define UNIQUE_FUNCTION<%0...%1> %0ip_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191846)
		#define UNIQUE_FUNCTION<%0...%1> %0ipa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191847)
		#define UNIQUE_FUNCTION<%0...%1> %0ipb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (191855)
	#elseif UNIQUE_SYMBOL == (191847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191848)
		#define UNIQUE_FUNCTION<%0...%1> %0ipc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191849)
		#define UNIQUE_FUNCTION<%0...%1> %0ipd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191850)
		#define UNIQUE_FUNCTION<%0...%1> %0ipe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191851)
		#define UNIQUE_FUNCTION<%0...%1> %0ipf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191852)
		#define UNIQUE_FUNCTION<%0...%1> %0ipg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191853)
		#define UNIQUE_FUNCTION<%0...%1> %0iph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191854)
		#define UNIQUE_FUNCTION<%0...%1> %0ipi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191855)
		#define UNIQUE_FUNCTION<%0...%1> %0ipj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (191863)
	#elseif UNIQUE_SYMBOL == (191855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191856)
		#define UNIQUE_FUNCTION<%0...%1> %0ipk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191857)
		#define UNIQUE_FUNCTION<%0...%1> %0ipl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191858)
		#define UNIQUE_FUNCTION<%0...%1> %0ipm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191859)
		#define UNIQUE_FUNCTION<%0...%1> %0ipn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191860)
		#define UNIQUE_FUNCTION<%0...%1> %0ipo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191861)
		#define UNIQUE_FUNCTION<%0...%1> %0ipp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191862)
		#define UNIQUE_FUNCTION<%0...%1> %0ipq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191863)
		#define UNIQUE_FUNCTION<%0...%1> %0ipr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (191863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191864)
		#define UNIQUE_FUNCTION<%0...%1> %0ips%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191865)
		#define UNIQUE_FUNCTION<%0...%1> %0ipt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191866)
		#define UNIQUE_FUNCTION<%0...%1> %0ipu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191867)
		#define UNIQUE_FUNCTION<%0...%1> %0ipv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191868)
		#define UNIQUE_FUNCTION<%0...%1> %0ipw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191869)
		#define UNIQUE_FUNCTION<%0...%1> %0ipx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (191869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191870)
		#define UNIQUE_FUNCTION<%0...%1> %0ipy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (191871)
		#define UNIQUE_FUNCTION<%0...%1> %0ipz%1
		#endinput
	#endif
#endif
