static stock const Y_UNIQUE_080576_080639_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_080576_080639
	#undef _inc_y_unique_080576_080639
#endif

#if UNIQUE_SYMBOL < (80583)
	#if UNIQUE_SYMBOL == (80575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80576)
		#define UNIQUE_FUNCTION<%0...%1> %0If0%1
		#endinput
	#if UNIQUE_SYMBOL == (80576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80577)
		#define UNIQUE_FUNCTION<%0...%1> %0If1%1
		#endinput
	#if UNIQUE_SYMBOL == (80577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80578)
		#define UNIQUE_FUNCTION<%0...%1> %0If2%1
		#endinput
	#if UNIQUE_SYMBOL == (80578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80579)
		#define UNIQUE_FUNCTION<%0...%1> %0If3%1
		#endinput
	#if UNIQUE_SYMBOL == (80579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80580)
		#define UNIQUE_FUNCTION<%0...%1> %0If4%1
		#endinput
	#if UNIQUE_SYMBOL == (80580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80581)
		#define UNIQUE_FUNCTION<%0...%1> %0If5%1
		#endinput
	#if UNIQUE_SYMBOL == (80581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80582)
		#define UNIQUE_FUNCTION<%0...%1> %0If6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80583)
		#define UNIQUE_FUNCTION<%0...%1> %0If7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80591)
	#elseif UNIQUE_SYMBOL == (80583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80584)
		#define UNIQUE_FUNCTION<%0...%1> %0If8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80585)
		#define UNIQUE_FUNCTION<%0...%1> %0If9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80586)
		#define UNIQUE_FUNCTION<%0...%1> %0If@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80587)
		#define UNIQUE_FUNCTION<%0...%1> %0IfA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80588)
		#define UNIQUE_FUNCTION<%0...%1> %0IfB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80589)
		#define UNIQUE_FUNCTION<%0...%1> %0IfC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80590)
		#define UNIQUE_FUNCTION<%0...%1> %0IfD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80591)
		#define UNIQUE_FUNCTION<%0...%1> %0IfE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80599)
	#elseif UNIQUE_SYMBOL == (80591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80592)
		#define UNIQUE_FUNCTION<%0...%1> %0IfF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80593)
		#define UNIQUE_FUNCTION<%0...%1> %0IfG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80594)
		#define UNIQUE_FUNCTION<%0...%1> %0IfH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80595)
		#define UNIQUE_FUNCTION<%0...%1> %0IfI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80596)
		#define UNIQUE_FUNCTION<%0...%1> %0IfJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80597)
		#define UNIQUE_FUNCTION<%0...%1> %0IfK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80598)
		#define UNIQUE_FUNCTION<%0...%1> %0IfL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80599)
		#define UNIQUE_FUNCTION<%0...%1> %0IfM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80607)
	#elseif UNIQUE_SYMBOL == (80599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80600)
		#define UNIQUE_FUNCTION<%0...%1> %0IfN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80601)
		#define UNIQUE_FUNCTION<%0...%1> %0IfO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80602)
		#define UNIQUE_FUNCTION<%0...%1> %0IfP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80603)
		#define UNIQUE_FUNCTION<%0...%1> %0IfQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80604)
		#define UNIQUE_FUNCTION<%0...%1> %0IfR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80605)
		#define UNIQUE_FUNCTION<%0...%1> %0IfS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80606)
		#define UNIQUE_FUNCTION<%0...%1> %0IfT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80607)
		#define UNIQUE_FUNCTION<%0...%1> %0IfU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80615)
	#elseif UNIQUE_SYMBOL == (80607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80608)
		#define UNIQUE_FUNCTION<%0...%1> %0IfV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80609)
		#define UNIQUE_FUNCTION<%0...%1> %0IfW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80610)
		#define UNIQUE_FUNCTION<%0...%1> %0IfX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80611)
		#define UNIQUE_FUNCTION<%0...%1> %0IfY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80612)
		#define UNIQUE_FUNCTION<%0...%1> %0IfZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80613)
		#define UNIQUE_FUNCTION<%0...%1> %0If_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80614)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80615)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80623)
	#elseif UNIQUE_SYMBOL == (80615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80616)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80617)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80618)
		#define UNIQUE_FUNCTION<%0...%1> %0Ife%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80619)
		#define UNIQUE_FUNCTION<%0...%1> %0Iff%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80620)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80621)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80622)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80623)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80631)
	#elseif UNIQUE_SYMBOL == (80623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80624)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80625)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80626)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80627)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80628)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80629)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80630)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80631)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (80631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80632)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80633)
		#define UNIQUE_FUNCTION<%0...%1> %0Ift%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80634)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80635)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80636)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80637)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80638)
		#define UNIQUE_FUNCTION<%0...%1> %0Ify%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80639)
		#define UNIQUE_FUNCTION<%0...%1> %0Ifz%1
		#endinput
	#endif
#endif
