static stock const Y_UNIQUE_091712_091775_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_091712_091775
	#undef _inc_y_unique_091712_091775
#endif

#if UNIQUE_SYMBOL < (91719)
	#if UNIQUE_SYMBOL == (91711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91712)
		#define UNIQUE_FUNCTION<%0...%1> %0LO0%1
		#endinput
	#if UNIQUE_SYMBOL == (91712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91713)
		#define UNIQUE_FUNCTION<%0...%1> %0LO1%1
		#endinput
	#if UNIQUE_SYMBOL == (91713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91714)
		#define UNIQUE_FUNCTION<%0...%1> %0LO2%1
		#endinput
	#if UNIQUE_SYMBOL == (91714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91715)
		#define UNIQUE_FUNCTION<%0...%1> %0LO3%1
		#endinput
	#if UNIQUE_SYMBOL == (91715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91716)
		#define UNIQUE_FUNCTION<%0...%1> %0LO4%1
		#endinput
	#if UNIQUE_SYMBOL == (91716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91717)
		#define UNIQUE_FUNCTION<%0...%1> %0LO5%1
		#endinput
	#if UNIQUE_SYMBOL == (91717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91718)
		#define UNIQUE_FUNCTION<%0...%1> %0LO6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91719)
		#define UNIQUE_FUNCTION<%0...%1> %0LO7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (91727)
	#elseif UNIQUE_SYMBOL == (91719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91720)
		#define UNIQUE_FUNCTION<%0...%1> %0LO8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91721)
		#define UNIQUE_FUNCTION<%0...%1> %0LO9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91722)
		#define UNIQUE_FUNCTION<%0...%1> %0LO@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91723)
		#define UNIQUE_FUNCTION<%0...%1> %0LOA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91724)
		#define UNIQUE_FUNCTION<%0...%1> %0LOB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91725)
		#define UNIQUE_FUNCTION<%0...%1> %0LOC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91726)
		#define UNIQUE_FUNCTION<%0...%1> %0LOD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91727)
		#define UNIQUE_FUNCTION<%0...%1> %0LOE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (91735)
	#elseif UNIQUE_SYMBOL == (91727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91728)
		#define UNIQUE_FUNCTION<%0...%1> %0LOF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91729)
		#define UNIQUE_FUNCTION<%0...%1> %0LOG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91730)
		#define UNIQUE_FUNCTION<%0...%1> %0LOH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91731)
		#define UNIQUE_FUNCTION<%0...%1> %0LOI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91732)
		#define UNIQUE_FUNCTION<%0...%1> %0LOJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91733)
		#define UNIQUE_FUNCTION<%0...%1> %0LOK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91734)
		#define UNIQUE_FUNCTION<%0...%1> %0LOL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91735)
		#define UNIQUE_FUNCTION<%0...%1> %0LOM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (91743)
	#elseif UNIQUE_SYMBOL == (91735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91736)
		#define UNIQUE_FUNCTION<%0...%1> %0LON%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91737)
		#define UNIQUE_FUNCTION<%0...%1> %0LOO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91738)
		#define UNIQUE_FUNCTION<%0...%1> %0LOP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91739)
		#define UNIQUE_FUNCTION<%0...%1> %0LOQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91740)
		#define UNIQUE_FUNCTION<%0...%1> %0LOR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91741)
		#define UNIQUE_FUNCTION<%0...%1> %0LOS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91742)
		#define UNIQUE_FUNCTION<%0...%1> %0LOT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91743)
		#define UNIQUE_FUNCTION<%0...%1> %0LOU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (91751)
	#elseif UNIQUE_SYMBOL == (91743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91744)
		#define UNIQUE_FUNCTION<%0...%1> %0LOV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91745)
		#define UNIQUE_FUNCTION<%0...%1> %0LOW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91746)
		#define UNIQUE_FUNCTION<%0...%1> %0LOX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91747)
		#define UNIQUE_FUNCTION<%0...%1> %0LOY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91748)
		#define UNIQUE_FUNCTION<%0...%1> %0LOZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91749)
		#define UNIQUE_FUNCTION<%0...%1> %0LO_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91750)
		#define UNIQUE_FUNCTION<%0...%1> %0LOa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91751)
		#define UNIQUE_FUNCTION<%0...%1> %0LOb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (91759)
	#elseif UNIQUE_SYMBOL == (91751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91752)
		#define UNIQUE_FUNCTION<%0...%1> %0LOc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91753)
		#define UNIQUE_FUNCTION<%0...%1> %0LOd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91754)
		#define UNIQUE_FUNCTION<%0...%1> %0LOe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91755)
		#define UNIQUE_FUNCTION<%0...%1> %0LOf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91756)
		#define UNIQUE_FUNCTION<%0...%1> %0LOg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91757)
		#define UNIQUE_FUNCTION<%0...%1> %0LOh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91758)
		#define UNIQUE_FUNCTION<%0...%1> %0LOi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91759)
		#define UNIQUE_FUNCTION<%0...%1> %0LOj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (91767)
	#elseif UNIQUE_SYMBOL == (91759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91760)
		#define UNIQUE_FUNCTION<%0...%1> %0LOk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91761)
		#define UNIQUE_FUNCTION<%0...%1> %0LOl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91762)
		#define UNIQUE_FUNCTION<%0...%1> %0LOm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91763)
		#define UNIQUE_FUNCTION<%0...%1> %0LOn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91764)
		#define UNIQUE_FUNCTION<%0...%1> %0LOo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91765)
		#define UNIQUE_FUNCTION<%0...%1> %0LOp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91766)
		#define UNIQUE_FUNCTION<%0...%1> %0LOq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91767)
		#define UNIQUE_FUNCTION<%0...%1> %0LOr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (91767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91768)
		#define UNIQUE_FUNCTION<%0...%1> %0LOs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91769)
		#define UNIQUE_FUNCTION<%0...%1> %0LOt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91770)
		#define UNIQUE_FUNCTION<%0...%1> %0LOu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91771)
		#define UNIQUE_FUNCTION<%0...%1> %0LOv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91772)
		#define UNIQUE_FUNCTION<%0...%1> %0LOw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91773)
		#define UNIQUE_FUNCTION<%0...%1> %0LOx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (91773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91774)
		#define UNIQUE_FUNCTION<%0...%1> %0LOy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (91775)
		#define UNIQUE_FUNCTION<%0...%1> %0LOz%1
		#endinput
	#endif
#endif
