static stock const Y_UNIQUE_188480_188543_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_188480_188543
	#undef _inc_y_unique_188480_188543
#endif

#if UNIQUE_SYMBOL < (188487)
	#if UNIQUE_SYMBOL == (188479)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188480)
		#define UNIQUE_FUNCTION<%0...%1> %0i10%1
		#endinput
	#if UNIQUE_SYMBOL == (188480)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188481)
		#define UNIQUE_FUNCTION<%0...%1> %0i11%1
		#endinput
	#if UNIQUE_SYMBOL == (188481)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188482)
		#define UNIQUE_FUNCTION<%0...%1> %0i12%1
		#endinput
	#if UNIQUE_SYMBOL == (188482)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188483)
		#define UNIQUE_FUNCTION<%0...%1> %0i13%1
		#endinput
	#if UNIQUE_SYMBOL == (188483)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188484)
		#define UNIQUE_FUNCTION<%0...%1> %0i14%1
		#endinput
	#if UNIQUE_SYMBOL == (188484)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188485)
		#define UNIQUE_FUNCTION<%0...%1> %0i15%1
		#endinput
	#if UNIQUE_SYMBOL == (188485)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188486)
		#define UNIQUE_FUNCTION<%0...%1> %0i16%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188487)
		#define UNIQUE_FUNCTION<%0...%1> %0i17%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188495)
	#elseif UNIQUE_SYMBOL == (188487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188488)
		#define UNIQUE_FUNCTION<%0...%1> %0i18%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188489)
		#define UNIQUE_FUNCTION<%0...%1> %0i19%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188490)
		#define UNIQUE_FUNCTION<%0...%1> %0i1@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188491)
		#define UNIQUE_FUNCTION<%0...%1> %0i1A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188492)
		#define UNIQUE_FUNCTION<%0...%1> %0i1B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188493)
		#define UNIQUE_FUNCTION<%0...%1> %0i1C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188494)
		#define UNIQUE_FUNCTION<%0...%1> %0i1D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188495)
		#define UNIQUE_FUNCTION<%0...%1> %0i1E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188503)
	#elseif UNIQUE_SYMBOL == (188495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188496)
		#define UNIQUE_FUNCTION<%0...%1> %0i1F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188497)
		#define UNIQUE_FUNCTION<%0...%1> %0i1G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188498)
		#define UNIQUE_FUNCTION<%0...%1> %0i1H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188499)
		#define UNIQUE_FUNCTION<%0...%1> %0i1I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188500)
		#define UNIQUE_FUNCTION<%0...%1> %0i1J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188501)
		#define UNIQUE_FUNCTION<%0...%1> %0i1K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188502)
		#define UNIQUE_FUNCTION<%0...%1> %0i1L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188503)
		#define UNIQUE_FUNCTION<%0...%1> %0i1M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188511)
	#elseif UNIQUE_SYMBOL == (188503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188504)
		#define UNIQUE_FUNCTION<%0...%1> %0i1N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188505)
		#define UNIQUE_FUNCTION<%0...%1> %0i1O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188506)
		#define UNIQUE_FUNCTION<%0...%1> %0i1P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188507)
		#define UNIQUE_FUNCTION<%0...%1> %0i1Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188508)
		#define UNIQUE_FUNCTION<%0...%1> %0i1R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188509)
		#define UNIQUE_FUNCTION<%0...%1> %0i1S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188510)
		#define UNIQUE_FUNCTION<%0...%1> %0i1T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188511)
		#define UNIQUE_FUNCTION<%0...%1> %0i1U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188519)
	#elseif UNIQUE_SYMBOL == (188511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188512)
		#define UNIQUE_FUNCTION<%0...%1> %0i1V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188513)
		#define UNIQUE_FUNCTION<%0...%1> %0i1W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188514)
		#define UNIQUE_FUNCTION<%0...%1> %0i1X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188515)
		#define UNIQUE_FUNCTION<%0...%1> %0i1Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188516)
		#define UNIQUE_FUNCTION<%0...%1> %0i1Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188517)
		#define UNIQUE_FUNCTION<%0...%1> %0i1_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188518)
		#define UNIQUE_FUNCTION<%0...%1> %0i1a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188519)
		#define UNIQUE_FUNCTION<%0...%1> %0i1b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188527)
	#elseif UNIQUE_SYMBOL == (188519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188520)
		#define UNIQUE_FUNCTION<%0...%1> %0i1c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188521)
		#define UNIQUE_FUNCTION<%0...%1> %0i1d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188522)
		#define UNIQUE_FUNCTION<%0...%1> %0i1e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188523)
		#define UNIQUE_FUNCTION<%0...%1> %0i1f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188524)
		#define UNIQUE_FUNCTION<%0...%1> %0i1g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188525)
		#define UNIQUE_FUNCTION<%0...%1> %0i1h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188526)
		#define UNIQUE_FUNCTION<%0...%1> %0i1i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188527)
		#define UNIQUE_FUNCTION<%0...%1> %0i1j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188535)
	#elseif UNIQUE_SYMBOL == (188527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188528)
		#define UNIQUE_FUNCTION<%0...%1> %0i1k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188529)
		#define UNIQUE_FUNCTION<%0...%1> %0i1l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188530)
		#define UNIQUE_FUNCTION<%0...%1> %0i1m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188531)
		#define UNIQUE_FUNCTION<%0...%1> %0i1n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188532)
		#define UNIQUE_FUNCTION<%0...%1> %0i1o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188533)
		#define UNIQUE_FUNCTION<%0...%1> %0i1p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188534)
		#define UNIQUE_FUNCTION<%0...%1> %0i1q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188535)
		#define UNIQUE_FUNCTION<%0...%1> %0i1r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (188535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188536)
		#define UNIQUE_FUNCTION<%0...%1> %0i1s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188537)
		#define UNIQUE_FUNCTION<%0...%1> %0i1t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188538)
		#define UNIQUE_FUNCTION<%0...%1> %0i1u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188539)
		#define UNIQUE_FUNCTION<%0...%1> %0i1v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188540)
		#define UNIQUE_FUNCTION<%0...%1> %0i1w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188541)
		#define UNIQUE_FUNCTION<%0...%1> %0i1x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188542)
		#define UNIQUE_FUNCTION<%0...%1> %0i1y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188543)
		#define UNIQUE_FUNCTION<%0...%1> %0i1z%1
		#endinput
	#endif
#endif
