static stock const Y_UNIQUE_256576_256639_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_256576_256639
	#undef _inc_y_unique_256576_256639
#endif

#if UNIQUE_SYMBOL < (256583)
	#if UNIQUE_SYMBOL == (256575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256576)
		#define UNIQUE_FUNCTION<%0...%1> %0yd0%1
		#endinput
	#if UNIQUE_SYMBOL == (256576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256577)
		#define UNIQUE_FUNCTION<%0...%1> %0yd1%1
		#endinput
	#if UNIQUE_SYMBOL == (256577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256578)
		#define UNIQUE_FUNCTION<%0...%1> %0yd2%1
		#endinput
	#if UNIQUE_SYMBOL == (256578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256579)
		#define UNIQUE_FUNCTION<%0...%1> %0yd3%1
		#endinput
	#if UNIQUE_SYMBOL == (256579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256580)
		#define UNIQUE_FUNCTION<%0...%1> %0yd4%1
		#endinput
	#if UNIQUE_SYMBOL == (256580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256581)
		#define UNIQUE_FUNCTION<%0...%1> %0yd5%1
		#endinput
	#if UNIQUE_SYMBOL == (256581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256582)
		#define UNIQUE_FUNCTION<%0...%1> %0yd6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256583)
		#define UNIQUE_FUNCTION<%0...%1> %0yd7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (256591)
	#elseif UNIQUE_SYMBOL == (256583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256584)
		#define UNIQUE_FUNCTION<%0...%1> %0yd8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256585)
		#define UNIQUE_FUNCTION<%0...%1> %0yd9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256586)
		#define UNIQUE_FUNCTION<%0...%1> %0yd@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256587)
		#define UNIQUE_FUNCTION<%0...%1> %0ydA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256588)
		#define UNIQUE_FUNCTION<%0...%1> %0ydB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256589)
		#define UNIQUE_FUNCTION<%0...%1> %0ydC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256590)
		#define UNIQUE_FUNCTION<%0...%1> %0ydD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256591)
		#define UNIQUE_FUNCTION<%0...%1> %0ydE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (256599)
	#elseif UNIQUE_SYMBOL == (256591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256592)
		#define UNIQUE_FUNCTION<%0...%1> %0ydF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256593)
		#define UNIQUE_FUNCTION<%0...%1> %0ydG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256594)
		#define UNIQUE_FUNCTION<%0...%1> %0ydH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256595)
		#define UNIQUE_FUNCTION<%0...%1> %0ydI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256596)
		#define UNIQUE_FUNCTION<%0...%1> %0ydJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256597)
		#define UNIQUE_FUNCTION<%0...%1> %0ydK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256598)
		#define UNIQUE_FUNCTION<%0...%1> %0ydL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256599)
		#define UNIQUE_FUNCTION<%0...%1> %0ydM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (256607)
	#elseif UNIQUE_SYMBOL == (256599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256600)
		#define UNIQUE_FUNCTION<%0...%1> %0ydN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256601)
		#define UNIQUE_FUNCTION<%0...%1> %0ydO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256602)
		#define UNIQUE_FUNCTION<%0...%1> %0ydP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256603)
		#define UNIQUE_FUNCTION<%0...%1> %0ydQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256604)
		#define UNIQUE_FUNCTION<%0...%1> %0ydR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256605)
		#define UNIQUE_FUNCTION<%0...%1> %0ydS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256606)
		#define UNIQUE_FUNCTION<%0...%1> %0ydT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256607)
		#define UNIQUE_FUNCTION<%0...%1> %0ydU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (256615)
	#elseif UNIQUE_SYMBOL == (256607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256608)
		#define UNIQUE_FUNCTION<%0...%1> %0ydV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256609)
		#define UNIQUE_FUNCTION<%0...%1> %0ydW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256610)
		#define UNIQUE_FUNCTION<%0...%1> %0ydX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256611)
		#define UNIQUE_FUNCTION<%0...%1> %0ydY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256612)
		#define UNIQUE_FUNCTION<%0...%1> %0ydZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256613)
		#define UNIQUE_FUNCTION<%0...%1> %0yd_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256614)
		#define UNIQUE_FUNCTION<%0...%1> %0yda%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256615)
		#define UNIQUE_FUNCTION<%0...%1> %0ydb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (256623)
	#elseif UNIQUE_SYMBOL == (256615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256616)
		#define UNIQUE_FUNCTION<%0...%1> %0ydc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256617)
		#define UNIQUE_FUNCTION<%0...%1> %0ydd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256618)
		#define UNIQUE_FUNCTION<%0...%1> %0yde%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256619)
		#define UNIQUE_FUNCTION<%0...%1> %0ydf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256620)
		#define UNIQUE_FUNCTION<%0...%1> %0ydg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256621)
		#define UNIQUE_FUNCTION<%0...%1> %0ydh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256622)
		#define UNIQUE_FUNCTION<%0...%1> %0ydi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256623)
		#define UNIQUE_FUNCTION<%0...%1> %0ydj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (256631)
	#elseif UNIQUE_SYMBOL == (256623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256624)
		#define UNIQUE_FUNCTION<%0...%1> %0ydk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256625)
		#define UNIQUE_FUNCTION<%0...%1> %0ydl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256626)
		#define UNIQUE_FUNCTION<%0...%1> %0ydm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256627)
		#define UNIQUE_FUNCTION<%0...%1> %0ydn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256628)
		#define UNIQUE_FUNCTION<%0...%1> %0ydo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256629)
		#define UNIQUE_FUNCTION<%0...%1> %0ydp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256630)
		#define UNIQUE_FUNCTION<%0...%1> %0ydq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256631)
		#define UNIQUE_FUNCTION<%0...%1> %0ydr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (256631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256632)
		#define UNIQUE_FUNCTION<%0...%1> %0yds%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256633)
		#define UNIQUE_FUNCTION<%0...%1> %0ydt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256634)
		#define UNIQUE_FUNCTION<%0...%1> %0ydu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256635)
		#define UNIQUE_FUNCTION<%0...%1> %0ydv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256636)
		#define UNIQUE_FUNCTION<%0...%1> %0ydw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256637)
		#define UNIQUE_FUNCTION<%0...%1> %0ydx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (256637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256638)
		#define UNIQUE_FUNCTION<%0...%1> %0ydy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (256639)
		#define UNIQUE_FUNCTION<%0...%1> %0ydz%1
		#endinput
	#endif
#endif
