static stock const Y_UNIQUE_045760_045823_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_045760_045823
	#undef _inc_y_unique_045760_045823
#endif

#if UNIQUE_SYMBOL < (45767)
	#if UNIQUE_SYMBOL == (45759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45760)
		#define UNIQUE_FUNCTION<%0...%1> %0AA0%1
		#endinput
	#if UNIQUE_SYMBOL == (45760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45761)
		#define UNIQUE_FUNCTION<%0...%1> %0AA1%1
		#endinput
	#if UNIQUE_SYMBOL == (45761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45762)
		#define UNIQUE_FUNCTION<%0...%1> %0AA2%1
		#endinput
	#if UNIQUE_SYMBOL == (45762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45763)
		#define UNIQUE_FUNCTION<%0...%1> %0AA3%1
		#endinput
	#if UNIQUE_SYMBOL == (45763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45764)
		#define UNIQUE_FUNCTION<%0...%1> %0AA4%1
		#endinput
	#if UNIQUE_SYMBOL == (45764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45765)
		#define UNIQUE_FUNCTION<%0...%1> %0AA5%1
		#endinput
	#if UNIQUE_SYMBOL == (45765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45766)
		#define UNIQUE_FUNCTION<%0...%1> %0AA6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45767)
		#define UNIQUE_FUNCTION<%0...%1> %0AA7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45775)
	#elseif UNIQUE_SYMBOL == (45767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45768)
		#define UNIQUE_FUNCTION<%0...%1> %0AA8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45769)
		#define UNIQUE_FUNCTION<%0...%1> %0AA9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45770)
		#define UNIQUE_FUNCTION<%0...%1> %0AA@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45771)
		#define UNIQUE_FUNCTION<%0...%1> %0AAA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45772)
		#define UNIQUE_FUNCTION<%0...%1> %0AAB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45773)
		#define UNIQUE_FUNCTION<%0...%1> %0AAC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45774)
		#define UNIQUE_FUNCTION<%0...%1> %0AAD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45775)
		#define UNIQUE_FUNCTION<%0...%1> %0AAE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45783)
	#elseif UNIQUE_SYMBOL == (45775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45776)
		#define UNIQUE_FUNCTION<%0...%1> %0AAF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45777)
		#define UNIQUE_FUNCTION<%0...%1> %0AAG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45778)
		#define UNIQUE_FUNCTION<%0...%1> %0AAH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45779)
		#define UNIQUE_FUNCTION<%0...%1> %0AAI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45780)
		#define UNIQUE_FUNCTION<%0...%1> %0AAJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45781)
		#define UNIQUE_FUNCTION<%0...%1> %0AAK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45782)
		#define UNIQUE_FUNCTION<%0...%1> %0AAL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45783)
		#define UNIQUE_FUNCTION<%0...%1> %0AAM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45791)
	#elseif UNIQUE_SYMBOL == (45783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45784)
		#define UNIQUE_FUNCTION<%0...%1> %0AAN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45785)
		#define UNIQUE_FUNCTION<%0...%1> %0AAO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45786)
		#define UNIQUE_FUNCTION<%0...%1> %0AAP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45787)
		#define UNIQUE_FUNCTION<%0...%1> %0AAQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45788)
		#define UNIQUE_FUNCTION<%0...%1> %0AAR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45789)
		#define UNIQUE_FUNCTION<%0...%1> %0AAS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45790)
		#define UNIQUE_FUNCTION<%0...%1> %0AAT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45791)
		#define UNIQUE_FUNCTION<%0...%1> %0AAU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45799)
	#elseif UNIQUE_SYMBOL == (45791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45792)
		#define UNIQUE_FUNCTION<%0...%1> %0AAV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45793)
		#define UNIQUE_FUNCTION<%0...%1> %0AAW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45794)
		#define UNIQUE_FUNCTION<%0...%1> %0AAX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45795)
		#define UNIQUE_FUNCTION<%0...%1> %0AAY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45796)
		#define UNIQUE_FUNCTION<%0...%1> %0AAZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45797)
		#define UNIQUE_FUNCTION<%0...%1> %0AA_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45798)
		#define UNIQUE_FUNCTION<%0...%1> %0AAa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45799)
		#define UNIQUE_FUNCTION<%0...%1> %0AAb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45807)
	#elseif UNIQUE_SYMBOL == (45799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45800)
		#define UNIQUE_FUNCTION<%0...%1> %0AAc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45801)
		#define UNIQUE_FUNCTION<%0...%1> %0AAd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45802)
		#define UNIQUE_FUNCTION<%0...%1> %0AAe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45803)
		#define UNIQUE_FUNCTION<%0...%1> %0AAf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45804)
		#define UNIQUE_FUNCTION<%0...%1> %0AAg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45805)
		#define UNIQUE_FUNCTION<%0...%1> %0AAh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45806)
		#define UNIQUE_FUNCTION<%0...%1> %0AAi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45807)
		#define UNIQUE_FUNCTION<%0...%1> %0AAj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (45815)
	#elseif UNIQUE_SYMBOL == (45807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45808)
		#define UNIQUE_FUNCTION<%0...%1> %0AAk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45809)
		#define UNIQUE_FUNCTION<%0...%1> %0AAl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45810)
		#define UNIQUE_FUNCTION<%0...%1> %0AAm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45811)
		#define UNIQUE_FUNCTION<%0...%1> %0AAn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45812)
		#define UNIQUE_FUNCTION<%0...%1> %0AAo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45813)
		#define UNIQUE_FUNCTION<%0...%1> %0AAp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45814)
		#define UNIQUE_FUNCTION<%0...%1> %0AAq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45815)
		#define UNIQUE_FUNCTION<%0...%1> %0AAr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (45815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45816)
		#define UNIQUE_FUNCTION<%0...%1> %0AAs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45817)
		#define UNIQUE_FUNCTION<%0...%1> %0AAt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45818)
		#define UNIQUE_FUNCTION<%0...%1> %0AAu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45819)
		#define UNIQUE_FUNCTION<%0...%1> %0AAv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45820)
		#define UNIQUE_FUNCTION<%0...%1> %0AAw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45821)
		#define UNIQUE_FUNCTION<%0...%1> %0AAx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (45821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45822)
		#define UNIQUE_FUNCTION<%0...%1> %0AAy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (45823)
		#define UNIQUE_FUNCTION<%0...%1> %0AAz%1
		#endinput
	#endif
#endif
