static stock const Y_UNIQUE_212736_212799_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_212736_212799
	#undef _inc_y_unique_212736_212799
#endif

#if UNIQUE_SYMBOL < (212743)
	#if UNIQUE_SYMBOL == (212735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212736)
		#define UNIQUE_FUNCTION<%0...%1> %0nw0%1
		#endinput
	#if UNIQUE_SYMBOL == (212736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212737)
		#define UNIQUE_FUNCTION<%0...%1> %0nw1%1
		#endinput
	#if UNIQUE_SYMBOL == (212737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212738)
		#define UNIQUE_FUNCTION<%0...%1> %0nw2%1
		#endinput
	#if UNIQUE_SYMBOL == (212738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212739)
		#define UNIQUE_FUNCTION<%0...%1> %0nw3%1
		#endinput
	#if UNIQUE_SYMBOL == (212739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212740)
		#define UNIQUE_FUNCTION<%0...%1> %0nw4%1
		#endinput
	#if UNIQUE_SYMBOL == (212740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212741)
		#define UNIQUE_FUNCTION<%0...%1> %0nw5%1
		#endinput
	#if UNIQUE_SYMBOL == (212741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212742)
		#define UNIQUE_FUNCTION<%0...%1> %0nw6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212743)
		#define UNIQUE_FUNCTION<%0...%1> %0nw7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212751)
	#elseif UNIQUE_SYMBOL == (212743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212744)
		#define UNIQUE_FUNCTION<%0...%1> %0nw8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212745)
		#define UNIQUE_FUNCTION<%0...%1> %0nw9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212746)
		#define UNIQUE_FUNCTION<%0...%1> %0nw@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212747)
		#define UNIQUE_FUNCTION<%0...%1> %0nwA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212748)
		#define UNIQUE_FUNCTION<%0...%1> %0nwB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212749)
		#define UNIQUE_FUNCTION<%0...%1> %0nwC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212750)
		#define UNIQUE_FUNCTION<%0...%1> %0nwD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212751)
		#define UNIQUE_FUNCTION<%0...%1> %0nwE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212759)
	#elseif UNIQUE_SYMBOL == (212751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212752)
		#define UNIQUE_FUNCTION<%0...%1> %0nwF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212753)
		#define UNIQUE_FUNCTION<%0...%1> %0nwG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212754)
		#define UNIQUE_FUNCTION<%0...%1> %0nwH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212755)
		#define UNIQUE_FUNCTION<%0...%1> %0nwI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212756)
		#define UNIQUE_FUNCTION<%0...%1> %0nwJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212757)
		#define UNIQUE_FUNCTION<%0...%1> %0nwK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212758)
		#define UNIQUE_FUNCTION<%0...%1> %0nwL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212759)
		#define UNIQUE_FUNCTION<%0...%1> %0nwM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212767)
	#elseif UNIQUE_SYMBOL == (212759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212760)
		#define UNIQUE_FUNCTION<%0...%1> %0nwN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212761)
		#define UNIQUE_FUNCTION<%0...%1> %0nwO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212762)
		#define UNIQUE_FUNCTION<%0...%1> %0nwP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212763)
		#define UNIQUE_FUNCTION<%0...%1> %0nwQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212764)
		#define UNIQUE_FUNCTION<%0...%1> %0nwR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212765)
		#define UNIQUE_FUNCTION<%0...%1> %0nwS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212766)
		#define UNIQUE_FUNCTION<%0...%1> %0nwT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212767)
		#define UNIQUE_FUNCTION<%0...%1> %0nwU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212775)
	#elseif UNIQUE_SYMBOL == (212767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212768)
		#define UNIQUE_FUNCTION<%0...%1> %0nwV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212769)
		#define UNIQUE_FUNCTION<%0...%1> %0nwW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212770)
		#define UNIQUE_FUNCTION<%0...%1> %0nwX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212771)
		#define UNIQUE_FUNCTION<%0...%1> %0nwY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212772)
		#define UNIQUE_FUNCTION<%0...%1> %0nwZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212773)
		#define UNIQUE_FUNCTION<%0...%1> %0nw_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212774)
		#define UNIQUE_FUNCTION<%0...%1> %0nwa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212775)
		#define UNIQUE_FUNCTION<%0...%1> %0nwb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212783)
	#elseif UNIQUE_SYMBOL == (212775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212776)
		#define UNIQUE_FUNCTION<%0...%1> %0nwc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212777)
		#define UNIQUE_FUNCTION<%0...%1> %0nwd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212778)
		#define UNIQUE_FUNCTION<%0...%1> %0nwe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212779)
		#define UNIQUE_FUNCTION<%0...%1> %0nwf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212780)
		#define UNIQUE_FUNCTION<%0...%1> %0nwg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212781)
		#define UNIQUE_FUNCTION<%0...%1> %0nwh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212782)
		#define UNIQUE_FUNCTION<%0...%1> %0nwi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212783)
		#define UNIQUE_FUNCTION<%0...%1> %0nwj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212791)
	#elseif UNIQUE_SYMBOL == (212783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212784)
		#define UNIQUE_FUNCTION<%0...%1> %0nwk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212785)
		#define UNIQUE_FUNCTION<%0...%1> %0nwl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212786)
		#define UNIQUE_FUNCTION<%0...%1> %0nwm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212787)
		#define UNIQUE_FUNCTION<%0...%1> %0nwn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212788)
		#define UNIQUE_FUNCTION<%0...%1> %0nwo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212789)
		#define UNIQUE_FUNCTION<%0...%1> %0nwp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212790)
		#define UNIQUE_FUNCTION<%0...%1> %0nwq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212791)
		#define UNIQUE_FUNCTION<%0...%1> %0nwr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (212791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212792)
		#define UNIQUE_FUNCTION<%0...%1> %0nws%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212793)
		#define UNIQUE_FUNCTION<%0...%1> %0nwt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212794)
		#define UNIQUE_FUNCTION<%0...%1> %0nwu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212795)
		#define UNIQUE_FUNCTION<%0...%1> %0nwv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212796)
		#define UNIQUE_FUNCTION<%0...%1> %0nww%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212797)
		#define UNIQUE_FUNCTION<%0...%1> %0nwx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212798)
		#define UNIQUE_FUNCTION<%0...%1> %0nwy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212799)
		#define UNIQUE_FUNCTION<%0...%1> %0nwz%1
		#endinput
	#endif
#endif
