static stock const Y_UNIQUE_063680_063743_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_063680_063743
	#undef _inc_y_unique_063680_063743
#endif

#if UNIQUE_SYMBOL < (63687)
	#if UNIQUE_SYMBOL == (63679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63680)
		#define UNIQUE_FUNCTION<%0...%1> %0EY0%1
		#endinput
	#if UNIQUE_SYMBOL == (63680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63681)
		#define UNIQUE_FUNCTION<%0...%1> %0EY1%1
		#endinput
	#if UNIQUE_SYMBOL == (63681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63682)
		#define UNIQUE_FUNCTION<%0...%1> %0EY2%1
		#endinput
	#if UNIQUE_SYMBOL == (63682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63683)
		#define UNIQUE_FUNCTION<%0...%1> %0EY3%1
		#endinput
	#if UNIQUE_SYMBOL == (63683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63684)
		#define UNIQUE_FUNCTION<%0...%1> %0EY4%1
		#endinput
	#if UNIQUE_SYMBOL == (63684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63685)
		#define UNIQUE_FUNCTION<%0...%1> %0EY5%1
		#endinput
	#if UNIQUE_SYMBOL == (63685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63686)
		#define UNIQUE_FUNCTION<%0...%1> %0EY6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63687)
		#define UNIQUE_FUNCTION<%0...%1> %0EY7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (63695)
	#elseif UNIQUE_SYMBOL == (63687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63688)
		#define UNIQUE_FUNCTION<%0...%1> %0EY8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63689)
		#define UNIQUE_FUNCTION<%0...%1> %0EY9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63690)
		#define UNIQUE_FUNCTION<%0...%1> %0EY@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63691)
		#define UNIQUE_FUNCTION<%0...%1> %0EYA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63692)
		#define UNIQUE_FUNCTION<%0...%1> %0EYB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63693)
		#define UNIQUE_FUNCTION<%0...%1> %0EYC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63694)
		#define UNIQUE_FUNCTION<%0...%1> %0EYD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63695)
		#define UNIQUE_FUNCTION<%0...%1> %0EYE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (63703)
	#elseif UNIQUE_SYMBOL == (63695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63696)
		#define UNIQUE_FUNCTION<%0...%1> %0EYF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63697)
		#define UNIQUE_FUNCTION<%0...%1> %0EYG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63698)
		#define UNIQUE_FUNCTION<%0...%1> %0EYH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63699)
		#define UNIQUE_FUNCTION<%0...%1> %0EYI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63700)
		#define UNIQUE_FUNCTION<%0...%1> %0EYJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63701)
		#define UNIQUE_FUNCTION<%0...%1> %0EYK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63702)
		#define UNIQUE_FUNCTION<%0...%1> %0EYL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63703)
		#define UNIQUE_FUNCTION<%0...%1> %0EYM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (63711)
	#elseif UNIQUE_SYMBOL == (63703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63704)
		#define UNIQUE_FUNCTION<%0...%1> %0EYN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63705)
		#define UNIQUE_FUNCTION<%0...%1> %0EYO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63706)
		#define UNIQUE_FUNCTION<%0...%1> %0EYP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63707)
		#define UNIQUE_FUNCTION<%0...%1> %0EYQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63708)
		#define UNIQUE_FUNCTION<%0...%1> %0EYR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63709)
		#define UNIQUE_FUNCTION<%0...%1> %0EYS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63710)
		#define UNIQUE_FUNCTION<%0...%1> %0EYT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63711)
		#define UNIQUE_FUNCTION<%0...%1> %0EYU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (63719)
	#elseif UNIQUE_SYMBOL == (63711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63712)
		#define UNIQUE_FUNCTION<%0...%1> %0EYV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63713)
		#define UNIQUE_FUNCTION<%0...%1> %0EYW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63714)
		#define UNIQUE_FUNCTION<%0...%1> %0EYX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63715)
		#define UNIQUE_FUNCTION<%0...%1> %0EYY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63716)
		#define UNIQUE_FUNCTION<%0...%1> %0EYZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63717)
		#define UNIQUE_FUNCTION<%0...%1> %0EY_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63718)
		#define UNIQUE_FUNCTION<%0...%1> %0EYa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63719)
		#define UNIQUE_FUNCTION<%0...%1> %0EYb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (63727)
	#elseif UNIQUE_SYMBOL == (63719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63720)
		#define UNIQUE_FUNCTION<%0...%1> %0EYc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63721)
		#define UNIQUE_FUNCTION<%0...%1> %0EYd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63722)
		#define UNIQUE_FUNCTION<%0...%1> %0EYe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63723)
		#define UNIQUE_FUNCTION<%0...%1> %0EYf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63724)
		#define UNIQUE_FUNCTION<%0...%1> %0EYg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63725)
		#define UNIQUE_FUNCTION<%0...%1> %0EYh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63726)
		#define UNIQUE_FUNCTION<%0...%1> %0EYi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63727)
		#define UNIQUE_FUNCTION<%0...%1> %0EYj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (63735)
	#elseif UNIQUE_SYMBOL == (63727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63728)
		#define UNIQUE_FUNCTION<%0...%1> %0EYk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63729)
		#define UNIQUE_FUNCTION<%0...%1> %0EYl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63730)
		#define UNIQUE_FUNCTION<%0...%1> %0EYm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63731)
		#define UNIQUE_FUNCTION<%0...%1> %0EYn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63732)
		#define UNIQUE_FUNCTION<%0...%1> %0EYo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63733)
		#define UNIQUE_FUNCTION<%0...%1> %0EYp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63734)
		#define UNIQUE_FUNCTION<%0...%1> %0EYq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63735)
		#define UNIQUE_FUNCTION<%0...%1> %0EYr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (63735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63736)
		#define UNIQUE_FUNCTION<%0...%1> %0EYs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63737)
		#define UNIQUE_FUNCTION<%0...%1> %0EYt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63738)
		#define UNIQUE_FUNCTION<%0...%1> %0EYu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63739)
		#define UNIQUE_FUNCTION<%0...%1> %0EYv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63740)
		#define UNIQUE_FUNCTION<%0...%1> %0EYw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63741)
		#define UNIQUE_FUNCTION<%0...%1> %0EYx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (63741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63742)
		#define UNIQUE_FUNCTION<%0...%1> %0EYy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (63743)
		#define UNIQUE_FUNCTION<%0...%1> %0EYz%1
		#endinput
	#endif
#endif
