static stock const Y_UNIQUE_079040_079103_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_079040_079103
	#undef _inc_y_unique_079040_079103
#endif

#if UNIQUE_SYMBOL < (79047)
	#if UNIQUE_SYMBOL == (79039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79040)
		#define UNIQUE_FUNCTION<%0...%1> %0II0%1
		#endinput
	#if UNIQUE_SYMBOL == (79040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79041)
		#define UNIQUE_FUNCTION<%0...%1> %0II1%1
		#endinput
	#if UNIQUE_SYMBOL == (79041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79042)
		#define UNIQUE_FUNCTION<%0...%1> %0II2%1
		#endinput
	#if UNIQUE_SYMBOL == (79042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79043)
		#define UNIQUE_FUNCTION<%0...%1> %0II3%1
		#endinput
	#if UNIQUE_SYMBOL == (79043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79044)
		#define UNIQUE_FUNCTION<%0...%1> %0II4%1
		#endinput
	#if UNIQUE_SYMBOL == (79044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79045)
		#define UNIQUE_FUNCTION<%0...%1> %0II5%1
		#endinput
	#if UNIQUE_SYMBOL == (79045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79046)
		#define UNIQUE_FUNCTION<%0...%1> %0II6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79047)
		#define UNIQUE_FUNCTION<%0...%1> %0II7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79055)
	#elseif UNIQUE_SYMBOL == (79047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79048)
		#define UNIQUE_FUNCTION<%0...%1> %0II8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79049)
		#define UNIQUE_FUNCTION<%0...%1> %0II9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79050)
		#define UNIQUE_FUNCTION<%0...%1> %0II@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79051)
		#define UNIQUE_FUNCTION<%0...%1> %0IIA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79052)
		#define UNIQUE_FUNCTION<%0...%1> %0IIB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79053)
		#define UNIQUE_FUNCTION<%0...%1> %0IIC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79054)
		#define UNIQUE_FUNCTION<%0...%1> %0IID%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79055)
		#define UNIQUE_FUNCTION<%0...%1> %0IIE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79063)
	#elseif UNIQUE_SYMBOL == (79055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79056)
		#define UNIQUE_FUNCTION<%0...%1> %0IIF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79057)
		#define UNIQUE_FUNCTION<%0...%1> %0IIG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79058)
		#define UNIQUE_FUNCTION<%0...%1> %0IIH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79059)
		#define UNIQUE_FUNCTION<%0...%1> %0III%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79060)
		#define UNIQUE_FUNCTION<%0...%1> %0IIJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79061)
		#define UNIQUE_FUNCTION<%0...%1> %0IIK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79062)
		#define UNIQUE_FUNCTION<%0...%1> %0IIL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79063)
		#define UNIQUE_FUNCTION<%0...%1> %0IIM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79071)
	#elseif UNIQUE_SYMBOL == (79063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79064)
		#define UNIQUE_FUNCTION<%0...%1> %0IIN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79065)
		#define UNIQUE_FUNCTION<%0...%1> %0IIO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79066)
		#define UNIQUE_FUNCTION<%0...%1> %0IIP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79067)
		#define UNIQUE_FUNCTION<%0...%1> %0IIQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79068)
		#define UNIQUE_FUNCTION<%0...%1> %0IIR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79069)
		#define UNIQUE_FUNCTION<%0...%1> %0IIS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79070)
		#define UNIQUE_FUNCTION<%0...%1> %0IIT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79071)
		#define UNIQUE_FUNCTION<%0...%1> %0IIU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79079)
	#elseif UNIQUE_SYMBOL == (79071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79072)
		#define UNIQUE_FUNCTION<%0...%1> %0IIV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79073)
		#define UNIQUE_FUNCTION<%0...%1> %0IIW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79074)
		#define UNIQUE_FUNCTION<%0...%1> %0IIX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79075)
		#define UNIQUE_FUNCTION<%0...%1> %0IIY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79076)
		#define UNIQUE_FUNCTION<%0...%1> %0IIZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79077)
		#define UNIQUE_FUNCTION<%0...%1> %0II_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79078)
		#define UNIQUE_FUNCTION<%0...%1> %0IIa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79079)
		#define UNIQUE_FUNCTION<%0...%1> %0IIb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79087)
	#elseif UNIQUE_SYMBOL == (79079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79080)
		#define UNIQUE_FUNCTION<%0...%1> %0IIc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79081)
		#define UNIQUE_FUNCTION<%0...%1> %0IId%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79082)
		#define UNIQUE_FUNCTION<%0...%1> %0IIe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79083)
		#define UNIQUE_FUNCTION<%0...%1> %0IIf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79084)
		#define UNIQUE_FUNCTION<%0...%1> %0IIg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79085)
		#define UNIQUE_FUNCTION<%0...%1> %0IIh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79086)
		#define UNIQUE_FUNCTION<%0...%1> %0IIi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79087)
		#define UNIQUE_FUNCTION<%0...%1> %0IIj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79095)
	#elseif UNIQUE_SYMBOL == (79087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79088)
		#define UNIQUE_FUNCTION<%0...%1> %0IIk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79089)
		#define UNIQUE_FUNCTION<%0...%1> %0IIl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79090)
		#define UNIQUE_FUNCTION<%0...%1> %0IIm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79091)
		#define UNIQUE_FUNCTION<%0...%1> %0IIn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79092)
		#define UNIQUE_FUNCTION<%0...%1> %0IIo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79093)
		#define UNIQUE_FUNCTION<%0...%1> %0IIp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79094)
		#define UNIQUE_FUNCTION<%0...%1> %0IIq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79095)
		#define UNIQUE_FUNCTION<%0...%1> %0IIr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (79095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79096)
		#define UNIQUE_FUNCTION<%0...%1> %0IIs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79097)
		#define UNIQUE_FUNCTION<%0...%1> %0IIt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79098)
		#define UNIQUE_FUNCTION<%0...%1> %0IIu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79099)
		#define UNIQUE_FUNCTION<%0...%1> %0IIv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79100)
		#define UNIQUE_FUNCTION<%0...%1> %0IIw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79101)
		#define UNIQUE_FUNCTION<%0...%1> %0IIx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79102)
		#define UNIQUE_FUNCTION<%0...%1> %0IIy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79103)
		#define UNIQUE_FUNCTION<%0...%1> %0IIz%1
		#endinput
	#endif
#endif
