static stock const Y_UNIQUE_024320_024383_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_024320_024383
	#undef _inc_y_unique_024320_024383
#endif

#if UNIQUE_SYMBOL < (24327)
	#if UNIQUE_SYMBOL == (24319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24320)
		#define UNIQUE_FUNCTION<%0...%1> %05w0%1
		#endinput
	#if UNIQUE_SYMBOL == (24320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24321)
		#define UNIQUE_FUNCTION<%0...%1> %05w1%1
		#endinput
	#if UNIQUE_SYMBOL == (24321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24322)
		#define UNIQUE_FUNCTION<%0...%1> %05w2%1
		#endinput
	#if UNIQUE_SYMBOL == (24322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24323)
		#define UNIQUE_FUNCTION<%0...%1> %05w3%1
		#endinput
	#if UNIQUE_SYMBOL == (24323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24324)
		#define UNIQUE_FUNCTION<%0...%1> %05w4%1
		#endinput
	#if UNIQUE_SYMBOL == (24324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24325)
		#define UNIQUE_FUNCTION<%0...%1> %05w5%1
		#endinput
	#if UNIQUE_SYMBOL == (24325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24326)
		#define UNIQUE_FUNCTION<%0...%1> %05w6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24327)
		#define UNIQUE_FUNCTION<%0...%1> %05w7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24335)
	#elseif UNIQUE_SYMBOL == (24327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24328)
		#define UNIQUE_FUNCTION<%0...%1> %05w8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24329)
		#define UNIQUE_FUNCTION<%0...%1> %05w9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24330)
		#define UNIQUE_FUNCTION<%0...%1> %05w@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24331)
		#define UNIQUE_FUNCTION<%0...%1> %05wA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24332)
		#define UNIQUE_FUNCTION<%0...%1> %05wB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24333)
		#define UNIQUE_FUNCTION<%0...%1> %05wC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24334)
		#define UNIQUE_FUNCTION<%0...%1> %05wD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24335)
		#define UNIQUE_FUNCTION<%0...%1> %05wE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24343)
	#elseif UNIQUE_SYMBOL == (24335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24336)
		#define UNIQUE_FUNCTION<%0...%1> %05wF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24337)
		#define UNIQUE_FUNCTION<%0...%1> %05wG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24338)
		#define UNIQUE_FUNCTION<%0...%1> %05wH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24339)
		#define UNIQUE_FUNCTION<%0...%1> %05wI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24340)
		#define UNIQUE_FUNCTION<%0...%1> %05wJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24341)
		#define UNIQUE_FUNCTION<%0...%1> %05wK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24342)
		#define UNIQUE_FUNCTION<%0...%1> %05wL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24343)
		#define UNIQUE_FUNCTION<%0...%1> %05wM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24351)
	#elseif UNIQUE_SYMBOL == (24343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24344)
		#define UNIQUE_FUNCTION<%0...%1> %05wN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24345)
		#define UNIQUE_FUNCTION<%0...%1> %05wO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24346)
		#define UNIQUE_FUNCTION<%0...%1> %05wP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24347)
		#define UNIQUE_FUNCTION<%0...%1> %05wQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24348)
		#define UNIQUE_FUNCTION<%0...%1> %05wR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24349)
		#define UNIQUE_FUNCTION<%0...%1> %05wS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24350)
		#define UNIQUE_FUNCTION<%0...%1> %05wT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24351)
		#define UNIQUE_FUNCTION<%0...%1> %05wU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24359)
	#elseif UNIQUE_SYMBOL == (24351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24352)
		#define UNIQUE_FUNCTION<%0...%1> %05wV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24353)
		#define UNIQUE_FUNCTION<%0...%1> %05wW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24354)
		#define UNIQUE_FUNCTION<%0...%1> %05wX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24355)
		#define UNIQUE_FUNCTION<%0...%1> %05wY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24356)
		#define UNIQUE_FUNCTION<%0...%1> %05wZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24357)
		#define UNIQUE_FUNCTION<%0...%1> %05w_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24358)
		#define UNIQUE_FUNCTION<%0...%1> %05wa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24359)
		#define UNIQUE_FUNCTION<%0...%1> %05wb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24367)
	#elseif UNIQUE_SYMBOL == (24359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24360)
		#define UNIQUE_FUNCTION<%0...%1> %05wc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24361)
		#define UNIQUE_FUNCTION<%0...%1> %05wd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24362)
		#define UNIQUE_FUNCTION<%0...%1> %05we%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24363)
		#define UNIQUE_FUNCTION<%0...%1> %05wf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24364)
		#define UNIQUE_FUNCTION<%0...%1> %05wg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24365)
		#define UNIQUE_FUNCTION<%0...%1> %05wh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24366)
		#define UNIQUE_FUNCTION<%0...%1> %05wi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24367)
		#define UNIQUE_FUNCTION<%0...%1> %05wj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24375)
	#elseif UNIQUE_SYMBOL == (24367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24368)
		#define UNIQUE_FUNCTION<%0...%1> %05wk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24369)
		#define UNIQUE_FUNCTION<%0...%1> %05wl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24370)
		#define UNIQUE_FUNCTION<%0...%1> %05wm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24371)
		#define UNIQUE_FUNCTION<%0...%1> %05wn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24372)
		#define UNIQUE_FUNCTION<%0...%1> %05wo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24373)
		#define UNIQUE_FUNCTION<%0...%1> %05wp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24374)
		#define UNIQUE_FUNCTION<%0...%1> %05wq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24375)
		#define UNIQUE_FUNCTION<%0...%1> %05wr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (24375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24376)
		#define UNIQUE_FUNCTION<%0...%1> %05ws%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24377)
		#define UNIQUE_FUNCTION<%0...%1> %05wt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24378)
		#define UNIQUE_FUNCTION<%0...%1> %05wu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24379)
		#define UNIQUE_FUNCTION<%0...%1> %05wv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24380)
		#define UNIQUE_FUNCTION<%0...%1> %05ww%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24381)
		#define UNIQUE_FUNCTION<%0...%1> %05wx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24382)
		#define UNIQUE_FUNCTION<%0...%1> %05wy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24383)
		#define UNIQUE_FUNCTION<%0...%1> %05wz%1
		#endinput
	#endif
#endif
