static stock const Y_UNIQUE_072384_072447_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_072384_072447
	#undef _inc_y_unique_072384_072447
#endif

#if UNIQUE_SYMBOL < (72391)
	#if UNIQUE_SYMBOL == (72383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72384)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf0%1
		#endinput
	#if UNIQUE_SYMBOL == (72384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72385)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf1%1
		#endinput
	#if UNIQUE_SYMBOL == (72385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72386)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf2%1
		#endinput
	#if UNIQUE_SYMBOL == (72386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72387)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf3%1
		#endinput
	#if UNIQUE_SYMBOL == (72387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72388)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf4%1
		#endinput
	#if UNIQUE_SYMBOL == (72388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72389)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf5%1
		#endinput
	#if UNIQUE_SYMBOL == (72389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72390)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72391)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (72399)
	#elseif UNIQUE_SYMBOL == (72391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72392)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72393)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72394)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72395)
		#define UNIQUE_FUNCTION<%0...%1> %0GfA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72396)
		#define UNIQUE_FUNCTION<%0...%1> %0GfB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72397)
		#define UNIQUE_FUNCTION<%0...%1> %0GfC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72398)
		#define UNIQUE_FUNCTION<%0...%1> %0GfD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72399)
		#define UNIQUE_FUNCTION<%0...%1> %0GfE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (72407)
	#elseif UNIQUE_SYMBOL == (72399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72400)
		#define UNIQUE_FUNCTION<%0...%1> %0GfF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72401)
		#define UNIQUE_FUNCTION<%0...%1> %0GfG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72402)
		#define UNIQUE_FUNCTION<%0...%1> %0GfH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72403)
		#define UNIQUE_FUNCTION<%0...%1> %0GfI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72404)
		#define UNIQUE_FUNCTION<%0...%1> %0GfJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72405)
		#define UNIQUE_FUNCTION<%0...%1> %0GfK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72406)
		#define UNIQUE_FUNCTION<%0...%1> %0GfL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72407)
		#define UNIQUE_FUNCTION<%0...%1> %0GfM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (72415)
	#elseif UNIQUE_SYMBOL == (72407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72408)
		#define UNIQUE_FUNCTION<%0...%1> %0GfN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72409)
		#define UNIQUE_FUNCTION<%0...%1> %0GfO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72410)
		#define UNIQUE_FUNCTION<%0...%1> %0GfP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72411)
		#define UNIQUE_FUNCTION<%0...%1> %0GfQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72412)
		#define UNIQUE_FUNCTION<%0...%1> %0GfR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72413)
		#define UNIQUE_FUNCTION<%0...%1> %0GfS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72414)
		#define UNIQUE_FUNCTION<%0...%1> %0GfT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72415)
		#define UNIQUE_FUNCTION<%0...%1> %0GfU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (72423)
	#elseif UNIQUE_SYMBOL == (72415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72416)
		#define UNIQUE_FUNCTION<%0...%1> %0GfV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72417)
		#define UNIQUE_FUNCTION<%0...%1> %0GfW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72418)
		#define UNIQUE_FUNCTION<%0...%1> %0GfX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72419)
		#define UNIQUE_FUNCTION<%0...%1> %0GfY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72420)
		#define UNIQUE_FUNCTION<%0...%1> %0GfZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72421)
		#define UNIQUE_FUNCTION<%0...%1> %0Gf_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72422)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72423)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (72431)
	#elseif UNIQUE_SYMBOL == (72423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72424)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72425)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72426)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72427)
		#define UNIQUE_FUNCTION<%0...%1> %0Gff%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72428)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72429)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72430)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72431)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (72439)
	#elseif UNIQUE_SYMBOL == (72431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72432)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72433)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72434)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72435)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72436)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72437)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72438)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72439)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (72439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72440)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72441)
		#define UNIQUE_FUNCTION<%0...%1> %0Gft%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72442)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72443)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72444)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72445)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (72445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72446)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (72447)
		#define UNIQUE_FUNCTION<%0...%1> %0Gfz%1
		#endinput
	#endif
#endif
