static stock const Y_UNIQUE_026112_026175_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_026112_026175
	#undef _inc_y_unique_026112_026175
#endif

#if UNIQUE_SYMBOL < (26119)
	#if UNIQUE_SYMBOL == (26111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26112)
		#define UNIQUE_FUNCTION<%0...%1> %06N0%1
		#endinput
	#if UNIQUE_SYMBOL == (26112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26113)
		#define UNIQUE_FUNCTION<%0...%1> %06N1%1
		#endinput
	#if UNIQUE_SYMBOL == (26113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26114)
		#define UNIQUE_FUNCTION<%0...%1> %06N2%1
		#endinput
	#if UNIQUE_SYMBOL == (26114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26115)
		#define UNIQUE_FUNCTION<%0...%1> %06N3%1
		#endinput
	#if UNIQUE_SYMBOL == (26115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26116)
		#define UNIQUE_FUNCTION<%0...%1> %06N4%1
		#endinput
	#if UNIQUE_SYMBOL == (26116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26117)
		#define UNIQUE_FUNCTION<%0...%1> %06N5%1
		#endinput
	#if UNIQUE_SYMBOL == (26117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26118)
		#define UNIQUE_FUNCTION<%0...%1> %06N6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26119)
		#define UNIQUE_FUNCTION<%0...%1> %06N7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (26127)
	#elseif UNIQUE_SYMBOL == (26119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26120)
		#define UNIQUE_FUNCTION<%0...%1> %06N8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26121)
		#define UNIQUE_FUNCTION<%0...%1> %06N9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26122)
		#define UNIQUE_FUNCTION<%0...%1> %06N@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26123)
		#define UNIQUE_FUNCTION<%0...%1> %06NA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26124)
		#define UNIQUE_FUNCTION<%0...%1> %06NB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26125)
		#define UNIQUE_FUNCTION<%0...%1> %06NC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26126)
		#define UNIQUE_FUNCTION<%0...%1> %06ND%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26127)
		#define UNIQUE_FUNCTION<%0...%1> %06NE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (26135)
	#elseif UNIQUE_SYMBOL == (26127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26128)
		#define UNIQUE_FUNCTION<%0...%1> %06NF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26129)
		#define UNIQUE_FUNCTION<%0...%1> %06NG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26130)
		#define UNIQUE_FUNCTION<%0...%1> %06NH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26131)
		#define UNIQUE_FUNCTION<%0...%1> %06NI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26132)
		#define UNIQUE_FUNCTION<%0...%1> %06NJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26133)
		#define UNIQUE_FUNCTION<%0...%1> %06NK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26134)
		#define UNIQUE_FUNCTION<%0...%1> %06NL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26135)
		#define UNIQUE_FUNCTION<%0...%1> %06NM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (26143)
	#elseif UNIQUE_SYMBOL == (26135)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26136)
		#define UNIQUE_FUNCTION<%0...%1> %06NN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26136)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26137)
		#define UNIQUE_FUNCTION<%0...%1> %06NO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26137)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26138)
		#define UNIQUE_FUNCTION<%0...%1> %06NP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26138)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26139)
		#define UNIQUE_FUNCTION<%0...%1> %06NQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26139)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26140)
		#define UNIQUE_FUNCTION<%0...%1> %06NR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26140)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26141)
		#define UNIQUE_FUNCTION<%0...%1> %06NS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26141)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26142)
		#define UNIQUE_FUNCTION<%0...%1> %06NT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26143)
		#define UNIQUE_FUNCTION<%0...%1> %06NU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (26151)
	#elseif UNIQUE_SYMBOL == (26143)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26144)
		#define UNIQUE_FUNCTION<%0...%1> %06NV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26144)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26145)
		#define UNIQUE_FUNCTION<%0...%1> %06NW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26145)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26146)
		#define UNIQUE_FUNCTION<%0...%1> %06NX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26146)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26147)
		#define UNIQUE_FUNCTION<%0...%1> %06NY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26147)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26148)
		#define UNIQUE_FUNCTION<%0...%1> %06NZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26148)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26149)
		#define UNIQUE_FUNCTION<%0...%1> %06N_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26149)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26150)
		#define UNIQUE_FUNCTION<%0...%1> %06Na%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26151)
		#define UNIQUE_FUNCTION<%0...%1> %06Nb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (26159)
	#elseif UNIQUE_SYMBOL == (26151)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26152)
		#define UNIQUE_FUNCTION<%0...%1> %06Nc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26152)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26153)
		#define UNIQUE_FUNCTION<%0...%1> %06Nd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26153)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26154)
		#define UNIQUE_FUNCTION<%0...%1> %06Ne%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26154)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26155)
		#define UNIQUE_FUNCTION<%0...%1> %06Nf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26155)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26156)
		#define UNIQUE_FUNCTION<%0...%1> %06Ng%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26156)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26157)
		#define UNIQUE_FUNCTION<%0...%1> %06Nh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26157)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26158)
		#define UNIQUE_FUNCTION<%0...%1> %06Ni%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26159)
		#define UNIQUE_FUNCTION<%0...%1> %06Nj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (26167)
	#elseif UNIQUE_SYMBOL == (26159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26160)
		#define UNIQUE_FUNCTION<%0...%1> %06Nk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26161)
		#define UNIQUE_FUNCTION<%0...%1> %06Nl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26162)
		#define UNIQUE_FUNCTION<%0...%1> %06Nm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26163)
		#define UNIQUE_FUNCTION<%0...%1> %06Nn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26164)
		#define UNIQUE_FUNCTION<%0...%1> %06No%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26165)
		#define UNIQUE_FUNCTION<%0...%1> %06Np%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26166)
		#define UNIQUE_FUNCTION<%0...%1> %06Nq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26167)
		#define UNIQUE_FUNCTION<%0...%1> %06Nr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (26167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26168)
		#define UNIQUE_FUNCTION<%0...%1> %06Ns%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26169)
		#define UNIQUE_FUNCTION<%0...%1> %06Nt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26170)
		#define UNIQUE_FUNCTION<%0...%1> %06Nu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26171)
		#define UNIQUE_FUNCTION<%0...%1> %06Nv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26172)
		#define UNIQUE_FUNCTION<%0...%1> %06Nw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26173)
		#define UNIQUE_FUNCTION<%0...%1> %06Nx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (26173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26174)
		#define UNIQUE_FUNCTION<%0...%1> %06Ny%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (26175)
		#define UNIQUE_FUNCTION<%0...%1> %06Nz%1
		#endinput
	#endif
#endif
