static stock const Y_UNIQUE_052032_052095_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_052032_052095
	#undef _inc_y_unique_052032_052095
#endif

#if UNIQUE_SYMBOL < (52039)
	#if UNIQUE_SYMBOL == (52031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52032)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh0%1
		#endinput
	#if UNIQUE_SYMBOL == (52032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52033)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh1%1
		#endinput
	#if UNIQUE_SYMBOL == (52033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52034)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh2%1
		#endinput
	#if UNIQUE_SYMBOL == (52034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52035)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh3%1
		#endinput
	#if UNIQUE_SYMBOL == (52035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52036)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh4%1
		#endinput
	#if UNIQUE_SYMBOL == (52036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52037)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh5%1
		#endinput
	#if UNIQUE_SYMBOL == (52037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52038)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52039)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52047)
	#elseif UNIQUE_SYMBOL == (52039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52040)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52041)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52042)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52043)
		#define UNIQUE_FUNCTION<%0...%1> %0BhA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52044)
		#define UNIQUE_FUNCTION<%0...%1> %0BhB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52045)
		#define UNIQUE_FUNCTION<%0...%1> %0BhC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52046)
		#define UNIQUE_FUNCTION<%0...%1> %0BhD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52047)
		#define UNIQUE_FUNCTION<%0...%1> %0BhE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52055)
	#elseif UNIQUE_SYMBOL == (52047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52048)
		#define UNIQUE_FUNCTION<%0...%1> %0BhF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52049)
		#define UNIQUE_FUNCTION<%0...%1> %0BhG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52050)
		#define UNIQUE_FUNCTION<%0...%1> %0BhH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52051)
		#define UNIQUE_FUNCTION<%0...%1> %0BhI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52052)
		#define UNIQUE_FUNCTION<%0...%1> %0BhJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52053)
		#define UNIQUE_FUNCTION<%0...%1> %0BhK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52054)
		#define UNIQUE_FUNCTION<%0...%1> %0BhL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52055)
		#define UNIQUE_FUNCTION<%0...%1> %0BhM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52063)
	#elseif UNIQUE_SYMBOL == (52055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52056)
		#define UNIQUE_FUNCTION<%0...%1> %0BhN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52057)
		#define UNIQUE_FUNCTION<%0...%1> %0BhO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52058)
		#define UNIQUE_FUNCTION<%0...%1> %0BhP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52059)
		#define UNIQUE_FUNCTION<%0...%1> %0BhQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52060)
		#define UNIQUE_FUNCTION<%0...%1> %0BhR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52061)
		#define UNIQUE_FUNCTION<%0...%1> %0BhS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52062)
		#define UNIQUE_FUNCTION<%0...%1> %0BhT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52063)
		#define UNIQUE_FUNCTION<%0...%1> %0BhU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52071)
	#elseif UNIQUE_SYMBOL == (52063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52064)
		#define UNIQUE_FUNCTION<%0...%1> %0BhV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52065)
		#define UNIQUE_FUNCTION<%0...%1> %0BhW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52066)
		#define UNIQUE_FUNCTION<%0...%1> %0BhX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52067)
		#define UNIQUE_FUNCTION<%0...%1> %0BhY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52068)
		#define UNIQUE_FUNCTION<%0...%1> %0BhZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52069)
		#define UNIQUE_FUNCTION<%0...%1> %0Bh_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52070)
		#define UNIQUE_FUNCTION<%0...%1> %0Bha%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52071)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52079)
	#elseif UNIQUE_SYMBOL == (52071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52072)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52073)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52074)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52075)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52076)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52077)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52078)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52079)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (52087)
	#elseif UNIQUE_SYMBOL == (52079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52080)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52081)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52082)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52083)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52084)
		#define UNIQUE_FUNCTION<%0...%1> %0Bho%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52085)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52086)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52087)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (52087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52088)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52089)
		#define UNIQUE_FUNCTION<%0...%1> %0Bht%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52090)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52091)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52092)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52093)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (52093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52094)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (52095)
		#define UNIQUE_FUNCTION<%0...%1> %0Bhz%1
		#endinput
	#endif
#endif
