static stock const Y_UNIQUE_089920_089983_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_089920_089983
	#undef _inc_y_unique_089920_089983
#endif

#if UNIQUE_SYMBOL < (89927)
	#if UNIQUE_SYMBOL == (89919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89920)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx0%1
		#endinput
	#if UNIQUE_SYMBOL == (89920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89921)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx1%1
		#endinput
	#if UNIQUE_SYMBOL == (89921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89922)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx2%1
		#endinput
	#if UNIQUE_SYMBOL == (89922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89923)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx3%1
		#endinput
	#if UNIQUE_SYMBOL == (89923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89924)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx4%1
		#endinput
	#if UNIQUE_SYMBOL == (89924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89925)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx5%1
		#endinput
	#if UNIQUE_SYMBOL == (89925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89926)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89927)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89935)
	#elseif UNIQUE_SYMBOL == (89927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89928)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89929)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89930)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89931)
		#define UNIQUE_FUNCTION<%0...%1> %0KxA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89932)
		#define UNIQUE_FUNCTION<%0...%1> %0KxB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89933)
		#define UNIQUE_FUNCTION<%0...%1> %0KxC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89934)
		#define UNIQUE_FUNCTION<%0...%1> %0KxD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89935)
		#define UNIQUE_FUNCTION<%0...%1> %0KxE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89943)
	#elseif UNIQUE_SYMBOL == (89935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89936)
		#define UNIQUE_FUNCTION<%0...%1> %0KxF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89937)
		#define UNIQUE_FUNCTION<%0...%1> %0KxG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89938)
		#define UNIQUE_FUNCTION<%0...%1> %0KxH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89939)
		#define UNIQUE_FUNCTION<%0...%1> %0KxI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89940)
		#define UNIQUE_FUNCTION<%0...%1> %0KxJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89941)
		#define UNIQUE_FUNCTION<%0...%1> %0KxK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89942)
		#define UNIQUE_FUNCTION<%0...%1> %0KxL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89943)
		#define UNIQUE_FUNCTION<%0...%1> %0KxM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89951)
	#elseif UNIQUE_SYMBOL == (89943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89944)
		#define UNIQUE_FUNCTION<%0...%1> %0KxN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89945)
		#define UNIQUE_FUNCTION<%0...%1> %0KxO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89946)
		#define UNIQUE_FUNCTION<%0...%1> %0KxP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89947)
		#define UNIQUE_FUNCTION<%0...%1> %0KxQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89948)
		#define UNIQUE_FUNCTION<%0...%1> %0KxR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89949)
		#define UNIQUE_FUNCTION<%0...%1> %0KxS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89950)
		#define UNIQUE_FUNCTION<%0...%1> %0KxT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89951)
		#define UNIQUE_FUNCTION<%0...%1> %0KxU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89959)
	#elseif UNIQUE_SYMBOL == (89951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89952)
		#define UNIQUE_FUNCTION<%0...%1> %0KxV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89953)
		#define UNIQUE_FUNCTION<%0...%1> %0KxW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89954)
		#define UNIQUE_FUNCTION<%0...%1> %0KxX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89955)
		#define UNIQUE_FUNCTION<%0...%1> %0KxY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89956)
		#define UNIQUE_FUNCTION<%0...%1> %0KxZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89957)
		#define UNIQUE_FUNCTION<%0...%1> %0Kx_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89958)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89959)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89967)
	#elseif UNIQUE_SYMBOL == (89959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89960)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89961)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89962)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89963)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89964)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89965)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89966)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89967)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89975)
	#elseif UNIQUE_SYMBOL == (89967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89968)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89969)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89970)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89971)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89972)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89973)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89974)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89975)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (89975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89976)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89977)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89978)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89979)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89980)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89981)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89982)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89983)
		#define UNIQUE_FUNCTION<%0...%1> %0Kxz%1
		#endinput
	#endif
#endif
