static stock const Y_UNIQUE_069760_069823_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_069760_069823
	#undef _inc_y_unique_069760_069823
#endif

#if UNIQUE_SYMBOL < (69767)
	#if UNIQUE_SYMBOL == (69759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69760)
		#define UNIQUE_FUNCTION<%0...%1> %0G20%1
		#endinput
	#if UNIQUE_SYMBOL == (69760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69761)
		#define UNIQUE_FUNCTION<%0...%1> %0G21%1
		#endinput
	#if UNIQUE_SYMBOL == (69761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69762)
		#define UNIQUE_FUNCTION<%0...%1> %0G22%1
		#endinput
	#if UNIQUE_SYMBOL == (69762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69763)
		#define UNIQUE_FUNCTION<%0...%1> %0G23%1
		#endinput
	#if UNIQUE_SYMBOL == (69763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69764)
		#define UNIQUE_FUNCTION<%0...%1> %0G24%1
		#endinput
	#if UNIQUE_SYMBOL == (69764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69765)
		#define UNIQUE_FUNCTION<%0...%1> %0G25%1
		#endinput
	#if UNIQUE_SYMBOL == (69765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69766)
		#define UNIQUE_FUNCTION<%0...%1> %0G26%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69767)
		#define UNIQUE_FUNCTION<%0...%1> %0G27%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (69775)
	#elseif UNIQUE_SYMBOL == (69767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69768)
		#define UNIQUE_FUNCTION<%0...%1> %0G28%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69769)
		#define UNIQUE_FUNCTION<%0...%1> %0G29%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69770)
		#define UNIQUE_FUNCTION<%0...%1> %0G2@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69771)
		#define UNIQUE_FUNCTION<%0...%1> %0G2A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69772)
		#define UNIQUE_FUNCTION<%0...%1> %0G2B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69773)
		#define UNIQUE_FUNCTION<%0...%1> %0G2C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69774)
		#define UNIQUE_FUNCTION<%0...%1> %0G2D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69775)
		#define UNIQUE_FUNCTION<%0...%1> %0G2E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (69783)
	#elseif UNIQUE_SYMBOL == (69775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69776)
		#define UNIQUE_FUNCTION<%0...%1> %0G2F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69777)
		#define UNIQUE_FUNCTION<%0...%1> %0G2G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69778)
		#define UNIQUE_FUNCTION<%0...%1> %0G2H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69779)
		#define UNIQUE_FUNCTION<%0...%1> %0G2I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69780)
		#define UNIQUE_FUNCTION<%0...%1> %0G2J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69781)
		#define UNIQUE_FUNCTION<%0...%1> %0G2K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69782)
		#define UNIQUE_FUNCTION<%0...%1> %0G2L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69783)
		#define UNIQUE_FUNCTION<%0...%1> %0G2M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (69791)
	#elseif UNIQUE_SYMBOL == (69783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69784)
		#define UNIQUE_FUNCTION<%0...%1> %0G2N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69785)
		#define UNIQUE_FUNCTION<%0...%1> %0G2O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69786)
		#define UNIQUE_FUNCTION<%0...%1> %0G2P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69787)
		#define UNIQUE_FUNCTION<%0...%1> %0G2Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69788)
		#define UNIQUE_FUNCTION<%0...%1> %0G2R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69789)
		#define UNIQUE_FUNCTION<%0...%1> %0G2S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69790)
		#define UNIQUE_FUNCTION<%0...%1> %0G2T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69791)
		#define UNIQUE_FUNCTION<%0...%1> %0G2U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (69799)
	#elseif UNIQUE_SYMBOL == (69791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69792)
		#define UNIQUE_FUNCTION<%0...%1> %0G2V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69793)
		#define UNIQUE_FUNCTION<%0...%1> %0G2W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69794)
		#define UNIQUE_FUNCTION<%0...%1> %0G2X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69795)
		#define UNIQUE_FUNCTION<%0...%1> %0G2Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69796)
		#define UNIQUE_FUNCTION<%0...%1> %0G2Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69797)
		#define UNIQUE_FUNCTION<%0...%1> %0G2_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69798)
		#define UNIQUE_FUNCTION<%0...%1> %0G2a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69799)
		#define UNIQUE_FUNCTION<%0...%1> %0G2b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (69807)
	#elseif UNIQUE_SYMBOL == (69799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69800)
		#define UNIQUE_FUNCTION<%0...%1> %0G2c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69801)
		#define UNIQUE_FUNCTION<%0...%1> %0G2d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69802)
		#define UNIQUE_FUNCTION<%0...%1> %0G2e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69803)
		#define UNIQUE_FUNCTION<%0...%1> %0G2f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69804)
		#define UNIQUE_FUNCTION<%0...%1> %0G2g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69805)
		#define UNIQUE_FUNCTION<%0...%1> %0G2h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69806)
		#define UNIQUE_FUNCTION<%0...%1> %0G2i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69807)
		#define UNIQUE_FUNCTION<%0...%1> %0G2j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (69815)
	#elseif UNIQUE_SYMBOL == (69807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69808)
		#define UNIQUE_FUNCTION<%0...%1> %0G2k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69809)
		#define UNIQUE_FUNCTION<%0...%1> %0G2l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69810)
		#define UNIQUE_FUNCTION<%0...%1> %0G2m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69811)
		#define UNIQUE_FUNCTION<%0...%1> %0G2n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69812)
		#define UNIQUE_FUNCTION<%0...%1> %0G2o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69813)
		#define UNIQUE_FUNCTION<%0...%1> %0G2p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69814)
		#define UNIQUE_FUNCTION<%0...%1> %0G2q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69815)
		#define UNIQUE_FUNCTION<%0...%1> %0G2r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (69815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69816)
		#define UNIQUE_FUNCTION<%0...%1> %0G2s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69817)
		#define UNIQUE_FUNCTION<%0...%1> %0G2t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69818)
		#define UNIQUE_FUNCTION<%0...%1> %0G2u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69819)
		#define UNIQUE_FUNCTION<%0...%1> %0G2v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69820)
		#define UNIQUE_FUNCTION<%0...%1> %0G2w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69821)
		#define UNIQUE_FUNCTION<%0...%1> %0G2x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (69821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69822)
		#define UNIQUE_FUNCTION<%0...%1> %0G2y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (69823)
		#define UNIQUE_FUNCTION<%0...%1> %0G2z%1
		#endinput
	#endif
#endif
