static stock const Y_UNIQUE_128896_128959_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_128896_128959
	#undef _inc_y_unique_128896_128959
#endif

#if UNIQUE_SYMBOL < (128903)
	#if UNIQUE_SYMBOL == (128895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128896)
		#define UNIQUE_FUNCTION<%0...%1> %0UT0%1
		#endinput
	#if UNIQUE_SYMBOL == (128896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128897)
		#define UNIQUE_FUNCTION<%0...%1> %0UT1%1
		#endinput
	#if UNIQUE_SYMBOL == (128897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128898)
		#define UNIQUE_FUNCTION<%0...%1> %0UT2%1
		#endinput
	#if UNIQUE_SYMBOL == (128898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128899)
		#define UNIQUE_FUNCTION<%0...%1> %0UT3%1
		#endinput
	#if UNIQUE_SYMBOL == (128899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128900)
		#define UNIQUE_FUNCTION<%0...%1> %0UT4%1
		#endinput
	#if UNIQUE_SYMBOL == (128900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128901)
		#define UNIQUE_FUNCTION<%0...%1> %0UT5%1
		#endinput
	#if UNIQUE_SYMBOL == (128901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128902)
		#define UNIQUE_FUNCTION<%0...%1> %0UT6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128903)
		#define UNIQUE_FUNCTION<%0...%1> %0UT7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128911)
	#elseif UNIQUE_SYMBOL == (128903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128904)
		#define UNIQUE_FUNCTION<%0...%1> %0UT8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128905)
		#define UNIQUE_FUNCTION<%0...%1> %0UT9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128906)
		#define UNIQUE_FUNCTION<%0...%1> %0UT@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128907)
		#define UNIQUE_FUNCTION<%0...%1> %0UTA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128908)
		#define UNIQUE_FUNCTION<%0...%1> %0UTB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128909)
		#define UNIQUE_FUNCTION<%0...%1> %0UTC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128910)
		#define UNIQUE_FUNCTION<%0...%1> %0UTD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128911)
		#define UNIQUE_FUNCTION<%0...%1> %0UTE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128919)
	#elseif UNIQUE_SYMBOL == (128911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128912)
		#define UNIQUE_FUNCTION<%0...%1> %0UTF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128913)
		#define UNIQUE_FUNCTION<%0...%1> %0UTG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128914)
		#define UNIQUE_FUNCTION<%0...%1> %0UTH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128915)
		#define UNIQUE_FUNCTION<%0...%1> %0UTI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128916)
		#define UNIQUE_FUNCTION<%0...%1> %0UTJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128917)
		#define UNIQUE_FUNCTION<%0...%1> %0UTK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128918)
		#define UNIQUE_FUNCTION<%0...%1> %0UTL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128919)
		#define UNIQUE_FUNCTION<%0...%1> %0UTM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128927)
	#elseif UNIQUE_SYMBOL == (128919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128920)
		#define UNIQUE_FUNCTION<%0...%1> %0UTN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128921)
		#define UNIQUE_FUNCTION<%0...%1> %0UTO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128922)
		#define UNIQUE_FUNCTION<%0...%1> %0UTP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128923)
		#define UNIQUE_FUNCTION<%0...%1> %0UTQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128924)
		#define UNIQUE_FUNCTION<%0...%1> %0UTR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128925)
		#define UNIQUE_FUNCTION<%0...%1> %0UTS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128926)
		#define UNIQUE_FUNCTION<%0...%1> %0UTT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128927)
		#define UNIQUE_FUNCTION<%0...%1> %0UTU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128935)
	#elseif UNIQUE_SYMBOL == (128927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128928)
		#define UNIQUE_FUNCTION<%0...%1> %0UTV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128929)
		#define UNIQUE_FUNCTION<%0...%1> %0UTW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128930)
		#define UNIQUE_FUNCTION<%0...%1> %0UTX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128931)
		#define UNIQUE_FUNCTION<%0...%1> %0UTY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128932)
		#define UNIQUE_FUNCTION<%0...%1> %0UTZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128933)
		#define UNIQUE_FUNCTION<%0...%1> %0UT_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128934)
		#define UNIQUE_FUNCTION<%0...%1> %0UTa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128935)
		#define UNIQUE_FUNCTION<%0...%1> %0UTb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128943)
	#elseif UNIQUE_SYMBOL == (128935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128936)
		#define UNIQUE_FUNCTION<%0...%1> %0UTc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128937)
		#define UNIQUE_FUNCTION<%0...%1> %0UTd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128938)
		#define UNIQUE_FUNCTION<%0...%1> %0UTe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128939)
		#define UNIQUE_FUNCTION<%0...%1> %0UTf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128940)
		#define UNIQUE_FUNCTION<%0...%1> %0UTg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128941)
		#define UNIQUE_FUNCTION<%0...%1> %0UTh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128942)
		#define UNIQUE_FUNCTION<%0...%1> %0UTi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128943)
		#define UNIQUE_FUNCTION<%0...%1> %0UTj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (128951)
	#elseif UNIQUE_SYMBOL == (128943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128944)
		#define UNIQUE_FUNCTION<%0...%1> %0UTk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128945)
		#define UNIQUE_FUNCTION<%0...%1> %0UTl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128946)
		#define UNIQUE_FUNCTION<%0...%1> %0UTm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128947)
		#define UNIQUE_FUNCTION<%0...%1> %0UTn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128948)
		#define UNIQUE_FUNCTION<%0...%1> %0UTo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128949)
		#define UNIQUE_FUNCTION<%0...%1> %0UTp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128950)
		#define UNIQUE_FUNCTION<%0...%1> %0UTq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128951)
		#define UNIQUE_FUNCTION<%0...%1> %0UTr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (128951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128952)
		#define UNIQUE_FUNCTION<%0...%1> %0UTs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128953)
		#define UNIQUE_FUNCTION<%0...%1> %0UTt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128954)
		#define UNIQUE_FUNCTION<%0...%1> %0UTu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128955)
		#define UNIQUE_FUNCTION<%0...%1> %0UTv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128956)
		#define UNIQUE_FUNCTION<%0...%1> %0UTw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128957)
		#define UNIQUE_FUNCTION<%0...%1> %0UTx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (128957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128958)
		#define UNIQUE_FUNCTION<%0...%1> %0UTy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (128959)
		#define UNIQUE_FUNCTION<%0...%1> %0UTz%1
		#endinput
	#endif
#endif
