static stock const Y_UNIQUE_130880_130943_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_130880_130943
	#undef _inc_y_unique_130880_130943
#endif

#if UNIQUE_SYMBOL < (130887)
	#if UNIQUE_SYMBOL == (130879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130880)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux0%1
		#endinput
	#if UNIQUE_SYMBOL == (130880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130881)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux1%1
		#endinput
	#if UNIQUE_SYMBOL == (130881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130882)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux2%1
		#endinput
	#if UNIQUE_SYMBOL == (130882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130883)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux3%1
		#endinput
	#if UNIQUE_SYMBOL == (130883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130884)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux4%1
		#endinput
	#if UNIQUE_SYMBOL == (130884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130885)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux5%1
		#endinput
	#if UNIQUE_SYMBOL == (130885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130886)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130887)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130895)
	#elseif UNIQUE_SYMBOL == (130887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130888)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130889)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130890)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130891)
		#define UNIQUE_FUNCTION<%0...%1> %0UxA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130892)
		#define UNIQUE_FUNCTION<%0...%1> %0UxB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130893)
		#define UNIQUE_FUNCTION<%0...%1> %0UxC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130894)
		#define UNIQUE_FUNCTION<%0...%1> %0UxD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130895)
		#define UNIQUE_FUNCTION<%0...%1> %0UxE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130903)
	#elseif UNIQUE_SYMBOL == (130895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130896)
		#define UNIQUE_FUNCTION<%0...%1> %0UxF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130897)
		#define UNIQUE_FUNCTION<%0...%1> %0UxG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130898)
		#define UNIQUE_FUNCTION<%0...%1> %0UxH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130899)
		#define UNIQUE_FUNCTION<%0...%1> %0UxI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130900)
		#define UNIQUE_FUNCTION<%0...%1> %0UxJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130901)
		#define UNIQUE_FUNCTION<%0...%1> %0UxK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130902)
		#define UNIQUE_FUNCTION<%0...%1> %0UxL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130903)
		#define UNIQUE_FUNCTION<%0...%1> %0UxM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130911)
	#elseif UNIQUE_SYMBOL == (130903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130904)
		#define UNIQUE_FUNCTION<%0...%1> %0UxN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130905)
		#define UNIQUE_FUNCTION<%0...%1> %0UxO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130906)
		#define UNIQUE_FUNCTION<%0...%1> %0UxP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130907)
		#define UNIQUE_FUNCTION<%0...%1> %0UxQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130908)
		#define UNIQUE_FUNCTION<%0...%1> %0UxR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130909)
		#define UNIQUE_FUNCTION<%0...%1> %0UxS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130910)
		#define UNIQUE_FUNCTION<%0...%1> %0UxT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130911)
		#define UNIQUE_FUNCTION<%0...%1> %0UxU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130919)
	#elseif UNIQUE_SYMBOL == (130911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130912)
		#define UNIQUE_FUNCTION<%0...%1> %0UxV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130913)
		#define UNIQUE_FUNCTION<%0...%1> %0UxW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130914)
		#define UNIQUE_FUNCTION<%0...%1> %0UxX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130915)
		#define UNIQUE_FUNCTION<%0...%1> %0UxY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130916)
		#define UNIQUE_FUNCTION<%0...%1> %0UxZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130917)
		#define UNIQUE_FUNCTION<%0...%1> %0Ux_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130918)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130919)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130927)
	#elseif UNIQUE_SYMBOL == (130919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130920)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130921)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130922)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130923)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130924)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130925)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130926)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130927)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130935)
	#elseif UNIQUE_SYMBOL == (130927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130928)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130929)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130930)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130931)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130932)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130933)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130934)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130935)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (130935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130936)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130937)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130938)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130939)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130940)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130941)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130942)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130943)
		#define UNIQUE_FUNCTION<%0...%1> %0Uxz%1
		#endinput
	#endif
#endif
