static stock const Y_UNIQUE_030912_030975_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_030912_030975
	#undef _inc_y_unique_030912_030975
#endif

#if UNIQUE_SYMBOL < (30919)
	#if UNIQUE_SYMBOL == (30911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30912)
		#define UNIQUE_FUNCTION<%0...%1> %07Y0%1
		#endinput
	#if UNIQUE_SYMBOL == (30912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30913)
		#define UNIQUE_FUNCTION<%0...%1> %07Y1%1
		#endinput
	#if UNIQUE_SYMBOL == (30913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30914)
		#define UNIQUE_FUNCTION<%0...%1> %07Y2%1
		#endinput
	#if UNIQUE_SYMBOL == (30914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30915)
		#define UNIQUE_FUNCTION<%0...%1> %07Y3%1
		#endinput
	#if UNIQUE_SYMBOL == (30915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30916)
		#define UNIQUE_FUNCTION<%0...%1> %07Y4%1
		#endinput
	#if UNIQUE_SYMBOL == (30916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30917)
		#define UNIQUE_FUNCTION<%0...%1> %07Y5%1
		#endinput
	#if UNIQUE_SYMBOL == (30917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30918)
		#define UNIQUE_FUNCTION<%0...%1> %07Y6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30919)
		#define UNIQUE_FUNCTION<%0...%1> %07Y7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30927)
	#elseif UNIQUE_SYMBOL == (30919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30920)
		#define UNIQUE_FUNCTION<%0...%1> %07Y8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30921)
		#define UNIQUE_FUNCTION<%0...%1> %07Y9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30922)
		#define UNIQUE_FUNCTION<%0...%1> %07Y@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30923)
		#define UNIQUE_FUNCTION<%0...%1> %07YA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30924)
		#define UNIQUE_FUNCTION<%0...%1> %07YB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30925)
		#define UNIQUE_FUNCTION<%0...%1> %07YC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30926)
		#define UNIQUE_FUNCTION<%0...%1> %07YD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30927)
		#define UNIQUE_FUNCTION<%0...%1> %07YE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30935)
	#elseif UNIQUE_SYMBOL == (30927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30928)
		#define UNIQUE_FUNCTION<%0...%1> %07YF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30929)
		#define UNIQUE_FUNCTION<%0...%1> %07YG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30930)
		#define UNIQUE_FUNCTION<%0...%1> %07YH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30931)
		#define UNIQUE_FUNCTION<%0...%1> %07YI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30932)
		#define UNIQUE_FUNCTION<%0...%1> %07YJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30933)
		#define UNIQUE_FUNCTION<%0...%1> %07YK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30934)
		#define UNIQUE_FUNCTION<%0...%1> %07YL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30935)
		#define UNIQUE_FUNCTION<%0...%1> %07YM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30943)
	#elseif UNIQUE_SYMBOL == (30935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30936)
		#define UNIQUE_FUNCTION<%0...%1> %07YN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30937)
		#define UNIQUE_FUNCTION<%0...%1> %07YO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30938)
		#define UNIQUE_FUNCTION<%0...%1> %07YP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30939)
		#define UNIQUE_FUNCTION<%0...%1> %07YQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30940)
		#define UNIQUE_FUNCTION<%0...%1> %07YR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30941)
		#define UNIQUE_FUNCTION<%0...%1> %07YS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30942)
		#define UNIQUE_FUNCTION<%0...%1> %07YT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30943)
		#define UNIQUE_FUNCTION<%0...%1> %07YU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30951)
	#elseif UNIQUE_SYMBOL == (30943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30944)
		#define UNIQUE_FUNCTION<%0...%1> %07YV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30945)
		#define UNIQUE_FUNCTION<%0...%1> %07YW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30946)
		#define UNIQUE_FUNCTION<%0...%1> %07YX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30947)
		#define UNIQUE_FUNCTION<%0...%1> %07YY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30948)
		#define UNIQUE_FUNCTION<%0...%1> %07YZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30949)
		#define UNIQUE_FUNCTION<%0...%1> %07Y_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30950)
		#define UNIQUE_FUNCTION<%0...%1> %07Ya%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30951)
		#define UNIQUE_FUNCTION<%0...%1> %07Yb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30959)
	#elseif UNIQUE_SYMBOL == (30951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30952)
		#define UNIQUE_FUNCTION<%0...%1> %07Yc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30953)
		#define UNIQUE_FUNCTION<%0...%1> %07Yd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30954)
		#define UNIQUE_FUNCTION<%0...%1> %07Ye%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30955)
		#define UNIQUE_FUNCTION<%0...%1> %07Yf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30956)
		#define UNIQUE_FUNCTION<%0...%1> %07Yg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30957)
		#define UNIQUE_FUNCTION<%0...%1> %07Yh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30958)
		#define UNIQUE_FUNCTION<%0...%1> %07Yi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30959)
		#define UNIQUE_FUNCTION<%0...%1> %07Yj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30967)
	#elseif UNIQUE_SYMBOL == (30959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30960)
		#define UNIQUE_FUNCTION<%0...%1> %07Yk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30961)
		#define UNIQUE_FUNCTION<%0...%1> %07Yl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30962)
		#define UNIQUE_FUNCTION<%0...%1> %07Ym%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30963)
		#define UNIQUE_FUNCTION<%0...%1> %07Yn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30964)
		#define UNIQUE_FUNCTION<%0...%1> %07Yo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30965)
		#define UNIQUE_FUNCTION<%0...%1> %07Yp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30966)
		#define UNIQUE_FUNCTION<%0...%1> %07Yq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30967)
		#define UNIQUE_FUNCTION<%0...%1> %07Yr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (30967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30968)
		#define UNIQUE_FUNCTION<%0...%1> %07Ys%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30969)
		#define UNIQUE_FUNCTION<%0...%1> %07Yt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30970)
		#define UNIQUE_FUNCTION<%0...%1> %07Yu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30971)
		#define UNIQUE_FUNCTION<%0...%1> %07Yv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30972)
		#define UNIQUE_FUNCTION<%0...%1> %07Yw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30973)
		#define UNIQUE_FUNCTION<%0...%1> %07Yx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30974)
		#define UNIQUE_FUNCTION<%0...%1> %07Yy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30975)
		#define UNIQUE_FUNCTION<%0...%1> %07Yz%1
		#endinput
	#endif
#endif
