static stock const Y_UNIQUE_123392_123455_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_123392_123455
	#undef _inc_y_unique_123392_123455
#endif

#if UNIQUE_SYMBOL < (123399)
	#if UNIQUE_SYMBOL == (123391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123392)
		#define UNIQUE_FUNCTION<%0...%1> %0T80%1
		#endinput
	#if UNIQUE_SYMBOL == (123392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123393)
		#define UNIQUE_FUNCTION<%0...%1> %0T81%1
		#endinput
	#if UNIQUE_SYMBOL == (123393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123394)
		#define UNIQUE_FUNCTION<%0...%1> %0T82%1
		#endinput
	#if UNIQUE_SYMBOL == (123394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123395)
		#define UNIQUE_FUNCTION<%0...%1> %0T83%1
		#endinput
	#if UNIQUE_SYMBOL == (123395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123396)
		#define UNIQUE_FUNCTION<%0...%1> %0T84%1
		#endinput
	#if UNIQUE_SYMBOL == (123396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123397)
		#define UNIQUE_FUNCTION<%0...%1> %0T85%1
		#endinput
	#if UNIQUE_SYMBOL == (123397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123398)
		#define UNIQUE_FUNCTION<%0...%1> %0T86%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123399)
		#define UNIQUE_FUNCTION<%0...%1> %0T87%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123407)
	#elseif UNIQUE_SYMBOL == (123399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123400)
		#define UNIQUE_FUNCTION<%0...%1> %0T88%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123401)
		#define UNIQUE_FUNCTION<%0...%1> %0T89%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123402)
		#define UNIQUE_FUNCTION<%0...%1> %0T8@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123403)
		#define UNIQUE_FUNCTION<%0...%1> %0T8A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123404)
		#define UNIQUE_FUNCTION<%0...%1> %0T8B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123405)
		#define UNIQUE_FUNCTION<%0...%1> %0T8C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123406)
		#define UNIQUE_FUNCTION<%0...%1> %0T8D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123407)
		#define UNIQUE_FUNCTION<%0...%1> %0T8E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123415)
	#elseif UNIQUE_SYMBOL == (123407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123408)
		#define UNIQUE_FUNCTION<%0...%1> %0T8F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123409)
		#define UNIQUE_FUNCTION<%0...%1> %0T8G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123410)
		#define UNIQUE_FUNCTION<%0...%1> %0T8H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123411)
		#define UNIQUE_FUNCTION<%0...%1> %0T8I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123412)
		#define UNIQUE_FUNCTION<%0...%1> %0T8J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123413)
		#define UNIQUE_FUNCTION<%0...%1> %0T8K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123414)
		#define UNIQUE_FUNCTION<%0...%1> %0T8L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123415)
		#define UNIQUE_FUNCTION<%0...%1> %0T8M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123423)
	#elseif UNIQUE_SYMBOL == (123415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123416)
		#define UNIQUE_FUNCTION<%0...%1> %0T8N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123417)
		#define UNIQUE_FUNCTION<%0...%1> %0T8O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123418)
		#define UNIQUE_FUNCTION<%0...%1> %0T8P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123419)
		#define UNIQUE_FUNCTION<%0...%1> %0T8Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123420)
		#define UNIQUE_FUNCTION<%0...%1> %0T8R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123421)
		#define UNIQUE_FUNCTION<%0...%1> %0T8S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123422)
		#define UNIQUE_FUNCTION<%0...%1> %0T8T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123423)
		#define UNIQUE_FUNCTION<%0...%1> %0T8U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123431)
	#elseif UNIQUE_SYMBOL == (123423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123424)
		#define UNIQUE_FUNCTION<%0...%1> %0T8V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123425)
		#define UNIQUE_FUNCTION<%0...%1> %0T8W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123426)
		#define UNIQUE_FUNCTION<%0...%1> %0T8X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123427)
		#define UNIQUE_FUNCTION<%0...%1> %0T8Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123428)
		#define UNIQUE_FUNCTION<%0...%1> %0T8Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123429)
		#define UNIQUE_FUNCTION<%0...%1> %0T8_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123430)
		#define UNIQUE_FUNCTION<%0...%1> %0T8a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123431)
		#define UNIQUE_FUNCTION<%0...%1> %0T8b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123439)
	#elseif UNIQUE_SYMBOL == (123431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123432)
		#define UNIQUE_FUNCTION<%0...%1> %0T8c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123433)
		#define UNIQUE_FUNCTION<%0...%1> %0T8d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123434)
		#define UNIQUE_FUNCTION<%0...%1> %0T8e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123435)
		#define UNIQUE_FUNCTION<%0...%1> %0T8f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123436)
		#define UNIQUE_FUNCTION<%0...%1> %0T8g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123437)
		#define UNIQUE_FUNCTION<%0...%1> %0T8h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123438)
		#define UNIQUE_FUNCTION<%0...%1> %0T8i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123439)
		#define UNIQUE_FUNCTION<%0...%1> %0T8j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (123447)
	#elseif UNIQUE_SYMBOL == (123439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123440)
		#define UNIQUE_FUNCTION<%0...%1> %0T8k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123441)
		#define UNIQUE_FUNCTION<%0...%1> %0T8l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123442)
		#define UNIQUE_FUNCTION<%0...%1> %0T8m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123443)
		#define UNIQUE_FUNCTION<%0...%1> %0T8n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123444)
		#define UNIQUE_FUNCTION<%0...%1> %0T8o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123445)
		#define UNIQUE_FUNCTION<%0...%1> %0T8p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123446)
		#define UNIQUE_FUNCTION<%0...%1> %0T8q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123447)
		#define UNIQUE_FUNCTION<%0...%1> %0T8r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (123447)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123448)
		#define UNIQUE_FUNCTION<%0...%1> %0T8s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123448)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123449)
		#define UNIQUE_FUNCTION<%0...%1> %0T8t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123449)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123450)
		#define UNIQUE_FUNCTION<%0...%1> %0T8u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123450)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123451)
		#define UNIQUE_FUNCTION<%0...%1> %0T8v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123451)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123452)
		#define UNIQUE_FUNCTION<%0...%1> %0T8w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123452)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123453)
		#define UNIQUE_FUNCTION<%0...%1> %0T8x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (123453)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123454)
		#define UNIQUE_FUNCTION<%0...%1> %0T8y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (123455)
		#define UNIQUE_FUNCTION<%0...%1> %0T8z%1
		#endinput
	#endif
#endif
