static stock const Y_UNIQUE_082624_082687_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_082624_082687
	#undef _inc_y_unique_082624_082687
#endif

#if UNIQUE_SYMBOL < (82631)
	#if UNIQUE_SYMBOL == (82623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82624)
		#define UNIQUE_FUNCTION<%0...%1> %0JA0%1
		#endinput
	#if UNIQUE_SYMBOL == (82624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82625)
		#define UNIQUE_FUNCTION<%0...%1> %0JA1%1
		#endinput
	#if UNIQUE_SYMBOL == (82625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82626)
		#define UNIQUE_FUNCTION<%0...%1> %0JA2%1
		#endinput
	#if UNIQUE_SYMBOL == (82626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82627)
		#define UNIQUE_FUNCTION<%0...%1> %0JA3%1
		#endinput
	#if UNIQUE_SYMBOL == (82627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82628)
		#define UNIQUE_FUNCTION<%0...%1> %0JA4%1
		#endinput
	#if UNIQUE_SYMBOL == (82628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82629)
		#define UNIQUE_FUNCTION<%0...%1> %0JA5%1
		#endinput
	#if UNIQUE_SYMBOL == (82629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82630)
		#define UNIQUE_FUNCTION<%0...%1> %0JA6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82631)
		#define UNIQUE_FUNCTION<%0...%1> %0JA7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (82639)
	#elseif UNIQUE_SYMBOL == (82631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82632)
		#define UNIQUE_FUNCTION<%0...%1> %0JA8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82633)
		#define UNIQUE_FUNCTION<%0...%1> %0JA9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82634)
		#define UNIQUE_FUNCTION<%0...%1> %0JA@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82635)
		#define UNIQUE_FUNCTION<%0...%1> %0JAA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82636)
		#define UNIQUE_FUNCTION<%0...%1> %0JAB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82637)
		#define UNIQUE_FUNCTION<%0...%1> %0JAC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82638)
		#define UNIQUE_FUNCTION<%0...%1> %0JAD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82639)
		#define UNIQUE_FUNCTION<%0...%1> %0JAE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (82647)
	#elseif UNIQUE_SYMBOL == (82639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82640)
		#define UNIQUE_FUNCTION<%0...%1> %0JAF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82641)
		#define UNIQUE_FUNCTION<%0...%1> %0JAG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82642)
		#define UNIQUE_FUNCTION<%0...%1> %0JAH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82643)
		#define UNIQUE_FUNCTION<%0...%1> %0JAI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82644)
		#define UNIQUE_FUNCTION<%0...%1> %0JAJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82645)
		#define UNIQUE_FUNCTION<%0...%1> %0JAK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82646)
		#define UNIQUE_FUNCTION<%0...%1> %0JAL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82647)
		#define UNIQUE_FUNCTION<%0...%1> %0JAM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (82655)
	#elseif UNIQUE_SYMBOL == (82647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82648)
		#define UNIQUE_FUNCTION<%0...%1> %0JAN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82649)
		#define UNIQUE_FUNCTION<%0...%1> %0JAO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82650)
		#define UNIQUE_FUNCTION<%0...%1> %0JAP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82651)
		#define UNIQUE_FUNCTION<%0...%1> %0JAQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82652)
		#define UNIQUE_FUNCTION<%0...%1> %0JAR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82653)
		#define UNIQUE_FUNCTION<%0...%1> %0JAS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82654)
		#define UNIQUE_FUNCTION<%0...%1> %0JAT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82655)
		#define UNIQUE_FUNCTION<%0...%1> %0JAU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (82663)
	#elseif UNIQUE_SYMBOL == (82655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82656)
		#define UNIQUE_FUNCTION<%0...%1> %0JAV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82657)
		#define UNIQUE_FUNCTION<%0...%1> %0JAW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82658)
		#define UNIQUE_FUNCTION<%0...%1> %0JAX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82659)
		#define UNIQUE_FUNCTION<%0...%1> %0JAY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82660)
		#define UNIQUE_FUNCTION<%0...%1> %0JAZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82661)
		#define UNIQUE_FUNCTION<%0...%1> %0JA_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82662)
		#define UNIQUE_FUNCTION<%0...%1> %0JAa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82663)
		#define UNIQUE_FUNCTION<%0...%1> %0JAb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (82671)
	#elseif UNIQUE_SYMBOL == (82663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82664)
		#define UNIQUE_FUNCTION<%0...%1> %0JAc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82665)
		#define UNIQUE_FUNCTION<%0...%1> %0JAd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82666)
		#define UNIQUE_FUNCTION<%0...%1> %0JAe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82667)
		#define UNIQUE_FUNCTION<%0...%1> %0JAf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82668)
		#define UNIQUE_FUNCTION<%0...%1> %0JAg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82669)
		#define UNIQUE_FUNCTION<%0...%1> %0JAh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82670)
		#define UNIQUE_FUNCTION<%0...%1> %0JAi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82671)
		#define UNIQUE_FUNCTION<%0...%1> %0JAj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (82679)
	#elseif UNIQUE_SYMBOL == (82671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82672)
		#define UNIQUE_FUNCTION<%0...%1> %0JAk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82673)
		#define UNIQUE_FUNCTION<%0...%1> %0JAl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82674)
		#define UNIQUE_FUNCTION<%0...%1> %0JAm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82675)
		#define UNIQUE_FUNCTION<%0...%1> %0JAn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82676)
		#define UNIQUE_FUNCTION<%0...%1> %0JAo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82677)
		#define UNIQUE_FUNCTION<%0...%1> %0JAp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82678)
		#define UNIQUE_FUNCTION<%0...%1> %0JAq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82679)
		#define UNIQUE_FUNCTION<%0...%1> %0JAr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (82679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82680)
		#define UNIQUE_FUNCTION<%0...%1> %0JAs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82681)
		#define UNIQUE_FUNCTION<%0...%1> %0JAt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82682)
		#define UNIQUE_FUNCTION<%0...%1> %0JAu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82683)
		#define UNIQUE_FUNCTION<%0...%1> %0JAv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82684)
		#define UNIQUE_FUNCTION<%0...%1> %0JAw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82685)
		#define UNIQUE_FUNCTION<%0...%1> %0JAx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (82685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82686)
		#define UNIQUE_FUNCTION<%0...%1> %0JAy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (82687)
		#define UNIQUE_FUNCTION<%0...%1> %0JAz%1
		#endinput
	#endif
#endif
