static stock const Y_UNIQUE_106688_106751_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_106688_106751
	#undef _inc_y_unique_106688_106751
#endif

#if UNIQUE_SYMBOL < (106695)
	#if UNIQUE_SYMBOL == (106687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106688)
		#define UNIQUE_FUNCTION<%0...%1> %0P30%1
		#endinput
	#if UNIQUE_SYMBOL == (106688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106689)
		#define UNIQUE_FUNCTION<%0...%1> %0P31%1
		#endinput
	#if UNIQUE_SYMBOL == (106689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106690)
		#define UNIQUE_FUNCTION<%0...%1> %0P32%1
		#endinput
	#if UNIQUE_SYMBOL == (106690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106691)
		#define UNIQUE_FUNCTION<%0...%1> %0P33%1
		#endinput
	#if UNIQUE_SYMBOL == (106691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106692)
		#define UNIQUE_FUNCTION<%0...%1> %0P34%1
		#endinput
	#if UNIQUE_SYMBOL == (106692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106693)
		#define UNIQUE_FUNCTION<%0...%1> %0P35%1
		#endinput
	#if UNIQUE_SYMBOL == (106693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106694)
		#define UNIQUE_FUNCTION<%0...%1> %0P36%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106695)
		#define UNIQUE_FUNCTION<%0...%1> %0P37%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (106703)
	#elseif UNIQUE_SYMBOL == (106695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106696)
		#define UNIQUE_FUNCTION<%0...%1> %0P38%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106697)
		#define UNIQUE_FUNCTION<%0...%1> %0P39%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106698)
		#define UNIQUE_FUNCTION<%0...%1> %0P3@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106699)
		#define UNIQUE_FUNCTION<%0...%1> %0P3A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106700)
		#define UNIQUE_FUNCTION<%0...%1> %0P3B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106701)
		#define UNIQUE_FUNCTION<%0...%1> %0P3C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106702)
		#define UNIQUE_FUNCTION<%0...%1> %0P3D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106703)
		#define UNIQUE_FUNCTION<%0...%1> %0P3E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (106711)
	#elseif UNIQUE_SYMBOL == (106703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106704)
		#define UNIQUE_FUNCTION<%0...%1> %0P3F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106705)
		#define UNIQUE_FUNCTION<%0...%1> %0P3G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106706)
		#define UNIQUE_FUNCTION<%0...%1> %0P3H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106707)
		#define UNIQUE_FUNCTION<%0...%1> %0P3I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106708)
		#define UNIQUE_FUNCTION<%0...%1> %0P3J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106709)
		#define UNIQUE_FUNCTION<%0...%1> %0P3K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106710)
		#define UNIQUE_FUNCTION<%0...%1> %0P3L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106711)
		#define UNIQUE_FUNCTION<%0...%1> %0P3M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (106719)
	#elseif UNIQUE_SYMBOL == (106711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106712)
		#define UNIQUE_FUNCTION<%0...%1> %0P3N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106713)
		#define UNIQUE_FUNCTION<%0...%1> %0P3O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106714)
		#define UNIQUE_FUNCTION<%0...%1> %0P3P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106715)
		#define UNIQUE_FUNCTION<%0...%1> %0P3Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106716)
		#define UNIQUE_FUNCTION<%0...%1> %0P3R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106717)
		#define UNIQUE_FUNCTION<%0...%1> %0P3S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106718)
		#define UNIQUE_FUNCTION<%0...%1> %0P3T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106719)
		#define UNIQUE_FUNCTION<%0...%1> %0P3U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (106727)
	#elseif UNIQUE_SYMBOL == (106719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106720)
		#define UNIQUE_FUNCTION<%0...%1> %0P3V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106721)
		#define UNIQUE_FUNCTION<%0...%1> %0P3W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106722)
		#define UNIQUE_FUNCTION<%0...%1> %0P3X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106723)
		#define UNIQUE_FUNCTION<%0...%1> %0P3Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106724)
		#define UNIQUE_FUNCTION<%0...%1> %0P3Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106725)
		#define UNIQUE_FUNCTION<%0...%1> %0P3_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106726)
		#define UNIQUE_FUNCTION<%0...%1> %0P3a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106727)
		#define UNIQUE_FUNCTION<%0...%1> %0P3b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (106735)
	#elseif UNIQUE_SYMBOL == (106727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106728)
		#define UNIQUE_FUNCTION<%0...%1> %0P3c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106729)
		#define UNIQUE_FUNCTION<%0...%1> %0P3d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106730)
		#define UNIQUE_FUNCTION<%0...%1> %0P3e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106731)
		#define UNIQUE_FUNCTION<%0...%1> %0P3f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106732)
		#define UNIQUE_FUNCTION<%0...%1> %0P3g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106733)
		#define UNIQUE_FUNCTION<%0...%1> %0P3h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106734)
		#define UNIQUE_FUNCTION<%0...%1> %0P3i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106735)
		#define UNIQUE_FUNCTION<%0...%1> %0P3j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (106743)
	#elseif UNIQUE_SYMBOL == (106735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106736)
		#define UNIQUE_FUNCTION<%0...%1> %0P3k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106737)
		#define UNIQUE_FUNCTION<%0...%1> %0P3l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106738)
		#define UNIQUE_FUNCTION<%0...%1> %0P3m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106739)
		#define UNIQUE_FUNCTION<%0...%1> %0P3n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106740)
		#define UNIQUE_FUNCTION<%0...%1> %0P3o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106741)
		#define UNIQUE_FUNCTION<%0...%1> %0P3p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106742)
		#define UNIQUE_FUNCTION<%0...%1> %0P3q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106743)
		#define UNIQUE_FUNCTION<%0...%1> %0P3r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (106743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106744)
		#define UNIQUE_FUNCTION<%0...%1> %0P3s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106745)
		#define UNIQUE_FUNCTION<%0...%1> %0P3t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106746)
		#define UNIQUE_FUNCTION<%0...%1> %0P3u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106747)
		#define UNIQUE_FUNCTION<%0...%1> %0P3v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106748)
		#define UNIQUE_FUNCTION<%0...%1> %0P3w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106749)
		#define UNIQUE_FUNCTION<%0...%1> %0P3x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (106749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106750)
		#define UNIQUE_FUNCTION<%0...%1> %0P3y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (106751)
		#define UNIQUE_FUNCTION<%0...%1> %0P3z%1
		#endinput
	#endif
#endif
