static stock const Y_UNIQUE_161600_161663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_161600_161663
	#undef _inc_y_unique_161600_161663
#endif

#if UNIQUE_SYMBOL < (161607)
	#if UNIQUE_SYMBOL == (161599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161600)
		#define UNIQUE_FUNCTION<%0...%1> %0bS0%1
		#endinput
	#if UNIQUE_SYMBOL == (161600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161601)
		#define UNIQUE_FUNCTION<%0...%1> %0bS1%1
		#endinput
	#if UNIQUE_SYMBOL == (161601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161602)
		#define UNIQUE_FUNCTION<%0...%1> %0bS2%1
		#endinput
	#if UNIQUE_SYMBOL == (161602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161603)
		#define UNIQUE_FUNCTION<%0...%1> %0bS3%1
		#endinput
	#if UNIQUE_SYMBOL == (161603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161604)
		#define UNIQUE_FUNCTION<%0...%1> %0bS4%1
		#endinput
	#if UNIQUE_SYMBOL == (161604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161605)
		#define UNIQUE_FUNCTION<%0...%1> %0bS5%1
		#endinput
	#if UNIQUE_SYMBOL == (161605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161606)
		#define UNIQUE_FUNCTION<%0...%1> %0bS6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161607)
		#define UNIQUE_FUNCTION<%0...%1> %0bS7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (161615)
	#elseif UNIQUE_SYMBOL == (161607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161608)
		#define UNIQUE_FUNCTION<%0...%1> %0bS8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161609)
		#define UNIQUE_FUNCTION<%0...%1> %0bS9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161610)
		#define UNIQUE_FUNCTION<%0...%1> %0bS@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161611)
		#define UNIQUE_FUNCTION<%0...%1> %0bSA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161612)
		#define UNIQUE_FUNCTION<%0...%1> %0bSB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161613)
		#define UNIQUE_FUNCTION<%0...%1> %0bSC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161614)
		#define UNIQUE_FUNCTION<%0...%1> %0bSD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161615)
		#define UNIQUE_FUNCTION<%0...%1> %0bSE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (161623)
	#elseif UNIQUE_SYMBOL == (161615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161616)
		#define UNIQUE_FUNCTION<%0...%1> %0bSF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161617)
		#define UNIQUE_FUNCTION<%0...%1> %0bSG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161618)
		#define UNIQUE_FUNCTION<%0...%1> %0bSH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161619)
		#define UNIQUE_FUNCTION<%0...%1> %0bSI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161620)
		#define UNIQUE_FUNCTION<%0...%1> %0bSJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161621)
		#define UNIQUE_FUNCTION<%0...%1> %0bSK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161622)
		#define UNIQUE_FUNCTION<%0...%1> %0bSL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161623)
		#define UNIQUE_FUNCTION<%0...%1> %0bSM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (161631)
	#elseif UNIQUE_SYMBOL == (161623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161624)
		#define UNIQUE_FUNCTION<%0...%1> %0bSN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161625)
		#define UNIQUE_FUNCTION<%0...%1> %0bSO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161626)
		#define UNIQUE_FUNCTION<%0...%1> %0bSP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161627)
		#define UNIQUE_FUNCTION<%0...%1> %0bSQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161628)
		#define UNIQUE_FUNCTION<%0...%1> %0bSR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161629)
		#define UNIQUE_FUNCTION<%0...%1> %0bSS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161630)
		#define UNIQUE_FUNCTION<%0...%1> %0bST%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161631)
		#define UNIQUE_FUNCTION<%0...%1> %0bSU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (161639)
	#elseif UNIQUE_SYMBOL == (161631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161632)
		#define UNIQUE_FUNCTION<%0...%1> %0bSV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161633)
		#define UNIQUE_FUNCTION<%0...%1> %0bSW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161634)
		#define UNIQUE_FUNCTION<%0...%1> %0bSX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161635)
		#define UNIQUE_FUNCTION<%0...%1> %0bSY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161636)
		#define UNIQUE_FUNCTION<%0...%1> %0bSZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161637)
		#define UNIQUE_FUNCTION<%0...%1> %0bS_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161638)
		#define UNIQUE_FUNCTION<%0...%1> %0bSa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161639)
		#define UNIQUE_FUNCTION<%0...%1> %0bSb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (161647)
	#elseif UNIQUE_SYMBOL == (161639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161640)
		#define UNIQUE_FUNCTION<%0...%1> %0bSc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161641)
		#define UNIQUE_FUNCTION<%0...%1> %0bSd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161642)
		#define UNIQUE_FUNCTION<%0...%1> %0bSe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161643)
		#define UNIQUE_FUNCTION<%0...%1> %0bSf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161644)
		#define UNIQUE_FUNCTION<%0...%1> %0bSg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161645)
		#define UNIQUE_FUNCTION<%0...%1> %0bSh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161646)
		#define UNIQUE_FUNCTION<%0...%1> %0bSi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161647)
		#define UNIQUE_FUNCTION<%0...%1> %0bSj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (161655)
	#elseif UNIQUE_SYMBOL == (161647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161648)
		#define UNIQUE_FUNCTION<%0...%1> %0bSk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161649)
		#define UNIQUE_FUNCTION<%0...%1> %0bSl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161650)
		#define UNIQUE_FUNCTION<%0...%1> %0bSm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161651)
		#define UNIQUE_FUNCTION<%0...%1> %0bSn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161652)
		#define UNIQUE_FUNCTION<%0...%1> %0bSo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161653)
		#define UNIQUE_FUNCTION<%0...%1> %0bSp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161654)
		#define UNIQUE_FUNCTION<%0...%1> %0bSq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161655)
		#define UNIQUE_FUNCTION<%0...%1> %0bSr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (161655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161656)
		#define UNIQUE_FUNCTION<%0...%1> %0bSs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161657)
		#define UNIQUE_FUNCTION<%0...%1> %0bSt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161658)
		#define UNIQUE_FUNCTION<%0...%1> %0bSu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161659)
		#define UNIQUE_FUNCTION<%0...%1> %0bSv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161660)
		#define UNIQUE_FUNCTION<%0...%1> %0bSw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161661)
		#define UNIQUE_FUNCTION<%0...%1> %0bSx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (161661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161662)
		#define UNIQUE_FUNCTION<%0...%1> %0bSy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (161663)
		#define UNIQUE_FUNCTION<%0...%1> %0bSz%1
		#endinput
	#endif
#endif
