static stock const Y_UNIQUE_087616_087679_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_087616_087679
	#undef _inc_y_unique_087616_087679
#endif

#if UNIQUE_SYMBOL < (87623)
	#if UNIQUE_SYMBOL == (87615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87616)
		#define UNIQUE_FUNCTION<%0...%1> %0KO0%1
		#endinput
	#if UNIQUE_SYMBOL == (87616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87617)
		#define UNIQUE_FUNCTION<%0...%1> %0KO1%1
		#endinput
	#if UNIQUE_SYMBOL == (87617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87618)
		#define UNIQUE_FUNCTION<%0...%1> %0KO2%1
		#endinput
	#if UNIQUE_SYMBOL == (87618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87619)
		#define UNIQUE_FUNCTION<%0...%1> %0KO3%1
		#endinput
	#if UNIQUE_SYMBOL == (87619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87620)
		#define UNIQUE_FUNCTION<%0...%1> %0KO4%1
		#endinput
	#if UNIQUE_SYMBOL == (87620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87621)
		#define UNIQUE_FUNCTION<%0...%1> %0KO5%1
		#endinput
	#if UNIQUE_SYMBOL == (87621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87622)
		#define UNIQUE_FUNCTION<%0...%1> %0KO6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87623)
		#define UNIQUE_FUNCTION<%0...%1> %0KO7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87631)
	#elseif UNIQUE_SYMBOL == (87623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87624)
		#define UNIQUE_FUNCTION<%0...%1> %0KO8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87625)
		#define UNIQUE_FUNCTION<%0...%1> %0KO9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87626)
		#define UNIQUE_FUNCTION<%0...%1> %0KO@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87627)
		#define UNIQUE_FUNCTION<%0...%1> %0KOA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87628)
		#define UNIQUE_FUNCTION<%0...%1> %0KOB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87629)
		#define UNIQUE_FUNCTION<%0...%1> %0KOC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87630)
		#define UNIQUE_FUNCTION<%0...%1> %0KOD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87631)
		#define UNIQUE_FUNCTION<%0...%1> %0KOE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87639)
	#elseif UNIQUE_SYMBOL == (87631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87632)
		#define UNIQUE_FUNCTION<%0...%1> %0KOF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87633)
		#define UNIQUE_FUNCTION<%0...%1> %0KOG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87634)
		#define UNIQUE_FUNCTION<%0...%1> %0KOH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87635)
		#define UNIQUE_FUNCTION<%0...%1> %0KOI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87636)
		#define UNIQUE_FUNCTION<%0...%1> %0KOJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87637)
		#define UNIQUE_FUNCTION<%0...%1> %0KOK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87638)
		#define UNIQUE_FUNCTION<%0...%1> %0KOL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87639)
		#define UNIQUE_FUNCTION<%0...%1> %0KOM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87647)
	#elseif UNIQUE_SYMBOL == (87639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87640)
		#define UNIQUE_FUNCTION<%0...%1> %0KON%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87641)
		#define UNIQUE_FUNCTION<%0...%1> %0KOO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87642)
		#define UNIQUE_FUNCTION<%0...%1> %0KOP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87643)
		#define UNIQUE_FUNCTION<%0...%1> %0KOQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87644)
		#define UNIQUE_FUNCTION<%0...%1> %0KOR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87645)
		#define UNIQUE_FUNCTION<%0...%1> %0KOS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87646)
		#define UNIQUE_FUNCTION<%0...%1> %0KOT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87647)
		#define UNIQUE_FUNCTION<%0...%1> %0KOU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87655)
	#elseif UNIQUE_SYMBOL == (87647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87648)
		#define UNIQUE_FUNCTION<%0...%1> %0KOV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87649)
		#define UNIQUE_FUNCTION<%0...%1> %0KOW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87650)
		#define UNIQUE_FUNCTION<%0...%1> %0KOX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87651)
		#define UNIQUE_FUNCTION<%0...%1> %0KOY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87652)
		#define UNIQUE_FUNCTION<%0...%1> %0KOZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87653)
		#define UNIQUE_FUNCTION<%0...%1> %0KO_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87654)
		#define UNIQUE_FUNCTION<%0...%1> %0KOa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87655)
		#define UNIQUE_FUNCTION<%0...%1> %0KOb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87663)
	#elseif UNIQUE_SYMBOL == (87655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87656)
		#define UNIQUE_FUNCTION<%0...%1> %0KOc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87657)
		#define UNIQUE_FUNCTION<%0...%1> %0KOd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87658)
		#define UNIQUE_FUNCTION<%0...%1> %0KOe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87659)
		#define UNIQUE_FUNCTION<%0...%1> %0KOf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87660)
		#define UNIQUE_FUNCTION<%0...%1> %0KOg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87661)
		#define UNIQUE_FUNCTION<%0...%1> %0KOh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87662)
		#define UNIQUE_FUNCTION<%0...%1> %0KOi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87663)
		#define UNIQUE_FUNCTION<%0...%1> %0KOj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (87671)
	#elseif UNIQUE_SYMBOL == (87663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87664)
		#define UNIQUE_FUNCTION<%0...%1> %0KOk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87665)
		#define UNIQUE_FUNCTION<%0...%1> %0KOl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87666)
		#define UNIQUE_FUNCTION<%0...%1> %0KOm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87667)
		#define UNIQUE_FUNCTION<%0...%1> %0KOn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87668)
		#define UNIQUE_FUNCTION<%0...%1> %0KOo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87669)
		#define UNIQUE_FUNCTION<%0...%1> %0KOp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87670)
		#define UNIQUE_FUNCTION<%0...%1> %0KOq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87671)
		#define UNIQUE_FUNCTION<%0...%1> %0KOr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (87671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87672)
		#define UNIQUE_FUNCTION<%0...%1> %0KOs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87673)
		#define UNIQUE_FUNCTION<%0...%1> %0KOt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87674)
		#define UNIQUE_FUNCTION<%0...%1> %0KOu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87675)
		#define UNIQUE_FUNCTION<%0...%1> %0KOv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87676)
		#define UNIQUE_FUNCTION<%0...%1> %0KOw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87677)
		#define UNIQUE_FUNCTION<%0...%1> %0KOx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (87677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87678)
		#define UNIQUE_FUNCTION<%0...%1> %0KOy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (87679)
		#define UNIQUE_FUNCTION<%0...%1> %0KOz%1
		#endinput
	#endif
#endif
