static stock const Y_UNIQUE_003072_003135_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_003072_003135
	#undef _inc_y_unique_003072_003135
#endif

#if UNIQUE_SYMBOL < (3079)
	#if UNIQUE_SYMBOL == (3071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3072)
		#define UNIQUE_FUNCTION<%0...%1> %00k0%1
		#endinput
	#if UNIQUE_SYMBOL == (3072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3073)
		#define UNIQUE_FUNCTION<%0...%1> %00k1%1
		#endinput
	#if UNIQUE_SYMBOL == (3073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3074)
		#define UNIQUE_FUNCTION<%0...%1> %00k2%1
		#endinput
	#if UNIQUE_SYMBOL == (3074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3075)
		#define UNIQUE_FUNCTION<%0...%1> %00k3%1
		#endinput
	#if UNIQUE_SYMBOL == (3075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3076)
		#define UNIQUE_FUNCTION<%0...%1> %00k4%1
		#endinput
	#if UNIQUE_SYMBOL == (3076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3077)
		#define UNIQUE_FUNCTION<%0...%1> %00k5%1
		#endinput
	#if UNIQUE_SYMBOL == (3077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3078)
		#define UNIQUE_FUNCTION<%0...%1> %00k6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3079)
		#define UNIQUE_FUNCTION<%0...%1> %00k7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3087)
	#elseif UNIQUE_SYMBOL == (3079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3080)
		#define UNIQUE_FUNCTION<%0...%1> %00k8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3081)
		#define UNIQUE_FUNCTION<%0...%1> %00k9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3082)
		#define UNIQUE_FUNCTION<%0...%1> %00k@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3083)
		#define UNIQUE_FUNCTION<%0...%1> %00kA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3084)
		#define UNIQUE_FUNCTION<%0...%1> %00kB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3085)
		#define UNIQUE_FUNCTION<%0...%1> %00kC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3086)
		#define UNIQUE_FUNCTION<%0...%1> %00kD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3087)
		#define UNIQUE_FUNCTION<%0...%1> %00kE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3095)
	#elseif UNIQUE_SYMBOL == (3087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3088)
		#define UNIQUE_FUNCTION<%0...%1> %00kF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3089)
		#define UNIQUE_FUNCTION<%0...%1> %00kG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3090)
		#define UNIQUE_FUNCTION<%0...%1> %00kH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3091)
		#define UNIQUE_FUNCTION<%0...%1> %00kI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3092)
		#define UNIQUE_FUNCTION<%0...%1> %00kJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3093)
		#define UNIQUE_FUNCTION<%0...%1> %00kK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3094)
		#define UNIQUE_FUNCTION<%0...%1> %00kL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3095)
		#define UNIQUE_FUNCTION<%0...%1> %00kM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3103)
	#elseif UNIQUE_SYMBOL == (3095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3096)
		#define UNIQUE_FUNCTION<%0...%1> %00kN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3097)
		#define UNIQUE_FUNCTION<%0...%1> %00kO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3098)
		#define UNIQUE_FUNCTION<%0...%1> %00kP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3099)
		#define UNIQUE_FUNCTION<%0...%1> %00kQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3100)
		#define UNIQUE_FUNCTION<%0...%1> %00kR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3101)
		#define UNIQUE_FUNCTION<%0...%1> %00kS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3102)
		#define UNIQUE_FUNCTION<%0...%1> %00kT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3103)
		#define UNIQUE_FUNCTION<%0...%1> %00kU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3111)
	#elseif UNIQUE_SYMBOL == (3103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3104)
		#define UNIQUE_FUNCTION<%0...%1> %00kV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3105)
		#define UNIQUE_FUNCTION<%0...%1> %00kW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3106)
		#define UNIQUE_FUNCTION<%0...%1> %00kX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3107)
		#define UNIQUE_FUNCTION<%0...%1> %00kY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3108)
		#define UNIQUE_FUNCTION<%0...%1> %00kZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3109)
		#define UNIQUE_FUNCTION<%0...%1> %00k_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3110)
		#define UNIQUE_FUNCTION<%0...%1> %00ka%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3111)
		#define UNIQUE_FUNCTION<%0...%1> %00kb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3119)
	#elseif UNIQUE_SYMBOL == (3111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3112)
		#define UNIQUE_FUNCTION<%0...%1> %00kc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3113)
		#define UNIQUE_FUNCTION<%0...%1> %00kd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3114)
		#define UNIQUE_FUNCTION<%0...%1> %00ke%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3115)
		#define UNIQUE_FUNCTION<%0...%1> %00kf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3116)
		#define UNIQUE_FUNCTION<%0...%1> %00kg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3117)
		#define UNIQUE_FUNCTION<%0...%1> %00kh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3118)
		#define UNIQUE_FUNCTION<%0...%1> %00ki%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3119)
		#define UNIQUE_FUNCTION<%0...%1> %00kj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (3127)
	#elseif UNIQUE_SYMBOL == (3119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3120)
		#define UNIQUE_FUNCTION<%0...%1> %00kk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3121)
		#define UNIQUE_FUNCTION<%0...%1> %00kl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3122)
		#define UNIQUE_FUNCTION<%0...%1> %00km%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3123)
		#define UNIQUE_FUNCTION<%0...%1> %00kn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3124)
		#define UNIQUE_FUNCTION<%0...%1> %00ko%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3125)
		#define UNIQUE_FUNCTION<%0...%1> %00kp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3126)
		#define UNIQUE_FUNCTION<%0...%1> %00kq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3127)
		#define UNIQUE_FUNCTION<%0...%1> %00kr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (3127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3128)
		#define UNIQUE_FUNCTION<%0...%1> %00ks%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3129)
		#define UNIQUE_FUNCTION<%0...%1> %00kt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3130)
		#define UNIQUE_FUNCTION<%0...%1> %00ku%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3131)
		#define UNIQUE_FUNCTION<%0...%1> %00kv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3132)
		#define UNIQUE_FUNCTION<%0...%1> %00kw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3133)
		#define UNIQUE_FUNCTION<%0...%1> %00kx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (3133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3134)
		#define UNIQUE_FUNCTION<%0...%1> %00ky%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (3135)
		#define UNIQUE_FUNCTION<%0...%1> %00kz%1
		#endinput
	#endif
#endif
