static stock const Y_UNIQUE_236800_236863_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_236800_236863
	#undef _inc_y_unique_236800_236863
#endif

#if UNIQUE_SYMBOL < (236807)
	#if UNIQUE_SYMBOL == (236799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236800)
		#define UNIQUE_FUNCTION<%0...%1> %0to0%1
		#endinput
	#if UNIQUE_SYMBOL == (236800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236801)
		#define UNIQUE_FUNCTION<%0...%1> %0to1%1
		#endinput
	#if UNIQUE_SYMBOL == (236801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236802)
		#define UNIQUE_FUNCTION<%0...%1> %0to2%1
		#endinput
	#if UNIQUE_SYMBOL == (236802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236803)
		#define UNIQUE_FUNCTION<%0...%1> %0to3%1
		#endinput
	#if UNIQUE_SYMBOL == (236803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236804)
		#define UNIQUE_FUNCTION<%0...%1> %0to4%1
		#endinput
	#if UNIQUE_SYMBOL == (236804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236805)
		#define UNIQUE_FUNCTION<%0...%1> %0to5%1
		#endinput
	#if UNIQUE_SYMBOL == (236805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236806)
		#define UNIQUE_FUNCTION<%0...%1> %0to6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236807)
		#define UNIQUE_FUNCTION<%0...%1> %0to7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236815)
	#elseif UNIQUE_SYMBOL == (236807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236808)
		#define UNIQUE_FUNCTION<%0...%1> %0to8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236809)
		#define UNIQUE_FUNCTION<%0...%1> %0to9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236810)
		#define UNIQUE_FUNCTION<%0...%1> %0to@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236811)
		#define UNIQUE_FUNCTION<%0...%1> %0toA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236812)
		#define UNIQUE_FUNCTION<%0...%1> %0toB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236813)
		#define UNIQUE_FUNCTION<%0...%1> %0toC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236814)
		#define UNIQUE_FUNCTION<%0...%1> %0toD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236815)
		#define UNIQUE_FUNCTION<%0...%1> %0toE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236823)
	#elseif UNIQUE_SYMBOL == (236815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236816)
		#define UNIQUE_FUNCTION<%0...%1> %0toF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236817)
		#define UNIQUE_FUNCTION<%0...%1> %0toG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236818)
		#define UNIQUE_FUNCTION<%0...%1> %0toH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236819)
		#define UNIQUE_FUNCTION<%0...%1> %0toI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236820)
		#define UNIQUE_FUNCTION<%0...%1> %0toJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236821)
		#define UNIQUE_FUNCTION<%0...%1> %0toK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236822)
		#define UNIQUE_FUNCTION<%0...%1> %0toL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236823)
		#define UNIQUE_FUNCTION<%0...%1> %0toM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236831)
	#elseif UNIQUE_SYMBOL == (236823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236824)
		#define UNIQUE_FUNCTION<%0...%1> %0toN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236825)
		#define UNIQUE_FUNCTION<%0...%1> %0toO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236826)
		#define UNIQUE_FUNCTION<%0...%1> %0toP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236827)
		#define UNIQUE_FUNCTION<%0...%1> %0toQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236828)
		#define UNIQUE_FUNCTION<%0...%1> %0toR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236829)
		#define UNIQUE_FUNCTION<%0...%1> %0toS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236830)
		#define UNIQUE_FUNCTION<%0...%1> %0toT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236831)
		#define UNIQUE_FUNCTION<%0...%1> %0toU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236839)
	#elseif UNIQUE_SYMBOL == (236831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236832)
		#define UNIQUE_FUNCTION<%0...%1> %0toV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236833)
		#define UNIQUE_FUNCTION<%0...%1> %0toW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236834)
		#define UNIQUE_FUNCTION<%0...%1> %0toX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236835)
		#define UNIQUE_FUNCTION<%0...%1> %0toY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236836)
		#define UNIQUE_FUNCTION<%0...%1> %0toZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236837)
		#define UNIQUE_FUNCTION<%0...%1> %0to_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236838)
		#define UNIQUE_FUNCTION<%0...%1> %0toa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236839)
		#define UNIQUE_FUNCTION<%0...%1> %0tob%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236847)
	#elseif UNIQUE_SYMBOL == (236839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236840)
		#define UNIQUE_FUNCTION<%0...%1> %0toc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236841)
		#define UNIQUE_FUNCTION<%0...%1> %0tod%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236842)
		#define UNIQUE_FUNCTION<%0...%1> %0toe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236843)
		#define UNIQUE_FUNCTION<%0...%1> %0tof%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236844)
		#define UNIQUE_FUNCTION<%0...%1> %0tog%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236845)
		#define UNIQUE_FUNCTION<%0...%1> %0toh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236846)
		#define UNIQUE_FUNCTION<%0...%1> %0toi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236847)
		#define UNIQUE_FUNCTION<%0...%1> %0toj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236855)
	#elseif UNIQUE_SYMBOL == (236847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236848)
		#define UNIQUE_FUNCTION<%0...%1> %0tok%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236849)
		#define UNIQUE_FUNCTION<%0...%1> %0tol%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236850)
		#define UNIQUE_FUNCTION<%0...%1> %0tom%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236851)
		#define UNIQUE_FUNCTION<%0...%1> %0ton%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236852)
		#define UNIQUE_FUNCTION<%0...%1> %0too%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236853)
		#define UNIQUE_FUNCTION<%0...%1> %0top%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236854)
		#define UNIQUE_FUNCTION<%0...%1> %0toq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236855)
		#define UNIQUE_FUNCTION<%0...%1> %0tor%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (236855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236856)
		#define UNIQUE_FUNCTION<%0...%1> %0tos%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236857)
		#define UNIQUE_FUNCTION<%0...%1> %0tot%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236858)
		#define UNIQUE_FUNCTION<%0...%1> %0tou%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236859)
		#define UNIQUE_FUNCTION<%0...%1> %0tov%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236860)
		#define UNIQUE_FUNCTION<%0...%1> %0tow%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236861)
		#define UNIQUE_FUNCTION<%0...%1> %0tox%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236862)
		#define UNIQUE_FUNCTION<%0...%1> %0toy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236863)
		#define UNIQUE_FUNCTION<%0...%1> %0toz%1
		#endinput
	#endif
#endif
