static stock const Y_UNIQUE_135296_135359_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_135296_135359
	#undef _inc_y_unique_135296_135359
#endif

#if UNIQUE_SYMBOL < (135303)
	#if UNIQUE_SYMBOL == (135295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135296)
		#define UNIQUE_FUNCTION<%0...%1> %0W20%1
		#endinput
	#if UNIQUE_SYMBOL == (135296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135297)
		#define UNIQUE_FUNCTION<%0...%1> %0W21%1
		#endinput
	#if UNIQUE_SYMBOL == (135297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135298)
		#define UNIQUE_FUNCTION<%0...%1> %0W22%1
		#endinput
	#if UNIQUE_SYMBOL == (135298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135299)
		#define UNIQUE_FUNCTION<%0...%1> %0W23%1
		#endinput
	#if UNIQUE_SYMBOL == (135299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135300)
		#define UNIQUE_FUNCTION<%0...%1> %0W24%1
		#endinput
	#if UNIQUE_SYMBOL == (135300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135301)
		#define UNIQUE_FUNCTION<%0...%1> %0W25%1
		#endinput
	#if UNIQUE_SYMBOL == (135301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135302)
		#define UNIQUE_FUNCTION<%0...%1> %0W26%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135303)
		#define UNIQUE_FUNCTION<%0...%1> %0W27%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135311)
	#elseif UNIQUE_SYMBOL == (135303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135304)
		#define UNIQUE_FUNCTION<%0...%1> %0W28%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135305)
		#define UNIQUE_FUNCTION<%0...%1> %0W29%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135306)
		#define UNIQUE_FUNCTION<%0...%1> %0W2@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135307)
		#define UNIQUE_FUNCTION<%0...%1> %0W2A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135308)
		#define UNIQUE_FUNCTION<%0...%1> %0W2B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135309)
		#define UNIQUE_FUNCTION<%0...%1> %0W2C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135310)
		#define UNIQUE_FUNCTION<%0...%1> %0W2D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135311)
		#define UNIQUE_FUNCTION<%0...%1> %0W2E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135319)
	#elseif UNIQUE_SYMBOL == (135311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135312)
		#define UNIQUE_FUNCTION<%0...%1> %0W2F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135313)
		#define UNIQUE_FUNCTION<%0...%1> %0W2G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135314)
		#define UNIQUE_FUNCTION<%0...%1> %0W2H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135315)
		#define UNIQUE_FUNCTION<%0...%1> %0W2I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135316)
		#define UNIQUE_FUNCTION<%0...%1> %0W2J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135317)
		#define UNIQUE_FUNCTION<%0...%1> %0W2K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135318)
		#define UNIQUE_FUNCTION<%0...%1> %0W2L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135319)
		#define UNIQUE_FUNCTION<%0...%1> %0W2M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135327)
	#elseif UNIQUE_SYMBOL == (135319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135320)
		#define UNIQUE_FUNCTION<%0...%1> %0W2N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135321)
		#define UNIQUE_FUNCTION<%0...%1> %0W2O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135322)
		#define UNIQUE_FUNCTION<%0...%1> %0W2P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135323)
		#define UNIQUE_FUNCTION<%0...%1> %0W2Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135324)
		#define UNIQUE_FUNCTION<%0...%1> %0W2R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135325)
		#define UNIQUE_FUNCTION<%0...%1> %0W2S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135326)
		#define UNIQUE_FUNCTION<%0...%1> %0W2T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135327)
		#define UNIQUE_FUNCTION<%0...%1> %0W2U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135335)
	#elseif UNIQUE_SYMBOL == (135327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135328)
		#define UNIQUE_FUNCTION<%0...%1> %0W2V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135329)
		#define UNIQUE_FUNCTION<%0...%1> %0W2W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135330)
		#define UNIQUE_FUNCTION<%0...%1> %0W2X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135331)
		#define UNIQUE_FUNCTION<%0...%1> %0W2Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135332)
		#define UNIQUE_FUNCTION<%0...%1> %0W2Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135333)
		#define UNIQUE_FUNCTION<%0...%1> %0W2_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135334)
		#define UNIQUE_FUNCTION<%0...%1> %0W2a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135335)
		#define UNIQUE_FUNCTION<%0...%1> %0W2b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135343)
	#elseif UNIQUE_SYMBOL == (135335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135336)
		#define UNIQUE_FUNCTION<%0...%1> %0W2c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135337)
		#define UNIQUE_FUNCTION<%0...%1> %0W2d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135338)
		#define UNIQUE_FUNCTION<%0...%1> %0W2e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135339)
		#define UNIQUE_FUNCTION<%0...%1> %0W2f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135340)
		#define UNIQUE_FUNCTION<%0...%1> %0W2g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135341)
		#define UNIQUE_FUNCTION<%0...%1> %0W2h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135342)
		#define UNIQUE_FUNCTION<%0...%1> %0W2i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135343)
		#define UNIQUE_FUNCTION<%0...%1> %0W2j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135351)
	#elseif UNIQUE_SYMBOL == (135343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135344)
		#define UNIQUE_FUNCTION<%0...%1> %0W2k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135345)
		#define UNIQUE_FUNCTION<%0...%1> %0W2l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135346)
		#define UNIQUE_FUNCTION<%0...%1> %0W2m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135347)
		#define UNIQUE_FUNCTION<%0...%1> %0W2n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135348)
		#define UNIQUE_FUNCTION<%0...%1> %0W2o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135349)
		#define UNIQUE_FUNCTION<%0...%1> %0W2p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135350)
		#define UNIQUE_FUNCTION<%0...%1> %0W2q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135351)
		#define UNIQUE_FUNCTION<%0...%1> %0W2r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (135351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135352)
		#define UNIQUE_FUNCTION<%0...%1> %0W2s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135353)
		#define UNIQUE_FUNCTION<%0...%1> %0W2t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135354)
		#define UNIQUE_FUNCTION<%0...%1> %0W2u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135355)
		#define UNIQUE_FUNCTION<%0...%1> %0W2v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135356)
		#define UNIQUE_FUNCTION<%0...%1> %0W2w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135357)
		#define UNIQUE_FUNCTION<%0...%1> %0W2x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135358)
		#define UNIQUE_FUNCTION<%0...%1> %0W2y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135359)
		#define UNIQUE_FUNCTION<%0...%1> %0W2z%1
		#endinput
	#endif
#endif
