static stock const Y_UNIQUE_066304_066367_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_066304_066367
	#undef _inc_y_unique_066304_066367
#endif

#if UNIQUE_SYMBOL < (66311)
	#if UNIQUE_SYMBOL == (66303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66304)
		#define UNIQUE_FUNCTION<%0...%1> %0FB0%1
		#endinput
	#if UNIQUE_SYMBOL == (66304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66305)
		#define UNIQUE_FUNCTION<%0...%1> %0FB1%1
		#endinput
	#if UNIQUE_SYMBOL == (66305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66306)
		#define UNIQUE_FUNCTION<%0...%1> %0FB2%1
		#endinput
	#if UNIQUE_SYMBOL == (66306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66307)
		#define UNIQUE_FUNCTION<%0...%1> %0FB3%1
		#endinput
	#if UNIQUE_SYMBOL == (66307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66308)
		#define UNIQUE_FUNCTION<%0...%1> %0FB4%1
		#endinput
	#if UNIQUE_SYMBOL == (66308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66309)
		#define UNIQUE_FUNCTION<%0...%1> %0FB5%1
		#endinput
	#if UNIQUE_SYMBOL == (66309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66310)
		#define UNIQUE_FUNCTION<%0...%1> %0FB6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66311)
		#define UNIQUE_FUNCTION<%0...%1> %0FB7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66319)
	#elseif UNIQUE_SYMBOL == (66311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66312)
		#define UNIQUE_FUNCTION<%0...%1> %0FB8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66313)
		#define UNIQUE_FUNCTION<%0...%1> %0FB9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66314)
		#define UNIQUE_FUNCTION<%0...%1> %0FB@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66315)
		#define UNIQUE_FUNCTION<%0...%1> %0FBA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66316)
		#define UNIQUE_FUNCTION<%0...%1> %0FBB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66317)
		#define UNIQUE_FUNCTION<%0...%1> %0FBC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66318)
		#define UNIQUE_FUNCTION<%0...%1> %0FBD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66319)
		#define UNIQUE_FUNCTION<%0...%1> %0FBE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66327)
	#elseif UNIQUE_SYMBOL == (66319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66320)
		#define UNIQUE_FUNCTION<%0...%1> %0FBF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66321)
		#define UNIQUE_FUNCTION<%0...%1> %0FBG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66322)
		#define UNIQUE_FUNCTION<%0...%1> %0FBH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66323)
		#define UNIQUE_FUNCTION<%0...%1> %0FBI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66324)
		#define UNIQUE_FUNCTION<%0...%1> %0FBJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66325)
		#define UNIQUE_FUNCTION<%0...%1> %0FBK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66326)
		#define UNIQUE_FUNCTION<%0...%1> %0FBL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66327)
		#define UNIQUE_FUNCTION<%0...%1> %0FBM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66335)
	#elseif UNIQUE_SYMBOL == (66327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66328)
		#define UNIQUE_FUNCTION<%0...%1> %0FBN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66329)
		#define UNIQUE_FUNCTION<%0...%1> %0FBO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66330)
		#define UNIQUE_FUNCTION<%0...%1> %0FBP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66331)
		#define UNIQUE_FUNCTION<%0...%1> %0FBQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66332)
		#define UNIQUE_FUNCTION<%0...%1> %0FBR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66333)
		#define UNIQUE_FUNCTION<%0...%1> %0FBS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66334)
		#define UNIQUE_FUNCTION<%0...%1> %0FBT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66335)
		#define UNIQUE_FUNCTION<%0...%1> %0FBU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66343)
	#elseif UNIQUE_SYMBOL == (66335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66336)
		#define UNIQUE_FUNCTION<%0...%1> %0FBV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66337)
		#define UNIQUE_FUNCTION<%0...%1> %0FBW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66338)
		#define UNIQUE_FUNCTION<%0...%1> %0FBX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66339)
		#define UNIQUE_FUNCTION<%0...%1> %0FBY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66340)
		#define UNIQUE_FUNCTION<%0...%1> %0FBZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66341)
		#define UNIQUE_FUNCTION<%0...%1> %0FB_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66342)
		#define UNIQUE_FUNCTION<%0...%1> %0FBa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66343)
		#define UNIQUE_FUNCTION<%0...%1> %0FBb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66351)
	#elseif UNIQUE_SYMBOL == (66343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66344)
		#define UNIQUE_FUNCTION<%0...%1> %0FBc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66345)
		#define UNIQUE_FUNCTION<%0...%1> %0FBd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66346)
		#define UNIQUE_FUNCTION<%0...%1> %0FBe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66347)
		#define UNIQUE_FUNCTION<%0...%1> %0FBf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66348)
		#define UNIQUE_FUNCTION<%0...%1> %0FBg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66349)
		#define UNIQUE_FUNCTION<%0...%1> %0FBh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66350)
		#define UNIQUE_FUNCTION<%0...%1> %0FBi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66351)
		#define UNIQUE_FUNCTION<%0...%1> %0FBj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (66359)
	#elseif UNIQUE_SYMBOL == (66351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66352)
		#define UNIQUE_FUNCTION<%0...%1> %0FBk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66353)
		#define UNIQUE_FUNCTION<%0...%1> %0FBl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66354)
		#define UNIQUE_FUNCTION<%0...%1> %0FBm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66355)
		#define UNIQUE_FUNCTION<%0...%1> %0FBn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66356)
		#define UNIQUE_FUNCTION<%0...%1> %0FBo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66357)
		#define UNIQUE_FUNCTION<%0...%1> %0FBp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66358)
		#define UNIQUE_FUNCTION<%0...%1> %0FBq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66359)
		#define UNIQUE_FUNCTION<%0...%1> %0FBr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (66359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66360)
		#define UNIQUE_FUNCTION<%0...%1> %0FBs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66361)
		#define UNIQUE_FUNCTION<%0...%1> %0FBt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66362)
		#define UNIQUE_FUNCTION<%0...%1> %0FBu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66363)
		#define UNIQUE_FUNCTION<%0...%1> %0FBv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66364)
		#define UNIQUE_FUNCTION<%0...%1> %0FBw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66365)
		#define UNIQUE_FUNCTION<%0...%1> %0FBx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (66365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66366)
		#define UNIQUE_FUNCTION<%0...%1> %0FBy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (66367)
		#define UNIQUE_FUNCTION<%0...%1> %0FBz%1
		#endinput
	#endif
#endif
