static stock const Y_UNIQUE_201408_201471_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_201408_201471
	#undef _inc_y_unique_201408_201471
#endif

#if UNIQUE_SYMBOL < (201415)
	#if UNIQUE_SYMBOL == (201407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201408)
		#define UNIQUE_FUNCTION<%0...%1> %0lA0%1
		#endinput
	#if UNIQUE_SYMBOL == (201408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201409)
		#define UNIQUE_FUNCTION<%0...%1> %0lA1%1
		#endinput
	#if UNIQUE_SYMBOL == (201409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201410)
		#define UNIQUE_FUNCTION<%0...%1> %0lA2%1
		#endinput
	#if UNIQUE_SYMBOL == (201410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201411)
		#define UNIQUE_FUNCTION<%0...%1> %0lA3%1
		#endinput
	#if UNIQUE_SYMBOL == (201411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201412)
		#define UNIQUE_FUNCTION<%0...%1> %0lA4%1
		#endinput
	#if UNIQUE_SYMBOL == (201412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201413)
		#define UNIQUE_FUNCTION<%0...%1> %0lA5%1
		#endinput
	#if UNIQUE_SYMBOL == (201413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201414)
		#define UNIQUE_FUNCTION<%0...%1> %0lA6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201415)
		#define UNIQUE_FUNCTION<%0...%1> %0lA7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201423)
	#elseif UNIQUE_SYMBOL == (201415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201416)
		#define UNIQUE_FUNCTION<%0...%1> %0lA8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201417)
		#define UNIQUE_FUNCTION<%0...%1> %0lA9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201418)
		#define UNIQUE_FUNCTION<%0...%1> %0lA@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201419)
		#define UNIQUE_FUNCTION<%0...%1> %0lAA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201420)
		#define UNIQUE_FUNCTION<%0...%1> %0lAB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201421)
		#define UNIQUE_FUNCTION<%0...%1> %0lAC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201422)
		#define UNIQUE_FUNCTION<%0...%1> %0lAD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201423)
		#define UNIQUE_FUNCTION<%0...%1> %0lAE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201431)
	#elseif UNIQUE_SYMBOL == (201423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201424)
		#define UNIQUE_FUNCTION<%0...%1> %0lAF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201425)
		#define UNIQUE_FUNCTION<%0...%1> %0lAG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201426)
		#define UNIQUE_FUNCTION<%0...%1> %0lAH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201427)
		#define UNIQUE_FUNCTION<%0...%1> %0lAI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201428)
		#define UNIQUE_FUNCTION<%0...%1> %0lAJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201429)
		#define UNIQUE_FUNCTION<%0...%1> %0lAK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201430)
		#define UNIQUE_FUNCTION<%0...%1> %0lAL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201431)
		#define UNIQUE_FUNCTION<%0...%1> %0lAM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201439)
	#elseif UNIQUE_SYMBOL == (201431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201432)
		#define UNIQUE_FUNCTION<%0...%1> %0lAN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201433)
		#define UNIQUE_FUNCTION<%0...%1> %0lAO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201434)
		#define UNIQUE_FUNCTION<%0...%1> %0lAP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201435)
		#define UNIQUE_FUNCTION<%0...%1> %0lAQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201436)
		#define UNIQUE_FUNCTION<%0...%1> %0lAR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201437)
		#define UNIQUE_FUNCTION<%0...%1> %0lAS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201438)
		#define UNIQUE_FUNCTION<%0...%1> %0lAT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201439)
		#define UNIQUE_FUNCTION<%0...%1> %0lAU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201447)
	#elseif UNIQUE_SYMBOL == (201439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201440)
		#define UNIQUE_FUNCTION<%0...%1> %0lAV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201441)
		#define UNIQUE_FUNCTION<%0...%1> %0lAW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201442)
		#define UNIQUE_FUNCTION<%0...%1> %0lAX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201443)
		#define UNIQUE_FUNCTION<%0...%1> %0lAY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201444)
		#define UNIQUE_FUNCTION<%0...%1> %0lAZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201445)
		#define UNIQUE_FUNCTION<%0...%1> %0lA_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201446)
		#define UNIQUE_FUNCTION<%0...%1> %0lAa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201447)
		#define UNIQUE_FUNCTION<%0...%1> %0lAb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201455)
	#elseif UNIQUE_SYMBOL == (201447)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201448)
		#define UNIQUE_FUNCTION<%0...%1> %0lAc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201448)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201449)
		#define UNIQUE_FUNCTION<%0...%1> %0lAd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201449)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201450)
		#define UNIQUE_FUNCTION<%0...%1> %0lAe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201450)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201451)
		#define UNIQUE_FUNCTION<%0...%1> %0lAf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201451)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201452)
		#define UNIQUE_FUNCTION<%0...%1> %0lAg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201452)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201453)
		#define UNIQUE_FUNCTION<%0...%1> %0lAh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201453)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201454)
		#define UNIQUE_FUNCTION<%0...%1> %0lAi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201455)
		#define UNIQUE_FUNCTION<%0...%1> %0lAj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (201463)
	#elseif UNIQUE_SYMBOL == (201455)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201456)
		#define UNIQUE_FUNCTION<%0...%1> %0lAk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201456)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201457)
		#define UNIQUE_FUNCTION<%0...%1> %0lAl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201457)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201458)
		#define UNIQUE_FUNCTION<%0...%1> %0lAm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201458)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201459)
		#define UNIQUE_FUNCTION<%0...%1> %0lAn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201459)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201460)
		#define UNIQUE_FUNCTION<%0...%1> %0lAo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201460)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201461)
		#define UNIQUE_FUNCTION<%0...%1> %0lAp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201461)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201462)
		#define UNIQUE_FUNCTION<%0...%1> %0lAq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201463)
		#define UNIQUE_FUNCTION<%0...%1> %0lAr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (201463)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201464)
		#define UNIQUE_FUNCTION<%0...%1> %0lAs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201464)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201465)
		#define UNIQUE_FUNCTION<%0...%1> %0lAt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201465)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201466)
		#define UNIQUE_FUNCTION<%0...%1> %0lAu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201466)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201467)
		#define UNIQUE_FUNCTION<%0...%1> %0lAv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201467)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201468)
		#define UNIQUE_FUNCTION<%0...%1> %0lAw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201468)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201469)
		#define UNIQUE_FUNCTION<%0...%1> %0lAx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (201469)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201470)
		#define UNIQUE_FUNCTION<%0...%1> %0lAy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (201471)
		#define UNIQUE_FUNCTION<%0...%1> %0lAz%1
		#endinput
	#endif
#endif
