static stock const Y_UNIQUE_024384_024447_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_024384_024447
	#undef _inc_y_unique_024384_024447
#endif

#if UNIQUE_SYMBOL < (24391)
	#if UNIQUE_SYMBOL == (24383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24384)
		#define UNIQUE_FUNCTION<%0...%1> %05x0%1
		#endinput
	#if UNIQUE_SYMBOL == (24384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24385)
		#define UNIQUE_FUNCTION<%0...%1> %05x1%1
		#endinput
	#if UNIQUE_SYMBOL == (24385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24386)
		#define UNIQUE_FUNCTION<%0...%1> %05x2%1
		#endinput
	#if UNIQUE_SYMBOL == (24386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24387)
		#define UNIQUE_FUNCTION<%0...%1> %05x3%1
		#endinput
	#if UNIQUE_SYMBOL == (24387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24388)
		#define UNIQUE_FUNCTION<%0...%1> %05x4%1
		#endinput
	#if UNIQUE_SYMBOL == (24388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24389)
		#define UNIQUE_FUNCTION<%0...%1> %05x5%1
		#endinput
	#if UNIQUE_SYMBOL == (24389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24390)
		#define UNIQUE_FUNCTION<%0...%1> %05x6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24391)
		#define UNIQUE_FUNCTION<%0...%1> %05x7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24399)
	#elseif UNIQUE_SYMBOL == (24391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24392)
		#define UNIQUE_FUNCTION<%0...%1> %05x8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24393)
		#define UNIQUE_FUNCTION<%0...%1> %05x9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24394)
		#define UNIQUE_FUNCTION<%0...%1> %05x@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24395)
		#define UNIQUE_FUNCTION<%0...%1> %05xA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24396)
		#define UNIQUE_FUNCTION<%0...%1> %05xB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24397)
		#define UNIQUE_FUNCTION<%0...%1> %05xC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24398)
		#define UNIQUE_FUNCTION<%0...%1> %05xD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24399)
		#define UNIQUE_FUNCTION<%0...%1> %05xE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24407)
	#elseif UNIQUE_SYMBOL == (24399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24400)
		#define UNIQUE_FUNCTION<%0...%1> %05xF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24401)
		#define UNIQUE_FUNCTION<%0...%1> %05xG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24402)
		#define UNIQUE_FUNCTION<%0...%1> %05xH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24403)
		#define UNIQUE_FUNCTION<%0...%1> %05xI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24404)
		#define UNIQUE_FUNCTION<%0...%1> %05xJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24405)
		#define UNIQUE_FUNCTION<%0...%1> %05xK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24406)
		#define UNIQUE_FUNCTION<%0...%1> %05xL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24407)
		#define UNIQUE_FUNCTION<%0...%1> %05xM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24415)
	#elseif UNIQUE_SYMBOL == (24407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24408)
		#define UNIQUE_FUNCTION<%0...%1> %05xN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24409)
		#define UNIQUE_FUNCTION<%0...%1> %05xO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24410)
		#define UNIQUE_FUNCTION<%0...%1> %05xP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24411)
		#define UNIQUE_FUNCTION<%0...%1> %05xQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24412)
		#define UNIQUE_FUNCTION<%0...%1> %05xR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24413)
		#define UNIQUE_FUNCTION<%0...%1> %05xS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24414)
		#define UNIQUE_FUNCTION<%0...%1> %05xT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24415)
		#define UNIQUE_FUNCTION<%0...%1> %05xU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24423)
	#elseif UNIQUE_SYMBOL == (24415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24416)
		#define UNIQUE_FUNCTION<%0...%1> %05xV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24417)
		#define UNIQUE_FUNCTION<%0...%1> %05xW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24418)
		#define UNIQUE_FUNCTION<%0...%1> %05xX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24419)
		#define UNIQUE_FUNCTION<%0...%1> %05xY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24420)
		#define UNIQUE_FUNCTION<%0...%1> %05xZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24421)
		#define UNIQUE_FUNCTION<%0...%1> %05x_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24422)
		#define UNIQUE_FUNCTION<%0...%1> %05xa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24423)
		#define UNIQUE_FUNCTION<%0...%1> %05xb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24431)
	#elseif UNIQUE_SYMBOL == (24423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24424)
		#define UNIQUE_FUNCTION<%0...%1> %05xc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24425)
		#define UNIQUE_FUNCTION<%0...%1> %05xd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24426)
		#define UNIQUE_FUNCTION<%0...%1> %05xe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24427)
		#define UNIQUE_FUNCTION<%0...%1> %05xf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24428)
		#define UNIQUE_FUNCTION<%0...%1> %05xg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24429)
		#define UNIQUE_FUNCTION<%0...%1> %05xh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24430)
		#define UNIQUE_FUNCTION<%0...%1> %05xi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24431)
		#define UNIQUE_FUNCTION<%0...%1> %05xj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (24439)
	#elseif UNIQUE_SYMBOL == (24431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24432)
		#define UNIQUE_FUNCTION<%0...%1> %05xk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24433)
		#define UNIQUE_FUNCTION<%0...%1> %05xl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24434)
		#define UNIQUE_FUNCTION<%0...%1> %05xm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24435)
		#define UNIQUE_FUNCTION<%0...%1> %05xn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24436)
		#define UNIQUE_FUNCTION<%0...%1> %05xo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24437)
		#define UNIQUE_FUNCTION<%0...%1> %05xp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24438)
		#define UNIQUE_FUNCTION<%0...%1> %05xq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24439)
		#define UNIQUE_FUNCTION<%0...%1> %05xr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (24439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24440)
		#define UNIQUE_FUNCTION<%0...%1> %05xs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24441)
		#define UNIQUE_FUNCTION<%0...%1> %05xt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24442)
		#define UNIQUE_FUNCTION<%0...%1> %05xu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24443)
		#define UNIQUE_FUNCTION<%0...%1> %05xv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24444)
		#define UNIQUE_FUNCTION<%0...%1> %05xw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24445)
		#define UNIQUE_FUNCTION<%0...%1> %05xx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (24445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24446)
		#define UNIQUE_FUNCTION<%0...%1> %05xy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (24447)
		#define UNIQUE_FUNCTION<%0...%1> %05xz%1
		#endinput
	#endif
#endif
