static stock const Y_UNIQUE_012288_012351_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_012288_012351
	#undef _inc_y_unique_012288_012351
#endif

#if UNIQUE_SYMBOL < (12295)
	#if UNIQUE_SYMBOL == (12287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12288)
		#define UNIQUE_FUNCTION<%0...%1> %0300%1
		#endinput
	#if UNIQUE_SYMBOL == (12288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12289)
		#define UNIQUE_FUNCTION<%0...%1> %0301%1
		#endinput
	#if UNIQUE_SYMBOL == (12289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12290)
		#define UNIQUE_FUNCTION<%0...%1> %0302%1
		#endinput
	#if UNIQUE_SYMBOL == (12290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12291)
		#define UNIQUE_FUNCTION<%0...%1> %0303%1
		#endinput
	#if UNIQUE_SYMBOL == (12291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12292)
		#define UNIQUE_FUNCTION<%0...%1> %0304%1
		#endinput
	#if UNIQUE_SYMBOL == (12292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12293)
		#define UNIQUE_FUNCTION<%0...%1> %0305%1
		#endinput
	#if UNIQUE_SYMBOL == (12293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12294)
		#define UNIQUE_FUNCTION<%0...%1> %0306%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12295)
		#define UNIQUE_FUNCTION<%0...%1> %0307%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (12303)
	#elseif UNIQUE_SYMBOL == (12295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12296)
		#define UNIQUE_FUNCTION<%0...%1> %0308%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12297)
		#define UNIQUE_FUNCTION<%0...%1> %0309%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12298)
		#define UNIQUE_FUNCTION<%0...%1> %030@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12299)
		#define UNIQUE_FUNCTION<%0...%1> %030A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12300)
		#define UNIQUE_FUNCTION<%0...%1> %030B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12301)
		#define UNIQUE_FUNCTION<%0...%1> %030C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12302)
		#define UNIQUE_FUNCTION<%0...%1> %030D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12303)
		#define UNIQUE_FUNCTION<%0...%1> %030E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (12311)
	#elseif UNIQUE_SYMBOL == (12303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12304)
		#define UNIQUE_FUNCTION<%0...%1> %030F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12305)
		#define UNIQUE_FUNCTION<%0...%1> %030G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12306)
		#define UNIQUE_FUNCTION<%0...%1> %030H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12307)
		#define UNIQUE_FUNCTION<%0...%1> %030I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12308)
		#define UNIQUE_FUNCTION<%0...%1> %030J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12309)
		#define UNIQUE_FUNCTION<%0...%1> %030K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12310)
		#define UNIQUE_FUNCTION<%0...%1> %030L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12311)
		#define UNIQUE_FUNCTION<%0...%1> %030M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (12319)
	#elseif UNIQUE_SYMBOL == (12311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12312)
		#define UNIQUE_FUNCTION<%0...%1> %030N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12313)
		#define UNIQUE_FUNCTION<%0...%1> %030O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12314)
		#define UNIQUE_FUNCTION<%0...%1> %030P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12315)
		#define UNIQUE_FUNCTION<%0...%1> %030Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12316)
		#define UNIQUE_FUNCTION<%0...%1> %030R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12317)
		#define UNIQUE_FUNCTION<%0...%1> %030S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12318)
		#define UNIQUE_FUNCTION<%0...%1> %030T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12319)
		#define UNIQUE_FUNCTION<%0...%1> %030U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (12327)
	#elseif UNIQUE_SYMBOL == (12319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12320)
		#define UNIQUE_FUNCTION<%0...%1> %030V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12321)
		#define UNIQUE_FUNCTION<%0...%1> %030W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12322)
		#define UNIQUE_FUNCTION<%0...%1> %030X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12323)
		#define UNIQUE_FUNCTION<%0...%1> %030Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12324)
		#define UNIQUE_FUNCTION<%0...%1> %030Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12325)
		#define UNIQUE_FUNCTION<%0...%1> %030_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12326)
		#define UNIQUE_FUNCTION<%0...%1> %030a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12327)
		#define UNIQUE_FUNCTION<%0...%1> %030b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (12335)
	#elseif UNIQUE_SYMBOL == (12327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12328)
		#define UNIQUE_FUNCTION<%0...%1> %030c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12329)
		#define UNIQUE_FUNCTION<%0...%1> %030d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12330)
		#define UNIQUE_FUNCTION<%0...%1> %030e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12331)
		#define UNIQUE_FUNCTION<%0...%1> %030f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12332)
		#define UNIQUE_FUNCTION<%0...%1> %030g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12333)
		#define UNIQUE_FUNCTION<%0...%1> %030h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12334)
		#define UNIQUE_FUNCTION<%0...%1> %030i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12335)
		#define UNIQUE_FUNCTION<%0...%1> %030j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (12343)
	#elseif UNIQUE_SYMBOL == (12335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12336)
		#define UNIQUE_FUNCTION<%0...%1> %030k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12337)
		#define UNIQUE_FUNCTION<%0...%1> %030l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12338)
		#define UNIQUE_FUNCTION<%0...%1> %030m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12339)
		#define UNIQUE_FUNCTION<%0...%1> %030n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12340)
		#define UNIQUE_FUNCTION<%0...%1> %030o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12341)
		#define UNIQUE_FUNCTION<%0...%1> %030p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12342)
		#define UNIQUE_FUNCTION<%0...%1> %030q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12343)
		#define UNIQUE_FUNCTION<%0...%1> %030r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (12343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12344)
		#define UNIQUE_FUNCTION<%0...%1> %030s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12345)
		#define UNIQUE_FUNCTION<%0...%1> %030t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12346)
		#define UNIQUE_FUNCTION<%0...%1> %030u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12347)
		#define UNIQUE_FUNCTION<%0...%1> %030v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12348)
		#define UNIQUE_FUNCTION<%0...%1> %030w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12349)
		#define UNIQUE_FUNCTION<%0...%1> %030x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (12349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12350)
		#define UNIQUE_FUNCTION<%0...%1> %030y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (12351)
		#define UNIQUE_FUNCTION<%0...%1> %030z%1
		#endinput
	#endif
#endif
