static stock const Y_UNIQUE_135680_135743_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_135680_135743
	#undef _inc_y_unique_135680_135743
#endif

#if UNIQUE_SYMBOL < (135687)
	#if UNIQUE_SYMBOL == (135679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135680)
		#define UNIQUE_FUNCTION<%0...%1> %0W80%1
		#endinput
	#if UNIQUE_SYMBOL == (135680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135681)
		#define UNIQUE_FUNCTION<%0...%1> %0W81%1
		#endinput
	#if UNIQUE_SYMBOL == (135681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135682)
		#define UNIQUE_FUNCTION<%0...%1> %0W82%1
		#endinput
	#if UNIQUE_SYMBOL == (135682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135683)
		#define UNIQUE_FUNCTION<%0...%1> %0W83%1
		#endinput
	#if UNIQUE_SYMBOL == (135683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135684)
		#define UNIQUE_FUNCTION<%0...%1> %0W84%1
		#endinput
	#if UNIQUE_SYMBOL == (135684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135685)
		#define UNIQUE_FUNCTION<%0...%1> %0W85%1
		#endinput
	#if UNIQUE_SYMBOL == (135685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135686)
		#define UNIQUE_FUNCTION<%0...%1> %0W86%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135687)
		#define UNIQUE_FUNCTION<%0...%1> %0W87%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135695)
	#elseif UNIQUE_SYMBOL == (135687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135688)
		#define UNIQUE_FUNCTION<%0...%1> %0W88%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135689)
		#define UNIQUE_FUNCTION<%0...%1> %0W89%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135690)
		#define UNIQUE_FUNCTION<%0...%1> %0W8@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135691)
		#define UNIQUE_FUNCTION<%0...%1> %0W8A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135692)
		#define UNIQUE_FUNCTION<%0...%1> %0W8B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135693)
		#define UNIQUE_FUNCTION<%0...%1> %0W8C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135694)
		#define UNIQUE_FUNCTION<%0...%1> %0W8D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135695)
		#define UNIQUE_FUNCTION<%0...%1> %0W8E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135703)
	#elseif UNIQUE_SYMBOL == (135695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135696)
		#define UNIQUE_FUNCTION<%0...%1> %0W8F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135697)
		#define UNIQUE_FUNCTION<%0...%1> %0W8G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135698)
		#define UNIQUE_FUNCTION<%0...%1> %0W8H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135699)
		#define UNIQUE_FUNCTION<%0...%1> %0W8I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135700)
		#define UNIQUE_FUNCTION<%0...%1> %0W8J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135701)
		#define UNIQUE_FUNCTION<%0...%1> %0W8K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135702)
		#define UNIQUE_FUNCTION<%0...%1> %0W8L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135703)
		#define UNIQUE_FUNCTION<%0...%1> %0W8M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135711)
	#elseif UNIQUE_SYMBOL == (135703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135704)
		#define UNIQUE_FUNCTION<%0...%1> %0W8N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135705)
		#define UNIQUE_FUNCTION<%0...%1> %0W8O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135706)
		#define UNIQUE_FUNCTION<%0...%1> %0W8P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135707)
		#define UNIQUE_FUNCTION<%0...%1> %0W8Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135708)
		#define UNIQUE_FUNCTION<%0...%1> %0W8R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135709)
		#define UNIQUE_FUNCTION<%0...%1> %0W8S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135710)
		#define UNIQUE_FUNCTION<%0...%1> %0W8T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135711)
		#define UNIQUE_FUNCTION<%0...%1> %0W8U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135719)
	#elseif UNIQUE_SYMBOL == (135711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135712)
		#define UNIQUE_FUNCTION<%0...%1> %0W8V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135713)
		#define UNIQUE_FUNCTION<%0...%1> %0W8W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135714)
		#define UNIQUE_FUNCTION<%0...%1> %0W8X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135715)
		#define UNIQUE_FUNCTION<%0...%1> %0W8Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135716)
		#define UNIQUE_FUNCTION<%0...%1> %0W8Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135717)
		#define UNIQUE_FUNCTION<%0...%1> %0W8_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135718)
		#define UNIQUE_FUNCTION<%0...%1> %0W8a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135719)
		#define UNIQUE_FUNCTION<%0...%1> %0W8b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135727)
	#elseif UNIQUE_SYMBOL == (135719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135720)
		#define UNIQUE_FUNCTION<%0...%1> %0W8c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135721)
		#define UNIQUE_FUNCTION<%0...%1> %0W8d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135722)
		#define UNIQUE_FUNCTION<%0...%1> %0W8e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135723)
		#define UNIQUE_FUNCTION<%0...%1> %0W8f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135724)
		#define UNIQUE_FUNCTION<%0...%1> %0W8g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135725)
		#define UNIQUE_FUNCTION<%0...%1> %0W8h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135726)
		#define UNIQUE_FUNCTION<%0...%1> %0W8i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135727)
		#define UNIQUE_FUNCTION<%0...%1> %0W8j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135735)
	#elseif UNIQUE_SYMBOL == (135727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135728)
		#define UNIQUE_FUNCTION<%0...%1> %0W8k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135729)
		#define UNIQUE_FUNCTION<%0...%1> %0W8l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135730)
		#define UNIQUE_FUNCTION<%0...%1> %0W8m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135731)
		#define UNIQUE_FUNCTION<%0...%1> %0W8n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135732)
		#define UNIQUE_FUNCTION<%0...%1> %0W8o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135733)
		#define UNIQUE_FUNCTION<%0...%1> %0W8p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135734)
		#define UNIQUE_FUNCTION<%0...%1> %0W8q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135735)
		#define UNIQUE_FUNCTION<%0...%1> %0W8r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (135735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135736)
		#define UNIQUE_FUNCTION<%0...%1> %0W8s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135737)
		#define UNIQUE_FUNCTION<%0...%1> %0W8t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135738)
		#define UNIQUE_FUNCTION<%0...%1> %0W8u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135739)
		#define UNIQUE_FUNCTION<%0...%1> %0W8v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135740)
		#define UNIQUE_FUNCTION<%0...%1> %0W8w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135741)
		#define UNIQUE_FUNCTION<%0...%1> %0W8x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135742)
		#define UNIQUE_FUNCTION<%0...%1> %0W8y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135743)
		#define UNIQUE_FUNCTION<%0...%1> %0W8z%1
		#endinput
	#endif
#endif
