static stock const Y_UNIQUE_232704_232767_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_232704_232767
	#undef _inc_y_unique_232704_232767
#endif

#if UNIQUE_SYMBOL < (232711)
	#if UNIQUE_SYMBOL == (232703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232704)
		#define UNIQUE_FUNCTION<%0...%1> %0so0%1
		#endinput
	#if UNIQUE_SYMBOL == (232704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232705)
		#define UNIQUE_FUNCTION<%0...%1> %0so1%1
		#endinput
	#if UNIQUE_SYMBOL == (232705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232706)
		#define UNIQUE_FUNCTION<%0...%1> %0so2%1
		#endinput
	#if UNIQUE_SYMBOL == (232706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232707)
		#define UNIQUE_FUNCTION<%0...%1> %0so3%1
		#endinput
	#if UNIQUE_SYMBOL == (232707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232708)
		#define UNIQUE_FUNCTION<%0...%1> %0so4%1
		#endinput
	#if UNIQUE_SYMBOL == (232708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232709)
		#define UNIQUE_FUNCTION<%0...%1> %0so5%1
		#endinput
	#if UNIQUE_SYMBOL == (232709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232710)
		#define UNIQUE_FUNCTION<%0...%1> %0so6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232711)
		#define UNIQUE_FUNCTION<%0...%1> %0so7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (232719)
	#elseif UNIQUE_SYMBOL == (232711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232712)
		#define UNIQUE_FUNCTION<%0...%1> %0so8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232713)
		#define UNIQUE_FUNCTION<%0...%1> %0so9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232714)
		#define UNIQUE_FUNCTION<%0...%1> %0so@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232715)
		#define UNIQUE_FUNCTION<%0...%1> %0soA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232716)
		#define UNIQUE_FUNCTION<%0...%1> %0soB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232717)
		#define UNIQUE_FUNCTION<%0...%1> %0soC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232718)
		#define UNIQUE_FUNCTION<%0...%1> %0soD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232719)
		#define UNIQUE_FUNCTION<%0...%1> %0soE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (232727)
	#elseif UNIQUE_SYMBOL == (232719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232720)
		#define UNIQUE_FUNCTION<%0...%1> %0soF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232721)
		#define UNIQUE_FUNCTION<%0...%1> %0soG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232722)
		#define UNIQUE_FUNCTION<%0...%1> %0soH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232723)
		#define UNIQUE_FUNCTION<%0...%1> %0soI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232724)
		#define UNIQUE_FUNCTION<%0...%1> %0soJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232725)
		#define UNIQUE_FUNCTION<%0...%1> %0soK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232726)
		#define UNIQUE_FUNCTION<%0...%1> %0soL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232727)
		#define UNIQUE_FUNCTION<%0...%1> %0soM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (232735)
	#elseif UNIQUE_SYMBOL == (232727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232728)
		#define UNIQUE_FUNCTION<%0...%1> %0soN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232729)
		#define UNIQUE_FUNCTION<%0...%1> %0soO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232730)
		#define UNIQUE_FUNCTION<%0...%1> %0soP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232731)
		#define UNIQUE_FUNCTION<%0...%1> %0soQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232732)
		#define UNIQUE_FUNCTION<%0...%1> %0soR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232733)
		#define UNIQUE_FUNCTION<%0...%1> %0soS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232734)
		#define UNIQUE_FUNCTION<%0...%1> %0soT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232735)
		#define UNIQUE_FUNCTION<%0...%1> %0soU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (232743)
	#elseif UNIQUE_SYMBOL == (232735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232736)
		#define UNIQUE_FUNCTION<%0...%1> %0soV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232737)
		#define UNIQUE_FUNCTION<%0...%1> %0soW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232738)
		#define UNIQUE_FUNCTION<%0...%1> %0soX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232739)
		#define UNIQUE_FUNCTION<%0...%1> %0soY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232740)
		#define UNIQUE_FUNCTION<%0...%1> %0soZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232741)
		#define UNIQUE_FUNCTION<%0...%1> %0so_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232742)
		#define UNIQUE_FUNCTION<%0...%1> %0soa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232743)
		#define UNIQUE_FUNCTION<%0...%1> %0sob%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (232751)
	#elseif UNIQUE_SYMBOL == (232743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232744)
		#define UNIQUE_FUNCTION<%0...%1> %0soc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232745)
		#define UNIQUE_FUNCTION<%0...%1> %0sod%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232746)
		#define UNIQUE_FUNCTION<%0...%1> %0soe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232747)
		#define UNIQUE_FUNCTION<%0...%1> %0sof%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232748)
		#define UNIQUE_FUNCTION<%0...%1> %0sog%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232749)
		#define UNIQUE_FUNCTION<%0...%1> %0soh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232750)
		#define UNIQUE_FUNCTION<%0...%1> %0soi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232751)
		#define UNIQUE_FUNCTION<%0...%1> %0soj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (232759)
	#elseif UNIQUE_SYMBOL == (232751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232752)
		#define UNIQUE_FUNCTION<%0...%1> %0sok%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232753)
		#define UNIQUE_FUNCTION<%0...%1> %0sol%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232754)
		#define UNIQUE_FUNCTION<%0...%1> %0som%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232755)
		#define UNIQUE_FUNCTION<%0...%1> %0son%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232756)
		#define UNIQUE_FUNCTION<%0...%1> %0soo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232757)
		#define UNIQUE_FUNCTION<%0...%1> %0sop%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232758)
		#define UNIQUE_FUNCTION<%0...%1> %0soq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232759)
		#define UNIQUE_FUNCTION<%0...%1> %0sor%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (232759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232760)
		#define UNIQUE_FUNCTION<%0...%1> %0sos%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232761)
		#define UNIQUE_FUNCTION<%0...%1> %0sot%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232762)
		#define UNIQUE_FUNCTION<%0...%1> %0sou%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232763)
		#define UNIQUE_FUNCTION<%0...%1> %0sov%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232764)
		#define UNIQUE_FUNCTION<%0...%1> %0sow%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232765)
		#define UNIQUE_FUNCTION<%0...%1> %0sox%1
		#endinput
	#elseif UNIQUE_SYMBOL == (232765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232766)
		#define UNIQUE_FUNCTION<%0...%1> %0soy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (232767)
		#define UNIQUE_FUNCTION<%0...%1> %0soz%1
		#endinput
	#endif
#endif
