static stock const Y_UNIQUE_080320_080383_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_080320_080383
	#undef _inc_y_unique_080320_080383
#endif

#if UNIQUE_SYMBOL < (80327)
	#if UNIQUE_SYMBOL == (80319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80320)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib0%1
		#endinput
	#if UNIQUE_SYMBOL == (80320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80321)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib1%1
		#endinput
	#if UNIQUE_SYMBOL == (80321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80322)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib2%1
		#endinput
	#if UNIQUE_SYMBOL == (80322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80323)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib3%1
		#endinput
	#if UNIQUE_SYMBOL == (80323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80324)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib4%1
		#endinput
	#if UNIQUE_SYMBOL == (80324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80325)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib5%1
		#endinput
	#if UNIQUE_SYMBOL == (80325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80326)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80327)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80335)
	#elseif UNIQUE_SYMBOL == (80327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80328)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80329)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80330)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80331)
		#define UNIQUE_FUNCTION<%0...%1> %0IbA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80332)
		#define UNIQUE_FUNCTION<%0...%1> %0IbB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80333)
		#define UNIQUE_FUNCTION<%0...%1> %0IbC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80334)
		#define UNIQUE_FUNCTION<%0...%1> %0IbD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80335)
		#define UNIQUE_FUNCTION<%0...%1> %0IbE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80343)
	#elseif UNIQUE_SYMBOL == (80335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80336)
		#define UNIQUE_FUNCTION<%0...%1> %0IbF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80337)
		#define UNIQUE_FUNCTION<%0...%1> %0IbG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80338)
		#define UNIQUE_FUNCTION<%0...%1> %0IbH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80339)
		#define UNIQUE_FUNCTION<%0...%1> %0IbI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80340)
		#define UNIQUE_FUNCTION<%0...%1> %0IbJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80341)
		#define UNIQUE_FUNCTION<%0...%1> %0IbK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80342)
		#define UNIQUE_FUNCTION<%0...%1> %0IbL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80343)
		#define UNIQUE_FUNCTION<%0...%1> %0IbM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80351)
	#elseif UNIQUE_SYMBOL == (80343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80344)
		#define UNIQUE_FUNCTION<%0...%1> %0IbN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80345)
		#define UNIQUE_FUNCTION<%0...%1> %0IbO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80346)
		#define UNIQUE_FUNCTION<%0...%1> %0IbP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80347)
		#define UNIQUE_FUNCTION<%0...%1> %0IbQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80348)
		#define UNIQUE_FUNCTION<%0...%1> %0IbR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80349)
		#define UNIQUE_FUNCTION<%0...%1> %0IbS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80350)
		#define UNIQUE_FUNCTION<%0...%1> %0IbT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80351)
		#define UNIQUE_FUNCTION<%0...%1> %0IbU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80359)
	#elseif UNIQUE_SYMBOL == (80351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80352)
		#define UNIQUE_FUNCTION<%0...%1> %0IbV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80353)
		#define UNIQUE_FUNCTION<%0...%1> %0IbW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80354)
		#define UNIQUE_FUNCTION<%0...%1> %0IbX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80355)
		#define UNIQUE_FUNCTION<%0...%1> %0IbY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80356)
		#define UNIQUE_FUNCTION<%0...%1> %0IbZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80357)
		#define UNIQUE_FUNCTION<%0...%1> %0Ib_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80358)
		#define UNIQUE_FUNCTION<%0...%1> %0Iba%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80359)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80367)
	#elseif UNIQUE_SYMBOL == (80359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80360)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80361)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80362)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80363)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80364)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80365)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80366)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80367)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80375)
	#elseif UNIQUE_SYMBOL == (80367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80368)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80369)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80370)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80371)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80372)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80373)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80374)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80375)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (80375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80376)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80377)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80378)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80379)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80380)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80381)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80382)
		#define UNIQUE_FUNCTION<%0...%1> %0Iby%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80383)
		#define UNIQUE_FUNCTION<%0...%1> %0Ibz%1
		#endinput
	#endif
#endif
