static stock const Y_UNIQUE_188736_188799_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_188736_188799
	#undef _inc_y_unique_188736_188799
#endif

#if UNIQUE_SYMBOL < (188743)
	#if UNIQUE_SYMBOL == (188735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188736)
		#define UNIQUE_FUNCTION<%0...%1> %0i50%1
		#endinput
	#if UNIQUE_SYMBOL == (188736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188737)
		#define UNIQUE_FUNCTION<%0...%1> %0i51%1
		#endinput
	#if UNIQUE_SYMBOL == (188737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188738)
		#define UNIQUE_FUNCTION<%0...%1> %0i52%1
		#endinput
	#if UNIQUE_SYMBOL == (188738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188739)
		#define UNIQUE_FUNCTION<%0...%1> %0i53%1
		#endinput
	#if UNIQUE_SYMBOL == (188739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188740)
		#define UNIQUE_FUNCTION<%0...%1> %0i54%1
		#endinput
	#if UNIQUE_SYMBOL == (188740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188741)
		#define UNIQUE_FUNCTION<%0...%1> %0i55%1
		#endinput
	#if UNIQUE_SYMBOL == (188741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188742)
		#define UNIQUE_FUNCTION<%0...%1> %0i56%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188743)
		#define UNIQUE_FUNCTION<%0...%1> %0i57%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188751)
	#elseif UNIQUE_SYMBOL == (188743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188744)
		#define UNIQUE_FUNCTION<%0...%1> %0i58%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188745)
		#define UNIQUE_FUNCTION<%0...%1> %0i59%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188746)
		#define UNIQUE_FUNCTION<%0...%1> %0i5@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188747)
		#define UNIQUE_FUNCTION<%0...%1> %0i5A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188748)
		#define UNIQUE_FUNCTION<%0...%1> %0i5B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188749)
		#define UNIQUE_FUNCTION<%0...%1> %0i5C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188750)
		#define UNIQUE_FUNCTION<%0...%1> %0i5D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188751)
		#define UNIQUE_FUNCTION<%0...%1> %0i5E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188759)
	#elseif UNIQUE_SYMBOL == (188751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188752)
		#define UNIQUE_FUNCTION<%0...%1> %0i5F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188753)
		#define UNIQUE_FUNCTION<%0...%1> %0i5G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188754)
		#define UNIQUE_FUNCTION<%0...%1> %0i5H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188755)
		#define UNIQUE_FUNCTION<%0...%1> %0i5I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188756)
		#define UNIQUE_FUNCTION<%0...%1> %0i5J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188757)
		#define UNIQUE_FUNCTION<%0...%1> %0i5K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188758)
		#define UNIQUE_FUNCTION<%0...%1> %0i5L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188759)
		#define UNIQUE_FUNCTION<%0...%1> %0i5M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188767)
	#elseif UNIQUE_SYMBOL == (188759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188760)
		#define UNIQUE_FUNCTION<%0...%1> %0i5N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188761)
		#define UNIQUE_FUNCTION<%0...%1> %0i5O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188762)
		#define UNIQUE_FUNCTION<%0...%1> %0i5P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188763)
		#define UNIQUE_FUNCTION<%0...%1> %0i5Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188764)
		#define UNIQUE_FUNCTION<%0...%1> %0i5R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188765)
		#define UNIQUE_FUNCTION<%0...%1> %0i5S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188766)
		#define UNIQUE_FUNCTION<%0...%1> %0i5T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188767)
		#define UNIQUE_FUNCTION<%0...%1> %0i5U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188775)
	#elseif UNIQUE_SYMBOL == (188767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188768)
		#define UNIQUE_FUNCTION<%0...%1> %0i5V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188769)
		#define UNIQUE_FUNCTION<%0...%1> %0i5W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188770)
		#define UNIQUE_FUNCTION<%0...%1> %0i5X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188771)
		#define UNIQUE_FUNCTION<%0...%1> %0i5Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188772)
		#define UNIQUE_FUNCTION<%0...%1> %0i5Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188773)
		#define UNIQUE_FUNCTION<%0...%1> %0i5_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188774)
		#define UNIQUE_FUNCTION<%0...%1> %0i5a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188775)
		#define UNIQUE_FUNCTION<%0...%1> %0i5b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188783)
	#elseif UNIQUE_SYMBOL == (188775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188776)
		#define UNIQUE_FUNCTION<%0...%1> %0i5c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188777)
		#define UNIQUE_FUNCTION<%0...%1> %0i5d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188778)
		#define UNIQUE_FUNCTION<%0...%1> %0i5e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188779)
		#define UNIQUE_FUNCTION<%0...%1> %0i5f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188780)
		#define UNIQUE_FUNCTION<%0...%1> %0i5g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188781)
		#define UNIQUE_FUNCTION<%0...%1> %0i5h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188782)
		#define UNIQUE_FUNCTION<%0...%1> %0i5i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188783)
		#define UNIQUE_FUNCTION<%0...%1> %0i5j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (188791)
	#elseif UNIQUE_SYMBOL == (188783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188784)
		#define UNIQUE_FUNCTION<%0...%1> %0i5k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188785)
		#define UNIQUE_FUNCTION<%0...%1> %0i5l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188786)
		#define UNIQUE_FUNCTION<%0...%1> %0i5m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188787)
		#define UNIQUE_FUNCTION<%0...%1> %0i5n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188788)
		#define UNIQUE_FUNCTION<%0...%1> %0i5o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188789)
		#define UNIQUE_FUNCTION<%0...%1> %0i5p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188790)
		#define UNIQUE_FUNCTION<%0...%1> %0i5q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188791)
		#define UNIQUE_FUNCTION<%0...%1> %0i5r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (188791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188792)
		#define UNIQUE_FUNCTION<%0...%1> %0i5s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188793)
		#define UNIQUE_FUNCTION<%0...%1> %0i5t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188794)
		#define UNIQUE_FUNCTION<%0...%1> %0i5u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188795)
		#define UNIQUE_FUNCTION<%0...%1> %0i5v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188796)
		#define UNIQUE_FUNCTION<%0...%1> %0i5w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188797)
		#define UNIQUE_FUNCTION<%0...%1> %0i5x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (188797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188798)
		#define UNIQUE_FUNCTION<%0...%1> %0i5y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (188799)
		#define UNIQUE_FUNCTION<%0...%1> %0i5z%1
		#endinput
	#endif
#endif
