static stock const Y_UNIQUE_242880_242943_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_242880_242943
	#undef _inc_y_unique_242880_242943
#endif

#if UNIQUE_SYMBOL < (242887)
	#if UNIQUE_SYMBOL == (242879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242880)
		#define UNIQUE_FUNCTION<%0...%1> %0vI0%1
		#endinput
	#if UNIQUE_SYMBOL == (242880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242881)
		#define UNIQUE_FUNCTION<%0...%1> %0vI1%1
		#endinput
	#if UNIQUE_SYMBOL == (242881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242882)
		#define UNIQUE_FUNCTION<%0...%1> %0vI2%1
		#endinput
	#if UNIQUE_SYMBOL == (242882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242883)
		#define UNIQUE_FUNCTION<%0...%1> %0vI3%1
		#endinput
	#if UNIQUE_SYMBOL == (242883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242884)
		#define UNIQUE_FUNCTION<%0...%1> %0vI4%1
		#endinput
	#if UNIQUE_SYMBOL == (242884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242885)
		#define UNIQUE_FUNCTION<%0...%1> %0vI5%1
		#endinput
	#if UNIQUE_SYMBOL == (242885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242886)
		#define UNIQUE_FUNCTION<%0...%1> %0vI6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242887)
		#define UNIQUE_FUNCTION<%0...%1> %0vI7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242895)
	#elseif UNIQUE_SYMBOL == (242887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242888)
		#define UNIQUE_FUNCTION<%0...%1> %0vI8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242889)
		#define UNIQUE_FUNCTION<%0...%1> %0vI9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242890)
		#define UNIQUE_FUNCTION<%0...%1> %0vI@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242891)
		#define UNIQUE_FUNCTION<%0...%1> %0vIA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242892)
		#define UNIQUE_FUNCTION<%0...%1> %0vIB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242893)
		#define UNIQUE_FUNCTION<%0...%1> %0vIC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242894)
		#define UNIQUE_FUNCTION<%0...%1> %0vID%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242895)
		#define UNIQUE_FUNCTION<%0...%1> %0vIE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242903)
	#elseif UNIQUE_SYMBOL == (242895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242896)
		#define UNIQUE_FUNCTION<%0...%1> %0vIF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242897)
		#define UNIQUE_FUNCTION<%0...%1> %0vIG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242898)
		#define UNIQUE_FUNCTION<%0...%1> %0vIH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242899)
		#define UNIQUE_FUNCTION<%0...%1> %0vII%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242900)
		#define UNIQUE_FUNCTION<%0...%1> %0vIJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242901)
		#define UNIQUE_FUNCTION<%0...%1> %0vIK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242902)
		#define UNIQUE_FUNCTION<%0...%1> %0vIL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242903)
		#define UNIQUE_FUNCTION<%0...%1> %0vIM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242911)
	#elseif UNIQUE_SYMBOL == (242903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242904)
		#define UNIQUE_FUNCTION<%0...%1> %0vIN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242905)
		#define UNIQUE_FUNCTION<%0...%1> %0vIO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242906)
		#define UNIQUE_FUNCTION<%0...%1> %0vIP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242907)
		#define UNIQUE_FUNCTION<%0...%1> %0vIQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242908)
		#define UNIQUE_FUNCTION<%0...%1> %0vIR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242909)
		#define UNIQUE_FUNCTION<%0...%1> %0vIS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242910)
		#define UNIQUE_FUNCTION<%0...%1> %0vIT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242911)
		#define UNIQUE_FUNCTION<%0...%1> %0vIU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242919)
	#elseif UNIQUE_SYMBOL == (242911)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242912)
		#define UNIQUE_FUNCTION<%0...%1> %0vIV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242912)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242913)
		#define UNIQUE_FUNCTION<%0...%1> %0vIW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242913)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242914)
		#define UNIQUE_FUNCTION<%0...%1> %0vIX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242914)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242915)
		#define UNIQUE_FUNCTION<%0...%1> %0vIY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242915)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242916)
		#define UNIQUE_FUNCTION<%0...%1> %0vIZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242916)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242917)
		#define UNIQUE_FUNCTION<%0...%1> %0vI_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242917)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242918)
		#define UNIQUE_FUNCTION<%0...%1> %0vIa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242919)
		#define UNIQUE_FUNCTION<%0...%1> %0vIb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242927)
	#elseif UNIQUE_SYMBOL == (242919)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242920)
		#define UNIQUE_FUNCTION<%0...%1> %0vIc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242920)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242921)
		#define UNIQUE_FUNCTION<%0...%1> %0vId%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242921)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242922)
		#define UNIQUE_FUNCTION<%0...%1> %0vIe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242922)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242923)
		#define UNIQUE_FUNCTION<%0...%1> %0vIf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242923)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242924)
		#define UNIQUE_FUNCTION<%0...%1> %0vIg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242924)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242925)
		#define UNIQUE_FUNCTION<%0...%1> %0vIh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242925)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242926)
		#define UNIQUE_FUNCTION<%0...%1> %0vIi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242927)
		#define UNIQUE_FUNCTION<%0...%1> %0vIj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (242935)
	#elseif UNIQUE_SYMBOL == (242927)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242928)
		#define UNIQUE_FUNCTION<%0...%1> %0vIk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242928)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242929)
		#define UNIQUE_FUNCTION<%0...%1> %0vIl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242929)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242930)
		#define UNIQUE_FUNCTION<%0...%1> %0vIm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242930)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242931)
		#define UNIQUE_FUNCTION<%0...%1> %0vIn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242931)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242932)
		#define UNIQUE_FUNCTION<%0...%1> %0vIo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242932)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242933)
		#define UNIQUE_FUNCTION<%0...%1> %0vIp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242933)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242934)
		#define UNIQUE_FUNCTION<%0...%1> %0vIq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242935)
		#define UNIQUE_FUNCTION<%0...%1> %0vIr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (242935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242936)
		#define UNIQUE_FUNCTION<%0...%1> %0vIs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242937)
		#define UNIQUE_FUNCTION<%0...%1> %0vIt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242938)
		#define UNIQUE_FUNCTION<%0...%1> %0vIu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242939)
		#define UNIQUE_FUNCTION<%0...%1> %0vIv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242940)
		#define UNIQUE_FUNCTION<%0...%1> %0vIw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242941)
		#define UNIQUE_FUNCTION<%0...%1> %0vIx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (242941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242942)
		#define UNIQUE_FUNCTION<%0...%1> %0vIy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (242943)
		#define UNIQUE_FUNCTION<%0...%1> %0vIz%1
		#endinput
	#endif
#endif
