static stock const Y_UNIQUE_054848_054911_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_054848_054911
	#undef _inc_y_unique_054848_054911
#endif

#if UNIQUE_SYMBOL < (54855)
	#if UNIQUE_SYMBOL == (54847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54848)
		#define UNIQUE_FUNCTION<%0...%1> %0CO0%1
		#endinput
	#if UNIQUE_SYMBOL == (54848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54849)
		#define UNIQUE_FUNCTION<%0...%1> %0CO1%1
		#endinput
	#if UNIQUE_SYMBOL == (54849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54850)
		#define UNIQUE_FUNCTION<%0...%1> %0CO2%1
		#endinput
	#if UNIQUE_SYMBOL == (54850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54851)
		#define UNIQUE_FUNCTION<%0...%1> %0CO3%1
		#endinput
	#if UNIQUE_SYMBOL == (54851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54852)
		#define UNIQUE_FUNCTION<%0...%1> %0CO4%1
		#endinput
	#if UNIQUE_SYMBOL == (54852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54853)
		#define UNIQUE_FUNCTION<%0...%1> %0CO5%1
		#endinput
	#if UNIQUE_SYMBOL == (54853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54854)
		#define UNIQUE_FUNCTION<%0...%1> %0CO6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54855)
		#define UNIQUE_FUNCTION<%0...%1> %0CO7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54863)
	#elseif UNIQUE_SYMBOL == (54855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54856)
		#define UNIQUE_FUNCTION<%0...%1> %0CO8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54857)
		#define UNIQUE_FUNCTION<%0...%1> %0CO9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54858)
		#define UNIQUE_FUNCTION<%0...%1> %0CO@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54859)
		#define UNIQUE_FUNCTION<%0...%1> %0COA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54860)
		#define UNIQUE_FUNCTION<%0...%1> %0COB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54861)
		#define UNIQUE_FUNCTION<%0...%1> %0COC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54862)
		#define UNIQUE_FUNCTION<%0...%1> %0COD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54863)
		#define UNIQUE_FUNCTION<%0...%1> %0COE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54871)
	#elseif UNIQUE_SYMBOL == (54863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54864)
		#define UNIQUE_FUNCTION<%0...%1> %0COF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54865)
		#define UNIQUE_FUNCTION<%0...%1> %0COG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54866)
		#define UNIQUE_FUNCTION<%0...%1> %0COH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54867)
		#define UNIQUE_FUNCTION<%0...%1> %0COI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54868)
		#define UNIQUE_FUNCTION<%0...%1> %0COJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54869)
		#define UNIQUE_FUNCTION<%0...%1> %0COK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54870)
		#define UNIQUE_FUNCTION<%0...%1> %0COL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54871)
		#define UNIQUE_FUNCTION<%0...%1> %0COM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54879)
	#elseif UNIQUE_SYMBOL == (54871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54872)
		#define UNIQUE_FUNCTION<%0...%1> %0CON%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54873)
		#define UNIQUE_FUNCTION<%0...%1> %0COO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54874)
		#define UNIQUE_FUNCTION<%0...%1> %0COP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54875)
		#define UNIQUE_FUNCTION<%0...%1> %0COQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54876)
		#define UNIQUE_FUNCTION<%0...%1> %0COR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54877)
		#define UNIQUE_FUNCTION<%0...%1> %0COS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54878)
		#define UNIQUE_FUNCTION<%0...%1> %0COT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54879)
		#define UNIQUE_FUNCTION<%0...%1> %0COU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54887)
	#elseif UNIQUE_SYMBOL == (54879)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54880)
		#define UNIQUE_FUNCTION<%0...%1> %0COV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54880)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54881)
		#define UNIQUE_FUNCTION<%0...%1> %0COW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54881)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54882)
		#define UNIQUE_FUNCTION<%0...%1> %0COX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54882)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54883)
		#define UNIQUE_FUNCTION<%0...%1> %0COY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54883)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54884)
		#define UNIQUE_FUNCTION<%0...%1> %0COZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54884)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54885)
		#define UNIQUE_FUNCTION<%0...%1> %0CO_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54885)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54886)
		#define UNIQUE_FUNCTION<%0...%1> %0COa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54887)
		#define UNIQUE_FUNCTION<%0...%1> %0COb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54895)
	#elseif UNIQUE_SYMBOL == (54887)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54888)
		#define UNIQUE_FUNCTION<%0...%1> %0COc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54888)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54889)
		#define UNIQUE_FUNCTION<%0...%1> %0COd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54889)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54890)
		#define UNIQUE_FUNCTION<%0...%1> %0COe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54890)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54891)
		#define UNIQUE_FUNCTION<%0...%1> %0COf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54891)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54892)
		#define UNIQUE_FUNCTION<%0...%1> %0COg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54892)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54893)
		#define UNIQUE_FUNCTION<%0...%1> %0COh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54893)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54894)
		#define UNIQUE_FUNCTION<%0...%1> %0COi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54895)
		#define UNIQUE_FUNCTION<%0...%1> %0COj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (54903)
	#elseif UNIQUE_SYMBOL == (54895)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54896)
		#define UNIQUE_FUNCTION<%0...%1> %0COk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54896)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54897)
		#define UNIQUE_FUNCTION<%0...%1> %0COl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54897)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54898)
		#define UNIQUE_FUNCTION<%0...%1> %0COm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54898)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54899)
		#define UNIQUE_FUNCTION<%0...%1> %0COn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54899)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54900)
		#define UNIQUE_FUNCTION<%0...%1> %0COo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54900)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54901)
		#define UNIQUE_FUNCTION<%0...%1> %0COp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54901)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54902)
		#define UNIQUE_FUNCTION<%0...%1> %0COq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54903)
		#define UNIQUE_FUNCTION<%0...%1> %0COr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (54903)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54904)
		#define UNIQUE_FUNCTION<%0...%1> %0COs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54904)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54905)
		#define UNIQUE_FUNCTION<%0...%1> %0COt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54905)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54906)
		#define UNIQUE_FUNCTION<%0...%1> %0COu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54906)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54907)
		#define UNIQUE_FUNCTION<%0...%1> %0COv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54907)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54908)
		#define UNIQUE_FUNCTION<%0...%1> %0COw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54908)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54909)
		#define UNIQUE_FUNCTION<%0...%1> %0COx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (54909)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54910)
		#define UNIQUE_FUNCTION<%0...%1> %0COy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (54911)
		#define UNIQUE_FUNCTION<%0...%1> %0COz%1
		#endinput
	#endif
#endif
