static stock const Y_UNIQUE_186432_186495_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_186432_186495
	#undef _inc_y_unique_186432_186495
#endif

#if UNIQUE_SYMBOL < (186439)
	#if UNIQUE_SYMBOL == (186431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186432)
		#define UNIQUE_FUNCTION<%0...%1> %0hW0%1
		#endinput
	#if UNIQUE_SYMBOL == (186432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186433)
		#define UNIQUE_FUNCTION<%0...%1> %0hW1%1
		#endinput
	#if UNIQUE_SYMBOL == (186433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186434)
		#define UNIQUE_FUNCTION<%0...%1> %0hW2%1
		#endinput
	#if UNIQUE_SYMBOL == (186434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186435)
		#define UNIQUE_FUNCTION<%0...%1> %0hW3%1
		#endinput
	#if UNIQUE_SYMBOL == (186435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186436)
		#define UNIQUE_FUNCTION<%0...%1> %0hW4%1
		#endinput
	#if UNIQUE_SYMBOL == (186436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186437)
		#define UNIQUE_FUNCTION<%0...%1> %0hW5%1
		#endinput
	#if UNIQUE_SYMBOL == (186437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186438)
		#define UNIQUE_FUNCTION<%0...%1> %0hW6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186439)
		#define UNIQUE_FUNCTION<%0...%1> %0hW7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (186447)
	#elseif UNIQUE_SYMBOL == (186439)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186440)
		#define UNIQUE_FUNCTION<%0...%1> %0hW8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186440)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186441)
		#define UNIQUE_FUNCTION<%0...%1> %0hW9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186441)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186442)
		#define UNIQUE_FUNCTION<%0...%1> %0hW@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186442)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186443)
		#define UNIQUE_FUNCTION<%0...%1> %0hWA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186443)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186444)
		#define UNIQUE_FUNCTION<%0...%1> %0hWB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186444)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186445)
		#define UNIQUE_FUNCTION<%0...%1> %0hWC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186445)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186446)
		#define UNIQUE_FUNCTION<%0...%1> %0hWD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186447)
		#define UNIQUE_FUNCTION<%0...%1> %0hWE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (186455)
	#elseif UNIQUE_SYMBOL == (186447)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186448)
		#define UNIQUE_FUNCTION<%0...%1> %0hWF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186448)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186449)
		#define UNIQUE_FUNCTION<%0...%1> %0hWG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186449)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186450)
		#define UNIQUE_FUNCTION<%0...%1> %0hWH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186450)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186451)
		#define UNIQUE_FUNCTION<%0...%1> %0hWI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186451)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186452)
		#define UNIQUE_FUNCTION<%0...%1> %0hWJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186452)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186453)
		#define UNIQUE_FUNCTION<%0...%1> %0hWK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186453)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186454)
		#define UNIQUE_FUNCTION<%0...%1> %0hWL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186455)
		#define UNIQUE_FUNCTION<%0...%1> %0hWM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (186463)
	#elseif UNIQUE_SYMBOL == (186455)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186456)
		#define UNIQUE_FUNCTION<%0...%1> %0hWN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186456)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186457)
		#define UNIQUE_FUNCTION<%0...%1> %0hWO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186457)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186458)
		#define UNIQUE_FUNCTION<%0...%1> %0hWP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186458)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186459)
		#define UNIQUE_FUNCTION<%0...%1> %0hWQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186459)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186460)
		#define UNIQUE_FUNCTION<%0...%1> %0hWR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186460)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186461)
		#define UNIQUE_FUNCTION<%0...%1> %0hWS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186461)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186462)
		#define UNIQUE_FUNCTION<%0...%1> %0hWT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186463)
		#define UNIQUE_FUNCTION<%0...%1> %0hWU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (186471)
	#elseif UNIQUE_SYMBOL == (186463)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186464)
		#define UNIQUE_FUNCTION<%0...%1> %0hWV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186464)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186465)
		#define UNIQUE_FUNCTION<%0...%1> %0hWW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186465)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186466)
		#define UNIQUE_FUNCTION<%0...%1> %0hWX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186466)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186467)
		#define UNIQUE_FUNCTION<%0...%1> %0hWY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186467)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186468)
		#define UNIQUE_FUNCTION<%0...%1> %0hWZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186468)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186469)
		#define UNIQUE_FUNCTION<%0...%1> %0hW_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186469)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186470)
		#define UNIQUE_FUNCTION<%0...%1> %0hWa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186471)
		#define UNIQUE_FUNCTION<%0...%1> %0hWb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (186479)
	#elseif UNIQUE_SYMBOL == (186471)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186472)
		#define UNIQUE_FUNCTION<%0...%1> %0hWc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186472)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186473)
		#define UNIQUE_FUNCTION<%0...%1> %0hWd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186473)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186474)
		#define UNIQUE_FUNCTION<%0...%1> %0hWe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186474)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186475)
		#define UNIQUE_FUNCTION<%0...%1> %0hWf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186475)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186476)
		#define UNIQUE_FUNCTION<%0...%1> %0hWg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186476)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186477)
		#define UNIQUE_FUNCTION<%0...%1> %0hWh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186477)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186478)
		#define UNIQUE_FUNCTION<%0...%1> %0hWi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186479)
		#define UNIQUE_FUNCTION<%0...%1> %0hWj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (186487)
	#elseif UNIQUE_SYMBOL == (186479)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186480)
		#define UNIQUE_FUNCTION<%0...%1> %0hWk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186480)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186481)
		#define UNIQUE_FUNCTION<%0...%1> %0hWl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186481)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186482)
		#define UNIQUE_FUNCTION<%0...%1> %0hWm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186482)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186483)
		#define UNIQUE_FUNCTION<%0...%1> %0hWn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186483)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186484)
		#define UNIQUE_FUNCTION<%0...%1> %0hWo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186484)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186485)
		#define UNIQUE_FUNCTION<%0...%1> %0hWp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186485)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186486)
		#define UNIQUE_FUNCTION<%0...%1> %0hWq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186487)
		#define UNIQUE_FUNCTION<%0...%1> %0hWr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (186487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186488)
		#define UNIQUE_FUNCTION<%0...%1> %0hWs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186489)
		#define UNIQUE_FUNCTION<%0...%1> %0hWt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186490)
		#define UNIQUE_FUNCTION<%0...%1> %0hWu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186491)
		#define UNIQUE_FUNCTION<%0...%1> %0hWv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186492)
		#define UNIQUE_FUNCTION<%0...%1> %0hWw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186493)
		#define UNIQUE_FUNCTION<%0...%1> %0hWx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (186493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186494)
		#define UNIQUE_FUNCTION<%0...%1> %0hWy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (186495)
		#define UNIQUE_FUNCTION<%0...%1> %0hWz%1
		#endinput
	#endif
#endif
