static stock const Y_UNIQUE_015232_015295_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_015232_015295
	#undef _inc_y_unique_015232_015295
#endif

#if UNIQUE_SYMBOL < (15239)
	#if UNIQUE_SYMBOL == (15231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15232)
		#define UNIQUE_FUNCTION<%0...%1> %03i0%1
		#endinput
	#if UNIQUE_SYMBOL == (15232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15233)
		#define UNIQUE_FUNCTION<%0...%1> %03i1%1
		#endinput
	#if UNIQUE_SYMBOL == (15233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15234)
		#define UNIQUE_FUNCTION<%0...%1> %03i2%1
		#endinput
	#if UNIQUE_SYMBOL == (15234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15235)
		#define UNIQUE_FUNCTION<%0...%1> %03i3%1
		#endinput
	#if UNIQUE_SYMBOL == (15235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15236)
		#define UNIQUE_FUNCTION<%0...%1> %03i4%1
		#endinput
	#if UNIQUE_SYMBOL == (15236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15237)
		#define UNIQUE_FUNCTION<%0...%1> %03i5%1
		#endinput
	#if UNIQUE_SYMBOL == (15237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15238)
		#define UNIQUE_FUNCTION<%0...%1> %03i6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15239)
		#define UNIQUE_FUNCTION<%0...%1> %03i7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15247)
	#elseif UNIQUE_SYMBOL == (15239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15240)
		#define UNIQUE_FUNCTION<%0...%1> %03i8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15241)
		#define UNIQUE_FUNCTION<%0...%1> %03i9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15242)
		#define UNIQUE_FUNCTION<%0...%1> %03i@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15243)
		#define UNIQUE_FUNCTION<%0...%1> %03iA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15244)
		#define UNIQUE_FUNCTION<%0...%1> %03iB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15245)
		#define UNIQUE_FUNCTION<%0...%1> %03iC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15246)
		#define UNIQUE_FUNCTION<%0...%1> %03iD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15247)
		#define UNIQUE_FUNCTION<%0...%1> %03iE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15255)
	#elseif UNIQUE_SYMBOL == (15247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15248)
		#define UNIQUE_FUNCTION<%0...%1> %03iF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15249)
		#define UNIQUE_FUNCTION<%0...%1> %03iG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15250)
		#define UNIQUE_FUNCTION<%0...%1> %03iH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15251)
		#define UNIQUE_FUNCTION<%0...%1> %03iI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15252)
		#define UNIQUE_FUNCTION<%0...%1> %03iJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15253)
		#define UNIQUE_FUNCTION<%0...%1> %03iK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15254)
		#define UNIQUE_FUNCTION<%0...%1> %03iL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15255)
		#define UNIQUE_FUNCTION<%0...%1> %03iM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15263)
	#elseif UNIQUE_SYMBOL == (15255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15256)
		#define UNIQUE_FUNCTION<%0...%1> %03iN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15257)
		#define UNIQUE_FUNCTION<%0...%1> %03iO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15258)
		#define UNIQUE_FUNCTION<%0...%1> %03iP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15259)
		#define UNIQUE_FUNCTION<%0...%1> %03iQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15260)
		#define UNIQUE_FUNCTION<%0...%1> %03iR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15261)
		#define UNIQUE_FUNCTION<%0...%1> %03iS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15262)
		#define UNIQUE_FUNCTION<%0...%1> %03iT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15263)
		#define UNIQUE_FUNCTION<%0...%1> %03iU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15271)
	#elseif UNIQUE_SYMBOL == (15263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15264)
		#define UNIQUE_FUNCTION<%0...%1> %03iV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15265)
		#define UNIQUE_FUNCTION<%0...%1> %03iW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15266)
		#define UNIQUE_FUNCTION<%0...%1> %03iX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15267)
		#define UNIQUE_FUNCTION<%0...%1> %03iY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15268)
		#define UNIQUE_FUNCTION<%0...%1> %03iZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15269)
		#define UNIQUE_FUNCTION<%0...%1> %03i_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15270)
		#define UNIQUE_FUNCTION<%0...%1> %03ia%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15271)
		#define UNIQUE_FUNCTION<%0...%1> %03ib%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15279)
	#elseif UNIQUE_SYMBOL == (15271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15272)
		#define UNIQUE_FUNCTION<%0...%1> %03ic%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15273)
		#define UNIQUE_FUNCTION<%0...%1> %03id%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15274)
		#define UNIQUE_FUNCTION<%0...%1> %03ie%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15275)
		#define UNIQUE_FUNCTION<%0...%1> %03if%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15276)
		#define UNIQUE_FUNCTION<%0...%1> %03ig%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15277)
		#define UNIQUE_FUNCTION<%0...%1> %03ih%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15278)
		#define UNIQUE_FUNCTION<%0...%1> %03ii%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15279)
		#define UNIQUE_FUNCTION<%0...%1> %03ij%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15287)
	#elseif UNIQUE_SYMBOL == (15279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15280)
		#define UNIQUE_FUNCTION<%0...%1> %03ik%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15281)
		#define UNIQUE_FUNCTION<%0...%1> %03il%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15282)
		#define UNIQUE_FUNCTION<%0...%1> %03im%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15283)
		#define UNIQUE_FUNCTION<%0...%1> %03in%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15284)
		#define UNIQUE_FUNCTION<%0...%1> %03io%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15285)
		#define UNIQUE_FUNCTION<%0...%1> %03ip%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15286)
		#define UNIQUE_FUNCTION<%0...%1> %03iq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15287)
		#define UNIQUE_FUNCTION<%0...%1> %03ir%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (15287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15288)
		#define UNIQUE_FUNCTION<%0...%1> %03is%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15289)
		#define UNIQUE_FUNCTION<%0...%1> %03it%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15290)
		#define UNIQUE_FUNCTION<%0...%1> %03iu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15291)
		#define UNIQUE_FUNCTION<%0...%1> %03iv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15292)
		#define UNIQUE_FUNCTION<%0...%1> %03iw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15293)
		#define UNIQUE_FUNCTION<%0...%1> %03ix%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15294)
		#define UNIQUE_FUNCTION<%0...%1> %03iy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15295)
		#define UNIQUE_FUNCTION<%0...%1> %03iz%1
		#endinput
	#endif
#endif
