static stock const Y_UNIQUE_101056_101119_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_101056_101119
	#undef _inc_y_unique_101056_101119
#endif

#if UNIQUE_SYMBOL < (101063)
	#if UNIQUE_SYMBOL == (101055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101056)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf0%1
		#endinput
	#if UNIQUE_SYMBOL == (101056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101057)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf1%1
		#endinput
	#if UNIQUE_SYMBOL == (101057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101058)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf2%1
		#endinput
	#if UNIQUE_SYMBOL == (101058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101059)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf3%1
		#endinput
	#if UNIQUE_SYMBOL == (101059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101060)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf4%1
		#endinput
	#if UNIQUE_SYMBOL == (101060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101061)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf5%1
		#endinput
	#if UNIQUE_SYMBOL == (101061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101062)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101063)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (101071)
	#elseif UNIQUE_SYMBOL == (101063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101064)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101065)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101066)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101067)
		#define UNIQUE_FUNCTION<%0...%1> %0NfA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101068)
		#define UNIQUE_FUNCTION<%0...%1> %0NfB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101069)
		#define UNIQUE_FUNCTION<%0...%1> %0NfC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101070)
		#define UNIQUE_FUNCTION<%0...%1> %0NfD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101071)
		#define UNIQUE_FUNCTION<%0...%1> %0NfE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (101079)
	#elseif UNIQUE_SYMBOL == (101071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101072)
		#define UNIQUE_FUNCTION<%0...%1> %0NfF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101073)
		#define UNIQUE_FUNCTION<%0...%1> %0NfG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101074)
		#define UNIQUE_FUNCTION<%0...%1> %0NfH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101075)
		#define UNIQUE_FUNCTION<%0...%1> %0NfI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101076)
		#define UNIQUE_FUNCTION<%0...%1> %0NfJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101077)
		#define UNIQUE_FUNCTION<%0...%1> %0NfK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101078)
		#define UNIQUE_FUNCTION<%0...%1> %0NfL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101079)
		#define UNIQUE_FUNCTION<%0...%1> %0NfM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (101087)
	#elseif UNIQUE_SYMBOL == (101079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101080)
		#define UNIQUE_FUNCTION<%0...%1> %0NfN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101081)
		#define UNIQUE_FUNCTION<%0...%1> %0NfO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101082)
		#define UNIQUE_FUNCTION<%0...%1> %0NfP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101083)
		#define UNIQUE_FUNCTION<%0...%1> %0NfQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101084)
		#define UNIQUE_FUNCTION<%0...%1> %0NfR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101085)
		#define UNIQUE_FUNCTION<%0...%1> %0NfS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101086)
		#define UNIQUE_FUNCTION<%0...%1> %0NfT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101087)
		#define UNIQUE_FUNCTION<%0...%1> %0NfU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (101095)
	#elseif UNIQUE_SYMBOL == (101087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101088)
		#define UNIQUE_FUNCTION<%0...%1> %0NfV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101089)
		#define UNIQUE_FUNCTION<%0...%1> %0NfW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101090)
		#define UNIQUE_FUNCTION<%0...%1> %0NfX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101091)
		#define UNIQUE_FUNCTION<%0...%1> %0NfY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101092)
		#define UNIQUE_FUNCTION<%0...%1> %0NfZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101093)
		#define UNIQUE_FUNCTION<%0...%1> %0Nf_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101094)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101095)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (101103)
	#elseif UNIQUE_SYMBOL == (101095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101096)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101097)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101098)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101099)
		#define UNIQUE_FUNCTION<%0...%1> %0Nff%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101100)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101101)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101102)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101103)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (101111)
	#elseif UNIQUE_SYMBOL == (101103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101104)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101105)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101106)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101107)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101108)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101109)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101110)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101111)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (101111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101112)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101113)
		#define UNIQUE_FUNCTION<%0...%1> %0Nft%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101114)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101115)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101116)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101117)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (101117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101118)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (101119)
		#define UNIQUE_FUNCTION<%0...%1> %0Nfz%1
		#endinput
	#endif
#endif
