static stock const Y_UNIQUE_079360_079423_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_079360_079423
	#undef _inc_y_unique_079360_079423
#endif

#if UNIQUE_SYMBOL < (79367)
	#if UNIQUE_SYMBOL == (79359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79360)
		#define UNIQUE_FUNCTION<%0...%1> %0IN0%1
		#endinput
	#if UNIQUE_SYMBOL == (79360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79361)
		#define UNIQUE_FUNCTION<%0...%1> %0IN1%1
		#endinput
	#if UNIQUE_SYMBOL == (79361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79362)
		#define UNIQUE_FUNCTION<%0...%1> %0IN2%1
		#endinput
	#if UNIQUE_SYMBOL == (79362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79363)
		#define UNIQUE_FUNCTION<%0...%1> %0IN3%1
		#endinput
	#if UNIQUE_SYMBOL == (79363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79364)
		#define UNIQUE_FUNCTION<%0...%1> %0IN4%1
		#endinput
	#if UNIQUE_SYMBOL == (79364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79365)
		#define UNIQUE_FUNCTION<%0...%1> %0IN5%1
		#endinput
	#if UNIQUE_SYMBOL == (79365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79366)
		#define UNIQUE_FUNCTION<%0...%1> %0IN6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79367)
		#define UNIQUE_FUNCTION<%0...%1> %0IN7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79375)
	#elseif UNIQUE_SYMBOL == (79367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79368)
		#define UNIQUE_FUNCTION<%0...%1> %0IN8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79369)
		#define UNIQUE_FUNCTION<%0...%1> %0IN9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79370)
		#define UNIQUE_FUNCTION<%0...%1> %0IN@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79371)
		#define UNIQUE_FUNCTION<%0...%1> %0INA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79372)
		#define UNIQUE_FUNCTION<%0...%1> %0INB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79373)
		#define UNIQUE_FUNCTION<%0...%1> %0INC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79374)
		#define UNIQUE_FUNCTION<%0...%1> %0IND%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79375)
		#define UNIQUE_FUNCTION<%0...%1> %0INE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79383)
	#elseif UNIQUE_SYMBOL == (79375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79376)
		#define UNIQUE_FUNCTION<%0...%1> %0INF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79377)
		#define UNIQUE_FUNCTION<%0...%1> %0ING%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79378)
		#define UNIQUE_FUNCTION<%0...%1> %0INH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79379)
		#define UNIQUE_FUNCTION<%0...%1> %0INI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79380)
		#define UNIQUE_FUNCTION<%0...%1> %0INJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79381)
		#define UNIQUE_FUNCTION<%0...%1> %0INK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79382)
		#define UNIQUE_FUNCTION<%0...%1> %0INL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79383)
		#define UNIQUE_FUNCTION<%0...%1> %0INM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79391)
	#elseif UNIQUE_SYMBOL == (79383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79384)
		#define UNIQUE_FUNCTION<%0...%1> %0INN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79385)
		#define UNIQUE_FUNCTION<%0...%1> %0INO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79386)
		#define UNIQUE_FUNCTION<%0...%1> %0INP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79387)
		#define UNIQUE_FUNCTION<%0...%1> %0INQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79388)
		#define UNIQUE_FUNCTION<%0...%1> %0INR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79389)
		#define UNIQUE_FUNCTION<%0...%1> %0INS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79390)
		#define UNIQUE_FUNCTION<%0...%1> %0INT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79391)
		#define UNIQUE_FUNCTION<%0...%1> %0INU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79399)
	#elseif UNIQUE_SYMBOL == (79391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79392)
		#define UNIQUE_FUNCTION<%0...%1> %0INV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79393)
		#define UNIQUE_FUNCTION<%0...%1> %0INW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79394)
		#define UNIQUE_FUNCTION<%0...%1> %0INX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79395)
		#define UNIQUE_FUNCTION<%0...%1> %0INY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79396)
		#define UNIQUE_FUNCTION<%0...%1> %0INZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79397)
		#define UNIQUE_FUNCTION<%0...%1> %0IN_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79398)
		#define UNIQUE_FUNCTION<%0...%1> %0INa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79399)
		#define UNIQUE_FUNCTION<%0...%1> %0INb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79407)
	#elseif UNIQUE_SYMBOL == (79399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79400)
		#define UNIQUE_FUNCTION<%0...%1> %0INc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79401)
		#define UNIQUE_FUNCTION<%0...%1> %0INd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79402)
		#define UNIQUE_FUNCTION<%0...%1> %0INe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79403)
		#define UNIQUE_FUNCTION<%0...%1> %0INf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79404)
		#define UNIQUE_FUNCTION<%0...%1> %0INg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79405)
		#define UNIQUE_FUNCTION<%0...%1> %0INh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79406)
		#define UNIQUE_FUNCTION<%0...%1> %0INi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79407)
		#define UNIQUE_FUNCTION<%0...%1> %0INj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (79415)
	#elseif UNIQUE_SYMBOL == (79407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79408)
		#define UNIQUE_FUNCTION<%0...%1> %0INk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79409)
		#define UNIQUE_FUNCTION<%0...%1> %0INl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79410)
		#define UNIQUE_FUNCTION<%0...%1> %0INm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79411)
		#define UNIQUE_FUNCTION<%0...%1> %0INn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79412)
		#define UNIQUE_FUNCTION<%0...%1> %0INo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79413)
		#define UNIQUE_FUNCTION<%0...%1> %0INp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79414)
		#define UNIQUE_FUNCTION<%0...%1> %0INq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79415)
		#define UNIQUE_FUNCTION<%0...%1> %0INr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (79415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79416)
		#define UNIQUE_FUNCTION<%0...%1> %0INs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79417)
		#define UNIQUE_FUNCTION<%0...%1> %0INt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79418)
		#define UNIQUE_FUNCTION<%0...%1> %0INu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79419)
		#define UNIQUE_FUNCTION<%0...%1> %0INv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79420)
		#define UNIQUE_FUNCTION<%0...%1> %0INw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79421)
		#define UNIQUE_FUNCTION<%0...%1> %0INx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (79421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79422)
		#define UNIQUE_FUNCTION<%0...%1> %0INy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (79423)
		#define UNIQUE_FUNCTION<%0...%1> %0INz%1
		#endinput
	#endif
#endif
