static stock const Y_UNIQUE_067712_067775_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_067712_067775
	#undef _inc_y_unique_067712_067775
#endif

#if UNIQUE_SYMBOL < (67719)
	#if UNIQUE_SYMBOL == (67711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67712)
		#define UNIQUE_FUNCTION<%0...%1> %0FX0%1
		#endinput
	#if UNIQUE_SYMBOL == (67712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67713)
		#define UNIQUE_FUNCTION<%0...%1> %0FX1%1
		#endinput
	#if UNIQUE_SYMBOL == (67713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67714)
		#define UNIQUE_FUNCTION<%0...%1> %0FX2%1
		#endinput
	#if UNIQUE_SYMBOL == (67714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67715)
		#define UNIQUE_FUNCTION<%0...%1> %0FX3%1
		#endinput
	#if UNIQUE_SYMBOL == (67715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67716)
		#define UNIQUE_FUNCTION<%0...%1> %0FX4%1
		#endinput
	#if UNIQUE_SYMBOL == (67716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67717)
		#define UNIQUE_FUNCTION<%0...%1> %0FX5%1
		#endinput
	#if UNIQUE_SYMBOL == (67717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67718)
		#define UNIQUE_FUNCTION<%0...%1> %0FX6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67719)
		#define UNIQUE_FUNCTION<%0...%1> %0FX7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67727)
	#elseif UNIQUE_SYMBOL == (67719)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67720)
		#define UNIQUE_FUNCTION<%0...%1> %0FX8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67720)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67721)
		#define UNIQUE_FUNCTION<%0...%1> %0FX9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67721)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67722)
		#define UNIQUE_FUNCTION<%0...%1> %0FX@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67722)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67723)
		#define UNIQUE_FUNCTION<%0...%1> %0FXA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67723)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67724)
		#define UNIQUE_FUNCTION<%0...%1> %0FXB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67724)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67725)
		#define UNIQUE_FUNCTION<%0...%1> %0FXC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67725)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67726)
		#define UNIQUE_FUNCTION<%0...%1> %0FXD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67727)
		#define UNIQUE_FUNCTION<%0...%1> %0FXE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67735)
	#elseif UNIQUE_SYMBOL == (67727)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67728)
		#define UNIQUE_FUNCTION<%0...%1> %0FXF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67728)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67729)
		#define UNIQUE_FUNCTION<%0...%1> %0FXG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67729)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67730)
		#define UNIQUE_FUNCTION<%0...%1> %0FXH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67730)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67731)
		#define UNIQUE_FUNCTION<%0...%1> %0FXI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67731)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67732)
		#define UNIQUE_FUNCTION<%0...%1> %0FXJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67732)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67733)
		#define UNIQUE_FUNCTION<%0...%1> %0FXK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67733)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67734)
		#define UNIQUE_FUNCTION<%0...%1> %0FXL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67735)
		#define UNIQUE_FUNCTION<%0...%1> %0FXM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67743)
	#elseif UNIQUE_SYMBOL == (67735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67736)
		#define UNIQUE_FUNCTION<%0...%1> %0FXN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67737)
		#define UNIQUE_FUNCTION<%0...%1> %0FXO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67738)
		#define UNIQUE_FUNCTION<%0...%1> %0FXP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67739)
		#define UNIQUE_FUNCTION<%0...%1> %0FXQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67740)
		#define UNIQUE_FUNCTION<%0...%1> %0FXR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67741)
		#define UNIQUE_FUNCTION<%0...%1> %0FXS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67742)
		#define UNIQUE_FUNCTION<%0...%1> %0FXT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67743)
		#define UNIQUE_FUNCTION<%0...%1> %0FXU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67751)
	#elseif UNIQUE_SYMBOL == (67743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67744)
		#define UNIQUE_FUNCTION<%0...%1> %0FXV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67745)
		#define UNIQUE_FUNCTION<%0...%1> %0FXW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67746)
		#define UNIQUE_FUNCTION<%0...%1> %0FXX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67747)
		#define UNIQUE_FUNCTION<%0...%1> %0FXY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67748)
		#define UNIQUE_FUNCTION<%0...%1> %0FXZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67749)
		#define UNIQUE_FUNCTION<%0...%1> %0FX_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67750)
		#define UNIQUE_FUNCTION<%0...%1> %0FXa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67751)
		#define UNIQUE_FUNCTION<%0...%1> %0FXb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67759)
	#elseif UNIQUE_SYMBOL == (67751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67752)
		#define UNIQUE_FUNCTION<%0...%1> %0FXc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67753)
		#define UNIQUE_FUNCTION<%0...%1> %0FXd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67754)
		#define UNIQUE_FUNCTION<%0...%1> %0FXe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67755)
		#define UNIQUE_FUNCTION<%0...%1> %0FXf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67756)
		#define UNIQUE_FUNCTION<%0...%1> %0FXg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67757)
		#define UNIQUE_FUNCTION<%0...%1> %0FXh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67758)
		#define UNIQUE_FUNCTION<%0...%1> %0FXi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67759)
		#define UNIQUE_FUNCTION<%0...%1> %0FXj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (67767)
	#elseif UNIQUE_SYMBOL == (67759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67760)
		#define UNIQUE_FUNCTION<%0...%1> %0FXk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67761)
		#define UNIQUE_FUNCTION<%0...%1> %0FXl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67762)
		#define UNIQUE_FUNCTION<%0...%1> %0FXm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67763)
		#define UNIQUE_FUNCTION<%0...%1> %0FXn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67764)
		#define UNIQUE_FUNCTION<%0...%1> %0FXo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67765)
		#define UNIQUE_FUNCTION<%0...%1> %0FXp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67766)
		#define UNIQUE_FUNCTION<%0...%1> %0FXq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67767)
		#define UNIQUE_FUNCTION<%0...%1> %0FXr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (67767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67768)
		#define UNIQUE_FUNCTION<%0...%1> %0FXs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67769)
		#define UNIQUE_FUNCTION<%0...%1> %0FXt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67770)
		#define UNIQUE_FUNCTION<%0...%1> %0FXu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67771)
		#define UNIQUE_FUNCTION<%0...%1> %0FXv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67772)
		#define UNIQUE_FUNCTION<%0...%1> %0FXw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67773)
		#define UNIQUE_FUNCTION<%0...%1> %0FXx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (67773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67774)
		#define UNIQUE_FUNCTION<%0...%1> %0FXy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (67775)
		#define UNIQUE_FUNCTION<%0...%1> %0FXz%1
		#endinput
	#endif
#endif
