static stock const Y_UNIQUE_025216_025279_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_025216_025279
	#undef _inc_y_unique_025216_025279
#endif

#if UNIQUE_SYMBOL < (25223)
	#if UNIQUE_SYMBOL == (25215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25216)
		#define UNIQUE_FUNCTION<%0...%1> %06@0%1
		#endinput
	#if UNIQUE_SYMBOL == (25216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25217)
		#define UNIQUE_FUNCTION<%0...%1> %06@1%1
		#endinput
	#if UNIQUE_SYMBOL == (25217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25218)
		#define UNIQUE_FUNCTION<%0...%1> %06@2%1
		#endinput
	#if UNIQUE_SYMBOL == (25218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25219)
		#define UNIQUE_FUNCTION<%0...%1> %06@3%1
		#endinput
	#if UNIQUE_SYMBOL == (25219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25220)
		#define UNIQUE_FUNCTION<%0...%1> %06@4%1
		#endinput
	#if UNIQUE_SYMBOL == (25220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25221)
		#define UNIQUE_FUNCTION<%0...%1> %06@5%1
		#endinput
	#if UNIQUE_SYMBOL == (25221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25222)
		#define UNIQUE_FUNCTION<%0...%1> %06@6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25223)
		#define UNIQUE_FUNCTION<%0...%1> %06@7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25231)
	#elseif UNIQUE_SYMBOL == (25223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25224)
		#define UNIQUE_FUNCTION<%0...%1> %06@8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25225)
		#define UNIQUE_FUNCTION<%0...%1> %06@9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25226)
		#define UNIQUE_FUNCTION<%0...%1> %06@@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25227)
		#define UNIQUE_FUNCTION<%0...%1> %06@A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25228)
		#define UNIQUE_FUNCTION<%0...%1> %06@B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25229)
		#define UNIQUE_FUNCTION<%0...%1> %06@C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25230)
		#define UNIQUE_FUNCTION<%0...%1> %06@D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25231)
		#define UNIQUE_FUNCTION<%0...%1> %06@E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25239)
	#elseif UNIQUE_SYMBOL == (25231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25232)
		#define UNIQUE_FUNCTION<%0...%1> %06@F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25233)
		#define UNIQUE_FUNCTION<%0...%1> %06@G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25234)
		#define UNIQUE_FUNCTION<%0...%1> %06@H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25235)
		#define UNIQUE_FUNCTION<%0...%1> %06@I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25236)
		#define UNIQUE_FUNCTION<%0...%1> %06@J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25237)
		#define UNIQUE_FUNCTION<%0...%1> %06@K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25238)
		#define UNIQUE_FUNCTION<%0...%1> %06@L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25239)
		#define UNIQUE_FUNCTION<%0...%1> %06@M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25247)
	#elseif UNIQUE_SYMBOL == (25239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25240)
		#define UNIQUE_FUNCTION<%0...%1> %06@N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25241)
		#define UNIQUE_FUNCTION<%0...%1> %06@O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25242)
		#define UNIQUE_FUNCTION<%0...%1> %06@P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25243)
		#define UNIQUE_FUNCTION<%0...%1> %06@Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25244)
		#define UNIQUE_FUNCTION<%0...%1> %06@R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25245)
		#define UNIQUE_FUNCTION<%0...%1> %06@S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25246)
		#define UNIQUE_FUNCTION<%0...%1> %06@T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25247)
		#define UNIQUE_FUNCTION<%0...%1> %06@U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25255)
	#elseif UNIQUE_SYMBOL == (25247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25248)
		#define UNIQUE_FUNCTION<%0...%1> %06@V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25249)
		#define UNIQUE_FUNCTION<%0...%1> %06@W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25250)
		#define UNIQUE_FUNCTION<%0...%1> %06@X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25251)
		#define UNIQUE_FUNCTION<%0...%1> %06@Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25252)
		#define UNIQUE_FUNCTION<%0...%1> %06@Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25253)
		#define UNIQUE_FUNCTION<%0...%1> %06@_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25254)
		#define UNIQUE_FUNCTION<%0...%1> %06@a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25255)
		#define UNIQUE_FUNCTION<%0...%1> %06@b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25263)
	#elseif UNIQUE_SYMBOL == (25255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25256)
		#define UNIQUE_FUNCTION<%0...%1> %06@c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25257)
		#define UNIQUE_FUNCTION<%0...%1> %06@d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25258)
		#define UNIQUE_FUNCTION<%0...%1> %06@e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25259)
		#define UNIQUE_FUNCTION<%0...%1> %06@f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25260)
		#define UNIQUE_FUNCTION<%0...%1> %06@g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25261)
		#define UNIQUE_FUNCTION<%0...%1> %06@h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25262)
		#define UNIQUE_FUNCTION<%0...%1> %06@i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25263)
		#define UNIQUE_FUNCTION<%0...%1> %06@j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25271)
	#elseif UNIQUE_SYMBOL == (25263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25264)
		#define UNIQUE_FUNCTION<%0...%1> %06@k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25265)
		#define UNIQUE_FUNCTION<%0...%1> %06@l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25266)
		#define UNIQUE_FUNCTION<%0...%1> %06@m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25267)
		#define UNIQUE_FUNCTION<%0...%1> %06@n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25268)
		#define UNIQUE_FUNCTION<%0...%1> %06@o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25269)
		#define UNIQUE_FUNCTION<%0...%1> %06@p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25270)
		#define UNIQUE_FUNCTION<%0...%1> %06@q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25271)
		#define UNIQUE_FUNCTION<%0...%1> %06@r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (25271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25272)
		#define UNIQUE_FUNCTION<%0...%1> %06@s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25273)
		#define UNIQUE_FUNCTION<%0...%1> %06@t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25274)
		#define UNIQUE_FUNCTION<%0...%1> %06@u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25275)
		#define UNIQUE_FUNCTION<%0...%1> %06@v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25276)
		#define UNIQUE_FUNCTION<%0...%1> %06@w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25277)
		#define UNIQUE_FUNCTION<%0...%1> %06@x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25278)
		#define UNIQUE_FUNCTION<%0...%1> %06@y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25279)
		#define UNIQUE_FUNCTION<%0...%1> %06@z%1
		#endinput
	#endif
#endif
