static stock const Y_UNIQUE_030976_031039_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_030976_031039
	#undef _inc_y_unique_030976_031039
#endif

#if UNIQUE_SYMBOL < (30983)
	#if UNIQUE_SYMBOL == (30975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30976)
		#define UNIQUE_FUNCTION<%0...%1> %07Z0%1
		#endinput
	#if UNIQUE_SYMBOL == (30976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30977)
		#define UNIQUE_FUNCTION<%0...%1> %07Z1%1
		#endinput
	#if UNIQUE_SYMBOL == (30977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30978)
		#define UNIQUE_FUNCTION<%0...%1> %07Z2%1
		#endinput
	#if UNIQUE_SYMBOL == (30978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30979)
		#define UNIQUE_FUNCTION<%0...%1> %07Z3%1
		#endinput
	#if UNIQUE_SYMBOL == (30979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30980)
		#define UNIQUE_FUNCTION<%0...%1> %07Z4%1
		#endinput
	#if UNIQUE_SYMBOL == (30980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30981)
		#define UNIQUE_FUNCTION<%0...%1> %07Z5%1
		#endinput
	#if UNIQUE_SYMBOL == (30981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30982)
		#define UNIQUE_FUNCTION<%0...%1> %07Z6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30983)
		#define UNIQUE_FUNCTION<%0...%1> %07Z7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30991)
	#elseif UNIQUE_SYMBOL == (30983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30984)
		#define UNIQUE_FUNCTION<%0...%1> %07Z8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30985)
		#define UNIQUE_FUNCTION<%0...%1> %07Z9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30986)
		#define UNIQUE_FUNCTION<%0...%1> %07Z@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30987)
		#define UNIQUE_FUNCTION<%0...%1> %07ZA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30988)
		#define UNIQUE_FUNCTION<%0...%1> %07ZB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30989)
		#define UNIQUE_FUNCTION<%0...%1> %07ZC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30990)
		#define UNIQUE_FUNCTION<%0...%1> %07ZD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30991)
		#define UNIQUE_FUNCTION<%0...%1> %07ZE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30999)
	#elseif UNIQUE_SYMBOL == (30991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30992)
		#define UNIQUE_FUNCTION<%0...%1> %07ZF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30993)
		#define UNIQUE_FUNCTION<%0...%1> %07ZG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30994)
		#define UNIQUE_FUNCTION<%0...%1> %07ZH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30995)
		#define UNIQUE_FUNCTION<%0...%1> %07ZI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30996)
		#define UNIQUE_FUNCTION<%0...%1> %07ZJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30997)
		#define UNIQUE_FUNCTION<%0...%1> %07ZK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30998)
		#define UNIQUE_FUNCTION<%0...%1> %07ZL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30999)
		#define UNIQUE_FUNCTION<%0...%1> %07ZM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31007)
	#elseif UNIQUE_SYMBOL == (30999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31000)
		#define UNIQUE_FUNCTION<%0...%1> %07ZN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31001)
		#define UNIQUE_FUNCTION<%0...%1> %07ZO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31002)
		#define UNIQUE_FUNCTION<%0...%1> %07ZP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31003)
		#define UNIQUE_FUNCTION<%0...%1> %07ZQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31004)
		#define UNIQUE_FUNCTION<%0...%1> %07ZR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31005)
		#define UNIQUE_FUNCTION<%0...%1> %07ZS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31006)
		#define UNIQUE_FUNCTION<%0...%1> %07ZT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31007)
		#define UNIQUE_FUNCTION<%0...%1> %07ZU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31015)
	#elseif UNIQUE_SYMBOL == (31007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31008)
		#define UNIQUE_FUNCTION<%0...%1> %07ZV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31009)
		#define UNIQUE_FUNCTION<%0...%1> %07ZW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31010)
		#define UNIQUE_FUNCTION<%0...%1> %07ZX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31011)
		#define UNIQUE_FUNCTION<%0...%1> %07ZY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31012)
		#define UNIQUE_FUNCTION<%0...%1> %07ZZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31013)
		#define UNIQUE_FUNCTION<%0...%1> %07Z_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31014)
		#define UNIQUE_FUNCTION<%0...%1> %07Za%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31015)
		#define UNIQUE_FUNCTION<%0...%1> %07Zb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31023)
	#elseif UNIQUE_SYMBOL == (31015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31016)
		#define UNIQUE_FUNCTION<%0...%1> %07Zc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31017)
		#define UNIQUE_FUNCTION<%0...%1> %07Zd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31018)
		#define UNIQUE_FUNCTION<%0...%1> %07Ze%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31019)
		#define UNIQUE_FUNCTION<%0...%1> %07Zf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31020)
		#define UNIQUE_FUNCTION<%0...%1> %07Zg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31021)
		#define UNIQUE_FUNCTION<%0...%1> %07Zh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31022)
		#define UNIQUE_FUNCTION<%0...%1> %07Zi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31023)
		#define UNIQUE_FUNCTION<%0...%1> %07Zj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31031)
	#elseif UNIQUE_SYMBOL == (31023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31024)
		#define UNIQUE_FUNCTION<%0...%1> %07Zk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31025)
		#define UNIQUE_FUNCTION<%0...%1> %07Zl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31026)
		#define UNIQUE_FUNCTION<%0...%1> %07Zm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31027)
		#define UNIQUE_FUNCTION<%0...%1> %07Zn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31028)
		#define UNIQUE_FUNCTION<%0...%1> %07Zo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31029)
		#define UNIQUE_FUNCTION<%0...%1> %07Zp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31030)
		#define UNIQUE_FUNCTION<%0...%1> %07Zq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31031)
		#define UNIQUE_FUNCTION<%0...%1> %07Zr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (31031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31032)
		#define UNIQUE_FUNCTION<%0...%1> %07Zs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31033)
		#define UNIQUE_FUNCTION<%0...%1> %07Zt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31034)
		#define UNIQUE_FUNCTION<%0...%1> %07Zu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31035)
		#define UNIQUE_FUNCTION<%0...%1> %07Zv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31036)
		#define UNIQUE_FUNCTION<%0...%1> %07Zw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31037)
		#define UNIQUE_FUNCTION<%0...%1> %07Zx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31038)
		#define UNIQUE_FUNCTION<%0...%1> %07Zy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31039)
		#define UNIQUE_FUNCTION<%0...%1> %07Zz%1
		#endinput
	#endif
#endif
