static stock const Y_UNIQUE_030656_030719_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_030656_030719
	#undef _inc_y_unique_030656_030719
#endif

#if UNIQUE_SYMBOL < (30663)
	#if UNIQUE_SYMBOL == (30655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30656)
		#define UNIQUE_FUNCTION<%0...%1> %07U0%1
		#endinput
	#if UNIQUE_SYMBOL == (30656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30657)
		#define UNIQUE_FUNCTION<%0...%1> %07U1%1
		#endinput
	#if UNIQUE_SYMBOL == (30657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30658)
		#define UNIQUE_FUNCTION<%0...%1> %07U2%1
		#endinput
	#if UNIQUE_SYMBOL == (30658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30659)
		#define UNIQUE_FUNCTION<%0...%1> %07U3%1
		#endinput
	#if UNIQUE_SYMBOL == (30659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30660)
		#define UNIQUE_FUNCTION<%0...%1> %07U4%1
		#endinput
	#if UNIQUE_SYMBOL == (30660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30661)
		#define UNIQUE_FUNCTION<%0...%1> %07U5%1
		#endinput
	#if UNIQUE_SYMBOL == (30661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30662)
		#define UNIQUE_FUNCTION<%0...%1> %07U6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30663)
		#define UNIQUE_FUNCTION<%0...%1> %07U7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30671)
	#elseif UNIQUE_SYMBOL == (30663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30664)
		#define UNIQUE_FUNCTION<%0...%1> %07U8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30665)
		#define UNIQUE_FUNCTION<%0...%1> %07U9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30666)
		#define UNIQUE_FUNCTION<%0...%1> %07U@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30667)
		#define UNIQUE_FUNCTION<%0...%1> %07UA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30668)
		#define UNIQUE_FUNCTION<%0...%1> %07UB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30669)
		#define UNIQUE_FUNCTION<%0...%1> %07UC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30670)
		#define UNIQUE_FUNCTION<%0...%1> %07UD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30671)
		#define UNIQUE_FUNCTION<%0...%1> %07UE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30679)
	#elseif UNIQUE_SYMBOL == (30671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30672)
		#define UNIQUE_FUNCTION<%0...%1> %07UF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30673)
		#define UNIQUE_FUNCTION<%0...%1> %07UG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30674)
		#define UNIQUE_FUNCTION<%0...%1> %07UH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30675)
		#define UNIQUE_FUNCTION<%0...%1> %07UI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30676)
		#define UNIQUE_FUNCTION<%0...%1> %07UJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30677)
		#define UNIQUE_FUNCTION<%0...%1> %07UK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30678)
		#define UNIQUE_FUNCTION<%0...%1> %07UL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30679)
		#define UNIQUE_FUNCTION<%0...%1> %07UM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30687)
	#elseif UNIQUE_SYMBOL == (30679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30680)
		#define UNIQUE_FUNCTION<%0...%1> %07UN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30681)
		#define UNIQUE_FUNCTION<%0...%1> %07UO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30682)
		#define UNIQUE_FUNCTION<%0...%1> %07UP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30683)
		#define UNIQUE_FUNCTION<%0...%1> %07UQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30684)
		#define UNIQUE_FUNCTION<%0...%1> %07UR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30685)
		#define UNIQUE_FUNCTION<%0...%1> %07US%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30686)
		#define UNIQUE_FUNCTION<%0...%1> %07UT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30687)
		#define UNIQUE_FUNCTION<%0...%1> %07UU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30695)
	#elseif UNIQUE_SYMBOL == (30687)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30688)
		#define UNIQUE_FUNCTION<%0...%1> %07UV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30688)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30689)
		#define UNIQUE_FUNCTION<%0...%1> %07UW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30689)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30690)
		#define UNIQUE_FUNCTION<%0...%1> %07UX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30690)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30691)
		#define UNIQUE_FUNCTION<%0...%1> %07UY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30691)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30692)
		#define UNIQUE_FUNCTION<%0...%1> %07UZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30692)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30693)
		#define UNIQUE_FUNCTION<%0...%1> %07U_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30693)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30694)
		#define UNIQUE_FUNCTION<%0...%1> %07Ua%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30695)
		#define UNIQUE_FUNCTION<%0...%1> %07Ub%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30703)
	#elseif UNIQUE_SYMBOL == (30695)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30696)
		#define UNIQUE_FUNCTION<%0...%1> %07Uc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30696)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30697)
		#define UNIQUE_FUNCTION<%0...%1> %07Ud%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30697)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30698)
		#define UNIQUE_FUNCTION<%0...%1> %07Ue%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30698)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30699)
		#define UNIQUE_FUNCTION<%0...%1> %07Uf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30699)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30700)
		#define UNIQUE_FUNCTION<%0...%1> %07Ug%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30700)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30701)
		#define UNIQUE_FUNCTION<%0...%1> %07Uh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30701)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30702)
		#define UNIQUE_FUNCTION<%0...%1> %07Ui%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30703)
		#define UNIQUE_FUNCTION<%0...%1> %07Uj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (30711)
	#elseif UNIQUE_SYMBOL == (30703)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30704)
		#define UNIQUE_FUNCTION<%0...%1> %07Uk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30704)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30705)
		#define UNIQUE_FUNCTION<%0...%1> %07Ul%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30705)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30706)
		#define UNIQUE_FUNCTION<%0...%1> %07Um%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30706)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30707)
		#define UNIQUE_FUNCTION<%0...%1> %07Un%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30707)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30708)
		#define UNIQUE_FUNCTION<%0...%1> %07Uo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30708)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30709)
		#define UNIQUE_FUNCTION<%0...%1> %07Up%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30709)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30710)
		#define UNIQUE_FUNCTION<%0...%1> %07Uq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30711)
		#define UNIQUE_FUNCTION<%0...%1> %07Ur%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (30711)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30712)
		#define UNIQUE_FUNCTION<%0...%1> %07Us%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30712)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30713)
		#define UNIQUE_FUNCTION<%0...%1> %07Ut%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30713)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30714)
		#define UNIQUE_FUNCTION<%0...%1> %07Uu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30714)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30715)
		#define UNIQUE_FUNCTION<%0...%1> %07Uv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30715)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30716)
		#define UNIQUE_FUNCTION<%0...%1> %07Uw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30716)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30717)
		#define UNIQUE_FUNCTION<%0...%1> %07Ux%1
		#endinput
	#elseif UNIQUE_SYMBOL == (30717)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30718)
		#define UNIQUE_FUNCTION<%0...%1> %07Uy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (30719)
		#define UNIQUE_FUNCTION<%0...%1> %07Uz%1
		#endinput
	#endif
#endif
