static stock const Y_UNIQUE_010624_010687_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_010624_010687
	#undef _inc_y_unique_010624_010687
#endif

#if UNIQUE_SYMBOL < (10631)
	#if UNIQUE_SYMBOL == (10623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10624)
		#define UNIQUE_FUNCTION<%0...%1> %02a0%1
		#endinput
	#if UNIQUE_SYMBOL == (10624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10625)
		#define UNIQUE_FUNCTION<%0...%1> %02a1%1
		#endinput
	#if UNIQUE_SYMBOL == (10625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10626)
		#define UNIQUE_FUNCTION<%0...%1> %02a2%1
		#endinput
	#if UNIQUE_SYMBOL == (10626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10627)
		#define UNIQUE_FUNCTION<%0...%1> %02a3%1
		#endinput
	#if UNIQUE_SYMBOL == (10627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10628)
		#define UNIQUE_FUNCTION<%0...%1> %02a4%1
		#endinput
	#if UNIQUE_SYMBOL == (10628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10629)
		#define UNIQUE_FUNCTION<%0...%1> %02a5%1
		#endinput
	#if UNIQUE_SYMBOL == (10629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10630)
		#define UNIQUE_FUNCTION<%0...%1> %02a6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10631)
		#define UNIQUE_FUNCTION<%0...%1> %02a7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10639)
	#elseif UNIQUE_SYMBOL == (10631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10632)
		#define UNIQUE_FUNCTION<%0...%1> %02a8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10633)
		#define UNIQUE_FUNCTION<%0...%1> %02a9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10634)
		#define UNIQUE_FUNCTION<%0...%1> %02a@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10635)
		#define UNIQUE_FUNCTION<%0...%1> %02aA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10636)
		#define UNIQUE_FUNCTION<%0...%1> %02aB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10637)
		#define UNIQUE_FUNCTION<%0...%1> %02aC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10638)
		#define UNIQUE_FUNCTION<%0...%1> %02aD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10639)
		#define UNIQUE_FUNCTION<%0...%1> %02aE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10647)
	#elseif UNIQUE_SYMBOL == (10639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10640)
		#define UNIQUE_FUNCTION<%0...%1> %02aF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10641)
		#define UNIQUE_FUNCTION<%0...%1> %02aG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10642)
		#define UNIQUE_FUNCTION<%0...%1> %02aH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10643)
		#define UNIQUE_FUNCTION<%0...%1> %02aI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10644)
		#define UNIQUE_FUNCTION<%0...%1> %02aJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10645)
		#define UNIQUE_FUNCTION<%0...%1> %02aK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10646)
		#define UNIQUE_FUNCTION<%0...%1> %02aL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10647)
		#define UNIQUE_FUNCTION<%0...%1> %02aM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10655)
	#elseif UNIQUE_SYMBOL == (10647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10648)
		#define UNIQUE_FUNCTION<%0...%1> %02aN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10649)
		#define UNIQUE_FUNCTION<%0...%1> %02aO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10650)
		#define UNIQUE_FUNCTION<%0...%1> %02aP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10651)
		#define UNIQUE_FUNCTION<%0...%1> %02aQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10652)
		#define UNIQUE_FUNCTION<%0...%1> %02aR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10653)
		#define UNIQUE_FUNCTION<%0...%1> %02aS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10654)
		#define UNIQUE_FUNCTION<%0...%1> %02aT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10655)
		#define UNIQUE_FUNCTION<%0...%1> %02aU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10663)
	#elseif UNIQUE_SYMBOL == (10655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10656)
		#define UNIQUE_FUNCTION<%0...%1> %02aV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10657)
		#define UNIQUE_FUNCTION<%0...%1> %02aW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10658)
		#define UNIQUE_FUNCTION<%0...%1> %02aX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10659)
		#define UNIQUE_FUNCTION<%0...%1> %02aY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10660)
		#define UNIQUE_FUNCTION<%0...%1> %02aZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10661)
		#define UNIQUE_FUNCTION<%0...%1> %02a_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10662)
		#define UNIQUE_FUNCTION<%0...%1> %02aa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10663)
		#define UNIQUE_FUNCTION<%0...%1> %02ab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10671)
	#elseif UNIQUE_SYMBOL == (10663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10664)
		#define UNIQUE_FUNCTION<%0...%1> %02ac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10665)
		#define UNIQUE_FUNCTION<%0...%1> %02ad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10666)
		#define UNIQUE_FUNCTION<%0...%1> %02ae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10667)
		#define UNIQUE_FUNCTION<%0...%1> %02af%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10668)
		#define UNIQUE_FUNCTION<%0...%1> %02ag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10669)
		#define UNIQUE_FUNCTION<%0...%1> %02ah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10670)
		#define UNIQUE_FUNCTION<%0...%1> %02ai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10671)
		#define UNIQUE_FUNCTION<%0...%1> %02aj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (10679)
	#elseif UNIQUE_SYMBOL == (10671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10672)
		#define UNIQUE_FUNCTION<%0...%1> %02ak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10673)
		#define UNIQUE_FUNCTION<%0...%1> %02al%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10674)
		#define UNIQUE_FUNCTION<%0...%1> %02am%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10675)
		#define UNIQUE_FUNCTION<%0...%1> %02an%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10676)
		#define UNIQUE_FUNCTION<%0...%1> %02ao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10677)
		#define UNIQUE_FUNCTION<%0...%1> %02ap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10678)
		#define UNIQUE_FUNCTION<%0...%1> %02aq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10679)
		#define UNIQUE_FUNCTION<%0...%1> %02ar%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (10679)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10680)
		#define UNIQUE_FUNCTION<%0...%1> %02as%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10680)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10681)
		#define UNIQUE_FUNCTION<%0...%1> %02at%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10681)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10682)
		#define UNIQUE_FUNCTION<%0...%1> %02au%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10682)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10683)
		#define UNIQUE_FUNCTION<%0...%1> %02av%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10683)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10684)
		#define UNIQUE_FUNCTION<%0...%1> %02aw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10684)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10685)
		#define UNIQUE_FUNCTION<%0...%1> %02ax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (10685)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10686)
		#define UNIQUE_FUNCTION<%0...%1> %02ay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (10687)
		#define UNIQUE_FUNCTION<%0...%1> %02az%1
		#endinput
	#endif
#endif
