static stock const Y_UNIQUE_130816_130879_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_130816_130879
	#undef _inc_y_unique_130816_130879
#endif

#if UNIQUE_SYMBOL < (130823)
	#if UNIQUE_SYMBOL == (130815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130816)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw0%1
		#endinput
	#if UNIQUE_SYMBOL == (130816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130817)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw1%1
		#endinput
	#if UNIQUE_SYMBOL == (130817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130818)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw2%1
		#endinput
	#if UNIQUE_SYMBOL == (130818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130819)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw3%1
		#endinput
	#if UNIQUE_SYMBOL == (130819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130820)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw4%1
		#endinput
	#if UNIQUE_SYMBOL == (130820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130821)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw5%1
		#endinput
	#if UNIQUE_SYMBOL == (130821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130822)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130823)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130831)
	#elseif UNIQUE_SYMBOL == (130823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130824)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130825)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130826)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130827)
		#define UNIQUE_FUNCTION<%0...%1> %0UwA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130828)
		#define UNIQUE_FUNCTION<%0...%1> %0UwB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130829)
		#define UNIQUE_FUNCTION<%0...%1> %0UwC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130830)
		#define UNIQUE_FUNCTION<%0...%1> %0UwD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130831)
		#define UNIQUE_FUNCTION<%0...%1> %0UwE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130839)
	#elseif UNIQUE_SYMBOL == (130831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130832)
		#define UNIQUE_FUNCTION<%0...%1> %0UwF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130833)
		#define UNIQUE_FUNCTION<%0...%1> %0UwG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130834)
		#define UNIQUE_FUNCTION<%0...%1> %0UwH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130835)
		#define UNIQUE_FUNCTION<%0...%1> %0UwI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130836)
		#define UNIQUE_FUNCTION<%0...%1> %0UwJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130837)
		#define UNIQUE_FUNCTION<%0...%1> %0UwK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130838)
		#define UNIQUE_FUNCTION<%0...%1> %0UwL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130839)
		#define UNIQUE_FUNCTION<%0...%1> %0UwM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130847)
	#elseif UNIQUE_SYMBOL == (130839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130840)
		#define UNIQUE_FUNCTION<%0...%1> %0UwN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130841)
		#define UNIQUE_FUNCTION<%0...%1> %0UwO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130842)
		#define UNIQUE_FUNCTION<%0...%1> %0UwP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130843)
		#define UNIQUE_FUNCTION<%0...%1> %0UwQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130844)
		#define UNIQUE_FUNCTION<%0...%1> %0UwR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130845)
		#define UNIQUE_FUNCTION<%0...%1> %0UwS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130846)
		#define UNIQUE_FUNCTION<%0...%1> %0UwT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130847)
		#define UNIQUE_FUNCTION<%0...%1> %0UwU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130855)
	#elseif UNIQUE_SYMBOL == (130847)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130848)
		#define UNIQUE_FUNCTION<%0...%1> %0UwV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130848)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130849)
		#define UNIQUE_FUNCTION<%0...%1> %0UwW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130849)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130850)
		#define UNIQUE_FUNCTION<%0...%1> %0UwX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130850)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130851)
		#define UNIQUE_FUNCTION<%0...%1> %0UwY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130851)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130852)
		#define UNIQUE_FUNCTION<%0...%1> %0UwZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130852)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130853)
		#define UNIQUE_FUNCTION<%0...%1> %0Uw_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130853)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130854)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130855)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130863)
	#elseif UNIQUE_SYMBOL == (130855)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130856)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130856)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130857)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130857)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130858)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130858)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130859)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130859)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130860)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130860)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130861)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130861)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130862)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130863)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (130871)
	#elseif UNIQUE_SYMBOL == (130863)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130864)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130864)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130865)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130865)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130866)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130866)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130867)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130867)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130868)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130868)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130869)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130869)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130870)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130871)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (130871)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130872)
		#define UNIQUE_FUNCTION<%0...%1> %0Uws%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130872)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130873)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130873)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130874)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130874)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130875)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130875)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130876)
		#define UNIQUE_FUNCTION<%0...%1> %0Uww%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130876)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130877)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (130877)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130878)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (130879)
		#define UNIQUE_FUNCTION<%0...%1> %0Uwz%1
		#endinput
	#endif
#endif
