static stock const Y_UNIQUE_017344_017407_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_017344_017407
	#undef _inc_y_unique_017344_017407
#endif

#if UNIQUE_SYMBOL < (17351)
	#if UNIQUE_SYMBOL == (17343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17344)
		#define UNIQUE_FUNCTION<%0...%1> %04E0%1
		#endinput
	#if UNIQUE_SYMBOL == (17344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17345)
		#define UNIQUE_FUNCTION<%0...%1> %04E1%1
		#endinput
	#if UNIQUE_SYMBOL == (17345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17346)
		#define UNIQUE_FUNCTION<%0...%1> %04E2%1
		#endinput
	#if UNIQUE_SYMBOL == (17346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17347)
		#define UNIQUE_FUNCTION<%0...%1> %04E3%1
		#endinput
	#if UNIQUE_SYMBOL == (17347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17348)
		#define UNIQUE_FUNCTION<%0...%1> %04E4%1
		#endinput
	#if UNIQUE_SYMBOL == (17348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17349)
		#define UNIQUE_FUNCTION<%0...%1> %04E5%1
		#endinput
	#if UNIQUE_SYMBOL == (17349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17350)
		#define UNIQUE_FUNCTION<%0...%1> %04E6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17351)
		#define UNIQUE_FUNCTION<%0...%1> %04E7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17359)
	#elseif UNIQUE_SYMBOL == (17351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17352)
		#define UNIQUE_FUNCTION<%0...%1> %04E8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17353)
		#define UNIQUE_FUNCTION<%0...%1> %04E9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17354)
		#define UNIQUE_FUNCTION<%0...%1> %04E@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17355)
		#define UNIQUE_FUNCTION<%0...%1> %04EA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17356)
		#define UNIQUE_FUNCTION<%0...%1> %04EB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17357)
		#define UNIQUE_FUNCTION<%0...%1> %04EC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17358)
		#define UNIQUE_FUNCTION<%0...%1> %04ED%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17359)
		#define UNIQUE_FUNCTION<%0...%1> %04EE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17367)
	#elseif UNIQUE_SYMBOL == (17359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17360)
		#define UNIQUE_FUNCTION<%0...%1> %04EF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17361)
		#define UNIQUE_FUNCTION<%0...%1> %04EG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17362)
		#define UNIQUE_FUNCTION<%0...%1> %04EH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17363)
		#define UNIQUE_FUNCTION<%0...%1> %04EI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17364)
		#define UNIQUE_FUNCTION<%0...%1> %04EJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17365)
		#define UNIQUE_FUNCTION<%0...%1> %04EK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17366)
		#define UNIQUE_FUNCTION<%0...%1> %04EL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17367)
		#define UNIQUE_FUNCTION<%0...%1> %04EM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17375)
	#elseif UNIQUE_SYMBOL == (17367)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17368)
		#define UNIQUE_FUNCTION<%0...%1> %04EN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17368)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17369)
		#define UNIQUE_FUNCTION<%0...%1> %04EO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17369)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17370)
		#define UNIQUE_FUNCTION<%0...%1> %04EP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17370)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17371)
		#define UNIQUE_FUNCTION<%0...%1> %04EQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17371)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17372)
		#define UNIQUE_FUNCTION<%0...%1> %04ER%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17372)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17373)
		#define UNIQUE_FUNCTION<%0...%1> %04ES%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17373)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17374)
		#define UNIQUE_FUNCTION<%0...%1> %04ET%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17375)
		#define UNIQUE_FUNCTION<%0...%1> %04EU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17383)
	#elseif UNIQUE_SYMBOL == (17375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17376)
		#define UNIQUE_FUNCTION<%0...%1> %04EV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17377)
		#define UNIQUE_FUNCTION<%0...%1> %04EW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17378)
		#define UNIQUE_FUNCTION<%0...%1> %04EX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17379)
		#define UNIQUE_FUNCTION<%0...%1> %04EY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17380)
		#define UNIQUE_FUNCTION<%0...%1> %04EZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17381)
		#define UNIQUE_FUNCTION<%0...%1> %04E_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17382)
		#define UNIQUE_FUNCTION<%0...%1> %04Ea%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17383)
		#define UNIQUE_FUNCTION<%0...%1> %04Eb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17391)
	#elseif UNIQUE_SYMBOL == (17383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17384)
		#define UNIQUE_FUNCTION<%0...%1> %04Ec%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17385)
		#define UNIQUE_FUNCTION<%0...%1> %04Ed%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17386)
		#define UNIQUE_FUNCTION<%0...%1> %04Ee%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17387)
		#define UNIQUE_FUNCTION<%0...%1> %04Ef%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17388)
		#define UNIQUE_FUNCTION<%0...%1> %04Eg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17389)
		#define UNIQUE_FUNCTION<%0...%1> %04Eh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17390)
		#define UNIQUE_FUNCTION<%0...%1> %04Ei%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17391)
		#define UNIQUE_FUNCTION<%0...%1> %04Ej%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17399)
	#elseif UNIQUE_SYMBOL == (17391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17392)
		#define UNIQUE_FUNCTION<%0...%1> %04Ek%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17393)
		#define UNIQUE_FUNCTION<%0...%1> %04El%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17394)
		#define UNIQUE_FUNCTION<%0...%1> %04Em%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17395)
		#define UNIQUE_FUNCTION<%0...%1> %04En%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17396)
		#define UNIQUE_FUNCTION<%0...%1> %04Eo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17397)
		#define UNIQUE_FUNCTION<%0...%1> %04Ep%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17398)
		#define UNIQUE_FUNCTION<%0...%1> %04Eq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17399)
		#define UNIQUE_FUNCTION<%0...%1> %04Er%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (17399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17400)
		#define UNIQUE_FUNCTION<%0...%1> %04Es%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17401)
		#define UNIQUE_FUNCTION<%0...%1> %04Et%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17402)
		#define UNIQUE_FUNCTION<%0...%1> %04Eu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17403)
		#define UNIQUE_FUNCTION<%0...%1> %04Ev%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17404)
		#define UNIQUE_FUNCTION<%0...%1> %04Ew%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17405)
		#define UNIQUE_FUNCTION<%0...%1> %04Ex%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17406)
		#define UNIQUE_FUNCTION<%0...%1> %04Ey%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17407)
		#define UNIQUE_FUNCTION<%0...%1> %04Ez%1
		#endinput
	#endif
#endif
