static stock const Y_UNIQUE_132160_132223_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_132160_132223
	#undef _inc_y_unique_132160_132223
#endif

#if UNIQUE_SYMBOL < (132167)
	#if UNIQUE_SYMBOL == (132159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132160)
		#define UNIQUE_FUNCTION<%0...%1> %0VG0%1
		#endinput
	#if UNIQUE_SYMBOL == (132160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132161)
		#define UNIQUE_FUNCTION<%0...%1> %0VG1%1
		#endinput
	#if UNIQUE_SYMBOL == (132161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132162)
		#define UNIQUE_FUNCTION<%0...%1> %0VG2%1
		#endinput
	#if UNIQUE_SYMBOL == (132162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132163)
		#define UNIQUE_FUNCTION<%0...%1> %0VG3%1
		#endinput
	#if UNIQUE_SYMBOL == (132163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132164)
		#define UNIQUE_FUNCTION<%0...%1> %0VG4%1
		#endinput
	#if UNIQUE_SYMBOL == (132164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132165)
		#define UNIQUE_FUNCTION<%0...%1> %0VG5%1
		#endinput
	#if UNIQUE_SYMBOL == (132165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132166)
		#define UNIQUE_FUNCTION<%0...%1> %0VG6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132167)
		#define UNIQUE_FUNCTION<%0...%1> %0VG7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132175)
	#elseif UNIQUE_SYMBOL == (132167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132168)
		#define UNIQUE_FUNCTION<%0...%1> %0VG8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132169)
		#define UNIQUE_FUNCTION<%0...%1> %0VG9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132170)
		#define UNIQUE_FUNCTION<%0...%1> %0VG@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132171)
		#define UNIQUE_FUNCTION<%0...%1> %0VGA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132172)
		#define UNIQUE_FUNCTION<%0...%1> %0VGB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132173)
		#define UNIQUE_FUNCTION<%0...%1> %0VGC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132174)
		#define UNIQUE_FUNCTION<%0...%1> %0VGD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132175)
		#define UNIQUE_FUNCTION<%0...%1> %0VGE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132183)
	#elseif UNIQUE_SYMBOL == (132175)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132176)
		#define UNIQUE_FUNCTION<%0...%1> %0VGF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132176)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132177)
		#define UNIQUE_FUNCTION<%0...%1> %0VGG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132177)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132178)
		#define UNIQUE_FUNCTION<%0...%1> %0VGH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132178)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132179)
		#define UNIQUE_FUNCTION<%0...%1> %0VGI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132179)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132180)
		#define UNIQUE_FUNCTION<%0...%1> %0VGJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132180)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132181)
		#define UNIQUE_FUNCTION<%0...%1> %0VGK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132181)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132182)
		#define UNIQUE_FUNCTION<%0...%1> %0VGL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132183)
		#define UNIQUE_FUNCTION<%0...%1> %0VGM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132191)
	#elseif UNIQUE_SYMBOL == (132183)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132184)
		#define UNIQUE_FUNCTION<%0...%1> %0VGN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132184)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132185)
		#define UNIQUE_FUNCTION<%0...%1> %0VGO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132185)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132186)
		#define UNIQUE_FUNCTION<%0...%1> %0VGP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132186)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132187)
		#define UNIQUE_FUNCTION<%0...%1> %0VGQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132187)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132188)
		#define UNIQUE_FUNCTION<%0...%1> %0VGR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132188)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132189)
		#define UNIQUE_FUNCTION<%0...%1> %0VGS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132189)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132190)
		#define UNIQUE_FUNCTION<%0...%1> %0VGT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132191)
		#define UNIQUE_FUNCTION<%0...%1> %0VGU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132199)
	#elseif UNIQUE_SYMBOL == (132191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132192)
		#define UNIQUE_FUNCTION<%0...%1> %0VGV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132193)
		#define UNIQUE_FUNCTION<%0...%1> %0VGW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132194)
		#define UNIQUE_FUNCTION<%0...%1> %0VGX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132195)
		#define UNIQUE_FUNCTION<%0...%1> %0VGY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132196)
		#define UNIQUE_FUNCTION<%0...%1> %0VGZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132197)
		#define UNIQUE_FUNCTION<%0...%1> %0VG_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132198)
		#define UNIQUE_FUNCTION<%0...%1> %0VGa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132199)
		#define UNIQUE_FUNCTION<%0...%1> %0VGb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132207)
	#elseif UNIQUE_SYMBOL == (132199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132200)
		#define UNIQUE_FUNCTION<%0...%1> %0VGc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132201)
		#define UNIQUE_FUNCTION<%0...%1> %0VGd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132202)
		#define UNIQUE_FUNCTION<%0...%1> %0VGe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132203)
		#define UNIQUE_FUNCTION<%0...%1> %0VGf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132204)
		#define UNIQUE_FUNCTION<%0...%1> %0VGg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132205)
		#define UNIQUE_FUNCTION<%0...%1> %0VGh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132206)
		#define UNIQUE_FUNCTION<%0...%1> %0VGi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132207)
		#define UNIQUE_FUNCTION<%0...%1> %0VGj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (132215)
	#elseif UNIQUE_SYMBOL == (132207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132208)
		#define UNIQUE_FUNCTION<%0...%1> %0VGk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132209)
		#define UNIQUE_FUNCTION<%0...%1> %0VGl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132210)
		#define UNIQUE_FUNCTION<%0...%1> %0VGm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132211)
		#define UNIQUE_FUNCTION<%0...%1> %0VGn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132212)
		#define UNIQUE_FUNCTION<%0...%1> %0VGo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132213)
		#define UNIQUE_FUNCTION<%0...%1> %0VGp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132214)
		#define UNIQUE_FUNCTION<%0...%1> %0VGq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132215)
		#define UNIQUE_FUNCTION<%0...%1> %0VGr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (132215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132216)
		#define UNIQUE_FUNCTION<%0...%1> %0VGs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132217)
		#define UNIQUE_FUNCTION<%0...%1> %0VGt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132218)
		#define UNIQUE_FUNCTION<%0...%1> %0VGu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132219)
		#define UNIQUE_FUNCTION<%0...%1> %0VGv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132220)
		#define UNIQUE_FUNCTION<%0...%1> %0VGw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132221)
		#define UNIQUE_FUNCTION<%0...%1> %0VGx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (132221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132222)
		#define UNIQUE_FUNCTION<%0...%1> %0VGy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (132223)
		#define UNIQUE_FUNCTION<%0...%1> %0VGz%1
		#endinput
	#endif
#endif
