static stock const Y_UNIQUE_118208_118271_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_118208_118271
	#undef _inc_y_unique_118208_118271
#endif

#if UNIQUE_SYMBOL < (118215)
	#if UNIQUE_SYMBOL == (118207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118208)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr0%1
		#endinput
	#if UNIQUE_SYMBOL == (118208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118209)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr1%1
		#endinput
	#if UNIQUE_SYMBOL == (118209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118210)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr2%1
		#endinput
	#if UNIQUE_SYMBOL == (118210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118211)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr3%1
		#endinput
	#if UNIQUE_SYMBOL == (118211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118212)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr4%1
		#endinput
	#if UNIQUE_SYMBOL == (118212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118213)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr5%1
		#endinput
	#if UNIQUE_SYMBOL == (118213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118214)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118215)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (118223)
	#elseif UNIQUE_SYMBOL == (118215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118216)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118217)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118218)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118219)
		#define UNIQUE_FUNCTION<%0...%1> %0RrA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118220)
		#define UNIQUE_FUNCTION<%0...%1> %0RrB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118221)
		#define UNIQUE_FUNCTION<%0...%1> %0RrC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118222)
		#define UNIQUE_FUNCTION<%0...%1> %0RrD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118223)
		#define UNIQUE_FUNCTION<%0...%1> %0RrE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (118231)
	#elseif UNIQUE_SYMBOL == (118223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118224)
		#define UNIQUE_FUNCTION<%0...%1> %0RrF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118225)
		#define UNIQUE_FUNCTION<%0...%1> %0RrG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118226)
		#define UNIQUE_FUNCTION<%0...%1> %0RrH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118227)
		#define UNIQUE_FUNCTION<%0...%1> %0RrI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118228)
		#define UNIQUE_FUNCTION<%0...%1> %0RrJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118229)
		#define UNIQUE_FUNCTION<%0...%1> %0RrK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118230)
		#define UNIQUE_FUNCTION<%0...%1> %0RrL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118231)
		#define UNIQUE_FUNCTION<%0...%1> %0RrM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (118239)
	#elseif UNIQUE_SYMBOL == (118231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118232)
		#define UNIQUE_FUNCTION<%0...%1> %0RrN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118233)
		#define UNIQUE_FUNCTION<%0...%1> %0RrO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118234)
		#define UNIQUE_FUNCTION<%0...%1> %0RrP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118235)
		#define UNIQUE_FUNCTION<%0...%1> %0RrQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118236)
		#define UNIQUE_FUNCTION<%0...%1> %0RrR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118237)
		#define UNIQUE_FUNCTION<%0...%1> %0RrS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118238)
		#define UNIQUE_FUNCTION<%0...%1> %0RrT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118239)
		#define UNIQUE_FUNCTION<%0...%1> %0RrU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (118247)
	#elseif UNIQUE_SYMBOL == (118239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118240)
		#define UNIQUE_FUNCTION<%0...%1> %0RrV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118241)
		#define UNIQUE_FUNCTION<%0...%1> %0RrW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118242)
		#define UNIQUE_FUNCTION<%0...%1> %0RrX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118243)
		#define UNIQUE_FUNCTION<%0...%1> %0RrY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118244)
		#define UNIQUE_FUNCTION<%0...%1> %0RrZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118245)
		#define UNIQUE_FUNCTION<%0...%1> %0Rr_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118246)
		#define UNIQUE_FUNCTION<%0...%1> %0Rra%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118247)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (118255)
	#elseif UNIQUE_SYMBOL == (118247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118248)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118249)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118250)
		#define UNIQUE_FUNCTION<%0...%1> %0Rre%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118251)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118252)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118253)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118254)
		#define UNIQUE_FUNCTION<%0...%1> %0Rri%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118255)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (118263)
	#elseif UNIQUE_SYMBOL == (118255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118256)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118257)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118258)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118259)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118260)
		#define UNIQUE_FUNCTION<%0...%1> %0Rro%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118261)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118262)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118263)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (118263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118264)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118265)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118266)
		#define UNIQUE_FUNCTION<%0...%1> %0Rru%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118267)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118268)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118269)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (118269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118270)
		#define UNIQUE_FUNCTION<%0...%1> %0Rry%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (118271)
		#define UNIQUE_FUNCTION<%0...%1> %0Rrz%1
		#endinput
	#endif
#endif
