static stock const Y_UNIQUE_036160_036223_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_036160_036223
	#undef _inc_y_unique_036160_036223
#endif

#if UNIQUE_SYMBOL < (36167)
	#if UNIQUE_SYMBOL == (36159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36160)
		#define UNIQUE_FUNCTION<%0...%1> %08p0%1
		#endinput
	#if UNIQUE_SYMBOL == (36160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36161)
		#define UNIQUE_FUNCTION<%0...%1> %08p1%1
		#endinput
	#if UNIQUE_SYMBOL == (36161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36162)
		#define UNIQUE_FUNCTION<%0...%1> %08p2%1
		#endinput
	#if UNIQUE_SYMBOL == (36162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36163)
		#define UNIQUE_FUNCTION<%0...%1> %08p3%1
		#endinput
	#if UNIQUE_SYMBOL == (36163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36164)
		#define UNIQUE_FUNCTION<%0...%1> %08p4%1
		#endinput
	#if UNIQUE_SYMBOL == (36164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36165)
		#define UNIQUE_FUNCTION<%0...%1> %08p5%1
		#endinput
	#if UNIQUE_SYMBOL == (36165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36166)
		#define UNIQUE_FUNCTION<%0...%1> %08p6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36167)
		#define UNIQUE_FUNCTION<%0...%1> %08p7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36175)
	#elseif UNIQUE_SYMBOL == (36167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36168)
		#define UNIQUE_FUNCTION<%0...%1> %08p8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36169)
		#define UNIQUE_FUNCTION<%0...%1> %08p9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36170)
		#define UNIQUE_FUNCTION<%0...%1> %08p@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36171)
		#define UNIQUE_FUNCTION<%0...%1> %08pA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36172)
		#define UNIQUE_FUNCTION<%0...%1> %08pB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36173)
		#define UNIQUE_FUNCTION<%0...%1> %08pC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36174)
		#define UNIQUE_FUNCTION<%0...%1> %08pD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36175)
		#define UNIQUE_FUNCTION<%0...%1> %08pE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36183)
	#elseif UNIQUE_SYMBOL == (36175)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36176)
		#define UNIQUE_FUNCTION<%0...%1> %08pF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36176)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36177)
		#define UNIQUE_FUNCTION<%0...%1> %08pG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36177)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36178)
		#define UNIQUE_FUNCTION<%0...%1> %08pH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36178)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36179)
		#define UNIQUE_FUNCTION<%0...%1> %08pI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36179)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36180)
		#define UNIQUE_FUNCTION<%0...%1> %08pJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36180)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36181)
		#define UNIQUE_FUNCTION<%0...%1> %08pK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36181)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36182)
		#define UNIQUE_FUNCTION<%0...%1> %08pL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36183)
		#define UNIQUE_FUNCTION<%0...%1> %08pM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36191)
	#elseif UNIQUE_SYMBOL == (36183)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36184)
		#define UNIQUE_FUNCTION<%0...%1> %08pN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36184)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36185)
		#define UNIQUE_FUNCTION<%0...%1> %08pO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36185)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36186)
		#define UNIQUE_FUNCTION<%0...%1> %08pP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36186)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36187)
		#define UNIQUE_FUNCTION<%0...%1> %08pQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36187)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36188)
		#define UNIQUE_FUNCTION<%0...%1> %08pR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36188)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36189)
		#define UNIQUE_FUNCTION<%0...%1> %08pS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36189)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36190)
		#define UNIQUE_FUNCTION<%0...%1> %08pT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36191)
		#define UNIQUE_FUNCTION<%0...%1> %08pU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36199)
	#elseif UNIQUE_SYMBOL == (36191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36192)
		#define UNIQUE_FUNCTION<%0...%1> %08pV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36193)
		#define UNIQUE_FUNCTION<%0...%1> %08pW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36194)
		#define UNIQUE_FUNCTION<%0...%1> %08pX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36195)
		#define UNIQUE_FUNCTION<%0...%1> %08pY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36196)
		#define UNIQUE_FUNCTION<%0...%1> %08pZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36197)
		#define UNIQUE_FUNCTION<%0...%1> %08p_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36198)
		#define UNIQUE_FUNCTION<%0...%1> %08pa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36199)
		#define UNIQUE_FUNCTION<%0...%1> %08pb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36207)
	#elseif UNIQUE_SYMBOL == (36199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36200)
		#define UNIQUE_FUNCTION<%0...%1> %08pc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36201)
		#define UNIQUE_FUNCTION<%0...%1> %08pd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36202)
		#define UNIQUE_FUNCTION<%0...%1> %08pe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36203)
		#define UNIQUE_FUNCTION<%0...%1> %08pf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36204)
		#define UNIQUE_FUNCTION<%0...%1> %08pg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36205)
		#define UNIQUE_FUNCTION<%0...%1> %08ph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36206)
		#define UNIQUE_FUNCTION<%0...%1> %08pi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36207)
		#define UNIQUE_FUNCTION<%0...%1> %08pj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36215)
	#elseif UNIQUE_SYMBOL == (36207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36208)
		#define UNIQUE_FUNCTION<%0...%1> %08pk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36209)
		#define UNIQUE_FUNCTION<%0...%1> %08pl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36210)
		#define UNIQUE_FUNCTION<%0...%1> %08pm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36211)
		#define UNIQUE_FUNCTION<%0...%1> %08pn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36212)
		#define UNIQUE_FUNCTION<%0...%1> %08po%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36213)
		#define UNIQUE_FUNCTION<%0...%1> %08pp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36214)
		#define UNIQUE_FUNCTION<%0...%1> %08pq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36215)
		#define UNIQUE_FUNCTION<%0...%1> %08pr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (36215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36216)
		#define UNIQUE_FUNCTION<%0...%1> %08ps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36217)
		#define UNIQUE_FUNCTION<%0...%1> %08pt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36218)
		#define UNIQUE_FUNCTION<%0...%1> %08pu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36219)
		#define UNIQUE_FUNCTION<%0...%1> %08pv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36220)
		#define UNIQUE_FUNCTION<%0...%1> %08pw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36221)
		#define UNIQUE_FUNCTION<%0...%1> %08px%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36222)
		#define UNIQUE_FUNCTION<%0...%1> %08py%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36223)
		#define UNIQUE_FUNCTION<%0...%1> %08pz%1
		#endinput
	#endif
#endif
