static stock const Y_UNIQUE_178304_178367_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_178304_178367
	#undef _inc_y_unique_178304_178367
#endif

#if UNIQUE_SYMBOL < (178311)
	#if UNIQUE_SYMBOL == (178303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178304)
		#define UNIQUE_FUNCTION<%0...%1> %0fX0%1
		#endinput
	#if UNIQUE_SYMBOL == (178304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178305)
		#define UNIQUE_FUNCTION<%0...%1> %0fX1%1
		#endinput
	#if UNIQUE_SYMBOL == (178305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178306)
		#define UNIQUE_FUNCTION<%0...%1> %0fX2%1
		#endinput
	#if UNIQUE_SYMBOL == (178306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178307)
		#define UNIQUE_FUNCTION<%0...%1> %0fX3%1
		#endinput
	#if UNIQUE_SYMBOL == (178307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178308)
		#define UNIQUE_FUNCTION<%0...%1> %0fX4%1
		#endinput
	#if UNIQUE_SYMBOL == (178308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178309)
		#define UNIQUE_FUNCTION<%0...%1> %0fX5%1
		#endinput
	#if UNIQUE_SYMBOL == (178309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178310)
		#define UNIQUE_FUNCTION<%0...%1> %0fX6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178311)
		#define UNIQUE_FUNCTION<%0...%1> %0fX7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (178319)
	#elseif UNIQUE_SYMBOL == (178311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178312)
		#define UNIQUE_FUNCTION<%0...%1> %0fX8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178313)
		#define UNIQUE_FUNCTION<%0...%1> %0fX9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178314)
		#define UNIQUE_FUNCTION<%0...%1> %0fX@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178315)
		#define UNIQUE_FUNCTION<%0...%1> %0fXA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178316)
		#define UNIQUE_FUNCTION<%0...%1> %0fXB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178317)
		#define UNIQUE_FUNCTION<%0...%1> %0fXC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178318)
		#define UNIQUE_FUNCTION<%0...%1> %0fXD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178319)
		#define UNIQUE_FUNCTION<%0...%1> %0fXE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (178327)
	#elseif UNIQUE_SYMBOL == (178319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178320)
		#define UNIQUE_FUNCTION<%0...%1> %0fXF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178321)
		#define UNIQUE_FUNCTION<%0...%1> %0fXG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178322)
		#define UNIQUE_FUNCTION<%0...%1> %0fXH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178323)
		#define UNIQUE_FUNCTION<%0...%1> %0fXI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178324)
		#define UNIQUE_FUNCTION<%0...%1> %0fXJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178325)
		#define UNIQUE_FUNCTION<%0...%1> %0fXK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178326)
		#define UNIQUE_FUNCTION<%0...%1> %0fXL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178327)
		#define UNIQUE_FUNCTION<%0...%1> %0fXM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (178335)
	#elseif UNIQUE_SYMBOL == (178327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178328)
		#define UNIQUE_FUNCTION<%0...%1> %0fXN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178329)
		#define UNIQUE_FUNCTION<%0...%1> %0fXO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178330)
		#define UNIQUE_FUNCTION<%0...%1> %0fXP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178331)
		#define UNIQUE_FUNCTION<%0...%1> %0fXQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178332)
		#define UNIQUE_FUNCTION<%0...%1> %0fXR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178333)
		#define UNIQUE_FUNCTION<%0...%1> %0fXS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178334)
		#define UNIQUE_FUNCTION<%0...%1> %0fXT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178335)
		#define UNIQUE_FUNCTION<%0...%1> %0fXU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (178343)
	#elseif UNIQUE_SYMBOL == (178335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178336)
		#define UNIQUE_FUNCTION<%0...%1> %0fXV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178337)
		#define UNIQUE_FUNCTION<%0...%1> %0fXW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178338)
		#define UNIQUE_FUNCTION<%0...%1> %0fXX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178339)
		#define UNIQUE_FUNCTION<%0...%1> %0fXY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178340)
		#define UNIQUE_FUNCTION<%0...%1> %0fXZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178341)
		#define UNIQUE_FUNCTION<%0...%1> %0fX_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178342)
		#define UNIQUE_FUNCTION<%0...%1> %0fXa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178343)
		#define UNIQUE_FUNCTION<%0...%1> %0fXb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (178351)
	#elseif UNIQUE_SYMBOL == (178343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178344)
		#define UNIQUE_FUNCTION<%0...%1> %0fXc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178345)
		#define UNIQUE_FUNCTION<%0...%1> %0fXd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178346)
		#define UNIQUE_FUNCTION<%0...%1> %0fXe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178347)
		#define UNIQUE_FUNCTION<%0...%1> %0fXf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178348)
		#define UNIQUE_FUNCTION<%0...%1> %0fXg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178349)
		#define UNIQUE_FUNCTION<%0...%1> %0fXh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178350)
		#define UNIQUE_FUNCTION<%0...%1> %0fXi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178351)
		#define UNIQUE_FUNCTION<%0...%1> %0fXj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (178359)
	#elseif UNIQUE_SYMBOL == (178351)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178352)
		#define UNIQUE_FUNCTION<%0...%1> %0fXk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178352)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178353)
		#define UNIQUE_FUNCTION<%0...%1> %0fXl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178353)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178354)
		#define UNIQUE_FUNCTION<%0...%1> %0fXm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178354)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178355)
		#define UNIQUE_FUNCTION<%0...%1> %0fXn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178355)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178356)
		#define UNIQUE_FUNCTION<%0...%1> %0fXo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178356)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178357)
		#define UNIQUE_FUNCTION<%0...%1> %0fXp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178357)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178358)
		#define UNIQUE_FUNCTION<%0...%1> %0fXq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178359)
		#define UNIQUE_FUNCTION<%0...%1> %0fXr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (178359)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178360)
		#define UNIQUE_FUNCTION<%0...%1> %0fXs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178360)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178361)
		#define UNIQUE_FUNCTION<%0...%1> %0fXt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178361)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178362)
		#define UNIQUE_FUNCTION<%0...%1> %0fXu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178362)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178363)
		#define UNIQUE_FUNCTION<%0...%1> %0fXv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178363)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178364)
		#define UNIQUE_FUNCTION<%0...%1> %0fXw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178364)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178365)
		#define UNIQUE_FUNCTION<%0...%1> %0fXx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (178365)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178366)
		#define UNIQUE_FUNCTION<%0...%1> %0fXy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (178367)
		#define UNIQUE_FUNCTION<%0...%1> %0fXz%1
		#endinput
	#endif
#endif
