static stock const Y_UNIQUE_019968_020031_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_019968_020031
	#undef _inc_y_unique_019968_020031
#endif

#if UNIQUE_SYMBOL < (19975)
	#if UNIQUE_SYMBOL == (19967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19968)
		#define UNIQUE_FUNCTION<%0...%1> %04s0%1
		#endinput
	#if UNIQUE_SYMBOL == (19968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19969)
		#define UNIQUE_FUNCTION<%0...%1> %04s1%1
		#endinput
	#if UNIQUE_SYMBOL == (19969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19970)
		#define UNIQUE_FUNCTION<%0...%1> %04s2%1
		#endinput
	#if UNIQUE_SYMBOL == (19970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19971)
		#define UNIQUE_FUNCTION<%0...%1> %04s3%1
		#endinput
	#if UNIQUE_SYMBOL == (19971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19972)
		#define UNIQUE_FUNCTION<%0...%1> %04s4%1
		#endinput
	#if UNIQUE_SYMBOL == (19972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19973)
		#define UNIQUE_FUNCTION<%0...%1> %04s5%1
		#endinput
	#if UNIQUE_SYMBOL == (19973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19974)
		#define UNIQUE_FUNCTION<%0...%1> %04s6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19975)
		#define UNIQUE_FUNCTION<%0...%1> %04s7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19983)
	#elseif UNIQUE_SYMBOL == (19975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19976)
		#define UNIQUE_FUNCTION<%0...%1> %04s8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19977)
		#define UNIQUE_FUNCTION<%0...%1> %04s9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19978)
		#define UNIQUE_FUNCTION<%0...%1> %04s@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19979)
		#define UNIQUE_FUNCTION<%0...%1> %04sA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19980)
		#define UNIQUE_FUNCTION<%0...%1> %04sB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19981)
		#define UNIQUE_FUNCTION<%0...%1> %04sC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19982)
		#define UNIQUE_FUNCTION<%0...%1> %04sD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19983)
		#define UNIQUE_FUNCTION<%0...%1> %04sE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19991)
	#elseif UNIQUE_SYMBOL == (19983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19984)
		#define UNIQUE_FUNCTION<%0...%1> %04sF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19985)
		#define UNIQUE_FUNCTION<%0...%1> %04sG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19986)
		#define UNIQUE_FUNCTION<%0...%1> %04sH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19987)
		#define UNIQUE_FUNCTION<%0...%1> %04sI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19988)
		#define UNIQUE_FUNCTION<%0...%1> %04sJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19989)
		#define UNIQUE_FUNCTION<%0...%1> %04sK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19990)
		#define UNIQUE_FUNCTION<%0...%1> %04sL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19991)
		#define UNIQUE_FUNCTION<%0...%1> %04sM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (19999)
	#elseif UNIQUE_SYMBOL == (19991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19992)
		#define UNIQUE_FUNCTION<%0...%1> %04sN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19993)
		#define UNIQUE_FUNCTION<%0...%1> %04sO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19994)
		#define UNIQUE_FUNCTION<%0...%1> %04sP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19995)
		#define UNIQUE_FUNCTION<%0...%1> %04sQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19996)
		#define UNIQUE_FUNCTION<%0...%1> %04sR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19997)
		#define UNIQUE_FUNCTION<%0...%1> %04sS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (19997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19998)
		#define UNIQUE_FUNCTION<%0...%1> %04sT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (19999)
		#define UNIQUE_FUNCTION<%0...%1> %04sU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (20007)
	#elseif UNIQUE_SYMBOL == (19999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20000)
		#define UNIQUE_FUNCTION<%0...%1> %04sV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20001)
		#define UNIQUE_FUNCTION<%0...%1> %04sW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20002)
		#define UNIQUE_FUNCTION<%0...%1> %04sX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20003)
		#define UNIQUE_FUNCTION<%0...%1> %04sY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20004)
		#define UNIQUE_FUNCTION<%0...%1> %04sZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20005)
		#define UNIQUE_FUNCTION<%0...%1> %04s_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20006)
		#define UNIQUE_FUNCTION<%0...%1> %04sa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20007)
		#define UNIQUE_FUNCTION<%0...%1> %04sb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (20015)
	#elseif UNIQUE_SYMBOL == (20007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20008)
		#define UNIQUE_FUNCTION<%0...%1> %04sc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20009)
		#define UNIQUE_FUNCTION<%0...%1> %04sd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20010)
		#define UNIQUE_FUNCTION<%0...%1> %04se%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20011)
		#define UNIQUE_FUNCTION<%0...%1> %04sf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20012)
		#define UNIQUE_FUNCTION<%0...%1> %04sg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20013)
		#define UNIQUE_FUNCTION<%0...%1> %04sh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20014)
		#define UNIQUE_FUNCTION<%0...%1> %04si%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20015)
		#define UNIQUE_FUNCTION<%0...%1> %04sj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (20023)
	#elseif UNIQUE_SYMBOL == (20015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20016)
		#define UNIQUE_FUNCTION<%0...%1> %04sk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20017)
		#define UNIQUE_FUNCTION<%0...%1> %04sl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20018)
		#define UNIQUE_FUNCTION<%0...%1> %04sm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20019)
		#define UNIQUE_FUNCTION<%0...%1> %04sn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20020)
		#define UNIQUE_FUNCTION<%0...%1> %04so%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20021)
		#define UNIQUE_FUNCTION<%0...%1> %04sp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20022)
		#define UNIQUE_FUNCTION<%0...%1> %04sq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20023)
		#define UNIQUE_FUNCTION<%0...%1> %04sr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (20023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20024)
		#define UNIQUE_FUNCTION<%0...%1> %04ss%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20025)
		#define UNIQUE_FUNCTION<%0...%1> %04st%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20026)
		#define UNIQUE_FUNCTION<%0...%1> %04su%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20027)
		#define UNIQUE_FUNCTION<%0...%1> %04sv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20028)
		#define UNIQUE_FUNCTION<%0...%1> %04sw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20029)
		#define UNIQUE_FUNCTION<%0...%1> %04sx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (20029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20030)
		#define UNIQUE_FUNCTION<%0...%1> %04sy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (20031)
		#define UNIQUE_FUNCTION<%0...%1> %04sz%1
		#endinput
	#endif
#endif
