static stock const Y_UNIQUE_136576_136639_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_136576_136639
	#undef _inc_y_unique_136576_136639
#endif

#if UNIQUE_SYMBOL < (136583)
	#if UNIQUE_SYMBOL == (136575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136576)
		#define UNIQUE_FUNCTION<%0...%1> %0WL0%1
		#endinput
	#if UNIQUE_SYMBOL == (136576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136577)
		#define UNIQUE_FUNCTION<%0...%1> %0WL1%1
		#endinput
	#if UNIQUE_SYMBOL == (136577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136578)
		#define UNIQUE_FUNCTION<%0...%1> %0WL2%1
		#endinput
	#if UNIQUE_SYMBOL == (136578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136579)
		#define UNIQUE_FUNCTION<%0...%1> %0WL3%1
		#endinput
	#if UNIQUE_SYMBOL == (136579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136580)
		#define UNIQUE_FUNCTION<%0...%1> %0WL4%1
		#endinput
	#if UNIQUE_SYMBOL == (136580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136581)
		#define UNIQUE_FUNCTION<%0...%1> %0WL5%1
		#endinput
	#if UNIQUE_SYMBOL == (136581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136582)
		#define UNIQUE_FUNCTION<%0...%1> %0WL6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136583)
		#define UNIQUE_FUNCTION<%0...%1> %0WL7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136591)
	#elseif UNIQUE_SYMBOL == (136583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136584)
		#define UNIQUE_FUNCTION<%0...%1> %0WL8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136585)
		#define UNIQUE_FUNCTION<%0...%1> %0WL9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136586)
		#define UNIQUE_FUNCTION<%0...%1> %0WL@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136587)
		#define UNIQUE_FUNCTION<%0...%1> %0WLA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136588)
		#define UNIQUE_FUNCTION<%0...%1> %0WLB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136589)
		#define UNIQUE_FUNCTION<%0...%1> %0WLC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136590)
		#define UNIQUE_FUNCTION<%0...%1> %0WLD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136591)
		#define UNIQUE_FUNCTION<%0...%1> %0WLE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136599)
	#elseif UNIQUE_SYMBOL == (136591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136592)
		#define UNIQUE_FUNCTION<%0...%1> %0WLF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136593)
		#define UNIQUE_FUNCTION<%0...%1> %0WLG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136594)
		#define UNIQUE_FUNCTION<%0...%1> %0WLH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136595)
		#define UNIQUE_FUNCTION<%0...%1> %0WLI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136596)
		#define UNIQUE_FUNCTION<%0...%1> %0WLJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136597)
		#define UNIQUE_FUNCTION<%0...%1> %0WLK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136598)
		#define UNIQUE_FUNCTION<%0...%1> %0WLL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136599)
		#define UNIQUE_FUNCTION<%0...%1> %0WLM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136607)
	#elseif UNIQUE_SYMBOL == (136599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136600)
		#define UNIQUE_FUNCTION<%0...%1> %0WLN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136601)
		#define UNIQUE_FUNCTION<%0...%1> %0WLO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136602)
		#define UNIQUE_FUNCTION<%0...%1> %0WLP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136603)
		#define UNIQUE_FUNCTION<%0...%1> %0WLQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136604)
		#define UNIQUE_FUNCTION<%0...%1> %0WLR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136605)
		#define UNIQUE_FUNCTION<%0...%1> %0WLS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136606)
		#define UNIQUE_FUNCTION<%0...%1> %0WLT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136607)
		#define UNIQUE_FUNCTION<%0...%1> %0WLU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136615)
	#elseif UNIQUE_SYMBOL == (136607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136608)
		#define UNIQUE_FUNCTION<%0...%1> %0WLV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136609)
		#define UNIQUE_FUNCTION<%0...%1> %0WLW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136610)
		#define UNIQUE_FUNCTION<%0...%1> %0WLX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136611)
		#define UNIQUE_FUNCTION<%0...%1> %0WLY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136612)
		#define UNIQUE_FUNCTION<%0...%1> %0WLZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136613)
		#define UNIQUE_FUNCTION<%0...%1> %0WL_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136614)
		#define UNIQUE_FUNCTION<%0...%1> %0WLa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136615)
		#define UNIQUE_FUNCTION<%0...%1> %0WLb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136623)
	#elseif UNIQUE_SYMBOL == (136615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136616)
		#define UNIQUE_FUNCTION<%0...%1> %0WLc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136617)
		#define UNIQUE_FUNCTION<%0...%1> %0WLd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136618)
		#define UNIQUE_FUNCTION<%0...%1> %0WLe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136619)
		#define UNIQUE_FUNCTION<%0...%1> %0WLf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136620)
		#define UNIQUE_FUNCTION<%0...%1> %0WLg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136621)
		#define UNIQUE_FUNCTION<%0...%1> %0WLh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136622)
		#define UNIQUE_FUNCTION<%0...%1> %0WLi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136623)
		#define UNIQUE_FUNCTION<%0...%1> %0WLj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136631)
	#elseif UNIQUE_SYMBOL == (136623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136624)
		#define UNIQUE_FUNCTION<%0...%1> %0WLk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136625)
		#define UNIQUE_FUNCTION<%0...%1> %0WLl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136626)
		#define UNIQUE_FUNCTION<%0...%1> %0WLm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136627)
		#define UNIQUE_FUNCTION<%0...%1> %0WLn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136628)
		#define UNIQUE_FUNCTION<%0...%1> %0WLo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136629)
		#define UNIQUE_FUNCTION<%0...%1> %0WLp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136630)
		#define UNIQUE_FUNCTION<%0...%1> %0WLq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136631)
		#define UNIQUE_FUNCTION<%0...%1> %0WLr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (136631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136632)
		#define UNIQUE_FUNCTION<%0...%1> %0WLs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136633)
		#define UNIQUE_FUNCTION<%0...%1> %0WLt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136634)
		#define UNIQUE_FUNCTION<%0...%1> %0WLu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136635)
		#define UNIQUE_FUNCTION<%0...%1> %0WLv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136636)
		#define UNIQUE_FUNCTION<%0...%1> %0WLw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136637)
		#define UNIQUE_FUNCTION<%0...%1> %0WLx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136638)
		#define UNIQUE_FUNCTION<%0...%1> %0WLy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136639)
		#define UNIQUE_FUNCTION<%0...%1> %0WLz%1
		#endinput
	#endif
#endif
