static stock const Y_UNIQUE_033472_033535_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_033472_033535
	#undef _inc_y_unique_033472_033535
#endif

#if UNIQUE_SYMBOL < (33479)
	#if UNIQUE_SYMBOL == (33471)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33472)
		#define UNIQUE_FUNCTION<%0...%1> %08A0%1
		#endinput
	#if UNIQUE_SYMBOL == (33472)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33473)
		#define UNIQUE_FUNCTION<%0...%1> %08A1%1
		#endinput
	#if UNIQUE_SYMBOL == (33473)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33474)
		#define UNIQUE_FUNCTION<%0...%1> %08A2%1
		#endinput
	#if UNIQUE_SYMBOL == (33474)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33475)
		#define UNIQUE_FUNCTION<%0...%1> %08A3%1
		#endinput
	#if UNIQUE_SYMBOL == (33475)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33476)
		#define UNIQUE_FUNCTION<%0...%1> %08A4%1
		#endinput
	#if UNIQUE_SYMBOL == (33476)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33477)
		#define UNIQUE_FUNCTION<%0...%1> %08A5%1
		#endinput
	#if UNIQUE_SYMBOL == (33477)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33478)
		#define UNIQUE_FUNCTION<%0...%1> %08A6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33479)
		#define UNIQUE_FUNCTION<%0...%1> %08A7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33487)
	#elseif UNIQUE_SYMBOL == (33479)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33480)
		#define UNIQUE_FUNCTION<%0...%1> %08A8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33480)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33481)
		#define UNIQUE_FUNCTION<%0...%1> %08A9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33481)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33482)
		#define UNIQUE_FUNCTION<%0...%1> %08A@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33482)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33483)
		#define UNIQUE_FUNCTION<%0...%1> %08AA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33483)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33484)
		#define UNIQUE_FUNCTION<%0...%1> %08AB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33484)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33485)
		#define UNIQUE_FUNCTION<%0...%1> %08AC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33485)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33486)
		#define UNIQUE_FUNCTION<%0...%1> %08AD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33487)
		#define UNIQUE_FUNCTION<%0...%1> %08AE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33495)
	#elseif UNIQUE_SYMBOL == (33487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33488)
		#define UNIQUE_FUNCTION<%0...%1> %08AF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33489)
		#define UNIQUE_FUNCTION<%0...%1> %08AG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33490)
		#define UNIQUE_FUNCTION<%0...%1> %08AH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33491)
		#define UNIQUE_FUNCTION<%0...%1> %08AI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33492)
		#define UNIQUE_FUNCTION<%0...%1> %08AJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33493)
		#define UNIQUE_FUNCTION<%0...%1> %08AK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33494)
		#define UNIQUE_FUNCTION<%0...%1> %08AL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33495)
		#define UNIQUE_FUNCTION<%0...%1> %08AM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33503)
	#elseif UNIQUE_SYMBOL == (33495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33496)
		#define UNIQUE_FUNCTION<%0...%1> %08AN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33497)
		#define UNIQUE_FUNCTION<%0...%1> %08AO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33498)
		#define UNIQUE_FUNCTION<%0...%1> %08AP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33499)
		#define UNIQUE_FUNCTION<%0...%1> %08AQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33500)
		#define UNIQUE_FUNCTION<%0...%1> %08AR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33501)
		#define UNIQUE_FUNCTION<%0...%1> %08AS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33502)
		#define UNIQUE_FUNCTION<%0...%1> %08AT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33503)
		#define UNIQUE_FUNCTION<%0...%1> %08AU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33511)
	#elseif UNIQUE_SYMBOL == (33503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33504)
		#define UNIQUE_FUNCTION<%0...%1> %08AV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33505)
		#define UNIQUE_FUNCTION<%0...%1> %08AW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33506)
		#define UNIQUE_FUNCTION<%0...%1> %08AX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33507)
		#define UNIQUE_FUNCTION<%0...%1> %08AY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33508)
		#define UNIQUE_FUNCTION<%0...%1> %08AZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33509)
		#define UNIQUE_FUNCTION<%0...%1> %08A_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33510)
		#define UNIQUE_FUNCTION<%0...%1> %08Aa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33511)
		#define UNIQUE_FUNCTION<%0...%1> %08Ab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33519)
	#elseif UNIQUE_SYMBOL == (33511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33512)
		#define UNIQUE_FUNCTION<%0...%1> %08Ac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33513)
		#define UNIQUE_FUNCTION<%0...%1> %08Ad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33514)
		#define UNIQUE_FUNCTION<%0...%1> %08Ae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33515)
		#define UNIQUE_FUNCTION<%0...%1> %08Af%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33516)
		#define UNIQUE_FUNCTION<%0...%1> %08Ag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33517)
		#define UNIQUE_FUNCTION<%0...%1> %08Ah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33518)
		#define UNIQUE_FUNCTION<%0...%1> %08Ai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33519)
		#define UNIQUE_FUNCTION<%0...%1> %08Aj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (33527)
	#elseif UNIQUE_SYMBOL == (33519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33520)
		#define UNIQUE_FUNCTION<%0...%1> %08Ak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33521)
		#define UNIQUE_FUNCTION<%0...%1> %08Al%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33522)
		#define UNIQUE_FUNCTION<%0...%1> %08Am%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33523)
		#define UNIQUE_FUNCTION<%0...%1> %08An%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33524)
		#define UNIQUE_FUNCTION<%0...%1> %08Ao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33525)
		#define UNIQUE_FUNCTION<%0...%1> %08Ap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33526)
		#define UNIQUE_FUNCTION<%0...%1> %08Aq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33527)
		#define UNIQUE_FUNCTION<%0...%1> %08Ar%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (33527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33528)
		#define UNIQUE_FUNCTION<%0...%1> %08As%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33529)
		#define UNIQUE_FUNCTION<%0...%1> %08At%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33530)
		#define UNIQUE_FUNCTION<%0...%1> %08Au%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33531)
		#define UNIQUE_FUNCTION<%0...%1> %08Av%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33532)
		#define UNIQUE_FUNCTION<%0...%1> %08Aw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33533)
		#define UNIQUE_FUNCTION<%0...%1> %08Ax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (33533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33534)
		#define UNIQUE_FUNCTION<%0...%1> %08Ay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (33535)
		#define UNIQUE_FUNCTION<%0...%1> %08Az%1
		#endinput
	#endif
#endif
