static stock const Y_UNIQUE_134784_134847_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_134784_134847
	#undef _inc_y_unique_134784_134847
#endif

#if UNIQUE_SYMBOL < (134791)
	#if UNIQUE_SYMBOL == (134783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134784)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu0%1
		#endinput
	#if UNIQUE_SYMBOL == (134784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134785)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu1%1
		#endinput
	#if UNIQUE_SYMBOL == (134785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134786)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu2%1
		#endinput
	#if UNIQUE_SYMBOL == (134786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134787)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu3%1
		#endinput
	#if UNIQUE_SYMBOL == (134787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134788)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu4%1
		#endinput
	#if UNIQUE_SYMBOL == (134788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134789)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu5%1
		#endinput
	#if UNIQUE_SYMBOL == (134789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134790)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134791)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (134799)
	#elseif UNIQUE_SYMBOL == (134791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134792)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134793)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134794)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134795)
		#define UNIQUE_FUNCTION<%0...%1> %0VuA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134796)
		#define UNIQUE_FUNCTION<%0...%1> %0VuB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134797)
		#define UNIQUE_FUNCTION<%0...%1> %0VuC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134798)
		#define UNIQUE_FUNCTION<%0...%1> %0VuD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134799)
		#define UNIQUE_FUNCTION<%0...%1> %0VuE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (134807)
	#elseif UNIQUE_SYMBOL == (134799)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134800)
		#define UNIQUE_FUNCTION<%0...%1> %0VuF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134800)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134801)
		#define UNIQUE_FUNCTION<%0...%1> %0VuG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134801)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134802)
		#define UNIQUE_FUNCTION<%0...%1> %0VuH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134802)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134803)
		#define UNIQUE_FUNCTION<%0...%1> %0VuI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134803)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134804)
		#define UNIQUE_FUNCTION<%0...%1> %0VuJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134804)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134805)
		#define UNIQUE_FUNCTION<%0...%1> %0VuK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134805)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134806)
		#define UNIQUE_FUNCTION<%0...%1> %0VuL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134807)
		#define UNIQUE_FUNCTION<%0...%1> %0VuM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (134815)
	#elseif UNIQUE_SYMBOL == (134807)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134808)
		#define UNIQUE_FUNCTION<%0...%1> %0VuN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134808)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134809)
		#define UNIQUE_FUNCTION<%0...%1> %0VuO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134809)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134810)
		#define UNIQUE_FUNCTION<%0...%1> %0VuP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134810)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134811)
		#define UNIQUE_FUNCTION<%0...%1> %0VuQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134811)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134812)
		#define UNIQUE_FUNCTION<%0...%1> %0VuR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134812)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134813)
		#define UNIQUE_FUNCTION<%0...%1> %0VuS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134813)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134814)
		#define UNIQUE_FUNCTION<%0...%1> %0VuT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134815)
		#define UNIQUE_FUNCTION<%0...%1> %0VuU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (134823)
	#elseif UNIQUE_SYMBOL == (134815)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134816)
		#define UNIQUE_FUNCTION<%0...%1> %0VuV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134816)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134817)
		#define UNIQUE_FUNCTION<%0...%1> %0VuW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134817)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134818)
		#define UNIQUE_FUNCTION<%0...%1> %0VuX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134818)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134819)
		#define UNIQUE_FUNCTION<%0...%1> %0VuY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134819)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134820)
		#define UNIQUE_FUNCTION<%0...%1> %0VuZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134820)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134821)
		#define UNIQUE_FUNCTION<%0...%1> %0Vu_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134821)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134822)
		#define UNIQUE_FUNCTION<%0...%1> %0Vua%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134823)
		#define UNIQUE_FUNCTION<%0...%1> %0Vub%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (134831)
	#elseif UNIQUE_SYMBOL == (134823)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134824)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134824)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134825)
		#define UNIQUE_FUNCTION<%0...%1> %0Vud%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134825)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134826)
		#define UNIQUE_FUNCTION<%0...%1> %0Vue%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134826)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134827)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134827)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134828)
		#define UNIQUE_FUNCTION<%0...%1> %0Vug%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134828)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134829)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134829)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134830)
		#define UNIQUE_FUNCTION<%0...%1> %0Vui%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134831)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (134839)
	#elseif UNIQUE_SYMBOL == (134831)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134832)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134832)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134833)
		#define UNIQUE_FUNCTION<%0...%1> %0Vul%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134833)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134834)
		#define UNIQUE_FUNCTION<%0...%1> %0Vum%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134834)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134835)
		#define UNIQUE_FUNCTION<%0...%1> %0Vun%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134835)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134836)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134836)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134837)
		#define UNIQUE_FUNCTION<%0...%1> %0Vup%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134837)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134838)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134839)
		#define UNIQUE_FUNCTION<%0...%1> %0Vur%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (134839)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134840)
		#define UNIQUE_FUNCTION<%0...%1> %0Vus%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134840)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134841)
		#define UNIQUE_FUNCTION<%0...%1> %0Vut%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134841)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134842)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134842)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134843)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134843)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134844)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134844)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134845)
		#define UNIQUE_FUNCTION<%0...%1> %0Vux%1
		#endinput
	#elseif UNIQUE_SYMBOL == (134845)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134846)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (134847)
		#define UNIQUE_FUNCTION<%0...%1> %0Vuz%1
		#endinput
	#endif
#endif
