static stock const Y_UNIQUE_151104_151167_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_151104_151167
	#undef _inc_y_unique_151104_151167
#endif

#if UNIQUE_SYMBOL < (151111)
	#if UNIQUE_SYMBOL == (151103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151104)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt0%1
		#endinput
	#if UNIQUE_SYMBOL == (151104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151105)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt1%1
		#endinput
	#if UNIQUE_SYMBOL == (151105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151106)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt2%1
		#endinput
	#if UNIQUE_SYMBOL == (151106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151107)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt3%1
		#endinput
	#if UNIQUE_SYMBOL == (151107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151108)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt4%1
		#endinput
	#if UNIQUE_SYMBOL == (151108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151109)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt5%1
		#endinput
	#if UNIQUE_SYMBOL == (151109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151110)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151111)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (151119)
	#elseif UNIQUE_SYMBOL == (151111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151112)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151113)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151114)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151115)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151116)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151117)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151118)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151119)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (151127)
	#elseif UNIQUE_SYMBOL == (151119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151120)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151121)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151122)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151123)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151124)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151125)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151126)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151127)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (151135)
	#elseif UNIQUE_SYMBOL == (151127)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151128)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151128)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151129)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151129)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151130)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151130)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151131)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151131)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151132)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151132)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151133)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151133)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151134)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151135)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (151143)
	#elseif UNIQUE_SYMBOL == (151135)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151136)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151136)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151137)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151137)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151138)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151138)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151139)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151139)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151140)
		#define UNIQUE_FUNCTION<%0...%1> %0ZtZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151140)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151141)
		#define UNIQUE_FUNCTION<%0...%1> %0Zt_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151141)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151142)
		#define UNIQUE_FUNCTION<%0...%1> %0Zta%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151143)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (151151)
	#elseif UNIQUE_SYMBOL == (151143)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151144)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151144)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151145)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151145)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151146)
		#define UNIQUE_FUNCTION<%0...%1> %0Zte%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151146)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151147)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151147)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151148)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151148)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151149)
		#define UNIQUE_FUNCTION<%0...%1> %0Zth%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151149)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151150)
		#define UNIQUE_FUNCTION<%0...%1> %0Zti%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151151)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (151159)
	#elseif UNIQUE_SYMBOL == (151151)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151152)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151152)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151153)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151153)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151154)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151154)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151155)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151155)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151156)
		#define UNIQUE_FUNCTION<%0...%1> %0Zto%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151156)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151157)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151157)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151158)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151159)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (151159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151160)
		#define UNIQUE_FUNCTION<%0...%1> %0Zts%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151161)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151162)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151163)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151164)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151165)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (151165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151166)
		#define UNIQUE_FUNCTION<%0...%1> %0Zty%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (151167)
		#define UNIQUE_FUNCTION<%0...%1> %0Ztz%1
		#endinput
	#endif
#endif
