static stock const Y_UNIQUE_028992_029055_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_028992_029055
	#undef _inc_y_unique_028992_029055
#endif

#if UNIQUE_SYMBOL < (28999)
	#if UNIQUE_SYMBOL == (28991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28992)
		#define UNIQUE_FUNCTION<%0...%1> %0750%1
		#endinput
	#if UNIQUE_SYMBOL == (28992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28993)
		#define UNIQUE_FUNCTION<%0...%1> %0751%1
		#endinput
	#if UNIQUE_SYMBOL == (28993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28994)
		#define UNIQUE_FUNCTION<%0...%1> %0752%1
		#endinput
	#if UNIQUE_SYMBOL == (28994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28995)
		#define UNIQUE_FUNCTION<%0...%1> %0753%1
		#endinput
	#if UNIQUE_SYMBOL == (28995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28996)
		#define UNIQUE_FUNCTION<%0...%1> %0754%1
		#endinput
	#if UNIQUE_SYMBOL == (28996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28997)
		#define UNIQUE_FUNCTION<%0...%1> %0755%1
		#endinput
	#if UNIQUE_SYMBOL == (28997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28998)
		#define UNIQUE_FUNCTION<%0...%1> %0756%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (28999)
		#define UNIQUE_FUNCTION<%0...%1> %0757%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (29007)
	#elseif UNIQUE_SYMBOL == (28999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29000)
		#define UNIQUE_FUNCTION<%0...%1> %0758%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29001)
		#define UNIQUE_FUNCTION<%0...%1> %0759%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29002)
		#define UNIQUE_FUNCTION<%0...%1> %075@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29003)
		#define UNIQUE_FUNCTION<%0...%1> %075A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29004)
		#define UNIQUE_FUNCTION<%0...%1> %075B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29005)
		#define UNIQUE_FUNCTION<%0...%1> %075C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29006)
		#define UNIQUE_FUNCTION<%0...%1> %075D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29007)
		#define UNIQUE_FUNCTION<%0...%1> %075E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (29015)
	#elseif UNIQUE_SYMBOL == (29007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29008)
		#define UNIQUE_FUNCTION<%0...%1> %075F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29009)
		#define UNIQUE_FUNCTION<%0...%1> %075G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29010)
		#define UNIQUE_FUNCTION<%0...%1> %075H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29011)
		#define UNIQUE_FUNCTION<%0...%1> %075I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29012)
		#define UNIQUE_FUNCTION<%0...%1> %075J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29013)
		#define UNIQUE_FUNCTION<%0...%1> %075K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29014)
		#define UNIQUE_FUNCTION<%0...%1> %075L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29015)
		#define UNIQUE_FUNCTION<%0...%1> %075M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (29023)
	#elseif UNIQUE_SYMBOL == (29015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29016)
		#define UNIQUE_FUNCTION<%0...%1> %075N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29017)
		#define UNIQUE_FUNCTION<%0...%1> %075O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29018)
		#define UNIQUE_FUNCTION<%0...%1> %075P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29019)
		#define UNIQUE_FUNCTION<%0...%1> %075Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29020)
		#define UNIQUE_FUNCTION<%0...%1> %075R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29021)
		#define UNIQUE_FUNCTION<%0...%1> %075S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29022)
		#define UNIQUE_FUNCTION<%0...%1> %075T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29023)
		#define UNIQUE_FUNCTION<%0...%1> %075U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (29031)
	#elseif UNIQUE_SYMBOL == (29023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29024)
		#define UNIQUE_FUNCTION<%0...%1> %075V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29025)
		#define UNIQUE_FUNCTION<%0...%1> %075W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29026)
		#define UNIQUE_FUNCTION<%0...%1> %075X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29027)
		#define UNIQUE_FUNCTION<%0...%1> %075Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29028)
		#define UNIQUE_FUNCTION<%0...%1> %075Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29029)
		#define UNIQUE_FUNCTION<%0...%1> %075_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29030)
		#define UNIQUE_FUNCTION<%0...%1> %075a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29031)
		#define UNIQUE_FUNCTION<%0...%1> %075b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (29039)
	#elseif UNIQUE_SYMBOL == (29031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29032)
		#define UNIQUE_FUNCTION<%0...%1> %075c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29033)
		#define UNIQUE_FUNCTION<%0...%1> %075d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29034)
		#define UNIQUE_FUNCTION<%0...%1> %075e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29035)
		#define UNIQUE_FUNCTION<%0...%1> %075f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29036)
		#define UNIQUE_FUNCTION<%0...%1> %075g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29037)
		#define UNIQUE_FUNCTION<%0...%1> %075h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29038)
		#define UNIQUE_FUNCTION<%0...%1> %075i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29039)
		#define UNIQUE_FUNCTION<%0...%1> %075j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (29047)
	#elseif UNIQUE_SYMBOL == (29039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29040)
		#define UNIQUE_FUNCTION<%0...%1> %075k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29041)
		#define UNIQUE_FUNCTION<%0...%1> %075l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29042)
		#define UNIQUE_FUNCTION<%0...%1> %075m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29043)
		#define UNIQUE_FUNCTION<%0...%1> %075n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29044)
		#define UNIQUE_FUNCTION<%0...%1> %075o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29045)
		#define UNIQUE_FUNCTION<%0...%1> %075p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29046)
		#define UNIQUE_FUNCTION<%0...%1> %075q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29047)
		#define UNIQUE_FUNCTION<%0...%1> %075r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (29047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29048)
		#define UNIQUE_FUNCTION<%0...%1> %075s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29049)
		#define UNIQUE_FUNCTION<%0...%1> %075t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29050)
		#define UNIQUE_FUNCTION<%0...%1> %075u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29051)
		#define UNIQUE_FUNCTION<%0...%1> %075v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29052)
		#define UNIQUE_FUNCTION<%0...%1> %075w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29053)
		#define UNIQUE_FUNCTION<%0...%1> %075x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (29053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29054)
		#define UNIQUE_FUNCTION<%0...%1> %075y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (29055)
		#define UNIQUE_FUNCTION<%0...%1> %075z%1
		#endinput
	#endif
#endif
