static stock const Y_UNIQUE_017024_017087_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_017024_017087
	#undef _inc_y_unique_017024_017087
#endif

#if UNIQUE_SYMBOL < (17031)
	#if UNIQUE_SYMBOL == (17023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17024)
		#define UNIQUE_FUNCTION<%0...%1> %04@0%1
		#endinput
	#if UNIQUE_SYMBOL == (17024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17025)
		#define UNIQUE_FUNCTION<%0...%1> %04@1%1
		#endinput
	#if UNIQUE_SYMBOL == (17025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17026)
		#define UNIQUE_FUNCTION<%0...%1> %04@2%1
		#endinput
	#if UNIQUE_SYMBOL == (17026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17027)
		#define UNIQUE_FUNCTION<%0...%1> %04@3%1
		#endinput
	#if UNIQUE_SYMBOL == (17027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17028)
		#define UNIQUE_FUNCTION<%0...%1> %04@4%1
		#endinput
	#if UNIQUE_SYMBOL == (17028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17029)
		#define UNIQUE_FUNCTION<%0...%1> %04@5%1
		#endinput
	#if UNIQUE_SYMBOL == (17029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17030)
		#define UNIQUE_FUNCTION<%0...%1> %04@6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17031)
		#define UNIQUE_FUNCTION<%0...%1> %04@7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17039)
	#elseif UNIQUE_SYMBOL == (17031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17032)
		#define UNIQUE_FUNCTION<%0...%1> %04@8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17033)
		#define UNIQUE_FUNCTION<%0...%1> %04@9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17034)
		#define UNIQUE_FUNCTION<%0...%1> %04@@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17035)
		#define UNIQUE_FUNCTION<%0...%1> %04@A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17036)
		#define UNIQUE_FUNCTION<%0...%1> %04@B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17037)
		#define UNIQUE_FUNCTION<%0...%1> %04@C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17038)
		#define UNIQUE_FUNCTION<%0...%1> %04@D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17039)
		#define UNIQUE_FUNCTION<%0...%1> %04@E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17047)
	#elseif UNIQUE_SYMBOL == (17039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17040)
		#define UNIQUE_FUNCTION<%0...%1> %04@F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17041)
		#define UNIQUE_FUNCTION<%0...%1> %04@G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17042)
		#define UNIQUE_FUNCTION<%0...%1> %04@H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17043)
		#define UNIQUE_FUNCTION<%0...%1> %04@I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17044)
		#define UNIQUE_FUNCTION<%0...%1> %04@J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17045)
		#define UNIQUE_FUNCTION<%0...%1> %04@K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17046)
		#define UNIQUE_FUNCTION<%0...%1> %04@L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17047)
		#define UNIQUE_FUNCTION<%0...%1> %04@M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17055)
	#elseif UNIQUE_SYMBOL == (17047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17048)
		#define UNIQUE_FUNCTION<%0...%1> %04@N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17049)
		#define UNIQUE_FUNCTION<%0...%1> %04@O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17050)
		#define UNIQUE_FUNCTION<%0...%1> %04@P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17051)
		#define UNIQUE_FUNCTION<%0...%1> %04@Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17052)
		#define UNIQUE_FUNCTION<%0...%1> %04@R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17053)
		#define UNIQUE_FUNCTION<%0...%1> %04@S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17054)
		#define UNIQUE_FUNCTION<%0...%1> %04@T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17055)
		#define UNIQUE_FUNCTION<%0...%1> %04@U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17063)
	#elseif UNIQUE_SYMBOL == (17055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17056)
		#define UNIQUE_FUNCTION<%0...%1> %04@V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17057)
		#define UNIQUE_FUNCTION<%0...%1> %04@W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17058)
		#define UNIQUE_FUNCTION<%0...%1> %04@X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17059)
		#define UNIQUE_FUNCTION<%0...%1> %04@Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17060)
		#define UNIQUE_FUNCTION<%0...%1> %04@Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17061)
		#define UNIQUE_FUNCTION<%0...%1> %04@_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17062)
		#define UNIQUE_FUNCTION<%0...%1> %04@a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17063)
		#define UNIQUE_FUNCTION<%0...%1> %04@b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17071)
	#elseif UNIQUE_SYMBOL == (17063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17064)
		#define UNIQUE_FUNCTION<%0...%1> %04@c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17065)
		#define UNIQUE_FUNCTION<%0...%1> %04@d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17066)
		#define UNIQUE_FUNCTION<%0...%1> %04@e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17067)
		#define UNIQUE_FUNCTION<%0...%1> %04@f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17068)
		#define UNIQUE_FUNCTION<%0...%1> %04@g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17069)
		#define UNIQUE_FUNCTION<%0...%1> %04@h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17070)
		#define UNIQUE_FUNCTION<%0...%1> %04@i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17071)
		#define UNIQUE_FUNCTION<%0...%1> %04@j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (17079)
	#elseif UNIQUE_SYMBOL == (17071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17072)
		#define UNIQUE_FUNCTION<%0...%1> %04@k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17073)
		#define UNIQUE_FUNCTION<%0...%1> %04@l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17074)
		#define UNIQUE_FUNCTION<%0...%1> %04@m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17075)
		#define UNIQUE_FUNCTION<%0...%1> %04@n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17076)
		#define UNIQUE_FUNCTION<%0...%1> %04@o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17077)
		#define UNIQUE_FUNCTION<%0...%1> %04@p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17078)
		#define UNIQUE_FUNCTION<%0...%1> %04@q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17079)
		#define UNIQUE_FUNCTION<%0...%1> %04@r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (17079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17080)
		#define UNIQUE_FUNCTION<%0...%1> %04@s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17081)
		#define UNIQUE_FUNCTION<%0...%1> %04@t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17082)
		#define UNIQUE_FUNCTION<%0...%1> %04@u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17083)
		#define UNIQUE_FUNCTION<%0...%1> %04@v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17084)
		#define UNIQUE_FUNCTION<%0...%1> %04@w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17085)
		#define UNIQUE_FUNCTION<%0...%1> %04@x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (17085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17086)
		#define UNIQUE_FUNCTION<%0...%1> %04@y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (17087)
		#define UNIQUE_FUNCTION<%0...%1> %04@z%1
		#endinput
	#endif
#endif
