static stock const Y_UNIQUE_252736_252799_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_252736_252799
	#undef _inc_y_unique_252736_252799
#endif

#if UNIQUE_SYMBOL < (252743)
	#if UNIQUE_SYMBOL == (252735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252736)
		#define UNIQUE_FUNCTION<%0...%1> %0xh0%1
		#endinput
	#if UNIQUE_SYMBOL == (252736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252737)
		#define UNIQUE_FUNCTION<%0...%1> %0xh1%1
		#endinput
	#if UNIQUE_SYMBOL == (252737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252738)
		#define UNIQUE_FUNCTION<%0...%1> %0xh2%1
		#endinput
	#if UNIQUE_SYMBOL == (252738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252739)
		#define UNIQUE_FUNCTION<%0...%1> %0xh3%1
		#endinput
	#if UNIQUE_SYMBOL == (252739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252740)
		#define UNIQUE_FUNCTION<%0...%1> %0xh4%1
		#endinput
	#if UNIQUE_SYMBOL == (252740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252741)
		#define UNIQUE_FUNCTION<%0...%1> %0xh5%1
		#endinput
	#if UNIQUE_SYMBOL == (252741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252742)
		#define UNIQUE_FUNCTION<%0...%1> %0xh6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252743)
		#define UNIQUE_FUNCTION<%0...%1> %0xh7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (252751)
	#elseif UNIQUE_SYMBOL == (252743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252744)
		#define UNIQUE_FUNCTION<%0...%1> %0xh8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252745)
		#define UNIQUE_FUNCTION<%0...%1> %0xh9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252746)
		#define UNIQUE_FUNCTION<%0...%1> %0xh@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252747)
		#define UNIQUE_FUNCTION<%0...%1> %0xhA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252748)
		#define UNIQUE_FUNCTION<%0...%1> %0xhB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252749)
		#define UNIQUE_FUNCTION<%0...%1> %0xhC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252750)
		#define UNIQUE_FUNCTION<%0...%1> %0xhD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252751)
		#define UNIQUE_FUNCTION<%0...%1> %0xhE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (252759)
	#elseif UNIQUE_SYMBOL == (252751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252752)
		#define UNIQUE_FUNCTION<%0...%1> %0xhF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252753)
		#define UNIQUE_FUNCTION<%0...%1> %0xhG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252754)
		#define UNIQUE_FUNCTION<%0...%1> %0xhH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252755)
		#define UNIQUE_FUNCTION<%0...%1> %0xhI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252756)
		#define UNIQUE_FUNCTION<%0...%1> %0xhJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252757)
		#define UNIQUE_FUNCTION<%0...%1> %0xhK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252758)
		#define UNIQUE_FUNCTION<%0...%1> %0xhL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252759)
		#define UNIQUE_FUNCTION<%0...%1> %0xhM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (252767)
	#elseif UNIQUE_SYMBOL == (252759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252760)
		#define UNIQUE_FUNCTION<%0...%1> %0xhN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252761)
		#define UNIQUE_FUNCTION<%0...%1> %0xhO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252762)
		#define UNIQUE_FUNCTION<%0...%1> %0xhP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252763)
		#define UNIQUE_FUNCTION<%0...%1> %0xhQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252764)
		#define UNIQUE_FUNCTION<%0...%1> %0xhR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252765)
		#define UNIQUE_FUNCTION<%0...%1> %0xhS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252766)
		#define UNIQUE_FUNCTION<%0...%1> %0xhT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252767)
		#define UNIQUE_FUNCTION<%0...%1> %0xhU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (252775)
	#elseif UNIQUE_SYMBOL == (252767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252768)
		#define UNIQUE_FUNCTION<%0...%1> %0xhV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252769)
		#define UNIQUE_FUNCTION<%0...%1> %0xhW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252770)
		#define UNIQUE_FUNCTION<%0...%1> %0xhX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252771)
		#define UNIQUE_FUNCTION<%0...%1> %0xhY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252772)
		#define UNIQUE_FUNCTION<%0...%1> %0xhZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252773)
		#define UNIQUE_FUNCTION<%0...%1> %0xh_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252774)
		#define UNIQUE_FUNCTION<%0...%1> %0xha%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252775)
		#define UNIQUE_FUNCTION<%0...%1> %0xhb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (252783)
	#elseif UNIQUE_SYMBOL == (252775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252776)
		#define UNIQUE_FUNCTION<%0...%1> %0xhc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252777)
		#define UNIQUE_FUNCTION<%0...%1> %0xhd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252778)
		#define UNIQUE_FUNCTION<%0...%1> %0xhe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252779)
		#define UNIQUE_FUNCTION<%0...%1> %0xhf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252780)
		#define UNIQUE_FUNCTION<%0...%1> %0xhg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252781)
		#define UNIQUE_FUNCTION<%0...%1> %0xhh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252782)
		#define UNIQUE_FUNCTION<%0...%1> %0xhi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252783)
		#define UNIQUE_FUNCTION<%0...%1> %0xhj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (252791)
	#elseif UNIQUE_SYMBOL == (252783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252784)
		#define UNIQUE_FUNCTION<%0...%1> %0xhk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252785)
		#define UNIQUE_FUNCTION<%0...%1> %0xhl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252786)
		#define UNIQUE_FUNCTION<%0...%1> %0xhm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252787)
		#define UNIQUE_FUNCTION<%0...%1> %0xhn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252788)
		#define UNIQUE_FUNCTION<%0...%1> %0xho%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252789)
		#define UNIQUE_FUNCTION<%0...%1> %0xhp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252790)
		#define UNIQUE_FUNCTION<%0...%1> %0xhq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252791)
		#define UNIQUE_FUNCTION<%0...%1> %0xhr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (252791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252792)
		#define UNIQUE_FUNCTION<%0...%1> %0xhs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252793)
		#define UNIQUE_FUNCTION<%0...%1> %0xht%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252794)
		#define UNIQUE_FUNCTION<%0...%1> %0xhu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252795)
		#define UNIQUE_FUNCTION<%0...%1> %0xhv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252796)
		#define UNIQUE_FUNCTION<%0...%1> %0xhw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252797)
		#define UNIQUE_FUNCTION<%0...%1> %0xhx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (252797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252798)
		#define UNIQUE_FUNCTION<%0...%1> %0xhy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (252799)
		#define UNIQUE_FUNCTION<%0...%1> %0xhz%1
		#endinput
	#endif
#endif
