static stock const Y_UNIQUE_126016_126079_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_126016_126079
	#undef _inc_y_unique_126016_126079
#endif

#if UNIQUE_SYMBOL < (126023)
	#if UNIQUE_SYMBOL == (126015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126016)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl0%1
		#endinput
	#if UNIQUE_SYMBOL == (126016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126017)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl1%1
		#endinput
	#if UNIQUE_SYMBOL == (126017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126018)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl2%1
		#endinput
	#if UNIQUE_SYMBOL == (126018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126019)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl3%1
		#endinput
	#if UNIQUE_SYMBOL == (126019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126020)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl4%1
		#endinput
	#if UNIQUE_SYMBOL == (126020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126021)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl5%1
		#endinput
	#if UNIQUE_SYMBOL == (126021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126022)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126023)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (126031)
	#elseif UNIQUE_SYMBOL == (126023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126024)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126025)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126026)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126027)
		#define UNIQUE_FUNCTION<%0...%1> %0TlA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126028)
		#define UNIQUE_FUNCTION<%0...%1> %0TlB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126029)
		#define UNIQUE_FUNCTION<%0...%1> %0TlC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126030)
		#define UNIQUE_FUNCTION<%0...%1> %0TlD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126031)
		#define UNIQUE_FUNCTION<%0...%1> %0TlE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (126039)
	#elseif UNIQUE_SYMBOL == (126031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126032)
		#define UNIQUE_FUNCTION<%0...%1> %0TlF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126033)
		#define UNIQUE_FUNCTION<%0...%1> %0TlG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126034)
		#define UNIQUE_FUNCTION<%0...%1> %0TlH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126035)
		#define UNIQUE_FUNCTION<%0...%1> %0TlI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126036)
		#define UNIQUE_FUNCTION<%0...%1> %0TlJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126037)
		#define UNIQUE_FUNCTION<%0...%1> %0TlK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126038)
		#define UNIQUE_FUNCTION<%0...%1> %0TlL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126039)
		#define UNIQUE_FUNCTION<%0...%1> %0TlM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (126047)
	#elseif UNIQUE_SYMBOL == (126039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126040)
		#define UNIQUE_FUNCTION<%0...%1> %0TlN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126041)
		#define UNIQUE_FUNCTION<%0...%1> %0TlO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126042)
		#define UNIQUE_FUNCTION<%0...%1> %0TlP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126043)
		#define UNIQUE_FUNCTION<%0...%1> %0TlQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126044)
		#define UNIQUE_FUNCTION<%0...%1> %0TlR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126045)
		#define UNIQUE_FUNCTION<%0...%1> %0TlS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126046)
		#define UNIQUE_FUNCTION<%0...%1> %0TlT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126047)
		#define UNIQUE_FUNCTION<%0...%1> %0TlU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (126055)
	#elseif UNIQUE_SYMBOL == (126047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126048)
		#define UNIQUE_FUNCTION<%0...%1> %0TlV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126049)
		#define UNIQUE_FUNCTION<%0...%1> %0TlW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126050)
		#define UNIQUE_FUNCTION<%0...%1> %0TlX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126051)
		#define UNIQUE_FUNCTION<%0...%1> %0TlY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126052)
		#define UNIQUE_FUNCTION<%0...%1> %0TlZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126053)
		#define UNIQUE_FUNCTION<%0...%1> %0Tl_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126054)
		#define UNIQUE_FUNCTION<%0...%1> %0Tla%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126055)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (126063)
	#elseif UNIQUE_SYMBOL == (126055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126056)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126057)
		#define UNIQUE_FUNCTION<%0...%1> %0Tld%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126058)
		#define UNIQUE_FUNCTION<%0...%1> %0Tle%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126059)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126060)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126061)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126062)
		#define UNIQUE_FUNCTION<%0...%1> %0Tli%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126063)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (126071)
	#elseif UNIQUE_SYMBOL == (126063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126064)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126065)
		#define UNIQUE_FUNCTION<%0...%1> %0Tll%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126066)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126067)
		#define UNIQUE_FUNCTION<%0...%1> %0Tln%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126068)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126069)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126070)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126071)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (126071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126072)
		#define UNIQUE_FUNCTION<%0...%1> %0Tls%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126073)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126074)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126075)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126076)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126077)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (126077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126078)
		#define UNIQUE_FUNCTION<%0...%1> %0Tly%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (126079)
		#define UNIQUE_FUNCTION<%0...%1> %0Tlz%1
		#endinput
	#endif
#endif
