static stock const Y_UNIQUE_050944_051007_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_050944_051007
	#undef _inc_y_unique_050944_051007
#endif

#if UNIQUE_SYMBOL < (50951)
	#if UNIQUE_SYMBOL == (50943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50944)
		#define UNIQUE_FUNCTION<%0...%1> %0BR0%1
		#endinput
	#if UNIQUE_SYMBOL == (50944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50945)
		#define UNIQUE_FUNCTION<%0...%1> %0BR1%1
		#endinput
	#if UNIQUE_SYMBOL == (50945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50946)
		#define UNIQUE_FUNCTION<%0...%1> %0BR2%1
		#endinput
	#if UNIQUE_SYMBOL == (50946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50947)
		#define UNIQUE_FUNCTION<%0...%1> %0BR3%1
		#endinput
	#if UNIQUE_SYMBOL == (50947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50948)
		#define UNIQUE_FUNCTION<%0...%1> %0BR4%1
		#endinput
	#if UNIQUE_SYMBOL == (50948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50949)
		#define UNIQUE_FUNCTION<%0...%1> %0BR5%1
		#endinput
	#if UNIQUE_SYMBOL == (50949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50950)
		#define UNIQUE_FUNCTION<%0...%1> %0BR6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50951)
		#define UNIQUE_FUNCTION<%0...%1> %0BR7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50959)
	#elseif UNIQUE_SYMBOL == (50951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50952)
		#define UNIQUE_FUNCTION<%0...%1> %0BR8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50953)
		#define UNIQUE_FUNCTION<%0...%1> %0BR9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50954)
		#define UNIQUE_FUNCTION<%0...%1> %0BR@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50955)
		#define UNIQUE_FUNCTION<%0...%1> %0BRA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50956)
		#define UNIQUE_FUNCTION<%0...%1> %0BRB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50957)
		#define UNIQUE_FUNCTION<%0...%1> %0BRC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50958)
		#define UNIQUE_FUNCTION<%0...%1> %0BRD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50959)
		#define UNIQUE_FUNCTION<%0...%1> %0BRE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50967)
	#elseif UNIQUE_SYMBOL == (50959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50960)
		#define UNIQUE_FUNCTION<%0...%1> %0BRF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50961)
		#define UNIQUE_FUNCTION<%0...%1> %0BRG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50962)
		#define UNIQUE_FUNCTION<%0...%1> %0BRH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50963)
		#define UNIQUE_FUNCTION<%0...%1> %0BRI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50964)
		#define UNIQUE_FUNCTION<%0...%1> %0BRJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50965)
		#define UNIQUE_FUNCTION<%0...%1> %0BRK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50966)
		#define UNIQUE_FUNCTION<%0...%1> %0BRL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50967)
		#define UNIQUE_FUNCTION<%0...%1> %0BRM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50975)
	#elseif UNIQUE_SYMBOL == (50967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50968)
		#define UNIQUE_FUNCTION<%0...%1> %0BRN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50969)
		#define UNIQUE_FUNCTION<%0...%1> %0BRO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50970)
		#define UNIQUE_FUNCTION<%0...%1> %0BRP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50971)
		#define UNIQUE_FUNCTION<%0...%1> %0BRQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50972)
		#define UNIQUE_FUNCTION<%0...%1> %0BRR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50973)
		#define UNIQUE_FUNCTION<%0...%1> %0BRS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50974)
		#define UNIQUE_FUNCTION<%0...%1> %0BRT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50975)
		#define UNIQUE_FUNCTION<%0...%1> %0BRU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50983)
	#elseif UNIQUE_SYMBOL == (50975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50976)
		#define UNIQUE_FUNCTION<%0...%1> %0BRV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50977)
		#define UNIQUE_FUNCTION<%0...%1> %0BRW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50978)
		#define UNIQUE_FUNCTION<%0...%1> %0BRX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50979)
		#define UNIQUE_FUNCTION<%0...%1> %0BRY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50980)
		#define UNIQUE_FUNCTION<%0...%1> %0BRZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50981)
		#define UNIQUE_FUNCTION<%0...%1> %0BR_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50982)
		#define UNIQUE_FUNCTION<%0...%1> %0BRa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50983)
		#define UNIQUE_FUNCTION<%0...%1> %0BRb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50991)
	#elseif UNIQUE_SYMBOL == (50983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50984)
		#define UNIQUE_FUNCTION<%0...%1> %0BRc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50985)
		#define UNIQUE_FUNCTION<%0...%1> %0BRd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50986)
		#define UNIQUE_FUNCTION<%0...%1> %0BRe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50987)
		#define UNIQUE_FUNCTION<%0...%1> %0BRf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50988)
		#define UNIQUE_FUNCTION<%0...%1> %0BRg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50989)
		#define UNIQUE_FUNCTION<%0...%1> %0BRh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50990)
		#define UNIQUE_FUNCTION<%0...%1> %0BRi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50991)
		#define UNIQUE_FUNCTION<%0...%1> %0BRj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (50999)
	#elseif UNIQUE_SYMBOL == (50991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50992)
		#define UNIQUE_FUNCTION<%0...%1> %0BRk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50993)
		#define UNIQUE_FUNCTION<%0...%1> %0BRl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50994)
		#define UNIQUE_FUNCTION<%0...%1> %0BRm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50995)
		#define UNIQUE_FUNCTION<%0...%1> %0BRn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50996)
		#define UNIQUE_FUNCTION<%0...%1> %0BRo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50997)
		#define UNIQUE_FUNCTION<%0...%1> %0BRp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (50997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50998)
		#define UNIQUE_FUNCTION<%0...%1> %0BRq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (50999)
		#define UNIQUE_FUNCTION<%0...%1> %0BRr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (50999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51000)
		#define UNIQUE_FUNCTION<%0...%1> %0BRs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51001)
		#define UNIQUE_FUNCTION<%0...%1> %0BRt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51002)
		#define UNIQUE_FUNCTION<%0...%1> %0BRu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51003)
		#define UNIQUE_FUNCTION<%0...%1> %0BRv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51004)
		#define UNIQUE_FUNCTION<%0...%1> %0BRw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51005)
		#define UNIQUE_FUNCTION<%0...%1> %0BRx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (51005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51006)
		#define UNIQUE_FUNCTION<%0...%1> %0BRy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (51007)
		#define UNIQUE_FUNCTION<%0...%1> %0BRz%1
		#endinput
	#endif
#endif
