static stock const Y_UNIQUE_153536_153599_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_153536_153599
	#undef _inc_y_unique_153536_153599
#endif

#if UNIQUE_SYMBOL < (153543)
	#if UNIQUE_SYMBOL == (153535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153536)
		#define UNIQUE_FUNCTION<%0...%1> %0_U0%1
		#endinput
	#if UNIQUE_SYMBOL == (153536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153537)
		#define UNIQUE_FUNCTION<%0...%1> %0_U1%1
		#endinput
	#if UNIQUE_SYMBOL == (153537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153538)
		#define UNIQUE_FUNCTION<%0...%1> %0_U2%1
		#endinput
	#if UNIQUE_SYMBOL == (153538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153539)
		#define UNIQUE_FUNCTION<%0...%1> %0_U3%1
		#endinput
	#if UNIQUE_SYMBOL == (153539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153540)
		#define UNIQUE_FUNCTION<%0...%1> %0_U4%1
		#endinput
	#if UNIQUE_SYMBOL == (153540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153541)
		#define UNIQUE_FUNCTION<%0...%1> %0_U5%1
		#endinput
	#if UNIQUE_SYMBOL == (153541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153542)
		#define UNIQUE_FUNCTION<%0...%1> %0_U6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153543)
		#define UNIQUE_FUNCTION<%0...%1> %0_U7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (153551)
	#elseif UNIQUE_SYMBOL == (153543)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153544)
		#define UNIQUE_FUNCTION<%0...%1> %0_U8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153544)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153545)
		#define UNIQUE_FUNCTION<%0...%1> %0_U9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153545)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153546)
		#define UNIQUE_FUNCTION<%0...%1> %0_U@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153546)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153547)
		#define UNIQUE_FUNCTION<%0...%1> %0_UA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153547)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153548)
		#define UNIQUE_FUNCTION<%0...%1> %0_UB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153548)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153549)
		#define UNIQUE_FUNCTION<%0...%1> %0_UC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153549)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153550)
		#define UNIQUE_FUNCTION<%0...%1> %0_UD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153551)
		#define UNIQUE_FUNCTION<%0...%1> %0_UE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (153559)
	#elseif UNIQUE_SYMBOL == (153551)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153552)
		#define UNIQUE_FUNCTION<%0...%1> %0_UF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153552)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153553)
		#define UNIQUE_FUNCTION<%0...%1> %0_UG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153553)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153554)
		#define UNIQUE_FUNCTION<%0...%1> %0_UH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153554)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153555)
		#define UNIQUE_FUNCTION<%0...%1> %0_UI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153555)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153556)
		#define UNIQUE_FUNCTION<%0...%1> %0_UJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153556)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153557)
		#define UNIQUE_FUNCTION<%0...%1> %0_UK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153557)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153558)
		#define UNIQUE_FUNCTION<%0...%1> %0_UL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153559)
		#define UNIQUE_FUNCTION<%0...%1> %0_UM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (153567)
	#elseif UNIQUE_SYMBOL == (153559)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153560)
		#define UNIQUE_FUNCTION<%0...%1> %0_UN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153560)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153561)
		#define UNIQUE_FUNCTION<%0...%1> %0_UO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153561)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153562)
		#define UNIQUE_FUNCTION<%0...%1> %0_UP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153562)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153563)
		#define UNIQUE_FUNCTION<%0...%1> %0_UQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153563)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153564)
		#define UNIQUE_FUNCTION<%0...%1> %0_UR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153564)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153565)
		#define UNIQUE_FUNCTION<%0...%1> %0_US%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153565)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153566)
		#define UNIQUE_FUNCTION<%0...%1> %0_UT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153567)
		#define UNIQUE_FUNCTION<%0...%1> %0_UU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (153575)
	#elseif UNIQUE_SYMBOL == (153567)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153568)
		#define UNIQUE_FUNCTION<%0...%1> %0_UV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153568)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153569)
		#define UNIQUE_FUNCTION<%0...%1> %0_UW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153569)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153570)
		#define UNIQUE_FUNCTION<%0...%1> %0_UX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153570)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153571)
		#define UNIQUE_FUNCTION<%0...%1> %0_UY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153571)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153572)
		#define UNIQUE_FUNCTION<%0...%1> %0_UZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153572)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153573)
		#define UNIQUE_FUNCTION<%0...%1> %0_U_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153573)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153574)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ua%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153575)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ub%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (153583)
	#elseif UNIQUE_SYMBOL == (153575)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153576)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153576)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153577)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ud%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153577)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153578)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ue%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153578)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153579)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153579)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153580)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ug%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153580)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153581)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153581)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153582)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ui%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153583)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (153591)
	#elseif UNIQUE_SYMBOL == (153583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153584)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153585)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ul%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153586)
		#define UNIQUE_FUNCTION<%0...%1> %0_Um%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153587)
		#define UNIQUE_FUNCTION<%0...%1> %0_Un%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153588)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153589)
		#define UNIQUE_FUNCTION<%0...%1> %0_Up%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153590)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153591)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ur%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (153591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153592)
		#define UNIQUE_FUNCTION<%0...%1> %0_Us%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153593)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ut%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153594)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153595)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153596)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153597)
		#define UNIQUE_FUNCTION<%0...%1> %0_Ux%1
		#endinput
	#elseif UNIQUE_SYMBOL == (153597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153598)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (153599)
		#define UNIQUE_FUNCTION<%0...%1> %0_Uz%1
		#endinput
	#endif
#endif
