static stock const Y_UNIQUE_036608_036671_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_036608_036671
	#undef _inc_y_unique_036608_036671
#endif

#if UNIQUE_SYMBOL < (36615)
	#if UNIQUE_SYMBOL == (36607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36608)
		#define UNIQUE_FUNCTION<%0...%1> %08w0%1
		#endinput
	#if UNIQUE_SYMBOL == (36608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36609)
		#define UNIQUE_FUNCTION<%0...%1> %08w1%1
		#endinput
	#if UNIQUE_SYMBOL == (36609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36610)
		#define UNIQUE_FUNCTION<%0...%1> %08w2%1
		#endinput
	#if UNIQUE_SYMBOL == (36610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36611)
		#define UNIQUE_FUNCTION<%0...%1> %08w3%1
		#endinput
	#if UNIQUE_SYMBOL == (36611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36612)
		#define UNIQUE_FUNCTION<%0...%1> %08w4%1
		#endinput
	#if UNIQUE_SYMBOL == (36612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36613)
		#define UNIQUE_FUNCTION<%0...%1> %08w5%1
		#endinput
	#if UNIQUE_SYMBOL == (36613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36614)
		#define UNIQUE_FUNCTION<%0...%1> %08w6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36615)
		#define UNIQUE_FUNCTION<%0...%1> %08w7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36623)
	#elseif UNIQUE_SYMBOL == (36615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36616)
		#define UNIQUE_FUNCTION<%0...%1> %08w8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36617)
		#define UNIQUE_FUNCTION<%0...%1> %08w9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36618)
		#define UNIQUE_FUNCTION<%0...%1> %08w@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36619)
		#define UNIQUE_FUNCTION<%0...%1> %08wA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36620)
		#define UNIQUE_FUNCTION<%0...%1> %08wB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36621)
		#define UNIQUE_FUNCTION<%0...%1> %08wC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36622)
		#define UNIQUE_FUNCTION<%0...%1> %08wD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36623)
		#define UNIQUE_FUNCTION<%0...%1> %08wE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36631)
	#elseif UNIQUE_SYMBOL == (36623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36624)
		#define UNIQUE_FUNCTION<%0...%1> %08wF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36625)
		#define UNIQUE_FUNCTION<%0...%1> %08wG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36626)
		#define UNIQUE_FUNCTION<%0...%1> %08wH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36627)
		#define UNIQUE_FUNCTION<%0...%1> %08wI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36628)
		#define UNIQUE_FUNCTION<%0...%1> %08wJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36629)
		#define UNIQUE_FUNCTION<%0...%1> %08wK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36630)
		#define UNIQUE_FUNCTION<%0...%1> %08wL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36631)
		#define UNIQUE_FUNCTION<%0...%1> %08wM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36639)
	#elseif UNIQUE_SYMBOL == (36631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36632)
		#define UNIQUE_FUNCTION<%0...%1> %08wN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36633)
		#define UNIQUE_FUNCTION<%0...%1> %08wO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36634)
		#define UNIQUE_FUNCTION<%0...%1> %08wP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36635)
		#define UNIQUE_FUNCTION<%0...%1> %08wQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36636)
		#define UNIQUE_FUNCTION<%0...%1> %08wR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36637)
		#define UNIQUE_FUNCTION<%0...%1> %08wS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36638)
		#define UNIQUE_FUNCTION<%0...%1> %08wT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36639)
		#define UNIQUE_FUNCTION<%0...%1> %08wU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36647)
	#elseif UNIQUE_SYMBOL == (36639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36640)
		#define UNIQUE_FUNCTION<%0...%1> %08wV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36641)
		#define UNIQUE_FUNCTION<%0...%1> %08wW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36642)
		#define UNIQUE_FUNCTION<%0...%1> %08wX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36643)
		#define UNIQUE_FUNCTION<%0...%1> %08wY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36644)
		#define UNIQUE_FUNCTION<%0...%1> %08wZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36645)
		#define UNIQUE_FUNCTION<%0...%1> %08w_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36646)
		#define UNIQUE_FUNCTION<%0...%1> %08wa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36647)
		#define UNIQUE_FUNCTION<%0...%1> %08wb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36655)
	#elseif UNIQUE_SYMBOL == (36647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36648)
		#define UNIQUE_FUNCTION<%0...%1> %08wc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36649)
		#define UNIQUE_FUNCTION<%0...%1> %08wd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36650)
		#define UNIQUE_FUNCTION<%0...%1> %08we%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36651)
		#define UNIQUE_FUNCTION<%0...%1> %08wf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36652)
		#define UNIQUE_FUNCTION<%0...%1> %08wg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36653)
		#define UNIQUE_FUNCTION<%0...%1> %08wh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36654)
		#define UNIQUE_FUNCTION<%0...%1> %08wi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36655)
		#define UNIQUE_FUNCTION<%0...%1> %08wj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (36663)
	#elseif UNIQUE_SYMBOL == (36655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36656)
		#define UNIQUE_FUNCTION<%0...%1> %08wk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36657)
		#define UNIQUE_FUNCTION<%0...%1> %08wl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36658)
		#define UNIQUE_FUNCTION<%0...%1> %08wm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36659)
		#define UNIQUE_FUNCTION<%0...%1> %08wn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36660)
		#define UNIQUE_FUNCTION<%0...%1> %08wo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36661)
		#define UNIQUE_FUNCTION<%0...%1> %08wp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36662)
		#define UNIQUE_FUNCTION<%0...%1> %08wq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36663)
		#define UNIQUE_FUNCTION<%0...%1> %08wr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (36663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36664)
		#define UNIQUE_FUNCTION<%0...%1> %08ws%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36665)
		#define UNIQUE_FUNCTION<%0...%1> %08wt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36666)
		#define UNIQUE_FUNCTION<%0...%1> %08wu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36667)
		#define UNIQUE_FUNCTION<%0...%1> %08wv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36668)
		#define UNIQUE_FUNCTION<%0...%1> %08ww%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36669)
		#define UNIQUE_FUNCTION<%0...%1> %08wx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (36669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36670)
		#define UNIQUE_FUNCTION<%0...%1> %08wy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (36671)
		#define UNIQUE_FUNCTION<%0...%1> %08wz%1
		#endinput
	#endif
#endif
