static stock const Y_UNIQUE_212288_212351_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_212288_212351
	#undef _inc_y_unique_212288_212351
#endif

#if UNIQUE_SYMBOL < (212295)
	#if UNIQUE_SYMBOL == (212287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212288)
		#define UNIQUE_FUNCTION<%0...%1> %0np0%1
		#endinput
	#if UNIQUE_SYMBOL == (212288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212289)
		#define UNIQUE_FUNCTION<%0...%1> %0np1%1
		#endinput
	#if UNIQUE_SYMBOL == (212289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212290)
		#define UNIQUE_FUNCTION<%0...%1> %0np2%1
		#endinput
	#if UNIQUE_SYMBOL == (212290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212291)
		#define UNIQUE_FUNCTION<%0...%1> %0np3%1
		#endinput
	#if UNIQUE_SYMBOL == (212291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212292)
		#define UNIQUE_FUNCTION<%0...%1> %0np4%1
		#endinput
	#if UNIQUE_SYMBOL == (212292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212293)
		#define UNIQUE_FUNCTION<%0...%1> %0np5%1
		#endinput
	#if UNIQUE_SYMBOL == (212293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212294)
		#define UNIQUE_FUNCTION<%0...%1> %0np6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212295)
		#define UNIQUE_FUNCTION<%0...%1> %0np7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212303)
	#elseif UNIQUE_SYMBOL == (212295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212296)
		#define UNIQUE_FUNCTION<%0...%1> %0np8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212297)
		#define UNIQUE_FUNCTION<%0...%1> %0np9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212298)
		#define UNIQUE_FUNCTION<%0...%1> %0np@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212299)
		#define UNIQUE_FUNCTION<%0...%1> %0npA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212300)
		#define UNIQUE_FUNCTION<%0...%1> %0npB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212301)
		#define UNIQUE_FUNCTION<%0...%1> %0npC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212302)
		#define UNIQUE_FUNCTION<%0...%1> %0npD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212303)
		#define UNIQUE_FUNCTION<%0...%1> %0npE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212311)
	#elseif UNIQUE_SYMBOL == (212303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212304)
		#define UNIQUE_FUNCTION<%0...%1> %0npF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212305)
		#define UNIQUE_FUNCTION<%0...%1> %0npG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212306)
		#define UNIQUE_FUNCTION<%0...%1> %0npH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212307)
		#define UNIQUE_FUNCTION<%0...%1> %0npI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212308)
		#define UNIQUE_FUNCTION<%0...%1> %0npJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212309)
		#define UNIQUE_FUNCTION<%0...%1> %0npK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212310)
		#define UNIQUE_FUNCTION<%0...%1> %0npL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212311)
		#define UNIQUE_FUNCTION<%0...%1> %0npM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212319)
	#elseif UNIQUE_SYMBOL == (212311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212312)
		#define UNIQUE_FUNCTION<%0...%1> %0npN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212313)
		#define UNIQUE_FUNCTION<%0...%1> %0npO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212314)
		#define UNIQUE_FUNCTION<%0...%1> %0npP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212315)
		#define UNIQUE_FUNCTION<%0...%1> %0npQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212316)
		#define UNIQUE_FUNCTION<%0...%1> %0npR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212317)
		#define UNIQUE_FUNCTION<%0...%1> %0npS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212318)
		#define UNIQUE_FUNCTION<%0...%1> %0npT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212319)
		#define UNIQUE_FUNCTION<%0...%1> %0npU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212327)
	#elseif UNIQUE_SYMBOL == (212319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212320)
		#define UNIQUE_FUNCTION<%0...%1> %0npV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212321)
		#define UNIQUE_FUNCTION<%0...%1> %0npW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212322)
		#define UNIQUE_FUNCTION<%0...%1> %0npX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212323)
		#define UNIQUE_FUNCTION<%0...%1> %0npY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212324)
		#define UNIQUE_FUNCTION<%0...%1> %0npZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212325)
		#define UNIQUE_FUNCTION<%0...%1> %0np_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212326)
		#define UNIQUE_FUNCTION<%0...%1> %0npa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212327)
		#define UNIQUE_FUNCTION<%0...%1> %0npb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212335)
	#elseif UNIQUE_SYMBOL == (212327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212328)
		#define UNIQUE_FUNCTION<%0...%1> %0npc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212329)
		#define UNIQUE_FUNCTION<%0...%1> %0npd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212330)
		#define UNIQUE_FUNCTION<%0...%1> %0npe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212331)
		#define UNIQUE_FUNCTION<%0...%1> %0npf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212332)
		#define UNIQUE_FUNCTION<%0...%1> %0npg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212333)
		#define UNIQUE_FUNCTION<%0...%1> %0nph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212334)
		#define UNIQUE_FUNCTION<%0...%1> %0npi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212335)
		#define UNIQUE_FUNCTION<%0...%1> %0npj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212343)
	#elseif UNIQUE_SYMBOL == (212335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212336)
		#define UNIQUE_FUNCTION<%0...%1> %0npk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212337)
		#define UNIQUE_FUNCTION<%0...%1> %0npl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212338)
		#define UNIQUE_FUNCTION<%0...%1> %0npm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212339)
		#define UNIQUE_FUNCTION<%0...%1> %0npn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212340)
		#define UNIQUE_FUNCTION<%0...%1> %0npo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212341)
		#define UNIQUE_FUNCTION<%0...%1> %0npp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212342)
		#define UNIQUE_FUNCTION<%0...%1> %0npq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212343)
		#define UNIQUE_FUNCTION<%0...%1> %0npr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (212343)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212344)
		#define UNIQUE_FUNCTION<%0...%1> %0nps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212344)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212345)
		#define UNIQUE_FUNCTION<%0...%1> %0npt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212345)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212346)
		#define UNIQUE_FUNCTION<%0...%1> %0npu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212346)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212347)
		#define UNIQUE_FUNCTION<%0...%1> %0npv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212347)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212348)
		#define UNIQUE_FUNCTION<%0...%1> %0npw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212348)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212349)
		#define UNIQUE_FUNCTION<%0...%1> %0npx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212349)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212350)
		#define UNIQUE_FUNCTION<%0...%1> %0npy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212351)
		#define UNIQUE_FUNCTION<%0...%1> %0npz%1
		#endinput
	#endif
#endif
