static stock const Y_UNIQUE_011584_011647_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_011584_011647
	#undef _inc_y_unique_011584_011647
#endif

#if UNIQUE_SYMBOL < (11591)
	#if UNIQUE_SYMBOL == (11583)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11584)
		#define UNIQUE_FUNCTION<%0...%1> %02p0%1
		#endinput
	#if UNIQUE_SYMBOL == (11584)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11585)
		#define UNIQUE_FUNCTION<%0...%1> %02p1%1
		#endinput
	#if UNIQUE_SYMBOL == (11585)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11586)
		#define UNIQUE_FUNCTION<%0...%1> %02p2%1
		#endinput
	#if UNIQUE_SYMBOL == (11586)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11587)
		#define UNIQUE_FUNCTION<%0...%1> %02p3%1
		#endinput
	#if UNIQUE_SYMBOL == (11587)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11588)
		#define UNIQUE_FUNCTION<%0...%1> %02p4%1
		#endinput
	#if UNIQUE_SYMBOL == (11588)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11589)
		#define UNIQUE_FUNCTION<%0...%1> %02p5%1
		#endinput
	#if UNIQUE_SYMBOL == (11589)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11590)
		#define UNIQUE_FUNCTION<%0...%1> %02p6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11591)
		#define UNIQUE_FUNCTION<%0...%1> %02p7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (11599)
	#elseif UNIQUE_SYMBOL == (11591)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11592)
		#define UNIQUE_FUNCTION<%0...%1> %02p8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11592)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11593)
		#define UNIQUE_FUNCTION<%0...%1> %02p9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11593)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11594)
		#define UNIQUE_FUNCTION<%0...%1> %02p@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11594)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11595)
		#define UNIQUE_FUNCTION<%0...%1> %02pA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11595)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11596)
		#define UNIQUE_FUNCTION<%0...%1> %02pB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11596)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11597)
		#define UNIQUE_FUNCTION<%0...%1> %02pC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11597)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11598)
		#define UNIQUE_FUNCTION<%0...%1> %02pD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11599)
		#define UNIQUE_FUNCTION<%0...%1> %02pE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (11607)
	#elseif UNIQUE_SYMBOL == (11599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11600)
		#define UNIQUE_FUNCTION<%0...%1> %02pF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11601)
		#define UNIQUE_FUNCTION<%0...%1> %02pG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11602)
		#define UNIQUE_FUNCTION<%0...%1> %02pH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11603)
		#define UNIQUE_FUNCTION<%0...%1> %02pI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11604)
		#define UNIQUE_FUNCTION<%0...%1> %02pJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11605)
		#define UNIQUE_FUNCTION<%0...%1> %02pK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11606)
		#define UNIQUE_FUNCTION<%0...%1> %02pL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11607)
		#define UNIQUE_FUNCTION<%0...%1> %02pM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (11615)
	#elseif UNIQUE_SYMBOL == (11607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11608)
		#define UNIQUE_FUNCTION<%0...%1> %02pN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11609)
		#define UNIQUE_FUNCTION<%0...%1> %02pO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11610)
		#define UNIQUE_FUNCTION<%0...%1> %02pP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11611)
		#define UNIQUE_FUNCTION<%0...%1> %02pQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11612)
		#define UNIQUE_FUNCTION<%0...%1> %02pR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11613)
		#define UNIQUE_FUNCTION<%0...%1> %02pS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11614)
		#define UNIQUE_FUNCTION<%0...%1> %02pT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11615)
		#define UNIQUE_FUNCTION<%0...%1> %02pU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (11623)
	#elseif UNIQUE_SYMBOL == (11615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11616)
		#define UNIQUE_FUNCTION<%0...%1> %02pV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11617)
		#define UNIQUE_FUNCTION<%0...%1> %02pW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11618)
		#define UNIQUE_FUNCTION<%0...%1> %02pX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11619)
		#define UNIQUE_FUNCTION<%0...%1> %02pY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11620)
		#define UNIQUE_FUNCTION<%0...%1> %02pZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11621)
		#define UNIQUE_FUNCTION<%0...%1> %02p_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11622)
		#define UNIQUE_FUNCTION<%0...%1> %02pa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11623)
		#define UNIQUE_FUNCTION<%0...%1> %02pb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (11631)
	#elseif UNIQUE_SYMBOL == (11623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11624)
		#define UNIQUE_FUNCTION<%0...%1> %02pc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11625)
		#define UNIQUE_FUNCTION<%0...%1> %02pd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11626)
		#define UNIQUE_FUNCTION<%0...%1> %02pe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11627)
		#define UNIQUE_FUNCTION<%0...%1> %02pf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11628)
		#define UNIQUE_FUNCTION<%0...%1> %02pg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11629)
		#define UNIQUE_FUNCTION<%0...%1> %02ph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11630)
		#define UNIQUE_FUNCTION<%0...%1> %02pi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11631)
		#define UNIQUE_FUNCTION<%0...%1> %02pj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (11639)
	#elseif UNIQUE_SYMBOL == (11631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11632)
		#define UNIQUE_FUNCTION<%0...%1> %02pk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11633)
		#define UNIQUE_FUNCTION<%0...%1> %02pl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11634)
		#define UNIQUE_FUNCTION<%0...%1> %02pm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11635)
		#define UNIQUE_FUNCTION<%0...%1> %02pn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11636)
		#define UNIQUE_FUNCTION<%0...%1> %02po%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11637)
		#define UNIQUE_FUNCTION<%0...%1> %02pp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11638)
		#define UNIQUE_FUNCTION<%0...%1> %02pq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11639)
		#define UNIQUE_FUNCTION<%0...%1> %02pr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (11639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11640)
		#define UNIQUE_FUNCTION<%0...%1> %02ps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11641)
		#define UNIQUE_FUNCTION<%0...%1> %02pt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11642)
		#define UNIQUE_FUNCTION<%0...%1> %02pu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11643)
		#define UNIQUE_FUNCTION<%0...%1> %02pv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11644)
		#define UNIQUE_FUNCTION<%0...%1> %02pw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11645)
		#define UNIQUE_FUNCTION<%0...%1> %02px%1
		#endinput
	#elseif UNIQUE_SYMBOL == (11645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11646)
		#define UNIQUE_FUNCTION<%0...%1> %02py%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (11647)
		#define UNIQUE_FUNCTION<%0...%1> %02pz%1
		#endinput
	#endif
#endif
