static stock const Y_UNIQUE_068480_068543_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_068480_068543
	#undef _inc_y_unique_068480_068543
#endif

#if UNIQUE_SYMBOL < (68487)
	#if UNIQUE_SYMBOL == (68479)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68480)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi0%1
		#endinput
	#if UNIQUE_SYMBOL == (68480)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68481)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi1%1
		#endinput
	#if UNIQUE_SYMBOL == (68481)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68482)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi2%1
		#endinput
	#if UNIQUE_SYMBOL == (68482)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68483)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi3%1
		#endinput
	#if UNIQUE_SYMBOL == (68483)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68484)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi4%1
		#endinput
	#if UNIQUE_SYMBOL == (68484)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68485)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi5%1
		#endinput
	#if UNIQUE_SYMBOL == (68485)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68486)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68487)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (68495)
	#elseif UNIQUE_SYMBOL == (68487)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68488)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68488)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68489)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68489)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68490)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68490)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68491)
		#define UNIQUE_FUNCTION<%0...%1> %0FiA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68491)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68492)
		#define UNIQUE_FUNCTION<%0...%1> %0FiB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68492)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68493)
		#define UNIQUE_FUNCTION<%0...%1> %0FiC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68493)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68494)
		#define UNIQUE_FUNCTION<%0...%1> %0FiD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68495)
		#define UNIQUE_FUNCTION<%0...%1> %0FiE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (68503)
	#elseif UNIQUE_SYMBOL == (68495)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68496)
		#define UNIQUE_FUNCTION<%0...%1> %0FiF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68496)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68497)
		#define UNIQUE_FUNCTION<%0...%1> %0FiG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68497)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68498)
		#define UNIQUE_FUNCTION<%0...%1> %0FiH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68498)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68499)
		#define UNIQUE_FUNCTION<%0...%1> %0FiI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68499)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68500)
		#define UNIQUE_FUNCTION<%0...%1> %0FiJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68500)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68501)
		#define UNIQUE_FUNCTION<%0...%1> %0FiK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68501)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68502)
		#define UNIQUE_FUNCTION<%0...%1> %0FiL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68503)
		#define UNIQUE_FUNCTION<%0...%1> %0FiM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (68511)
	#elseif UNIQUE_SYMBOL == (68503)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68504)
		#define UNIQUE_FUNCTION<%0...%1> %0FiN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68504)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68505)
		#define UNIQUE_FUNCTION<%0...%1> %0FiO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68505)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68506)
		#define UNIQUE_FUNCTION<%0...%1> %0FiP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68506)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68507)
		#define UNIQUE_FUNCTION<%0...%1> %0FiQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68507)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68508)
		#define UNIQUE_FUNCTION<%0...%1> %0FiR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68508)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68509)
		#define UNIQUE_FUNCTION<%0...%1> %0FiS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68509)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68510)
		#define UNIQUE_FUNCTION<%0...%1> %0FiT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68511)
		#define UNIQUE_FUNCTION<%0...%1> %0FiU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (68519)
	#elseif UNIQUE_SYMBOL == (68511)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68512)
		#define UNIQUE_FUNCTION<%0...%1> %0FiV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68512)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68513)
		#define UNIQUE_FUNCTION<%0...%1> %0FiW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68513)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68514)
		#define UNIQUE_FUNCTION<%0...%1> %0FiX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68514)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68515)
		#define UNIQUE_FUNCTION<%0...%1> %0FiY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68515)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68516)
		#define UNIQUE_FUNCTION<%0...%1> %0FiZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68516)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68517)
		#define UNIQUE_FUNCTION<%0...%1> %0Fi_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68517)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68518)
		#define UNIQUE_FUNCTION<%0...%1> %0Fia%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68519)
		#define UNIQUE_FUNCTION<%0...%1> %0Fib%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (68527)
	#elseif UNIQUE_SYMBOL == (68519)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68520)
		#define UNIQUE_FUNCTION<%0...%1> %0Fic%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68520)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68521)
		#define UNIQUE_FUNCTION<%0...%1> %0Fid%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68521)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68522)
		#define UNIQUE_FUNCTION<%0...%1> %0Fie%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68522)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68523)
		#define UNIQUE_FUNCTION<%0...%1> %0Fif%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68523)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68524)
		#define UNIQUE_FUNCTION<%0...%1> %0Fig%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68524)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68525)
		#define UNIQUE_FUNCTION<%0...%1> %0Fih%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68525)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68526)
		#define UNIQUE_FUNCTION<%0...%1> %0Fii%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68527)
		#define UNIQUE_FUNCTION<%0...%1> %0Fij%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (68535)
	#elseif UNIQUE_SYMBOL == (68527)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68528)
		#define UNIQUE_FUNCTION<%0...%1> %0Fik%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68528)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68529)
		#define UNIQUE_FUNCTION<%0...%1> %0Fil%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68529)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68530)
		#define UNIQUE_FUNCTION<%0...%1> %0Fim%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68530)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68531)
		#define UNIQUE_FUNCTION<%0...%1> %0Fin%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68531)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68532)
		#define UNIQUE_FUNCTION<%0...%1> %0Fio%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68532)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68533)
		#define UNIQUE_FUNCTION<%0...%1> %0Fip%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68533)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68534)
		#define UNIQUE_FUNCTION<%0...%1> %0Fiq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68535)
		#define UNIQUE_FUNCTION<%0...%1> %0Fir%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (68535)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68536)
		#define UNIQUE_FUNCTION<%0...%1> %0Fis%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68536)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68537)
		#define UNIQUE_FUNCTION<%0...%1> %0Fit%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68537)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68538)
		#define UNIQUE_FUNCTION<%0...%1> %0Fiu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68538)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68539)
		#define UNIQUE_FUNCTION<%0...%1> %0Fiv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68539)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68540)
		#define UNIQUE_FUNCTION<%0...%1> %0Fiw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68540)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68541)
		#define UNIQUE_FUNCTION<%0...%1> %0Fix%1
		#endinput
	#elseif UNIQUE_SYMBOL == (68541)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68542)
		#define UNIQUE_FUNCTION<%0...%1> %0Fiy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (68543)
		#define UNIQUE_FUNCTION<%0...%1> %0Fiz%1
		#endinput
	#endif
#endif
