static stock const Y_UNIQUE_032064_032127_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_032064_032127
	#undef _inc_y_unique_032064_032127
#endif

#if UNIQUE_SYMBOL < (32071)
	#if UNIQUE_SYMBOL == (32063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32064)
		#define UNIQUE_FUNCTION<%0...%1> %07p0%1
		#endinput
	#if UNIQUE_SYMBOL == (32064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32065)
		#define UNIQUE_FUNCTION<%0...%1> %07p1%1
		#endinput
	#if UNIQUE_SYMBOL == (32065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32066)
		#define UNIQUE_FUNCTION<%0...%1> %07p2%1
		#endinput
	#if UNIQUE_SYMBOL == (32066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32067)
		#define UNIQUE_FUNCTION<%0...%1> %07p3%1
		#endinput
	#if UNIQUE_SYMBOL == (32067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32068)
		#define UNIQUE_FUNCTION<%0...%1> %07p4%1
		#endinput
	#if UNIQUE_SYMBOL == (32068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32069)
		#define UNIQUE_FUNCTION<%0...%1> %07p5%1
		#endinput
	#if UNIQUE_SYMBOL == (32069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32070)
		#define UNIQUE_FUNCTION<%0...%1> %07p6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32071)
		#define UNIQUE_FUNCTION<%0...%1> %07p7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (32079)
	#elseif UNIQUE_SYMBOL == (32071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32072)
		#define UNIQUE_FUNCTION<%0...%1> %07p8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32073)
		#define UNIQUE_FUNCTION<%0...%1> %07p9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32074)
		#define UNIQUE_FUNCTION<%0...%1> %07p@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32075)
		#define UNIQUE_FUNCTION<%0...%1> %07pA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32076)
		#define UNIQUE_FUNCTION<%0...%1> %07pB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32077)
		#define UNIQUE_FUNCTION<%0...%1> %07pC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32078)
		#define UNIQUE_FUNCTION<%0...%1> %07pD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32079)
		#define UNIQUE_FUNCTION<%0...%1> %07pE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (32087)
	#elseif UNIQUE_SYMBOL == (32079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32080)
		#define UNIQUE_FUNCTION<%0...%1> %07pF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32081)
		#define UNIQUE_FUNCTION<%0...%1> %07pG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32082)
		#define UNIQUE_FUNCTION<%0...%1> %07pH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32083)
		#define UNIQUE_FUNCTION<%0...%1> %07pI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32084)
		#define UNIQUE_FUNCTION<%0...%1> %07pJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32085)
		#define UNIQUE_FUNCTION<%0...%1> %07pK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32086)
		#define UNIQUE_FUNCTION<%0...%1> %07pL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32087)
		#define UNIQUE_FUNCTION<%0...%1> %07pM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (32095)
	#elseif UNIQUE_SYMBOL == (32087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32088)
		#define UNIQUE_FUNCTION<%0...%1> %07pN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32089)
		#define UNIQUE_FUNCTION<%0...%1> %07pO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32090)
		#define UNIQUE_FUNCTION<%0...%1> %07pP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32091)
		#define UNIQUE_FUNCTION<%0...%1> %07pQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32092)
		#define UNIQUE_FUNCTION<%0...%1> %07pR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32093)
		#define UNIQUE_FUNCTION<%0...%1> %07pS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32094)
		#define UNIQUE_FUNCTION<%0...%1> %07pT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32095)
		#define UNIQUE_FUNCTION<%0...%1> %07pU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (32103)
	#elseif UNIQUE_SYMBOL == (32095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32096)
		#define UNIQUE_FUNCTION<%0...%1> %07pV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32097)
		#define UNIQUE_FUNCTION<%0...%1> %07pW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32098)
		#define UNIQUE_FUNCTION<%0...%1> %07pX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32099)
		#define UNIQUE_FUNCTION<%0...%1> %07pY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32100)
		#define UNIQUE_FUNCTION<%0...%1> %07pZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32101)
		#define UNIQUE_FUNCTION<%0...%1> %07p_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32102)
		#define UNIQUE_FUNCTION<%0...%1> %07pa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32103)
		#define UNIQUE_FUNCTION<%0...%1> %07pb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (32111)
	#elseif UNIQUE_SYMBOL == (32103)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32104)
		#define UNIQUE_FUNCTION<%0...%1> %07pc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32104)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32105)
		#define UNIQUE_FUNCTION<%0...%1> %07pd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32105)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32106)
		#define UNIQUE_FUNCTION<%0...%1> %07pe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32106)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32107)
		#define UNIQUE_FUNCTION<%0...%1> %07pf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32107)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32108)
		#define UNIQUE_FUNCTION<%0...%1> %07pg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32108)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32109)
		#define UNIQUE_FUNCTION<%0...%1> %07ph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32109)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32110)
		#define UNIQUE_FUNCTION<%0...%1> %07pi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32111)
		#define UNIQUE_FUNCTION<%0...%1> %07pj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (32119)
	#elseif UNIQUE_SYMBOL == (32111)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32112)
		#define UNIQUE_FUNCTION<%0...%1> %07pk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32112)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32113)
		#define UNIQUE_FUNCTION<%0...%1> %07pl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32113)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32114)
		#define UNIQUE_FUNCTION<%0...%1> %07pm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32114)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32115)
		#define UNIQUE_FUNCTION<%0...%1> %07pn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32115)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32116)
		#define UNIQUE_FUNCTION<%0...%1> %07po%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32116)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32117)
		#define UNIQUE_FUNCTION<%0...%1> %07pp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32117)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32118)
		#define UNIQUE_FUNCTION<%0...%1> %07pq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32119)
		#define UNIQUE_FUNCTION<%0...%1> %07pr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (32119)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32120)
		#define UNIQUE_FUNCTION<%0...%1> %07ps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32120)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32121)
		#define UNIQUE_FUNCTION<%0...%1> %07pt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32121)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32122)
		#define UNIQUE_FUNCTION<%0...%1> %07pu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32122)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32123)
		#define UNIQUE_FUNCTION<%0...%1> %07pv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32123)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32124)
		#define UNIQUE_FUNCTION<%0...%1> %07pw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32124)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32125)
		#define UNIQUE_FUNCTION<%0...%1> %07px%1
		#endinput
	#elseif UNIQUE_SYMBOL == (32125)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32126)
		#define UNIQUE_FUNCTION<%0...%1> %07py%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (32127)
		#define UNIQUE_FUNCTION<%0...%1> %07pz%1
		#endinput
	#endif
#endif
