static stock const Y_UNIQUE_236736_236799_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_236736_236799
	#undef _inc_y_unique_236736_236799
#endif

#if UNIQUE_SYMBOL < (236743)
	#if UNIQUE_SYMBOL == (236735)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236736)
		#define UNIQUE_FUNCTION<%0...%1> %0tn0%1
		#endinput
	#if UNIQUE_SYMBOL == (236736)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236737)
		#define UNIQUE_FUNCTION<%0...%1> %0tn1%1
		#endinput
	#if UNIQUE_SYMBOL == (236737)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236738)
		#define UNIQUE_FUNCTION<%0...%1> %0tn2%1
		#endinput
	#if UNIQUE_SYMBOL == (236738)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236739)
		#define UNIQUE_FUNCTION<%0...%1> %0tn3%1
		#endinput
	#if UNIQUE_SYMBOL == (236739)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236740)
		#define UNIQUE_FUNCTION<%0...%1> %0tn4%1
		#endinput
	#if UNIQUE_SYMBOL == (236740)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236741)
		#define UNIQUE_FUNCTION<%0...%1> %0tn5%1
		#endinput
	#if UNIQUE_SYMBOL == (236741)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236742)
		#define UNIQUE_FUNCTION<%0...%1> %0tn6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236743)
		#define UNIQUE_FUNCTION<%0...%1> %0tn7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236751)
	#elseif UNIQUE_SYMBOL == (236743)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236744)
		#define UNIQUE_FUNCTION<%0...%1> %0tn8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236744)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236745)
		#define UNIQUE_FUNCTION<%0...%1> %0tn9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236745)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236746)
		#define UNIQUE_FUNCTION<%0...%1> %0tn@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236746)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236747)
		#define UNIQUE_FUNCTION<%0...%1> %0tnA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236747)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236748)
		#define UNIQUE_FUNCTION<%0...%1> %0tnB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236748)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236749)
		#define UNIQUE_FUNCTION<%0...%1> %0tnC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236749)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236750)
		#define UNIQUE_FUNCTION<%0...%1> %0tnD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236751)
		#define UNIQUE_FUNCTION<%0...%1> %0tnE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236759)
	#elseif UNIQUE_SYMBOL == (236751)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236752)
		#define UNIQUE_FUNCTION<%0...%1> %0tnF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236752)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236753)
		#define UNIQUE_FUNCTION<%0...%1> %0tnG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236753)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236754)
		#define UNIQUE_FUNCTION<%0...%1> %0tnH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236754)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236755)
		#define UNIQUE_FUNCTION<%0...%1> %0tnI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236755)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236756)
		#define UNIQUE_FUNCTION<%0...%1> %0tnJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236756)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236757)
		#define UNIQUE_FUNCTION<%0...%1> %0tnK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236757)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236758)
		#define UNIQUE_FUNCTION<%0...%1> %0tnL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236759)
		#define UNIQUE_FUNCTION<%0...%1> %0tnM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236767)
	#elseif UNIQUE_SYMBOL == (236759)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236760)
		#define UNIQUE_FUNCTION<%0...%1> %0tnN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236760)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236761)
		#define UNIQUE_FUNCTION<%0...%1> %0tnO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236761)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236762)
		#define UNIQUE_FUNCTION<%0...%1> %0tnP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236762)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236763)
		#define UNIQUE_FUNCTION<%0...%1> %0tnQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236763)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236764)
		#define UNIQUE_FUNCTION<%0...%1> %0tnR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236764)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236765)
		#define UNIQUE_FUNCTION<%0...%1> %0tnS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236765)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236766)
		#define UNIQUE_FUNCTION<%0...%1> %0tnT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236767)
		#define UNIQUE_FUNCTION<%0...%1> %0tnU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236775)
	#elseif UNIQUE_SYMBOL == (236767)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236768)
		#define UNIQUE_FUNCTION<%0...%1> %0tnV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236768)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236769)
		#define UNIQUE_FUNCTION<%0...%1> %0tnW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236769)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236770)
		#define UNIQUE_FUNCTION<%0...%1> %0tnX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236770)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236771)
		#define UNIQUE_FUNCTION<%0...%1> %0tnY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236771)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236772)
		#define UNIQUE_FUNCTION<%0...%1> %0tnZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236772)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236773)
		#define UNIQUE_FUNCTION<%0...%1> %0tn_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236773)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236774)
		#define UNIQUE_FUNCTION<%0...%1> %0tna%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236775)
		#define UNIQUE_FUNCTION<%0...%1> %0tnb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236783)
	#elseif UNIQUE_SYMBOL == (236775)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236776)
		#define UNIQUE_FUNCTION<%0...%1> %0tnc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236776)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236777)
		#define UNIQUE_FUNCTION<%0...%1> %0tnd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236777)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236778)
		#define UNIQUE_FUNCTION<%0...%1> %0tne%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236778)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236779)
		#define UNIQUE_FUNCTION<%0...%1> %0tnf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236779)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236780)
		#define UNIQUE_FUNCTION<%0...%1> %0tng%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236780)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236781)
		#define UNIQUE_FUNCTION<%0...%1> %0tnh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236781)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236782)
		#define UNIQUE_FUNCTION<%0...%1> %0tni%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236783)
		#define UNIQUE_FUNCTION<%0...%1> %0tnj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (236791)
	#elseif UNIQUE_SYMBOL == (236783)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236784)
		#define UNIQUE_FUNCTION<%0...%1> %0tnk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236784)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236785)
		#define UNIQUE_FUNCTION<%0...%1> %0tnl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236785)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236786)
		#define UNIQUE_FUNCTION<%0...%1> %0tnm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236786)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236787)
		#define UNIQUE_FUNCTION<%0...%1> %0tnn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236787)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236788)
		#define UNIQUE_FUNCTION<%0...%1> %0tno%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236788)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236789)
		#define UNIQUE_FUNCTION<%0...%1> %0tnp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236789)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236790)
		#define UNIQUE_FUNCTION<%0...%1> %0tnq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236791)
		#define UNIQUE_FUNCTION<%0...%1> %0tnr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (236791)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236792)
		#define UNIQUE_FUNCTION<%0...%1> %0tns%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236792)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236793)
		#define UNIQUE_FUNCTION<%0...%1> %0tnt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236793)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236794)
		#define UNIQUE_FUNCTION<%0...%1> %0tnu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236794)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236795)
		#define UNIQUE_FUNCTION<%0...%1> %0tnv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236795)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236796)
		#define UNIQUE_FUNCTION<%0...%1> %0tnw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236796)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236797)
		#define UNIQUE_FUNCTION<%0...%1> %0tnx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (236797)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236798)
		#define UNIQUE_FUNCTION<%0...%1> %0tny%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (236799)
		#define UNIQUE_FUNCTION<%0...%1> %0tnz%1
		#endinput
	#endif
#endif
