static stock const Y_UNIQUE_141376_141439_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_141376_141439
	#undef _inc_y_unique_141376_141439
#endif

#if UNIQUE_SYMBOL < (141383)
	#if UNIQUE_SYMBOL == (141375)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141376)
		#define UNIQUE_FUNCTION<%0...%1> %0XW0%1
		#endinput
	#if UNIQUE_SYMBOL == (141376)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141377)
		#define UNIQUE_FUNCTION<%0...%1> %0XW1%1
		#endinput
	#if UNIQUE_SYMBOL == (141377)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141378)
		#define UNIQUE_FUNCTION<%0...%1> %0XW2%1
		#endinput
	#if UNIQUE_SYMBOL == (141378)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141379)
		#define UNIQUE_FUNCTION<%0...%1> %0XW3%1
		#endinput
	#if UNIQUE_SYMBOL == (141379)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141380)
		#define UNIQUE_FUNCTION<%0...%1> %0XW4%1
		#endinput
	#if UNIQUE_SYMBOL == (141380)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141381)
		#define UNIQUE_FUNCTION<%0...%1> %0XW5%1
		#endinput
	#if UNIQUE_SYMBOL == (141381)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141382)
		#define UNIQUE_FUNCTION<%0...%1> %0XW6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141383)
		#define UNIQUE_FUNCTION<%0...%1> %0XW7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141391)
	#elseif UNIQUE_SYMBOL == (141383)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141384)
		#define UNIQUE_FUNCTION<%0...%1> %0XW8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141384)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141385)
		#define UNIQUE_FUNCTION<%0...%1> %0XW9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141385)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141386)
		#define UNIQUE_FUNCTION<%0...%1> %0XW@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141386)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141387)
		#define UNIQUE_FUNCTION<%0...%1> %0XWA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141387)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141388)
		#define UNIQUE_FUNCTION<%0...%1> %0XWB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141388)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141389)
		#define UNIQUE_FUNCTION<%0...%1> %0XWC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141389)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141390)
		#define UNIQUE_FUNCTION<%0...%1> %0XWD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141391)
		#define UNIQUE_FUNCTION<%0...%1> %0XWE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141399)
	#elseif UNIQUE_SYMBOL == (141391)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141392)
		#define UNIQUE_FUNCTION<%0...%1> %0XWF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141392)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141393)
		#define UNIQUE_FUNCTION<%0...%1> %0XWG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141393)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141394)
		#define UNIQUE_FUNCTION<%0...%1> %0XWH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141394)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141395)
		#define UNIQUE_FUNCTION<%0...%1> %0XWI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141395)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141396)
		#define UNIQUE_FUNCTION<%0...%1> %0XWJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141396)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141397)
		#define UNIQUE_FUNCTION<%0...%1> %0XWK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141397)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141398)
		#define UNIQUE_FUNCTION<%0...%1> %0XWL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141399)
		#define UNIQUE_FUNCTION<%0...%1> %0XWM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141407)
	#elseif UNIQUE_SYMBOL == (141399)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141400)
		#define UNIQUE_FUNCTION<%0...%1> %0XWN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141400)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141401)
		#define UNIQUE_FUNCTION<%0...%1> %0XWO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141401)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141402)
		#define UNIQUE_FUNCTION<%0...%1> %0XWP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141402)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141403)
		#define UNIQUE_FUNCTION<%0...%1> %0XWQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141403)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141404)
		#define UNIQUE_FUNCTION<%0...%1> %0XWR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141404)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141405)
		#define UNIQUE_FUNCTION<%0...%1> %0XWS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141405)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141406)
		#define UNIQUE_FUNCTION<%0...%1> %0XWT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141407)
		#define UNIQUE_FUNCTION<%0...%1> %0XWU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141415)
	#elseif UNIQUE_SYMBOL == (141407)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141408)
		#define UNIQUE_FUNCTION<%0...%1> %0XWV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141408)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141409)
		#define UNIQUE_FUNCTION<%0...%1> %0XWW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141409)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141410)
		#define UNIQUE_FUNCTION<%0...%1> %0XWX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141410)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141411)
		#define UNIQUE_FUNCTION<%0...%1> %0XWY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141411)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141412)
		#define UNIQUE_FUNCTION<%0...%1> %0XWZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141412)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141413)
		#define UNIQUE_FUNCTION<%0...%1> %0XW_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141413)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141414)
		#define UNIQUE_FUNCTION<%0...%1> %0XWa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141415)
		#define UNIQUE_FUNCTION<%0...%1> %0XWb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141423)
	#elseif UNIQUE_SYMBOL == (141415)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141416)
		#define UNIQUE_FUNCTION<%0...%1> %0XWc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141416)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141417)
		#define UNIQUE_FUNCTION<%0...%1> %0XWd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141417)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141418)
		#define UNIQUE_FUNCTION<%0...%1> %0XWe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141418)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141419)
		#define UNIQUE_FUNCTION<%0...%1> %0XWf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141419)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141420)
		#define UNIQUE_FUNCTION<%0...%1> %0XWg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141420)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141421)
		#define UNIQUE_FUNCTION<%0...%1> %0XWh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141421)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141422)
		#define UNIQUE_FUNCTION<%0...%1> %0XWi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141423)
		#define UNIQUE_FUNCTION<%0...%1> %0XWj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (141431)
	#elseif UNIQUE_SYMBOL == (141423)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141424)
		#define UNIQUE_FUNCTION<%0...%1> %0XWk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141424)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141425)
		#define UNIQUE_FUNCTION<%0...%1> %0XWl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141425)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141426)
		#define UNIQUE_FUNCTION<%0...%1> %0XWm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141426)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141427)
		#define UNIQUE_FUNCTION<%0...%1> %0XWn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141427)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141428)
		#define UNIQUE_FUNCTION<%0...%1> %0XWo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141428)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141429)
		#define UNIQUE_FUNCTION<%0...%1> %0XWp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141429)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141430)
		#define UNIQUE_FUNCTION<%0...%1> %0XWq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141431)
		#define UNIQUE_FUNCTION<%0...%1> %0XWr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (141431)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141432)
		#define UNIQUE_FUNCTION<%0...%1> %0XWs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141432)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141433)
		#define UNIQUE_FUNCTION<%0...%1> %0XWt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141433)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141434)
		#define UNIQUE_FUNCTION<%0...%1> %0XWu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141434)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141435)
		#define UNIQUE_FUNCTION<%0...%1> %0XWv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141435)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141436)
		#define UNIQUE_FUNCTION<%0...%1> %0XWw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141436)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141437)
		#define UNIQUE_FUNCTION<%0...%1> %0XWx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (141437)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141438)
		#define UNIQUE_FUNCTION<%0...%1> %0XWy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (141439)
		#define UNIQUE_FUNCTION<%0...%1> %0XWz%1
		#endinput
	#endif
#endif
