static stock const Y_UNIQUE_015040_015103_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_015040_015103
	#undef _inc_y_unique_015040_015103
#endif

#if UNIQUE_SYMBOL < (15047)
	#if UNIQUE_SYMBOL == (15039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15040)
		#define UNIQUE_FUNCTION<%0...%1> %03f0%1
		#endinput
	#if UNIQUE_SYMBOL == (15040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15041)
		#define UNIQUE_FUNCTION<%0...%1> %03f1%1
		#endinput
	#if UNIQUE_SYMBOL == (15041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15042)
		#define UNIQUE_FUNCTION<%0...%1> %03f2%1
		#endinput
	#if UNIQUE_SYMBOL == (15042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15043)
		#define UNIQUE_FUNCTION<%0...%1> %03f3%1
		#endinput
	#if UNIQUE_SYMBOL == (15043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15044)
		#define UNIQUE_FUNCTION<%0...%1> %03f4%1
		#endinput
	#if UNIQUE_SYMBOL == (15044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15045)
		#define UNIQUE_FUNCTION<%0...%1> %03f5%1
		#endinput
	#if UNIQUE_SYMBOL == (15045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15046)
		#define UNIQUE_FUNCTION<%0...%1> %03f6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15047)
		#define UNIQUE_FUNCTION<%0...%1> %03f7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15055)
	#elseif UNIQUE_SYMBOL == (15047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15048)
		#define UNIQUE_FUNCTION<%0...%1> %03f8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15049)
		#define UNIQUE_FUNCTION<%0...%1> %03f9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15050)
		#define UNIQUE_FUNCTION<%0...%1> %03f@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15051)
		#define UNIQUE_FUNCTION<%0...%1> %03fA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15052)
		#define UNIQUE_FUNCTION<%0...%1> %03fB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15053)
		#define UNIQUE_FUNCTION<%0...%1> %03fC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15054)
		#define UNIQUE_FUNCTION<%0...%1> %03fD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15055)
		#define UNIQUE_FUNCTION<%0...%1> %03fE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15063)
	#elseif UNIQUE_SYMBOL == (15055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15056)
		#define UNIQUE_FUNCTION<%0...%1> %03fF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15057)
		#define UNIQUE_FUNCTION<%0...%1> %03fG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15058)
		#define UNIQUE_FUNCTION<%0...%1> %03fH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15059)
		#define UNIQUE_FUNCTION<%0...%1> %03fI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15060)
		#define UNIQUE_FUNCTION<%0...%1> %03fJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15061)
		#define UNIQUE_FUNCTION<%0...%1> %03fK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15062)
		#define UNIQUE_FUNCTION<%0...%1> %03fL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15063)
		#define UNIQUE_FUNCTION<%0...%1> %03fM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15071)
	#elseif UNIQUE_SYMBOL == (15063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15064)
		#define UNIQUE_FUNCTION<%0...%1> %03fN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15065)
		#define UNIQUE_FUNCTION<%0...%1> %03fO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15066)
		#define UNIQUE_FUNCTION<%0...%1> %03fP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15067)
		#define UNIQUE_FUNCTION<%0...%1> %03fQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15068)
		#define UNIQUE_FUNCTION<%0...%1> %03fR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15069)
		#define UNIQUE_FUNCTION<%0...%1> %03fS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15070)
		#define UNIQUE_FUNCTION<%0...%1> %03fT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15071)
		#define UNIQUE_FUNCTION<%0...%1> %03fU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15079)
	#elseif UNIQUE_SYMBOL == (15071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15072)
		#define UNIQUE_FUNCTION<%0...%1> %03fV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15073)
		#define UNIQUE_FUNCTION<%0...%1> %03fW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15074)
		#define UNIQUE_FUNCTION<%0...%1> %03fX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15075)
		#define UNIQUE_FUNCTION<%0...%1> %03fY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15076)
		#define UNIQUE_FUNCTION<%0...%1> %03fZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15077)
		#define UNIQUE_FUNCTION<%0...%1> %03f_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15078)
		#define UNIQUE_FUNCTION<%0...%1> %03fa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15079)
		#define UNIQUE_FUNCTION<%0...%1> %03fb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15087)
	#elseif UNIQUE_SYMBOL == (15079)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15080)
		#define UNIQUE_FUNCTION<%0...%1> %03fc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15080)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15081)
		#define UNIQUE_FUNCTION<%0...%1> %03fd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15081)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15082)
		#define UNIQUE_FUNCTION<%0...%1> %03fe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15082)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15083)
		#define UNIQUE_FUNCTION<%0...%1> %03ff%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15083)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15084)
		#define UNIQUE_FUNCTION<%0...%1> %03fg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15084)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15085)
		#define UNIQUE_FUNCTION<%0...%1> %03fh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15085)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15086)
		#define UNIQUE_FUNCTION<%0...%1> %03fi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15087)
		#define UNIQUE_FUNCTION<%0...%1> %03fj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (15095)
	#elseif UNIQUE_SYMBOL == (15087)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15088)
		#define UNIQUE_FUNCTION<%0...%1> %03fk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15088)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15089)
		#define UNIQUE_FUNCTION<%0...%1> %03fl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15089)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15090)
		#define UNIQUE_FUNCTION<%0...%1> %03fm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15090)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15091)
		#define UNIQUE_FUNCTION<%0...%1> %03fn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15091)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15092)
		#define UNIQUE_FUNCTION<%0...%1> %03fo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15092)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15093)
		#define UNIQUE_FUNCTION<%0...%1> %03fp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15093)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15094)
		#define UNIQUE_FUNCTION<%0...%1> %03fq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15095)
		#define UNIQUE_FUNCTION<%0...%1> %03fr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (15095)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15096)
		#define UNIQUE_FUNCTION<%0...%1> %03fs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15096)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15097)
		#define UNIQUE_FUNCTION<%0...%1> %03ft%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15097)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15098)
		#define UNIQUE_FUNCTION<%0...%1> %03fu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15098)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15099)
		#define UNIQUE_FUNCTION<%0...%1> %03fv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15099)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15100)
		#define UNIQUE_FUNCTION<%0...%1> %03fw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15100)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15101)
		#define UNIQUE_FUNCTION<%0...%1> %03fx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (15101)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15102)
		#define UNIQUE_FUNCTION<%0...%1> %03fy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (15103)
		#define UNIQUE_FUNCTION<%0...%1> %03fz%1
		#endinput
	#endif
#endif
