static stock const Y_UNIQUE_047936_047999_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_047936_047999
	#undef _inc_y_unique_047936_047999
#endif

#if UNIQUE_SYMBOL < (47943)
	#if UNIQUE_SYMBOL == (47935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47936)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah0%1
		#endinput
	#if UNIQUE_SYMBOL == (47936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47937)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah1%1
		#endinput
	#if UNIQUE_SYMBOL == (47937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47938)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah2%1
		#endinput
	#if UNIQUE_SYMBOL == (47938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47939)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah3%1
		#endinput
	#if UNIQUE_SYMBOL == (47939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47940)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah4%1
		#endinput
	#if UNIQUE_SYMBOL == (47940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47941)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah5%1
		#endinput
	#if UNIQUE_SYMBOL == (47941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47942)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47943)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47951)
	#elseif UNIQUE_SYMBOL == (47943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47944)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47945)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47946)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47947)
		#define UNIQUE_FUNCTION<%0...%1> %0AhA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47948)
		#define UNIQUE_FUNCTION<%0...%1> %0AhB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47949)
		#define UNIQUE_FUNCTION<%0...%1> %0AhC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47950)
		#define UNIQUE_FUNCTION<%0...%1> %0AhD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47951)
		#define UNIQUE_FUNCTION<%0...%1> %0AhE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47959)
	#elseif UNIQUE_SYMBOL == (47951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47952)
		#define UNIQUE_FUNCTION<%0...%1> %0AhF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47953)
		#define UNIQUE_FUNCTION<%0...%1> %0AhG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47954)
		#define UNIQUE_FUNCTION<%0...%1> %0AhH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47955)
		#define UNIQUE_FUNCTION<%0...%1> %0AhI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47956)
		#define UNIQUE_FUNCTION<%0...%1> %0AhJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47957)
		#define UNIQUE_FUNCTION<%0...%1> %0AhK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47958)
		#define UNIQUE_FUNCTION<%0...%1> %0AhL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47959)
		#define UNIQUE_FUNCTION<%0...%1> %0AhM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47967)
	#elseif UNIQUE_SYMBOL == (47959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47960)
		#define UNIQUE_FUNCTION<%0...%1> %0AhN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47961)
		#define UNIQUE_FUNCTION<%0...%1> %0AhO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47962)
		#define UNIQUE_FUNCTION<%0...%1> %0AhP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47963)
		#define UNIQUE_FUNCTION<%0...%1> %0AhQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47964)
		#define UNIQUE_FUNCTION<%0...%1> %0AhR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47965)
		#define UNIQUE_FUNCTION<%0...%1> %0AhS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47966)
		#define UNIQUE_FUNCTION<%0...%1> %0AhT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47967)
		#define UNIQUE_FUNCTION<%0...%1> %0AhU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47975)
	#elseif UNIQUE_SYMBOL == (47967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47968)
		#define UNIQUE_FUNCTION<%0...%1> %0AhV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47969)
		#define UNIQUE_FUNCTION<%0...%1> %0AhW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47970)
		#define UNIQUE_FUNCTION<%0...%1> %0AhX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47971)
		#define UNIQUE_FUNCTION<%0...%1> %0AhY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47972)
		#define UNIQUE_FUNCTION<%0...%1> %0AhZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47973)
		#define UNIQUE_FUNCTION<%0...%1> %0Ah_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47974)
		#define UNIQUE_FUNCTION<%0...%1> %0Aha%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47975)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47983)
	#elseif UNIQUE_SYMBOL == (47975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47976)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47977)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47978)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47979)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47980)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47981)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47982)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47983)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (47991)
	#elseif UNIQUE_SYMBOL == (47983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47984)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47985)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47986)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47987)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47988)
		#define UNIQUE_FUNCTION<%0...%1> %0Aho%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47989)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47990)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47991)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (47991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47992)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47993)
		#define UNIQUE_FUNCTION<%0...%1> %0Aht%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47994)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47995)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47996)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47997)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (47997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47998)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (47999)
		#define UNIQUE_FUNCTION<%0...%1> %0Ahz%1
		#endinput
	#endif
#endif
