static stock const Y_UNIQUE_065600_065663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_065600_065663
	#undef _inc_y_unique_065600_065663
#endif

#if UNIQUE_SYMBOL < (65607)
	#if UNIQUE_SYMBOL == (65599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65600)
		#define UNIQUE_FUNCTION<%0...%1> %0F10%1
		#endinput
	#if UNIQUE_SYMBOL == (65600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65601)
		#define UNIQUE_FUNCTION<%0...%1> %0F11%1
		#endinput
	#if UNIQUE_SYMBOL == (65601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65602)
		#define UNIQUE_FUNCTION<%0...%1> %0F12%1
		#endinput
	#if UNIQUE_SYMBOL == (65602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65603)
		#define UNIQUE_FUNCTION<%0...%1> %0F13%1
		#endinput
	#if UNIQUE_SYMBOL == (65603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65604)
		#define UNIQUE_FUNCTION<%0...%1> %0F14%1
		#endinput
	#if UNIQUE_SYMBOL == (65604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65605)
		#define UNIQUE_FUNCTION<%0...%1> %0F15%1
		#endinput
	#if UNIQUE_SYMBOL == (65605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65606)
		#define UNIQUE_FUNCTION<%0...%1> %0F16%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65607)
		#define UNIQUE_FUNCTION<%0...%1> %0F17%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (65615)
	#elseif UNIQUE_SYMBOL == (65607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65608)
		#define UNIQUE_FUNCTION<%0...%1> %0F18%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65609)
		#define UNIQUE_FUNCTION<%0...%1> %0F19%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65610)
		#define UNIQUE_FUNCTION<%0...%1> %0F1@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65611)
		#define UNIQUE_FUNCTION<%0...%1> %0F1A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65612)
		#define UNIQUE_FUNCTION<%0...%1> %0F1B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65613)
		#define UNIQUE_FUNCTION<%0...%1> %0F1C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65614)
		#define UNIQUE_FUNCTION<%0...%1> %0F1D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65615)
		#define UNIQUE_FUNCTION<%0...%1> %0F1E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (65623)
	#elseif UNIQUE_SYMBOL == (65615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65616)
		#define UNIQUE_FUNCTION<%0...%1> %0F1F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65617)
		#define UNIQUE_FUNCTION<%0...%1> %0F1G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65618)
		#define UNIQUE_FUNCTION<%0...%1> %0F1H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65619)
		#define UNIQUE_FUNCTION<%0...%1> %0F1I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65620)
		#define UNIQUE_FUNCTION<%0...%1> %0F1J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65621)
		#define UNIQUE_FUNCTION<%0...%1> %0F1K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65622)
		#define UNIQUE_FUNCTION<%0...%1> %0F1L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65623)
		#define UNIQUE_FUNCTION<%0...%1> %0F1M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (65631)
	#elseif UNIQUE_SYMBOL == (65623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65624)
		#define UNIQUE_FUNCTION<%0...%1> %0F1N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65625)
		#define UNIQUE_FUNCTION<%0...%1> %0F1O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65626)
		#define UNIQUE_FUNCTION<%0...%1> %0F1P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65627)
		#define UNIQUE_FUNCTION<%0...%1> %0F1Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65628)
		#define UNIQUE_FUNCTION<%0...%1> %0F1R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65629)
		#define UNIQUE_FUNCTION<%0...%1> %0F1S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65630)
		#define UNIQUE_FUNCTION<%0...%1> %0F1T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65631)
		#define UNIQUE_FUNCTION<%0...%1> %0F1U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (65639)
	#elseif UNIQUE_SYMBOL == (65631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65632)
		#define UNIQUE_FUNCTION<%0...%1> %0F1V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65633)
		#define UNIQUE_FUNCTION<%0...%1> %0F1W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65634)
		#define UNIQUE_FUNCTION<%0...%1> %0F1X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65635)
		#define UNIQUE_FUNCTION<%0...%1> %0F1Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65636)
		#define UNIQUE_FUNCTION<%0...%1> %0F1Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65637)
		#define UNIQUE_FUNCTION<%0...%1> %0F1_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65638)
		#define UNIQUE_FUNCTION<%0...%1> %0F1a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65639)
		#define UNIQUE_FUNCTION<%0...%1> %0F1b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (65647)
	#elseif UNIQUE_SYMBOL == (65639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65640)
		#define UNIQUE_FUNCTION<%0...%1> %0F1c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65641)
		#define UNIQUE_FUNCTION<%0...%1> %0F1d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65642)
		#define UNIQUE_FUNCTION<%0...%1> %0F1e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65643)
		#define UNIQUE_FUNCTION<%0...%1> %0F1f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65644)
		#define UNIQUE_FUNCTION<%0...%1> %0F1g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65645)
		#define UNIQUE_FUNCTION<%0...%1> %0F1h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65646)
		#define UNIQUE_FUNCTION<%0...%1> %0F1i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65647)
		#define UNIQUE_FUNCTION<%0...%1> %0F1j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (65655)
	#elseif UNIQUE_SYMBOL == (65647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65648)
		#define UNIQUE_FUNCTION<%0...%1> %0F1k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65649)
		#define UNIQUE_FUNCTION<%0...%1> %0F1l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65650)
		#define UNIQUE_FUNCTION<%0...%1> %0F1m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65651)
		#define UNIQUE_FUNCTION<%0...%1> %0F1n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65652)
		#define UNIQUE_FUNCTION<%0...%1> %0F1o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65653)
		#define UNIQUE_FUNCTION<%0...%1> %0F1p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65654)
		#define UNIQUE_FUNCTION<%0...%1> %0F1q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65655)
		#define UNIQUE_FUNCTION<%0...%1> %0F1r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (65655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65656)
		#define UNIQUE_FUNCTION<%0...%1> %0F1s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65657)
		#define UNIQUE_FUNCTION<%0...%1> %0F1t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65658)
		#define UNIQUE_FUNCTION<%0...%1> %0F1u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65659)
		#define UNIQUE_FUNCTION<%0...%1> %0F1v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65660)
		#define UNIQUE_FUNCTION<%0...%1> %0F1w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65661)
		#define UNIQUE_FUNCTION<%0...%1> %0F1x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (65661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65662)
		#define UNIQUE_FUNCTION<%0...%1> %0F1y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (65663)
		#define UNIQUE_FUNCTION<%0...%1> %0F1z%1
		#endinput
	#endif
#endif
