static stock const Y_UNIQUE_031616_031679_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_031616_031679
	#undef _inc_y_unique_031616_031679
#endif

#if UNIQUE_SYMBOL < (31623)
	#if UNIQUE_SYMBOL == (31615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31616)
		#define UNIQUE_FUNCTION<%0...%1> %07i0%1
		#endinput
	#if UNIQUE_SYMBOL == (31616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31617)
		#define UNIQUE_FUNCTION<%0...%1> %07i1%1
		#endinput
	#if UNIQUE_SYMBOL == (31617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31618)
		#define UNIQUE_FUNCTION<%0...%1> %07i2%1
		#endinput
	#if UNIQUE_SYMBOL == (31618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31619)
		#define UNIQUE_FUNCTION<%0...%1> %07i3%1
		#endinput
	#if UNIQUE_SYMBOL == (31619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31620)
		#define UNIQUE_FUNCTION<%0...%1> %07i4%1
		#endinput
	#if UNIQUE_SYMBOL == (31620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31621)
		#define UNIQUE_FUNCTION<%0...%1> %07i5%1
		#endinput
	#if UNIQUE_SYMBOL == (31621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31622)
		#define UNIQUE_FUNCTION<%0...%1> %07i6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31623)
		#define UNIQUE_FUNCTION<%0...%1> %07i7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31631)
	#elseif UNIQUE_SYMBOL == (31623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31624)
		#define UNIQUE_FUNCTION<%0...%1> %07i8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31625)
		#define UNIQUE_FUNCTION<%0...%1> %07i9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31626)
		#define UNIQUE_FUNCTION<%0...%1> %07i@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31627)
		#define UNIQUE_FUNCTION<%0...%1> %07iA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31628)
		#define UNIQUE_FUNCTION<%0...%1> %07iB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31629)
		#define UNIQUE_FUNCTION<%0...%1> %07iC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31630)
		#define UNIQUE_FUNCTION<%0...%1> %07iD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31631)
		#define UNIQUE_FUNCTION<%0...%1> %07iE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31639)
	#elseif UNIQUE_SYMBOL == (31631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31632)
		#define UNIQUE_FUNCTION<%0...%1> %07iF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31633)
		#define UNIQUE_FUNCTION<%0...%1> %07iG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31634)
		#define UNIQUE_FUNCTION<%0...%1> %07iH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31635)
		#define UNIQUE_FUNCTION<%0...%1> %07iI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31636)
		#define UNIQUE_FUNCTION<%0...%1> %07iJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31637)
		#define UNIQUE_FUNCTION<%0...%1> %07iK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31638)
		#define UNIQUE_FUNCTION<%0...%1> %07iL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31639)
		#define UNIQUE_FUNCTION<%0...%1> %07iM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31647)
	#elseif UNIQUE_SYMBOL == (31639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31640)
		#define UNIQUE_FUNCTION<%0...%1> %07iN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31641)
		#define UNIQUE_FUNCTION<%0...%1> %07iO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31642)
		#define UNIQUE_FUNCTION<%0...%1> %07iP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31643)
		#define UNIQUE_FUNCTION<%0...%1> %07iQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31644)
		#define UNIQUE_FUNCTION<%0...%1> %07iR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31645)
		#define UNIQUE_FUNCTION<%0...%1> %07iS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31646)
		#define UNIQUE_FUNCTION<%0...%1> %07iT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31647)
		#define UNIQUE_FUNCTION<%0...%1> %07iU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31655)
	#elseif UNIQUE_SYMBOL == (31647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31648)
		#define UNIQUE_FUNCTION<%0...%1> %07iV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31649)
		#define UNIQUE_FUNCTION<%0...%1> %07iW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31650)
		#define UNIQUE_FUNCTION<%0...%1> %07iX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31651)
		#define UNIQUE_FUNCTION<%0...%1> %07iY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31652)
		#define UNIQUE_FUNCTION<%0...%1> %07iZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31653)
		#define UNIQUE_FUNCTION<%0...%1> %07i_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31654)
		#define UNIQUE_FUNCTION<%0...%1> %07ia%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31655)
		#define UNIQUE_FUNCTION<%0...%1> %07ib%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31663)
	#elseif UNIQUE_SYMBOL == (31655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31656)
		#define UNIQUE_FUNCTION<%0...%1> %07ic%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31657)
		#define UNIQUE_FUNCTION<%0...%1> %07id%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31658)
		#define UNIQUE_FUNCTION<%0...%1> %07ie%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31659)
		#define UNIQUE_FUNCTION<%0...%1> %07if%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31660)
		#define UNIQUE_FUNCTION<%0...%1> %07ig%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31661)
		#define UNIQUE_FUNCTION<%0...%1> %07ih%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31662)
		#define UNIQUE_FUNCTION<%0...%1> %07ii%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31663)
		#define UNIQUE_FUNCTION<%0...%1> %07ij%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (31671)
	#elseif UNIQUE_SYMBOL == (31663)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31664)
		#define UNIQUE_FUNCTION<%0...%1> %07ik%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31664)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31665)
		#define UNIQUE_FUNCTION<%0...%1> %07il%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31665)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31666)
		#define UNIQUE_FUNCTION<%0...%1> %07im%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31666)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31667)
		#define UNIQUE_FUNCTION<%0...%1> %07in%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31667)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31668)
		#define UNIQUE_FUNCTION<%0...%1> %07io%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31668)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31669)
		#define UNIQUE_FUNCTION<%0...%1> %07ip%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31669)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31670)
		#define UNIQUE_FUNCTION<%0...%1> %07iq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31671)
		#define UNIQUE_FUNCTION<%0...%1> %07ir%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (31671)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31672)
		#define UNIQUE_FUNCTION<%0...%1> %07is%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31672)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31673)
		#define UNIQUE_FUNCTION<%0...%1> %07it%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31673)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31674)
		#define UNIQUE_FUNCTION<%0...%1> %07iu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31674)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31675)
		#define UNIQUE_FUNCTION<%0...%1> %07iv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31675)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31676)
		#define UNIQUE_FUNCTION<%0...%1> %07iw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31676)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31677)
		#define UNIQUE_FUNCTION<%0...%1> %07ix%1
		#endinput
	#elseif UNIQUE_SYMBOL == (31677)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31678)
		#define UNIQUE_FUNCTION<%0...%1> %07iy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (31679)
		#define UNIQUE_FUNCTION<%0...%1> %07iz%1
		#endinput
	#endif
#endif
