static stock const Y_UNIQUE_129600_129663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_129600_129663
	#undef _inc_y_unique_129600_129663
#endif

#if UNIQUE_SYMBOL < (129607)
	#if UNIQUE_SYMBOL == (129599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129600)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud0%1
		#endinput
	#if UNIQUE_SYMBOL == (129600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129601)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud1%1
		#endinput
	#if UNIQUE_SYMBOL == (129601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129602)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud2%1
		#endinput
	#if UNIQUE_SYMBOL == (129602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129603)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud3%1
		#endinput
	#if UNIQUE_SYMBOL == (129603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129604)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud4%1
		#endinput
	#if UNIQUE_SYMBOL == (129604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129605)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud5%1
		#endinput
	#if UNIQUE_SYMBOL == (129605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129606)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129607)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (129615)
	#elseif UNIQUE_SYMBOL == (129607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129608)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129609)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129610)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129611)
		#define UNIQUE_FUNCTION<%0...%1> %0UdA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129612)
		#define UNIQUE_FUNCTION<%0...%1> %0UdB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129613)
		#define UNIQUE_FUNCTION<%0...%1> %0UdC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129614)
		#define UNIQUE_FUNCTION<%0...%1> %0UdD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129615)
		#define UNIQUE_FUNCTION<%0...%1> %0UdE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (129623)
	#elseif UNIQUE_SYMBOL == (129615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129616)
		#define UNIQUE_FUNCTION<%0...%1> %0UdF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129617)
		#define UNIQUE_FUNCTION<%0...%1> %0UdG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129618)
		#define UNIQUE_FUNCTION<%0...%1> %0UdH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129619)
		#define UNIQUE_FUNCTION<%0...%1> %0UdI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129620)
		#define UNIQUE_FUNCTION<%0...%1> %0UdJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129621)
		#define UNIQUE_FUNCTION<%0...%1> %0UdK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129622)
		#define UNIQUE_FUNCTION<%0...%1> %0UdL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129623)
		#define UNIQUE_FUNCTION<%0...%1> %0UdM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (129631)
	#elseif UNIQUE_SYMBOL == (129623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129624)
		#define UNIQUE_FUNCTION<%0...%1> %0UdN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129625)
		#define UNIQUE_FUNCTION<%0...%1> %0UdO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129626)
		#define UNIQUE_FUNCTION<%0...%1> %0UdP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129627)
		#define UNIQUE_FUNCTION<%0...%1> %0UdQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129628)
		#define UNIQUE_FUNCTION<%0...%1> %0UdR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129629)
		#define UNIQUE_FUNCTION<%0...%1> %0UdS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129630)
		#define UNIQUE_FUNCTION<%0...%1> %0UdT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129631)
		#define UNIQUE_FUNCTION<%0...%1> %0UdU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (129639)
	#elseif UNIQUE_SYMBOL == (129631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129632)
		#define UNIQUE_FUNCTION<%0...%1> %0UdV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129633)
		#define UNIQUE_FUNCTION<%0...%1> %0UdW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129634)
		#define UNIQUE_FUNCTION<%0...%1> %0UdX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129635)
		#define UNIQUE_FUNCTION<%0...%1> %0UdY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129636)
		#define UNIQUE_FUNCTION<%0...%1> %0UdZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129637)
		#define UNIQUE_FUNCTION<%0...%1> %0Ud_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129638)
		#define UNIQUE_FUNCTION<%0...%1> %0Uda%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129639)
		#define UNIQUE_FUNCTION<%0...%1> %0Udb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (129647)
	#elseif UNIQUE_SYMBOL == (129639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129640)
		#define UNIQUE_FUNCTION<%0...%1> %0Udc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129641)
		#define UNIQUE_FUNCTION<%0...%1> %0Udd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129642)
		#define UNIQUE_FUNCTION<%0...%1> %0Ude%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129643)
		#define UNIQUE_FUNCTION<%0...%1> %0Udf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129644)
		#define UNIQUE_FUNCTION<%0...%1> %0Udg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129645)
		#define UNIQUE_FUNCTION<%0...%1> %0Udh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129646)
		#define UNIQUE_FUNCTION<%0...%1> %0Udi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129647)
		#define UNIQUE_FUNCTION<%0...%1> %0Udj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (129655)
	#elseif UNIQUE_SYMBOL == (129647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129648)
		#define UNIQUE_FUNCTION<%0...%1> %0Udk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129649)
		#define UNIQUE_FUNCTION<%0...%1> %0Udl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129650)
		#define UNIQUE_FUNCTION<%0...%1> %0Udm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129651)
		#define UNIQUE_FUNCTION<%0...%1> %0Udn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129652)
		#define UNIQUE_FUNCTION<%0...%1> %0Udo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129653)
		#define UNIQUE_FUNCTION<%0...%1> %0Udp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129654)
		#define UNIQUE_FUNCTION<%0...%1> %0Udq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129655)
		#define UNIQUE_FUNCTION<%0...%1> %0Udr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (129655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129656)
		#define UNIQUE_FUNCTION<%0...%1> %0Uds%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129657)
		#define UNIQUE_FUNCTION<%0...%1> %0Udt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129658)
		#define UNIQUE_FUNCTION<%0...%1> %0Udu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129659)
		#define UNIQUE_FUNCTION<%0...%1> %0Udv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129660)
		#define UNIQUE_FUNCTION<%0...%1> %0Udw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129661)
		#define UNIQUE_FUNCTION<%0...%1> %0Udx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (129661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129662)
		#define UNIQUE_FUNCTION<%0...%1> %0Udy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (129663)
		#define UNIQUE_FUNCTION<%0...%1> %0Udz%1
		#endinput
	#endif
#endif
