static stock const Y_UNIQUE_136192_136255_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_136192_136255
	#undef _inc_y_unique_136192_136255
#endif

#if UNIQUE_SYMBOL < (136199)
	#if UNIQUE_SYMBOL == (136191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136192)
		#define UNIQUE_FUNCTION<%0...%1> %0WF0%1
		#endinput
	#if UNIQUE_SYMBOL == (136192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136193)
		#define UNIQUE_FUNCTION<%0...%1> %0WF1%1
		#endinput
	#if UNIQUE_SYMBOL == (136193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136194)
		#define UNIQUE_FUNCTION<%0...%1> %0WF2%1
		#endinput
	#if UNIQUE_SYMBOL == (136194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136195)
		#define UNIQUE_FUNCTION<%0...%1> %0WF3%1
		#endinput
	#if UNIQUE_SYMBOL == (136195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136196)
		#define UNIQUE_FUNCTION<%0...%1> %0WF4%1
		#endinput
	#if UNIQUE_SYMBOL == (136196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136197)
		#define UNIQUE_FUNCTION<%0...%1> %0WF5%1
		#endinput
	#if UNIQUE_SYMBOL == (136197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136198)
		#define UNIQUE_FUNCTION<%0...%1> %0WF6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136199)
		#define UNIQUE_FUNCTION<%0...%1> %0WF7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136207)
	#elseif UNIQUE_SYMBOL == (136199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136200)
		#define UNIQUE_FUNCTION<%0...%1> %0WF8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136201)
		#define UNIQUE_FUNCTION<%0...%1> %0WF9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136202)
		#define UNIQUE_FUNCTION<%0...%1> %0WF@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136203)
		#define UNIQUE_FUNCTION<%0...%1> %0WFA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136204)
		#define UNIQUE_FUNCTION<%0...%1> %0WFB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136205)
		#define UNIQUE_FUNCTION<%0...%1> %0WFC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136206)
		#define UNIQUE_FUNCTION<%0...%1> %0WFD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136207)
		#define UNIQUE_FUNCTION<%0...%1> %0WFE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136215)
	#elseif UNIQUE_SYMBOL == (136207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136208)
		#define UNIQUE_FUNCTION<%0...%1> %0WFF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136209)
		#define UNIQUE_FUNCTION<%0...%1> %0WFG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136210)
		#define UNIQUE_FUNCTION<%0...%1> %0WFH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136211)
		#define UNIQUE_FUNCTION<%0...%1> %0WFI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136212)
		#define UNIQUE_FUNCTION<%0...%1> %0WFJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136213)
		#define UNIQUE_FUNCTION<%0...%1> %0WFK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136214)
		#define UNIQUE_FUNCTION<%0...%1> %0WFL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136215)
		#define UNIQUE_FUNCTION<%0...%1> %0WFM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136223)
	#elseif UNIQUE_SYMBOL == (136215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136216)
		#define UNIQUE_FUNCTION<%0...%1> %0WFN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136217)
		#define UNIQUE_FUNCTION<%0...%1> %0WFO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136218)
		#define UNIQUE_FUNCTION<%0...%1> %0WFP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136219)
		#define UNIQUE_FUNCTION<%0...%1> %0WFQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136220)
		#define UNIQUE_FUNCTION<%0...%1> %0WFR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136221)
		#define UNIQUE_FUNCTION<%0...%1> %0WFS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136222)
		#define UNIQUE_FUNCTION<%0...%1> %0WFT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136223)
		#define UNIQUE_FUNCTION<%0...%1> %0WFU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136231)
	#elseif UNIQUE_SYMBOL == (136223)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136224)
		#define UNIQUE_FUNCTION<%0...%1> %0WFV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136224)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136225)
		#define UNIQUE_FUNCTION<%0...%1> %0WFW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136225)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136226)
		#define UNIQUE_FUNCTION<%0...%1> %0WFX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136226)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136227)
		#define UNIQUE_FUNCTION<%0...%1> %0WFY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136227)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136228)
		#define UNIQUE_FUNCTION<%0...%1> %0WFZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136228)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136229)
		#define UNIQUE_FUNCTION<%0...%1> %0WF_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136229)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136230)
		#define UNIQUE_FUNCTION<%0...%1> %0WFa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136231)
		#define UNIQUE_FUNCTION<%0...%1> %0WFb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136239)
	#elseif UNIQUE_SYMBOL == (136231)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136232)
		#define UNIQUE_FUNCTION<%0...%1> %0WFc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136232)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136233)
		#define UNIQUE_FUNCTION<%0...%1> %0WFd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136233)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136234)
		#define UNIQUE_FUNCTION<%0...%1> %0WFe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136234)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136235)
		#define UNIQUE_FUNCTION<%0...%1> %0WFf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136235)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136236)
		#define UNIQUE_FUNCTION<%0...%1> %0WFg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136236)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136237)
		#define UNIQUE_FUNCTION<%0...%1> %0WFh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136237)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136238)
		#define UNIQUE_FUNCTION<%0...%1> %0WFi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136239)
		#define UNIQUE_FUNCTION<%0...%1> %0WFj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (136247)
	#elseif UNIQUE_SYMBOL == (136239)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136240)
		#define UNIQUE_FUNCTION<%0...%1> %0WFk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136240)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136241)
		#define UNIQUE_FUNCTION<%0...%1> %0WFl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136241)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136242)
		#define UNIQUE_FUNCTION<%0...%1> %0WFm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136242)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136243)
		#define UNIQUE_FUNCTION<%0...%1> %0WFn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136243)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136244)
		#define UNIQUE_FUNCTION<%0...%1> %0WFo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136244)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136245)
		#define UNIQUE_FUNCTION<%0...%1> %0WFp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136245)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136246)
		#define UNIQUE_FUNCTION<%0...%1> %0WFq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136247)
		#define UNIQUE_FUNCTION<%0...%1> %0WFr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (136247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136248)
		#define UNIQUE_FUNCTION<%0...%1> %0WFs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136249)
		#define UNIQUE_FUNCTION<%0...%1> %0WFt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136250)
		#define UNIQUE_FUNCTION<%0...%1> %0WFu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136251)
		#define UNIQUE_FUNCTION<%0...%1> %0WFv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136252)
		#define UNIQUE_FUNCTION<%0...%1> %0WFw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136253)
		#define UNIQUE_FUNCTION<%0...%1> %0WFx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (136253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136254)
		#define UNIQUE_FUNCTION<%0...%1> %0WFy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (136255)
		#define UNIQUE_FUNCTION<%0...%1> %0WFz%1
		#endinput
	#endif
#endif
