static stock const Y_UNIQUE_025280_025343_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_025280_025343
	#undef _inc_y_unique_025280_025343
#endif

#if UNIQUE_SYMBOL < (25287)
	#if UNIQUE_SYMBOL == (25279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25280)
		#define UNIQUE_FUNCTION<%0...%1> %06A0%1
		#endinput
	#if UNIQUE_SYMBOL == (25280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25281)
		#define UNIQUE_FUNCTION<%0...%1> %06A1%1
		#endinput
	#if UNIQUE_SYMBOL == (25281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25282)
		#define UNIQUE_FUNCTION<%0...%1> %06A2%1
		#endinput
	#if UNIQUE_SYMBOL == (25282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25283)
		#define UNIQUE_FUNCTION<%0...%1> %06A3%1
		#endinput
	#if UNIQUE_SYMBOL == (25283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25284)
		#define UNIQUE_FUNCTION<%0...%1> %06A4%1
		#endinput
	#if UNIQUE_SYMBOL == (25284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25285)
		#define UNIQUE_FUNCTION<%0...%1> %06A5%1
		#endinput
	#if UNIQUE_SYMBOL == (25285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25286)
		#define UNIQUE_FUNCTION<%0...%1> %06A6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25287)
		#define UNIQUE_FUNCTION<%0...%1> %06A7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25295)
	#elseif UNIQUE_SYMBOL == (25287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25288)
		#define UNIQUE_FUNCTION<%0...%1> %06A8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25289)
		#define UNIQUE_FUNCTION<%0...%1> %06A9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25290)
		#define UNIQUE_FUNCTION<%0...%1> %06A@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25291)
		#define UNIQUE_FUNCTION<%0...%1> %06AA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25292)
		#define UNIQUE_FUNCTION<%0...%1> %06AB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25293)
		#define UNIQUE_FUNCTION<%0...%1> %06AC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25294)
		#define UNIQUE_FUNCTION<%0...%1> %06AD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25295)
		#define UNIQUE_FUNCTION<%0...%1> %06AE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25303)
	#elseif UNIQUE_SYMBOL == (25295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25296)
		#define UNIQUE_FUNCTION<%0...%1> %06AF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25297)
		#define UNIQUE_FUNCTION<%0...%1> %06AG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25298)
		#define UNIQUE_FUNCTION<%0...%1> %06AH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25299)
		#define UNIQUE_FUNCTION<%0...%1> %06AI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25300)
		#define UNIQUE_FUNCTION<%0...%1> %06AJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25301)
		#define UNIQUE_FUNCTION<%0...%1> %06AK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25302)
		#define UNIQUE_FUNCTION<%0...%1> %06AL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25303)
		#define UNIQUE_FUNCTION<%0...%1> %06AM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25311)
	#elseif UNIQUE_SYMBOL == (25303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25304)
		#define UNIQUE_FUNCTION<%0...%1> %06AN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25305)
		#define UNIQUE_FUNCTION<%0...%1> %06AO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25306)
		#define UNIQUE_FUNCTION<%0...%1> %06AP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25307)
		#define UNIQUE_FUNCTION<%0...%1> %06AQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25308)
		#define UNIQUE_FUNCTION<%0...%1> %06AR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25309)
		#define UNIQUE_FUNCTION<%0...%1> %06AS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25310)
		#define UNIQUE_FUNCTION<%0...%1> %06AT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25311)
		#define UNIQUE_FUNCTION<%0...%1> %06AU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25319)
	#elseif UNIQUE_SYMBOL == (25311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25312)
		#define UNIQUE_FUNCTION<%0...%1> %06AV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25313)
		#define UNIQUE_FUNCTION<%0...%1> %06AW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25314)
		#define UNIQUE_FUNCTION<%0...%1> %06AX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25315)
		#define UNIQUE_FUNCTION<%0...%1> %06AY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25316)
		#define UNIQUE_FUNCTION<%0...%1> %06AZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25317)
		#define UNIQUE_FUNCTION<%0...%1> %06A_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25318)
		#define UNIQUE_FUNCTION<%0...%1> %06Aa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25319)
		#define UNIQUE_FUNCTION<%0...%1> %06Ab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25327)
	#elseif UNIQUE_SYMBOL == (25319)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25320)
		#define UNIQUE_FUNCTION<%0...%1> %06Ac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25320)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25321)
		#define UNIQUE_FUNCTION<%0...%1> %06Ad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25321)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25322)
		#define UNIQUE_FUNCTION<%0...%1> %06Ae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25322)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25323)
		#define UNIQUE_FUNCTION<%0...%1> %06Af%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25323)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25324)
		#define UNIQUE_FUNCTION<%0...%1> %06Ag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25324)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25325)
		#define UNIQUE_FUNCTION<%0...%1> %06Ah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25325)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25326)
		#define UNIQUE_FUNCTION<%0...%1> %06Ai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25327)
		#define UNIQUE_FUNCTION<%0...%1> %06Aj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (25335)
	#elseif UNIQUE_SYMBOL == (25327)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25328)
		#define UNIQUE_FUNCTION<%0...%1> %06Ak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25328)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25329)
		#define UNIQUE_FUNCTION<%0...%1> %06Al%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25329)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25330)
		#define UNIQUE_FUNCTION<%0...%1> %06Am%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25330)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25331)
		#define UNIQUE_FUNCTION<%0...%1> %06An%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25331)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25332)
		#define UNIQUE_FUNCTION<%0...%1> %06Ao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25332)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25333)
		#define UNIQUE_FUNCTION<%0...%1> %06Ap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25333)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25334)
		#define UNIQUE_FUNCTION<%0...%1> %06Aq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25335)
		#define UNIQUE_FUNCTION<%0...%1> %06Ar%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (25335)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25336)
		#define UNIQUE_FUNCTION<%0...%1> %06As%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25336)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25337)
		#define UNIQUE_FUNCTION<%0...%1> %06At%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25337)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25338)
		#define UNIQUE_FUNCTION<%0...%1> %06Au%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25338)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25339)
		#define UNIQUE_FUNCTION<%0...%1> %06Av%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25339)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25340)
		#define UNIQUE_FUNCTION<%0...%1> %06Aw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25340)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25341)
		#define UNIQUE_FUNCTION<%0...%1> %06Ax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (25341)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25342)
		#define UNIQUE_FUNCTION<%0...%1> %06Ay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (25343)
		#define UNIQUE_FUNCTION<%0...%1> %06Az%1
		#endinput
	#endif
#endif
