static stock const Y_UNIQUE_145600_145663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_145600_145663
	#undef _inc_y_unique_145600_145663
#endif

#if UNIQUE_SYMBOL < (145607)
	#if UNIQUE_SYMBOL == (145599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145600)
		#define UNIQUE_FUNCTION<%0...%1> %0YY0%1
		#endinput
	#if UNIQUE_SYMBOL == (145600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145601)
		#define UNIQUE_FUNCTION<%0...%1> %0YY1%1
		#endinput
	#if UNIQUE_SYMBOL == (145601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145602)
		#define UNIQUE_FUNCTION<%0...%1> %0YY2%1
		#endinput
	#if UNIQUE_SYMBOL == (145602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145603)
		#define UNIQUE_FUNCTION<%0...%1> %0YY3%1
		#endinput
	#if UNIQUE_SYMBOL == (145603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145604)
		#define UNIQUE_FUNCTION<%0...%1> %0YY4%1
		#endinput
	#if UNIQUE_SYMBOL == (145604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145605)
		#define UNIQUE_FUNCTION<%0...%1> %0YY5%1
		#endinput
	#if UNIQUE_SYMBOL == (145605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145606)
		#define UNIQUE_FUNCTION<%0...%1> %0YY6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145607)
		#define UNIQUE_FUNCTION<%0...%1> %0YY7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145615)
	#elseif UNIQUE_SYMBOL == (145607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145608)
		#define UNIQUE_FUNCTION<%0...%1> %0YY8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145609)
		#define UNIQUE_FUNCTION<%0...%1> %0YY9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145610)
		#define UNIQUE_FUNCTION<%0...%1> %0YY@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145611)
		#define UNIQUE_FUNCTION<%0...%1> %0YYA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145612)
		#define UNIQUE_FUNCTION<%0...%1> %0YYB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145613)
		#define UNIQUE_FUNCTION<%0...%1> %0YYC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145614)
		#define UNIQUE_FUNCTION<%0...%1> %0YYD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145615)
		#define UNIQUE_FUNCTION<%0...%1> %0YYE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145623)
	#elseif UNIQUE_SYMBOL == (145615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145616)
		#define UNIQUE_FUNCTION<%0...%1> %0YYF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145617)
		#define UNIQUE_FUNCTION<%0...%1> %0YYG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145618)
		#define UNIQUE_FUNCTION<%0...%1> %0YYH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145619)
		#define UNIQUE_FUNCTION<%0...%1> %0YYI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145620)
		#define UNIQUE_FUNCTION<%0...%1> %0YYJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145621)
		#define UNIQUE_FUNCTION<%0...%1> %0YYK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145622)
		#define UNIQUE_FUNCTION<%0...%1> %0YYL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145623)
		#define UNIQUE_FUNCTION<%0...%1> %0YYM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145631)
	#elseif UNIQUE_SYMBOL == (145623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145624)
		#define UNIQUE_FUNCTION<%0...%1> %0YYN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145625)
		#define UNIQUE_FUNCTION<%0...%1> %0YYO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145626)
		#define UNIQUE_FUNCTION<%0...%1> %0YYP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145627)
		#define UNIQUE_FUNCTION<%0...%1> %0YYQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145628)
		#define UNIQUE_FUNCTION<%0...%1> %0YYR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145629)
		#define UNIQUE_FUNCTION<%0...%1> %0YYS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145630)
		#define UNIQUE_FUNCTION<%0...%1> %0YYT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145631)
		#define UNIQUE_FUNCTION<%0...%1> %0YYU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145639)
	#elseif UNIQUE_SYMBOL == (145631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145632)
		#define UNIQUE_FUNCTION<%0...%1> %0YYV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145633)
		#define UNIQUE_FUNCTION<%0...%1> %0YYW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145634)
		#define UNIQUE_FUNCTION<%0...%1> %0YYX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145635)
		#define UNIQUE_FUNCTION<%0...%1> %0YYY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145636)
		#define UNIQUE_FUNCTION<%0...%1> %0YYZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145637)
		#define UNIQUE_FUNCTION<%0...%1> %0YY_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145638)
		#define UNIQUE_FUNCTION<%0...%1> %0YYa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145639)
		#define UNIQUE_FUNCTION<%0...%1> %0YYb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145647)
	#elseif UNIQUE_SYMBOL == (145639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145640)
		#define UNIQUE_FUNCTION<%0...%1> %0YYc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145641)
		#define UNIQUE_FUNCTION<%0...%1> %0YYd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145642)
		#define UNIQUE_FUNCTION<%0...%1> %0YYe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145643)
		#define UNIQUE_FUNCTION<%0...%1> %0YYf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145644)
		#define UNIQUE_FUNCTION<%0...%1> %0YYg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145645)
		#define UNIQUE_FUNCTION<%0...%1> %0YYh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145646)
		#define UNIQUE_FUNCTION<%0...%1> %0YYi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145647)
		#define UNIQUE_FUNCTION<%0...%1> %0YYj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (145655)
	#elseif UNIQUE_SYMBOL == (145647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145648)
		#define UNIQUE_FUNCTION<%0...%1> %0YYk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145649)
		#define UNIQUE_FUNCTION<%0...%1> %0YYl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145650)
		#define UNIQUE_FUNCTION<%0...%1> %0YYm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145651)
		#define UNIQUE_FUNCTION<%0...%1> %0YYn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145652)
		#define UNIQUE_FUNCTION<%0...%1> %0YYo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145653)
		#define UNIQUE_FUNCTION<%0...%1> %0YYp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145654)
		#define UNIQUE_FUNCTION<%0...%1> %0YYq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145655)
		#define UNIQUE_FUNCTION<%0...%1> %0YYr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (145655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145656)
		#define UNIQUE_FUNCTION<%0...%1> %0YYs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145657)
		#define UNIQUE_FUNCTION<%0...%1> %0YYt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145658)
		#define UNIQUE_FUNCTION<%0...%1> %0YYu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145659)
		#define UNIQUE_FUNCTION<%0...%1> %0YYv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145660)
		#define UNIQUE_FUNCTION<%0...%1> %0YYw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145661)
		#define UNIQUE_FUNCTION<%0...%1> %0YYx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (145661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145662)
		#define UNIQUE_FUNCTION<%0...%1> %0YYy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (145663)
		#define UNIQUE_FUNCTION<%0...%1> %0YYz%1
		#endinput
	#endif
#endif
