static stock const Y_UNIQUE_261248_261311_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_261248_261311
	#undef _inc_y_unique_261248_261311
#endif

#if UNIQUE_SYMBOL < (261255)
	#if UNIQUE_SYMBOL == (261247)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261248)
		#define UNIQUE_FUNCTION<%0...%1> %0zm0%1
		#endinput
	#if UNIQUE_SYMBOL == (261248)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261249)
		#define UNIQUE_FUNCTION<%0...%1> %0zm1%1
		#endinput
	#if UNIQUE_SYMBOL == (261249)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261250)
		#define UNIQUE_FUNCTION<%0...%1> %0zm2%1
		#endinput
	#if UNIQUE_SYMBOL == (261250)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261251)
		#define UNIQUE_FUNCTION<%0...%1> %0zm3%1
		#endinput
	#if UNIQUE_SYMBOL == (261251)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261252)
		#define UNIQUE_FUNCTION<%0...%1> %0zm4%1
		#endinput
	#if UNIQUE_SYMBOL == (261252)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261253)
		#define UNIQUE_FUNCTION<%0...%1> %0zm5%1
		#endinput
	#if UNIQUE_SYMBOL == (261253)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261254)
		#define UNIQUE_FUNCTION<%0...%1> %0zm6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261255)
		#define UNIQUE_FUNCTION<%0...%1> %0zm7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261263)
	#elseif UNIQUE_SYMBOL == (261255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261256)
		#define UNIQUE_FUNCTION<%0...%1> %0zm8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261257)
		#define UNIQUE_FUNCTION<%0...%1> %0zm9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261258)
		#define UNIQUE_FUNCTION<%0...%1> %0zm@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261259)
		#define UNIQUE_FUNCTION<%0...%1> %0zmA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261260)
		#define UNIQUE_FUNCTION<%0...%1> %0zmB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261261)
		#define UNIQUE_FUNCTION<%0...%1> %0zmC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261262)
		#define UNIQUE_FUNCTION<%0...%1> %0zmD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261263)
		#define UNIQUE_FUNCTION<%0...%1> %0zmE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261271)
	#elseif UNIQUE_SYMBOL == (261263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261264)
		#define UNIQUE_FUNCTION<%0...%1> %0zmF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261265)
		#define UNIQUE_FUNCTION<%0...%1> %0zmG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261266)
		#define UNIQUE_FUNCTION<%0...%1> %0zmH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261267)
		#define UNIQUE_FUNCTION<%0...%1> %0zmI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261268)
		#define UNIQUE_FUNCTION<%0...%1> %0zmJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261269)
		#define UNIQUE_FUNCTION<%0...%1> %0zmK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261270)
		#define UNIQUE_FUNCTION<%0...%1> %0zmL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261271)
		#define UNIQUE_FUNCTION<%0...%1> %0zmM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261279)
	#elseif UNIQUE_SYMBOL == (261271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261272)
		#define UNIQUE_FUNCTION<%0...%1> %0zmN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261273)
		#define UNIQUE_FUNCTION<%0...%1> %0zmO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261274)
		#define UNIQUE_FUNCTION<%0...%1> %0zmP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261275)
		#define UNIQUE_FUNCTION<%0...%1> %0zmQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261276)
		#define UNIQUE_FUNCTION<%0...%1> %0zmR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261277)
		#define UNIQUE_FUNCTION<%0...%1> %0zmS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261278)
		#define UNIQUE_FUNCTION<%0...%1> %0zmT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261279)
		#define UNIQUE_FUNCTION<%0...%1> %0zmU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261287)
	#elseif UNIQUE_SYMBOL == (261279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261280)
		#define UNIQUE_FUNCTION<%0...%1> %0zmV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261281)
		#define UNIQUE_FUNCTION<%0...%1> %0zmW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261282)
		#define UNIQUE_FUNCTION<%0...%1> %0zmX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261283)
		#define UNIQUE_FUNCTION<%0...%1> %0zmY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261284)
		#define UNIQUE_FUNCTION<%0...%1> %0zmZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261285)
		#define UNIQUE_FUNCTION<%0...%1> %0zm_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261286)
		#define UNIQUE_FUNCTION<%0...%1> %0zma%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261287)
		#define UNIQUE_FUNCTION<%0...%1> %0zmb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261295)
	#elseif UNIQUE_SYMBOL == (261287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261288)
		#define UNIQUE_FUNCTION<%0...%1> %0zmc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261289)
		#define UNIQUE_FUNCTION<%0...%1> %0zmd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261290)
		#define UNIQUE_FUNCTION<%0...%1> %0zme%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261291)
		#define UNIQUE_FUNCTION<%0...%1> %0zmf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261292)
		#define UNIQUE_FUNCTION<%0...%1> %0zmg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261293)
		#define UNIQUE_FUNCTION<%0...%1> %0zmh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261294)
		#define UNIQUE_FUNCTION<%0...%1> %0zmi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261295)
		#define UNIQUE_FUNCTION<%0...%1> %0zmj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (261303)
	#elseif UNIQUE_SYMBOL == (261295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261296)
		#define UNIQUE_FUNCTION<%0...%1> %0zmk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261297)
		#define UNIQUE_FUNCTION<%0...%1> %0zml%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261298)
		#define UNIQUE_FUNCTION<%0...%1> %0zmm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261299)
		#define UNIQUE_FUNCTION<%0...%1> %0zmn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261300)
		#define UNIQUE_FUNCTION<%0...%1> %0zmo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261301)
		#define UNIQUE_FUNCTION<%0...%1> %0zmp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261302)
		#define UNIQUE_FUNCTION<%0...%1> %0zmq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261303)
		#define UNIQUE_FUNCTION<%0...%1> %0zmr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (261303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261304)
		#define UNIQUE_FUNCTION<%0...%1> %0zms%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261305)
		#define UNIQUE_FUNCTION<%0...%1> %0zmt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261306)
		#define UNIQUE_FUNCTION<%0...%1> %0zmu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261307)
		#define UNIQUE_FUNCTION<%0...%1> %0zmv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261308)
		#define UNIQUE_FUNCTION<%0...%1> %0zmw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261309)
		#define UNIQUE_FUNCTION<%0...%1> %0zmx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (261309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261310)
		#define UNIQUE_FUNCTION<%0...%1> %0zmy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (261311)
		#define UNIQUE_FUNCTION<%0...%1> %0zmz%1
		#endinput
	#endif
#endif
