static stock const Y_UNIQUE_212160_212223_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_212160_212223
	#undef _inc_y_unique_212160_212223
#endif

#if UNIQUE_SYMBOL < (212167)
	#if UNIQUE_SYMBOL == (212159)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212160)
		#define UNIQUE_FUNCTION<%0...%1> %0nn0%1
		#endinput
	#if UNIQUE_SYMBOL == (212160)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212161)
		#define UNIQUE_FUNCTION<%0...%1> %0nn1%1
		#endinput
	#if UNIQUE_SYMBOL == (212161)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212162)
		#define UNIQUE_FUNCTION<%0...%1> %0nn2%1
		#endinput
	#if UNIQUE_SYMBOL == (212162)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212163)
		#define UNIQUE_FUNCTION<%0...%1> %0nn3%1
		#endinput
	#if UNIQUE_SYMBOL == (212163)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212164)
		#define UNIQUE_FUNCTION<%0...%1> %0nn4%1
		#endinput
	#if UNIQUE_SYMBOL == (212164)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212165)
		#define UNIQUE_FUNCTION<%0...%1> %0nn5%1
		#endinput
	#if UNIQUE_SYMBOL == (212165)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212166)
		#define UNIQUE_FUNCTION<%0...%1> %0nn6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212167)
		#define UNIQUE_FUNCTION<%0...%1> %0nn7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212175)
	#elseif UNIQUE_SYMBOL == (212167)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212168)
		#define UNIQUE_FUNCTION<%0...%1> %0nn8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212168)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212169)
		#define UNIQUE_FUNCTION<%0...%1> %0nn9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212169)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212170)
		#define UNIQUE_FUNCTION<%0...%1> %0nn@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212170)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212171)
		#define UNIQUE_FUNCTION<%0...%1> %0nnA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212171)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212172)
		#define UNIQUE_FUNCTION<%0...%1> %0nnB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212172)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212173)
		#define UNIQUE_FUNCTION<%0...%1> %0nnC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212173)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212174)
		#define UNIQUE_FUNCTION<%0...%1> %0nnD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212175)
		#define UNIQUE_FUNCTION<%0...%1> %0nnE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212183)
	#elseif UNIQUE_SYMBOL == (212175)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212176)
		#define UNIQUE_FUNCTION<%0...%1> %0nnF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212176)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212177)
		#define UNIQUE_FUNCTION<%0...%1> %0nnG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212177)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212178)
		#define UNIQUE_FUNCTION<%0...%1> %0nnH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212178)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212179)
		#define UNIQUE_FUNCTION<%0...%1> %0nnI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212179)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212180)
		#define UNIQUE_FUNCTION<%0...%1> %0nnJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212180)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212181)
		#define UNIQUE_FUNCTION<%0...%1> %0nnK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212181)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212182)
		#define UNIQUE_FUNCTION<%0...%1> %0nnL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212183)
		#define UNIQUE_FUNCTION<%0...%1> %0nnM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212191)
	#elseif UNIQUE_SYMBOL == (212183)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212184)
		#define UNIQUE_FUNCTION<%0...%1> %0nnN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212184)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212185)
		#define UNIQUE_FUNCTION<%0...%1> %0nnO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212185)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212186)
		#define UNIQUE_FUNCTION<%0...%1> %0nnP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212186)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212187)
		#define UNIQUE_FUNCTION<%0...%1> %0nnQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212187)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212188)
		#define UNIQUE_FUNCTION<%0...%1> %0nnR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212188)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212189)
		#define UNIQUE_FUNCTION<%0...%1> %0nnS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212189)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212190)
		#define UNIQUE_FUNCTION<%0...%1> %0nnT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212191)
		#define UNIQUE_FUNCTION<%0...%1> %0nnU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212199)
	#elseif UNIQUE_SYMBOL == (212191)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212192)
		#define UNIQUE_FUNCTION<%0...%1> %0nnV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212192)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212193)
		#define UNIQUE_FUNCTION<%0...%1> %0nnW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212193)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212194)
		#define UNIQUE_FUNCTION<%0...%1> %0nnX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212194)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212195)
		#define UNIQUE_FUNCTION<%0...%1> %0nnY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212195)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212196)
		#define UNIQUE_FUNCTION<%0...%1> %0nnZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212196)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212197)
		#define UNIQUE_FUNCTION<%0...%1> %0nn_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212197)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212198)
		#define UNIQUE_FUNCTION<%0...%1> %0nna%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212199)
		#define UNIQUE_FUNCTION<%0...%1> %0nnb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212207)
	#elseif UNIQUE_SYMBOL == (212199)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212200)
		#define UNIQUE_FUNCTION<%0...%1> %0nnc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212200)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212201)
		#define UNIQUE_FUNCTION<%0...%1> %0nnd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212201)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212202)
		#define UNIQUE_FUNCTION<%0...%1> %0nne%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212202)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212203)
		#define UNIQUE_FUNCTION<%0...%1> %0nnf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212203)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212204)
		#define UNIQUE_FUNCTION<%0...%1> %0nng%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212204)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212205)
		#define UNIQUE_FUNCTION<%0...%1> %0nnh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212205)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212206)
		#define UNIQUE_FUNCTION<%0...%1> %0nni%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212207)
		#define UNIQUE_FUNCTION<%0...%1> %0nnj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (212215)
	#elseif UNIQUE_SYMBOL == (212207)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212208)
		#define UNIQUE_FUNCTION<%0...%1> %0nnk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212208)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212209)
		#define UNIQUE_FUNCTION<%0...%1> %0nnl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212209)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212210)
		#define UNIQUE_FUNCTION<%0...%1> %0nnm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212210)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212211)
		#define UNIQUE_FUNCTION<%0...%1> %0nnn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212211)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212212)
		#define UNIQUE_FUNCTION<%0...%1> %0nno%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212212)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212213)
		#define UNIQUE_FUNCTION<%0...%1> %0nnp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212213)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212214)
		#define UNIQUE_FUNCTION<%0...%1> %0nnq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212215)
		#define UNIQUE_FUNCTION<%0...%1> %0nnr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (212215)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212216)
		#define UNIQUE_FUNCTION<%0...%1> %0nns%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212216)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212217)
		#define UNIQUE_FUNCTION<%0...%1> %0nnt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212217)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212218)
		#define UNIQUE_FUNCTION<%0...%1> %0nnu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212218)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212219)
		#define UNIQUE_FUNCTION<%0...%1> %0nnv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212219)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212220)
		#define UNIQUE_FUNCTION<%0...%1> %0nnw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212220)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212221)
		#define UNIQUE_FUNCTION<%0...%1> %0nnx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (212221)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212222)
		#define UNIQUE_FUNCTION<%0...%1> %0nny%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (212223)
		#define UNIQUE_FUNCTION<%0...%1> %0nnz%1
		#endinput
	#endif
#endif
