static stock const Y_UNIQUE_120000_120063_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_120000_120063
	#undef _inc_y_unique_120000_120063
#endif

#if UNIQUE_SYMBOL < (120007)
	#if UNIQUE_SYMBOL == (119999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120000)
		#define UNIQUE_FUNCTION<%0...%1> %0SI0%1
		#endinput
	#if UNIQUE_SYMBOL == (120000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120001)
		#define UNIQUE_FUNCTION<%0...%1> %0SI1%1
		#endinput
	#if UNIQUE_SYMBOL == (120001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120002)
		#define UNIQUE_FUNCTION<%0...%1> %0SI2%1
		#endinput
	#if UNIQUE_SYMBOL == (120002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120003)
		#define UNIQUE_FUNCTION<%0...%1> %0SI3%1
		#endinput
	#if UNIQUE_SYMBOL == (120003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120004)
		#define UNIQUE_FUNCTION<%0...%1> %0SI4%1
		#endinput
	#if UNIQUE_SYMBOL == (120004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120005)
		#define UNIQUE_FUNCTION<%0...%1> %0SI5%1
		#endinput
	#if UNIQUE_SYMBOL == (120005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120006)
		#define UNIQUE_FUNCTION<%0...%1> %0SI6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120007)
		#define UNIQUE_FUNCTION<%0...%1> %0SI7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120015)
	#elseif UNIQUE_SYMBOL == (120007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120008)
		#define UNIQUE_FUNCTION<%0...%1> %0SI8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120009)
		#define UNIQUE_FUNCTION<%0...%1> %0SI9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120010)
		#define UNIQUE_FUNCTION<%0...%1> %0SI@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120011)
		#define UNIQUE_FUNCTION<%0...%1> %0SIA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120012)
		#define UNIQUE_FUNCTION<%0...%1> %0SIB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120013)
		#define UNIQUE_FUNCTION<%0...%1> %0SIC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120014)
		#define UNIQUE_FUNCTION<%0...%1> %0SID%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120015)
		#define UNIQUE_FUNCTION<%0...%1> %0SIE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120023)
	#elseif UNIQUE_SYMBOL == (120015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120016)
		#define UNIQUE_FUNCTION<%0...%1> %0SIF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120017)
		#define UNIQUE_FUNCTION<%0...%1> %0SIG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120018)
		#define UNIQUE_FUNCTION<%0...%1> %0SIH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120019)
		#define UNIQUE_FUNCTION<%0...%1> %0SII%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120020)
		#define UNIQUE_FUNCTION<%0...%1> %0SIJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120021)
		#define UNIQUE_FUNCTION<%0...%1> %0SIK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120022)
		#define UNIQUE_FUNCTION<%0...%1> %0SIL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120023)
		#define UNIQUE_FUNCTION<%0...%1> %0SIM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120031)
	#elseif UNIQUE_SYMBOL == (120023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120024)
		#define UNIQUE_FUNCTION<%0...%1> %0SIN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120025)
		#define UNIQUE_FUNCTION<%0...%1> %0SIO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120026)
		#define UNIQUE_FUNCTION<%0...%1> %0SIP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120027)
		#define UNIQUE_FUNCTION<%0...%1> %0SIQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120028)
		#define UNIQUE_FUNCTION<%0...%1> %0SIR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120029)
		#define UNIQUE_FUNCTION<%0...%1> %0SIS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120030)
		#define UNIQUE_FUNCTION<%0...%1> %0SIT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120031)
		#define UNIQUE_FUNCTION<%0...%1> %0SIU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120039)
	#elseif UNIQUE_SYMBOL == (120031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120032)
		#define UNIQUE_FUNCTION<%0...%1> %0SIV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120033)
		#define UNIQUE_FUNCTION<%0...%1> %0SIW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120034)
		#define UNIQUE_FUNCTION<%0...%1> %0SIX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120035)
		#define UNIQUE_FUNCTION<%0...%1> %0SIY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120036)
		#define UNIQUE_FUNCTION<%0...%1> %0SIZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120037)
		#define UNIQUE_FUNCTION<%0...%1> %0SI_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120038)
		#define UNIQUE_FUNCTION<%0...%1> %0SIa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120039)
		#define UNIQUE_FUNCTION<%0...%1> %0SIb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120047)
	#elseif UNIQUE_SYMBOL == (120039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120040)
		#define UNIQUE_FUNCTION<%0...%1> %0SIc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120041)
		#define UNIQUE_FUNCTION<%0...%1> %0SId%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120042)
		#define UNIQUE_FUNCTION<%0...%1> %0SIe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120043)
		#define UNIQUE_FUNCTION<%0...%1> %0SIf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120044)
		#define UNIQUE_FUNCTION<%0...%1> %0SIg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120045)
		#define UNIQUE_FUNCTION<%0...%1> %0SIh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120046)
		#define UNIQUE_FUNCTION<%0...%1> %0SIi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120047)
		#define UNIQUE_FUNCTION<%0...%1> %0SIj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (120055)
	#elseif UNIQUE_SYMBOL == (120047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120048)
		#define UNIQUE_FUNCTION<%0...%1> %0SIk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120049)
		#define UNIQUE_FUNCTION<%0...%1> %0SIl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120050)
		#define UNIQUE_FUNCTION<%0...%1> %0SIm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120051)
		#define UNIQUE_FUNCTION<%0...%1> %0SIn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120052)
		#define UNIQUE_FUNCTION<%0...%1> %0SIo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120053)
		#define UNIQUE_FUNCTION<%0...%1> %0SIp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120054)
		#define UNIQUE_FUNCTION<%0...%1> %0SIq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120055)
		#define UNIQUE_FUNCTION<%0...%1> %0SIr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (120055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120056)
		#define UNIQUE_FUNCTION<%0...%1> %0SIs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120057)
		#define UNIQUE_FUNCTION<%0...%1> %0SIt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120058)
		#define UNIQUE_FUNCTION<%0...%1> %0SIu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120059)
		#define UNIQUE_FUNCTION<%0...%1> %0SIv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120060)
		#define UNIQUE_FUNCTION<%0...%1> %0SIw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120061)
		#define UNIQUE_FUNCTION<%0...%1> %0SIx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (120061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120062)
		#define UNIQUE_FUNCTION<%0...%1> %0SIy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (120063)
		#define UNIQUE_FUNCTION<%0...%1> %0SIz%1
		#endinput
	#endif
#endif
