static stock const Y_UNIQUE_080256_080319_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_080256_080319
	#undef _inc_y_unique_080256_080319
#endif

#if UNIQUE_SYMBOL < (80263)
	#if UNIQUE_SYMBOL == (80255)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80256)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia0%1
		#endinput
	#if UNIQUE_SYMBOL == (80256)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80257)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia1%1
		#endinput
	#if UNIQUE_SYMBOL == (80257)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80258)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia2%1
		#endinput
	#if UNIQUE_SYMBOL == (80258)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80259)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia3%1
		#endinput
	#if UNIQUE_SYMBOL == (80259)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80260)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia4%1
		#endinput
	#if UNIQUE_SYMBOL == (80260)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80261)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia5%1
		#endinput
	#if UNIQUE_SYMBOL == (80261)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80262)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80263)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80271)
	#elseif UNIQUE_SYMBOL == (80263)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80264)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80264)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80265)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80265)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80266)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80266)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80267)
		#define UNIQUE_FUNCTION<%0...%1> %0IaA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80267)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80268)
		#define UNIQUE_FUNCTION<%0...%1> %0IaB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80268)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80269)
		#define UNIQUE_FUNCTION<%0...%1> %0IaC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80269)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80270)
		#define UNIQUE_FUNCTION<%0...%1> %0IaD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80271)
		#define UNIQUE_FUNCTION<%0...%1> %0IaE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80279)
	#elseif UNIQUE_SYMBOL == (80271)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80272)
		#define UNIQUE_FUNCTION<%0...%1> %0IaF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80272)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80273)
		#define UNIQUE_FUNCTION<%0...%1> %0IaG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80273)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80274)
		#define UNIQUE_FUNCTION<%0...%1> %0IaH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80274)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80275)
		#define UNIQUE_FUNCTION<%0...%1> %0IaI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80275)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80276)
		#define UNIQUE_FUNCTION<%0...%1> %0IaJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80276)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80277)
		#define UNIQUE_FUNCTION<%0...%1> %0IaK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80277)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80278)
		#define UNIQUE_FUNCTION<%0...%1> %0IaL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80279)
		#define UNIQUE_FUNCTION<%0...%1> %0IaM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80287)
	#elseif UNIQUE_SYMBOL == (80279)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80280)
		#define UNIQUE_FUNCTION<%0...%1> %0IaN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80280)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80281)
		#define UNIQUE_FUNCTION<%0...%1> %0IaO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80281)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80282)
		#define UNIQUE_FUNCTION<%0...%1> %0IaP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80282)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80283)
		#define UNIQUE_FUNCTION<%0...%1> %0IaQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80283)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80284)
		#define UNIQUE_FUNCTION<%0...%1> %0IaR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80284)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80285)
		#define UNIQUE_FUNCTION<%0...%1> %0IaS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80285)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80286)
		#define UNIQUE_FUNCTION<%0...%1> %0IaT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80287)
		#define UNIQUE_FUNCTION<%0...%1> %0IaU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80295)
	#elseif UNIQUE_SYMBOL == (80287)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80288)
		#define UNIQUE_FUNCTION<%0...%1> %0IaV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80288)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80289)
		#define UNIQUE_FUNCTION<%0...%1> %0IaW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80289)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80290)
		#define UNIQUE_FUNCTION<%0...%1> %0IaX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80290)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80291)
		#define UNIQUE_FUNCTION<%0...%1> %0IaY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80291)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80292)
		#define UNIQUE_FUNCTION<%0...%1> %0IaZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80292)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80293)
		#define UNIQUE_FUNCTION<%0...%1> %0Ia_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80293)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80294)
		#define UNIQUE_FUNCTION<%0...%1> %0Iaa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80295)
		#define UNIQUE_FUNCTION<%0...%1> %0Iab%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80303)
	#elseif UNIQUE_SYMBOL == (80295)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80296)
		#define UNIQUE_FUNCTION<%0...%1> %0Iac%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80296)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80297)
		#define UNIQUE_FUNCTION<%0...%1> %0Iad%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80297)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80298)
		#define UNIQUE_FUNCTION<%0...%1> %0Iae%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80298)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80299)
		#define UNIQUE_FUNCTION<%0...%1> %0Iaf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80299)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80300)
		#define UNIQUE_FUNCTION<%0...%1> %0Iag%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80300)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80301)
		#define UNIQUE_FUNCTION<%0...%1> %0Iah%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80301)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80302)
		#define UNIQUE_FUNCTION<%0...%1> %0Iai%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80303)
		#define UNIQUE_FUNCTION<%0...%1> %0Iaj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (80311)
	#elseif UNIQUE_SYMBOL == (80303)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80304)
		#define UNIQUE_FUNCTION<%0...%1> %0Iak%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80304)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80305)
		#define UNIQUE_FUNCTION<%0...%1> %0Ial%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80305)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80306)
		#define UNIQUE_FUNCTION<%0...%1> %0Iam%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80306)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80307)
		#define UNIQUE_FUNCTION<%0...%1> %0Ian%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80307)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80308)
		#define UNIQUE_FUNCTION<%0...%1> %0Iao%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80308)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80309)
		#define UNIQUE_FUNCTION<%0...%1> %0Iap%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80309)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80310)
		#define UNIQUE_FUNCTION<%0...%1> %0Iaq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80311)
		#define UNIQUE_FUNCTION<%0...%1> %0Iar%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (80311)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80312)
		#define UNIQUE_FUNCTION<%0...%1> %0Ias%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80312)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80313)
		#define UNIQUE_FUNCTION<%0...%1> %0Iat%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80313)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80314)
		#define UNIQUE_FUNCTION<%0...%1> %0Iau%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80314)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80315)
		#define UNIQUE_FUNCTION<%0...%1> %0Iav%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80315)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80316)
		#define UNIQUE_FUNCTION<%0...%1> %0Iaw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80316)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80317)
		#define UNIQUE_FUNCTION<%0...%1> %0Iax%1
		#endinput
	#elseif UNIQUE_SYMBOL == (80317)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80318)
		#define UNIQUE_FUNCTION<%0...%1> %0Iay%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (80319)
		#define UNIQUE_FUNCTION<%0...%1> %0Iaz%1
		#endinput
	#endif
#endif
