static stock const Y_UNIQUE_089984_090047_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_089984_090047
	#undef _inc_y_unique_089984_090047
#endif

#if UNIQUE_SYMBOL < (89991)
	#if UNIQUE_SYMBOL == (89983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89984)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky0%1
		#endinput
	#if UNIQUE_SYMBOL == (89984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89985)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky1%1
		#endinput
	#if UNIQUE_SYMBOL == (89985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89986)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky2%1
		#endinput
	#if UNIQUE_SYMBOL == (89986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89987)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky3%1
		#endinput
	#if UNIQUE_SYMBOL == (89987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89988)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky4%1
		#endinput
	#if UNIQUE_SYMBOL == (89988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89989)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky5%1
		#endinput
	#if UNIQUE_SYMBOL == (89989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89990)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89991)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (89999)
	#elseif UNIQUE_SYMBOL == (89991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89992)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89993)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89994)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89995)
		#define UNIQUE_FUNCTION<%0...%1> %0KyA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89996)
		#define UNIQUE_FUNCTION<%0...%1> %0KyB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89997)
		#define UNIQUE_FUNCTION<%0...%1> %0KyC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (89997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89998)
		#define UNIQUE_FUNCTION<%0...%1> %0KyD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (89999)
		#define UNIQUE_FUNCTION<%0...%1> %0KyE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90007)
	#elseif UNIQUE_SYMBOL == (89999)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90000)
		#define UNIQUE_FUNCTION<%0...%1> %0KyF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90000)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90001)
		#define UNIQUE_FUNCTION<%0...%1> %0KyG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90001)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90002)
		#define UNIQUE_FUNCTION<%0...%1> %0KyH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90002)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90003)
		#define UNIQUE_FUNCTION<%0...%1> %0KyI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90003)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90004)
		#define UNIQUE_FUNCTION<%0...%1> %0KyJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90004)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90005)
		#define UNIQUE_FUNCTION<%0...%1> %0KyK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90005)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90006)
		#define UNIQUE_FUNCTION<%0...%1> %0KyL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90007)
		#define UNIQUE_FUNCTION<%0...%1> %0KyM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90015)
	#elseif UNIQUE_SYMBOL == (90007)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90008)
		#define UNIQUE_FUNCTION<%0...%1> %0KyN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90008)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90009)
		#define UNIQUE_FUNCTION<%0...%1> %0KyO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90009)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90010)
		#define UNIQUE_FUNCTION<%0...%1> %0KyP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90010)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90011)
		#define UNIQUE_FUNCTION<%0...%1> %0KyQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90011)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90012)
		#define UNIQUE_FUNCTION<%0...%1> %0KyR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90012)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90013)
		#define UNIQUE_FUNCTION<%0...%1> %0KyS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90013)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90014)
		#define UNIQUE_FUNCTION<%0...%1> %0KyT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90015)
		#define UNIQUE_FUNCTION<%0...%1> %0KyU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90023)
	#elseif UNIQUE_SYMBOL == (90015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90016)
		#define UNIQUE_FUNCTION<%0...%1> %0KyV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90017)
		#define UNIQUE_FUNCTION<%0...%1> %0KyW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90018)
		#define UNIQUE_FUNCTION<%0...%1> %0KyX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90019)
		#define UNIQUE_FUNCTION<%0...%1> %0KyY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90020)
		#define UNIQUE_FUNCTION<%0...%1> %0KyZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90021)
		#define UNIQUE_FUNCTION<%0...%1> %0Ky_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90022)
		#define UNIQUE_FUNCTION<%0...%1> %0Kya%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90023)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90031)
	#elseif UNIQUE_SYMBOL == (90023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90024)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90025)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90026)
		#define UNIQUE_FUNCTION<%0...%1> %0Kye%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90027)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90028)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90029)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90030)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90031)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (90039)
	#elseif UNIQUE_SYMBOL == (90031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90032)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90033)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90034)
		#define UNIQUE_FUNCTION<%0...%1> %0Kym%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90035)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90036)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90037)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90038)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90039)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (90039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90040)
		#define UNIQUE_FUNCTION<%0...%1> %0Kys%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90041)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90042)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90043)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90044)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90045)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (90045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90046)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (90047)
		#define UNIQUE_FUNCTION<%0...%1> %0Kyz%1
		#endinput
	#endif
#endif
