static stock const Y_UNIQUE_135936_135999_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_135936_135999
	#undef _inc_y_unique_135936_135999
#endif

#if UNIQUE_SYMBOL < (135943)
	#if UNIQUE_SYMBOL == (135935)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135936)
		#define UNIQUE_FUNCTION<%0...%1> %0WB0%1
		#endinput
	#if UNIQUE_SYMBOL == (135936)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135937)
		#define UNIQUE_FUNCTION<%0...%1> %0WB1%1
		#endinput
	#if UNIQUE_SYMBOL == (135937)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135938)
		#define UNIQUE_FUNCTION<%0...%1> %0WB2%1
		#endinput
	#if UNIQUE_SYMBOL == (135938)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135939)
		#define UNIQUE_FUNCTION<%0...%1> %0WB3%1
		#endinput
	#if UNIQUE_SYMBOL == (135939)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135940)
		#define UNIQUE_FUNCTION<%0...%1> %0WB4%1
		#endinput
	#if UNIQUE_SYMBOL == (135940)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135941)
		#define UNIQUE_FUNCTION<%0...%1> %0WB5%1
		#endinput
	#if UNIQUE_SYMBOL == (135941)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135942)
		#define UNIQUE_FUNCTION<%0...%1> %0WB6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135943)
		#define UNIQUE_FUNCTION<%0...%1> %0WB7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135951)
	#elseif UNIQUE_SYMBOL == (135943)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135944)
		#define UNIQUE_FUNCTION<%0...%1> %0WB8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135944)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135945)
		#define UNIQUE_FUNCTION<%0...%1> %0WB9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135945)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135946)
		#define UNIQUE_FUNCTION<%0...%1> %0WB@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135946)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135947)
		#define UNIQUE_FUNCTION<%0...%1> %0WBA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135947)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135948)
		#define UNIQUE_FUNCTION<%0...%1> %0WBB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135948)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135949)
		#define UNIQUE_FUNCTION<%0...%1> %0WBC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135949)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135950)
		#define UNIQUE_FUNCTION<%0...%1> %0WBD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135951)
		#define UNIQUE_FUNCTION<%0...%1> %0WBE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135959)
	#elseif UNIQUE_SYMBOL == (135951)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135952)
		#define UNIQUE_FUNCTION<%0...%1> %0WBF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135952)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135953)
		#define UNIQUE_FUNCTION<%0...%1> %0WBG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135953)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135954)
		#define UNIQUE_FUNCTION<%0...%1> %0WBH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135954)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135955)
		#define UNIQUE_FUNCTION<%0...%1> %0WBI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135955)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135956)
		#define UNIQUE_FUNCTION<%0...%1> %0WBJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135956)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135957)
		#define UNIQUE_FUNCTION<%0...%1> %0WBK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135957)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135958)
		#define UNIQUE_FUNCTION<%0...%1> %0WBL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135959)
		#define UNIQUE_FUNCTION<%0...%1> %0WBM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135967)
	#elseif UNIQUE_SYMBOL == (135959)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135960)
		#define UNIQUE_FUNCTION<%0...%1> %0WBN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135960)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135961)
		#define UNIQUE_FUNCTION<%0...%1> %0WBO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135961)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135962)
		#define UNIQUE_FUNCTION<%0...%1> %0WBP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135962)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135963)
		#define UNIQUE_FUNCTION<%0...%1> %0WBQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135963)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135964)
		#define UNIQUE_FUNCTION<%0...%1> %0WBR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135964)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135965)
		#define UNIQUE_FUNCTION<%0...%1> %0WBS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135965)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135966)
		#define UNIQUE_FUNCTION<%0...%1> %0WBT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135967)
		#define UNIQUE_FUNCTION<%0...%1> %0WBU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135975)
	#elseif UNIQUE_SYMBOL == (135967)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135968)
		#define UNIQUE_FUNCTION<%0...%1> %0WBV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135968)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135969)
		#define UNIQUE_FUNCTION<%0...%1> %0WBW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135969)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135970)
		#define UNIQUE_FUNCTION<%0...%1> %0WBX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135970)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135971)
		#define UNIQUE_FUNCTION<%0...%1> %0WBY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135971)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135972)
		#define UNIQUE_FUNCTION<%0...%1> %0WBZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135972)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135973)
		#define UNIQUE_FUNCTION<%0...%1> %0WB_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135973)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135974)
		#define UNIQUE_FUNCTION<%0...%1> %0WBa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135975)
		#define UNIQUE_FUNCTION<%0...%1> %0WBb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135983)
	#elseif UNIQUE_SYMBOL == (135975)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135976)
		#define UNIQUE_FUNCTION<%0...%1> %0WBc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135976)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135977)
		#define UNIQUE_FUNCTION<%0...%1> %0WBd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135977)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135978)
		#define UNIQUE_FUNCTION<%0...%1> %0WBe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135978)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135979)
		#define UNIQUE_FUNCTION<%0...%1> %0WBf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135979)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135980)
		#define UNIQUE_FUNCTION<%0...%1> %0WBg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135980)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135981)
		#define UNIQUE_FUNCTION<%0...%1> %0WBh%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135981)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135982)
		#define UNIQUE_FUNCTION<%0...%1> %0WBi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135983)
		#define UNIQUE_FUNCTION<%0...%1> %0WBj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (135991)
	#elseif UNIQUE_SYMBOL == (135983)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135984)
		#define UNIQUE_FUNCTION<%0...%1> %0WBk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135984)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135985)
		#define UNIQUE_FUNCTION<%0...%1> %0WBl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135985)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135986)
		#define UNIQUE_FUNCTION<%0...%1> %0WBm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135986)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135987)
		#define UNIQUE_FUNCTION<%0...%1> %0WBn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135987)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135988)
		#define UNIQUE_FUNCTION<%0...%1> %0WBo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135988)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135989)
		#define UNIQUE_FUNCTION<%0...%1> %0WBp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135989)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135990)
		#define UNIQUE_FUNCTION<%0...%1> %0WBq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135991)
		#define UNIQUE_FUNCTION<%0...%1> %0WBr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (135991)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135992)
		#define UNIQUE_FUNCTION<%0...%1> %0WBs%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135992)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135993)
		#define UNIQUE_FUNCTION<%0...%1> %0WBt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135993)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135994)
		#define UNIQUE_FUNCTION<%0...%1> %0WBu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135994)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135995)
		#define UNIQUE_FUNCTION<%0...%1> %0WBv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135995)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135996)
		#define UNIQUE_FUNCTION<%0...%1> %0WBw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135996)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135997)
		#define UNIQUE_FUNCTION<%0...%1> %0WBx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (135997)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135998)
		#define UNIQUE_FUNCTION<%0...%1> %0WBy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (135999)
		#define UNIQUE_FUNCTION<%0...%1> %0WBz%1
		#endinput
	#endif
#endif
