static stock const Y_UNIQUE_062016_062079_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_062016_062079
	#undef _inc_y_unique_062016_062079
#endif

#if UNIQUE_SYMBOL < (62023)
	#if UNIQUE_SYMBOL == (62015)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62016)
		#define UNIQUE_FUNCTION<%0...%1> %0E90%1
		#endinput
	#if UNIQUE_SYMBOL == (62016)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62017)
		#define UNIQUE_FUNCTION<%0...%1> %0E91%1
		#endinput
	#if UNIQUE_SYMBOL == (62017)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62018)
		#define UNIQUE_FUNCTION<%0...%1> %0E92%1
		#endinput
	#if UNIQUE_SYMBOL == (62018)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62019)
		#define UNIQUE_FUNCTION<%0...%1> %0E93%1
		#endinput
	#if UNIQUE_SYMBOL == (62019)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62020)
		#define UNIQUE_FUNCTION<%0...%1> %0E94%1
		#endinput
	#if UNIQUE_SYMBOL == (62020)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62021)
		#define UNIQUE_FUNCTION<%0...%1> %0E95%1
		#endinput
	#if UNIQUE_SYMBOL == (62021)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62022)
		#define UNIQUE_FUNCTION<%0...%1> %0E96%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62023)
		#define UNIQUE_FUNCTION<%0...%1> %0E97%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (62031)
	#elseif UNIQUE_SYMBOL == (62023)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62024)
		#define UNIQUE_FUNCTION<%0...%1> %0E98%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62024)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62025)
		#define UNIQUE_FUNCTION<%0...%1> %0E99%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62025)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62026)
		#define UNIQUE_FUNCTION<%0...%1> %0E9@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62026)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62027)
		#define UNIQUE_FUNCTION<%0...%1> %0E9A%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62027)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62028)
		#define UNIQUE_FUNCTION<%0...%1> %0E9B%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62028)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62029)
		#define UNIQUE_FUNCTION<%0...%1> %0E9C%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62029)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62030)
		#define UNIQUE_FUNCTION<%0...%1> %0E9D%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62031)
		#define UNIQUE_FUNCTION<%0...%1> %0E9E%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (62039)
	#elseif UNIQUE_SYMBOL == (62031)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62032)
		#define UNIQUE_FUNCTION<%0...%1> %0E9F%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62032)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62033)
		#define UNIQUE_FUNCTION<%0...%1> %0E9G%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62033)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62034)
		#define UNIQUE_FUNCTION<%0...%1> %0E9H%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62034)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62035)
		#define UNIQUE_FUNCTION<%0...%1> %0E9I%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62035)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62036)
		#define UNIQUE_FUNCTION<%0...%1> %0E9J%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62036)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62037)
		#define UNIQUE_FUNCTION<%0...%1> %0E9K%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62037)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62038)
		#define UNIQUE_FUNCTION<%0...%1> %0E9L%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62039)
		#define UNIQUE_FUNCTION<%0...%1> %0E9M%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (62047)
	#elseif UNIQUE_SYMBOL == (62039)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62040)
		#define UNIQUE_FUNCTION<%0...%1> %0E9N%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62040)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62041)
		#define UNIQUE_FUNCTION<%0...%1> %0E9O%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62041)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62042)
		#define UNIQUE_FUNCTION<%0...%1> %0E9P%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62042)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62043)
		#define UNIQUE_FUNCTION<%0...%1> %0E9Q%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62043)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62044)
		#define UNIQUE_FUNCTION<%0...%1> %0E9R%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62044)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62045)
		#define UNIQUE_FUNCTION<%0...%1> %0E9S%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62045)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62046)
		#define UNIQUE_FUNCTION<%0...%1> %0E9T%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62047)
		#define UNIQUE_FUNCTION<%0...%1> %0E9U%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (62055)
	#elseif UNIQUE_SYMBOL == (62047)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62048)
		#define UNIQUE_FUNCTION<%0...%1> %0E9V%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62048)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62049)
		#define UNIQUE_FUNCTION<%0...%1> %0E9W%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62049)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62050)
		#define UNIQUE_FUNCTION<%0...%1> %0E9X%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62050)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62051)
		#define UNIQUE_FUNCTION<%0...%1> %0E9Y%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62051)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62052)
		#define UNIQUE_FUNCTION<%0...%1> %0E9Z%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62052)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62053)
		#define UNIQUE_FUNCTION<%0...%1> %0E9_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62053)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62054)
		#define UNIQUE_FUNCTION<%0...%1> %0E9a%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62055)
		#define UNIQUE_FUNCTION<%0...%1> %0E9b%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (62063)
	#elseif UNIQUE_SYMBOL == (62055)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62056)
		#define UNIQUE_FUNCTION<%0...%1> %0E9c%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62056)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62057)
		#define UNIQUE_FUNCTION<%0...%1> %0E9d%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62057)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62058)
		#define UNIQUE_FUNCTION<%0...%1> %0E9e%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62058)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62059)
		#define UNIQUE_FUNCTION<%0...%1> %0E9f%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62059)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62060)
		#define UNIQUE_FUNCTION<%0...%1> %0E9g%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62060)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62061)
		#define UNIQUE_FUNCTION<%0...%1> %0E9h%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62061)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62062)
		#define UNIQUE_FUNCTION<%0...%1> %0E9i%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62063)
		#define UNIQUE_FUNCTION<%0...%1> %0E9j%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (62071)
	#elseif UNIQUE_SYMBOL == (62063)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62064)
		#define UNIQUE_FUNCTION<%0...%1> %0E9k%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62064)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62065)
		#define UNIQUE_FUNCTION<%0...%1> %0E9l%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62065)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62066)
		#define UNIQUE_FUNCTION<%0...%1> %0E9m%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62066)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62067)
		#define UNIQUE_FUNCTION<%0...%1> %0E9n%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62067)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62068)
		#define UNIQUE_FUNCTION<%0...%1> %0E9o%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62068)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62069)
		#define UNIQUE_FUNCTION<%0...%1> %0E9p%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62069)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62070)
		#define UNIQUE_FUNCTION<%0...%1> %0E9q%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62071)
		#define UNIQUE_FUNCTION<%0...%1> %0E9r%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (62071)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62072)
		#define UNIQUE_FUNCTION<%0...%1> %0E9s%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62072)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62073)
		#define UNIQUE_FUNCTION<%0...%1> %0E9t%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62073)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62074)
		#define UNIQUE_FUNCTION<%0...%1> %0E9u%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62074)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62075)
		#define UNIQUE_FUNCTION<%0...%1> %0E9v%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62075)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62076)
		#define UNIQUE_FUNCTION<%0...%1> %0E9w%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62076)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62077)
		#define UNIQUE_FUNCTION<%0...%1> %0E9x%1
		#endinput
	#elseif UNIQUE_SYMBOL == (62077)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62078)
		#define UNIQUE_FUNCTION<%0...%1> %0E9y%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (62079)
		#define UNIQUE_FUNCTION<%0...%1> %0E9z%1
		#endinput
	#endif
#endif
