static stock const Y_UNIQUE_097600_097663_CALLED = UNIQUE_SYMBOL;

#if defined _inc_y_unique_097600_097663
	#undef _inc_y_unique_097600_097663
#endif

#if UNIQUE_SYMBOL < (97607)
	#if UNIQUE_SYMBOL == (97599)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97600)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp0%1
		#endinput
	#if UNIQUE_SYMBOL == (97600)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97601)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp1%1
		#endinput
	#if UNIQUE_SYMBOL == (97601)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97602)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp2%1
		#endinput
	#if UNIQUE_SYMBOL == (97602)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97603)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp3%1
		#endinput
	#if UNIQUE_SYMBOL == (97603)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97604)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp4%1
		#endinput
	#if UNIQUE_SYMBOL == (97604)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97605)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp5%1
		#endinput
	#if UNIQUE_SYMBOL == (97605)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97606)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp6%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97607)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp7%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (97615)
	#elseif UNIQUE_SYMBOL == (97607)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97608)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp8%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97608)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97609)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp9%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97609)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97610)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp@%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97610)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97611)
		#define UNIQUE_FUNCTION<%0...%1> %0MpA%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97611)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97612)
		#define UNIQUE_FUNCTION<%0...%1> %0MpB%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97612)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97613)
		#define UNIQUE_FUNCTION<%0...%1> %0MpC%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97613)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97614)
		#define UNIQUE_FUNCTION<%0...%1> %0MpD%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97615)
		#define UNIQUE_FUNCTION<%0...%1> %0MpE%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (97623)
	#elseif UNIQUE_SYMBOL == (97615)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97616)
		#define UNIQUE_FUNCTION<%0...%1> %0MpF%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97616)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97617)
		#define UNIQUE_FUNCTION<%0...%1> %0MpG%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97617)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97618)
		#define UNIQUE_FUNCTION<%0...%1> %0MpH%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97618)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97619)
		#define UNIQUE_FUNCTION<%0...%1> %0MpI%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97619)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97620)
		#define UNIQUE_FUNCTION<%0...%1> %0MpJ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97620)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97621)
		#define UNIQUE_FUNCTION<%0...%1> %0MpK%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97621)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97622)
		#define UNIQUE_FUNCTION<%0...%1> %0MpL%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97623)
		#define UNIQUE_FUNCTION<%0...%1> %0MpM%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (97631)
	#elseif UNIQUE_SYMBOL == (97623)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97624)
		#define UNIQUE_FUNCTION<%0...%1> %0MpN%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97624)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97625)
		#define UNIQUE_FUNCTION<%0...%1> %0MpO%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97625)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97626)
		#define UNIQUE_FUNCTION<%0...%1> %0MpP%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97626)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97627)
		#define UNIQUE_FUNCTION<%0...%1> %0MpQ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97627)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97628)
		#define UNIQUE_FUNCTION<%0...%1> %0MpR%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97628)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97629)
		#define UNIQUE_FUNCTION<%0...%1> %0MpS%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97629)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97630)
		#define UNIQUE_FUNCTION<%0...%1> %0MpT%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97631)
		#define UNIQUE_FUNCTION<%0...%1> %0MpU%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (97639)
	#elseif UNIQUE_SYMBOL == (97631)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97632)
		#define UNIQUE_FUNCTION<%0...%1> %0MpV%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97632)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97633)
		#define UNIQUE_FUNCTION<%0...%1> %0MpW%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97633)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97634)
		#define UNIQUE_FUNCTION<%0...%1> %0MpX%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97634)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97635)
		#define UNIQUE_FUNCTION<%0...%1> %0MpY%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97635)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97636)
		#define UNIQUE_FUNCTION<%0...%1> %0MpZ%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97636)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97637)
		#define UNIQUE_FUNCTION<%0...%1> %0Mp_%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97637)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97638)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpa%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97639)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpb%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (97647)
	#elseif UNIQUE_SYMBOL == (97639)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97640)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpc%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97640)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97641)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpd%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97641)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97642)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpe%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97642)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97643)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpf%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97643)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97644)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpg%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97644)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97645)
		#define UNIQUE_FUNCTION<%0...%1> %0Mph%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97645)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97646)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpi%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97647)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpj%1
		#endinput
	#endif
#elseif UNIQUE_SYMBOL < (97655)
	#elseif UNIQUE_SYMBOL == (97647)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97648)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpk%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97648)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97649)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpl%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97649)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97650)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpm%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97650)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97651)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpn%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97651)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97652)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpo%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97652)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97653)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpp%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97653)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97654)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpq%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97655)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpr%1
		#endinput
	#endif
#else
	#elseif UNIQUE_SYMBOL == (97655)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97656)
		#define UNIQUE_FUNCTION<%0...%1> %0Mps%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97656)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97657)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpt%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97657)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97658)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpu%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97658)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97659)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpv%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97659)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97660)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpw%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97660)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97661)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpx%1
		#endinput
	#elseif UNIQUE_SYMBOL == (97661)
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97662)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpy%1
		#endinput
	#else
		#undef UNIQUE_SYMBOL
		#define UNIQUE_SYMBOL (97663)
		#define UNIQUE_FUNCTION<%0...%1> %0Mpz%1
		#endinput
	#endif
#endif
