#undef _inc__stack_push_003

#undef _YSIM_PUSH_INDEX
#define _YSIM_PUSH_INDEX 4
#if defined _YSIM_STACK_SLOT_3
	#undef _YSIM_STACK_SLOT_3
#endif
#if     _MASTER == 0
	#define _YSIM_STACK_SLOT_3 0
	#endinput
#elseif _MASTER == 1
	#define _YSIM_STACK_SLOT_3 1
	#endinput
#elseif _MASTER == 2
	#define _YSIM_STACK_SLOT_3 2
	#endinput
#elseif _MASTER == 3
	#define _YSIM_STACK_SLOT_3 3
	#endinput
#elseif _MASTER == 4
	#define _YSIM_STACK_SLOT_3 4
	#endinput
#elseif _MASTER == 5
	#define _YSIM_STACK_SLOT_3 5
	#endinput
#elseif _MASTER == 6
	#define _YSIM_STACK_SLOT_3 6
	#endinput
#elseif _MASTER == 7
	#define _YSIM_STACK_SLOT_3 7
	#endinput
#elseif _MASTER == 8
	#define _YSIM_STACK_SLOT_3 8
	#endinput
#elseif _MASTER == 9
	#define _YSIM_STACK_SLOT_3 9
	#endinput
#elseif _MASTER == 10
	#define _YSIM_STACK_SLOT_3 10
	#endinput
#elseif _MASTER == 11
	#define _YSIM_STACK_SLOT_3 11
	#endinput
#elseif _MASTER == 12
	#define _YSIM_STACK_SLOT_3 12
	#endinput
#elseif _MASTER == 13
	#define _YSIM_STACK_SLOT_3 13
	#endinput
#elseif _MASTER == 14
	#define _YSIM_STACK_SLOT_3 14
	#endinput
#elseif _MASTER == 15
	#define _YSIM_STACK_SLOT_3 15
	#endinput
#elseif _MASTER == 16
	#define _YSIM_STACK_SLOT_3 16
	#endinput
#elseif _MASTER == 17
	#define _YSIM_STACK_SLOT_3 17
	#endinput
#elseif _MASTER == 18
	#define _YSIM_STACK_SLOT_3 18
	#endinput
#elseif _MASTER == 19
	#define _YSIM_STACK_SLOT_3 19
	#endinput
#elseif _MASTER == 20
	#define _YSIM_STACK_SLOT_3 20
	#endinput
#elseif _MASTER == 21
	#define _YSIM_STACK_SLOT_3 21
	#endinput
#elseif _MASTER == 22
	#define _YSIM_STACK_SLOT_3 22
	#endinput
#elseif _MASTER == 23
	#define _YSIM_STACK_SLOT_3 23
	#endinput
#elseif _MASTER == 24
	#define _YSIM_STACK_SLOT_3 24
	#endinput
#elseif _MASTER == 25
	#define _YSIM_STACK_SLOT_3 25
	#endinput
#elseif _MASTER == 26
	#define _YSIM_STACK_SLOT_3 26
	#endinput
#elseif _MASTER == 27
	#define _YSIM_STACK_SLOT_3 27
	#endinput
#elseif _MASTER == 28
	#define _YSIM_STACK_SLOT_3 28
	#endinput
#elseif _MASTER == 29
	#define _YSIM_STACK_SLOT_3 29
	#endinput
#elseif _MASTER == 30
	#define _YSIM_STACK_SLOT_3 30
	#endinput
#elseif _MASTER == 31
	#define _YSIM_STACK_SLOT_3 31
	#endinput
#elseif _MASTER == 32
	#define _YSIM_STACK_SLOT_3 32
	#endinput
#elseif _MASTER == 33
	#define _YSIM_STACK_SLOT_3 33
	#endinput
#elseif _MASTER == 34
	#define _YSIM_STACK_SLOT_3 34
	#endinput
#elseif _MASTER == 35
	#define _YSIM_STACK_SLOT_3 35
	#endinput
#elseif _MASTER == 36
	#define _YSIM_STACK_SLOT_3 36
	#endinput
#elseif _MASTER == 37
	#define _YSIM_STACK_SLOT_3 37
	#endinput
#elseif _MASTER == 38
	#define _YSIM_STACK_SLOT_3 38
	#endinput
#elseif _MASTER == 39
	#define _YSIM_STACK_SLOT_3 39
	#endinput
#elseif _MASTER == 40
	#define _YSIM_STACK_SLOT_3 40
	#endinput
#elseif _MASTER == 41
	#define _YSIM_STACK_SLOT_3 41
	#endinput
#elseif _MASTER == 42
	#define _YSIM_STACK_SLOT_3 42
	#endinput
#elseif _MASTER == 43
	#define _YSIM_STACK_SLOT_3 43
	#endinput
#elseif _MASTER == 44
	#define _YSIM_STACK_SLOT_3 44
	#endinput
#elseif _MASTER == 45
	#define _YSIM_STACK_SLOT_3 45
	#endinput
#elseif _MASTER == 46
	#define _YSIM_STACK_SLOT_3 46
	#endinput
#elseif _MASTER == 47
	#define _YSIM_STACK_SLOT_3 47
	#endinput
#elseif _MASTER == 48
	#define _YSIM_STACK_SLOT_3 48
	#endinput
#elseif _MASTER == 49
	#define _YSIM_STACK_SLOT_3 49
	#endinput
#elseif _MASTER == 50
	#define _YSIM_STACK_SLOT_3 50
	#endinput
#elseif _MASTER == 51
	#define _YSIM_STACK_SLOT_3 51
	#endinput
#elseif _MASTER == 52
	#define _YSIM_STACK_SLOT_3 52
	#endinput
#elseif _MASTER == 53
	#define _YSIM_STACK_SLOT_3 53
	#endinput
#elseif _MASTER == 54
	#define _YSIM_STACK_SLOT_3 54
	#endinput
#elseif _MASTER == 55
	#define _YSIM_STACK_SLOT_3 55
	#endinput
#elseif _MASTER == 56
	#define _YSIM_STACK_SLOT_3 56
	#endinput
#elseif _MASTER == 57
	#define _YSIM_STACK_SLOT_3 57
	#endinput
#elseif _MASTER == 58
	#define _YSIM_STACK_SLOT_3 58
	#endinput
#elseif _MASTER == 59
	#define _YSIM_STACK_SLOT_3 59
	#endinput
#elseif _MASTER == 60
	#define _YSIM_STACK_SLOT_3 60
	#endinput
#elseif _MASTER == 61
	#define _YSIM_STACK_SLOT_3 61
	#endinput
#elseif _MASTER == 62
	#define _YSIM_STACK_SLOT_3 62
	#endinput
#elseif _MASTER == 63
	#define _YSIM_STACK_SLOT_3 63
	#endinput
#elseif _MASTER == 64
	#define _YSIM_STACK_SLOT_3 64
	#endinput
#elseif _MASTER == 65
	#define _YSIM_STACK_SLOT_3 65
	#endinput
#elseif _MASTER == 66
	#define _YSIM_STACK_SLOT_3 66
	#endinput
#elseif _MASTER == 67
	#define _YSIM_STACK_SLOT_3 67
	#endinput
#elseif _MASTER == 68
	#define _YSIM_STACK_SLOT_3 68
	#endinput
#elseif _MASTER == 69
	#define _YSIM_STACK_SLOT_3 69
	#endinput
#elseif _MASTER == 70
	#define _YSIM_STACK_SLOT_3 70
	#endinput
#elseif _MASTER == 71
	#define _YSIM_STACK_SLOT_3 71
	#endinput
#elseif _MASTER == 72
	#define _YSIM_STACK_SLOT_3 72
	#endinput
#elseif _MASTER == 73
	#define _YSIM_STACK_SLOT_3 73
	#endinput
#elseif _MASTER == 74
	#define _YSIM_STACK_SLOT_3 74
	#endinput
#elseif _MASTER == 75
	#define _YSIM_STACK_SLOT_3 75
	#endinput
#elseif _MASTER == 76
	#define _YSIM_STACK_SLOT_3 76
	#endinput
#elseif _MASTER == 77
	#define _YSIM_STACK_SLOT_3 77
	#endinput
#elseif _MASTER == 78
	#define _YSIM_STACK_SLOT_3 78
	#endinput
#elseif _MASTER == 79
	#define _YSIM_STACK_SLOT_3 79
	#endinput
#elseif _MASTER == 80
	#define _YSIM_STACK_SLOT_3 80
	#endinput
#elseif _MASTER == 81
	#define _YSIM_STACK_SLOT_3 81
	#endinput
#elseif _MASTER == 82
	#define _YSIM_STACK_SLOT_3 82
	#endinput
#elseif _MASTER == 83
	#define _YSIM_STACK_SLOT_3 83
	#endinput
#elseif _MASTER == 84
	#define _YSIM_STACK_SLOT_3 84
	#endinput
#elseif _MASTER == 85
	#define _YSIM_STACK_SLOT_3 85
	#endinput
#elseif _MASTER == 86
	#define _YSIM_STACK_SLOT_3 86
	#endinput
#elseif _MASTER == 87
	#define _YSIM_STACK_SLOT_3 87
	#endinput
#elseif _MASTER == 88
	#define _YSIM_STACK_SLOT_3 88
	#endinput
#elseif _MASTER == 89
	#define _YSIM_STACK_SLOT_3 89
	#endinput
#elseif _MASTER == 90
	#define _YSIM_STACK_SLOT_3 90
	#endinput
#elseif _MASTER == 91
	#define _YSIM_STACK_SLOT_3 91
	#endinput
#elseif _MASTER == 92
	#define _YSIM_STACK_SLOT_3 92
	#endinput
#elseif _MASTER == 93
	#define _YSIM_STACK_SLOT_3 93
	#endinput
#elseif _MASTER == 94
	#define _YSIM_STACK_SLOT_3 94
	#endinput
#elseif _MASTER == 95
	#define _YSIM_STACK_SLOT_3 95
	#endinput
#elseif _MASTER == 96
	#define _YSIM_STACK_SLOT_3 96
	#endinput
#elseif _MASTER == 97
	#define _YSIM_STACK_SLOT_3 97
	#endinput
#elseif _MASTER == 98
	#define _YSIM_STACK_SLOT_3 98
	#endinput
#elseif _MASTER == 99
	#define _YSIM_STACK_SLOT_3 99
	#endinput
#elseif _MASTER == 100
	#define _YSIM_STACK_SLOT_3 100
	#endinput
#elseif _MASTER == 101
	#define _YSIM_STACK_SLOT_3 101
	#endinput
#elseif _MASTER == 102
	#define _YSIM_STACK_SLOT_3 102
	#endinput
#elseif _MASTER == 103
	#define _YSIM_STACK_SLOT_3 103
	#endinput
#elseif _MASTER == 104
	#define _YSIM_STACK_SLOT_3 104
	#endinput
#elseif _MASTER == 105
	#define _YSIM_STACK_SLOT_3 105
	#endinput
#elseif _MASTER == 106
	#define _YSIM_STACK_SLOT_3 106
	#endinput
#elseif _MASTER == 107
	#define _YSIM_STACK_SLOT_3 107
	#endinput
#elseif _MASTER == 108
	#define _YSIM_STACK_SLOT_3 108
	#endinput
#elseif _MASTER == 109
	#define _YSIM_STACK_SLOT_3 109
	#endinput
#elseif _MASTER == 110
	#define _YSIM_STACK_SLOT_3 110
	#endinput
#elseif _MASTER == 111
	#define _YSIM_STACK_SLOT_3 111
	#endinput
#elseif _MASTER == 112
	#define _YSIM_STACK_SLOT_3 112
	#endinput
#elseif _MASTER == 113
	#define _YSIM_STACK_SLOT_3 113
	#endinput
#elseif _MASTER == 114
	#define _YSIM_STACK_SLOT_3 114
	#endinput
#elseif _MASTER == 115
	#define _YSIM_STACK_SLOT_3 115
	#endinput
#elseif _MASTER == 116
	#define _YSIM_STACK_SLOT_3 116
	#endinput
#endif

