#undef _inc__stack_push_004

#undef _YSIM_PUSH_INDEX
#define _YSIM_PUSH_INDEX 5
#if defined _YSIM_STACK_SLOT_4
	#undef _YSIM_STACK_SLOT_4
#endif
#if     _MASTER == 0
	#define _YSIM_STACK_SLOT_4 0
	#endinput
#elseif _MASTER == 1
	#define _YSIM_STACK_SLOT_4 1
	#endinput
#elseif _MASTER == 2
	#define _YSIM_STACK_SLOT_4 2
	#endinput
#elseif _MASTER == 3
	#define _YSIM_STACK_SLOT_4 3
	#endinput
#elseif _MASTER == 4
	#define _YSIM_STACK_SLOT_4 4
	#endinput
#elseif _MASTER == 5
	#define _YSIM_STACK_SLOT_4 5
	#endinput
#elseif _MASTER == 6
	#define _YSIM_STACK_SLOT_4 6
	#endinput
#elseif _MASTER == 7
	#define _YSIM_STACK_SLOT_4 7
	#endinput
#elseif _MASTER == 8
	#define _YSIM_STACK_SLOT_4 8
	#endinput
#elseif _MASTER == 9
	#define _YSIM_STACK_SLOT_4 9
	#endinput
#elseif _MASTER == 10
	#define _YSIM_STACK_SLOT_4 10
	#endinput
#elseif _MASTER == 11
	#define _YSIM_STACK_SLOT_4 11
	#endinput
#elseif _MASTER == 12
	#define _YSIM_STACK_SLOT_4 12
	#endinput
#elseif _MASTER == 13
	#define _YSIM_STACK_SLOT_4 13
	#endinput
#elseif _MASTER == 14
	#define _YSIM_STACK_SLOT_4 14
	#endinput
#elseif _MASTER == 15
	#define _YSIM_STACK_SLOT_4 15
	#endinput
#elseif _MASTER == 16
	#define _YSIM_STACK_SLOT_4 16
	#endinput
#elseif _MASTER == 17
	#define _YSIM_STACK_SLOT_4 17
	#endinput
#elseif _MASTER == 18
	#define _YSIM_STACK_SLOT_4 18
	#endinput
#elseif _MASTER == 19
	#define _YSIM_STACK_SLOT_4 19
	#endinput
#elseif _MASTER == 20
	#define _YSIM_STACK_SLOT_4 20
	#endinput
#elseif _MASTER == 21
	#define _YSIM_STACK_SLOT_4 21
	#endinput
#elseif _MASTER == 22
	#define _YSIM_STACK_SLOT_4 22
	#endinput
#elseif _MASTER == 23
	#define _YSIM_STACK_SLOT_4 23
	#endinput
#elseif _MASTER == 24
	#define _YSIM_STACK_SLOT_4 24
	#endinput
#elseif _MASTER == 25
	#define _YSIM_STACK_SLOT_4 25
	#endinput
#elseif _MASTER == 26
	#define _YSIM_STACK_SLOT_4 26
	#endinput
#elseif _MASTER == 27
	#define _YSIM_STACK_SLOT_4 27
	#endinput
#elseif _MASTER == 28
	#define _YSIM_STACK_SLOT_4 28
	#endinput
#elseif _MASTER == 29
	#define _YSIM_STACK_SLOT_4 29
	#endinput
#elseif _MASTER == 30
	#define _YSIM_STACK_SLOT_4 30
	#endinput
#elseif _MASTER == 31
	#define _YSIM_STACK_SLOT_4 31
	#endinput
#elseif _MASTER == 32
	#define _YSIM_STACK_SLOT_4 32
	#endinput
#elseif _MASTER == 33
	#define _YSIM_STACK_SLOT_4 33
	#endinput
#elseif _MASTER == 34
	#define _YSIM_STACK_SLOT_4 34
	#endinput
#elseif _MASTER == 35
	#define _YSIM_STACK_SLOT_4 35
	#endinput
#elseif _MASTER == 36
	#define _YSIM_STACK_SLOT_4 36
	#endinput
#elseif _MASTER == 37
	#define _YSIM_STACK_SLOT_4 37
	#endinput
#elseif _MASTER == 38
	#define _YSIM_STACK_SLOT_4 38
	#endinput
#elseif _MASTER == 39
	#define _YSIM_STACK_SLOT_4 39
	#endinput
#elseif _MASTER == 40
	#define _YSIM_STACK_SLOT_4 40
	#endinput
#elseif _MASTER == 41
	#define _YSIM_STACK_SLOT_4 41
	#endinput
#elseif _MASTER == 42
	#define _YSIM_STACK_SLOT_4 42
	#endinput
#elseif _MASTER == 43
	#define _YSIM_STACK_SLOT_4 43
	#endinput
#elseif _MASTER == 44
	#define _YSIM_STACK_SLOT_4 44
	#endinput
#elseif _MASTER == 45
	#define _YSIM_STACK_SLOT_4 45
	#endinput
#elseif _MASTER == 46
	#define _YSIM_STACK_SLOT_4 46
	#endinput
#elseif _MASTER == 47
	#define _YSIM_STACK_SLOT_4 47
	#endinput
#elseif _MASTER == 48
	#define _YSIM_STACK_SLOT_4 48
	#endinput
#elseif _MASTER == 49
	#define _YSIM_STACK_SLOT_4 49
	#endinput
#elseif _MASTER == 50
	#define _YSIM_STACK_SLOT_4 50
	#endinput
#elseif _MASTER == 51
	#define _YSIM_STACK_SLOT_4 51
	#endinput
#elseif _MASTER == 52
	#define _YSIM_STACK_SLOT_4 52
	#endinput
#elseif _MASTER == 53
	#define _YSIM_STACK_SLOT_4 53
	#endinput
#elseif _MASTER == 54
	#define _YSIM_STACK_SLOT_4 54
	#endinput
#elseif _MASTER == 55
	#define _YSIM_STACK_SLOT_4 55
	#endinput
#elseif _MASTER == 56
	#define _YSIM_STACK_SLOT_4 56
	#endinput
#elseif _MASTER == 57
	#define _YSIM_STACK_SLOT_4 57
	#endinput
#elseif _MASTER == 58
	#define _YSIM_STACK_SLOT_4 58
	#endinput
#elseif _MASTER == 59
	#define _YSIM_STACK_SLOT_4 59
	#endinput
#elseif _MASTER == 60
	#define _YSIM_STACK_SLOT_4 60
	#endinput
#elseif _MASTER == 61
	#define _YSIM_STACK_SLOT_4 61
	#endinput
#elseif _MASTER == 62
	#define _YSIM_STACK_SLOT_4 62
	#endinput
#elseif _MASTER == 63
	#define _YSIM_STACK_SLOT_4 63
	#endinput
#elseif _MASTER == 64
	#define _YSIM_STACK_SLOT_4 64
	#endinput
#elseif _MASTER == 65
	#define _YSIM_STACK_SLOT_4 65
	#endinput
#elseif _MASTER == 66
	#define _YSIM_STACK_SLOT_4 66
	#endinput
#elseif _MASTER == 67
	#define _YSIM_STACK_SLOT_4 67
	#endinput
#elseif _MASTER == 68
	#define _YSIM_STACK_SLOT_4 68
	#endinput
#elseif _MASTER == 69
	#define _YSIM_STACK_SLOT_4 69
	#endinput
#elseif _MASTER == 70
	#define _YSIM_STACK_SLOT_4 70
	#endinput
#elseif _MASTER == 71
	#define _YSIM_STACK_SLOT_4 71
	#endinput
#elseif _MASTER == 72
	#define _YSIM_STACK_SLOT_4 72
	#endinput
#elseif _MASTER == 73
	#define _YSIM_STACK_SLOT_4 73
	#endinput
#elseif _MASTER == 74
	#define _YSIM_STACK_SLOT_4 74
	#endinput
#elseif _MASTER == 75
	#define _YSIM_STACK_SLOT_4 75
	#endinput
#elseif _MASTER == 76
	#define _YSIM_STACK_SLOT_4 76
	#endinput
#elseif _MASTER == 77
	#define _YSIM_STACK_SLOT_4 77
	#endinput
#elseif _MASTER == 78
	#define _YSIM_STACK_SLOT_4 78
	#endinput
#elseif _MASTER == 79
	#define _YSIM_STACK_SLOT_4 79
	#endinput
#elseif _MASTER == 80
	#define _YSIM_STACK_SLOT_4 80
	#endinput
#elseif _MASTER == 81
	#define _YSIM_STACK_SLOT_4 81
	#endinput
#elseif _MASTER == 82
	#define _YSIM_STACK_SLOT_4 82
	#endinput
#elseif _MASTER == 83
	#define _YSIM_STACK_SLOT_4 83
	#endinput
#elseif _MASTER == 84
	#define _YSIM_STACK_SLOT_4 84
	#endinput
#elseif _MASTER == 85
	#define _YSIM_STACK_SLOT_4 85
	#endinput
#elseif _MASTER == 86
	#define _YSIM_STACK_SLOT_4 86
	#endinput
#elseif _MASTER == 87
	#define _YSIM_STACK_SLOT_4 87
	#endinput
#elseif _MASTER == 88
	#define _YSIM_STACK_SLOT_4 88
	#endinput
#elseif _MASTER == 89
	#define _YSIM_STACK_SLOT_4 89
	#endinput
#elseif _MASTER == 90
	#define _YSIM_STACK_SLOT_4 90
	#endinput
#elseif _MASTER == 91
	#define _YSIM_STACK_SLOT_4 91
	#endinput
#elseif _MASTER == 92
	#define _YSIM_STACK_SLOT_4 92
	#endinput
#elseif _MASTER == 93
	#define _YSIM_STACK_SLOT_4 93
	#endinput
#elseif _MASTER == 94
	#define _YSIM_STACK_SLOT_4 94
	#endinput
#elseif _MASTER == 95
	#define _YSIM_STACK_SLOT_4 95
	#endinput
#elseif _MASTER == 96
	#define _YSIM_STACK_SLOT_4 96
	#endinput
#elseif _MASTER == 97
	#define _YSIM_STACK_SLOT_4 97
	#endinput
#elseif _MASTER == 98
	#define _YSIM_STACK_SLOT_4 98
	#endinput
#elseif _MASTER == 99
	#define _YSIM_STACK_SLOT_4 99
	#endinput
#elseif _MASTER == 100
	#define _YSIM_STACK_SLOT_4 100
	#endinput
#elseif _MASTER == 101
	#define _YSIM_STACK_SLOT_4 101
	#endinput
#elseif _MASTER == 102
	#define _YSIM_STACK_SLOT_4 102
	#endinput
#elseif _MASTER == 103
	#define _YSIM_STACK_SLOT_4 103
	#endinput
#elseif _MASTER == 104
	#define _YSIM_STACK_SLOT_4 104
	#endinput
#elseif _MASTER == 105
	#define _YSIM_STACK_SLOT_4 105
	#endinput
#elseif _MASTER == 106
	#define _YSIM_STACK_SLOT_4 106
	#endinput
#elseif _MASTER == 107
	#define _YSIM_STACK_SLOT_4 107
	#endinput
#elseif _MASTER == 108
	#define _YSIM_STACK_SLOT_4 108
	#endinput
#elseif _MASTER == 109
	#define _YSIM_STACK_SLOT_4 109
	#endinput
#elseif _MASTER == 110
	#define _YSIM_STACK_SLOT_4 110
	#endinput
#elseif _MASTER == 111
	#define _YSIM_STACK_SLOT_4 111
	#endinput
#elseif _MASTER == 112
	#define _YSIM_STACK_SLOT_4 112
	#endinput
#elseif _MASTER == 113
	#define _YSIM_STACK_SLOT_4 113
	#endinput
#elseif _MASTER == 114
	#define _YSIM_STACK_SLOT_4 114
	#endinput
#elseif _MASTER == 115
	#define _YSIM_STACK_SLOT_4 115
	#endinput
#elseif _MASTER == 116
	#define _YSIM_STACK_SLOT_4 116
	#endinput
#endif

